### ISSUE TITLE
FAIL: test_quickened_static_code_gets_unquickened_at_Py_FINALIZE

### ISSUE THREAD

**Issue by fabiounixpi** [python/cpython#100225]
# Bug report

Compiling Python 3.11.1 from source code, on AlmaLinux 8.7 (fully updated), issuing
  $ make test
it stop with

```
...
stderr:
--- Loop #1 ---
Traceback (most recent call last):
  File "<string>", line 8, in <module>
AssertionError

------
FAIL

======================================================================
FAIL: test_quickened_static_code_gets_unquickened_at_Py_FINALIZE (test.test_embed.EmbeddingTests.test_quickened_static_code_gets_unquickened_at_Py_FINALIZE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/sorgenti/Python-3.11.1/Lib/test/test_embed.py", line 381, in test_quickened_static_code_gets_unquickened_at_Py_FINALIZE
    out, err = run("test_repeated_init_exec", code)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/sorgenti/Python-3.11.1/Lib/test/test_embed.py", line 115, in run_embedded_interpreter
    self.assertEqual(p.returncode, returncode,
AssertionError: 1 != 0 : bad returncode 1, stderr is '--- Loop #1 ---\nTraceback (most recent call last):\n  File "<string>", line 8, in <module>\nAssertionError\n'

----------------------------------------------------------------------
Ran 1 test in 0.021s

FAILED (failures=1)
test test_embed failed
0:02:21 load avg: 2.47 Re-running test_tools in verbose mode (matching: test_freeze_simple_script)
test_freeze_simple_script (test.test_tools.test_freeze.TestFreeze.test_freeze_simple_script) ... creating the script to be frozen at /tmp/tmp7zgf8ru6/app.py
copying the source tree into /tmp/tmp7zgf8ru6/cpython...
configuring python in /tmp/tmp7zgf8ru6/python-build...
building python in /tmp/tmp7zgf8ru6/python-build...
installing python into /tmp/tmp7zgf8ru6/python-installation...
freezing /tmp/tmp7zgf8ru6/app.py...
ok

----------------------------------------------------------------------
Ran 1 test in 86.208s

OK
1 test failed again:
    test_embed

== Tests result: FAILURE then FAILURE ==

418 tests OK.

1 test failed:
    test_embed

15 tests skipped:
    test_devpoll test_gdb test_ioctl test_kqueue test_launcher
    test_msilib test_ossaudiodev test_startfile test_tix test_tk
    test_ttk_guionly test_winconsoleio test_winreg test_winsound
    test_zipfile64

2 re-run tests:
    test_embed test_tools

Total duration: 3 min 48 sec
Tests result: FAILURE then FAILURE
make: *** [Makefile:1815: test] Error 2

```

# Your environment

- CPython versions tested on: Python 3.11.1
- Operating system and architecture: AlmaLinux 8.7 x86_64
- Build options:  ./configure --enable-shared --enable-optimizations

**Comment by sobolevn** [comment]
This test is now removed in 3.12
But, the problem might actually still exist or it might be just a flaky test.

Source for the removed failing test: https://github.com/python/cpython/blob/4b4e6da7b53f9eb2d3654d321f6acfbd599bd990/Lib/test/test_embed.py#L350-L382

@fabiounixpi can you please try `main` branch? Will it still fail for you?

**Comment by brandtbucher** [comment]
The test wasn't really *removed*, we just renamed it and updated it for [changes to how quickening works](https://github.com/python/cpython/pull/98687/files#diff-573be25566e43f5adc6650ad1b58d106dbbd79521cb9c6e6d5df9588616a1ffd). The old test isn't valid anymore, and likely raises on line 8 (like the issue shows) if run under 3.12.

**Comment by vstinner** [comment]
No activity for 2 years, I close the issue. Please reopen the issue if you can still reproduce the `test_embed` failure on a recent Python version (ex: Python 3.14).
