### ISSUE TITLE
Exception thrown when using python in for-loop in C++-script

### ISSUE THREAD

**Issue by jhaggle** [python/cpython#100395]
I have a C++ script that I run in Visual studio 2022 on windows 10 and where I include the python module. In the code I import numpy in a for-loop. The code executes fine the first round, but in the second round and exception is thrown as soon as the code tries to execute the import statement. I have googled for the error and searched for similar issues on stackOverflow but not found any solution. I have also isolated the error and made a minimal example. Here is the code from the example:

```
#include <C:\Program Files\Python39\include\Python.h>
#include <iostream>

using namespace std;

int main() {

	for (int i = 0; i < 5; i++) {
		cout << i << endl;

		Py_Initialize();
		PyRun_SimpleString("import numpy as np"); 
		PyRun_SimpleString("arr = np.array([1,2,3])");
		PyRun_SimpleString("print(arr)");
		Py_Finalize();

	}
}

```

This is the output from the console when running the code:

```
0
[1 2 3]
1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
```

Here is the error message in visual studio:

```
Exception thrown at 0x00007FFCB9461319 (_multiarray_umath.cp39-win_amd64.pyd) in App4.exe: 0xC0000005: Access violation writing location 0x0000000000000008.
```

What could be going on here and how can I solve it?

**Comment by ericvsmith** [comment]
Please include a stack dump when it fails.

**Comment by ronaldoussoren** [comment]
On macOS I get the following stack trace with a trivial change to the program:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
  * frame #0: 0x000000010311de84 _multiarray_umath.cpython-311-darwin.so`PyArray_Item_INCREF + 64
    frame #1: 0x000000010312100c _multiarray_umath.cpython-311-darwin.so`PyArray_FromScalar + 232
    frame #2: 0x0000000103129ed4 _multiarray_umath.cpython-311-darwin.so`gentype_nonzero_number + 20
    frame #3: 0x0000000100fe5ff4 Python`_PyEval_EvalFrameDefault + 41164
    frame #4: 0x0000000100fee89c Python`_PyEval_Vector + 156
    frame #5: 0x0000000100ec7450 Python`_PyObject_CallFunctionVa + 152
    frame #6: 0x0000000100ec7944 Python`PyObject_CallMethod + 96
    frame #7: 0x0000000101048100 Python`pycore_interp_init + 5300
    frame #8: 0x0000000101046870 Python`Py_InitializeFromConfig + 860
    frame #9: 0x000000010104ae08 Python`Py_InitializeEx + 292
    frame #10: 0x0000000100003c84 t`main at t.cc:11:3 [opt]
    frame #11: 0x000000018eb73e50 dyld`start + 2544
```

With the following output just before the crash:

```
0
[1 2 3]
1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ronald/Projects/pyobjc-8/pyobjc-core/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/Users/ronald/Projects/pyobjc-8/pyobjc-core/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/Users/ronald/Projects/pyobjc-8/pyobjc-core/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/Users/ronald/Projects/pyobjc-8/pyobjc-core/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
SystemError: /Users/sysadmin/build/v3.11.1/Objects/structseq.c:476: bad argument to internal function
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'np' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'arr' is not defined
2
Process 18482 stopped
```

This is likely a problem in numpy, the extension module might not clean up on interpreter shutdown and reuse an object from the first iteration in a later iteration.

**Comment by kumaraditya303** [comment]
On 3.10 I get the following output:
```console
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/home/codespace/.python/current/bin/python3"
  * The NumPy version is: "1.23.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
```

You should report this to numpy, I'll close as this is not a bug in Python.
