### ISSUE TITLE
You don't need to raise NotImplementedError for abstract methods

### ISSUE THREAD

**Issue by Xophmeister** [python/cpython#100400]
# Documentation

In the documentation for `NotImplementedError`, we see the following:

https://github.com/python/cpython/blob/a7715ccfba5b86ab09f86ec56ac3755c93b46b48/Doc/library/exceptions.rst?plain=1#L299-L304

If "abstract base classes" are meant to mean ABCs from the standard library, this is unnecessary as the ABC metaclass will prohibit instantiation of any derived class that doesn't implement an abstract method. Indeed, adding a `raise` would be dead code that would flaunt, say, coverage metrics.

**Comment by stevendaprano** [comment]
I think the purpose of raising NotImplementedError is to protect against calling the abstract method from the class like this:

```
>>> from abc import ABC, abstractmethod
>>> 
>>> class Animal(ABC):
...     @abstractmethod
...     def move(self):
...         raise NotImplementedError
... 
>>> class Human(Animal):
...     def move(self):
...         print("human move")
... 
>>> Animal.move(Human())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in move
NotImplementedError
```

If we removed the `NotImplementedError`, calling the abstract `move` method would silently do nothing.

I think the statement should stay, or even be made more prominent in the docs. I see lots of abstract methods which wrongly (in my opinion) just have `pass` as the body.

Does anyone know whether linters check for this?

**Comment by sobolevn** [comment]
I cannoy say for all linters, but mypy does not catch it.

**Comment by cameron-simpson** [comment]
(a) I think `NotImplementedError` _predates_ `ABC` and `abstractmethod`.
(b) you can implement a "abstract" class semanticly without `ABC`, and if you do then `NotImplementedError` is that way to ensure that your abstract method is meaningfully unworkable

It probably would be sensible to clarify the distinction between this mechanism (`NotImplementedError`) which would fire at runtime and the `ABC` metaclass mechanism which fires at class definition time.

But it's still reasonable to have an `abstractmethod`'s _code_ be `raise NotImplementedError` to make the situation really clear, not to mention aiding a linter unaware of `abstractmethod` specificly, but aware of unconditional `raise` results.

**Comment by Xophmeister** [comment]
It's worth pointing out that the documentation for `abc.abstractmethod` doesn't mention using `NotImplementedError` and uses ellipses in its examples. It's therefore not surprising that this is what is usually seen in the wild:

https://github.com/python/cpython/blob/84bc6a4f25fcf467813ee12b74118f7b1b54e285/Doc/library/abc.rst?plain=1#L165-L237

To add to the linter evidence: Pylint also doesn't catch this.

The valid reasons for raising here are thus:
1. If you are implementing a base class/abstract method manually, without ABC's help.
2. If you routinely call base class methods (not `@classmethod`s) against instantiated objects. (i.e., Presumably in inheritance situations, when `super` doesn't cut it.)
3. For documentation/signalling purposes.
