### ISSUE TITLE
Source Checkout Installs With Unparseable Version

### ISSUE THREAD

**Issue by xloem** [python/cpython#100531]
```
git clone https://github.com/python/cpython
cd cpython
git checkout 3.9 # i think 3.10 has it too, not certain
./configure && make && sudo make install
python3 -c 'import packaging.version, platform; packaging.version.parse(platform.python_version())'
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.local/lib/python3.9/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/user/.local/lib/python3.9/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '3.9.16+'
```

**Comment by ronaldoussoren** [comment]
This is a duplicate of #99968.

**Comment by xloem** [comment]
Thank you.
