### ISSUE TITLE
`f(kw=a, *b)` with keyword argument before star arguments isn’t evaluated left-to-right

### ISSUE THREAD

**Issue by andersk** [python/cpython#100549]
```python
def f(a, kw):
    pass

f(kw=print(1), *[print(2)])
```

In Python 3.4.10 and earlier, this prints `1` then `2`, but in Python 3.5.0 and later, this prints `2` then `1`.

This seems like a bug of some kind. Given that `ast.parse()` doesn’t distinguish between `f(kw=a, *b)` and `f(*b, kw=a)`, perhaps the bug is that a keyword argument is allowed before star arguments at all—we already disallow `f(kw=a, b)`, `f(**a, b)`, and `f(**a, *b)`.

**Comment by sobolevn** [comment]
Moreover, for non-kw-only argument, it is not even allowed in runtime to do this:

```python
>>> def func(a, b, c):
...    print(a, b, c)
... 
>>> func(a=1, *[2, 3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: func() got multiple values for argument 'a'
>>> func(b=1, *[2, 3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: func() got multiple values for argument 'b'
>>> func(c=1, *[2, 3])
2 3 1
```

**Comment by pochmann** [comment]
Works [as documented](https://docs.python.org/3/reference/expressions.html#calls), no?

> although the `*expression` syntax may appear after explicit keyword arguments, it is processed *before* the keyword arguments

**Comment by sobolevn** [comment]
> It is unusual for both keyword arguments and the *expression syntax to be used in the same call, so in practice this confusion does not often arise.

@andersk do you have any practical cases that you can show? :)

**Comment by andersk** [comment]
That documentation sentence is unchanged since [Python 2.2](https://docs.python.org/release/2.2/ref/calls.html), which evaluated keyword arguments before star arguments like 3.4.10 and earlier.

```pycon
Python 2.2.3+ (#1, Sep  4 2005, 21:50:09) 
[GCC 3.3.5 (Debian 1:3.3.5-13)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> def f(a, kw):
...     pass
... 
>>> def p(a):
...     print a
... 
>>> f(kw=p(1), *[p(2)])
1
2
```

The example below that sentence makes it clear that it wasn’t referring to the evaluation order, but rather the order in which the arguments are mapped to parameters.

I don’t have a practical use case (just a highly [impractical one](https://github.com/csvoss/onelinerizer/blob/bad341f261d35e56872b4c22297a44dc6d5cfab3/onelinerizer/onelinerizer.py#L640-L641) in Python 2), which is why my proposal was to disallow this confusing syntax. Maybe that’s an overreaction—would a `SyntaxWarning` be appropriate?

**Comment by sobolevn** [comment]
I think for such a massive thing starting a new discussion on https://discuss.python.org/ is adviced!
