### ISSUE TITLE
mock.patch cannot import an invalid-name module in >=3.11 due to importlib.import_module vs pkgutil.resolve_name differences when module has a dash in its filename

### ISSUE THREAD

**Issue by terceiro** [python/cpython#100950]
# Bug report

`importlib.import_module()` and `pkgutil.resolve_name()` are inconsistent with regards to which formats they accept. For example, if I have a module that contains a dash (-) in its filename (for example in a Django management command), `importlib.import_module()` is able to import the module just fine, while `pkgutil.resolve_name()` will raise an exception about an invalid format.

Minimal reproducer (all files are empty):

```
$ find . -name \*.py
./foobar/__init__.py
./foobar/foo-bar.py
$ python3 -c 'import importlib; importlib.import_module("foobar.foo-bar")'
$ python3 -c 'import pkgutil; pkgutil.resolve_name("foobar.foo-bar")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/pkgutil.py", line 687, in resolve_name
    raise ValueError(f'invalid format: {name!r}')
ValueError: invalid format: 'foobar.foo-bar'
```
I would expect those to be consistent in the format they accept, i.e. accept and reject the same inputs.
My current actual problem is that `unittest.mock.patch` uses `pkgutil.resolve_name()` in Python 3.11 (but not in Python 3.10), what means that one cannot easily patch a function inside a Django management command module that contains a dash.

# Your environment

Tested on Debian testing amd64 (x86_64) as of today, with both python 3.11.1 and 3.9.10.

**Comment by gpshead** [comment]
pkgutil.resolve_name's behavior seems correct, that is not a resolvable module name. No naturally importable module can be an invalid Python identifier.  pkgutil.resolve_name's documentation agrees. https://docs.python.org/3/library/pkgutil.html#pkgutil.resolve_name

I would not _expect_ `mock.patch` to import invalid names. But that it happened to before and no longer does sounds like a potentially unintentional behavior change.

Possible workaround: You can import dash-named code using `importlib.import_module` to get a module object for it and `unittest.mock.patch.object()` on that. Though check if a future call to `importlib.import_module` on the same dash-named code returns the same module object or a new effectively reload()ed one. If so you may need to ensure you do your testing via the instance your import_module call used in order to see the mocks in place.

**Comment by terceiro** [comment]
> Possible workaround: You can import dash-named code using `importlib.import_module` to get a module object for it and `unittest.mock.patch.object()` on that.

yes, that is exactly what [I did](https://git.lavasoftware.org/lava/lava/-/commit/e9179d68a1bbd8d7aa7103a173c650d989ee830e), FWIW. thanks for the feedback.
