### ISSUE TITLE
issubclass() is inconsistent with generic aliases

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#101162]
Instances of `types.GenericAlias` are accepted as the first argument of `issubclass()`:

```pycon
>>> issubclass(list[int], object)
True
>>> issubclass(list[int], type)
False
```
while instances of `typing.GenericAlias` are not:

```pycon
>>> issubclass(typing.List[int], object)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: issubclass() arg 1 must be a class
>>> issubclass(typing.List[int], type)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: issubclass() arg 1 must be a class
```
Although both are rejected if the second argument is an abstract class:
```pycon
>>> issubclass(list[int], collections.abc.Sequence)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/py/cpython/Lib/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
>>> issubclass(typing.List[int], collections.abc.Sequence)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/py/cpython/Lib/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
```

Usually `issubclass(x, y)` is preceded by the check `isinstance(x, type)`, so the final result will always be false since 3.11, but if that check is omitted, you can see a difference.

### Linked PRs
* gh-103369

**Comment by sobolevn** [comment]
This happens because `PyObject_IsSubclass` uses `abstract_get_bases` which returns `(object,)` for `list[int]`, but raises an error for `typing.List[int]`:

```python
>>> list[int].__bases__
(<class 'object'>,)
>>> import typing
>>> typing.List[int].__bases__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sobolev/Desktop/cpython/Lib/typing.py", line 1307, in __getattr__
    raise AttributeError(attr)
AttributeError: __bases__. Did you mean: '__args__'?
```

But, we can easily change this and forbid `__bases__` access for `types.GenericAlias` objects by adding it to `attr_exceptions`.

As the result, everything is going to work the same as `typing._GenericAlias`:

```python
>>> list[int].__bases__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: __bases__. Did you mean: '__args__'?

>>> issubclass(list[int], object)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: issubclass() arg 1 must be a class
```

Moreover, all typing/types/genericalias tests pass with this change. 
I think that it is a reasonable thing to do. Because `GenericAlias` already has `__mro_entries__` method and exposing `__bases__` does not actually solve any problems as far as I know.
