### ISSUE TITLE
invalid signature for math.hypot

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#101123]
```python
>>> import math
>>> import inspect
>>> inspect.signature(math.hypot) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sk/src/cpython/Lib/inspect.py", line 3295, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sk/src/cpython/Lib/inspect.py", line 3039, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sk/src/cpython/Lib/inspect.py", line 2531, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sk/src/cpython/Lib/inspect.py", line 2330, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in function hypot>
```

This patch works:
```diff
diff --git a/Modules/mathmodule.c b/Modules/mathmodule.c
index 1342162fa7..0e610eb9cb 100644
--- a/Modules/mathmodule.c
+++ b/Modules/mathmodule.c
@@ -2805,7 +2805,9 @@ math_hypot(PyObject *self, PyObject *const *args, Py_ssize_t nargs)
 #undef NUM_STACK_ELEMS
 
 PyDoc_STRVAR(math_hypot_doc,
-             "hypot(*coordinates) -> value\n\n\
+             "hypot($module, *coordinates)\n\
+--\n\
+\n\
 Multidimensional Euclidean distance from the origin to a point.\n\
 \n\
 Roughly equivalent to:\n\
```

### Linked PRs
* gh-101124
* gh-126235

**Comment by rhettinger** [comment]
We don't have a rule that all docstrings have to be in a format edible by inspect?   There are many docstrings that don't.  This is just a simple `*args*` function and I would rather not garbage-up the docstring with the funky looking text_signature notation.

**Comment by skirpichev** [comment]
> This is just a simple *args* function and I would rather not garbage-up the docstring with the funky looking text_signature notation.

@rhettinger, could you explain a bit more what it does break?

Here is how new docstring looks (just like other similar functions in the module, e.g. gcd and lcm, and how the rst docs for the hypot looks too):
```
>>> help(math.hypot)
Help on built-in function hypot in module math:

hypot(*coordinates)
    Multidimensional Euclidean distance from the origin to a point.

    Roughly equivalent to:
        sqrt(sum(x**2 for x in coordinates))

    For a two dimensional point (x, y), gives the hypotenuse
    using the Pythagorean theorem:  sqrt(x*x + y*y).

    For example, the hypotenuse of a 3/4/5 right triangle is:

        >>> hypot(3.0, 4.0)
        5.0

```
Here is the old:
```
>>> help(math.hypot)
Help on built-in function hypot in module math:

hypot(...)
    hypot(*coordinates) -> value

    Multidimensional Euclidean distance from the origin to a point.

    Roughly equivalent to:
        sqrt(sum(x**2 for x in coordinates))

    For a two dimensional point (x, y), gives the hypotenuse
    using the Pythagorean theorem:  sqrt(x*x + y*y).

    For example, the hypotenuse of a 3/4/5 right triangle is:

        >>> hypot(3.0, 4.0)
        5.0
```

**Comment by skirpichev** [comment]
FYI: AC stuff is fast with #30312.

**Comment by skirpichev** [comment]
@rhettinger, I'll reopen this as a feature request.

AC now supports \*args processing, but it's coming with a slight performance penalty.  One can be mitigated, using approach from #90370; I'm working on patch.  With this, gcd/lcm could be converted to AC too (now these functions use "funky looking text_signature notation" (c) in docstrings).

**Comment by skirpichev** [comment]
#126064 should fix this
