### ISSUE TITLE
Regression in Python 3.11 when explicitly passing None to FutureIter.throw

### ISSUE THREAD

**Issue by hauntsaninja** [python/cpython#101326]
Reported and commit identified by @alicederyn in https://github.com/python/typeshed/issues/9586

Regression caused by https://github.com/python/cpython/pull/31973. Doesn't contain a news entry, so probably not intentional.

```
λ cat xxx.py
import asyncio
async def f():
  await asyncio.sleep(0)
async def g():
  await asyncio.gather(f(), f())

h = g()
h.send(None)
print(type(h))
h.throw(ValueError("some error"), None, None)

λ python3.10 xxx.py
/Users/shantanu/dev/cpython/xxx.py:5: DeprecationWarning: There is no current event loop
  await asyncio.gather(f(), f())
<class 'coroutine'>
Traceback (most recent call last):
  File "/Users/shantanu/dev/cpython/xxx.py", line 10, in <module>
    h.throw(ValueError("some error"), None, None)
  File "/Users/shantanu/dev/cpython/xxx.py", line 5, in g
    await asyncio.gather(f(), f())
ValueError: some error

λ python3.11 xxx.py
/Users/shantanu/dev/cpython/xxx.py:5: DeprecationWarning: There is no current event loop
  await asyncio.gather(f(), f())
<class 'coroutine'>
Traceback (most recent call last):
  File "/Users/shantanu/dev/cpython/xxx.py", line 10, in <module>
    h.throw(ValueError("some error"), None, None)
  File "/Users/shantanu/dev/cpython/xxx.py", line 5, in g
    await asyncio.gather(f(), f())
TypeError: throw() third argument must be a traceback
```

### Linked PRs
* gh-101327
* gh-101328

**Comment by hauntsaninja** [comment]
cc @asvetlov @kumaraditya303

**Comment by hauntsaninja** [comment]
Thanks @alicederyn!

**Comment by alicederyn** [comment]
Thanks @hauntsaninja! Amazing turnaround!
