### ISSUE TITLE
os.walk() silent about non-directory

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#101420]
`os.walk()` silently produces an empty iterator if the argument  is not a path to directory:

```pycon
>>> import os
>>> list(os.walk('./non-existing'))
[]
>>> list(os.walk('./python'))
[]
>>> list(os.walk('/dev/null'))
[]
```

It can causes bugs like #99203, when a function produces some incorrect result instead of raising an exception.

**Comment by serhiy-storchaka** [comment]
Note that `os.fwalk()` raises an exception for non-existing entity, but not for file.
```pycon
>>> list(os.fwalk('./non-existing'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/py/cpython/Lib/os.py", line 475, in fwalk
    orig_st = stat(top, follow_symlinks=False, dir_fd=dir_fd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './non-existing'
>>> list(os.fwalk('./python'))
[]
```

`glob()` also produces an empty result:
```pycon
>>> glob.glob('./non-existing/*')
[]
>>> glob.glob('./python/*')
[]
```

**Comment by achhina** [comment]
I would like to work on this.

@serhiy-storchaka what do you think the expected behavior for this should be? Looking at the [docs](https://docs.python.org/3/library/os.html#os.fwalk), it seems to imply `os.fwalk` should mimic `os.walk`, however I agree that silently producing an iterator is probably not the best way to deal with this. Also, would there be any backward compatibility concerns for folks who are relying on this feature in `os.walk`, if we decide to modify it?
