### ISSUE TITLE
using a staticmethod decorator inside a subclass

### ISSUE THREAD

**Issue by nschloe** [python/cpython#101781]
A `staticmethod` can be used to decorate other class methods:
```python
class A:
    @staticmethod
    def mydecorator(func):
        print("a")
        return func

    @mydecorator
    def foo(self):
        return

A().foo()
```
```
a
```

Using the decorator inside a subclass does not work:
```python
class A:
    @staticmethod
    def mydecorator(func):
        return func

    class B:
        @mydecorator
        def foo(self):
            return

A()
```
```
Traceback (most recent call last):
  File "/tmp/e.py", line 1, in <module>
    class A:
  File "/tmp/e.py", line 7, in A
    class B:
  File "/tmp/e.py", line 8, in B
    @mydecorator
     ^^^^^^^^^^^
NameError: name 'mydecorator' is not defined
```

A bug?

This is with
```
python --version
```
```
Python 3.11.1
```

**Comment by sobolevn** [comment]
This is just how scoping works in python. Names are visible in the class itself, but not in nested classes.

For example, this works:

```python
>>> class A:
...   a = 1
...   b = a
```

This does not work:

```python
>>> class A:
...   a = 1
...   b = a
...   class B:
...      inner = a
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in A
  File "<stdin>", line 5, in B
NameError: name 'a' is not defined
```

But, you can use full names:

```python
>>> class A:
...    a = 1
...    class B:
...       b = A.a
... 
>>> A.B.b
1
```

I am going to close this issue, because it is not really an issue, as far as I understand :)

**Comment by nschloe** [comment]
Thanks for the explanation.
