### ISSUE TITLE
[unittest.mock] `spec_set` should be applied after setting attributes via kwargs

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/cpython#101756]
```pytb
>>> a=create_autospec("foo", spec_set=True, banana=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/unittest/mock.py", line 2607, in create_autospec
    mock = Klass(parent=_parent, _new_parent=_parent, _new_name=_new_name,
  File "/usr/lib/python3.8/unittest/mock.py", line 2006, in __init__
    _safe_super(MagicMixin, self).__init__(*args, **kw)
  File "/usr/lib/python3.8/unittest/mock.py", line 460, in __init__
    self.configure_mock(**kwargs)
  File "/usr/lib/python3.8/unittest/mock.py", line 629, in configure_mock
    setattr(obj, final, val)
  File "/usr/lib/python3.8/unittest/mock.py", line 744, in __setattr__
    raise AttributeError("Mock object has no attribute '%s'" % name)
AttributeError: Mock object has no attribute 'banana'
```

One reason to pass extra kwargs to `create_autospec()` like this is to set missing attributes (e.g. because you know that they get set dynamically later on). So, it would be nice to have those attributes set on the mock before `spec_set` comes into effect.

**Comment by tirkarthi** [comment]
Mock doesn't allow passing arbitrary arguments when `spec` and `spec_set=True` are passed. So this is not something related only to `create_autospec`. A simpler approach would be to create the mock with additional attributes and then use `mock_add_spec` to configure spec and spec_set. I searched the previous issues and don't find any similar issues/suggestions reported.

```
>>> from unittest.mock import Mock
>>> def foo(): pass
>>> m = Mock(banana=1) # create with extra attribute 
>>> m.__qualname__ # __qualname__ doesn't exist yet but will once we add foo function as spec later
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/karthikeyan/stuff/python/cpython/Lib/unittest/mock.py", line 654, in __getattr__
    raise AttributeError(name)
AttributeError: __qualname__
>>> m.banana
1
>>> m.mock_add_spec(foo, spec_set=True)
>>> m.__qualname__
<Mock name='mock.__qualname__' id='140394879153504'>
>>> m.spam = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/karthikeyan/stuff/python/cpython/Lib/unittest/mock.py", line 768, in __setattr__
    raise AttributeError("Mock object has no attribute '%s'" % name)
AttributeError: Mock object has no attribute 'spam'
```

With respect to create_autospec in your example you can try passing the extra attribute and then later add `spec_set` using `mock_add_spec`. Note that string is used here as spec here and in case you use a function foo then you can access the mock using `a.mock` to use `mock_add_spec`.

```
>>> a = create_autospec("foo", banana=1)
>>> a.banana
1
>>> a.spam = 1
>>> a.mock_add_spec("foo", spec_set=True)
>>> a.spam = 2 # can still set the attribute since it was set before spec_set=True
>>> a.spam
2
>>> a.eggs = 2 # new attributes are not allowed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/karthikeyan/stuff/python/cpython/Lib/unittest/mock.py", line 768, in __setattr__
    raise AttributeError("Mock object has no attribute '%s'" % name)
AttributeError: Mock object has no attribute 'eggs'
```

**Comment by Dreamsorcerer** [comment]
That's a reasonable workaround for current releases, but would still be nice to be able to set them at the same time as spec_set in future.
