### ISSUE TITLE
Pure-python version of `collections._tuplegetter` is not picklable

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#101785]
Right now here's how `_tuplegetter` is defined: https://github.com/python/cpython/blob/826bf0e6957fd0addc321d1baee1fa846e9457eb/Lib/collections/__init__.py#L343-L346

Luckly, we (almost) never miss `_collections` module, since it is a part of the stdlib.
But, in case we theoretically cannot import `_tuplegetter` from `_collections`, we have several test failures:

```pytb
======================================================================
ERROR: test_field_descriptor (test.test_collections.TestNamedTuple.test_field_descriptor) (proto=0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 690, in test_field_descriptor
    class NewPoint(tuple):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 691, in NewPoint
    x = pickle.loads(pickle.dumps(Point.x, proto))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython/Lib/copyreg.py", line 70, in _reduce_ex
    raise TypeError(f"cannot pickle {cls.__name__!r} object")
TypeError: cannot pickle 'property' object

======================================================================
ERROR: test_field_descriptor (test.test_collections.TestNamedTuple.test_field_descriptor) (proto=1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 690, in test_field_descriptor
    class NewPoint(tuple):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 691, in NewPoint
    x = pickle.loads(pickle.dumps(Point.x, proto))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython/Lib/copyreg.py", line 70, in _reduce_ex
    raise TypeError(f"cannot pickle {cls.__name__!r} object")
TypeError: cannot pickle 'property' object

======================================================================
ERROR: test_field_descriptor (test.test_collections.TestNamedTuple.test_field_descriptor) (proto=2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 690, in test_field_descriptor
    class NewPoint(tuple):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 691, in NewPoint
    x = pickle.loads(pickle.dumps(Point.x, proto))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'property' object

======================================================================
ERROR: test_field_descriptor (test.test_collections.TestNamedTuple.test_field_descriptor) (proto=3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 690, in test_field_descriptor
    class NewPoint(tuple):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 691, in NewPoint
    x = pickle.loads(pickle.dumps(Point.x, proto))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'property' object

======================================================================
ERROR: test_field_descriptor (test.test_collections.TestNamedTuple.test_field_descriptor) (proto=4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 690, in test_field_descriptor
    class NewPoint(tuple):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 691, in NewPoint
    x = pickle.loads(pickle.dumps(Point.x, proto))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'property' object

======================================================================
ERROR: test_field_descriptor (test.test_collections.TestNamedTuple.test_field_descriptor) (proto=5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 690, in test_field_descriptor
    class NewPoint(tuple):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 691, in NewPoint
    x = pickle.loads(pickle.dumps(Point.x, proto))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'property' object

======================================================================
FAIL: test_field_repr (test.test_collections.TestNamedTuple.test_field_repr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_collections.py", line 446, in test_field_repr
    self.assertEqual(repr(Point.x), "_tuplegetter(0, 'Alias for field number 0')")
AssertionError: '<property object at 0x10bb073f0>' != "_tuplegetter(0, 'Alias for field number 0')"
- <property object at 0x10bb073f0>
+ _tuplegetter(0, 'Alias for field number 0')
```

I think that:
1. We can consider adding `pickle` support
2. `repr` is not really important
3. Test can easily be added to check that fallback version also works

Do we care about it enough to make this change?

**Comment by rhettinger** [comment]
> Do we care about it enough to make this change?

No.  Those tests are marked as cpython-only and were there just to give coverage of the C code.  They are not an API promise.
