### ISSUE TITLE
SystemError in re.match with a "*+" pattern

### ISSUE THREAD

**Issue by aryla** [python/cpython#101955]
# Bug report

The following code raises a SystemError.
```python
import re
re.match('((x)|y|z)*+', 'xyz')
```

Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Arttu\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 166, in match
    return _compile(pattern, flags).match(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: The span of capturing group is wrong, please report a bug for the re module.
```

`((x)|y|z)++` gives the same error but `(?>((x)|y|z)*)` does not.

# Your environment

Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32

### Linked PRs
* gh-111362
* gh-126962
* gh-126963

**Comment by animalize** [comment]
Need to set `state->repeat` to non-NULL.
```diff
--- a/Modules/_sre/sre_lib.h
+++ b/Modules/_sre/sre_lib.h
@@ -1257,6 +1257,15 @@ SRE(match)(SRE_STATE* state, const SRE_CODE* pattern, int toplevel)
                pointer */
             state->ptr = ptr;
 
+            /* Set state->repeat to non-NULL */
+            ctx->u.rep = (SRE_REPEAT*) PyObject_Malloc(sizeof(*ctx->u.rep));
+            if (!ctx->u.rep) {
+                PyErr_NoMemory();
+                RETURN_ERROR(SRE_ERROR_MEMORY);
+            }
+            ctx->u.rep->prev = state->repeat;
+            state->repeat = ctx->u.rep;
+
             /* Initialize Count to 0 */
             ctx->count = 0;
 
@@ -1271,6 +1280,10 @@ SRE(match)(SRE_STATE* state, const SRE_CODE* pattern, int toplevel)
                 }
                 else {
                     state->ptr = ptr;
+                    /* Restore state->repeat */
+                    state->repeat = ctx->u.rep->prev;
+                    PyObject_Free(ctx->u.rep);
+
                     RETURN_FAILURE;
                 }
             }
@@ -1339,6 +1352,10 @@ SRE(match)(SRE_STATE* state, const SRE_CODE* pattern, int toplevel)
                 }
             }
 
+            /* Restore state->repeat */
+            state->repeat = ctx->u.rep->prev;
+            PyObject_Free(ctx->u.rep);
+
             /* Evaluate Tail */
             /* Jump to end of pattern indicated by skip, and then skip
                the SUCCESS op code that follows it. */
```

**Comment by animalize** [comment]
Should set `state->repeat` to non-NULL in `SRE_OP_POSSESSIVE_REPEAT` opcode.

**Comment by uyw4687** [comment]
I'll look into it

**Comment by corona10** [comment]
> I'll look into it

Please go a head

**Comment by animalize** [comment]
> I'll look into it

If you don't know much about `sre`, it's better to start with this issue: #100061
This issue involves capture groups.

**Comment by serhiy-storchaka** [comment]
Thanks @wjssz. The final code is his contribution.
