### ISSUE TITLE
arm64/macOS: Python 3.11.1+ build failure - ensurepip/pyexpat

### ISSUE THREAD

**Issue by sendmalwhere** [python/cpython#102164]
# Bug report

Hi y'all. I'm on an m1 Mac attempting to install Python 3.11.2. I initially tried to do this via `pyenv`, but it also fails with the same error if I try to compile from source, so I expect it's something about my specific environment, or else something about the way that `ensurepip` is handled in python 3.11.1+ (as this also fails in 3.11.1, but not 3.11.0).

### Error when attempting to install from source
```
if test "x" != "x" ; then \
		rm -f /usr/local/bin/python3-32; \
		(cd /usr/local/bin; ln -s python3.11-32 python3-32) \
	fi
if test "x" != "x" ; then \
		rm -f /usr/local/bin/python3-intel64; \
		(cd /usr/local/bin; ln -s python3.11-intel64 python3-intel64) \
	fi
rm -f /usr/local/share/man/man1/python3.1
(cd /usr/local/share/man/man1; ln -s python3.11.1 python3.1)
if test "xupgrade" != "xno"  ; then \
		case upgrade in \
			upgrade) ensurepip="--upgrade" ;; \
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/tmpxub_yl18/pip-22.3.1-py3-none-any.whl/pip/__main__.py", line 31, in <module>
  File "/tmp/tmpxub_yl18/pip-22.3.1-py3-none-any.whl/pip/_internal/cli/main.py", line 68, in main
  File "/tmp/tmpxub_yl18/pip-22.3.1-py3-none-any.whl/pip/_internal/commands/__init__.py", line 114, in create_command
  File "/Users/sroo/Downloads/Python-3.11.2/Lib/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/tmpxub_yl18/pip-22.3.1-py3-none-any.whl/pip/_internal/commands/install.py", line 16, in <module>
  File "/tmp/tmpxub_yl18/pip-22.3.1-py3-none-any.whl/pip/_internal/cli/req_command.py", line 21, in <module>
  File "/tmp/tmpxub_yl18/pip-22.3.1-py3-none-any.whl/pip/_internal/index/package_finder.py", line 33, in <module>
  File "/tmp/tmpxub_yl18/pip-22.3.1-py3-none-any.whl/pip/_internal/req/__init__.py", line 8, in <module>
  File "/tmp/tmpxub_yl18/pip-22.3.1-py3-none-any.whl/pip/_internal/req/req_install.py", line 44, in <module>
  File "/tmp/tmpxub_yl18/pip-22.3.1-py3-none-any.whl/pip/_internal/operations/install/wheel.py", line 39, in <module>
  File "/tmp/tmpxub_yl18/pip-22.3.1-py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 16, in <module>
  File "/tmp/tmpxub_yl18/pip-22.3.1-py3-none-any.whl/pip/_vendor/distlib/compat.py", line 83, in <module>
  File "/Users/sroo/Downloads/Python-3.11.2/Lib/xmlrpc/client.py", line 138, in <module>
    from xml.parsers import expat
  File "/Users/sroo/Downloads/Python-3.11.2/Lib/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ModuleNotFoundError: No module named 'pyexpat'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/sroo/Downloads/Python-3.11.2/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
             ^^^^^^^^^^^^^^^^^
  File "/Users/sroo/Downloads/Python-3.11.2/Lib/ensurepip/__init__.py", line 286, in _main
    return _bootstrap(
           ^^^^^^^^^^^
  File "/Users/sroo/Downloads/Python-3.11.2/Lib/ensurepip/__init__.py", line 202, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sroo/Downloads/Python-3.11.2/Lib/ensurepip/__init__.py", line 103, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sroo/Downloads/Python-3.11.2/Lib/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/sroo/Downloads/Python-3.11.2/python.exe', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmpxub_yl18/setuptools-65.5.0-py3-none-any.whl\', \'/tmp/tmpxub_yl18/pip-22.3.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmpxub_yl18\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
make: *** [install] Error 1
```
[Full `sudo make install` log output](https://github.com/python/cpython/files/10809724/make_install_output.log)

### Error when attempting to install via pyenv
```
pyenv install 3.11.2
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.11.2.tar.xz...
-> https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tar.xz
Installing Python-3.11.2...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 13.3 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/52/dh476s_91pb8xsxpxbl6qkbm0000gn/T/python-build.20230222175636.93061
Results logged to /var/folders/52/dh476s_91pb8xsxpxbl6qkbm0000gn/T/python-build.20230222175636.93061.log

Last 10 log lines:
  File "/private/var/folders/52/dh476s_91pb8xsxpxbl6qkbm0000gn/T/python-build.20230222175636.93061/Python-3.11.2/Lib/ensurepip/__init__.py", line 202, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/52/dh476s_91pb8xsxpxbl6qkbm0000gn/T/python-build.20230222175636.93061/Python-3.11.2/Lib/ensurepip/__init__.py", line 103, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/52/dh476s_91pb8xsxpxbl6qkbm0000gn/T/python-build.20230222175636.93061/Python-3.11.2/Lib/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/private/var/folders/52/dh476s_91pb8xsxpxbl6qkbm0000gn/T/python-build.20230222175636.93061/Python-3.11.2/python.exe', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/52/dh476s_91pb8xsxpxbl6qkbm0000gn/T/tmpkk9ez1ky/setuptools-65.5.0-py3-none-any.whl\', \'/var/folders/52/dh476s_91pb8xsxpxbl6qkbm0000gn/T/tmpkk9ez1ky/pip-22.3.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/52/dh476s_91pb8xsxpxbl6qkbm0000gn/T/tmpkk9ez1ky\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
make: *** [install] Error 1
```

Note also that if I attempt to `pip install libexpat` on my existing python installation, I get the following error:
```
pip install libexpat
ERROR:root:code for hash blake2b was not found.
Traceback (most recent call last):
  File "/Users/sroo/.pyenv/versions/3.11.0/lib/python3.11/hashlib.py", line 307, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sroo/.pyenv/versions/3.11.0/lib/python3.11/hashlib.py", line 129, in __get_openssl_constructor
    return __get_builtin_constructor(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sroo/.pyenv/versions/3.11.0/lib/python3.11/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type blake2b
ERROR:root:code for hash blake2s was not found.
Traceback (most recent call last):
  File "/Users/sroo/.pyenv/versions/3.11.0/lib/python3.11/hashlib.py", line 307, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sroo/.pyenv/versions/3.11.0/lib/python3.11/hashlib.py", line 129, in __get_openssl_constructor
    return __get_builtin_constructor(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sroo/.pyenv/versions/3.11.0/lib/python3.11/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type blake2s
ERROR: Could not find a version that satisfies the requirement libexpat (from versions: none)
ERROR: No matching distribution found for libexpat
```

## Repro instructions:
1. `brew install pyenv`
2. `pyenv install 3.11.2`

# My environment

- CPython versions tested on: `3.10.10`, `3.11.0`, `3.11.1`, `3.11.2` (versions >= 3.11.1 fail to install; versions < 3.11.1 work properly)
- OS: `macOS 13.3`
- CPU Arch: `arm64`
- python-build: `20180424`

# Things I have tried that don't work
- Completely removing homebrew, pyenv, and all existing versions of Python before reinstalling them
- Just honking `export ARCHFLAGS="-arch arm64"` into the env to make sure the arch isn't the problem

**Comment by dtrodrigues** [comment]
This is likely an issue with your environment and not an issue with CPython. Both installation from the source tar and via pyenv are working for me on an M1 Mac. Does the .pkg installer from python.org work for you: https://www.python.org/ftp/python/3.11.2/python-3.11.2-macos11.pkg

That being said, can you include the full log you get after you run `./configure --with-openssl=$(brew --prefix openssl@1.1) && make` on the downloaded source?

**Comment by gatsbysghost** [comment]
I figured I would not be the first person to post about this, like, _now_, if it was an OS-wide issue, and in support of that theory, yeah, the .pkg installer works fine.

And sure thing--here's that file: [configure_and_make.log](https://github.com/python/cpython/files/10811190/configure_and_make.log)

Interesting items from close to the failure here:
```running build
running build_ext
building 'pyexpat' extension
gcc -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden -I./Include/internal -I./Modules/expat -I./Include -I. -I/usr/local/include -I/Users/sroo/Downloads/Python-3.11.2/Include -I/Users/sroo/Downloads/Python-3.11.2 -c /Users/sroo/Downloads/Python-3.11.2/Modules/pyexpat.c -o build/temp.macosx-13.3-arm64-3.11/Users/sroo/Downloads/Python-3.11.2/Modules/pyexpat.o
**error: unable to open output file 'build/temp.macosx-13.3-arm64-3.11/Users/sroo/Downloads/Python-3.11.2/Modules/pyexpat.o': 'Operation not permitted'**
1 error generated.
building '_elementtree' extension
gcc -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden -I./Include/internal -I./Modules/expat -I./Include -I. -I/usr/local/include -I/Users/sroo/Downloads/Python-3.11.2/Include -I/Users/sroo/Downloads/Python-3.11.2 -c /Users/sroo/Downloads/Python-3.11.2/Modules/_elementtree.c -o build/temp.macosx-13.3-arm64-3.11/Users/sroo/Downloads/Python-3.11.2/Modules/_elementtree.o
**error: unable to open output file 'build/temp.macosx-13.3-arm64-3.11/Users/sroo/Downloads/Python-3.11.2/Modules/_elementtree.o': 'Operation not permitted'**
1 error generated.
building '_decimal' extension
gcc -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden -I./Include/internal -DUNIVERSAL=1 -I./Modules/_decimal/libmpdec -I./Include -I. -I/usr/local/include -I/Users/sroo/Downloads/Python-3.11.2/Include -I/Users/sroo/Downloads/Python-3.11.2 -c /Users/sroo/Downloads/Python-3.11.2/Modules/_decimal/_decimal.c -o build/temp.macosx-13.3-arm64-3.11/Users/sroo/Downloads/Python-3.11.2/Modules/_decimal/_decimal.o
**error: unable to open output file 'build/temp.macosx-13.3-arm64-3.11/Users/sroo/Downloads/Python-3.11.2/Modules/_decimal/_decimal.o': 'Operation not permitted'**
1 error generated.

The necessary bits to build these optional modules were not found:
_gdbm                 _tkinter
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


Failed to build these modules:
_decimal              _elementtree          pyexpat
```

**Comment by gatsbysghost** [comment]
OH. You know what, this is actually all my fault, and in a way that only I could possibly have contrived for myself (i.e., the reason why I'm the only person I've been able to find on the entire internet who has this specific error).

Long story short, about a month ago, I attempted to replace my linker with `mold`, by way of setting compiler flags in my shell profile and replacing llvm with the mold binary symlinked to `/opt/homebrew/bin/llvm`. Then I promptly forgot that I had done that.

Removed all the env vars, fixed up my path to use system `llvm`, and bob's your uncle.

Hoist by my own stupid devops petard. Sorry for wasting your time with this!
