### ISSUE TITLE
Float conversion error in IDLE 

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#102220]
I observed the following console traceback while running IDLE from the command line:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 861, in callit
    func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/idlelib/codecontext.py", line 243, in timer_event
    self.update_code_context()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/idlelib/codecontext.py", line 187, in update_code_context
    new_topvisible = self.editwin.getlineno("@0,0")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/idlelib/editor.py", line 1056, in getlineno
    return int(float(text.index(mark)))
               ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''
```

**Comment by JamesParrott** [comment]
Hi Raymond.  This puzzled me at first, but it's from a call to tkinter.Text.index (not str.index).  

tkinter.Text.index can return a string, of the form "line.column", which could be coerced to a float, just like and thence the integer part extraced for the line number, just as in yout error: `int(float(text.index(mark)))`.  A basic example can be tried out from the repl:

```
>>> import tkinter
>>> t = tkinter.Text()
>>> t.index('@0,0')
'1.0'
```

But tkinter.Text.index can return all manner of other strings too, many of which are not convertable to floats, such as "line.**end**":

"The index notation for Text widgets is very rich and is best described in the Tk man pages."
https://docs.python.org/3/library/tkinter.html
https://tkdocs.com/shipman/text-index.html

Did you open a particular file with idlelib, or perform some particular action that caused this error?

**Comment by JamesParrott** [comment]
getlineno is intended to simply return a line number.
Perhaps delving into Tkinter and idlelib further is overthinking it, when a simple fix will probably suffice:

```
def getlineno(self, mark="insert"):
          text = self.text

 -        return int(float(text.index(mark)))
 +       text_widget_index = text.index(mark)
 +       return int(text_widget_index.partition('.')[0])
```

https://github.com/python/cpython/pull/102226/commits/32152cf6a63738a758758f46db696ec076c23296

**Comment by terryjreedy** [comment]
Raymond, is this, as far as you know, a unique occurrence for you?  Traceback indicates Mac, as usual.
It seems that _tkinter.c catches and prints TclErrors in callbacks, allowing the program to continue as if the event never happened.  I added an explicit raise and got a similar traceback.  Your traceback does not include toggle_code_context, so the initial update call worked.  A later timer update had the error.

Even though the `index` arg of `text.index` can have multiple forms, the *return* value is documented at https://www.tcl.tk/man/tcl8.6/TkCmd/text.html#M130 as always having the form 'line.col'.  The error message says that it was instead '', which is a ValueError for both float() and int().  Since ''.partition('.')[0] == '', it is no fix.  Ditto for the more usual alternative ''.split('.')[0].

https://www.tcl.tk/man/tcl8.6/TkCmd/text.html#M24 says "@x,y:     Indicates the character that covers the pixel whose x and y coordinates within the text's window are x and y. "  AFAIK, `index('@0,0')` has been working for years.  It is used in several places in editor.py.  (CHECK: all in event handlers?)  And as noted above, I believe it worked at least once in Raymond's session.  It is hard to know, for instance, if `@1,1` would work better.

Under what condition does it return '' instead of the documented value?  I tried showing code context in a blank IDLE editor started from Command Prompt (Windows) and Terminal and got no  error in multiple tries.

**Comment by serhiy-storchaka** [comment]
`Text.index()` can return an empty string if the argument is invalid. And it is the first surprise, because in pure Tk shell it is an error. I have no idea why it is not a TclError in Tkinter.

In any case, it can return an empty string as an indication of some error. I was not able to get any error for "@0,0". I tried with freshly created text widget not yet managed by the geometry manager, I tried to move the window on other screen, to change the window size to zero, to withdraw and forget it -- nothing produced error. So we should just handle the special case of an empty string, return some sensible value from `getlineno()` which does not cause issues on the caller side.

**Comment by chrstphrchvz** [comment]
I looked into this issue a while ago, but neglected to comment here. I am not sure Tkinter should work around this, because from what I can tell, it is not expected behavior.

I asked on the Tcl chatroom (which I do not frequent) about how the text index command could return an empty string without error. One veteran Tcl/Tk maintainer replied that it should not be possible, nor were there any recent C code changes which would affect this. I agree with this assessment; if the text index command does not raise an error, then the result must have the form `%d.%d`, as this call chain in the C code should illustrate:
`TextWidgetObjCmd()` https://github.com/tcltk/tk/blob/core-8-6-13/generic/tkText.c#L1359
`TkTextNewIndexObj()` https://github.com/tcltk/tk/blob/core-8-6-13/generic/tkTextIndex.c#L285
`UpdateStringOfTextIndex()` https://github.com/tcltk/tk/blob/core-8-6-13/generic/tkTextIndex.c#L140
`TkTextPrintIndex()` https://github.com/tcltk/tk/blob/core-8-6-13/generic/tkTextIndex.c#L1131

This should also rule out the possibility of it returning e.g. something of the form `%d.end`.

However, because I mentioned that this was an isolated occurrence, someone else in the chatroom attributed the issue to a "cosmic ray" (i.e. single event upset). Personally, I think it is still more likely to have been caused by a bug somewhere else in Tcl/Tk silently corrupting memory, particularly given how Tcl/Tk’s default `malloc()` wrapper often helps conceal such issues.

**Comment by StanFromIreland** [comment]
I agree that this might just be a "cosmic ray".

Unable to reproduce on main branch build or 3.13.

**Comment by terryjreedy** [comment]
This is not an IDLE issue, so I am leaving decisions to Raymond and/or Serhiy.
