### ISSUE TITLE
Possible race condition in signal handling

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#102397]
The following code segfaults the interpreter on Linux.  Tested on current main. 

```py
import gc
import _thread

gc.set_threshold(1, 0, 0)

def cb(*args):
    _thread.interrupt_main()


gc.callbacks.append(cb)

def gen():
    yield 1

g = gen()
g.__next__()
```

```console 
Exception ignored in: <function cb at 0x7f7f4f6fe200>
Traceback (most recent call last):
  File "/workspaces/cpython/main.py", line 7, in cb
    _thread.interrupt_main()
KeyboardInterrupt: 
Exception ignored in: <function cb at 0x7f7f4f6fe200>
Traceback (most recent call last):
  File "/workspaces/cpython/main.py", line 7, in cb
    _thread.interrupt_main()
KeyboardInterrupt: 
Exception ignored in: <function cb at 0x7f7f4f6fe200>
Traceback (most recent call last):
  File "/workspaces/cpython/main.py", line 7, in cb
    _thread.interrupt_main()
KeyboardInterrupt: 
Exception ignored in: <function cb at 0x7f7f4f6fe200>
Traceback (most recent call last):
  File "/workspaces/cpython/main.py", line 7, in cb
    _thread.interrupt_main()
KeyboardInterrupt: 
Segmentation fault (core dumped)
```

### Linked PRs
* gh-102399
* gh-102527
* gh-102528

**Comment by chgnrdv** [comment]
Guess I found a minimal reproducer:

```python
import _thread

class Foo():
    def __del__(self):
        _thread.interrupt_main()

x = Foo()
```

This, as well as original one, crashes on 3.10.8, 3.11.0 and current main under Linux.

**Comment by kumaraditya303** [comment]
Yeah, both of these crashes are basically the same, they both crash in `compare_handler` in signal handling, I am working on a fix.

**Comment by kumaraditya303** [comment]
Fixed in main and backported, closing.
