### ISSUE TITLE
exec adds a dict and not a module for __builtins__

### ISSUE THREAD

**Issue by impact27** [python/cpython#102316]
# Bug report
The doc claims (https://docs.python.org/3/library/functions.html#exec):

> If the globals dictionary does not contain a value for the key `__builtins__`, a reference to the dictionary of the built-in module builtins is inserted under that key. That way you can control what builtins are available to the executed code by inserting your own `__builtins__` dictionary into globals before passing it to exec().

Yet:
```python
Python 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> __builtins__.__class__
<class 'module'>
>>> glob = {}
>>> exec("0", glob)
>>> glob["__builtins__"].__class__
<class 'dict'>
>>> 
```

I would expect `glob["__builtins__"]` to be the builtins module, not a dict containing builtins functions!
This is a problem if I try to access the dict:

```python
>>> bool(__builtins__.globals())
True
>>> glob = {}
>>> exec("bool(__builtins__.globals())", glob)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'globals'
>>> 
```

So exec and the interpreter do not have the same behaviour!

# Your environment

- CPython versions tested on: Python 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
- Operating system and architecture: Apple M1 Max - 13.1 (22C65)

**Comment by impact27** [comment]
Sorry I misread the doc. It is still strange that `__builtins__` is sometimes a dict and sometimes a module
