### ISSUE TITLE
All standard library functions accepting `str` paths must accept `PathLike` as well

### ISSUE THREAD

**Issue by arhadthedev** [python/cpython#102425]
*Inspired by gh-3484 that tried to fix this for `wave.open()` only but failed.*

We need a centralized and universal approach instead so everything accepting `str` paths could automatically accept `PathLike` for free.

For this, we can amend stdlib functions to wrap their path arguments into `pathlib.PurePath` introduced in Python 3.4. Unlike `os.fspath`, it throws a nicely formatted exception for us:

- `os.fspath` from the mentioned gh-3484: https://github.com/python/cpython/blob/4a82d651b5472641f966959e046b89f0ade3a8a7/Lib/aifc.py#L912-L918
- `PurePath`:

   ```python
   >>> import pathlib
   >>> pathlib.PurePath(16)
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "D:\Oleg\cpython\Lib\pathlib.py", line 267, in __new__
       return cls._from_parts(args)
              ^^^^^^^^^^^^^^^^^^^^^
     File "D:\Oleg\cpython\Lib\pathlib.py", line 316, in _from_parts
       drv, root, parts = self._parse_args(args)
                          ^^^^^^^^^^^^^^^^^^^^^^
     File "D:\Oleg\cpython\Lib\pathlib.py", line 300, in _parse_args
       a = os.fspath(a)
           ^^^^^^^^^^^^
   TypeError: expected str, bytes or os.PathLike object, not int
   ```

**Comment by ericvsmith** [comment]
It’s not clear to me what you’re proposing to change. Can you provide specifics?

How would `PurePath(16)`’s behavior change?

**Comment by encukou** [comment]
> We need a centralized and universal approach instead so everything accepting str paths could automatically accept PathLike for free.

`os.fspath` is meant to do just that.

Note that importing `pathlib` and creating `PurePath` are relatively expensive operations (compared to `os.fspath` with strings). When the niceties they provide aren't useful, it's better to avoid them.

> Unlike `os.fspath`, it throws a nicely formatted exception for us:

How can the error message from `os.fspath` be improved?

**Comment by hauntsaninja** [comment]
> Unlike os.fspath, it throws a nicely formatted exception for us

I'm confused, `pathlib.PurePath`'s error message in the thing you've posted is literally coming straight from `os.fspath`

**Comment by arhadthedev** [comment]
Closing in favor of gh-103659.

**Comment by arhadthedev** [comment]
Reopening after https://github.com/python/cpython/issues/103659#issuecomment-1517895900:

> BTW, I don't think https://github.com/python/cpython/issues/102425 applies here, the os.environ values are strings some of which happen to look like paths (or integers).

However, I'll return to this issue much later.

**Comment by ronaldoussoren** [comment]
No need to reopen this for my comment on #103659 , I tried to say that this issue is not a reason for changing the behaviour of ``os.environ`` with PathLike objects.

**Comment by serhiy-storchaka** [comment]
The purpose of this issue is not clear. `os.fspath()` already has a clear error message. The caller can override it if it supports more types (for example, open file descriptors or open file objects). I do not see how using the `pathlib.PurePath` constructor can make this better. More, `os.fspath()` is more lightweight and faster than `pathlib.PurePath()`.

**Comment by efimov-mikhail** [comment]
@serhiy-storchaka , "not planned" suits better, isn't it?
