### ISSUE TITLE
[Enum] Exception being ignored in custom datatypes

### ISSUE THREAD

**Issue by ethanfurman** [python/cpython#102549]
```python
import enum

class Base:
    def __init__(self, x):
        print('In Base init')
        raise ValueError("I don't like", x)

class MyEnum(Base, enum.Enum):
    A = 'a'
    def __init__(self, y):
        print('In MyEnum init')
        self.y = y
```

`MyEnum` should not be created because of the exception in `Base.__init__`.

### Linked PRs
* gh-103149
* gh-103154

**Comment by kwsp** [comment]
Just tested this - `MyEnum` is indeed not created and the `ValueError` is raised.

```python
import enum

class Base:
    def __init__(self, x):
        print('In Base init')
        raise ValueError("I don't like", x)

class MyEnum(Base, enum.Enum):
    A = 'a'
    def __init__(self, y):
        print('In MyEnum init')
        self.y = y

MyEnum(1)
```

Output

```
In Base init
In MyEnum init
Traceback (most recent call last):
  File "/Users/tnie/code/cpython/tmp.py", line 14, in <module>
    MyEnum(1)
  File "/Users/tnie/code/cpython/Lib/enum.py", line 728, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tnie/code/cpython/Lib/enum.py", line 1132, in __new__
    raise ve_exc
ValueError: 1 is not a valid MyEnum
```

What behaviour are you describing that's a bug?

**Comment by ethanfurman** [comment]
`MyEnum` should not have been created in the first place.  The behavior in the patch I'm working on:
```python
import enum

class Base:
    def __init__(self, x):
        print('In Base init')
        raise ValueError("I don't like", x)

class MyEnum(Base, enum.Enum):
    A = 'a'
    def __init__(self, y):
        print('In MyEnum init')
        self.y = y
```
and
```
In Base init
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/source/python/cpython/Lib/enum.py", line 561, in __new__
    raise exc
  File "/source/python/cpython/Lib/enum.py", line 278, in __set_name__
    raise TypeError(
TypeError: _value_ not set in __new__, unable to create it
>>> MyEnum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'MyEnum' is not defined
```
