### ISSUE TITLE
Python 3.11 fails to build from source under homebrew on macOS 13.3 / Xcode 14.3

### ISSUE THREAD

**Issue by NeilBetham** [python/cpython#103235]
# Bug report
Building from source is failing under Homebrew on macOS 13.3 / Xcode 14.3. For reference [here](https://github.com/Homebrew/homebrew-core/issues/127316) is the issue on the homebrew side. I was asked to file a report here as it appears to be an issue in Python rather than Homebrew. Command output and logs are in the issue there.

A quick synopsis is that after an upgrade from Ventura 13.2 to 13.3 and the accompanying upgrade of Xcode from 14.2 to 14.3 Python is no longer building. I replicated this on two separate machines. The build seems to fail when trying to build a Wheel of Wheel.

# Your environment
I tested this with the 3.9, 10 and 11 Python formulae and all fail to complete.
```
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

# Logs
### macOS 13.3 - Xcode 14.3 - Python 3.11
Command Output:
```
➜ brew install -s python@3.11
==> Fetching dependencies for python@3.11: mpdecimal, ca-certificates, openssl@1.1, readline, sqlite, xz and pkg-config
==> Fetching mpdecimal
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/manifests/2.5.1
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/f367c2ee08c56b88be0662703a8e4275f8657608a268c8c44e845154b0cea543--mpdecimal-2.5.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/blobs/sha256:5b1c62c08b42feb6e48c461a9de4751803f3ccc76830213a517f0905178dbbef
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/6bf6539627b31c17765f4bcfbe8be8996f3505d3342804531f114c13e64a5a9e--mpdecimal--2.5.1.arm64_ventura.bottle.tar.gz
==> Fetching ca-certificates
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/manifests/2023-01-10
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/927414ed081d996b84d938be6af4d2639403b4d2bee3cc29268d0844999da180--ca-certificates-2023-01-10.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/blobs/sha256:11fe9d0a98a2ac454fa1db95762a697c3340f46560ff27e5e9db8fdeb003f17e
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/ca2448928ab98c455b5e46d4a6604247a151ab0f4e60553dbb5c6aecd2e1df3c--ca-certificates--2023-01-10.all.bottle.tar.gz
==> Fetching openssl@1.1
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/1.1/manifests/1.1.1t
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/e8519d4f6d202ef928d8abd8368bb1599920846dd8c5d4986fdb9df9497c393f--openssl@1.1-1.1.1t.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/1.1/blobs/sha256:e1e08ddd93298ef8776b202e4b2f86fc519bf27a72f7cfb082b69ff2868a0175
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/cb74bd875c0a6e7da2aac14326bbd631ab173405f45b4eb3d06a75b67ef0e4ef--openssl@1.1--1.1.1t.arm64_ventura.bottle.tar.gz
==> Fetching readline
==> Downloading https://ghcr.io/v2/homebrew/core/readline/manifests/8.2.1
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/ab483c9a913ae82f3a2b3ae20918791bc3bd6825c7122a29cd4f1e0c65413759--readline-8.2.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/readline/blobs/sha256:fba42a9bd6feaa8902ae4491ffdf177662e0a165a0d0ddef0988ad6ecf0f23dd
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/1d2d645220a91b8ac8869d09ddf0206070cd2f4278dddcfcc106eefb86be3c6c--readline--8.2.1.arm64_ventura.bottle.tar.gz
==> Fetching sqlite
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.41.2
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/4ce9e1d111b77d4bd5b1ba9aa50b6cf58528731dc5703a7b23814e4ffd9e352f--sqlite-3.41.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:2a77f2ddcf124d8704c299572c4dc55517996d796011545852e362c6e2a2a2ea
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/17747922b09123042dfa270fdf1dec467c9e8740d11f91ae54b82c0b76fdc8b2--sqlite--3.41.2.arm64_ventura.bottle.tar.gz
==> Fetching xz
==> Downloading https://ghcr.io/v2/homebrew/core/xz/manifests/5.4.2
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/a3e9156f769d3e7b84fa810d0f9f2f3fdf3280dea14e1e46231ce3d3f92d5960--xz-5.4.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/xz/blobs/sha256:5919a39bb56458a164ec5b757b0cb903c2d167e4e593daf8360a55db1db85d4f
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/edab4c7180e8db30e6fefc40962a80732071a33540de258f676005e76262f3c7--xz--5.4.2.arm64_ventura.bottle.tar.gz
==> Fetching pkg-config
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/manifests/0.29.2_3
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/ac691fc7ab8ecffba32a837e7197101d271474a3a84cfddcc30c9fd6763ab3c6--pkg-config-0.29.2_3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/blobs/sha256:3ff612c5e44b945c8c0cc6df7d3edb407ca67cddad9c89f9ab99ced494b7a8c2
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/67d3dc124994992b9bf52271e49db7787da015530f056ba397996a46766a3e4f--pkg-config--0.29.2_3.arm64_ventura.bottle.tar.gz
==> Fetching python@3.11
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/ee14da206ae9d8af2416c9c516e8b731bb67a3f5/Formula/python@3.11.rb
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/6d2fba8de3159182025237d373a6f4f78b8bd203/python/3.11-sysconfig.diff
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/2322057182c6bb73dfe09e098010168a5a9d0712a89cee86d2c5ddb11052137e--3.11-sysconfig.diff
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/a1618a5005d0b01d63b720321806820a03432f1a/python/3.10-distutils-scheme.diff
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/5fea40db1cb33001d6ab42c76fc28693ce292532c6ed6f89dd3154dac29167bb--3.10-distutils-scheme.diff
==> Downloading https://files.pythonhosted.org/packages/b6/21/cb9a8d0b2c8597c83fce8e9c02884bce3d4951e41e807fc35791c6b23d9a/setuptools-65.6.3.tar.gz
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/baa4898f4ba1986a3029b65e2816bd8027282a9c55dfe944dd85a0081a76bf99--setuptools-65.6.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/a3/50/c4d2727b99052780aad92c7297465af5fe6eec2dbae490aa9763273ffdc1/pip-22.3.1.tar.gz
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/18f112eb5ce9a9a304959fcd69b75d3102a4f4bc9821d5aecacadd114a74c6b9--pip-22.3.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/a2/b8/6a06ff0f13a00fc3c3e7d222a995526cbca26c1ad107691b6b1badbbabf1/wheel-0.38.4.tar.gz
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/11cf98bef3f824f9e6accda9cc720e738be1574ce4b58aa560a67633ac092eab--wheel-0.38.4.tar.gz
==> Downloading https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tgz
Already downloaded: /Users/neilbetham/Library/Caches/Homebrew/downloads/ce4d3485f1170910f1fc15bee454d07bce7f72122bf69605c03a10856a187fb8--Python-3.11.2.tgz
==> Installing dependencies for python@3.11: pkg-config, mpdecimal, ca-certificates, openssl@1.1, readline, sqlite and xz
==> Installing python@3.11 dependency: pkg-config
==> Pouring pkg-config--0.29.2_3.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/pkg-config/0.29.2_3: 11 files, 676.2KB
==> Installing python@3.11 dependency: mpdecimal
==> Pouring mpdecimal--2.5.1.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/mpdecimal/2.5.1: 71 files, 2.2MB
==> Installing python@3.11 dependency: ca-certificates
==> Pouring ca-certificates--2023-01-10.all.bottle.tar.gz
==> Regenerating CA certificate bundle from keychain, this may take a while...
🍺  /opt/homebrew/Cellar/ca-certificates/2023-01-10: 3 files, 216.9KB
==> Installing python@3.11 dependency: openssl@1.1
==> Pouring openssl@1.1--1.1.1t.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/openssl@1.1/1.1.1t: 8,101 files, 18MB
==> Installing python@3.11 dependency: readline
==> Pouring readline--8.2.1.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/readline/8.2.1: 50 files, 1.7MB
==> Installing python@3.11 dependency: sqlite
==> Pouring sqlite--3.41.2.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/sqlite/3.41.2: 11 files, 4.5MB
==> Installing python@3.11 dependency: xz
==> Pouring xz--5.4.2.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/xz/5.4.2: 162 files, 2.5MB
==> Installing python@3.11
==> Patching
==> Applying 3.11-sysconfig.diff
patching file 'Lib/sysconfig.py'
==> Applying 3.10-distutils-scheme.diff
patching file 'Lib/distutils/command/install.py'
==> ./configure --prefix=/opt/homebrew/Cellar/python@3.11/3.11.2_1 --enable-ipv6 --datarootdir=/opt/homebrew/Cellar/python@3.11/3.11.2_1/share --datadir=/opt/homebrew/Cellar/python@3.11/3.11
==> make
==> make install PYTHONAPPSDIR=/opt/homebrew/Cellar/python@3.11/3.11.2_1
==> make frameworkinstallextras PYTHONAPPSDIR=/opt/homebrew/Cellar/python@3.11/3.11.2_1/share/python@3.11
==> /opt/homebrew/Cellar/python@3.11/3.11.2_1/bin/python3.11 -m venv /private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build
==> /private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build/bin/pip3 install -v --no-deps --no-binary :all: --no-index --no-build-isolation .
==> /private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build/bin/pip3 wheel -v --no-deps --no-binary :all: --no-index --no-build-isolation --wheel-dir=/opt/homebrew/Cellar/pyt
Last 15 lines from /Users/neilbetham/Library/Logs/Homebrew/python@3.11/07.pip3:
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/private/tmp/pythonA3.11--wheel-20230402-97406-1prkzi6/wheel-0.38.4/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /private/tmp/pip-wheel-yrzdu0vz
  cwd: /private/tmp/pythonA3.11--wheel-20230402-97406-1prkzi6/wheel-0.38.4/
  Building wheel for wheel (setup.py): finished with status 'error'
  ERROR: Failed building wheel for wheel
  Running setup.py clean for wheel
  Running command python setup.py clean
  running clean
  removing 'build/lib' (and everything under it)
  'build/bdist.macosx-13-arm64' does not exist -- can't clean it
  'build/scripts-3.11' does not exist -- can't clean it
  removing 'build'
Failed to build wheel
ERROR: Failed to build one or more wheels
```

Log output for failed command:

```
2023-04-02 03:16:33 +0000

/private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build/bin/pip3
wheel
-v
--no-deps
--no-binary
:all:
--no-index
--no-build-isolation
--wheel-dir=/opt/homebrew/Cellar/python@3.11/3.11.2_1/libexec
.

DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Processing /private/tmp/pythonA3.11--wheel-20230402-97406-1prkzi6/wheel-0.38.4
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  running egg_info
  creating /private/tmp/pip-pip-egg-info-h9c8l8yx/wheel.egg-info
  writing /private/tmp/pip-pip-egg-info-h9c8l8yx/wheel.egg-info/PKG-INFO
  writing dependency_links to /private/tmp/pip-pip-egg-info-h9c8l8yx/wheel.egg-info/dependency_links.txt
  writing entry points to /private/tmp/pip-pip-egg-info-h9c8l8yx/wheel.egg-info/entry_points.txt
  writing requirements to /private/tmp/pip-pip-egg-info-h9c8l8yx/wheel.egg-info/requires.txt
  writing top-level names to /private/tmp/pip-pip-egg-info-h9c8l8yx/wheel.egg-info/top_level.txt
  writing manifest file '/private/tmp/pip-pip-egg-info-h9c8l8yx/wheel.egg-info/SOURCES.txt'
  reading manifest file '/private/tmp/pip-pip-egg-info-h9c8l8yx/wheel.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.dynlib' under directory 'tests'
  no previously-included directories found matching 'tests/testdata/*/build'
  no previously-included directories found matching 'tests/testdata/*/dist'
  no previously-included directories found matching 'tests/testdata/*/*.egg-info'
  adding license file 'LICENSE.txt'
  writing manifest file '/private/tmp/pip-pip-egg-info-h9c8l8yx/wheel.egg-info/SOURCES.txt'
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: wheel
  Building wheel for wheel (setup.py): started
  Running command python setup.py bdist_wheel
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/private/tmp/pythonA3.11--wheel-20230402-97406-1prkzi6/wheel-0.38.4/setup.py", line 5, in <module>
      setup()
    File "/private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 172, in setup
      ok = dist.parse_command_line()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 474, in parse_command_line
      args = self._parse_command_opts(parser, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build/lib/python3.11/site-packages/setuptools/dist.py", line 1107, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 533, in _parse_command_opts
      cmd_class = self.get_command_class(command)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build/lib/python3.11/site-packages/setuptools/dist.py", line 954, in get_command_class
      self.cmdclass[command] = cmdclass = ep.load()
                                          ^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
      module = import_module(match.group('module'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 940, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 28, in <module>
      from .macosx_libfile import calculate_macosx_platform_tag
    File "/private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build/lib/python3.11/site-packages/wheel/macosx_libfile.py", line 43, in <module>
      import ctypes
    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 8, in <module>
      from _ctypes import Union, Structure, Array
  ModuleNotFoundError: No module named '_ctypes'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /private/tmp/pythonA3.11-20230401-97406-1qnd8re/Python-3.11.2/whl_build/bin/python3.11 -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/private/tmp/pythonA3.11--wheel-20230402-97406-1prkzi6/wheel-0.38.4/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /private/tmp/pip-wheel-yrzdu0vz
  cwd: /private/tmp/pythonA3.11--wheel-20230402-97406-1prkzi6/wheel-0.38.4/
  Building wheel for wheel (setup.py): finished with status 'error'
  ERROR: Failed building wheel for wheel
  Running setup.py clean for wheel
  Running command python setup.py clean
  running clean
  removing 'build/lib' (and everything under it)
  'build/bdist.macosx-13-arm64' does not exist -- can't clean it
  'build/scripts-3.11' does not exist -- can't clean it
  removing 'build'
Failed to build wheel
ERROR: Failed to build one or more wheels

HOMEBREW_VERSION: 4.0.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: cf6614b50eac1c9f4bf386dc6989f0d443148df8
Last commit: 6 days ago
Core tap JSON: 02 Apr 03:10 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_BOOTSNAP: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j10
CMAKE_PREFIX_PATH: /opt/homebrew/opt/openssl@1.1:/opt/homebrew/opt/readline:/opt/homebrew/opt/sqlite:/opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /opt/homebrew/opt/openssl@1.1/lib/pkgconfig:/opt/homebrew/opt/readline/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/xz/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/13
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
ACLOCAL_PATH: /opt/homebrew/share/aclocal
PATH: /opt/homebrew/Library/Homebrew/shims/mac/super:/opt/homebrew/opt/pkg-config/bin:/opt/homebrew/opt/openssl@1.1/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/xz/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Gist log of the build [here](https://gist.github.com/NeilBetham/ae8d814f0c73bef5bf5f7e507a7064a4)

**Comment by dtrodrigues** [comment]
This seems like the likely culprit for `_ctypes` not building, and thus the `pip wheel` command failing: https://github.com/Homebrew/homebrew-core/issues/127316#issuecomment-1494467002

**Comment by ned-deily** [comment]
Sorry, I am unable to reproduce a build failure of Python (in particular, the latest 3.11) using macOS 13.3 and the latest Command Line Tools 14.3. I am not intimately familiar with how Homebrew chooses to build Python but, from a quick look at the logs provided here, I don't see anything obviously wrong with the Python portion, although it is more complex than a typical Python build on macOS. Again from a quick look, it appears the failure being reported here is in the building of the third-party `wheel` package, apparently as part of a source build of the `pip` package, neither of which is part of CPython itself. A Python source distribution does provide pre-built wheels of `pip` with its dependencies as part of the `ensurepip` module but it looks like Homebrew chooses to build `pip` and its dependencies from source. I suspect that `setuptools` is being used as well, yet another third-party package not part of cpython itself. There could be some issue there explaining why the build of `wheel` could not find the `_ctypes` extention module which *is* part of a standard cpython build. I suggest you or somewhere on the Homebrew team try to further isolate the issue and perhaps check with the `pip` project. But, without digging a lot deeper into the whole Homebrew build process, there does not appear to be an obvious problem with Python itself.  Please re-open if you can provide more evidence of such a problem. Good luck!

**Comment by SMillerDev** [comment]
This error in the make step that is part of the provided logs would be in a part of the python source, correct?

```
/private/tmp/pythonA3.11-20230403-20233-1kvmvgu/Python-3.11.2/Modules/_ctypes/callbacks.c:438:18: error: call to undeclared function 'ffi_prep_closure'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        result = ffi_prep_closure(p->pcl_write, &p->cif, closure_fcn, p);
                 ^
1 error generated.

The necessary bits to build these optional modules were not found:
_tkinter                                                       
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


The following modules found by detect_modules() in setup.py have not
been built, they are *disabled* by configure:
_gdbm                                                          


Failed to build these modules:
_ctypes
```

**Comment by SMillerDev** [comment]
There are not, we rely on macOS to provide those in this build configuration. Those seem to be from libffi 3.4-rc1 and contain:
```
#if FFI_LEGACY_CLOSURE_API
FFI_AVAILABLE_APPLE_2019 FFI_API ffi_status
ffi_prep_closure (ffi_closure*,
		  ffi_cif *,
		  void (*fun)(ffi_cif*,void*,void**,void*),
		  void *user_data)
#if defined(__GNUC__) && (((__GNUC__ * 100) + __GNUC_MINOR__) >= 405)
  __attribute__((deprecated ("use ffi_prep_closure_loc instead")))
#elif defined(__GNUC__) && __GNUC__ >= 3
  __attribute__((deprecated))
#endif
  ;
#endif
```

**Comment by ned-deily** [comment]
> This error in the make step that is part of the provided logs would be in a part of the python source, correct?

Indeed, and my apologies for not noticing that. As Ronald notes, the most likely cause for that kind of problem would be either picking up a different libffi or a mismatch between the libffi headers and lib versions; I know there were problems with this in the past but much of the third-party lib configuring and linking has been enhanced in 3.11 and even more in the upcoming 3.12. It could also just be an issue with Apple Silicon builds. I'm on the road at the moment without access to a Apple Silicon Mac but can look at it further in a few days.

**Comment by SMillerDev** [comment]
No need to apologise, thanks for reopening. Let me know if you need me to check anything else.

**Comment by cho-m** [comment]
In CPython releases, what is the current state of `--with-system-ffi` flag?

In Homebrew's build, we are still using this, but I see that there are commits in `main` mentioning obsolete/removal.

I think the build error is due to `USING_APPLE_OS_LIBFFI` not being defined when `--with-system-ffi` is used, which ends up trying to compile code with `ffi_prep_closure` on Apple Silicon.

Was able to locally reproduce issue and then work around error by either:
- Manually adding `-DUSING_APPLE_OS_LIBFFI=1` to CFLAGS
- Removing `--with-system-ffi` build flag

**Comment by dvtoever** [comment]
I can confirm the above issue on a freshly installed MAC M2. `brew install python@3.10` yields the exact same error.

**Comment by ned-deily** [comment]
OK, I've finally had some time to look at this and I now understand what's going on. It's a somewhat complicated chain of events but there is an easy fix: just remove the `--with-system-ffi` option from `./configure` in the Python 3.11 and earlier builds. That option doesn't really do anything anymore on macOS 11 and later systems except to introduce buggy behavior under certain conditions. In this case, it impacts builds for Apple Silicon Macs using Homebrew because, for some reason, the Homebrew version of `pkg-config` provides a default configuration file for the default Apple-provided `libffi` and that triggers the bug that results in the `-DUSING_APPLE_OS_LIBFFI=1` macro not being properly added by Python's `setup.py` to the C compile commands for the `_ctype` module. I'm guessing that perhaps supplying this default definition for the system `libffi` is a more recent change in Homebrew such that this problem didn't show up before because, AFAICT, Python's buggy handling of `--with-system-ffi` on macOS hasn't changed for quite some time. In any case, the problem no longer exists in the upcoming Python 3.12 release as `--with-system-ffi` has been removed along with other major simplifications of how third-party libraries are configured.  We should provide some fix for 3.11 to prevent this bug from showing up but again the easiest workaround is simply to not use `--with-system-ffi`.

**Comment by ned-deily** [comment]
For the record, it's the combination of building for Apple Silicon Macs, specifying `--with-system-ffi`, and the fact that Homebrew returns pkg-config values for the Apple-supplied `libffi` that triggers this bug in the Python build system:

```
$ which pkg-config
/opt/homebrew/bin/pkg-config
$ /opt/homebrew/bin/pkg-config libffi --cflags-only-I
-I/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ffi
...
Parsing package file '/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/13/libffi.pc'
```
While that's a bit unusual, it shouldn't cause a problem but it does.

**Comment by SMillerDev** [comment]
Thanks for the suggestion, we'll implement it on the brew side. 

The pkg-config files have been there for a long time though (so much so that some other tools came to depend on them already).

**Comment by dtrodrigues** [comment]
Thanks for the investigation, removal of the `--with-system-ffi` flag has now been implemented in Homebrew. This issue can be closed.
