### ISSUE TITLE
Package error while importing

### ISSUE THREAD

**Issue by TharunParthiban** [python/cpython#103523]
Hello there!

While working with matplotlib library file I have encountered a new error which I cant understand!
 Here it is...

```plain
"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\__init__.py", line 246, in <module>
    _check_versions()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\__init__.py", line 240, in _check_versions
    module = importlib.import_module(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: The specified module could not be found."
```

If anyone knows how to fix it pls SHARE IT!

Thanks

**Comment by hugovk** [comment]
Hello! This is the issue tracker for CPython itself, it looks like you're better off reporting this to matplotlob. Their issue tracker is at https://github.com/matplotlib/matplotlib/issues
