### ISSUE TITLE
Memory error in operator.imod

### ISSUE THREAD

**Issue by baltsers** [python/cpython#103689]
# Bug report

We did a fuzzing test on Python3.9.15, a memory error happened.

```py
from operator import *
import operator


def demoFunc(arg1,arg2):
    try:
        ret = operator.imod(arg1, arg2)
    except (AssertionError, AttributeError, ImportError, LookupError, OSError, TypeError, ValueError) as e:
        pass

a= b"b'hhnZJ)uoMtf8CzdP#FBWi!RLUA3jIUIVB0bN%0333333333333r1YuFodxIuzDaR%N'"
b= ""
demoFunc(a,b)
```
[details](https://github.com/baltsers/fuzzVuls/tree/master/Python3.9.15/operator.imod)

## Bug info
```
    #1 0x499621 in PyMem_RawMalloc /root/CpyFuzz/experiments/Python-3.9.15/Objects/obmalloc.c:572:12
    #2 0x499621 in _PyObject_Malloc /root/CpyFuzz/experiments/Python-3.9.15/Objects/obmalloc.c:1645:11
    #3 0x41f83e in _PyBytes_FromSize /root/CpyFuzz/experiments/Python-3.9.15/Objects/bytesobject.c:81:31
    #4 0x41f83e in PyBytes_FromStringAndSize /root/CpyFuzz/experiments/Python-3.9.15/Objects/bytesobject.c:112:27
    #5 0x428506 in _PyBytesWriter_Resize /root/CpyFuzz/experiments/Python-3.9.15/Objects/bytesobject.c:3348:30
    #6 0x422faa in _PyBytesWriter_Prepare /root/CpyFuzz/experiments/Python-3.9.15/Objects/bytesobject.c:3401:15
    #7 0x422faa in _PyBytes_FormatEx /root/CpyFuzz/experiments/Python-3.9.15/Objects/bytesobject.c:962:23
    #8 0x6be614 in binary_op1 /root/CpyFuzz/experiments/Python-3.9.15/Objects/abstract.c:869:13
    #9 0x6c0394 in binary_iop1 /root/CpyFuzz/experiments/Python-3.9.15/Objects/abstract.c:1125:12
    #10 0x6c0394 in binary_iop /root/CpyFuzz/experiments/Python-3.9.15/Objects/abstract.c:1132:24
    #11 0x6c0394 in PyNumber_InPlaceRemainder /root/CpyFuzz/experiments/Python-3.9.15/Objects/abstract.c:1228:12
    #12 0x6fabbe in cfunction_vectorcall_FASTCALL /root/CpyFuzz/experiments/Python-3.9.15/Objects/methodobject.c:430:24
    #13 0x5635fd in _PyObject_VectorcallTstate /root/CpyFuzz/experiments/Python-3.9.15/./Include/cpython/abstract.h:118:11
    #14 0x5635fd in PyObject_Vectorcall /root/CpyFuzz/experiments/Python-3.9.15/./Include/cpython/abstract.h:127:12
    #15 0x5635fd in call_function /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:5077:13
    #16 0x55d8bf in _PyEval_EvalFrameDefault /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:3489:23
    #17 0x43336f in _PyEval_EvalFrame /root/CpyFuzz/experiments/Python-3.9.15/./Include/internal/pycore_ceval.h:40:12
    #18 0x43336f in function_code_fastcall /root/CpyFuzz/experiments/Python-3.9.15/Objects/call.c:330:24
    #19 0x5635fd in _PyObject_VectorcallTstate /root/CpyFuzz/experiments/Python-3.9.15/./Include/cpython/abstract.h:118:11
    #20 0x5635fd in PyObject_Vectorcall /root/CpyFuzz/experiments/Python-3.9.15/./Include/cpython/abstract.h:127:12
    #21 0x5635fd in call_function /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:5077:13
    #22 0x55d96e in _PyEval_EvalFrameDefault /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:3520:19
    #23 0x565264 in _PyEval_EvalFrame /root/CpyFuzz/experiments/Python-3.9.15/./Include/internal/pycore_ceval.h:40:12
    #24 0x565264 in _PyEval_EvalCode /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:4329:14
    #25 0x554061 in _PyEval_EvalCodeWithName /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:4361:12
    #26 0x554061 in PyEval_EvalCodeEx /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:4377:12
    #27 0x554061 in PyEval_EvalCode /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:828:12
    #28 0x5d2367 in run_eval_code_obj /root/CpyFuzz/experiments/Python-3.9.15/Python/pythonrun.c:1221:9
    #29 0x5d2367 in run_mod /root/CpyFuzz/experiments/Python-3.9.15/Python/pythonrun.c:1242:19
    #30 0x5d2367 in pyrun_file /root/CpyFuzz/experiments/Python-3.9.15/Python/pythonrun.c:1140:15
    #31 0x5cedc6 in pyrun_simple_file /root/CpyFuzz/experiments/Python-3.9.15/Python/pythonrun.c:450:13
    #32 0x5cedc6 in PyRun_SimpleFileExFlags /root/CpyFuzz/experiments/Python-3.9.15/Python/pythonrun.c:483:15
    #33 0x41e1fd in pymain_run_file /root/CpyFuzz/experiments/Python-3.9.15/Modules/main.c:373:15
    #34 0x41e1fd in pymain_run_python /root/CpyFuzz/experiments/Python-3.9.15/Modules/main.c:598:21
    #35 0x41e1fd in Py_RunMain /root/CpyFuzz/experiments/Python-3.9.15/Modules/main.c:677:5
    #36 0x41ea66 in pymain_main /root/CpyFuzz/experiments/Python-3.9.15/Modules/main.c:707:12
    #37 0x41ead2 in Py_BytesMain /root/CpyFuzz/experiments/Python-3.9.15/Modules/main.c:731:12
    #38 0x7f6044dfdc86 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c86)
```

# My environment

CPython: 3.9.15
Ubuntu: 18.0.4 (x86 64)

**Comment by sunmy2019** [comment]
The cause is the same as https://github.com/python/cpython/issues/103687

**Comment by ronaldoussoren** [comment]
@baltsers : All issues you are filing are basically the same: your script tries to allocate a very large amount of memory and fails because of that, either with a MemoryError if the process is constrained or by being killed by the OOM killer when it is not constrained.

This is not something the Python interpreter can guard against, memory allocations functions (e.g. malloc(3)) will succeed if there's free address space and the proces will crash later on when trying to use that address space when there's not enough available RAM and swap space.
