### ISSUE TITLE
argparse: add_mutually_exclusive_group() documented example is not working

### ISSUE THREAD

**Issue by eric-silk** [python/cpython#103711]
# Bug report
The example as provided [here](https://docs.python.org/3.10/library/argparse.html#mutual-exclusion) does not work.
```python
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="PROG")
    parser.add_mutually_exclusive_group()
    parser.add_argument("--foo", action="store_true")
    parser.add_argument("--bar", action="store_false")

    print(parser.parse_args([]))
    print(parser.parse_args(["--foo"]))
    print(parser.parse_args(["--bar"]))
    print(parser.parse_args(["--foo", "--bar"]))
```
prints:
```
Namespace(foo=False, bar=True)
Namespace(foo=True, bar=True)
Namespace(foo=False, bar=False)
Namespace(foo=True, bar=False)
```
rather than the expected:
```
usage: PROG [-h] [--foo | --bar]
PROG: error: argument --bar: not allowed with argument --foo
```
for the last parsing.

Similarly, adding `required=True` to the mutex group:
```python
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="PROG")
    parser.add_mutually_exclusive_group(required=True)
    parser.add_argument("--foo", action="store_true")
    parser.add_argument("--bar", action="store_false")

    print(parser.parse_args(["--foo"]))
    print(parser.parse_args(["--bar"]))
    print(parser.parse_args(["--foo", "--bar"]))
```
breaks parsing entirely:
```
Traceback (most recent call last):
  File "/tmp/mutex_arg.py", line 9, in <module>
    print(parser.parse_args(["--foo"]))
  File "/usr/lib/python3.10/argparse.py", line 1838, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 1871, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 2124, in _parse_known_args
    self.error(msg % ' '.join(names))
  File "/usr/lib/python3.10/argparse.py", line 2593, in error
    self.print_usage(_sys.stderr)
  File "/usr/lib/python3.10/argparse.py", line 2563, in print_usage
    self._print_message(self.format_usage(), file)
  File "/usr/lib/python3.10/argparse.py", line 2529, in format_usage
    return formatter.format_help()
  File "/usr/lib/python3.10/argparse.py", line 295, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.10/argparse.py", line 226, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.10/argparse.py", line 226, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.10/argparse.py", line 333, in _format_usage
    action_usage = format(optionals + positionals, groups)
  File "/usr/lib/python3.10/argparse.py", line 408, in _format_actions_usage
    raise ValueError(f'empty group {group}')
ValueError: empty group <argparse._MutuallyExclusiveGroup object at 0x7fa8389b3c70>
```
# Your environment

- CPython versions tested on: 3.10.6
- Operating system and architecture: Ubuntu 22.04, x86-64

# Extra
Happy to do some extra testing with different versions in a Docker env once I'm back in the office Monday, if that would be helpful.

**Comment by sobolevn** [comment]
Sorry, I am a bit confused.

I followed your link, but I don't see the code sample you are referrering to:
<img width="936" alt="Снимок экрана 2023-04-23 в 21 20 49" src="https://user-images.githubusercontent.com/4660275/233857828-052a201e-b59f-4908-ac93-0ff05bca547d.png">

Notice, that on my screenshot code correctly uses `group = parser.add_mutually_exclusive_group()`

I also cannot find any other locations with this code.

Can you please clarify?

**Comment by eric-silk** [comment]
Ah. Issue exists between chair and keyboard, I didn't parse the example correctly. No bug, thank you for taking the time to look at it!
