### ISSUE TITLE
Cannot run tests 

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#104070]
On current main, I got this:
```python3
 C:\Users\KIRILL-1\CLionProjects\cpython> ./python -m test -v test_typing
Running Debug|x64 interpreter...
== CPython 3.12.0a7+ (heads/issue-104057-dirty:d9931f6855, May 1 2023, 23:20:40) [MSC v.1933 64 bit (AMD64)]
== Windows-10-10.0.19043-SP0 little-endian
== Python build: debug
== cwd: C:\Users\KIRILL-1\CLionProjects\cpython\build\test_python_19412æ
== CPU count: 16
== encodings: locale=cp1251, FS=utf-8
0:00:00 Run tests sequentially
0:00:00 [1/1] test_typing
test test_typing crashed -- Traceback (most recent call last):
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\test\libregrtest\runtest.py", line 373, in _runtest_inner
    refleak = _runtest_inner2(ns, test_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\test\libregrtest\runtest.py", line 313, in _runtest_inner2
    the_module = importlib.import_module(abstest)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\importlib\__init__.py", line 124, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1332, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1305, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1276, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 841, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 400, in _call_with_frames_removed
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\test\test_typing.py", line 12, in <module>
    from unittest.mock import patch
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\unittest\mock.py", line 26, in <module>
    import asyncio
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\asyncio\__init__.py", line 8, in <module>
    from .base_events import *
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\asyncio\base_events.py", line 45, in <module>
    from . import staggered
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\asyncio\staggered.py", line 11, in <module>
    from . import tasks
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\asyncio\tasks.py", line 946, in <module>
    eager_task_factory = create_eager_task_factory(Task)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\asyncio\tasks.py", line 936, in create_eager_task_factory
    raise TypeError(
TypeError: Provided constructor does not support eager task execution

test_typing failed (uncaught exception)

== Tests result: FAILURE ==

1 test failed:
    test_typing

Total duration: 672 ms
Tests result: FAILURE
```

**Comment by JelleZijlstra** [comment]
Probably from #102853, cc @itamaro.

**Comment by Eclips4** [comment]
However.. I just rebuilt an interpreter and now tests are ok.
Please, add `pending` label until I find way to reproduce it =)

**Comment by JelleZijlstra** [comment]
Might be related to whether the `_asyncio` accelerator module exists? Just guessing.

**Comment by itamaro** [comment]
my guess: if you pulled main without rebuilding the interpreter, you got an old Task type from the accelerator module mixed with new eager task factory from the tasks python module

**Comment by Eclips4** [comment]
Yeah, @itamaro you're right! 
Sorry for making noise
