### ISSUE TITLE
issue while installing hashlib

### ISSUE THREAD

**Issue by wiredhikari** [python/cpython#104343]
# Bug report

On running`pip install hashlib`
I get 
```
hikar@wired:~/dev/indy-node$ pip install hashlib
Collecting hashlib
  Using cached hashlib-20081119.zip (42 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/hikar/.pyenv/versions/3.8.4/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-th8m83sc/hashlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-th8m83sc/hashlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-u6_xznrt
         cwd: /tmp/pip-install-th8m83sc/hashlib/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-th8m83sc/hashlib/setup.py", line 68
        print "unknown OS, please update setup.py"
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("unknown OS, please update setup.py")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 23.1.2 is available.
You should consider upgrading via the '/home/hikar/.pyenv/versions/3.8.4/bin/python3.8 -m pip install --upgrade pip' command.
hikar@wired:~/dev/indy-node$ 
```

- Operating system and architecture: ubuntu 22.04
- python - 3.8.4

**Comment by JelleZijlstra** [comment]
`hashlib` is in the standard library, so there's no need to `pip install` it; it should always be available. The package you get with `pip install hashlib` is outdated and not useful.
