### ISSUE TITLE
OSError and SegFault encountered when building p11-Kit against 32 bit Python-3.11.2 using 64 bit time flags

### ISSUE THREAD

**Issue by TabLand** [python/cpython#104351]
Hi Team,

I followed the instructions for Linux From Scratch (LFS) book version 11.3, which builds `p11-kit-0.24.1` using the following dependencies:

```
Python-3.11.2
meson-1.1.0
```

Most of the (userspace) packages have been build with the following 64-bit flags...
```
CPPFLAGS="-D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64"
```
... with the exception of the below packages:
```
binutils-2.40 (build fails, requires further investigation)
gcc-12.2.0 (not required)
grub-2.06 (LFS instructions explicitly advised not to)
linux-6.1.11 (not required)
```
The following error is encountered:
```
ijtaba@lfs:/sources/p11-kit-0.24.1$ mkdir p11-build && cd p11-build && meson --prefix=/usr --buildtype=release \ 
  -Dtrust_paths=/etc/pki/anchors && ninja
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 309, in run
    app.generate()
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 186, in generate
    self._generate(env)
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 194, in _generate
    mlog.debug('Build started at', datetime.datetime.now().isoformat())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 75] Value too large for defined data type

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
Segmentation fault
```
Able to replicate this issue in python, which suggests its not just tied to p11-kit:
```
ijtaba@lfs:/sources/cpython$ python3 -c 'import datetime; print(datetime.datetime.now())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 75] Value too large for defined data type
Segmentation fault
```
Found whilst preparing my environment to replicate issue #101732
Will investigate this further when I get a chance. I was not able to replicate this issue in `Python 3.12.0a7+`
```
ijtaba@lfs:/sources/cpython$ ./python -c 'import datetime; print(datetime.datetime.now())'
2023-05-10 13:10:25.833959
ijtaba@lfs:/sources/cpython$ ./python --version
Python 3.12.0a7+
```

**Comment by StanFromIreland** [comment]
I do not have a 32bit system at hand to try and reproduce this, but from the description it appears this does not occur for 3.12+, and so I assume this has been fixed?

Related: https://github.com/python/cpython/issues/101069

**Comment by TabLand** [comment]
> I do not have a 32bit system at hand to try and reproduce this, but from the description it appears this does not occur for 3.12+, and so I assume this has been fixed?
> 
> Related: https://github.com/python/cpython/issues/101069

Yes

**Comment by StanFromIreland** [comment]
Thank you for verifying.

Closing as there is nothing to be done for bugfix branches. If you experience this issue please update your Python version.
