### ISSUE TITLE
Tkinter: Tk 8.7 quotes pathnames in certain error messages

### ISSUE THREAD

**Issue by chrstphrchvz** [python/cpython#104494]
Tk 8.7 (as of https://core.tcl-lang.org/tk/info/2991150c09f6) adds quotes around window pathnames in a few error messages, including those triggered by two Tkinter tests, causing them to fail:

```
======================================================================
FAIL: test_pack_configure_in (test.test_tkinter.test_geometry_managers.PackTest.test_pack_configure_in)
----------------------------------------------------------------------
_tkinter.TclError: can't pack ".pack.a" inside itself

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/git/cpython/Lib/test/test_tkinter/test_geometry_managers.py", line 111, in test_pack_configure_in
    with self.assertRaisesRegex(TclError,
AssertionError: "can't pack .pack.a inside itself" does not match "can't pack ".pack.a" inside itself"

======================================================================
FAIL: test_place_configure_in (test.test_tkinter.test_geometry_managers.PlaceTest.test_place_configure_in)
----------------------------------------------------------------------
_tkinter.TclError: can't place ".!toplevel2.!frame2" relative to itself

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/git/cpython/Lib/test/test_tkinter/test_geometry_managers.py", line 295, in test_place_configure_in
    with self.assertRaisesRegex(TclError, "can't place %s relative to "
AssertionError: "can't place \.!toplevel2\.!frame2 relative to itself" does not match "can't place ".!toplevel2.!frame2" relative to itself"
```

### Linked PRs
* gh-104495
* gh-104569

**Comment by terryjreedy** [comment]
I have asked on the triager-coredev discord whether these prevent-future-bug issues should be considered enhancements or bugfixes (and eligible to be backported).  Even if we decide not an issue for 3.11, this will matter soon for 3.12, when 3.12.0b1 is released (a week?) and 'main' becomes the future 3.13.0.

**Comment by terryjreedy** [comment]
I now agree that we should backport all tests. See new tracking issue #104568.  Will immediately backport the PR here.
