### ISSUE TITLE
PEP 709 behavior change around mangling

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#104604]
Another bug with comprehension inlining.

I made the fuzzer (https://github.com/carljm/compgenerator/pull/1) use `__a` and `__b` as names in the hope of finding bugs around name mangling and got this one:

```python
class __a:
    __a = (1)[[__a for __b in [1]]] = 1
```

On #104602:

```pycon
>>> class __a:
...     __a = (1)[[__a for __b in [1]]] = 1
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in __a
TypeError: 'int' object does not support item assignment
```

On 3.11:
```pycon
>>> class __a:
...     __a = (1)[[__a for __b in [1]]] = 1
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in __a
  File "<stdin>", line 2, in <listcomp>
NameError: name '_a__a' is not defined. Did you mean: '_a__b'?
```

I think that means we're missing some name mangling, but haven't thought too deeply about this yet.

**Comment by JelleZijlstra** [comment]
cc @carljm

**Comment by JelleZijlstra** [comment]
Actually this is just class scoping change. It doesn't reproduce any more after #104528; looks like I forgot to merge that in before starting the fuzzer. Sorry for the noise.
