### ISSUE TITLE
package install fails with installed Visual Studio 2022 17.7.0 Preview 1.0

### ISSUE THREAD

**Issue by trivalik** [python/cpython#104617]
# Bug report

I have installed Visual Studio 2022 17.6.0 and Visual Studio 2022 17.7.0 Preview 1.0. When I try to run:

`pip install llama-cpp-python`

At time of bug report creation current version was 1.50 of the package.
it finds the preview and this fails. I would now to force to disable the use of preview but there is no option for it https://github.com/python/cpython/blob/main/Tools/c-analyzer/distutils/_msvccompiler.py#L72
Alternative solution would be to fix the build, maybe is something wrong in the generated vcxproj file.

I have another PC without the preview and all works.

Is this maybe a cmake problem?

# environment

Windows 10 22H2, x64
Visual Studio 2022 17.6.0, Visual Studio 2022 17.7.0 Preview 1.0, Visual Studio 2019 Build Tools 16.11.26
CPython versions tested on: 3.11.3

#log

```
 Not searching for unused variables given on the command line.
      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
      -- The C compiler identification is MSVC 19.37.32705.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.37.32705/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.37.32705.0
      CMake Warning (dev) at C:/Users/Triv/AppData/Local/Temp/pip-build-env-cywctzqz/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:168 (if):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at C:/Users/Triv/AppData/Local/Temp/pip-build-env-cywctzqz/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:189 (elseif):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.37.32705/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (7.4s)
      -- Generating done (0.0s)
      -- Build files have been written to: C:/Users/Triv/AppData/Local/Temp/pip-install-j_aln6oj/llama-cpp-python_50968eab11794303b019002623cbac90/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build
        Command:
          'C:\Users\Triv\AppData\Local\Temp\pip-build-env-cywctzqz\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90' -G 'Visual Studio 17 2022' --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.11.3 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\Triv\AppData\Local\Temp\pip-build-env-cywctzqz\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Program Files\Python311\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Program Files\Python311\Include' '-DPYTHON_LIBRARY:PATH=C:\Program Files\Python311\libs\python311.lib' '-DPython_EXECUTABLE:PATH=C:\Program Files\Python311\python.exe' '-DPython_ROOT_DIR:PATH=C:\Program Files\Python311' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Program Files\Python311\Include' '-DPython_LIBRARY:PATH=C:\Program Files\Python311\libs\python311.lib' '-DPython3_EXECUTABLE:PATH=C:\Program Files\Python311\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Program Files\Python311' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Program Files\Python311\Include' '-DPython3_LIBRARY:PATH=C:\Program Files\Python311\libs\python311.lib' -T v143 -A x64 -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
      -- The C compiler identification is MSVC 19.37.32705.0
      -- The CXX compiler identification is MSVC 19.37.32705.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.37.32705/bin/Hostx64/x64/cl.exe
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.37.32705/bin/Hostx64/x64/cl.exe - broken
      CMake Error at C:/Users/Triv/AppData/Local/Temp/pip-build-env-cywctzqz/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.37.32705/bin/Hostx64/x64/cl.exe"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: C:/Users/Triv/AppData/Local/Temp/pip-install-j_aln6oj/llama-cpp-python_50968eab11794303b019002623cbac90/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-8lmq0o

          Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Preview/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_da06d.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.7.0-preview-23226-04+0dbc421ea for .NET Framework
          Der Buildvorgang wurde am 18.05.2023 18:19:01 gestartet.

          Projekt "C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj" auf Knoten "1" (Standardziele).
          PrepareForBuild:
            Das Verzeichnis "cmTC_da06d.dir\Debug\" wird erstellt.
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: Das Zwischenverzeichnis oder das Ausgabeverzeichnis darf nicht im temporÃ¤ren Verzeichnis enthalten sein, da dies zu Problemen mit dem inkrementellen Build fÃ¼hren kann. [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
            Das Verzeichnis "C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\Debug\" wird erstellt.
            Das Verzeichnis "cmTC_da06d.dir\Debug\cmTC_da06d.tlog\" wird erstellt.
          InitializeBuildStatus:
            "cmTC_da06d.dir\Debug\cmTC_da06d.tlog\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
            Aktualisieren des Timestamps von "cmTC_da06d.dir\Debug\cmTC_da06d.tlog\unsuccessfulbuild".
          ClCompile:
            C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.37.32705\bin\HostX64\x64\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_da06d.dir\Debug\\" /Fd"cmTC_da06d.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\testCCompiler.c"
            Microsoft (R) C/C++-Optimierungscompiler Version 19.37.32705 fÃ¼r x64
            testCCompiler.c
            Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
            cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_da06d.dir\Debug\\" /Fd"cmTC_da06d.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\testCCompiler.c"
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: Die angegebene ausfÃ¼hrbare Datei der Aufgabe "CL.exe" konnte nicht ausgefÃ¼hrt werden. System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.dir\Debug\cmTC_da06d.tlog" konnte nicht gefunden werden. [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei Microsoft.Build.CPPTasks.TrackedVCToolTask.DeleteFiles(ITaskItem[] filesToDelete) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          Die Erstellung des Projekts "C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj" ist abgeschlossen (Standardziele) -- FEHLER.

          Fehler beim Buildvorgang.

          "C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj" (Standardziel) (1) ->
          (PrepareForBuild Ziel) ->
            C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: Das Zwischenverzeichnis oder das Ausgabeverzeichnis darf nicht im temporÃ¤ren Verzeichnis enthalten sein, da dies zu Problemen mit dem inkrementellen Build fÃ¼hren kann. [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]


          "C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj" (Standardziel) (1) ->
          (ClCompile Ziel) ->
            C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: Die angegebene ausfÃ¼hrbare Datei der Aufgabe "CL.exe" konnte nicht ausgefÃ¼hrt werden. System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.dir\Debug\cmTC_da06d.tlog" konnte nicht gefunden werden. [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei Microsoft.Build.CPPTasks.TrackedVCToolTask.DeleteFiles(ITaskItem[] filesToDelete) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]
          C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    bei Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-8lmq0o\cmTC_da06d.vcxproj]

              1 Warnung(en)
              1 Fehler

          Verstrichene Zeit 00:00:00.55





        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (project)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\Triv\AppData\Local\Temp\pip-build-env-cywctzqz\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
                ^^^^^^^^^^^^^^^
        File "C:\Users\Triv\AppData\Local\Temp\pip-build-env-cywctzqz\overlay\Lib\site-packages\skbuild\cmaker.py", line 357, in configure
          raise SKBuildError(msg)

      An error occurred while configuring with CMake.
        Command:
          'C:\Users\Triv\AppData\Local\Temp\pip-build-env-cywctzqz\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90' -G 'Visual Studio 17 2022' --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.11.3 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\Triv\AppData\Local\Temp\pip-build-env-cywctzqz\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Program Files\Python311\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Program Files\Python311\Include' '-DPYTHON_LIBRARY:PATH=C:\Program Files\Python311\libs\python311.lib' '-DPython_EXECUTABLE:PATH=C:\Program Files\Python311\python.exe' '-DPython_ROOT_DIR:PATH=C:\Program Files\Python311' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Program Files\Python311\Include' '-DPython_LIBRARY:PATH=C:\Program Files\Python311\libs\python311.lib' '-DPython3_EXECUTABLE:PATH=C:\Program Files\Python311\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Program Files\Python311' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Program Files\Python311\Include' '-DPython3_LIBRARY:PATH=C:\Program Files\Python311\libs\python311.lib' -T v143 -A x64 -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90
        Working directory:
          C:\Users\Triv\AppData\Local\Temp\pip-install-j_aln6oj\llama-cpp-python_50968eab11794303b019002623cbac90\_skbuild\win-amd64-3.11\cmake-build
      Please see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

**Comment by ronaldoussoren** [comment]
Could you check with the ``llama-cpp-python`` project as well? 

The project appears to use scikit-build (``skbuild``) and the build tool output in the original report is from that library, not the standard library.  In particular, ``skbuild`` does not seem to use distutils and does not retrieve compiler related information from ``sysconfig``.

**Comment by trivalik** [comment]
Thanks for pointing this out. Could not find really useful right now but:

The weird thing is that I cloned llama-cpp-python with submodules (next hard thing). Then pip install on local folder worked fine.
