### ISSUE TITLE
so i tried to make a discord bot but it always says<class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory

### ISSUE THREAD

**Issue by umxeno** [python/cpython#104859]
Traceback (most recent call last):
  File "C:\Users\x\Downloads\BoostBot\main.py", line 95, in <module>
    @bot.command(name="help", description="Display help menu")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\BoostBot\discord\bot.py", line 894, in decorator
    result = command(**kwargs)(func)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\BoostBot\discord\commands\core.py", line 1650, in decorator
    return cls(func, **attrs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\BoostBot\discord\commands\core.py", line 640, in __init__
    super().__init__(func, **kwargs)
  File "C:\Users\x\Downloads\BoostBot\discord\commands\core.py", line 181, in __init__
    from ..ext.commands.cooldowns import BucketType, CooldownMapping, MaxConcurrency
  File "C:\Users\x\Downloads\BoostBot\discord\ext\commands\__init__.py", line 18, in <module>
    from .flags import *
  File "C:\Users\x\Downloads\BoostBot\discord\ext\commands\flags.py", line 71, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1223, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory

**Comment by sunmy2019** [comment]
Check this https://docs.python.org/3/library/dataclasses.html#dataclasses.field

```py
@dataclass
class C:
    mylist: discord.utils._MissingSentinel = field(default_factory=discord.utils._MissingSentinel)
```

**Comment by Eclips4** [comment]
> > ```python
> > @dataclass
> > class C:
> >     mylist: discord.utils._MissingSentinel = field(default_factory=discord.utils._MissingSentinel)
> > ```
> 
> Still not working now it says NameError: name 'discord' is not defined but i installed it

Please, ask help here: https://discuss.python.org/c/users/7
This repo is intended as bug tracker for CPython development.
