### ISSUE TITLE
When setuptools is installed with old pyc, test_gdb_fails

### ISSUE THREAD

**Issue by hroncok** [python/cpython#104858]
# Bug report

We recently saw this failure in our Fedora build of Python 3.12.0b1:

```
======================================================================
FAIL: test_builtins_help (test.test_gdb.PrettyPrintTests.test_builtins_help)
Ensure that the new-style class _Helper in site.py can be handled
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Python-3.12.0b1/Lib/test/test_gdb.py", line 575, in test_builtins_help
    self.assertTrue(m,
AssertionError: None is not true : Unexpected rendering "'/usr/lib/python3.12/site-packages/_distutils_hack/__pycache__/__init__.cpython-312.pyc'"

----------------------------------------------------------------------
Ran 1 test in 1.012s
```

I investigated the problem and noticed python3-setuptools RPM is installed when we build Python (as it is now a dependency of glib2-devel which imports from distutils), but that RPM was built with 3.12.0a7, hence `/usr/lib/python3.12/site-packages/_distutils_hack/__pycache__/__init__.cpython-312.pyc` is a bytecode created with an old Python 3.12 version.

I've been able to reproduce this from a git checkout of v3.12.0b1 like this:

```
[cpython ((v3.12.0b1))]$ ./configure --config-cache --without-ensurepip && make -j ...
...
[cpython ((v3.12.0b1))]$ ./python -m test.regrtest test_gdb
0:00:00 load avg: 11.18 Run tests sequentially
0:00:00 load avg: 11.18 [1/1] test_gdb

== Tests result: SUCCESS ==

1 test OK.

Total duration: 15.6 sec
Tests result: SUCCESS

[cpython ((v3.12.0b1) %)]$ ./python -m ensurepip
Defaulting to user installation because normal site-packages is not writeable
...
Successfully installed pip-23.1.2

[cpython ((v3.12.0b1) %)]$ ./python -m pip install setuptools
Defaulting to user installation because normal site-packages is not writeable
...
Successfully installed setuptools-67.8.0

[cpython ((v3.12.0b1) %)]$ sudo mv ~/.local/lib/python3.12 /usr/local/lib/
[cpython ((v3.12.0b1) %)]$ sudo chown -R root:root /usr/local/lib/python3.12/
[cpython ((v3.12.0b1) %)]$ ./python -m pip list -v
Package    Version Location                                Installer
---------- ------- --------------------------------------- ---------
pip        23.1.2  /usr/local/lib/python3.12/site-packages pip
setuptools 67.8.0  /usr/local/lib/python3.12/site-packages pip

[cpython ((v3.12.0b1) %)]$ python3.12 --version
Python 3.12.0a7

[cpython ((v3.12.0b1) %)]$ sudo rm /usr/local/lib/python3.12/site-packages/_distutils_hack/__pycache__/__init__.cpython-312.pyc
[cpython ((v3.12.0b1) %)]$ sudo python3.12 -m compileall /usr/local/lib/python3.12/site-packages/_distutils_hack/__init__.py

[cpython ((v3.12.0b1) %)]$ ./python -m test.regrtest test_gdb
0:00:00 load avg: 1.97 Run tests sequentially
0:00:00 load avg: 1.97 [1/1] test_gdb
test test_gdb failed -- Traceback (most recent call last):
  File "/home/churchyard/Dokumenty/RedHat/cpython/Lib/test/test_gdb.py", line 575, in test_builtins_help
    self.assertTrue(m,
AssertionError: None is not true : Unexpected rendering "'/usr/local/lib/python3.12/site-packages/_distutils_hack/__pycache__/__init__.cpython-312.pyc'"

test_gdb failed (1 failure)

== Tests result: FAILURE ==

1 test failed:
    test_gdb

Total duration: 11.2 sec
Tests result: FAILURE
```

By editing the test this way:

```diff
         self.assertTrue(m,
-                        msg='Unexpected rendering %r' % gdb_repr)
+                        msg='Unexpected rendering %r' % gdb_output)
```

I see the gdb output was:

```
Breakpoint 1 at 0x594c10: file Python/bltinmodule.c, line 1221.

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.fedoraproject.org/>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Breakpoint 1, builtin_id (self=, v='/usr/local/lib/python3.12/site-packages/_distutils_hack/__pycache__/__init__.cpython-312.pyc') at Python/bltinmodule.c:1221
1221	    PyObject *id = PyLong_FromVoidPtr(v);
#0  builtin_id (self=, v='/usr/local/lib/python3.12/site-packages/_distutils_hack/__pycache__/__init__.cpython-312.pyc') at Python/bltinmodule.c:1221
```

# Your environment

- CPython versions tested on: 3.12.0b1
- Operating system and architecture: Fedora Linux x86_64

I know the reproducer is a bit far fetch, but it seems the test did not expect the Spanish Inquisition.

**Comment by hroncok** [comment]
FTR the ensurpip + sudo mv + compileall could be possibly replaced by sudo ensurpip'ing at start, but I didn't want to put anything in my /usr/local/bin etc.

**Comment by vstinner** [comment]
What's the status of this issue? Can you still reproduce it?

**Comment by hroncok** [comment]
I do not care about this issue anymore. This hasn't happened with newer versions of Python since.
