### ISSUE TITLE
Issue Multiprocessing while trainning agent with PPO

### ISSUE THREAD

**Issue by roeslib** [python/cpython#104966]
I am training my agent with PPO to pack boxes in a bin and since I increased the observation space from 1000 to 10800 and my action space from 100 to 540, the training lasted until the step 508832 and then stop executing the scripts. Before this changes the training lasted 10M steps. My operating system is Windows 10, my python version is 3.8.16, the number of parallel environment is 8,the total number of cores from my computer are 24 and from logic processors are 32 (I don’t know if I am using them apropiately). I got this error message:

```
global_step=5088032, episodic_return=1.592593
global_step=5088032, episodic_return=0.75
Traceback (most recent call last):
  File "C:\Users\Libia\anaconda3\envs\rlenvironment\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] Ha terminado la canalización

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 17, in <module>
    train_model(args, writer,run_name)
  File "C:\Users\Libia\anaconda3\envs\rlenvironment\PPO_3DCONV\modeltraining.py", line 102, in train_model
    next_obs, reward, done, info = envs.step(action.cpu().numpy())
  File "c:\users\libia\anaconda3\envs\rlenvironment\baselines\baselines\common\vec_env\vec_env.py", line 108, in step
    return self.step_wait()
  File "C:\Users\Libia\anaconda3\envs\rlenvironment\PPO_3DCONV\vectorizedenvs.py", line 126, in step_wait
    obs, reward, done, info = self.venv.step_wait()
  File "c:\users\libia\anaconda3\envs\rlenvironment\baselines\baselines\common\vec_env\vec_normalize.py", line 27, in step_wait
    obs, rews, news, infos = self.venv.step_wait()
  File "c:\users\libia\anaconda3\envs\rlenvironment\baselines\baselines\common\vec_env\shmem_vec_env.py", line 76, in step_wait
    outs = [pipe.recv() for pipe in self.parent_pipes]
  File "c:\users\libia\anaconda3\envs\rlenvironment\baselines\baselines\common\vec_env\shmem_vec_env.py", line 76, in <listcomp>
    outs = [pipe.recv() for pipe in self.parent_pipes]
  File "C:\Users\Libia\anaconda3\envs\rlenvironment\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\Libia\anaconda3\envs\rlenvironment\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
wandb:  View run Binpacking-v0__PPO1__1__1685045018 at: https://wandb.ai/libia-romero/ppo-bin-packing-details/runs/mgnpaijz
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
wandb: Find logs at: .\wandb\run-20230525_150340-mgnpaijz\logs
```

Please could someone explain me what is wrong? why do I get this error? how can I solve it?

**Comment by gaogaotiantian** [comment]
From the error message, it seems like your pipe was closed when your code tried to read from it. This is almost 100% user code/environment(out of memory?) issue. If you can reproduce this issue with a simple example(preferably without any 3rd party libraries), we'll take a look at it.

Raising an exception when something goes wrong is expected behavior, this is not a crash.

**Comment by ericvsmith** [comment]
This bug tracker is not the place to ask for help. Please ask your question at https://discuss.python.org/c/users/7
