### ISSUE TITLE
child process cannot put to multiprocessing.Queue on venv

### ISSUE THREAD

**Issue by bns-h-yasuhara** [python/cpython#105033]
Under the following conditions: 

- Windows
- Use the set_executable method
- Run on venv

The attached script(changed .txt extention) does not finish in the venv on Windows, becuase the child process cannot put objects to multiprocessing.Queue. 

Tested on: 
- CPython Version: 3.9.13, 3.11.3 
- Operation system: Windows10(x86-64) 

[pythontest3.txt](https://github.com/python/cpython/files/11583295/pythontest3.txt)

**Comment by ericvsmith** [comment]
What output do you get? What output do you expect?

**Comment by bns-h-yasuhara** [comment]
I run the attached scirpt on venv,  main process log is
```
(py311_env1) c:\temp\pythontest>python pythontest3.py
PYTHON_EXE_PATH = c:\Local\pyenv\py311_env1\Scripts\pythonw.exe
TempDir C:\Users\yasuhara\AppData\Local\Temp
--- parent queue info before ---
qsize=0, empty=True, full=False
sem=<BoundedSemaphore(value=1024, maxvalue=1024)>
semlock name=None, count=0, value=1024, maxvalue=1024, is_zero=False. is_mine=False, handle=300
---
pid = 11964
Traceback (most recent call last):
  File "c:\temp\pythontest\pythontest3.py", line 67, in <module>
    print(queue.get())
          ^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\multiprocessing\queues.py", line 103, in get
    res = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\multiprocessing\connection.py", line 215, in recv_bytes
    buf = self._recv_bytes(maxlength)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python311\Lib\multiprocessing\connection.py", line 304, in _recv_bytes
    waitres = _winapi.WaitForMultipleObjects(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
^C
```
sub process log (%TMPDIR%\pythontest3_child.txt) is
```
--- child queue info before ---
qsize=1024, empty=True, full=True
sem=<BoundedSemaphore(value=0, maxvalue=1024)>
semlock name=None, count=0, value=0, maxvalue=1024, is_zero=True. is_mine=False, handle=8
---
<class 'queue.Full'>
--- child queue info after exception ---
qsize=1024, empty=True, full=True
sem=<BoundedSemaphore(value=0, maxvalue=1024)>
semlock name=None, count=0, value=0, maxvalue=1024, is_zero=True. is_mine=False, handle=8
---
```
sub process threw queue.Full exception.  Why is the queue's Semaphore value "0"?



The attached scirpt run on direct python,  main process log is
```
c:\temp\pythontest>"c:\Program Files\Python311\python.exe" pythontest3.py
PYTHON_EXE_PATH = c:\Program Files\Python311\pythonw.exe
TempDir C:\Users\yasuhara\AppData\Local\Temp
--- parent queue info before ---
qsize=0, empty=True, full=False
sem=<BoundedSemaphore(value=1024, maxvalue=1024)>
semlock name=None, count=0, value=1024, maxvalue=1024, is_zero=False. is_mine=False, handle=420
---
pid = 16276
('hello',)
call p.join
exit code = 0
--- parent queue info after ---
qsize=0, empty=True, full=False
sem=<BoundedSemaphore(value=1024, maxvalue=1024)>
semlock name=None, count=-1, value=1024, maxvalue=1024, is_zero=False. is_mine=False, handle=420
---
```
sub process log (%TMPDIR%\pythontest3_child.txt) is
```
--- child queue info before ---
qsize=0, empty=True, full=False
sem=<BoundedSemaphore(value=1024, maxvalue=1024)>
semlock name=None, count=0, value=1024, maxvalue=1024, is_zero=False. is_mine=False, handle=8
---
--- child queue info after success ---
qsize=0, empty=True, full=False
sem=<BoundedSemaphore(value=1024, maxvalue=1024)>
semlock name=None, count=1, value=1024, maxvalue=1024, is_zero=False. is_mine=True, handle=8
---
```
This result is what I expect.

**Comment by ericvsmith** [comment]
I'm not sure if this is a bug in Python or not, but I suspect not. You should probably try asking on https://discuss.python.org/c/users/7 to see if anyone can help.
