### ISSUE TITLE
Cannot call `issubclass()` against `typing.Protocol` on Python 3.12

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#105237]
# Bug report

On Python 3.11, you can do this:

```pycon
>>> import typing
>>> issubclass(object, typing.Protocol)
False
```

But on Python 3.12 (following the backport of https://github.com/python/cpython/commit/c05c31db8c9dfd708b9857bb57f8e5f3ce40266d), this raises:

```pycon
>>> import typing
>>> issubclass(object, typing.Protocol)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\coding\cpython\Lib\typing.py", line 1797, in __subclasscheck__
    raise TypeError(
TypeError: Instance and class checks can only be used with @runtime_checkable protocols
```

The new behaviour doesn't make sense. That `TypeError` should only be triggered if a user is calling `issubclass()` against a _subclass_ of `typing.Protocol`. `typing.Protocol` itself should be exempted.

### Linked PRs
* gh-105239
* gh-105316

**Comment by AlexWaygood** [comment]
> While working on fixing the bug, we discovered another bug, where `issubclass(object, Protocol)` can sometimes evaluate to `True`. Unlike the original bug, this one reproduces all the way back to Python 3.8. It's now fixed on `main` and 3.12, but it might be good to see if we can fix it on 3.11 as well.

Well, but on the other hand, I'm hesitant to touch 3.11 here, given that it's an edge-case bug, and it's hard to do a proper fix that's not somewhat invasive. So, I'll close this for now. (But if somebody else disagrees and wants to have a go at fixing it on 3.11, happy to reopen.)
