### ISSUE TITLE
Merge `typing.Union` and `types.UnionType`

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#105499]
Currently, unions created through `typing.Union[A, B]` and through the PEP-604 syntax `A | B` are at runtime instances of completely different types, and they differ in exactly what elements they accept. This is confusing and makes it harder for users to detect unions at runtime.

I propose to proceed in two steps:

1. Make `typing.Union` an alias for `types.UnionType` and make it so `types.UnionType[A, B]` works, accepting the same types `Union` accepts now.
2. Loosen the rules for what the `|` operator accepts to accept more types that are commonly used in unions.

### Linked PRs
* gh-105511
* gh-132061

**Comment by tibbe** [comment]
This broken an AST walker I had written for Python 3.9, after I upgraded all my `Union[X, Y]` to `X | Y`, something is expected to be purely syntactical change.

**Comment by MarsCapone** [comment]
Will this also fix the issue of `unsupported operand type(s) for |: 'str' and ...` when using a string reference of a type?

i.e. 

```python
class Foo:
    def get_self(self) -> "Foo" | None:
        pass

# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "<stdin>", line 2, in Foo
# TypeError: unsupported operand type(s) for |: 'str' and 'NoneType'

from typing import Union
class Foo:
    def get_self(self) -> Union["Foo", None]:
        pass

# no issues
```

**Comment by JelleZijlstra** [comment]
@MarsCapone, no, but other changes in Python 3.14 (PEP-649) will fix that case.

**Comment by hauntsaninja** [comment]
See also https://mypy.readthedocs.io/en/stable/runtime_troubles.html and `from __future__ import annotations`

**Comment by serhiy-storchaka** [comment]
I think this was a mistake. `types.UnionType` was intentionally named so to avoid confusion with `typing.Union` (see #88895
). `types.UnionType` should not be subscriptable because it is not generic type (and if it was a generic type, subscription would have different semantic than for `typing.Union`). `types.UnionType` corresponds to `typing._UnionGenericAlias`, not `typing.Union`.
