### ISSUE TITLE
`types.GenericAlias` has extra `__copy__` and `__deepcopy__` in `__dir__`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#105487]
Repro:

```python
>>> type A[X] = list[X]
>>> dir(A[int])
[..., '__copy__', '__deepcopy__', ...]
```

We can access all other attributes, but not `__copy__` and `__deepcopy__`:

```pytb
>>> A[int].__copy__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'types.GenericAlias' object has no attribute '__copy__'. Did you mean: '__doc__'?

>>> A[int].__deepcopy__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'types.GenericAlias' object has no attribute '__deepcopy__'
```

I am not quite sure what is the right thing to do here 🤔 

### Linked PRs
* gh-138578
* gh-138629
* gh-138640

**Comment by hugovk** [comment]
Thanks for the fix!

**Comment by asottile-sentry** [comment]
a little late to the party but `__bases__` appears to not work as well:

```python
>>> '__bases__' in dir(list[str])
True
>>> list[str].__bases__
Traceback (most recent call last):
  File "<python-input-15>", line 1, in <module>
    list[str].__bases__
AttributeError: 'types.GenericAlias' object has no attribute '__bases__'. Did you mean: '__args__'?
```

**Comment by sobolevn** [comment]
Looks like the linked PR does something completely different. I created a new one.

**Comment by sobolevn** [comment]
Thanks for the report!
