### ISSUE TITLE
Modernize `test_enum` by removing unused exception handling

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#105522]
Right now there are places in `test_enum` that for some reason contain code like https://github.com/python/cpython/blob/4ff5690e591b7d11cf11e34bf61004e2ea58ab3c/Lib/test/test_enum.py#L53-L76

For some reason we try to catch exceptions that won't ever happen (at least, they never *should* happen).

But, there are also regular `Enum`s that are defined without any exceptions: https://github.com/python/cpython/blob/4ff5690e591b7d11cf11e34bf61004e2ea58ab3c/Lib/test/test_enum.py#L78-L101

This is an artifact of 10+ age: https://github.com/python/cpython/commit/6b3d64ab5d7a448535a10811234d4ef99ddb54b0#diff-8467f9fbbff81abf26d87a8dbbf0e0c866157971948010e48cc73539251a9e4cR14

I propose to remove this and backport this PR to all supported Python versions.
PR will be available quite soon :)

### Linked PRs
* gh-105523

**Comment by ethanfurman** [comment]
@sobolevn You are correct that they never _should_ happen, but if they do none of the tests in the file will run, so there will be no information on which tests did pass.

Rather than get rid of the existing exception handling, please update the global enums that do not have it (and their tests, of course).

**Comment by sobolevn** [comment]
I finally had time to look at this. Here are my thoughts.

## Raising an error for "protected" Enum

I've added these lines to `EnumType.__prepare__`:

```python
if 'FloatStooges' in cls:
    raise RuntimeError('Example with FloatStooges', cls)
```

Here are the results:

```
======================================================================
ERROR: test_floatenum_fromhex (test.test_enum.TestSpecial.test_floatenum_fromhex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_enum.py", line 1268, in test_floatenum_fromhex
    h = float.hex(FloatStooges.MOE.value)
                  ^^^^^^^^^^^^^^^^
AttributeError: 'RuntimeError' object has no attribute 'MOE'

======================================================================
ERROR: test_pickle_float (test.test_enum.TestSpecial.test_pickle_float)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_enum.py", line 1429, in test_pickle_float
    raise FloatStooges
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_enum.py", line 62, in <module>
    class FloatStooges(float, Enum):
  File "/Users/sobolev/Desktop/cpython/Lib/enum.py", line 494, in __prepare__
    raise RuntimeError('Example with FloatStooges', cls)
RuntimeError: ('Example with FloatStooges', 'FloatStooges')

----------------------------------------------------------------------
```

I've noticed that around 10 tests do not reraise errors if `*Stooges` is an exception instance.

## Raising an error for an "unprotected" Enum

I went with `IntFlagStoogesWithZero`, so the whole suite failed with an error.

```
0:00:00 load avg: 0.91 [1/1] test_enum
test test_enum crashed -- Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/libregrtest/runtest.py", line 373, in _runtest_inner
    refleak = _runtest_inner2(ns, test_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython/Lib/test/libregrtest/runtest.py", line 313, in _runtest_inner2
    the_module = importlib.import_module(abstest)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython/Lib/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1293, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1266, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1237, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 841, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 996, in exec_module
  File "<frozen importlib._bootstrap>", line 400, in _call_with_frames_removed
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_enum.py", line 91, in <module>
    class IntFlagStoogesWithZero(IntFlag):
  File "/Users/sobolev/Desktop/cpython/Lib/enum.py", line 494, in __prepare__
    raise RuntimeError('Example with IntFlagStoogesWithZero', cls)
RuntimeError: ('Example with IntFlagStoogesWithZero', 'IntFlagStoogesWithZero')

test_enum failed (uncaught exception)

== Tests result: FAILURE ==

1 test failed:
    test_enum

Total duration: 49 ms
Tests result: FAILURE
```

## Conclusion

Indeed, the first case is much more informative and helpful. But, I need to:
1. Update all "unprotected" enum definions
2. Reraise exception whenever any of these enums are used in tests
