### ISSUE TITLE
Test failure in test_find_periodic_pattern in string_tests.py

### ISSUE THREAD

**Issue by sweeneyde** [python/cpython#105639]
A recent test failure:

```
FAIL: test_find_periodic_pattern (test.test_bytes.ByteArrayAsStringTest.test_find_periodic_pattern) (p='', text='')
Cover the special path for periodic patterns.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/test/string_tests.py", line 335, in test_find_periodic_pattern
    self.checkequal(reference_find(p, text),
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/test/string_tests.py", line 60, in checkequal
    self.assertEqual(
AssertionError: -1 != 0
```

The issue is `reference_find`:

```
        def reference_find(p, s):
            for i in range(len(s)):
                if s.startswith(p, i):
                    return i
            return -1
```

When `s == p == ''`, we get `for i in range(0)`, and then `-1` is returned instead of the actual result which should be 0.

### Linked PRs
* gh-105640

**Comment by terryjreedy** [comment]
My immediate question was "What could have happened that this should suddenly fail?"  The answer is "Nothing!"  For each CI run, reference_find is called 1000 times with random input.  There is obviously a non-zero probabilty of generating this corner case for which the test as a whole is wrong.  Hence we get an occasional bogus failure.  Some possible fixes:
* Do not generate this corner case; I have no idea how right now.
* Do not test this easy-to-detect case: `if not p or not text: continue` after `text` is generated, or perhaps `if not p: continue` after `p` is generated.
* Change reference_find to return 0 for this case, *making sure to not introduce another bug*.

The test was added in #86138, with PR by Dennis Sweeny and Tim Peters.

**Comment by hugovk** [comment]
Thanks for the report, however it's been subsequently resolved by PR https://github.com/python/cpython/pull/110170 and issue https://github.com/python/cpython/issues/110160.
