### ISSUE TITLE
Tkinter issue in Python-3.11.3 installed on WSL (Ubuntu 22.04)

### ISSUE THREAD

**Issue by mivanc** [python/cpython#105811]
I tried to install python 3.11.3 on my WSL (Ubuntu 22.04) with a command 
pyenv install 3.11.3

Downloading Python-3.11.3.tar.xz...
-> https://www.python.org/ftp/python/3.11.3/Python-3.11.3.tar.xz
Installing Python-3.11.3...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/matic/.pyenv/versions/3.11.3/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
WARNING: The Python tkinter extension was not compiled and GUI subsystem has been detected. Missing the Tk toolkit?
Installed Python-3.11.3 to /home/matic/.pyenv/versions/3.11.3

It looks like there is bug with thinker installation. I found the issue with older version previously on my older computer. Now I have a new computer and fresh installation of the whole environment. And the issue is still here. Any idea how to solve the issue?

**Comment by mivanc** [comment]
The issues with pyenv installation were fixed with following pre-installations before creating new version:

sudo apt-get install libffi-dev

sudo apt-get install lzma
sudo apt-get install liblzma-dev

sudo apt-get install python3-tk tk-dev
