### ISSUE TITLE
`unittest.mock.patch` fails for callables with multiple signatures in 3.11.4 (works in 3.11.3)

### ISSUE THREAD

**Issue by bersbersbers** [python/cpython#105904]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

```python
r"""
Bug.

Works:
pyenv local 3.11.3
pip install PySide6-Essentials==6.4.3
python C:\Code\project\bug.py

Fails:
pyenv local 3.11.4
pip install PySide6-Essentials==6.4.3
python C:\Code\project\bug.py
"""

import unittest.mock

unittest.mock.patch("PySide6.QtWidgets.QMessageBox.warning", autospec=True).__enter__()
```

Traceback:
```
Traceback (most recent call last):
  File "C:\Code\project\bug.py", line 17, in <module>
    unittest.mock.patch("PySide6.QtWidgets.QMessageBox.warning", autospec=True).__enter__()
  File "C:\Users\bers\.pyenv\pyenv-win\versions\3.11.4\Lib\unittest\mock.py", line 1539, in __enter__
    new = create_autospec(autospec, spec_set=spec_set,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bers\.pyenv\pyenv-win\versions\3.11.4\Lib\unittest\mock.py", line 2720, in create_autospec
    mock = Klass(parent=_parent, _new_parent=_parent, _new_name=_new_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bers\.pyenv\pyenv-win\versions\3.11.4\Lib\unittest\mock.py", line 2106, in __init__
    _safe_super(MagicMixin, self).__init__(*args, **kw)
  File "C:\Users\bers\.pyenv\pyenv-win\versions\3.11.4\Lib\unittest\mock.py", line 1106, in __init__
    _safe_super(CallableMixin, self).__init__(
  File "C:\Users\bers\.pyenv\pyenv-win\versions\3.11.4\Lib\unittest\mock.py", line 457, in __init__
    self._mock_add_spec(spec, spec_set, _spec_as_instance, _eat_self)
  File "C:\Users\bers\.pyenv\pyenv-win\versions\3.11.4\Lib\unittest\mock.py", line 523, in _mock_add_spec
    res = _get_signature_object(spec,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bers\.pyenv\pyenv-win\versions\3.11.4\Lib\unittest\mock.py", line 119, in _get_signature_object
    return func, inspect.signature(sig_func)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bers\.pyenv\pyenv-win\versions\3.11.4\Lib\inspect.py", line 3280, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bers\.pyenv\pyenv-win\versions\3.11.4\Lib\inspect.py", line 3028, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bers\.pyenv\pyenv-win\versions\3.11.4\Lib\inspect.py", line 2480, in _signature_from_callable
    raise TypeError(
TypeError: unexpected object [<Signature (parent: PySide6.QtWidgets.QWidget, title: str, text: str, button0: PySide6.QtWidgets.QMessageBox.StandardButton, button1: PySide6.QtWidgets.QMessageBox.StandardButton) -> int>, <Signature (parent: PySide6.QtWidgets.QWidget, title: str, text: str, buttons: PySide6.QtWidgets.QMessageBox.StandardButton = Instance(QMessageBox.StandardButton.Ok), defaultButton: PySide6.QtWidgets.QMessageBox.StandardButton = Instance(QMessageBox.StandardButton.NoButton)) -> PySide6.QtWidgets.QMessageBox.StandardButton>] in __signature__ attribute
```

The problem seems to be here:
https://github.com/python/cpython/blob/8bb16f665691b2869e107e180208d28b292bf3bd/Lib/inspect.py#L2473-L2483

In 3.11.3, `obj.__signature__` fails with an attribute error which is handled - patching works.
In 3.11.4, `obj.__signature__` is a list of two signatures, which fails the `isinstance` check - patching fails.

# Your environment

- CPython versions tested on: 3.11.4
- Operating system and architecture: Windows 10 21H2

**Comment by gaogaotiantian** [comment]
I don't think this is a CPython issue.

If you do

```python
import PySide6.QtWidgets

print(PySide6.QtWidgets.QMessageBox.warning.__signature__)
```

You'll find that `__signature__` is set on `PySide6.QtWidgets.QMessageBox.warning`, and it's a list of `Signature` objects. So `PySide6` probably presets the signature to it.

However, I don't believe a list of `Signature` objects is a valid value for `__signature__`. `__signature__` was introduced in https://peps.python.org/pep-0362/ and was designed to cache the `Signature` object.

I think this is a case where a thrid party library incorrectly uses the Python magics, which caused the exception you saw above.

**Comment by sobolevn** [comment]
I agree with @gaogaotiantian this signature is just invalid. Garbage in, garbage out.

**Comment by bersbersbers** [comment]
Thanks. In addition, this problem does not even appear in PySide6 v6.5.2.
