### ISSUE TITLE
dataclasses: frozen dataclasses with slots' `__setattr__` and `__delattr__` does not work.

### ISSUE THREAD

**Issue by avboag** [python/cpython#105936]
# Bug report

The check in frozen dataclasses' `__setattr__` and `__delattr__` does not work when `slots=True`:

```
@dataclass(frozen=True, slots=True)
class C:
    i: int

C(10).j = 5
```
crashes with
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 5, in __setattr__
TypeError: super(type, obj): obj must be an instance or subtype of type
```
instead of raising a FrozenInstanceError.

Likewise,

```
@dataclass(frozen=True, slots=True)
class C:
    i: int

class D(C):
    pass

D(10).j = 5
```

crashes with the same error instead of working.

### Linked PRs
* gh-105937
* gh-144021
* gh-148469
* gh-148476

**Comment by gpshead** [comment]
A 3.13 is up as a Draft PR because it requires more changes and backporting pieces of some other stuff that is already in 3.14 in order for it to work.

**Comment by gpshead** [comment]
all merged. thanks for the report, contributions and reviews.
