### ISSUE TITLE
failed tests in Lib/test/test_webbrowser.py

### ISSUE THREAD

**Issue by kr-g** [python/cpython#106009]
when running the tests in Lib/test/test_webbrowser.py i do get the following result

```
***patched 1
.....................***patched 1
***patched 1
.***patched 1
***patched 1
F***patched 1
F***patched 1
F***patched 1
.........
======================================================================
FAIL: test_environment_preferred (__main__.ImportTest.test_environment_preferred)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/benutzer/repo/cpython/Lib/test/test_webbrowser.py", line 327, in test_environment_preferred
    self.assertEqual(webbrowser.get().name, least_preferred_browser)
AssertionError: 'firefox' != 'opera'
- firefox
+ opera


======================================================================
FAIL: test_get (__main__.ImportTest.test_get)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/benutzer/repo/cpython/Lib/test/test_webbrowser.py", line 292, in test_get
    self.assertIsNone(webbrowser._tryorder)
AssertionError: ['firefox', 'firefox', 'xdg-open', 'gio', 'x-www-browser', 'konqueror', 'epiphany', 'chromium', 'opera', 'www-browser', 'elinks', 'lynx', 'xdg-open', 'gio', 'x-www-browser', 'konqueror', 'epiphany', 'chromium', 'opera'] is not None

======================================================================
FAIL: test_register (__main__.ImportTest.test_register)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/benutzer/repo/cpython/Lib/test/test_webbrowser.py", line 278, in test_register
    self.assertIsNone(webbrowser._tryorder)
AssertionError: ['firefox', 'firefox', 'xdg-open', 'gio', 'x-www-browser', 'konqueror', 'epiphany', 'chromium', 'opera', 'www-browser', 'elinks', 'lynx', 'xdg-open', 'gio', 'x-www-browser', 'konqueror', 'epiphany', 'chromium', 'opera'] is not None

----------------------------------------------------------------------
Ran 34 tests in 0.191s

FAILED (failures=3)
```

**Comment by terryjreedy** [comment]
What OS and Python release?

**Comment by kr-g** [comment]
i m using linux mint 
with build from https://github.com/kr-g/cpython/tree/kr-g-browser-incognito

```
cd ~/repo/cpython/
mkdir install
./configure --prefix ~/repo/cpython/install
make
make test
make install
...
./install/bin/python3 Lib/test/test_webbrowser.py 
```

**Comment by kr-g** [comment]
it might be fine on the build /test system ... i will give a try with my new tests on the build test system

**Comment by kr-g** [comment]
the webbrowser tests passed.
but patchcheck.py failed
https://dev.azure.com/Python/cpython/_build/results?buildId=130810&view=logs&j=256d7e09-002a-52d7-8661-29ee3960640e&t=3d7276d3-4e8d-5309-55ad-fb0b172d9925

**Comment by kr-g** [comment]
well...
i can live with that 
(that it doesnt run on my system... but on the build/ test system)

i let it up to you to close this, or follow up further

**Comment by terryjreedy** [comment]
The issue tracker is for bugs when running unpatched python.  If you create a branch, you have to fix the bug in your branch.  Anyway, patchcheck tells you what change you must make.  If you run it yourself on your machine, tools/patchcheck.py, I believe, it fixes your branch itself.  It is described in the devguide.  It is usually about trailing whitespace.
