### ISSUE TITLE
[match-case] Allow matching Union types

### ISSUE THREAD

**Issue by randolf-scholz** [python/cpython#106246]
# Feature or enhancement

Since python 3.10, `isinstance` and `issubclass` allow testing against `Union`-types ([PEP604](https://peps.python.org/pep-0604/)).
However, the same is not true for match-case.

# Pitch

`case klass():` should probably be 1:1 equivalent with `isinstance(x, klass):`.

```python
from typing import TypeAlias

Numeric: TypeAlias = int | float

assert isinstance(1.2, Numeric)  # ✔

match 1.2:
     case Numeric():  # TypeError: called match pattern must be a type
          pass
```

This carries extra benefits, as `TypeAliases` are kind of necessary to write legible code when working with large unions, such as e.g. `PythonScalar: TypeAlias = None | bool | int | float | complex | bool | str | datetime | timedelta`.

### Linked PRs
* gh-118525
* gh-118644

**Comment by sobolevn** [comment]
This can also play nicely with new `type` keyword.

```python
>>> type Numberic = int | str
>>> match 1:
...    case Numeric():
...       print(1)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: called match pattern must be a class
```

Also `isinstance()` is not supported for this form of `TypeAlias`es, but support for old ones:

```python
>>> isinstance(1, Numeric)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

>>> Numeric2 = int | float
>>> isinstance(1, Numeric2)
True

>>> from typing import Union
>>> isinstance(1, Union[int, float])
True
```

However, there are couple of things that bother me:
1. `Numeric()` form, it seems logical for classes, but it feels a bit out of place for type aliases (personal opinion)
2. `Union` might contain things like `Literal` types, so `isinstance(1, Literal[1] | float)` won't work
3. What about unions that use string type notations? Like `Numeric = Union["SomeForwardRef", int]`?

**Comment by randolf-scholz** [comment]
@sobolevn As far as I understand it, `isinstance(obj, Union[x, y, z])` is equivalent to `isinstance(obj, (x, y, z))` is equivalent to `isinstance(obj, x) or isinstance(obj, y) or isinstance(obj, z)`. So if members of the Union-type are not eligible for `isinstance` checks (such as e.g. `list[int]` or `Literal`), this is not covered.

**Comment by schiegl** [comment]
A workaround is to use `if isinstance`.

```py
MyType = str | int

match "some string":
    case a if isinstance(a, MyType):
        print("matched")
    # ... other patterns
    case _:
        print("no match")
```

**Comment by randolf-scholz** [comment]
@sobolevn I opened https://github.com/python/cpython/issues/113904 as a separate issue for `isinstance` calls with PEP 695 syntax.

**Comment by gvanrossum** [comment]
This is for 3.14 right? There’s no time for 3.13.

**Comment by randolf-scholz** [comment]
There are some open questions:

1. should it support subpatterns (without, I think it's a pretty pointless feature)
2. How does it interact with PEP695 style type aliases.

Current situation:

```python
match node:
    case ast.FunctionDef(name=name, body=body) | ast.AsyncFunctionDef(name=name, body=body):
        ...
```

What would be nice to have:

```python
FuncDef: TypeAlias = ast.FunctionDef | ast.AsyncFunctionDef

match node:
    case FuncDef(name=name, body=body):
        ...
```

But with PEP695-style type hints, if I follow the conclusion of #113904, we would have.

```python
type FuncDef = ast.FunctionDef | ast.AsyncFunctionDef

match node:
    case FuncDef.__value__(name=name, body=body):
       ...
```

which looks kinda funny.

**Comment by gvanrossum** [comment]
So are you planning to write a PEP about this? Given that the isinstance support was PEP 604, I think it makes sense to have a PEP for this as well. From the discussion above it's hard to extract the feature being proposed, and I don't want to have to learn it from the PR.

**Comment by randolf-scholz** [comment]
Currently, I don't have time for that, but I could write it if required. The feature is simply to allow matching class-patterns, when the class is given by an instance of `types.UnionType`.

One could also consider making a larger PEP for 3.14 with combining it with other proposed match-case improvements, such as [`__match__`](https://pyfound.blogspot.com/2023/05/the-python-language-summit-2023-pattern.html), or [matching literal sets](https://github.com/python/cpython/issues/107497).

**Comment by gvanrossum** [comment]
I am not a fan of "omnibus" PEPs. If you don't want to write a PEP, could you at least write up a concise specification for what you are proposing, which can be understood independently from the PR? I would prefer not to have to infer the intended semantics from the submitted code (I hope you understand). Once I understand the proposal I can give you a better recommendation about whether a PEP would be required or not.

**Comment by randolf-scholz** [comment]
# Draft PEP: Matching Union Types

## Abstract

This PEP proposes allowing union types to be used in structural pattern matching[^1].

## Motivation

PEP 604 introduced the `|` operator to create type unions, and allows its usage in `isinstance` and `issubclass` calls.

PEP 634 introduced structural pattern matching, which allows representing `isinstance` calls using the more powerful class-pattern syntax.

This PEP proposes to allow using union types in class patterns, mirroring their behavior as observed in `isinstance` calls.

As a motivating example, consider using the `ast` module to find all decorated functions in a Python source file. The corresponding `ast` node classes are `FunctionDef` and `AsyncFunctionDef`. To match both types of function definitions, one must currently either write two separate case clauses or use a union-pattern of class-patterns:

```python
import ast

for node in ast.walk(tree):
    match node:
        case (
            ast.FunctionDef(name=name, decorator_list=decorators)
            | ast.AsyncFunctionDef(name=name, decorator_list=decorators)
        ):
            print(f"Found function {name} with decorators {decorators}")
```

With this PEP, the same logic can be expressed more elegantly as:

```python
import ast

AnyFunctionDef = ast.FunctionDef | ast.AsyncFunctionDef

for node in ast.walk(tree):
    match node:
        case AnyFunctionDef(name=name, decorator_list=decorators):
            print(f"Found function {name} with decorators {decorators}")
```

This has four main advantages:

1.  It reduces the amount of boilerplate code needed to match multiple classes in a single `case` clause, making the code more readable and maintainable.
2.  It allows for easier extension and refactoring. If a class is to be added or removed from the selection of classes to match, instead of updating all existing `case` clauses across all files in the codebase, updating the union type definition is sufficient.
3.  It strengthens the consistency between the behavior of `isinstance` and class-pattern matching.
4.  It allows emulation of `@sealed` types proposed in[^2].

## Specification

This PEP modifies the logical flow of class-pattern matching[^3]. When `name_or_attr` is a union, the pattern is sequentially checked against each member of the union, returning either the first match or raising on the first encountered exception.

This makes matching a class pattern with union type essentially equivalent to matching the union-pattern of the class-pattern of the individual members:

```python
union = A | B | C
match arg:
    case union(foo=foo, bar=bar): ...
    # is essentially equivalent to:
    case A(foo=foo, bar=bar) | B(foo=foo, bar=bar) | C(foo=foo, bar=bar): ...
```

A small difference is that matching malformed union types such as `int | list[int]` may still succeed, whereas `case int() | list[int]():` would be an illegal pattern causing a `SyntaxError`.

Originally, PEP 604 specified that calls like `isinstance(5, int | list[str])` should always raise a `TypeError`, since the second argument is not an instance of `type` (but of `types.GenericAlias`). While this is the case in Python 3.10, this behavior was changed in Python 3.11, and a `TypeError` is only raised if no earlier legal member of the union produced a match. This PEP adopts the same behavior as `isinstance` for consistency. See[^4] and[^5] for more details.

## Examples

A simple example of matching a union type:

```python
IntOrStr = int | str
match "Hello":
    case IntOrStr(x):
        # will match, since str is a valid member of the union
        print(f"Matched string {x!r}")

match 3.14:
    case IntOrStr(x):
        # will not match, since float value is neither int nor str.
        ...
    case _:
        # will match, since the wildcard pattern matches everything
        print("Matched something else")
```

Matching union types with positional or keyword arguments is straightforward:

```python
import dataclasses

@dataclasses.dataclass
class Point2D:
    x: int
    y: int

@dataclasses.dataclass
class Point3D:
    x: int
    y: int
    z: int

AnyPoint = Point2D | Point3D
IntOrStr = int | str

match Point2D(1, 2):
    case AnyPoint(x, y):
        print(f"Matched Point({x}, {y})")  # Matched Point(1, 2)

match Point3D(1, 2, 3):
    case AnyPoint(x, y, z):
        # Will match the second member, since Point2D has no z component
        print(f"Matched Point({x}, {y}, {z})")  # Matched Point(1, 2, 3)

match Point3D(1, 2, 3):
    case AnyPoint(x, y, z=IntOrStr(value)):
        # No restriction on the subpatterns.
        print(f"Matched Point({x}, {y}, {value})")  # Matched Point(1, 2, 3)
```

Invalid class patterns within a union only raise exceptions if evaluated:

```python
Dims = int | tuple[int, ...]

match 1:
    case Dims() as one:
        # eagerly matches int, second union member is never tested
        print("Matched single dimension {one!r}.")

match (1, 2):
    case Dims() as many:
        # will produce a ``TypeError``, since tuple[int, ...] is not a valid class pattern
        print("Matched multiple dimensions {many!r}.")
```

## Reference Implementation

- A proposed implementation for `CPython` is available in[^6].

## How to Teach This

The reference implementation updates the documentation[^7] to describe the new behavior of class patterns with union types. Because this behavior aligns class patterns with the existing behavior of `isinstance` calls, it should be intuitive for users already familiar with structural pattern matching and Python's type system.

Moreover, since Python 3.14, `typing.Union` and `types.UnionType` have been unified[^8], eliminating concerns about runtime differences between the two forms of union types, which would have been needed to explain otherwise.

## Open Issues

Note that `TypeAliasType` introduced by PEP 695 is not supported in class patterns:

```python
type IntOrStr = int | str  # TypeAliasType, not UnionType

match "Hello":
    case IntOrStr():  # raises TypeError
        ...

match "Hello":
    case IntOrStr.__value__(value):  # holds the original UnionType
        # This is technically legal, but discouraged and likely unsupported by static type checkers.
        print("Matched {value!r}")  # Matched 'Hello'
```

However, the legacy `typing.TypeAlias` works as expected, since at runtime it produces a standard union type:

```python
from typing import TypeAlias

IntOrStr: TypeAlias = int | str
match "Hello":
    case IntOrStr(x):
        print(f"Matched {x!r}")  # Matched 'Hello'
```

Tools that automatically convert `TypeAlias` to `695` `TypeAliasType` may cause runtime failures in class patterns, although similar issues already exist when such aliases are used in `isinstance` calls.

## Copyright

This document is placed in the public domain or under the CC0-1.0-Universal license, whichever is more permissive.

## References

[^1]: \[match-case\] Allow matching Union types
    <https://github.com/python/cpython/issues/106246>

[^2]: Draft PEP: Sealed decorator for static typing
    <https://discuss.python.org/t/draft-pep-sealed-decorator-for-static-typing/49206>

[^3]: Class Patterns
    <https://docs.python.org/3/reference/compound_stmts.html#class-patterns>

[^4]: Speed up isinstance on union types
    <https://github.com/python/cpython/issues/91603>

[^5]: `isinstance(object, classinfo)`
    <https://docs.python.org/3/library/functions.html#isinstance>

[^6]: gh-106246: Allow the use of unions as match patterns
    <https://github.com/python/cpython/pull/118644>

[^7]: Class Patterns
    <https://docs.python.org/3/reference/compound_stmts.html#class-patterns>

[^8]: Merge `typing.Union` and `types.UnionType`
    <https://github.com/python/cpython/issues/105499>
