### ISSUE TITLE
`test_venv` failures on installed buildbots

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#106313]
# Bug report

`test_venv` has been failing consistently on the "[AMD64 Fedora Stable Clang Installed](https://buildbot.python.org/all/#/builders/363)" buildbot for the last month. The test failure is:

```pytb

======================================================================
ERROR: test_zippath_from_non_installed_posix (test.test_venv.BasicTest.test_zippath_from_non_installed_posix)
Test that when create venv from non-installed python, the zip path
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.13/test/test_venv.py", line 612, in test_zippath_from_non_installed_posix
    subprocess.check_call(cmd, env=child_env)
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.13/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.13/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.13/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.13/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/test_python_q98ubefs/tmpjf9pltrd/bin/python3'
======================================================================
FAIL: test_upgrade_dependencies (test.test_venv.BasicTest.test_upgrade_dependencies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.13/test/test_venv.py", line 236, in test_upgrade_dependencies
    builder.upgrade_dependencies(fake_context)
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.13/venv/__init__.py", line 459, in upgrade_dependencies
    self._call_new_python(context, '-m', 'pip', 'install', '--upgrade',
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.13/venv/__init__.py", line 355, in _call_new_python
    subprocess.check_output(args, **kwargs)
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.13/test/test_venv.py", line 222, in pip_cmd_checker
    self.assertEqual(
AssertionError: Lists differ: ['/tm[32 chars]w4/bin/python3', '-m', 'pip', 'install', '--upgrade', 'pip'] != ['/tm[32 chars]w4/bin/python3.13', '-m', 'pip', 'install', '--upgrade', 'pip']
First differing element 0:
'/tmp/test_python_q98ubefs/tmpcaooe7w4/bin/python3'
'/tmp/test_python_q98ubefs/tmpcaooe7w4/bin/python3.13'
- ['/tmp/test_python_q98ubefs/tmpcaooe7w4/bin/python3',
+ ['/tmp/test_python_q98ubefs/tmpcaooe7w4/bin/python3.13',
?                                                    +++
   '-m',
   'pip',
   'install',
   '--upgrade',
   'pip']
----------------------------------------------------------------------
Ran 27 tests in 14.253s
FAILED (failures=1, errors=1, skipped=2)
test test_venv failed
```

Cc. @vsajip for venv expertise. It looks like #103243 is probably to blame (cc. @artemmukhin).

**Comment by AlexWaygood** [comment]
Oh, I see @zooba already brought this up in https://github.com/python/cpython/issues/103224#issuecomment-1583141041. Closing as a duplicate of that issue.
