### ISSUE TITLE
Can't create virtual environment on Ubuntu, Python 3.13.0a0, No module named '_posixsubprocess'

### ISSUE THREAD

**Issue by bityob** [python/cpython#106663]
# Bug report

I'm trying to create a virtual environment and it doesn't work.

```
./python -m venv ../cpython-venv
```

Full output - 
```
$ ./python -m venv ../cpython-venv
Traceback (most recent call last):
  File "/home/bit/Code/cpython/Lib/runpy.py", line 189, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bit/Code/cpython/Lib/runpy.py", line 148, in _get_module_details
    return _get_module_details(pkg_main_name, error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bit/Code/cpython/Lib/runpy.py", line 112, in _get_module_details
    __import__(pkg_name)
  File "/home/bit/Code/cpython/Lib/venv/__init__.py", line 10, in <module>
    import subprocess
  File "/home/bit/Code/cpython/Lib/subprocess.py", line 104, in <module>
    from _posixsubprocess import fork_exec as _fork_exec
ModuleNotFoundError: No module named '_posixsubprocess'
```

# Your environment

- CPython versions tested on:
```
Python 3.13.0a0
```
- Commit d0972c77aa1cd5fe27618e82c10141a2bf157476
- Operating system and architecture:
```
Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Verified locally and it works fine with Python 3.12.0b3

**Comment by bityob** [comment]
Verified now again after building with last commit and it works fine, so I guess it was fixed already.

Current commit: e8ab0096a583184fe24dfbc39eff70d270c8e6f4
