### ISSUE TITLE
`datetime.fromtimestamp(t).astimezone()` fails for `0`<=`t`<`86400` in Windows

### ISSUE THREAD

**Issue by LefterisJP** [python/cpython#107078]
# Bug report

`dt.datetime.fromtimestamp(t).astimezone()` fails for `0`<=`t`<`86400` in Windows for at least python 3.9, 3.10, 3.11.
Works fine in Linux, Mac.

```python
>> import datetime as dt
>> dt.datetime.fromtimestamp(0)
datetime.datetime(1970, 1, 1, 1, 0)

>> dt.datetime.fromtimestamp(86400)
datetime.datetime(1970, 1, 2, 1, 0)

>> dt.datetime.fromtimestamp(0).astimezone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument

>> dt.datetime.fromtimestamp(86399).astimezone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument

>> dt.datetime.fromtimestamp(86400).astimezone()
datetime.datetime(1970, 1, 2, 1, 0, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600), 'W. Europe Standard Time'))
```

A screenshot also:
![F1qM1ZmXgAAVrTw](https://github.com/python/cpython/assets/1658405/5659938e-2523-4b48-98f2-dd7b4aeeed8c)

# Your environment

- CPython versions tested on: 3.9, 3.10, 3.11
- Operating system and architecture: Windows

# Additional information

This looks very very related to this issue: https://github.com/python/cpython/issues/73283 but now it seems to happen for `astimezone`.

### Linked PRs
* gh-107176

**Comment by littlebutt** [comment]
I think the bug was introduced by `_datetimemodule.c` here.
https://github.com/python/cpython/blob/7fc9be350af055538e70ece8d7de78414bad431e/Modules/_datetimemodule.c#L6336
If the `t` is not large enough, the `local` method will return -1 since it will minus an epoch time(62135683200).

**Comment by zooba** [comment]
I suspect the value `0` is important, as it's an obvious edge case (or null case). Investigating that revealed that the first value that works is `86400`, and so that's the range.

I guess people are less surprised that `-1` doesn't work? TBH, I'd be okay with making this calculation fully Python specific, rather than trying to use OS APIs, assuming we can find a migration path. The CRT emulation clearly isn't compatible enough, and the OS APIs are so much richer that they aren't really compatible either.

There was some discussion about adopting ICU for this kind of stuff... maybe if we even do that we can have consistent timezone handling?

**Comment by leon-adarcewicz** [comment]
Hi folks, 
I fail with same issue for `datetime.datetime(1900, 1, 1, 9, 0).astimezone(tz=None)` ==> `[Errno 22] Invalid argument`, 
so I wanted to check if the is some solution for this issue for windows users?

**Comment by wkoot** [comment]
Is this not a duplicate of https://github.com/python/cpython/issues/80620 ?

**Comment by sigma67** [comment]
It does seem to fail for every date before 1970 as well.

**Comment by vstinner** [comment]
Issue fixed by https://github.com/python/cpython/pull/143463.

```
Python 3.15.0a5+ (heads/main:f5685a266b2, Jan 15 2026, 10:57:22) [MSC v.1944 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime as dt
>>> dt.datetime.fromtimestamp(0).astimezone()
datetime.datetime(1970, 1, 1, 14, 0, tzinfo=datetime.timezone(datetime.timedelta(seconds=50400), 'Îles de la Ligne '))
>>> dt.datetime.fromtimestamp(86399).astimezone()
datetime.datetime(1970, 1, 2, 13, 59, 59, tzinfo=datetime.timezone(datetime.timedelta(seconds=50400), 'Îles de la Ligne '))
```
