### ISSUE TITLE
Logger error under Pythonw results in a crash and recursion error

### ISSUE THREAD

**Issue by ElliotGarbus** [python/cpython#107792]
# Bug report
Running under pythonw, log messages to stderr cause a crash with recursion.

The error messages:
```
Traceback (most recent call last):
  File "logging\__init__.py", line 1113, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1113, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:
...
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kivy\logger.py", line 310, in emit
  File "kivy\logger.py", line 284, in _configure
  File "logging\__init__.py", line 1489, in info
  File "logging\__init__.py", line 1634, in _log
  File "logging\__init__.py", line 1644, in handle
  File "logging\__init__.py", line 1706, in callHandlers
  File "logging\__init__.py", line 978, in handle
  File "logging\__init__.py", line 1118, in emit
  File "logging\__init__.py", line 1031, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1501, in warning
  File "logging\__init__.py", line 1634, in _log
  File "logging\__init__.py", line 1644, in handle
  File "logging\__init__.py", line 1706, in callHandlers
  File "logging\__init__.py", line 978, in handle
  File "logging\__init__.py", line 1118, in emit
  File "logging\__init__.py", line 1031, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1501, in warning
  File "logging\__init__.py", line 1634, in _log
  File "logging\__init__.py", line 1644, in handle
  File "logging\__init__.py", line 1706, in callHandlers
  File "logging\__init__.py", line 978, in handle
  File "logging\__init__.py", line 1118, in emit
  File "logging\__init__.py", line 1031, in handleError
...
RecursionError: maximum recursion depth exceeded
...
```

## Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the CPython issue tracker, and am confident this bug has not been reported before

## A clear and concise description of the bug
In pythonw, stderr is None.  This triggers a problem in the exception handling of the emit code in the logger. https://github.com/python/cpython/blob/0aa3b9d76c036fd306c0fd1c270d5d88d02962a1/Lib/logging/__init__.py#L1098
 

  ```py
 # The emit code in the standard library:

    def emit(self, record):
        """
        Emit a record.

        If a formatter is specified, it is used to format the record.
        The record is then written to the stream with a trailing newline.  If
        exception information is present, it is formatted using
        traceback.print_exception and appended to the stream.  If the stream
        has an 'encoding' attribute, it is used to determine how to do the
        output to the stream.
        """
        try:
            msg = self.format(record)
            stream = self.stream
            # issue 35046: merged two stream.writes into one.
            stream.write(msg + self.terminator)
            self.flush()
        except RecursionError:  # See issue 36272
            raise
        except Exception:
            self.handleError(record)
  ```
I believe the more correct solution is to handle the Attribute exception caused when sys.stderr is None.
```py

    def emit(self, record):
        """
        Emit a record.

        If a formatter is specified, it is used to format the record.
        The record is then written to the stream with a trailing newline.  If
        exception information is present, it is formatted using
        traceback.print_exception and appended to the stream.  If the stream
        has an 'encoding' attribute, it is used to determine how to do the
        output to the stream.
        """
        try:
            msg = self.format(record)
            stream = self.stream
            # issue 35046: merged two stream.writes into one.
            stream.write(msg + self.terminator)
            self.flush()
        except AttributeError:  # handle the Attribute error, return, ignoring the request.
            return # this would cover the case for pythonw or whenever sys.stderr is None
        except RecursionError:  # See issue 36272
            raise
        except Exception:
            self.handleError(record)
```
I would submit a PR - but I'm not confident I understand the logger with enough depth to not open up other issues.  There appears to be a number of issues that are related that this fix would address.

**Comment by sunmy2019** [comment]
> ```python
>         except AttributeError:  # handle the Attribute error, return, ignoring the request.
>             return # this would cover the case for pythonw or whenever sys.stderr is None
> ```

This is too wildcarded. How about something like

```py
            msg = self.format(record)
            stream = self.stream
            # issue 35046: merged two stream.writes into one.
            if stream is not None:
                stream.write(msg + self.terminator)
            self.flush()
```

**Comment by ElliotGarbus** [comment]
I managed to fix my issue by not adding the console handler to the logger when sys.stderr is None.
@sunmy2019 Your solution looks good to me. 
 I can close this issue or leave it open it is worth taking a closer look.

**Comment by sunmy2019** [comment]
I see. I think it can be left open. We can add checks here.

https://github.com/python/cpython/blob/0aa3b9d76c036fd306c0fd1c270d5d88d02962a1/Lib/logging/__init__.py#L1076-L1085

At least we can prevent `emit` itself from causing the recursion.

**Comment by ElliotGarbus** [comment]
Good idea.

**Comment by vsajip** [comment]
I think the solution used by @ElliotGarbus - to not add the console handler when running in `pythonw` - makes the most sense for the use case. I'm not against putting a check for a `None` value just before `self.stream = stream` - but there would also need to be a check in `setStream()`, and perhaps the check should be for `hasattr(stream, 'write')` rather than a simple check for `None`. Since this is a change in behavior (e.g. an exception will be raised by the check where one wasn't raised before) it seems like such a change would have to be _not_ backported.

**Comment by serhiy-storchaka** [comment]
Nothing to do on our side. The error is produced by third-party handler. Closed as not planned.
