### ISSUE TITLE
A bug about += and =....+... 

### ISSUE THREAD

**Issue by wuzeyuuu** [python/cpython#107765]
```pycon
>>> new
['instruction', 'input', 'output', 'instruction', 'input', 'output']
>>> new_sample
{'instruction': '今天日期为20190630,将下列文字转格式的json字典', 'input': 'macd金叉', 'output': {'R': 'OP', 'T': 'MACD金叉', 'KEY': 'MACD金叉'}}
>>> new = []
>>> new += new_sample
>>> new
['instruction', 'input', 'output']
>>> new = new_sample + []
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'dict' and 'list'
>>> new = new_sample + new
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'dict' and 'list'
```

Above is on debug mode, and I found that a little different between the two statements.

**Comment by AlexWaygood** [comment]
Hi! This isn't a bug in Python, I'm afraid. Please see https://discuss.python.org/t/difference-between-and-operator-in-python/ for a full explanation of this peculiarity in Python :)
