### ISSUE TITLE
test.test_asyncio.test_runners fails in "development mode"

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#107895]
```pytb
$ ./python -Xdev -m test test.test_asyncio.test_runners -m test_asyncio_run_debug
0:00:00 load avg: 2.08 Run tests sequentially
0:00:00 load avg: 2.08 [1/1] test.test_asyncio.test_runners
test test.test_asyncio.test_runners failed -- Traceback (most recent call last):
  File ".../Lib/test/test_asyncio/test_runners.py", line 104, in test_asyncio_run_debug
    asyncio.run(main(False))
  File ".../Lib/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File ".../Lib/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../Lib/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File ".../Lib/test/test_asyncio/test_runners.py", line 102, in main
    self.assertIs(loop.get_debug(), expected)
AssertionError: True is not False

test.test_asyncio.test_runners failed (1 failure)
...
```

### Linked PRs
* gh-108168
* gh-108196
* gh-108197

**Comment by xncbf** [comment]
I just posted a patch
