### ISSUE TITLE
test_flock/test_lockf are racy

### ISSUE THREAD

**Issue by andreas-schwab** [python/cpython#107851]
The tests test_flock and test_lockf are racy and fail spuriously.  The parent process trying to synchronize the subprocess may sleep up to max_delay=1.0 seconds between tries, while the subprocess locks the file at most sleep_time=0.2 seconds until it exits (and unlocks the file).  This may happen completely while the parent sleeps between two tries.

### Linked PRs
* gh-107931
* gh-121556
* gh-121585
* gh-121586

**Comment by Eclips4** [comment]
Hello!
Can you give an example of the failure of these tests?
Did you see failure at our buildbot fleet?

**Comment by andreas-schwab** [comment]
You get a timeout while waiting for the synchronisation.

**Comment by colesbury** [comment]
I've been seeing this fairly often in the nogil refleaks buildbot (even before we disabled the GIL in the CI).

For example, https://buildbot.python.org/all/#/builders/1287/builds/218/steps/5/logs/stdio

```
======================================================================
ERROR: test_flock (__main__.FNTLEINTRTest.test_flock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/buildarea/pull_request.itamaro-ubuntu-aws.refleak.nogil/build/Lib/test/_test_eintr.py", line 535, in test_flock
    self._lock(fcntl.flock, "flock")
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/buildarea/pull_request.itamaro-ubuntu-aws.refleak.nogil/build/Lib/test/_test_eintr.py", line 517, in _lock
    raise Exception("failed to sync child in %.1f sec" % dt)
Exception: failed to sync child in 300.4 sec
======================================================================
ERROR: test_lockf (__main__.FNTLEINTRTest.test_lockf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/buildarea/pull_request.itamaro-ubuntu-aws.refleak.nogil/build/Lib/test/_test_eintr.py", line 532, in test_lockf
    self._lock(fcntl.lockf, "lockf")
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/buildarea/pull_request.itamaro-ubuntu-aws.refleak.nogil/build/Lib/test/_test_eintr.py", line 517, in _lock
    raise Exception("failed to sync child in %.1f sec" % dt)
Exception: failed to sync child in 300.6 sec
```
