### ISSUE TITLE
Non-closed socket cannot be reused across different asyncio event loops

### ISSUE THREAD

**Issue by marcosatti** [python/cpython#108089]
### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.10, 3.11

### Operating systems tested on:

Windows 11 22H2

### Output from running 'python -VV' on the command line:

Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

### A clear and concise description of the bug:

Trying to quickly put together an application using a shell component (no asyncio support) and a IO driver component (asyncio support), without major refactoring. One way to do this is to reuse a socket opened at the start, and use it within the asyncio event loops spawned as part of when the shell commands execute.

At least on Windows, this isnt possible once the second event loop interacts with the socket, and throws an OSError ("parameter is incorrect"):
```python
Traceback (most recent call last):
...
  File "C:\Users\malsattima\Development\python-sandbox\async_socket_test.py", line 87, in <module>
    asyncio.run(main(port))
  File "C:\Users\malsattima\scoop\apps\python\current\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\malsattima\scoop\apps\python\current\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malsattima\scoop\apps\python\current\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\malsattima\Development\python-sandbox\async_socket_test.py", line 75, in main
    data = await reader.read(4096)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malsattima\scoop\apps\python\current\Lib\asyncio\streams.py", line 690, in read
    await self._wait_for_data('read')
  File "C:\Users\malsattima\scoop\apps\python\current\Lib\asyncio\streams.py", line 522, in _wait_for_data
    await self._waiter
  File "C:\Users\malsattima\scoop\apps\python\current\Lib\asyncio\proactor_events.py", line 705, in sock_recv
    return await self._proactor.recv(sock, n)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malsattima\scoop\apps\python\current\Lib\asyncio\windows_events.py", line 459, in recv
    self._register_with_iocp(conn)
  File "C:\Users\malsattima\scoop\apps\python\current\Lib\asyncio\windows_events.py", line 752, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] The parameter is incorrect
```

Adding some print statements, the `obj.fileno()` and `self._iocp` have valid values (and `self._iocp` is changing between event loops) - so not sure whats going on, seems like it should work.

Reproducable code sample:
```python
import asyncio
import socket
from contextlib import asynccontextmanager

class NonOwningTransport(asyncio.Transport):
    def __init__(self, sock: socket.socket, protocol: asyncio.Protocol) -> None:
        super().__init__()
        self._closing = False
        self._read_future: asyncio.Future | None = None
        self._sock = sock
        self._protocol = protocol
        self._ensure_reading_loop(None)
        self._protocol.connection_made(self)

    def _ensure_reading_loop(self, future: asyncio.Future | None) -> None:
        loop = asyncio.get_event_loop()

        if future is not None:
            assert future is self._read_future
            assert self._protocol is not None
            assert self._read_future.done()

            if (exception := self._read_future.exception()) is not None:
                self._closing = True
                self._protocol.connection_lost(exception)
            elif data := self._read_future.result():
                self._protocol.data_received(data)
                self._read_future = loop.create_task(loop.sock_recv(self._sock, 4096))
                self._read_future.add_done_callback(self._ensure_reading_loop)
            else:
                self._closing = True
                self._protocol.eof_received()
                self._protocol.connection_lost(None)
        else:
            self._read_future = loop.create_task(loop.sock_recv(self._sock, 4096))
            self._read_future.add_done_callback(self._ensure_reading_loop)

    def write(self, data: bytes) -> None:
        assert not self._closing
        self._sock.send(data)

    def is_closing(self) -> bool:
        return self._closing

    def close(self) -> None:
        assert self._protocol is not None
        assert self._read_future is not None
        self._closing = True
        self._read_future.remove_done_callback(self._ensure_reading_loop)
        self._read_future.cancel()
        self._protocol.connection_lost(None)

@asynccontextmanager
async def use_stream_wrapper(sock: socket.socket):
    loop = asyncio.get_event_loop()
    reader = asyncio.StreamReader(loop=loop)
    protocol = asyncio.StreamReaderProtocol(reader, loop=loop)
    writer = asyncio.StreamWriter(NonOwningTransport(sock, protocol), protocol, reader, loop)

    try:
        yield reader, writer
    finally:
        writer.close()

async def main(sock: socket.socket):
    async with use_stream_wrapper(sock) as reader_writer:
        reader, writer = reader_writer
        writer.write(b"ABC")
        data = await reader.read(4096)
        print(data)

sock = socket.create_connection(("localhost", 5015))
sock.setblocking(False)
asyncio.run(main(sock))
asyncio.run(main(sock))
```

Also using netcat as part of the testing (connection endpoint):
`nc -l -n -p 5015`

**Comment by gvanrossum** [comment]
Alas, asyncio wasn't implemented with your use case in mind, so I'm not surprised it doesn't work. I consider this a feature request, and not one with a lot of priority.

**Comment by marcosatti** [comment]
Bummer, thought that would be the case... I'll have to find another way then - cheers.
