### ISSUE TITLE
The file IO function--readline() can not circularly read more than 11145966 lines，it will output the error UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6

### ISSUE THREAD

**Issue by biuki4** [python/cpython#108177]
# Bug report

### Checklist

- [x] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.8, 3.10, 3.11

### Operating systems tested on:

Linux, Windows

### Output from running 'python -VV' on the command line:

python3 -VV Python 3.11.4 (main, Jun  7 2023, 12:45:49) [GCC 9.4.0]

### A clear and concise description of the bug:

I want to find ubuntu20 commit log that all have keywords--HID_QUIRK_NO_INIT_REPORTS,then write the the code.When use run the code ,it get the log.

### the first 10 loops log is this :

the remaining 90 loops are the same as this:

```
i= 0
Traceback (most recent call last):
  File "/home/y/code/toolScript/1.py", line 30, in fun
    line = logFile1.readline()
           ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3032: invalid start byte
beginNum: 0 linenum: 11145964 linenum-beginNum = 11145964
line:     Cc: devicetree-discuss@lists.ozlabs.org

i= 1
Traceback (most recent call last):
  File "/home/y/code/toolScript/1.py", line 30, in fun
    line = logFile1.readline()
           ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3031: invalid start byte
beginNum: 1 linenum: 11145966 linenum-beginNum = 11145965
line:     Cc: linux-kernel@vger.kernel.org

i= 2
Traceback (most recent call last):
  File "/home/y/code/toolScript/1.py", line 30, in fun
    line = logFile1.readline()
           ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3030: invalid start byte
beginNum: 2 linenum: 11145968 linenum-beginNum = 11145966
line: 

i= 3
Traceback (most recent call last):
  File "/home/y/code/toolScript/1.py", line 30, in fun
    line = logFile1.readline()
           ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3029: invalid start byte
beginNum: 3 linenum: 11145969 linenum-beginNum = 11145966
line: 

i= 4
Traceback (most recent call last):
  File "/home/y/code/toolScript/1.py", line 30, in fun
    line = logFile1.readline()
           ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3028: invalid start byte
beginNum: 4 linenum: 11145970 linenum-beginNum = 11145966
line: 

i= 5
Traceback (most recent call last):
  File "/home/y/code/toolScript/1.py", line 30, in fun
    line = logFile1.readline()
           ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3027: invalid start byte
beginNum: 5 linenum: 11145971 linenum-beginNum = 11145966
line: 

i= 6
Traceback (most recent call last):
  File "/home/y/code/toolScript/1.py", line 30, in fun
    line = logFile1.readline()
           ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3026: invalid start byte
beginNum: 6 linenum: 11145972 linenum-beginNum = 11145966
line: 

i= 7
Traceback (most recent call last):
  File "/home/y/code/toolScript/1.py", line 30, in fun
    line = logFile1.readline()
           ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3025: invalid start byte
beginNum: 7 linenum: 11145973 linenum-beginNum = 11145966
line: 

i= 8
Traceback (most recent call last):
  File "/home/y/code/toolScript/1.py", line 30, in fun
    line = logFile1.readline()
           ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3024: invalid start byte
beginNum: 8 linenum: 11145974 linenum-beginNum = 11145966
line: 

i= 9
Traceback (most recent call last):
  File "/home/y/code/toolScript/1.py", line 30, in fun
    line = logFile1.readline()
           ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3023: invalid start byte
beginNum: 9 linenum: 11145975 linenum-beginNum = 11145966
line: 

i= 10
Traceback (most recent call last):
  File "/home/y/code/toolScript/1.py", line 30, in fun
    line = logFile1.readline()
           ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3022: invalid start byte
beginNum: 10 linenum: 11145976 linenum-beginNum = 11145966
line: 
```

### the code is this :

```python
import traceback
logFile1 = open("ubuntu20.log", "r", encoding="utf8")
#logFile1 = open("2.log", "r", encoding="utf8")
logFile2 = open("1.log", "w", encoding="utf8")

def fun(beginNum=4):
    keyword = "HID_QUIRK_NO_INIT_REPORTS"
    num = 0
    #beginNum=4
    linenum = beginNum
    logFile1.seek(beginNum)
    line = logFile1.readline()
    try:
        while line:
            commit = ""
            if line[:7] == "commit ":
                #print(str(num) + line)
                num = num + 1
                commit = ""
                while line:
                    commit = commit + line
                    #print("linenum: " + str(linenum)+" "+ line)
                    line = logFile1.readline()
                    linenum = linenum + 1
                    if line[:7] == "commit ":
                        break
                        if keyword in commit:
                            logFile2.write(commit)
                        break
            else:
                #print("linenum: " + str(linenum)+" "+ line)
                line = logFile1.readline()
                linenum = linenum + 1
    except Exception as e:
        traceback.print_exc()
        print("beginNum: "+str(beginNum)+" linenum: " + str(linenum)+" linenum-beginNum = "+str(linenum-beginNum))
        print("line: "+line)

for i in range(100):
    print("i= "+str(i))
    fun(i)
logFile1.close()
logFile2.close()
```

### the log format:

```
commit 41906731c03fc437f8d93a030584a88f8bbd7a1a
Author: Luke Nowakowski-Krijger <luke.nowakowskikrijger@canonical.com>
Date:   2023-06-06 14:45:17

    UBUNTU: Ubuntu-5.4.0-152.169
    
    Signed-off-by: Luke Nowakowski-Krijger <luke.nowakowskikrijger@canonical.com>
```

### the all code test enviments:

The following environments all have this bug，the main test enviment is ubuntu with python3.11
Ubuntu20.04LTS: 5.4.0-139-generic
python version: 3.11.4 and 3.8.4 
arch: x64
the ubuntu on vmware16
Memory： 8g

windows10: 
python -VV: Python 3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)]
conda -V：conda 23.7.2
CPU	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
memory: 16.0 GB 
arch： x64
version	22H2
internal version version	19045.3324
Windows Feature Experience Pack 1000.19041.1000.0

the log is from ubuntu20 kernel git repo which I use git log --encoding="utf8" > ubuntu20.log to get in ubuntu20 system
https://kernel.ubuntu.com/git/ubuntu/ubuntu-focal.git/

the log link:

https://drive.google.com/file/d/1i8ojwp5IX-Ks-3MQQvGB1B9rLURQMrB7/view?usp=sharing

ps:  I tried to repeatedly write the line with the error 20000000 times, and then read it using this code without any bugs

**Comment by asottile** [comment]
the error is correct -- that log (despite requesting `--encoding=utf8` from `git log`) contains non-utf8 bytes at that position:

```
    From  "Uwe Kleine-K�nig" <u.kleine-koenig@pengutronix.de>:
```

**Comment by AA-Turner** [comment]
Closing per Anthony. You could use an [error handler](https://docs.python.org/3/library/codecs.html#error-handlers) to avoid this (e.g. ``open("ubuntu20.log", "r", encoding="utf8", errors="...")``).

A
