### ISSUE TITLE
`imaplib.IMAP4.error: None`

### ISSUE THREAD

**Issue by vpanteleev-sym** [python/cpython#108280]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]

### A clear and concise description of the bug:

```python
import imaplib

imaplib.IMAP4_SSL('outlook.office365.com', port=995)
```

Output:
```
Traceback (most recent call last):
  File "/home/vladimir/tmp/2023-08-22-scratch/11:33:20/./test.py", line 3, in <module>
    imaplib.IMAP4_SSL('outlook.office365.com', port=995)
  File "/usr/lib/python3.11/imaplib.py", line 1323, in __init__
    IMAP4.__init__(self, host, port, timeout)
  File "/usr/lib/python3.11/imaplib.py", line 205, in __init__
    self._connect()
  File "/usr/lib/python3.11/imaplib.py", line 253, in _connect
    raise self.error(self.welcome)
imaplib.IMAP4.error: None
```

Regardless of anything, I don't think `None` should show up as the error message.

**Comment by VPanteleev-S7** [comment]
> I haven't dug into it enough to know why it doesn't like the message returned by outlook.office365.com.

As I found out, I was accidentally using the POP3 port instead of the IMAP port, which probably explains why it raises an exception (though not the error message, of course).

**Comment by serhiy-storchaka** [comment]
Fixed in #152768. imaplib now reports a meaningful error for an invalid greeting instead of `error: None`.
