### ISSUE TITLE
tarfile.extract skips chmod when works in a podman container

### ISSUE THREAD

**Issue by omirochn** [python/cpython#108254]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.10, CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

### A clear and concise description of the bug:

```python
import tarfile
with tarfile.open("foo.tgz", "r", debug=9) as tar:
  tar.extractall("foo-dst")
```

Steps being in a podman container for ubu2204:
root@pod-ub22-scsel-icx-07:/netbatch# rm -rf foo*
root@pod-ub22-scsel-icx-07:/netbatch# touch foo.sh
root@pod-ub22-scsel-icx-07:/netbatch# chmod +x foo.sh
root@pod-ub22-scsel-icx-07:/netbatch# tar czf foo.tgz foo.sh
root@pod-ub22-scsel-icx-07:/netbatch# python3 -c 'import tarfile
> with tarfile.open("foo.tgz", "r", debug=9) as tar:
>   tar.extractall("foo-dst")'
foo.sh
tarfile: could not change owner
root@pod-ub22-scsel-icx-07:/netbatch# cd foo-dst/
root@pod-ub22-scsel-icx-07:/netbatch/foo-dst# ls -l
total 0
-rw-r--r-- 1 root nogroup 0 Aug 21 18:09 foo.sh
root@pod-ub22-scsel-icx-07:/netbatch/foo-dst# /bin/tar xzf ../foo.tgz --no-same-owner
root@pod-ub22-scsel-icx-07:/netbatch/foo-dst# ls -l
total 0
-rwxr-xr-x 1 root nogroup 0 Aug 21 18:08 foo.sh
root@pod-ub22-scsel-icx-07:/netbatch/foo-dst#

**Comment by omirochn** [comment]
BTW simple fix like the below works for me:
```
--- tarfile.py
+++ tarfile.py
@@ -2124,10 +2124,16 @@ class TarFile(object):
             self.makefile(tarinfo, targetpath)

         if set_attrs:
-            self.chown(tarinfo, targetpath, numeric_owner)
+            err = None
+            try:
+                self.chown(tarinfo, targetpath, numeric_owner)
+            except ExtractError as e:
+                err = e
             if not tarinfo.issym():
                 self.chmod(tarinfo, targetpath)
                 self.utime(tarinfo, targetpath)
+            if err:
+                raise err

     #--------------------------------------------------------------------------
     # Below are the different file methods. They are called via

```

```
root@pod-ub22-scsel-icx-07:/netbatch# python3 -c 'import tarfile
with tarfile.open("foo.tgz", "r", debug=9) as tar:
  tar.extractall("foo-dst")'
foo.sh
tarfile: could not change owner
root@pod-ub22-scsel-icx-07:/netbatch# ls -l foo-dst/
total 0
-rwxr-xr-x 1 root nogroup 0 Aug 21 18:08 foo.sh
```

**Comment by cheese** [comment]
I met the same issue when extracting [1] in Podman containers with Python 3.11.5 and 3.10.12.

When set `errorlevel`, a call trace is shown:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/tarfile.py", line 2546, in chown
    os.chown(targetpath, u, g)
OSError: [Errno 22] Invalid argument: './less-643/brac.c'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/./testextract.py", line 7, in <module> 
    tar.extractall()
  File "/usr/lib/python3.10/tarfile.py", line 2257, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.10/tarfile.py", line 2326, in _extract_one
    self._handle_nonfatal_error(e)
  File "/usr/lib/python3.10/tarfile.py", line 2320, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.10/tarfile.py", line 2418, in _extract_member
    self.chown(tarinfo, targetpath, numeric_owner)
  File "/usr/lib/python3.10/tarfile.py", line 2548, in chown
    raise ExtractError("could not change owner") from e
tarfile.ExtractError: could not change owner
```

[1] https://ftp.gnu.org/gnu/less/less-643.tar.gz
