### ISSUE TITLE
test_ssl fails with "env changed" on ARM64 Windows buildbot: thread doesn't catch TimeoutError

### ISSUE THREAD

**Issue by vstinner** [python/cpython#108342]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### A clear and concise description of the bug:

ARM64 Windows Non-Debug PR buildbot [build failed](https://buildbot.python.org/all/#/builders/738/builds/3479) with: test_ssl failed (**env changed**):

```
== CPython 3.13.0a0 (heads/refs/pull/108299/merge-dirty:5af459ef07, Aug 23 2023, 01:37:38) [MSC v.1936 64 bit (AMD64)]
== Windows-11-10.0.22621-SP0 little-endian
== Python build: debug
== cwd: R:\buildarea\pull_request.ambv-bb-win11.bigmem\build\build\test_python_12132�
== CPU count: 6
== encodings: locale=cp1252, FS=utf-8
0:00:00 Run tests in parallel using 4 child processes (timeout: 1 hour 15 min, worker timeout: 1 hour 20 min)
(...)
0:08:08 load avg: 0.81 [228/447/1] test_ssl failed (env changed) (32.5 sec) -- ...
(...)
test_https_client_non_tls_response_ignored (test.test_ssl.TestPreHandshakeClose.test_https_client_non_tls_response_ignored) ...

Warning -- Uncaught thread exception: TimeoutError
Exception in thread non_tls_http_RST_responder:
Traceback (most recent call last):
  File "R:\buildarea\pull_request.ambv-bb-win11.bigmem\build\Lib\threading.py", line 1059, in _bootstrap_inner
    self.run()
  File "R:\buildarea\pull_request.ambv-bb-win11.bigmem\build\Lib\test\test_ssl.py", line 4708, in run
    conn, address = self.listener.accept()
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\buildarea\pull_request.ambv-bb-win11.bigmem\build\Lib\socket.py", line 295, in accept
    fd, addr = self._accept()
               ^^^^^^^^^^^^^^
TimeoutError: timed out
ok
```

test.pythoninfo:

```
ssl.OPENSSL_VERSION: OpenSSL 3.0.9 30 May 2023
ssl.OPENSSL_VERSION_INFO: (3, 0, 0, 9, 0)
```

### Linked PRs
* gh-108344
* gh-108348
* gh-108349
* gh-108350
* gh-108351
* gh-108352
* gh-108370
* gh-108404
* gh-108405
* gh-108406
* gh-108407
* gh-108408

**Comment by vstinner** [comment]
Not sure if it's the same, but on Linux, I can reproduce an "env changed" failure:

```
$ ./python -m test test_ssl -u all --fail-env-changed -v -R 3:3 -m test_preauth_data_to_tls_server
(...)
Warning -- threading_cleanup() failed to cleanup 0 threads (count: 0, dangling: 2)
Warning -- Dangling thread: <SingleConnectionTestServerThread(preauth_data_to_tls_server, stopped 139945293178560)>
Warning -- Dangling thread: <_MainThread(MainThread, started 139945539692352)>
(...)
Tests result: ENV CHANGED
```
