### ISSUE TITLE
test_capi.test_watchers fails with "env changed" on "wasm32-emscripten node": Warning -- Unraisable exception

### ISSUE THREAD

**Issue by vstinner** [python/cpython#108373]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

### A clear and concise description of the bug:

Recent build: https://buildbot.python.org/all/#/builders/1050/builds/2826

Dictionary watcher tests using ``catch_unraisable_exception`` context manager fails on the "wasm32-emscripten node (pthreads) 3.x" buildbot: the exception was logged too late, after ``catch_unraisable_exception`` block.

Example of error:

```
test_dealloc_watcher_raises_error (test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error) ... Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function loop at 0x19e62a0>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
```

Full logs:

<details>

```
test_dealloc_watcher_raises_error (test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error) ... Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function loop at 0x19e62a0>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function nop at 0x17c5218>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function long_loop at 0x1628518>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function  at 0x19edb78>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x16431a0>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x19d4b50>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x17944b8>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x1860cf8>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x1860c80>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x185fec8>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x18960c0>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x194f980>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x18ee1b8>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x19240b8>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x168ff60>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x16c3df0>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x19d7f80>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x19fbce0>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x1986a38>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x19ed358>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x1983750>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x18d00a0>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x197cfe0>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x189bb00>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function TestPendingCalls.PendingTask.run_in_pending_call.<locals>.callback at 0x18529e8>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function WeakSet.__init__.<locals>._remove at 0x17015a0>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function many_vars at 0x189d770>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function  at 0x18d1bd8>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function  at 0x18159b8>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function  at 0x1696620>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
Warning -- Unraisable exception
Exception ignored in: 'PyFunction_EVENT_DESTROY watcher callback for <function  at 0x1872448>'
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node-pthreads/build/Lib/test/test_capi/test_watchers.py", line 532, in watcher
    raise MyError("testing 123")
test.test_capi.test_watchers.TestFuncWatchers.test_dealloc_watcher_raises_error.<locals>.MyError: testing 123
ok
```

</details>

**Comment by vstinner** [comment]
cc @brandtbucher @iritkatriel @brettcannon

**Comment by vstinner** [comment]
I didn't see this warning recently. If it occurs, a buildbot build should be marked as WARNINGS (orange). I close the issue.
