### ISSUE TITLE
makeunicodedata.py breaks on Unicode 15.1 draft

### ISSUE THREAD

**Issue by SnoopJ** [python/cpython#108531]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

N/A

### A clear and concise description of the bug:

Unicode 15.1.0 is [scheduled to come out](https://www.unicode.org/versions/Unicode15.1.0/) next month, and introduces a change to the `DerivedCoreProperties.txt` file in the Unicode Character Database (UCD) that breaks an assumption buried in `Tools/makeunicodedata.py`. Bumping the `UNIDATA_VERSION` and adding the new `CJK Ideograph Extension` to the list of known CJK ranges (normal maintenance when updating `unicodedata`, see diff below) and running the tool produces the following error:

```pytb
$ python3 Tools/unicode/makeunicodedata.py 
--- Reading UnicodeData.txt ...
Traceback (most recent call last):
  File "Tools/unicode/makeunicodedata.py", line 1385, in <module>
    maketables(1)
  File "Tools/unicode/makeunicodedata.py", line 121, in maketables
    unicode = UnicodeData(UNIDATA_VERSION)
  File "Tools/unicode/makeunicodedata.py", line 1109, in __init__
    for char, (p,) in UcdFile(DERIVED_CORE_PROPERTIES, version).expanded():
ValueError: too many values to unpack (expected 1)
```

<details><summary>click for Unicode 15.1.0 support diff</summary>

```diff
diff --git a/Tools/unicode/makeunicodedata.py b/Tools/unicode/makeunicodedata.py
index 41adff1e52..5baad261ad 100644
--- a/Tools/unicode/makeunicodedata.py
+++ b/Tools/unicode/makeunicodedata.py
@@ -44,7 +44,7 @@
 #   * Doc/library/stdtypes.rst, and
 #   * Doc/library/unicodedata.rst
 #   * Doc/reference/lexical_analysis.rst (two occurrences)
-UNIDATA_VERSION = "15.0.0"
+UNIDATA_VERSION = "15.1.0"
 UNICODE_DATA = "UnicodeData%s.txt"
 COMPOSITION_EXCLUSIONS = "CompositionExclusions%s.txt"
 EASTASIAN_WIDTH = "EastAsianWidth%s.txt"
@@ -108,6 +108,7 @@
     ('2B740', '2B81D'),
     ('2B820', '2CEA1'),
     ('2CEB0', '2EBE0'),
+    ('2EBF0', '2EE5D'),
     ('30000', '3134A'),
     ('31350', '323AF'),
 ]
```

</details>

Up until now, `DerivedCoreProperties.txt` has contained only binary character properties, but with 15.1.0 the file will also contain some entries for the non-binary property `Indic_Conjunct_Break` that break the tool's assumption about this homogeneity of properties.

Note that this tool has many assumptions about the property type contents of each file in the UCD of the same sort (which could break in the same way in the future), but I am filing this issue and corresponding PR specifically about the breakage caused by `Indic_Conjunct_Break` in the upcoming release.

### Linked PRs
* gh-108532

**Comment by SnoopJ** [comment]
Superceded by #109559
