### ISSUE TITLE
Program getting crashed after running the script (_tkinter.TclError:)

### ISSUE THREAD

**Issue by ghost** [python/cpython#108703]
# Crash report

### CPython versions tested on:

3.9

### Operating systems tested on:

macOS

### What happened?

```python
import turtle as t

t.forward(100)
```

### Error messages

```ptb
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "/Users/dileepkumarsharma/Desktop/Coding/Python/Turtle/turtle_new.py", line 3, in <module>
    t.forward(100)
  File "<string>", line 6, in forward
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/turtle.py", line 3813, in __init__
    Turtle._screen = Screen()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/turtle.py", line 3663, in Screen
    Turtle._screen = _Screen()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/turtle.py", line 3691, in __init__
    TurtleScreen.__init__(self, _Screen._canvas)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/turtle.py", line 996, in __init__
    self.clear()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/turtle.py", line 1028, in clear
    self.onclick(None, btn)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/turtle.py", line 1365, in onclick
    self._onscreenclick(fun, btn, add)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/turtle.py", line 669, in _onscreenclick
    self.cv.unbind("<Button-%s>" % num)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/turtle.py", line 422, in unbind
    self._canvas.unbind(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1397, in unbind
    self.tk.call('bind', self._w, sequence, '')
_tkinter.TclError: can't invoke "bind" command:  application has been destroyed
```

**Comment by terryjreedy** [comment]
A traceback is not a crash.  I don't know how you would be running tkinter with the system tk, if indeed you are, but as the warning suggests, it should not be used as it is buggy and prone to crashing.  In any case, 3.9 is no longer supported.

**Comment by ronaldoussoren** [comment]
The system version of Tk is too old (8.5.9) and buggy, that's why our own installers ship with a much newer version of Tk (8.6.13).  This is almost certainly a bug in the Tk library, not in the ``tkinter`` package.

As such I propose to close this issue a 3th party bug.

**Comment by chrstphrchvz** [comment]
> I don't know how you would be running tkinter with the system tk

As indicated from paths like `/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py`, this is because recent versions of Xcode command line tools still include Python 3.9 plus Tkinter (linked to the system Tk Cocoa 8.5.9).

On macOS 12 and 13, I find the system Tk to be unusable. In this example, Tk is stuck in an event loop somewhere. Closing the Tk window breaks out of that loop by causing the `application has been destroyed` error.
