### ISSUE TITLE
test_gdb fails on PPC64LE Fedora Stable Clang 3.x buildbot

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109053]
In PR #108999 (commit fbce43a251488f666be9794c908a6613bf8ae260), I skipped some test_gdb tests if gdb fails to retrieve the *frame* argument of _PyEval_EvalFrameDefault().

Here, the problem looks similar but different. gdb has 2 errors:

* ``Backtrace stopped: frame did not save the PC``
* ``Unable to locate python frame``

Log (reformatted to be more readable):

```
======================================================================
FAIL: test_pycfunction (test.test_gdb.PyBtTests.test_pycfunction) [_testcapi.meth_varargs]
Verify that "py-bt" displays invocations of PyCFunction instances
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-stable-ppc64le.clang/build/Lib/test/test_gdb.py", line 950, in test_pycfunction
    self.assertIn(f'<built-in method {func_name}', gdb_output)
AssertionError: '<built-in method meth_varargs' not found in 'Breakpoint 1 (meth_varargs) pending.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Breakpoint 1, meth_varargs (self=<module at remote 0x7fffea347890>, args=()) at ./Modules/_testcapimodule.c:2060
2060\t    return Py_BuildValue("NO", _null_to_none(self), args);
#0  meth_varargs (self=<module at remote 0x7fffea347890>, args=()) at ./Modules/_testcapimodule.c:2060
#1  PyModuleDef_Type ()
Backtrace stopped: frame did not save the PC
Unable to locate python frame
'

======================================================================
FAIL: test_pycfunction (test.test_gdb.PyBtTests.test_pycfunction) [_testcapi.meth_fastcall_keywords]
Verify that "py-bt" displays invocations of PyCFunction instances
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-stable-ppc64le.clang/build/Lib/test/test_gdb.py", line 950, in test_pycfunction
    self.assertIn(f'<built-in method {func_name}', gdb_output)
AssertionError: '<built-in method meth_fastcall_keywords' not found in 'Breakpoint 1 (meth_fastcall_keywords) pending.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Breakpoint 1, meth_fastcall_keywords (self=<module at remote 0x7fffea3478f0>, args=, nargs=0, kwargs=0x0) at ./Modules/_testcapimodule.c:2107
2107\t    PyObject *pyargs = _fastcall_to_tuple(args, nargs);
#0  meth_fastcall_keywords (self=<module at remote 0x7fffea3478f0>, args=, nargs=0, kwargs=0x0) at ./Modules/_testcapimodule.c:2107
#1  ?? ()
Unable to locate python frame
'
```

build: https://buildbot.python.org/all/#/builders/435/builds/3568

**Comment by vstinner** [comment]
> Note there is another open issue for this https://github.com/python/cpython/issues/104736

Oh right. I closed this issue as a duplicate of issue #104736.
