### ISSUE TITLE
test_asyncio: test_start_tls_server_1() fails randomly on the Cirrus CI FreeBSD job

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109051]
```
0:14:00 load avg: 2.96 Run tests in parallel using 4 child processes (timeout: 10 min, worker timeout: 15 min)
0:14:01 load avg: 2.96 [1/1/1] test.test_asyncio.test_sslproto failed (1 failure)
Re-running test.test_asyncio.test_sslproto in verbose mode (matching: test_start_tls_client_reg_proto_1, test_start_tls_client_reg_proto_1, test_start_tls_server_1)
test_start_tls_client_reg_proto_1 (test.test_asyncio.test_sslproto.ProactorStartTLSTests.test_start_tls_client_reg_proto_1) ... skipped 'Windows only'
test_start_tls_server_1 (test.test_asyncio.test_sslproto.ProactorStartTLSTests.test_start_tls_server_1) ... skipped 'Windows only'
test_start_tls_client_reg_proto_1 (test.test_asyncio.test_sslproto.SelectorStartTLSTests.test_start_tls_client_reg_proto_1) ... ok
test_start_tls_server_1 (test.test_asyncio.test_sslproto.SelectorStartTLSTests.test_start_tls_server_1) ... protocol.resume_writing() failed
protocol: <asyncio.sslproto.SSLProtocol object at 0x8417074e0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<polling, bufsize=0>>
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/Lib/asyncio/transports.py", line 300, in _maybe_resume_protocol
    self._protocol.resume_writing()
  File "/tmp/cirrus-ci-build/Lib/asyncio/sslproto.py", line 905, in resume_writing
    assert self._ssl_writing_paused
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Unexpected calls to loop.call_exception_handler():
[{'exception': AssertionError(),
  'message': 'protocol.resume_writing() failed',
  'protocol': <asyncio.sslproto.SSLProtocol object at 0x8417074e0>,
  'transport': <_SelectorSocketTransport closed fd=8>}]
FAIL
======================================================================
FAIL: test_start_tls_server_1 (test.test_asyncio.test_sslproto.SelectorStartTLSTests.test_start_tls_server_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/Lib/test/test_asyncio/functional.py", line 39, in tearDown
    self.fail('unexpected calls to loop.call_exception_handler()')
AssertionError: unexpected calls to loop.call_exception_handler()
----------------------------------------------------------------------
Ran 4 tests in 0.599s
FAILED (failures=1, skipped=2)
test test.test_asyncio.test_sslproto failed
1 test failed again:
    test.test_asyncio.test_sslproto
== Tests result: FAILURE then FAILURE ==
```

FreeBSD job: https://cirrus-ci.com/task/5957332299939840

### Linked PRs
* gh-109571
* gh-109603

**Comment by vstinner** [comment]
@emaste @sorcio @zware: I'm unable to reproduce this issue on my FreeBSD VM. Are you able to reproduce it?

**Comment by vstinner** [comment]
See also issue #108973: "test_asyncio: test_subprocess_consistent_callbacks() fails randomly".

**Comment by vstinner** [comment]
Cirrus CI has been fixed. I close the issue. The discussion can continue in https://github.com/python/cpython/pull/109603 if needed.

**Comment by vstinner** [comment]
test_asyncio pass on FreeBSD buildbots, and [Cirrus CI is shutting down](https://circleci.com/blog/cirrus-ci-alternative/).
