### ISSUE TITLE
Document that "multiprocessing.get_context()" is also setting the context globally

### ISSUE THREAD

**Issue by Delgan** [python/cpython#109070]
# Documentation

Hi.

It's not clear from the documentation that calling [`multiprocessing.get_context()`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.get_context) (with `method=None`) has the side effect of also setting the default context globally, preventing future usage of `multiprocessing.set_start_method()`.

```python
import multiprocessing

default_context = multiprocessing.get_context()  # "Fork" on Linux.
multiprocessing.set_start_method("spawn")  # Error.
```

Which causes:

```python
Traceback (most recent call last):
  File "/home/delgan/test.py", line 5, in <module>
    multiprocessing.set_start_method("spawn")  # Error raised.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

This is a surprising behavior because calling `multiprocessing.get_context("fork")` then `multiprocessing.set_start_method("spawn")` works perfectly fine. I assumed calling `get_context(method=None)` would just create a context using the default method (`"fork"` on Linux, `"spawn"` otherwise) but there is visibly more to it than that.

---

I have a library allowing user to specify the `multiprocessing.Context` of their choice:

```python
def function(context=None):
    if context is None:
        context = multiprocessing.get_context()
    pipe = context.Pipe()
    ...
```

This recipe looks correct, but it is not. It will cause a `RuntimeError` if the user or another third-party library tries to call `multiprocesing.set_start_method()` after using my function.

I'll probably need to refactor it to something like that:

```python
def function(context=None):
    if context is None:
        start_method = multiprocessing.get_start_method(allow_none=True)
        if start_method is not None:
            context = multiprocessing.get_context(start_method)
        elif os.name == "posix":
            context = multiprocessing.get_context("fork")
        else:
            context = multiprocessing.get_context("spawn")
    pipe = context.Pipe()
    ...
```

I wonder if there shouldn't be a method to retrieve the current context without setting one if there is none?
I would like to be able to use a `Context` just like if I was using `multiprocessing` directly.

### Linked PRs
* gh-109488
* gh-135678
* gh-136341
* gh-136343
* gh-136344

**Comment by gpshead** [comment]
> Would like to work on this

Feel free to go ahead and propose documentation updates in a PR.  Regardless of if we're able to change the side effect behavior in the future (the other issue), we should document the current actual behavior.

**Comment by aisk** [comment]
Maybe we can fix the side effect of this function, instead of document it.

**Comment by gpshead** [comment]
I think we still need to just document it rather than try to change it.  We depend on this otherwise unseemly default setting behavior.  https://github.com/python/cpython/pull/135678#discussion_r2168316922

**Comment by aisk** [comment]
Thank you for your review. I agree that we can't change the behavior easily, so we should just update the document.

There is already a PR #109070 to update the document, but it hasn't been active for a while, and the CLA seems not signed (or validated?) anymore, so I can't just continue the author's work. Therefore I created a new PR #136341 to address this.

**Comment by aisk** [comment]
Hi @gpshead I found that there are a lot of other method, especially creating shared types like `multiprocessing.Value`, will internally calls `get_context`, thus the default start method will be set. There already a issue https://github.com/python/cpython/issues/85222 for this.

Should we fix them, or just document the behaviors of these methods?

**Comment by gpshead** [comment]
I followed up over on https://github.com/python/cpython/issues/85222 but these are basically the same issue: insufficient docs.  lets document things properly.

thanks!
