### ISSUE TITLE
`site.py`: `sys.path` while invoking `addusersitepackages` is insufficient

### ISSUE THREAD

**Issue by arcivanov** [python/cpython#109117]
# Bug report

### Bug description:

1. User-local packages can depend on system packages in the environment.
2. `.pth` file in the user-local packages is entitled to import global system packages: https://github.com/python/cpython/blob/1ebe014d62a700514c7dce8fd0b4d6b6d7929835/Lib/site.py#L186
3. The order the `site.py` mutates `sys.path` is incorrect, while the final order of `sys.path` is correct: https://github.com/python/cpython/blob/1ebe014d62a700514c7dce8fd0b4d6b6d7929835/Lib/site.py#L602-L603

In `site.py` the final order of `sys.path` is `[<user-local packages>, <system packages>]`. 
However, the order in which those paths are added is wrong, it should be:
1. Line 600: sys.path = `[]`
2. Line 602: sys.path = `[<system packages>]`
3. Line 603: sys.path = `[<user-local packages>, <system packages>]`

Here's an example:

```bash
$ pip --version
pip 22.3.1 from /usr/lib/python3.11/site-packages/pip (python 3.11)
$ pwd
/home/arcivanov/.local/lib/python3.11/site-packages
$ cat /home/arcivanov/.local/lib/python3.11/site-packages/test_path.pth 
import sys;print(sys.path);import pip
$ python -c "import sys; print(sys.path); import pip"
['/usr/lib64/python311.zip', '/usr/lib64/python3.11', '/usr/lib64/python3.11/lib-dynload', '/home/arcivanov/.local/lib/python3.11/site-packages']
Error processing line 1 of /home/arcivanov/.local/lib/python3.11/site-packages/test_path.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 186, in addpackage
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'pip'

Remainder of file ignored
['', '/usr/lib64/python311.zip', '/usr/lib64/python3.11', '/usr/lib64/python3.11/lib-dynload', '/home/arcivanov/.local/lib/python3.11/site-packages', '/usr/lib64/python3.11/site-packages', '/usr/lib/python3.11/site-packages']
```

The easiest way to solve this is to first add paths of the system packages and then insert the paths of the user-local packages **before** system packages.

However, the current implementation with `known_paths` only designed for appending.

Discovered in https://github.com/karellen/wheel-axle-runtime/issues/10

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by arcivanov** [comment]
The workaround for this issue is demonstrated here: 

https://github.com/karellen/wheel-axle-runtime/blob/06114b38536bfe087cf72ea7c8086bcd7af1c29d/src/main/python/wheel_axle/runtime/__init__.py#L56-L62
