### ISSUE TITLE
test_site: test_underpth_basic() fails if the current directory is non-ASCII

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109237]
Failure on GHA Windows x64 CI with PR #109229 which runs test_site in a non-ASCII working directory:

```
FAIL: test_underpth_basic (test.test_site._pthFileTests.test_underpth_basic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_site.py", line 621, in test_underpth_basic
    self.assertEqual(
AssertionError: Lists differ: ['D:\[40 chars]_1460\udce6', 'D:\\a\\cpython\\cpython\\PCbuil[396 chars]18f'] != ['D:\[40 chars]_1460�', 'D:\\a\\cpython\\cpython\\PCbuild\\am[391 chars]18f']

First differing element 0:
'D:\\a\\cpython\\cpython\\build\\test_python_1460\udce6'
'D:\\a\\cpython\\cpython\\build\\test_python_1460�'

Diff is 690 characters long. Set self.maxDiff to None to see it. : sys.path is incorrect
```

build: https://github.com/python/cpython/actions/runs/6138224249/job/16654899364?pr=109229

### Linked PRs
* gh-109238
* gh-109239
* gh-109240

**Comment by vstinner** [comment]
Example:

```
vstinner@WIN C:\victor\python\main>mkdir héhé

vstinner@WIN C:\victor\python\main>cd héhé

vstinner@WIN C:\victor\python\main\héhé>..\python -m test test_site -v
(...)
======================================================================
FAIL: test_underpth_basic (test.test_site._pthFileTests.test_underpth_basic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\victor\python\main\Lib\test\test_site.py", line 621, in test_underpth_basic
    self.assertEqual(
AssertionError: Lists differ: ['C:\[19 chars]in\\h\udce9h\udce9', 'C:\\victor\\python\\main[361 chars]emp'] != ['C:\[19 chars]in\\héhé', 'C:\\victor\\python\\main\\PCbuild\[351 chars]emp']

First differing element 0:
'C:\\victor\\python\\main\\h\udce9h\udce9'
'C:\\victor\\python\\main\\héhé'

- ['C:\\victor\\python\\main\\h\udce9h\udce9',
?                              ^^^^^^ ^^^^^^

+ ['C:\\victor\\python\\main\\héhé',
?                              ^ ^

   'C:\\victor\\python\\main\\PCbuild\\amd64\\python313_d.zip',
   'C:\\victor\\python\\main\\PCbuild\\amd64',
   'C:\\victor\\python\\main\\Lib',
   'C:\\Users\\vstinner\\AppData\\Roaming\\Python\\Python313\\site-packages',
   'C:\\victor\\python\\main',
   'C:\\victor\\python\\main\\Lib\\site-packages',
   'C:\\Users\\vstinner\\AppData\\Local\\Temp\\tmpesrsy5ed',
   'C:\\Users\\vstinner\\AppData\\Local\\Temp'] : sys.path is incorrect

----------------------------------------------------------------------
Ran 32 tests in 2.619s

FAILED (failures=1, skipped=2)
(...)
```
