### ISSUE TITLE
test_eintr: test_flock() fails with: 0.19043820584192872 not greater than or equal to 0.2

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109592]
Failure on AMD64 RHEL8 3.x buildbot:

```
FAIL: test_flock (__main__.FNTLEINTRTest.test_flock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-x86_64/build/Lib/test/_test_eintr.py", line 526, in test_flock
    self._lock(fcntl.flock, "flock")
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-x86_64/build/Lib/test/_test_eintr.py", line 515, in _lock
    self.assertGreaterEqual(dt, self.sleep_time)
AssertionError: 0.19043820584192872 not greater than or equal to 0.2
```

build: https://buildbot.python.org/all/#/builders/185/builds/5045

dt is measured with ``time.monotonic()``. test.pythoninfo says:

```
time.get_clock_info(monotonic): namespace(implementation='clock_gettime(CLOCK_MONOTONIC)', monotonic=True, adjustable=False, resolution=1e-09)
```

``sleep_time = 0.2`` constant is used to call ``time.sleep(0.2)`` in a child process which is created after ``start_time = time.monotonic()``.

### Linked PRs
* gh-110102
* gh-110106
* gh-110107

**Comment by vstinner** [comment]
time.sleep() is implemented with clock_nanosleep() on this buildbot. configure says:

```
checking for clock_nanosleep... yes
```
