### ISSUE TITLE
test_concurrent_futures.test_wait: test_timeout() failed on ARM Raspbian 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109594]
The test uses sleep and timeout in seconds (6 and 7 seconds):

```py
    @support.requires_resource('walltime')
    def test_timeout(self):
        future1 = self.executor.submit(mul, 6, 7)
        future2 = self.executor.submit(time.sleep, 6) # <==== HERE

        finished, pending = futures.wait(
                [CANCELLED_AND_NOTIFIED_FUTURE,
                 EXCEPTION_FUTURE,
                 SUCCESSFUL_FUTURE,
                 future1, future2],
                timeout=5, # <=== HERE
                return_when=futures.ALL_COMPLETED)

        self.assertEqual(set([CANCELLED_AND_NOTIFIED_FUTURE,
                              EXCEPTION_FUTURE,
                              SUCCESSFUL_FUTURE,
                              future1]), finished)
        self.assertEqual(set([future2]), pending)
```

ARM Raspbian 3.x:

```
test_timeout (test.test_concurrent_futures.test_wait.ProcessPoolForkserverWaitTest.test_timeout) ... FAIL

Stdout:
12.34s 

(...)

FAIL: test_timeout (test.test_concurrent_futures.test_wait.ProcessPoolForkserverWaitTest.test_timeout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/buildbot/workers/3.x.gps-raspbian.nondebug/build/Lib/test/test_concurrent_futures/test_wait.py", line 128, in test_timeout
    self.assertEqual(set([CANCELLED_AND_NOTIFIED_FUTURE,
AssertionError: Items in the first set but not the second:
<Future at 0xf5fbdfc0 state=running>
```

build: https://buildbot.python.org/all/#/builders/424/builds/4964

### Linked PRs
* gh-110018
* gh-110021
* gh-110022

**Comment by vstinner** [comment]
Similar failure:

```
Test ``futures.as_completed`` timing out before ... 
  test_future_times_out (test.test_concurrent_futures.test_as_completed.ThreadPoolAsCompletedTest.test_future_times_out) [0]
Test ``futures.as_completed`` timing out before ... FAIL
0.37s test_no_timeout (test.test_concurrent_futures.test_as_completed.ThreadPoolAsCompletedTest.test_no_timeout) ... 0.00s ok

FAIL: test_future_times_out (test.test_concurrent_futures.test_as_completed.ThreadPoolAsCompletedTest.test_future_times_out) [0]
Test ``futures.as_completed`` timing out before
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/cpython/cpython/Lib/test/test_concurrent_futures/test_as_completed.py", line 60, in test_future_times_out
    self.assertEqual(completed_futures, already_completed)
AssertionError: Items in the first set but not the second:
<Future at 0x10559f8a0 state=finished returned NoneType>
```

buil (macOS): https://github.com/python/cpython/actions/runs/6242454682/job/16946423721?pr=109591
