### ISSUE TITLE
AssertionError: 'Europe' != 'MSK' when running `make test` on 3.12.0

### ISSUE THREAD

**Issue by SamuelMarks** [python/cpython#109692]
# Bug report

### Bug description:

```sh
./configure --with-lto --with-pydebug --enable-optimizations
make
make test
```

Running Ubuntu 23.10 with the 6.5.3 kernel.

Maybe relevant:
```console
$ locale
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by hugovk** [comment]
Please can you give more detail? Which test failed, and paste the full traceback.

**Comment by SamuelMarks** [comment]
```
0:07:15 load avg: 2.19 Re-running 1 failed tests in verbose mode in subprocesses
0:07:15 load avg: 2.19 Run tests in parallel using 18 child processes
0:07:16 load avg: 2.19 [1/1/1] test_email failed (1 failure)
Re-running test_email in verbose mode (matching: test_variable_tzname)
test_variable_tzname (test.test_email.test_utils.LocaltimeTests.test_variable_tzname) ... FAIL

======================================================================
FAIL: test_variable_tzname (test.test_email.test_utils.LocaltimeTests.test_variable_tzname)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Python-3.12.0rc3/Lib/test/support/__init__.py", line 867, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "Python-3.12.0rc3/Lib/test/test_email/test_utils.py", line 155, in test_variable_tzname
    self.assertEqual(t1.tzname(), 'MSK')
AssertionError: 'Europe' != 'MSK'
- Europe
+ MSK


----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
test test_email failed
1 test failed again:
    test_email

== Tests result: FAILURE then FAILURE ==

463 tests OK.

1 test failed:
    test_email

13 tests skipped:
    test.test_asyncio.test_windows_events
    test.test_asyncio.test_windows_utils test_dbm_ndbm test_devpoll
    test_gdb test_ioctl test_kqueue test_launcher test_msilib
    test_startfile test_winconsoleio test_winreg test_wmi

6 tests skipped (resource denied):
    test_ossaudiodev test_tix test_tkinter test_ttk test_winsound
    test_zipfile64

1 re-run test:
    test_email

Total duration: 7 min 16 sec
Total tests: run=41,391 failures=2 skipped=1,124
Total test files: run=478/483 failed=1 skipped=13 resource_denied=6 rerun=1
Result: FAILURE then FAILURE
make: *** [Makefile:1980: test] Error 2
```

**Comment by jspricke** [comment]
Can you test with 3.12.1? I can't reproduce it with that version.

**Comment by serhiy-storchaka** [comment]
Results for 3.12.0 are not relevant. Please test with 3.12.1.

**Comment by SamuelMarks** [comment]
```
== Tests result: SUCCESS ==

17 tests skipped:
    test.test_asyncio.test_windows_events
    test.test_asyncio.test_windows_utils test.test_gdb.test_backtrace
    test.test_gdb.test_cfunction test.test_gdb.test_cfunction_full
    test.test_gdb.test_misc test.test_gdb.test_pretty_print
    test_dbm_ndbm test_devpoll test_ioctl test_kqueue test_launcher
    test_msilib test_startfile test_winconsoleio test_winreg test_wmi

6 tests skipped (resource denied):
    test_ossaudiodev test_tix test_tkinter test_ttk test_winsound
    test_zipfile64

466 tests OK.

Total duration: 6 min 45 sec
Total tests: run=40,971 skipped=1,139
Total test files: run=483/489 skipped=17 resource_denied=6
Result: SUCCESS
```
