### ISSUE TITLE
distutils/util.py: AttributeError: module 'distutils' has no attribute '_DEPRECATION_MESSAGE'

### ISSUE THREAD

**Issue by bbobrov** [python/cpython#109604]
# Bug report

### Bug description:

When building `thrift` without gcc i ran into this: 
```
#8 55.91       During handling of the above exception, another exception occurred:
#8 55.91       
#8 55.91       Traceback (most recent call last):
#8 55.91         File "<string>", line 2, in <module>
#8 55.91         File "<pip-setuptools-caller>", line 34, in <module>
#8 55.91         File "/tmp/pip-install-xnm192dg/thrift_ab908bc240eb430b82670b05efbf48e0/setup.py", line 156, in <module>
#8 55.91           run_setup(False)
#8 55.91         File "/tmp/pip-install-xnm192dg/thrift_ab908bc240eb430b82670b05efbf48e0/setup.py", line 107, in run_setup
#8 55.91           setup(name='thrift',
#8 55.91         File "/var/lib/openstack/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
#8 55.91           return distutils.core.setup(**attrs)
#8 55.91         File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
#8 55.91           dist.run_commands()
#8 55.91         File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
#8 55.91           self.run_command(cmd)
#8 55.91         File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
#8 55.91           cmd_obj.run()
#8 55.91         File "/var/lib/openstack/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 399, in run
#8 55.91           self.run_command("install")
#8 55.91         File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
#8 55.91           self.distribution.run_command(command)
#8 55.91         File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
#8 55.91           cmd_obj.run()
#8 55.91         File "/var/lib/openstack/lib/python3.10/site-packages/setuptools/command/install.py", line 61, in run
#8 55.91           return orig.install.run(self)
#8 55.91         File "/usr/lib/python3.10/distutils/command/install.py", line 631, in run
#8 55.91           self.run_command(cmd_name)
#8 55.91         File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
#8 55.91           self.distribution.run_command(command)
#8 55.91         File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
#8 55.91           cmd_obj.run()
#8 55.91         File "/var/lib/openstack/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 15, in run
#8 55.91           self.byte_compile(outfiles)
#8 55.91         File "/usr/lib/python3.10/distutils/command/install_lib.py", line 140, in byte_compile
#8 55.91           byte_compile(files, optimize=self.optimize,
#8 55.91         File "/usr/lib/python3.10/distutils/util.py", line 423, in byte_compile
#8 55.91           msg = distutils._DEPRECATION_MESSAGE
#8 55.91       AttributeError: module 'distutils' has no attribute '_DEPRECATION_MESSAGE'
#8 55.91       [end of output]
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by zware** [comment]
Python 3.10 is in security-only maintenance, `distutils` has been (more or less) deprecated for over a decade, and `setuptools` does a lot of black magic to try to intercept `distutils` usage which seems like a likely source of this particular failure.

All that to say that I'm sorry, but there's nothing we can do about this here.  Python 3.12 will fix it once and for all by finally removing `distutils` completely :)
