### ISSUE TITLE
Failed with install `pip -e .` ('pkgutil' has no attribute 'ImpImporter')

### ISSUE THREAD

**Issue by Olegt0rr** [python/cpython#109779]
# Bug report

### Bug description:

Tried to install project dependencies with `pip -e .` and failed :(

### How to reproduce

1. Clone https://github.com/aiogram/aiogram
2. Run command `pip -e .`

#### Expected

Output (copied from python 3.11)
```
Successfully installed aiofiles-23.1.0 aiogram-3.1.0 aiohttp-3.8.5 aiosignal-1.3.1 annotated-types-0.5.0 async-timeout-4.0.3 attrs-23.1.0 certifi-2023.7.22 charset-normalizer-3.2.0 frozenlist-1.4.0 idna-3.4 magic-filter-1.0.11 multidict-6.0.4 pydantic-2.3.0 pydantic-core-2.6.3 typing-extensions-4.7.1 yarl-1.9.2
```

#### Actual

```
Traceback (most recent call last):
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/bin/pip", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    self.handle_pip_version_check(options)
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 179, in handle_pip_version_check
    session = self._build_session(
              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/network/session.py", line 343, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 188, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 183, in <genexpr>
    matches = (
              ^
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
    for dist in finder.find_eggs(location):
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 144, in find_eggs
    yield from self._find_eggs_in_dir(location)
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 111, in _find_eggs_in_dir
    from pip._vendor.pkg_resources import find_distributions
  File "/Users/t0rr/PycharmProjects/aiogram/.venv312/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

```

### CPython versions tested on:

 3.12.0rc3

### Operating systems tested on:

macOS Ventura 13.5.1 (22G90)

**Comment by AlexWaygood** [comment]
This is an issue with pip/setuptools, not CPython. See e.g. https://github.com/pypa/pip/issues/12179.
