### ISSUE TITLE
test_multiprocessing_fork.test_processes: test_rapid_restart() fails randomly with EOFError

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109712]
s390x Debian 3.x:

```
ERROR: test_rapid_restart (test.test_multiprocessing_fork.test_processes.WithProcessesTestManagerRestart.test_rapid_restart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-debian-z/build/Lib/test/_test_multiprocessing.py", line 3140, in test_rapid_restart
    manager.start()
  File "/home/dje/cpython-buildarea/3.x.edelsohn-debian-z/build/Lib/multiprocessing/managers.py", line 569, in start
    self._address = reader.recv()
                    ^^^^^^^^^^^^^
  File "/home/dje/cpython-buildarea/3.x.edelsohn-debian-z/build/Lib/multiprocessing/connection.py", line 251, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/home/dje/cpython-buildarea/3.x.edelsohn-debian-z/build/Lib/multiprocessing/connection.py", line 431, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/home/dje/cpython-buildarea/3.x.edelsohn-debian-z/build/Lib/multiprocessing/connection.py", line 400, in _recv
    raise EOFError
EOFError
```

build: https://buildbot.python.org/all/#/builders/49/builds/6632

I already saw this bug in 2017, test_rapid_restart() failing with EOFError:

* https://github.com/python/cpython/issues/75029
* https://github.com/python/cpython/issues/75252

See also old bugs about "address already in use":

* https://github.com/python/cpython/issues/51747 (2009)
* https://github.com/python/cpython/issues/76244 (2017)

**Comment by vstinner** [comment]
Similar error on aarch64 RHEL8 3.x:

```
0:01:08 load avg: 20.31 [453/467/1] test.test_multiprocessing_forkserver.test_threads failed (1 error) -- running (7): test_signal (43.6 sec), test.test_multiprocessing_forkserver.test_processes (42.8 sec), test.test_multiprocessing_spawn.test_processes (54.1 sec), test_capi (1 min 5 sec), test.test_asyncio.test_events (31.3 sec), test.test_gdb.test_pretty_print (1 min 4 sec), test_math (58.1 sec)
Process QueueManager-2:
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-aarch64/build/Lib/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-aarch64/build/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-aarch64/build/Lib/multiprocessing/managers.py", line 594, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-aarch64/build/Lib/multiprocessing/managers.py", line 159, in __init__
    self.listener = Listener(address=address, backlog=16)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-aarch64/build/Lib/multiprocessing/connection.py", line 464, in __init__
    self._listener = SocketListener(address, family, backlog)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-aarch64/build/Lib/multiprocessing/connection.py", line 607, in __init__
    self._socket.bind(address)
OSError: [Errno 98] Address already in use

test_abort (test.test_multiprocessing_forkserver.test_threads.WithThreadsTestBarrier.test_abort)

test_rapid_restart (test.test_multiprocessing_forkserver.test_threads.WithThreadsTestManagerRestart.test_rapid_restart) ... ERROR
Warning -- Dangling processes: {<ForkServerProcess name='QueueManager-2' pid=257193 parent=255153 stopped exitcode=1>}
(...)
Warning -- Dangling processes: {<ForkServerProcess name='QueueManager-2' pid=257193 parent=255153 stopped exitcode=1>}

======================================================================
ERROR: test_rapid_restart (test.test_multiprocessing_forkserver.test_threads.WithThreadsTestManagerRestart.test_rapid_restart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-aarch64/build/Lib/test/_test_multiprocessing.py", line 3141, in test_rapid_restart
    manager.start()
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-aarch64/build/Lib/multiprocessing/managers.py", line 569, in start
    self._address = reader.recv()
                    ^^^^^^^^^^^^^
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-aarch64/build/Lib/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-aarch64/build/Lib/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL8-aarch64/build/Lib/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError

----------------------------------------------------------------------
Ran 100 tests in 16.356s

FAILED (errors=1, skipped=23)
test test.test_multiprocessing_forkserver.test_threads failed
```

test_multiprocessing_forkserver passed when re-run.

build: https://buildbot.python.org/all/#/builders/529/builds/5076

**Comment by vstinner** [comment]
Sadly, such race condition looks tricky to reproduce, I didn't see the failure on s390x Debian 3.x, I just close the issue. See you the next time the issue pops up :-)
