### ISSUE TITLE
datetime error message is different between _pydatetime.py and _datetimemodule.c

### ISSUE THREAD

**Issue by mattip** [python/cpython#109798]
# Bug report

### Bug description:

```python
import _datetime, _pydatetime
_datetime.date(1, 1, 50)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: day is out of range for month```

_pydatetime.date(1, 1, 50)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/_pydatetime.py", line 960, in __new__
    year, month, day = _check_date_fields(year, month, day)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pydatetime.py", line 535, in _check_date_fields
    raise ValueError('day must be in 1..%d' % dim, day)
ValueError: ('day must be in 1..31', 50)

```

The error message differs between the two implementations of datetime. This came up when testing PyPy, which uses the pure-python datetime implementation. xref https://github.com/conda-forge/rtoml-feedstock/pull/1#issuecomment-1732509648

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-127345

**Comment by donBarbos** [comment]
So, you suggest to leave the option as in the `_datetime` implementation?

I can send a PR

**Comment by donBarbos** [comment]
Ok, I will leave error message as in the c implementation

Firstly, it is better to output a string (not tuple), and in the python implementation, the second value in tuple is redundant.
Secondly, it seems to me that it is the main implementation.

**Comment by donBarbos** [comment]
I also add more inconsistency in the error messages that I found in the code

### 1. Errors about date and time have inconsistent messages, for example problem with `year` field may raise next errors:
```python
ValueError: ('year must be in 1..9999', {year})
ValueError: Year is out of range: {year}
ValueError: year {year} is out of range
ValueError: Year {year} is out of range
```
We need to make same message template for the fields `year`, `month`, `day`, `hour`, `minute`, `second`, `microsecond` and `fold`.
### 2. Method `date.fromisocalendar` may raise next errors depends on implementation:
```python
ValueError: Invalid weekday: {day} (range is [1, 7])
ValueError: Invalid day: {day} (range is [1, 7])
```
### 3. Error with offset argument in timezone may raise next errors:
```python
ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24), not datetime.timedelta(days=21).  # with dot
ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24), not datetime.timedelta(days=21)   # without dot
ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).
ValueError: {name}()={offset}, must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24)
```

**Comment by StanFromIreland** [comment]
PR was merged, issue is complete :-)

It seems there was no plan to back port which is for the best for backwards compatibility.

**Comment by mattip** [comment]
Thanks!
