### ISSUE TITLE
test_asyncio.test_subprocess: test_stdin_broken_pipe() failed on GHA Windows x64 CI

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109709]
```
test_stdin_broken_pipe (test.test_asyncio.test_subprocess.SubprocessProactorTests.test_stdin_broken_pipe) ... FAIL

FAIL: test_stdin_broken_pipe (test.test_asyncio.test_subprocess.SubprocessProactorTests.test_stdin_broken_pipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_asyncio\test_subprocess.py", line 298, in test_stdin_broken_pipe
    self.assertRaises((BrokenPipeError, ConnectionResetError),
AssertionError: (<class 'BrokenPipeError'>, <class 'ConnectionResetError'>) not raised by run_until_complete
```

build: https://github.com/python/cpython/actions/runs/6268408487/job/17024556425?pr=109701

cc @sorcio

### Linked PRs
* gh-109710
* gh-109731
* gh-109735

**Comment by vstinner** [comment]
I already saw this bug in the past:

* 2017: issue GH-74567
* 2018: issue GH-77712
* 2019: issue GH-81336

**Comment by vstinner** [comment]
The issue can be reproduced on FreeBSD with:

```
vstinner@freebsd$ ./python -m test test_asyncio.test_subprocess -m test_stdin_broken_pipe -v -j25 --forever
(...)
0:00:07 load avg: 7.48 [ 20/1] test_asyncio.test_subprocess failed (1 failure)
test_stdin_broken_pipe (test.test_asyncio.test_subprocess.SubprocessFastWatcherTests.test_stdin_broken_pipe) ... ok
test_stdin_broken_pipe (test.test_asyncio.test_subprocess.SubprocessPidfdWatcherTests.test_stdin_broken_pipe) ... skipped 'operating system does not support pidfds'
test_stdin_broken_pipe (test.test_asyncio.test_subprocess.SubprocessSafeWatcherTests.test_stdin_broken_pipe) ... ok
test_stdin_broken_pipe (test.test_asyncio.test_subprocess.SubprocessThreadedWatcherTests.test_stdin_broken_pipe) ... FAIL

======================================================================
FAIL: test_stdin_broken_pipe (test.test_asyncio.test_subprocess.SubprocessThreadedWatcherTests.test_stdin_broken_pipe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/home/vstinner/python/main/Lib/test/test_asyncio/test_subprocess.py", line 298, in test_stdin_broken_pipe
    self.assertRaises((BrokenPipeError, ConnectionResetError),
AssertionError: (<class 'BrokenPipeError'>, <class 'ConnectionResetError'>) not raised by run_until_complete

----------------------------------------------------------------------
Ran 4 tests in 2.170s

FAILED (failures=1, skipped=1)
/usr/home/vstinner/python/main/Lib/asyncio/base_subprocess.py:125: ResourceWarning: unclosed transport <_UnixSubprocessTransport pid=2131 running stdin=<_UnixWritePipeTransport closed fd=7 closed>>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
test test_asyncio.test_subprocess failed
```
