### ISSUE TITLE
test_ftplib: test_storlines() fails randomly

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109845]
s390x RHEL7 Refleaks 3.x:

```
0:00:19 load avg: 3.25 [ 17/463/1] test_ftplib failed (1 failure)
beginning 6 repetitions
123456
..test test_ftplib failed -- Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-rhel-z.refleak/build/Lib/test/test_ftplib.py", line 634, in test_storlines
    self.check_data(self.server.handler_instance.last_received_data, RETR_DATA)
  File "/home/dje/cpython-buildarea/3.x.edelsohn-rhel-z.refleak/build/Lib/test/test_ftplib.py", line 505, in check_data
    self.assertEqual(len(received), len(expected))
AssertionError: 12019 != 12018
```

build: https://buildbot.python.org/all/#/builders/129/builds/890

I can reproduce the failure locally on Linux with command:

```
vstinner@mona$ ./python -m test test_ftplib -m test_storlines -u all -j10 --forever -R 3:3 
(...)
0:00:10 load avg: 24.24 [ 11/1] test_ftplib failed (1 failure)
beginning 6 repetitions
123456
..test test_ftplib failed -- Traceback (most recent call last):
  File "/home/vstinner/python/main/Lib/test/test_ftplib.py", line 634, in test_storlines
    self.check_data(self.server.handler_instance.last_received_data, RETR_DATA)
  File "/home/vstinner/python/main/Lib/test/test_ftplib.py", line 505, in check_data
    self.assertEqual(len(received), len(expected))
AssertionError: 12019 != 12018
```

### Linked PRs
* gh-109912
* gh-109919
* gh-109920

**Comment by vstinner** [comment]
I looked at the issue but I didn't see anything obvious 🤷🏻‍♂️ Also, I got scared when I saw that the server IS implemented with asyncore, the zombie module 😱

**Comment by serhiy-storchaka** [comment]
Other unstable tests are test_storbinary and test_encoding_param.

I changed also test_retrbinary, test_retrbinary_rest and test_transfer which potentially can fail for same reason, although I cannot reproduce this.

**Comment by vstinner** [comment]
Thanks for the fix @serhiy-storchaka.
