### ISSUE TITLE
test_asyncio.test_waitfor: test_wait_for_timeout_less_then_0_or_0_coroutine_do_not_started() failed on GHA Windows x64

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109878]
GHA Windows x64:

```
FAIL: test_wait_for_timeout_less_then_0_or_0_coroutine_do_not_started (test.test_asyncio.test_waitfor.AsyncioWaitForTest.test_wait_for_timeout_less_then_0_or_0_coroutine_do_not_started)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\unittest\async_case.py", line 90, in _callTestMethod
    if self._callMaybeAsync(method) is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\cpython\cpython\Lib\unittest\async_case.py", line 112, in _callMaybeAsync
    return self._asyncioRunner.run(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\cpython\cpython\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\cpython\cpython\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\a\cpython\cpython\Lib\test\test_asyncio\test_waitfor.py", line 92, in test_wait_for_timeout_less_then_0_or_0_coroutine_do_not_started
    self.assertLess(t1 - t0, 0.1)
AssertionError: 0.1879999999998745 not less than 0.1
```

build: https://github.com/python/cpython/actions/runs/6306288599/job/17121189775?pr=109871

**Comment by vstinner** [comment]
See also issue gh-110088.

**Comment by vstinner** [comment]
Fixed by PR gh-110092.
