### ISSUE TITLE
test_asyncio.test_windows_events: test_wait_for_handle() failed on GHA Windows x86

### ISSUE THREAD

**Issue by vstinner** [python/cpython#110088]
The test must not measure the performance of the CI.

GHA Windows x86:

```
FAIL: test_wait_for_handle (test.test_asyncio.test_windows_events.ProactorTests.test_wait_for_handle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_asyncio\test_windows_events.py", line 188, in test_wait_for_handle
    self.assertTrue(0 <= elapsed < 0.3, elapsed)
AssertionError: False is not true : 0.3129999999998745
```

build: https://github.com/python/cpython/actions/runs/6348560548/job/17245417314?pr=110080

### Linked PRs
* gh-110092
* gh-110098
* gh-110099
* gh-110157
* gh-110158
* gh-110159

**Comment by vstinner** [comment]
On GHA Windows x64, on another PR: https://github.com/python/cpython/actions/runs/6348572958/job/17246410556?pr=110078

```

FAIL: test_wait_for_handle (test.test_asyncio.test_windows_events.ProactorTests.test_wait_for_handle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_asyncio\test_windows_events.py", line 175, in test_wait_for_handle
    self.assertTrue(0.45 <= elapsed <= 0.9, elapsed)
AssertionError: False is not true : 0.9380000000001019
```

**Comment by vstinner** [comment]
See also issue gh-109878.

**Comment by zooba** [comment]
> The test must not measure the performance of the CI.

This belongs in a Zen of Testing 😄
