### ISSUE TITLE
test_multiprocessing_main_handling failed on GHA Windows x64: temp_cwd() fails with PermissionError

### ISSUE THREAD

**Issue by vstinner** [python/cpython#110154]
I suspect that sometimes, multiprocessing created a process which didn't complete and so the Python test worker process cannot remove its temporary directory, since it's still used by at least one process.

GHA Windows x64:

```
0:04:16 load avg: 14.19 [106/467/1] test_multiprocessing_main_handling worker non-zero exit code (Exit code 1) -- running (1): test_importlib (45.6 sec)
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 480, in temp_dir
    yield path
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 533, in temp_cwd
    yield cwd_dir
  File "D:\a\cpython\cpython\Lib\test\libregrtest\worker.py", line 112, in main
    worker_process(worker_json)
  File "D:\a\cpython\cpython\Lib\test\libregrtest\worker.py", line 98, in worker_process
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\support\__init__.py", line 208, in _force_run
    return func(*args)
           ^^^^^^^^^^^
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\a\\cpython\\cpython\\build\\test_python_5088�'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\cpython\cpython\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "D:\a\cpython\cpython\Lib\test\libregrtest\worker.py", line 116, in <module>
    main()
  File "D:\a\cpython\cpython\Lib\test\libregrtest\worker.py", line 111, in main
    with os_helper.temp_cwd(work_dir, quiet=True):
  File "D:\a\cpython\cpython\Lib\contextlib.py", line 159, in __exit__
    self.gen.throw(value)
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 531, in temp_cwd
    with temp_dir(path=name, quiet=quiet) as temp_path:
  File "D:\a\cpython\cpython\Lib\contextlib.py", line 159, in __exit__
    self.gen.throw(value)
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 485, in temp_dir
    rmtree(path)
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 442, in rmtree
    _rmtree(path)
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 386, in _rmtree
    _waitfor(lambda p: _force_run(p, os.rmdir, p), path)
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 330, in _waitfor
    func(pathname)
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 386, in <lambda>
    _waitfor(lambda p: _force_run(p, os.rmdir, p), path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\cpython\cpython\Lib\test\support\__init__.py", line 219, in _force_run
    return func(*args)
           ^^^^^^^^^^^
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\a\\cpython\\cpython\\build\\test_python_5088�'
```

build: https://github.com/python/cpython/actions/runs/6364342183/job/17280567266?pr=110148

**Comment by vstinner** [comment]
Variant:

```
ERROR: test_basic_script_no_suffix (test.test_multiprocessing_main_handling.SpawnCmdLineTest.test_basic_script_no_suffix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\support\__init__.py", line 208, in _force_run
    return func(*args)
           ^^^^^^^^^^^
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\test_python_1aqu5p_i\\tmpf3rgohl9\\script'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_multiprocessing_main_handling.py", line 176, in test_basic_script_no_suffix
    with os_helper.temp_dir() as script_dir:
  File "D:\a\cpython\cpython\Lib\contextlib.py", line 148, in __exit__
    next(self.gen)
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 485, in temp_dir
    rmtree(path)
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 442, in rmtree
    _rmtree(path)
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 385, in _rmtree
    _waitfor(_rmtree_inner, path, waitall=True)
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 330, in _waitfor
    func(pathname)
  File "D:\a\cpython\cpython\Lib\test\support\os_helper.py", line 384, in _rmtree_inner
    _force_run(fullname, os.unlink, fullname)
  File "D:\a\cpython\cpython\Lib\test\support\__init__.py", line 219, in _force_run
    return func(*args)
           ^^^^^^^^^^^
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\test_python_1aqu5p_i\\tmpf3rgohl9\\script'
```

**Comment by vstinner** [comment]
I didn't see this failure recently, I close the issue.
