### ISSUE TITLE
SSLContext.do_handshake() does not raise SSLError when connection is reject by server

### ISSUE THREAD

**Issue by ulyssesric** [python/cpython#110197]
# Bug report

### Summary

1. Connecting to a TLS server that requires client certificate.
2. `SSLContext` does not set client cert via `load_cert_chain(cert, key)`.
3. Connection will be terminated by server side, but `do_handshake()` does not raise `SSLError`.

### Python version

macOS HomeBrew (X86-64) release, `3.11.5 (main, Aug 24 2023, 15:18:16) [Clang 14.0.3 (clang-1403.0.22.14.1)]`

### Description

Server side: 

`openssl s_server -port 12345 -CAfile ca.crt -cert server.crt -key server.key -Verify 1`

Client side:

```python
import ssl
import socket

context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
context.verify_mode = ssl.CERT_REQUIRED
context.check_hostname = False
# context.load_cert_chain(certfile='client.crt', keyfile='client.key')
context.load_verify_locations(cafile='ca.crt')

client = socket.create_connection(('127.0.0.1', 12345))
ssock = context.wrap_socket(client, server_hostname='example.com', do_handshake_on_connect=False)
ssock.do_handshake()

ssock.sendall(b'Hello, world\n')
while 1:
    data = ssock.recv(1024)
    if not data:
        ssock.close()
        exit()
    do_something(data)
```

With line 7 commented, server side will reject connection immediately, but client side will raise exception only during `ssock.recv()` call:

```
Traceback (most recent call last):
  File "client.py", line 16, in <module>
    data = ssock.recv(1024)
    ^^^^^^^^^^^^^^^^^^
  File "***/python3.11/ssl.py", line 1263, in recv
    return self.read(buflen)
    ^^^^^^^^^^^^^^^^^
  File "***/python3.11/ssl.py", line 1136, in read
    return self._sslobj.read(len)
    ^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SSL: TLSV13_ALERT_CERTIFICATE_REQUIRED] tlsv13 alert certificate required (_ssl.c:2576)
```

Further notes:

1. This issue might be related to TLSv1.3; creating `SSLContext` instance via `ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)` and `do_handshake()` will raise exception.
2. Try to run the same code with macOS Ventura 13.6 built-in Python 3 and `do_handshake()` will raise exception. Version info: `3.9.6 (default, Aug 11 2023, 19:44:50) [Clang 15.0.0 (clang-1500.0.40.1)]`

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by sergei-maertens** [comment]
I spent half the day today trying to debug this behaviour because it seemed unintuitive to me.

Python 3.11, on Arch Linux.

OpenSSL s_client exits immediately with missing/bad client certificate, as expected
