### ISSUE TITLE
test_subprocess: test_pipesize_default() failed on s390x Fedora Clang 3.x buildbot

### ISSUE THREAD

**Issue by vstinner** [python/cpython#110184]
s390x Fedora Clang 3.x buildbot:

```
FAIL: test_pipesize_default (test.test_subprocess.ProcessTestCase.test_pipesize_default)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-fedora-z.clang/build/Lib/test/test_subprocess.py", line 763, in test_pipesize_default
    self.assertEqual(
AssertionError: 65536 != 8192
```

build: https://buildbot.python.org/all/#/builders/3/builds/4728

### Linked PRs
* gh-110465
* gh-110471
* gh-110472

**Comment by vstinner** [comment]
New fail on s390x Fedora Refleaks 3.x: https://buildbot.python.org/all/#/builders/433/builds/902

**Comment by vstinner** [comment]
Oh. It seems like the test failed again when PR gh-110441 got merged: https://buildbot.python.org/all/#/builders/531/builds/4639 It's surprising since the test passed before.

```
0:03:25 load avg: 2.45 Re-running 1 failed tests in verbose mode in subprocesses
0:03:25 load avg: 2.45 Run 1 test in parallel using 1 worker process (timeout: 20 min, worker timeout: 25 min)
0:03:25 load avg: 2.45 [1/1/1] test_subprocess failed (2 errors, 2 failures)
Re-running test_subprocess in verbose mode (matching: test_pipesizes, test_pipesize_default)
test_pipesize_default (test.test_subprocess.ProcessTestCase.test_pipesize_default) ... FAIL
test_pipesizes (test.test_subprocess.ProcessTestCase.test_pipesizes) ... ERROR
test_pipesize_default (test.test_subprocess.ProcessTestCaseNoPoll.test_pipesize_default) ... FAIL
test_pipesizes (test.test_subprocess.ProcessTestCaseNoPoll.test_pipesizes) ... ERROR

======================================================================
ERROR: test_pipesizes (test.test_subprocess.ProcessTestCase.test_pipesizes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-fedora-z.clang-installed/build/target/lib/python3.13/test/test_subprocess.py", line 727, in test_pipesizes
    p = subprocess.Popen(
        ^^^^^^^^^^^^^^^^^
  File "/home/dje/cpython-buildarea/3.x.edelsohn-fedora-z.clang-installed/build/target/lib/python3.13/subprocess.py", line 992, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dje/cpython-buildarea/3.x.edelsohn-fedora-z.clang-installed/build/target/lib/python3.13/subprocess.py", line 1731, in _get_handles
    fcntl.fcntl(errwrite, fcntl.F_SETPIPE_SZ, self.pipesize)
PermissionError: [Errno 1] Operation not permitted

======================================================================
ERROR: test_pipesizes (test.test_subprocess.ProcessTestCaseNoPoll.test_pipesizes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-fedora-z.clang-installed/build/target/lib/python3.13/test/test_subprocess.py", line 727, in test_pipesizes
    p = subprocess.Popen(
        ^^^^^^^^^^^^^^^^^
  File "/home/dje/cpython-buildarea/3.x.edelsohn-fedora-z.clang-installed/build/target/lib/python3.13/subprocess.py", line 992, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dje/cpython-buildarea/3.x.edelsohn-fedora-z.clang-installed/build/target/lib/python3.13/subprocess.py", line 1731, in _get_handles
    fcntl.fcntl(errwrite, fcntl.F_SETPIPE_SZ, self.pipesize)
PermissionError: [Errno 1] Operation not permitted

======================================================================
FAIL: test_pipesize_default (test.test_subprocess.ProcessTestCase.test_pipesize_default)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-fedora-z.clang-installed/build/target/lib/python3.13/test/test_subprocess.py", line 769, in test_pipesize_default
    self.assertEqual(
AssertionError: 65536 != 8192

======================================================================
FAIL: test_pipesize_default (test.test_subprocess.ProcessTestCaseNoPoll.test_pipesize_default)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-fedora-z.clang-installed/build/target/lib/python3.13/test/test_subprocess.py", line 769, in test_pipesize_default
    self.assertEqual(
AssertionError: 65536 != 8192

----------------------------------------------------------------------
Ran 4 tests in 0.013s

FAILED (failures=2, errors=2)
test test_subprocess failed
1 test failed again:
    test_subprocess

== Tests result: FAILURE then FAILURE ==
```

**Comment by vstinner** [comment]
```
  File "/home/dje/cpython-buildarea/3.x.edelsohn-fedora-z.clang-installed/build/target/lib/python3.13/subprocess.py", line 1731, in _get_handles
    fcntl.fcntl(errwrite, fcntl.F_SETPIPE_SZ, self.pipesize)
PermissionError: [Errno 1] Operation not permitted
```

The manual page says: https://man7.org/linux/man-pages/man2/fcntl.2.html

> An unprivileged process can adjust the
> pipe capacity to any value **between the system page size**
> **and the limit defined in /proc/sys/fs/pipe-max-size** (see
> [proc(5)](https://man7.org/linux/man-pages/man5/proc.5.html)).

and:

> Attempts by an unprivileged process to set the pipe
> capacity **above the limit in /proc/sys/fs/pipe-max-size**
> yield the error **EPERM**

**Comment by vstinner** [comment]
I didn't see the failure failure recently on s390x Fedora Clang 3.x, so I close the issue.
