### ISSUE TITLE
test_msvcrt: test_getwche() failed with timeout (10 min) on GHA Windows x64

### ISSUE THREAD

**Issue by vstinner** [python/cpython#110147]
GHA Windows x64:

```
0:16:19 load avg: 5.19 [377/467/1] test_msvcrt process crashed (Exit code 1) -- running (1): test_winconsoleio (10 min)
Timeout (0:10:00)!
Thread 0x000001d4 (most recent call first):
  File "D:\a\cpython\cpython\Lib\test\test_msvcrt.py", line 91 in test_getwche
  (...)

== Tests result: FAILURE ==
```

build: https://github.com/python/cpython/actions/runs/6363931614/job/17279864816?pr=110146

### Linked PRs
* gh-110268

**Comment by vstinner** [comment]
cc @aisk @terryjreedy @zooba

**Comment by vstinner** [comment]
Another failure, on GHA Windows x86:

```
FAIL: test_kbhit (test.test_msvcrt.TestConsoleIO.test_kbhit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_msvcrt.py", line 67, in test_kbhit
    self.assertEqual(msvcrt.kbhit(), 0)
AssertionError: 1 != 0
```

build: https://github.com/python/cpython/actions/runs/6365753186/job/17283009093?pr=109907

**Comment by aisk** [comment]
Changed the three tests which depends on `_write_input` to be run in a separate process: #110268 , maybe this can totally resolve the stability issue.
