### ISSUE TITLE
test_socket: NetworkConnectionAttributesTest.clientTearDown() raised AttributeError on AMD64 RHEL7 Refleaks 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#110391]
`NetworkConnectionAttributesTest.clientTearDown()` raised `AttributeError: 'NetworkConnectionAttributesTest' object has no attribute 'cli'`.

AMD64 RHEL7 Refleaks 3.x:

```
(...)
3:19:42 load avg: 0.00 running (1): test_socket (3 hour 17 min)
3:20:12 load avg: 0.00 running (1): test_socket (3 hour 18 min)
3:20:42 load avg: 0.00 running (1): test_socket (3 hour 18 min)
3:21:12 load avg: 0.00 running (1): test_socket (3 hour 19 min)
3:21:42 load avg: 0.00 running (1): test_socket (3 hour 19 min)
3:22:12 load avg: 0.00 [467/467/2] test_socket worker non-zero exit code (Exit code 1)
beginning 6 repetitions
123456
..Warning -- Unraisable exception
Exception ignored in thread started by: <bound method ThreadableTest.clientRun of <test.test_socket.NetworkConnectionAttributesTest testMethod=testSourceAddress>>
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/test/test_socket.py", line 406, in clientRun
    self.clientTearDown()
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/test/test_socket.py", line 5368, in clientTearDown
    self.cli.close()
    ^^^^^^^^
AttributeError: 'NetworkConnectionAttributesTest' object has no attribute 'cli'
Timeout (3:20:00)!
Thread 0x00007f268deaf740 (most recent call first):
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/socket.py", line 295 in accept
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/test/test_socket.py", line 5373 in _justAccept
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/unittest/case.py", line 589 in _callTestMethod
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/unittest/case.py", line 636 in run
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/unittest/case.py", line 692 in __call__
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/unittest/suite.py", line 122 in run
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/unittest/suite.py", line 84 in __call__
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/unittest/suite.py", line 122 in run
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/unittest/suite.py", line 84 in __call__
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/unittest/suite.py", line 122 in run
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/unittest/suite.py", line 84 in __call__
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/test/support/testresult.py", line 146 in run
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/test/support/__init__.py", line 1155 in _run_suite
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-x86_64.refleak/build/Lib/test/support/__init__.py", line 1282 in run_unittest
```

build: https://buildbot.python.org/all/#/builders/562/builds/902

### Linked PRs
* gh-110401
* gh-110405
* gh-110406

**Comment by vstinner** [comment]
I don't know the root cause of this issue, but the merged change https://github.com/python/cpython/commit/e37d4557c3de0476e76ca4b8a1cc8d2566b86c79 should unblock test_socket which may provide more information if the test fails again.
