### ISSUE TITLE
SharedMemoryManager not persisting SharedMemory references created in sub-processes

### ISSUE THREAD

**Issue by drbsg** [python/cpython#110468]
# Bug report

### Bug description:

I have the following setup:
* a main process which starts a `SharedMemoryManager` which persists for the lifetime of the program;
* a producer subprocess which connects to the `SharedMemoryManager` server started above, uses it to allocate some `SharedMemory` and puts it in a `Queue`;
* a consumer subprocess which reads from the `Queue` and displays the result.

My expectation is that the allocated shared memory should be valid for the lifetime of the main process, so it should be safe to pass through a queue to the consumer process. But instead, I get a `FileNotFoundError` instead:

```shell
Process Process-3:
Traceback (most recent call last):
  File "C:\Users\brett.gibson\Miniconda3\envs\experiments-multiprocessing-py312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\brett.gibson\Miniconda3\envs\experiments-multiprocessing-py312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\brett.gibson\Code\experiments\multiprocessing\bug.py", line 18, in consumer
    shared_memory = in_q.get()
                    ^^^^^^^^^^
  File "C:\Users\brett.gibson\Miniconda3\envs\experiments-multiprocessing-py312\Lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brett.gibson\Miniconda3\envs\experiments-multiprocessing-py312\Lib\multiprocessing\shared_memory.py", line 161, in __init__
    h_map = _winapi.OpenFileMapping(
            ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'wnsm_d6fa4935'
```

I am using the code below to reproduce this:

```python
import multiprocessing as mp
from multiprocessing.managers import SharedMemoryManager
from time import sleep

def producer(out_q, addr):
    smm = SharedMemoryManager(address=addr)
    smm.connect()
    shared_memory = smm.SharedMemory(size=1)
    out_q.put(shared_memory)
    # With the following sleep, shared_memory lives long enough for the
    # consumer to use it. Without, smm goes out of scope and the reference
    # in out_q now points to a missing file. Presumably it has been unlinked.
    # sleep(1)

def consumer(in_q):
    shared_memory = in_q.get()
    print(shared_memory)

def main():
    with SharedMemoryManager() as smm:
        work_q = mp.Queue()
        p1 = mp.Process(target=producer, args=(work_q, smm.address))
        p2 = mp.Process(target=consumer, args=(work_q,))
        p1.start()
        p2.start()
        p1.join()
        p2.join()

if __name__ == "__main__":
    main()
```

### CPython versions tested on:

3.8, 3.10, 3.12

### Operating systems tested on:

Windows

**Comment by drbsg** [comment]
Enabling debug level logging with `multiprocessing.log_to_stderr(level=logging.DEBUG)` shows that the top-level `SharedMemoryManager` is behaving as expected. It is also results in about 50% of runs failing, and 50% being successful.

Successful:
```shell
[DEBUG/MainProcess] SharedMemoryManager created by pid 38160
[INFO/SharedMemoryManager-1] child process calling self.run()
[DEBUG/SharedMemoryManager-1] SharedMemoryServer started by pid 37456
[INFO/SharedMemoryManager-1] manager serving at '\\\\.\\pipe\\pyc-37456-0-zptesb_d'
[DEBUG/MainProcess] created semlock with handle 508
[DEBUG/MainProcess] created semlock with handle 512
[DEBUG/Process-2] recreated blocker with handle 20
[DEBUG/Process-2] recreated blocker with handle 24
[INFO/Process-2] child process calling self.run()
[DEBUG/Process-3] recreated blocker with handle 20
[DEBUG/Process-2] SharedMemoryManager created by pid 40656
[DEBUG/Process-3] recreated blocker with handle 24
[INFO/Process-3] child process calling self.run()
[DEBUG/SharedMemoryManager-1] Register segment 'wnsm_2f2fe859' in pid 37456
[DEBUG/Process-2] Queue._start_thread()
[DEBUG/Process-2] doing self._thread.start()
[DEBUG/Process-2] starting thread to feed data to pipe
[DEBUG/Process-2] ... done self._thread.start()
[DEBUG/Process-2] SharedMemoryManager.__del__ by pid 40656
SharedMemory('wnsm_2f2fe859', size=4096)
[INFO/Process-2] process shutting down
[INFO/Process-3] process shutting down
[DEBUG/Process-2] running all "atexit" finalizers with priority >= 0
[DEBUG/Process-3] running all "atexit" finalizers with priority >= 0
[DEBUG/Process-2] telling queue thread to quit
[DEBUG/Process-3] running the remaining "atexit" finalizers
[DEBUG/Process-2] running the remaining "atexit" finalizers
[INFO/Process-3] process exiting with exitcode 0
[DEBUG/Process-2] joining queue thread
[DEBUG/Process-2] feeder thread got sentinel -- exiting
[DEBUG/Process-2] ... queue thread joined
[INFO/Process-2] process exiting with exitcode 0
[INFO/MainProcess] sending shutdown message to manager
[DEBUG/SharedMemoryManager-1] Destroy segment 'wnsm_2f2fe859' in pid 37456
[INFO/MainProcess] manager still alive
[INFO/MainProcess] trying to `terminate()` manager process
[DEBUG/MainProcess] SharedMemoryManager.__del__ by pid 38160
[INFO/MainProcess] process shutting down
[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
[DEBUG/MainProcess] running the remaining "atexit" finalizers
```

Failure:
```shell
[DEBUG/MainProcess] SharedMemoryManager created by pid 35112
[INFO/SharedMemoryManager-1] child process calling self.run()
[DEBUG/SharedMemoryManager-1] SharedMemoryServer started by pid 38468
[INFO/SharedMemoryManager-1] manager serving at '\\\\.\\pipe\\pyc-38468-0-mgs9ys_4'
[DEBUG/MainProcess] created semlock with handle 528
[DEBUG/MainProcess] created semlock with handle 384
[DEBUG/Process-2] recreated blocker with handle 20
[DEBUG/Process-2] recreated blocker with handle 24
[INFO/Process-2] child process calling self.run()
[DEBUG/Process-2] SharedMemoryManager created by pid 31148
[DEBUG/Process-3] recreated blocker with handle 20
[DEBUG/Process-3] recreated blocker with handle 24
[INFO/Process-3] child process calling self.run()
[DEBUG/SharedMemoryManager-1] Register segment 'wnsm_ac181760' in pid 38468
[DEBUG/Process-2] Queue._start_thread()
[DEBUG/Process-2] doing self._thread.start()
[DEBUG/Process-2] starting thread to feed data to pipe
[DEBUG/Process-2] ... done self._thread.start()
[DEBUG/Process-2] SharedMemoryManager.__del__ by pid 31148
[INFO/Process-2] process shutting down
[INFO/Process-3] process shutting down
[DEBUG/Process-2] running all "atexit" finalizers with priority >= 0
[DEBUG/Process-3] running all "atexit" finalizers with priority >= 0
[DEBUG/Process-2] telling queue thread to quit
[DEBUG/Process-3] running the remaining "atexit" finalizers
[DEBUG/Process-2] running the remaining "atexit" finalizers
Process Process-3:
[DEBUG/Process-2] feeder thread got sentinel -- exiting
[DEBUG/Process-2] joining queue thread
[DEBUG/Process-2] ... queue thread joined
[INFO/Process-2] process exiting with exitcode 0
Traceback (most recent call last):
  File "C:\Users\brett.gibson\Miniconda3\envs\experiments-multiprocessing-py312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\brett.gibson\Miniconda3\envs\experiments-multiprocessing-py312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\brett.gibson\Code\experiments\multiprocessing\bug.py", line 20, in consumer
    shared_memory = in_q.get()
                    ^^^^^^^^^^
  File "C:\Users\brett.gibson\Miniconda3\envs\experiments-multiprocessing-py312\Lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brett.gibson\Miniconda3\envs\experiments-multiprocessing-py312\Lib\multiprocessing\shared_memory.py", line 161, in __init__
    h_map = _winapi.OpenFileMapping(
            ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'wnsm_ac181760'
[INFO/Process-3] process exiting with exitcode 1
[INFO/MainProcess] sending shutdown message to manager
[DEBUG/SharedMemoryManager-1] Destroy segment 'wnsm_ac181760' in pid 38468
[INFO/MainProcess] manager still alive
[INFO/MainProcess] trying to `terminate()` manager process
[DEBUG/MainProcess] SharedMemoryManager.__del__ by pid 35112
[INFO/MainProcess] process shutting down
[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
[DEBUG/MainProcess] running the remaining "atexit" finalizers
```

**Comment by drbsg** [comment]
Closed thinking I had found a race condition. But on further investigation I believe there is still an issue to address here.

**Comment by drbsg** [comment]
There is a race condition as `shared_memory` goes through the queue. When `consumer` exits, it releases its shared memory references. If that completes before `producer` unpickles the reference to `shared_memory` from the queue, then the reference count held by the manager goes to zero and `shared_memory` is unlinked.

If my understanding here is correct, then adding some synchronization between the processes can fix the immediate problem. But I think a more elegant approach would be for `Queue` to be aware of `SharedMemory` and bump the reference count. This would make it safer to use queues to pass shared memory references around.

**Comment by zpz** [comment]
`multiprocessing.managers` has a bug around pickling; please see my blog post here https://zpz.github.io/blog/python-mp-manager-2/#bug-in-pickling . I'm about to create an issue about this.

However, my reading of the shared-memory code in `multiprocessing.managers` suggests that the memory release never happens until the manager/server exits. In other words, it does not happen when any particular piece of shared-memory has reached zero ref count. My other blog https://zpz.github.io/blog/python-mp-manager-3/ claims this problem but I could be wrong. My reading of this shared-memory part is not that careful.

The package [mpservice.multiprocessing.server_process](https://github.com/zpz/mpservice/blob/main/src/mpservice/multiprocessing/server_process.py) most likely has solved your issues. If you need a solution now, you can give it a try.
