### ISSUE TITLE
test_threading: `test_3_join_in_forked_from_thread` failed on Ubuntu

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#110592]
# Bug report

Link: https://github.com/python/cpython/actions/runs/6462365372/job/17543839277?pr=110573

Output:

```
======================================================================
FAIL: test_3_join_in_forked_from_thread (test.test_threading.ThreadJoinOnShutdown.test_3_join_in_forked_from_thread)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/test/test_threading.py", line 1152, in test_3_join_in_forked_from_thread
    self._run_and_join(script)
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/test/test_threading.py", line 1092, in _run_and_join
    self.assertEqual(data, "end of main\nend of thread\n")
AssertionError: '' != 'end of main\nend of thread\n'
+ end of main
+ end of thread
```

Refs https://github.com/python/cpython/issues/56079
CC @vstinner

**Comment by vstinner** [comment]
@sobolevn: Can you reproduce the issue?

I ran `/python -m test test_threading -m test_3_join_in_forked_from_thread -j60 -FW` for a minute, but I cannot reproduce just with that. I ran `./python -m test -j20 -r` in a separated terminal, I still couldn't reproduce the issue.
