### ISSUE TITLE
test_multiprocessing_spawn.test_misc: test_resource_tracker_sigkill() failed on PPC64LE RHEL7 LTO + PGO 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#110698]
I suspect that `time.sleep(1.0)  # give it time to die` is a bad synchronization primitive to wait until the process dies and restarts. `PPC64LE RHEL7` is a slow buildbot.

Test:

```
    def check_resource_tracker_death(self, signum, should_die):
        # bpo-31310: if the semaphore tracker process has died, it should
        # be restarted implicitly.
        from multiprocessing.resource_tracker import _resource_tracker
        pid = _resource_tracker._pid
        if pid is not None:
            os.kill(pid, signal.SIGKILL)
            support.wait_process(pid, exitcode=-signal.SIGKILL)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            _resource_tracker.ensure_running()
        pid = _resource_tracker._pid

        os.kill(pid, signum)
        time.sleep(1.0)  # give it time to die

        ctx = multiprocessing.get_context("spawn")
        with warnings.catch_warnings(record=True) as all_warn:
            warnings.simplefilter("always")
            sem = ctx.Semaphore()
            sem.acquire()
            sem.release()
            wr = weakref.ref(sem)
            # ensure `sem` gets collected, which triggers communication with
            # the semaphore tracker
            del sem
            gc.collect()
            self.assertIsNone(wr())
            if should_die:
                self.assertEqual(len(all_warn), 1) # <=== HERE LINE 5580 ===
                the_warn = all_warn[0]
                self.assertTrue(issubclass(the_warn.category, UserWarning))
                self.assertTrue("resource_tracker: process died"
                                in str(the_warn.message))
            else:
                self.assertEqual(len(all_warn), 0)

    def test_resource_tracker_sigkill(self):
        # Uncatchable signal.
        self.check_resource_tracker_death(signal.SIGKILL, True)
```

PPC64LE RHEL7 LTO + PGO 3.x:

```
FAIL: test_resource_tracker_sigkill (test.test_multiprocessing_spawn.test_misc.TestResourceTracker.test_resource_tracker_sigkill)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-ppc64le.lto-pgo/build/Lib/test/_test_multiprocessing.py", line 5598, in test_resource_tracker_sigkill
    self.check_resource_tracker_death(signal.SIGKILL, True)
  File "/home/buildbot/buildarea/3.x.cstratak-RHEL7-ppc64le.lto-pgo/build/Lib/test/_test_multiprocessing.py", line 5580, in check_resource_tracker_death
    self.assertEqual(len(all_warn), 1)
AssertionError: 0 != 1
```

The test passed when re-run.

build: https://buildbot.python.org/all/#/builders/43/builds/4366

**Comment by Eclips4** [comment]
Victor, `test-with-buildbots` label is intended for attachment only to PR's, so I remove it from this issue :)

**Comment by Eclips4** [comment]
Victor, label `test-with-buildbots-` is intended for attachment only to PR's, so I removing it from this issue :)

**Comment by vstinner** [comment]
I don't why I added test-with-buildbots on this issue, it's a mistake.

**Comment by vstinner** [comment]
I didn't see this failure on PPC64LE RHEL7 LTO + PGO 3.x recently, so I close the issue.
