### ISSUE TITLE
test__xxinterpchannels: _xxinterpchannels.ChannelClosedError is raised

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#110866]
# Bug report

### Bug description:

`./python.exe -m test -R 3:3 test__xxinterpchannels`
<details>
<summary>
Output:
</summary>

```python
Using random seed 1904004318
0:00:00 load avg: 4.72 Run 1 test sequentially
0:00:00 load avg: 4.72 [1/1] test__xxinterpchannels
beginning 6 repetitions
123456
Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 34 is closed
Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 34 is closed
.Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 93 is closed
Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 93 is closed
.Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 152 is closed
Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 152 is closed
.Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 211 is closed
Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 211 is closed
.Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 270 is closed
Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 270 is closed
.Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 329 is closed
Traceback (most recent call last):
  File "<string>", line 2, in <module>
_xxinterpchannels.ChannelClosedError: channel 329 is closed
.

== Tests result: SUCCESS ==

1 test OK.

Total duration: 2.8 sec
Total tests: run=59 skipped=3
Total test files: run=1/1
Result: SUCCESS
```
</details>
### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS, Win 10

**Comment by Eclips4** [comment]
Bisected to ee317f7dddd
cc @ericsnowcurrently

**Comment by Eclips4** [comment]
Probably related:
<details>
<summary> Traceback </summary>

```python
./python.exe -m test -R 3:3 test__xxsubinterpreters
Using random seed 2909661639
0:00:00 load avg: 1.96 Run 1 test sequentially
0:00:00 load avg: 1.96 [1/1] test__xxsubinterpreters
beginning 6 repetitions
123456
Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemExit: 42
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Exception: spam
  File "<string>", line 1
    print("spam"
         ^
SyntaxError: '(' was never closed
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit: 42
.Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemExit: 42
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Exception: spam
  File "<string>", line 1
    print("spam"
         ^
SyntaxError: '(' was never closed
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit: 42
.Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemExit: 42
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Exception: spam
  File "<string>", line 1
    print("spam"
         ^
SyntaxError: '(' was never closed
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit: 42
.Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemExit: 42
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Exception: spam
  File "<string>", line 1
    print("spam"
         ^
SyntaxError: '(' was never closed
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit: 42
.Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemExit: 42
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Exception: spam
  File "<string>", line 1
    print("spam"
         ^
SyntaxError: '(' was never closed
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit: 42
.Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemExit: 42
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Exception: spam
  File "<string>", line 1
    print("spam"
         ^
SyntaxError: '(' was never closed
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit
Traceback (most recent call last):
  File "<string>", line 3, in <module>
SystemExit: 42
.

== Tests result: SUCCESS ==

1 test OK.

Total duration: 5.2 sec
Total tests: run=72 skipped=3
Total test files: run=1/1
Result: SUCCESS
```
</details>

**Comment by Eclips4** [comment]
My super small research:

```python
import _xxsubinterpreters as _interpreters

def with_own_gil(script):
    interpid = _interpreters.create()
    _interpreters.run_string(interpid, script)


try:
    with_own_gil("1 / 0")
except _interpreters.RunFailedError as exc:
    print("gotcha")
 ```
 
 Output:
 ```python
 Traceback (most recent call last):
  File "<string>", line 1, in <module>
ZeroDivisionError: division by zero
gotcha
```

I don't know how true this behaviour is, but I would expect only "gotcha" instead of traceback + "gotcha".

**Comment by Eclips4** [comment]
It's no longer reproducible, probably fixed by https://github.com/python/cpython/commit/86a77f4e1a5ceaff1036b0072521e12752b5df47.
I'm closing it now as "fixed".
