### ISSUE TITLE
Display frame numbers in `pdb` stack trace and allow user to select needed frame by its number

### ISSUE THREAD

**Issue by chgnrdv** [python/cpython#110953]
# Feature or enhancement

### Proposal:

For now, the only way to select a particular frame in `pdb` stack trace is to use `up` and `down` commands, which can be uncomfortable in case of a deep stack and target frame that is near to stack top. I propose to add the new `f(rame)` command to allow user to select any frame in stack by its number, and also change stack trace representation to show numbers beside stack trace entries.
This proposal is inspired by a very similar `gdb` functionality, which I personally find very useful.

**example.py**
```python
def f(x, y):
    z = x / y
    return z


def g(l, n):
    s = 0
    for x in l:
        s += x
    return f(s, n)


def h(l):
    return g(l, len(l))


h([])
```

Currently it looks like this:
```
$ python -m pdb -c c example.py
Traceback (most recent call last):
  File "/home/radislav/projects/cpython/Lib/pdb.py", line 2159, in main
    ...
  File "/home/radislav/example.py", line 3, in f
    z = x / y
        ~~^~~
ZeroDivisionError: division by zero
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/radislav/example.py(3)f()
-> z = x / y
(Pdb) w
  /home/radislav/projects/cpython/Lib/pdb.py(2159)main()
-> pdb._run(target)
  /home/radislav/projects/cpython/Lib/pdb.py(1923)_run()
-> self.run(target.code)
  /home/radislav/projects/cpython/Lib/bdb.py(600)run()
-> exec(cmd, globals, locals)
  <string>(1)<module>()
   /home/radislav/example.py(18)<module>()
-> h([])
   /home/radislav/example.py(15)h()
-> return g(l, len(l))
   /home/radislav/example.py(11)g()
-> return f(s, n)
>  /home/radislav/example.py(3)f()
-> z = x / y
(Pdb) 
```
How it can look with this change:
```
$ python -m pdb -c c example.py
Traceback (most recent call last):
  File "/home/radislav/projects/cpython/Lib/pdb.py", line 2159, in main
    ...
  File "/home/radislav/example.py", line 3, in f
    z = x / y
        ~~^~~
ZeroDivisionError: division by zero
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/radislav/example.py(3)f()
-> z = x / y
(Pdb) w
  0  /home/radislav/projects/cpython/Lib/pdb.py(2159)main()
-> pdb._run(target)
  1  /home/radislav/projects/cpython/Lib/pdb.py(1923)_run()
-> self.run(target.code)
  2  /home/radislav/projects/cpython/Lib/bdb.py(600)run()
-> exec(cmd, globals, locals)
  3  <string>(1)<module>()
  4  /home/radislav/example.py(18)<module>()
-> h([])
  5  /home/radislav/example.py(15)h()
-> return g(l, len(l))
  6  /home/radislav/example.py(11)g()
-> return f(s, n)
> 7  /home/radislav/example.py(3)f()
-> z = x / y
(Pdb) frame 5
> 5  /home/radislav/example.py(15)h()
-> return g(l, len(l))
(Pdb)
```

If this change will be accepted, I can work on implementation.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by gaogaotiantian** [comment]
There is a very real concern for the feature - you'll basically break all tests involving `where`. Not sure if you want to change the stack entry displayed before each command, if you do - then you'll basically break all tests.

I once had a related [proposal](https://discuss.python.org/t/changing-the-stack-format-of-pdb/26619) on dpo, to change the format of stack entry - it raises concern about backward compatibility.

I actually like the idea if it's for a NEW debugger (although strongly -1 for `f(rame)`, `frame` is much better). But there are plenty of tools relying on `pdb` and this could be a breaking change for them, which is something we had to consider, unfortunately.

**Comment by chgnrdv** [comment]
@gaogaotiantian , thanks for your feedback. Yes, looks like backward compatibility of stack entries representation is a big issue here.
I don't want to push this proposal at any cost, but I still see a few ways it can be implemented to be used optionally:
* `where` command can take additional option argument to change view of stack entries it prints.
* some convenience variable can be added to `pdb` that can be set to `True` to enable "enumerated" view. User can set it in `.pdbrc` file to permanently change stack trace representation if they want.
* `pdb` command line option can be added to change stack view for current `pdb` session.

One of problems here is that `frame` command becomes way less useful if "enumerated" stack trace view is not enabled.


> Not sure if you want to change the stack entry displayed before each command, if you do - then you'll basically break all tests.

I think that the view of stack entry displayed before `Pdb` prompt can be left unchanged.

> I once had a related [proposal](https://discuss.python.org/t/changing-the-stack-format-of-pdb/26619) on dpo, to change the format of stack entry - it raises concern about backward compatibility.

Maybe I had to open dpo thread first :smile: 

> although strongly -1 for `f(rame)`, `frame` is much better

Sorry for the confusion. I meant that `frame` command can be used, and it can be shortened to `f`, as with `h(elp)` or `w(here)`.

**Comment by gaogaotiantian** [comment]
> Sorry for the confusion. I meant that `frame` command can be used, and it can be shortened to `f`, as with `h(elp)` or `w(here)`

Yeah I understood, that's what I'm against for. I don't want to introduce more one-letter command unless it is super commonly used. one-letter command has some negative impacts when users try to use raw expression/statement like `f()`, and `f` is a very common name for a temp function. I had enough frustration with `a(rgs)` already.

Make this configurable is probably a good path, and I'm working on a `config` command to do global configuration for `pdb`, which was designed for some other stuff like how many source lines should be displayed by default, but that command should be applicable to this scenario. This is better than using the convenience variable which sounds like a workaround.

**Comment by chgnrdv** [comment]
I got your point about one-letter command. Yes, it's better to leave `frame` as it is, without short version.

I like your idea about `config` command, and the proposal above fits well with it. Now it can look like `where.show_frame_numbers` boolean config key, along with new `frame` command.
