### ISSUE TITLE
ibm_boto3 is throwing error

### ISSUE THREAD

**Issue by theaga-d** [python/cpython#110977]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
> /usr/local/bin/python3.8
Python 3.8.1 (default, Jul 22 2020, 08:02:16)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
>>> import ibm_boto3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/ibm_boto3/__init__.py", line 16, in <module>
    from ibm_boto3.session import Session
  File "/usr/local/lib/python3.8/site-packages/ibm_boto3/session.py", line 27, in <module>
    import ibm_botocore.session
  File "/usr/local/lib/python3.8/site-packages/ibm_botocore/session.py", line 30, in <module>
    import ibm_botocore.credentials
  File "/usr/local/lib/python3.8/site-packages/ibm_botocore/credentials.py", line 34, in <module>
    from ibm_botocore.config import Config
  File "/usr/local/lib/python3.8/site-packages/ibm_botocore/config.py", line 16, in <module>
    from ibm_botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/lib/python3.8/site-packages/ibm_botocore/endpoint.py", line 22, in <module>
    from ibm_botocore.awsrequest import create_request_object
  File "/usr/local/lib/python3.8/site-packages/ibm_botocore/awsrequest.py", line 25, in <module>
    import ibm_botocore.utils
  File "/usr/local/lib/python3.8/site-packages/ibm_botocore/utils.py", line 33, in <module>
    import ibm_botocore.httpsession
  File "/usr/local/lib/python3.8/site-packages/ibm_botocore/httpsession.py", line 8, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_' (/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py)

### CPython versions tested on:

3.8

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
The error message seems to indicate that the stdlib ssl module cannot be imported. The most likely reason for that is that the openssl headers weren't available while building and installing python.

[The devguide](https://devguide.python.org/getting-started/setup-building/#install-dependencies) explains how to install build dependencies for python.

**Comment by sunmy2019** [comment]
Here, `urllib3` requires a `ssl` module.

https://github.com/urllib3/urllib3/blob/312a47b596859fe8ae1cea228e4525f2d0345a75/src/urllib3/util/ssl_.py#L95C13-L95C13

Try directly importing `ssl` from your Python, and you'll see a clearer failure.

Nevertheless, the most likely reason for that is that the OpenSSL headers weren't available while building and installing Python.
