### ISSUE TITLE
unparsing FormattedValue without JoinedStr fails

### ISSUE THREAD

**Issue by 15r10nk** [python/cpython#111257]
# Bug report

### Bug description:

The python documentation for FormattedValue states:

> If the string contains a single formatting field and nothing else the node can be isolated otherwise it appears in [JoinedStr](https://docs.python.org/3.12/library/ast.html#ast.JoinedStr).

Which means that `ast.unparse()` should be able to unparse a `FormattedValue`.
This worked in 3.10 but is broken in 3.11 and 3.12
I bisected this problem down to 3d98ece (@isidentical maybe you want to take a look at it)

```python
from ast import *

tree = Module(
    body=[
        Expr(
            value=FormattedValue(
                value=Name(id="name_1", ctx=Load()),
                conversion=-1,
            )
        )
    ],
    type_ignores=[],
)

code = unparse(tree)

print(code)

assert code.startswith("f'")
```

output (Python 3.12.0):
```python
{name_1}
Traceback (most recent call last):
  File "/home/frank/projects/cpython/../cpython_bugs/formatted_value_only.py", line 19, in <module>
    assert code.startswith("f'")
AssertionError
```

the expected output would be
``` python
f'{name_1}'
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by sobolevn** [comment]
What is interesting is that https://github.com/python/cpython/commit/2c4c26c4ce4bb94200ff3c9b5a0f4c75eed96f31 explicitly add this test:

https://github.com/python/cpython/blob/9bb202a1a90ef0edce20c495c9426d9766df11bb/Lib/test/test_unparse.py#L385-L393

And this AST produces the correct `eval` result, but incorrect `unparse`:

```python
>>> from ast import *
>>> tree = Module(
...     body=[
...         Expr(
...             value=Call(
...                 func=Name(id="print", ctx=Load()),
...                 args=[
...                     FormattedValue(
...                         value=Name(id="name_1", ctx=Load()),
...                         conversion=-1,
...                     )
...                 ],
...                 keywords=[],
...             ),
...         )
...     ],
...     type_ignores=[],
... )
>>> fix_missing_locations(tree)
>>> code = unparse(tree)
>>> code
'print({name_1})'
>>> name_1 = 'abc'
>>> eval(compile(tree, 'str', 'exec'))
abc
```

**Comment by sobolevn** [comment]
cc @pablogsal @lysnikolaou 
I have a PR that kinda fixes this, but I need someone to also valide this issue first :)

**Comment by tomasr8** [comment]
I'm guessing it's because when parsing e.g. `f'{foo}'` we get `JoinedStr` instead of just `FormattedValue`:

```python
>>> from ast import parse
>>> parse("f'{a}'", mode='eval').body
<ast.JoinedStr object at 0x7f7809963bc0>
```
That's also probably why this is missed by the unparse tests

**Comment by lysnikolaou** [comment]
Hmm, I'm a bit confused. I didn't know about that statement in the docs, and from the parser's point of view, it sounds kinda wrong, since we always produce an `ast.JoinedStr`. I'd be okay with fixing this specific issue, but I'd also say we remove this statement from the docs.

@pablogsal @isidentical What do you think?

**Comment by sobolevn** [comment]
@lysnikolaou don't forget that `exec`uting `ast.FormattedValue` also works for some reason.

**Comment by 15r10nk** [comment]
> but I'd also say we remove this statement from the docs.

I should point out that I don't need this feature for anything. I stumbled about the inconsistency in the docs while I was writing tests for [pysource-codegen](https://github.com/15r10nk/pysource-codegen). It would be also ok for me if the docs are fixed and the change is added to the changelogs.

**Comment by lysnikolaou** [comment]
Yeah, I saw that, but that seems to me like it should be more of an implementation detail than a documented feature, especially since `ast.parse` will produce an `ast.JoinedStr` in all cases. I might be missing somthing though.

**Comment by 15r10nk** [comment]
I found something else during my tests.
The astunparse library has also problems with a `FormattedValue` without an `JoinedStr`.
Maybe this helps something.

```python
from ast import *
from astunparse import unparse

tree = Module(
    body=[
        Expr(
            value=FormattedValue(
                value=Name(id="name_1", ctx=Load()),
                conversion=-1,
            )
        )
    ],
    type_ignores=[],
)

unparse(tree)

```

output (Python 3.9.18):
```python
Traceback (most recent call last):
  File "/home/frank/projects/pysource-playground/pysource-codegen/codi.py", line 16, in <module>
    unparse(tree)
  File "/home/frank/projects/pysource-playground/pysource-codegen/venv3.9/lib/python3.9/site-packages/astunparse/__init__.py", line 13, in unparse
    Unparser(tree, file=v)
  File "/home/frank/projects/pysource-playground/pysource-codegen/venv3.9/lib/python3.9/site-packages/astunparse/unparser.py", line 38, in __init__
    self.dispatch(tree)
  File "/home/frank/projects/pysource-playground/pysource-codegen/venv3.9/lib/python3.9/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/home/frank/projects/pysource-playground/pysource-codegen/venv3.9/lib/python3.9/site-packages/astunparse/unparser.py", line 78, in _Module
    self.dispatch(stmt)
  File "/home/frank/projects/pysource-playground/pysource-codegen/venv3.9/lib/python3.9/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/home/frank/projects/pysource-playground/pysource-codegen/venv3.9/lib/python3.9/site-packages/astunparse/unparser.py", line 90, in _Expr
    self.dispatch(tree.value)
  File "/home/frank/projects/pysource-playground/pysource-codegen/venv3.9/lib/python3.9/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/home/frank/projects/pysource-playground/pysource-codegen/venv3.9/lib/python3.9/site-packages/astunparse/unparser.py", line 485, in _FormattedValue
    self._fstring_JoinedStr(t, string.write)
  File "/home/frank/projects/pysource-playground/pysource-codegen/venv3.9/lib/python3.9/site-packages/astunparse/unparser.py", line 489, in _fstring_JoinedStr
    for value in t.values:
AttributeError: 'FormattedValue' object has no attribute 'values'
```
unparsing an normal `JoinedStr` works.

**Comment by sunmy2019** [comment]
> from the parser's point of view, it sounds kinda wrong, since we always produce an `ast.JoinedStr`.

I agree with that.

`ast.unparse` should not give any guarantee for AST not produced from `ast.parse` (i.e. valid AST generated from the compiler).

We should only commit to the validity of `ast.unparse(ast.parse(...)`.

**Comment by sunmy2019** [comment]
> This AST produces the correct `eval` result, but incorrect `unparse`:

Not all AST can be converted to source code, just like you are not always able to convert valid Python byte code (pyc) to Python source code.

"AST --> source code" conversion should be only kept guaranteed for "source code --> AST".
