### ISSUE TITLE
Traceback formatting issue: `SyntaxError` and `ExceptionGroup`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111334]
# Bug report

When raising `SyntaxError` with `ExceptionGroup` the traceback formatting seems to be broken:

```python
>>> e = SyntaxError("error", ("x.py", 23, None, "bad syntax"))
>>> raise ExceptionGroup('A', [e])
  + Exception Group Traceback (most recent call last):
  |   File "<stdin>", line 1, in <module>
  | ExceptionGroup: A (1 sub-exception)
  +-+---------------- 1 ----------------
    |   File "x.py", line 23
    bad syntax
    | SyntaxError: error
    +------------------------------------
```

Note that `bad syntax` is not properly prefixed by `| ` and not indented properly.

Compare it with:

```python
>>> raise e
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "x.py", line 23
    bad syntax
SyntaxError: error
```

I expect it to be:

```python
  + Exception Group Traceback (most recent call last):
  |   File "<stdin>", line 1, in <module>
  | ExceptionGroup: A (1 sub-exception)
  +-+---------------- 1 ----------------
    |   File "x.py", line 23
    |     bad syntax
    | SyntaxError: error
    +------------------------------------
```

This causes some side-effects on my work in https://github.com/python/cpython/issues/104150
So, I've prepared a PR to fix it. Polishing it and send today / tomorrow.

CC @iritkatriel

**Comment by sobolevn** [comment]
It is fixed on `main`, but not on `3.11.5`.
This is the second time today I run a different python version 😒
