### ISSUE TITLE
idle doesn't display nested tracebacks for ExceptionGroups

### ISSUE THREAD

**Issue by graingert** [python/cpython#111414]
# Bug report

### Bug description:

Idle prints:
```
Python 3.13.0a1+ (main, Oct 20 2023, 08:50:56) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license()" for more information.
raise ExceptionGroup("bad", [ValueError()])
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    raise ExceptionGroup("bad", [ValueError()])
ExceptionGroup: bad (1 sub-exception)
```

the repl displays tracebacks correctly:

```
Python 3.13.0a1+ (main, Oct 20 2023, 08:50:56) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> raise ExceptionGroup("bad", [ValueError()])
  + Exception Group Traceback (most recent call last):
  |   File "<stdin>", line 1, in <module>
  |     raise ExceptionGroup("bad", [ValueError()])
  | ExceptionGroup: bad (1 sub-exception)
  +-+---------------- 1 ----------------
    | ValueError
    +------------------------------------ 
```

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Linux

**Comment by graingert** [comment]
here's where the traceback is cleaned and printed:

https://github.com/python/cpython/blob/9d4a1a480b65196c3aabbcd2d165d1fb86d0c8e5/Lib/idlelib/run.py#L261-L266

**Comment by serhiy-storchaka** [comment]
Resolved by gh-139551 (#139563): IDLE's Shell and Debugger now render nested `ExceptionGroup` tracebacks, matching the REPL, with tests in `idlelib/idle_test/test_run.py`. The original example now displays the sub-exceptions. Closing as fixed.
