### ISSUE TITLE
`typing.rst` contains failing doctests

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111681]
# Bug report

```pytb
» ./python.exe -m doctest Doc/library/typing.rst
**********************************************************************
File "Doc/library/typing.rst", line 1959, in typing.rst
Failed example:
    get_origin(P.args) is P
Exception raised:
    Traceback (most recent call last):
      File "/Users/sobolev/Desktop/cpython2/Lib/doctest.py", line 1374, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest typing.rst[15]>", line 1, in <module>
        get_origin(P.args) is P
        ^^^^^^^^^^
    NameError: name 'get_origin' is not defined
**********************************************************************
File "Doc/library/typing.rst", line 1961, in typing.rst
Failed example:
    get_origin(P.kwargs) is P
Exception raised:
    Traceback (most recent call last):
      File "/Users/sobolev/Desktop/cpython2/Lib/doctest.py", line 1374, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest typing.rst[16]>", line 1, in <module>
        get_origin(P.kwargs) is P
        ^^^^^^^^^^
    NameError: name 'get_origin' is not defined
**********************************************************************
1 items had failures:
   2 of  47 in typing.rst
***Test Failed*** 2 failures.
                               
```

My proposal is too:
1. Fix it 
2. Add a test to `test_typing` to ensure that doctests pass

### Linked PRs
* gh-111682
* gh-112035
* gh-112037

**Comment by AlexWaygood** [comment]
The doctests in `typing.rst` aren't designed to be run via `python -m doctest`. They're designed to be run via Sphinx; we have special directives like this, which instruct Sphinx to run blocks of code prior to every doctest, but which wouldn't have any impact if you just ran the doctests via `python -m doctest`:

https://github.com/python/cpython/blob/d49aba5a7a3c695213810a9f82715809c6332df2/Doc/library/typing.rst?plain=1#L5-L9
