### ISSUE TITLE
Segmentation fault during garbage collection

### ISSUE THREAD

**Issue by jefferyto** [python/cpython#111629]
# Crash report

### What happened?

This is an issue one of our (OpenWrt packages feed) contributors opened: https://github.com/openwrt/packages/issues/21764

I tried to reproduce the issue on arm, aarch64, mips, i386, and x86_64 (all using qemu, running a current OpenWrt snapshot); I was able to reproduce it on arm and mips.

The segfault appears to happen during gc after running a subprocess. I built Python with debug symbols to run with gdb:

```
Program received signal SIGSEGV, Segmentation fault.
deduce_unreachable (base=base@entry=0xb6f56884 <_PyRuntime+31476>, unreachable=0xbefff454, unreachable@entry=0xbefff44c) at Modules/gcmodule.c:1099
1099	Modules/gcmodule.c: No such file or directory.
```

Backtrace:

```
#0  deduce_unreachable (base=base@entry=0xb6f56884 <_PyRuntime+31476>, unreachable=0xbefff454, unreachable@entry=0xbefff44c) at Modules/gcmodule.c:1099
#1  0xb6dac884 in gc_collect_main (tstate=tstate@entry=0xb6f63970 <_PyRuntime+84960>, generation=generation@entry=0, n_collected=0xb6f56894 <_PyRuntime+31492>, n_collected@entry=0xbefff4ec, n_uncollectable=0x0, n_uncollectable@entry=0xbefff4e8, nofail=nofail@entry=0) at Modules/gcmodule.c:1226
#2  0xb6cc6c1c in gc_collect_with_callback (tstate=0xb6f63970 <_PyRuntime+84960>, generation=0) at Modules/gcmodule.c:1400
#3  0xb6cc6d90 in gc_collect_generations (tstate=<optimized out>) at Modules/gcmodule.c:1455
#4  _PyObject_GC_Link (op=op@entry=0xb6765370) at Modules/gcmodule.c:2270
#5  0xb6cc6dec in gc_alloc (basicsize=<optimized out>, presize=8) at Modules/gcmodule.c:2290
#6  0xb6cda99c in _PyObject_GC_New (tp=0xb6f3ee98 <PyCell_Type>) at Modules/gcmodule.c:2298
#7  0xb6cde008 in PyCell_New (obj=0xb6b9ee38) at Objects/cellobject.c:11
#8  0xb6c8b4b0 in _PyEval_EvalFrameDefault (tstate=0x0, frame=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3115
#9  0xb6de6c3c in _PyEval_Vector (tstate=0xb6f63970 <_PyRuntime+84960>, func=func@entry=0xb6afe168, locals=<optimized out>, args=<optimized out>, argcount=argcount@entry=2, kwnames=kwnames@entry=0x0) at Python/ceval.c:6425
#10 0xb6debae4 in _PyFunction_Vectorcall (func=0xb6afe168, stack=<optimized out>, nargsf=<optimized out>, kwnames=0x0) at Objects/call.c:396
#11 0xb6d5cef8 in _PyObject_Call (tstate=0xb6f63970 <_PyRuntime+84960>, callable=0xb6afe168, args=0xb66ca4c8, kwargs=0xb675db40) at Objects/call.c:328
#12 0xb6c90238 in _PyEval_EvalFrameDefault (tstate=0x0, frame=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:5367
#13 0xb6de6c3c in _PyEval_Vector (tstate=0xb6f63970 <_PyRuntime+84960>, func=func@entry=0xb6739208, locals=<optimized out>, args=<optimized out>, argcount=argcount@entry=2, kwnames=kwnames@entry=0xb66ca368) at Python/ceval.c:6425
#14 0xb6debae4 in _PyFunction_Vectorcall (func=0xb6739208, stack=<optimized out>, nargsf=<optimized out>, kwnames=0xb66ca368) at Objects/call.c:396
#15 0xb6d5d758 in _PyObject_FastCallDictTstate (tstate=0xb6f63970 <_PyRuntime+84960>, callable=0xb6739208, args=<optimized out>, nargsf=2, kwargs=0xb675d9d8) at Objects/call.c:152
#16 0xb6d5d81c in _PyObject_Call_Prepend (tstate=0xb6f63970 <_PyRuntime+84960>, callable=0xb6739208, obj=0xb66ca410, args=0xb6765178, kwargs=0xb675d9d8) at Objects/call.c:482
#17 0xb6d69ef4 in slot_tp_init (self=0xb66ca410, args=0xb6765178, kwds=0xb675d9d8) at Objects/typeobject.c:7854
#18 0xb6ce249c in type_call (type=0xb67387a8, args=0xb6765178, kwds=0xb675d9d8) at Objects/typeobject.c:1103
#19 0xb6d177b8 in _PyObject_MakeTpCall (tstate=0xb6f63970 <_PyRuntime+84960>, callable=0xb67387a8, args=<optimized out>, nargs=1, keywords=0xb674f068) at Objects/call.c:214
#20 0xb6d1ac58 in PyObject_Vectorcall (callable=0xb67387a8, args=<optimized out>, nargsf=2147483649, kwnames=0xb674f068) at Objects/call.c:299
#21 0xb6c8ec44 in _PyEval_EvalFrameDefault (tstate=0x0, frame=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:4760
#22 0xb6de6c3c in _PyEval_Vector (tstate=0xb6f63970 <_PyRuntime+84960>, func=func@entry=0xb6755cf8, locals=<optimized out>, args=<optimized out>, argcount=argcount@entry=4, kwnames=kwnames@entry=0x0) at Python/ceval.c:6425
#23 0xb6debae4 in _PyFunction_Vectorcall (func=0xb6755cf8, stack=<optimized out>, nargsf=<optimized out>, kwnames=0x0) at Objects/call.c:396
#24 0xb6d5d6fc in _PyObject_FastCallDictTstate (tstate=0xb6f63970 <_PyRuntime+84960>, callable=0xb6755cf8, args=0xbefff944, nargsf=4, kwargs=0x0) at Objects/call.c:141
#25 0xb6d5d81c in _PyObject_Call_Prepend (tstate=0xb6f63970 <_PyRuntime+84960>, callable=0xb6755cf8, obj=0xb66ca430, args=0xb675ccc8, kwargs=0x0) at Objects/call.c:482
#26 0xb6d69ef4 in slot_tp_init (self=0xb66ca430, args=0xb675ccc8, kwds=0x0) at Objects/typeobject.c:7854
#27 0xb6ce249c in type_call (type=0xb675b028, args=0xb675ccc8, kwds=0x0) at Objects/typeobject.c:1103
#28 0xb6d177b8 in _PyObject_MakeTpCall (tstate=0xb6f63970 <_PyRuntime+84960>, callable=0xb675b028, args=<optimized out>, nargs=3, keywords=0x0) at Objects/call.c:214
#29 0xb6d1ac58 in PyObject_Vectorcall (callable=0xb675b028, args=<optimized out>, nargsf=2147483651, kwnames=0x0) at Objects/call.c:299
#30 0xb6c8ec44 in _PyEval_EvalFrameDefault (tstate=0x0, frame=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:4760
#31 0xb6de6c3c in _PyEval_Vector (tstate=tstate@entry=0xb6f63970 <_PyRuntime+84960>, func=func@entry=0xb6afef78, locals=locals@entry=0xb6b28bb8, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:6425
#32 0xb6de6f4c in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=0xb6b28bb8) at Python/ceval.c:1140
#33 0xb6deb984 in builtin_exec_impl (module=<optimized out>, closure=<optimized out>, locals=0xb6b28bb8, globals=0xb6b28bb8, source=0xb6bd85c0) at Python/bltinmodule.c:1077
#34 builtin_exec (module=<optimized out>, args=<optimized out>, args@entry=0xb6b840c8, nargs=nargs@entry=2, kwnames=kwnames@entry=0x0) at Python/clinic/bltinmodule.c.h:465
#35 0xb6cd22d4 in cfunction_vectorcall_FASTCALL_KEYWORDS (func=0xb6b91730, args=0xb6b840c8, nargsf=<optimized out>, kwnames=0x0) at Objects/methodobject.c:443
#36 0xb6d17864 in _PyObject_VectorcallTstate (tstate=0xb6f63970 <_PyRuntime+84960>, callable=0xb6b91730, args=0xb6b840c8, nargsf=2147483650, kwnames=0x0) at ./Include/internal/pycore_call.h:92
#37 0xb6d1ac58 in PyObject_Vectorcall (callable=0xb6b91730, args=<optimized out>, nargsf=2147483650, kwnames=0x0) at Objects/call.c:299
#38 0xb6c8ec44 in _PyEval_EvalFrameDefault (tstate=0x0, frame=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:4760
#39 0xb6de6c3c in _PyEval_Vector (tstate=0xb6f63970 <_PyRuntime+84960>, func=func@entry=0xb6afed98, locals=<optimized out>, args=<optimized out>, argcount=argcount@entry=2, kwnames=kwnames@entry=0x0) at Python/ceval.c:6425
#40 0xb6debae4 in _PyFunction_Vectorcall (func=0xb6afed98, stack=<optimized out>, nargsf=<optimized out>, kwnames=0x0) at Objects/call.c:396
#41 0xb6d5cef8 in _PyObject_Call (tstate=0xb6f63970 <_PyRuntime+84960>, callable=0xb6afed98, args=0xb6addfa8, kwargs=0x0) at Objects/call.c:328
#42 0xb6de2c14 in pymain_run_module (modname=<optimized out>, set_argv0=1) at Modules/main.c:300
#43 0xb6de81b4 in pymain_run_python (exitcode=0xbefffcfc) at Modules/main.c:598
#44 Py_RunMain () at Modules/main.c:680
#45 0xb6e0e618 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:734
#46 0xb6fac42c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Terminal session logs (created with `script`): [arm](https://github.com/python/cpython/files/13234210/arm.log), [mips](https://github.com/python/cpython/files/13234211/mips.log)
Core file: [arm](https://github.com/python/cpython/files/13234209/arm.core.zip) (was not able to generate a core file for mips)

Please let me know if there is any other information I can provide :pray:

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.11.6 (main, Oct 27 2023, 18:43:06) [GCC 12.3.0]

**Comment by StanFromIreland** [comment]
Closing, without a reproducer I can't confirm if this is still an issue, and it's difficult to work on a fix.

**Comment by jefferyto** [comment]
@StanFromIreland I don't have a reproducer (as the issue is triggered from [tunneldigger](https://github.com/wlanslovenija/tunneldigger) which I know nothing about), but as a matter of courtesy it would have been nice to be asked for a reproducer before having this issue closed.
