### ISSUE TITLE
Socket.recvmsg can't receive file descriptor on FreeBSD

### ISSUE THREAD

**Issue by ppodds** [python/cpython#111675]
# Bug report

### Bug description:

It seems `socket.recvmsg` can't receive file descriptors on FreeBSD. Is it a normal behavior or actually a bug?

## Reproduce

`server.py`
```python
import socket
import array

sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
sock.bind('server.sock')
sock.listen(1)

def handle_client():
    while True:
        conn, addr = sock.accept()
        a = array.array('i')
        bytes_size = a.itemsize * 1
        msg, ancdata, flags, addr = conn.recvmsg(1, socket.CMSG_LEN(bytes_size))
        print(msg)
        print(ancdata)

handle_client()
```

`client.py`
```python
import socket
import array
import os

sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
sock.connect('server.sock')
fds = array.array('i', [os.pipe()[0]])
msg = bytes([len(fds) % 256])
t = [(socket.SOL_SOCKET, socket.SCM_RIGHTS, fds)]
print(t)
```

## Output

`server.py`
```
// FreeBSD
b'\x01'
[]
// Linux
b'\x01'
[(1, 1, b'\x08\x00\x00\x00')]
```

`client.py`
```
// FreeBSD
b'\x01'
[(65535, 1, array('i', [4]))]
// Linux
b'\x01'
[(1, 1, array('i', [4]))
```

## Extra Information

Test on:
FreeBSD 13.2-REALEASE
Python 3.9.18 (install by pkg)

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux, Other

**Comment by vstinner** [comment]
You can use `socket.send_fds()` and `socket.recv_fds()`. It works as expected on FreeBSD. Python works as expected, I close the issue.

Example of server:

```py
import socket
import os

sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
name = 'server.sock'
sock.bind(name)
sock.listen(1)

def handle_client():
    while True:
        conn, addr = sock.accept()

        buf_size = 100
        max_fds = 10
        msg, fds, flags, addr = socket.recv_fds(conn, buf_size, max_fds)
        print(msg, fds, flags, addr)
        conn.close()

        fd = fds[0]
        data = os.read(fd, 100)
        print("read():", data)

try:
    handle_client()
except KeyboardInterrupt:
    pass
sock.close()
os.unlink(name)
```

Example of client:

```py
import socket
import array
import os

fd, fd2 = os.pipe()
os.set_inheritable(fd, True)
os.set_inheritable(fd2, True)

os.write(fd2, b"hello world")

sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
sock.connect('server.sock')

print("send", [b'data'], [fd])
res = socket.send_fds(sock, [b'data'], [fd])
print("send_fds", res)
if 0:
    fds = array.array('i', [fd])
    msg = bytes([len(fds) % 256])
    t = [(socket.SOL_SOCKET, socket.SCM_RIGHTS, fds)]
    print(t)
sock.close()
```

Server output:

```
b'data' [5] 0 None
read(): b'hello world'
```

Client output:

```
send [b'data'] [3]
send_fds 4
```

The server receives the file descriptor 5 and can read from it: it gets "hello world" string.

**Comment by rhaberkorn** [comment]
@vstinner Something is still wrong here. Try setting `max_fds = 1` which should still work. I get the following error:
```
b'data' [] 32 None
Traceback (most recent call last):
  File "/home/rhaberkorn/./server.py", line 24, in <module>
    handle_client()
  File "/home/rhaberkorn/./server.py", line 19, in handle_client
    fd = fds[0]
IndexError: list index out of range
```

The 32 for the returned flag means
> MSG_CTRUNC indicates that some control data were discarded due to lack of space in the buffer
> for ancillary data.  MSG_OOB is returned to indicate that expedited or
> out-of-band data were received.

Interestingly, this goes away even when setting `max_fds = 2`.

**Comment by vstinner** [comment]
> Interestingly, this goes away even when setting max_fds = 2.

I have no idea why it doesn't work with max_fds=1, nor what flags=32 means in this case. I'm not sure that it's a bug in Python.
