### ISSUE TITLE
AssertionError: 'LOAD_GLOBAL_MODULE' not found in {'RETURN_VALUE', 'RESUME_CHECK', 'LOAD_GLOBAL'} in test_opcache.py

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#111760]
# Bug report

Configuration:
```
./configure --with-pydebug
```

```python
➜  cpython git:(main) ./python -m test test_opcache -R 16:9 -j16   
Using random seed: 2017792323
0:00:00 load avg: 7.53 Run 1 test in parallel using 1 worker process
0:00:14 load avg: 6.15 [1/1/1] test_opcache failed (1 failure)
beginning 25 repetitions
1234567890123456789012345
...............test test_opcache failed -- Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_opcache.py", line 924, in test_load_global_module
    self.assert_races_do_not_crash(
  File "/home/arf/cpython/Lib/test/test_opcache.py", line 21, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/arf/cpython/Lib/test/test_opcache.py", line 540, in assert_races_do_not_crash
    self.assert_specialized(item, opname)
  File "/home/arf/cpython/Lib/test/test_opcache.py", line 520, in assert_specialized
    self.assertIn(opname, opnames)
AssertionError: 'LOAD_GLOBAL_MODULE' not found in {'RETURN_VALUE', 'RESUME_CHECK', 'LOAD_GLOBAL'}

== Tests result: FAILURE ==

1 test failed:
    test_opcache

Total duration: 14.2 sec
Total tests: run=52 failures=1
Total test files: run=1/1 failed=1
Result: FAILURE

```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

OS: Arch Linux x86_64

**Comment by furkanonder** [comment]
CC: @brandtbucher

**Comment by brandtbucher** [comment]
Hm, I wonder if we're running out of module versions by doing this so many times. But there will always be some upper limit on how many times the test can be run before it stops specializing (at least without making it so much more complicated by running each one in a subprocess or something).

I'm not 100% convinced that this strange edge case is really worth fixing, if so.

**Comment by picnixz** [comment]
@furkanonder Any reason to remove the bug label?
