### ISSUE TITLE
`Doc/library/sqlite3.rst` has multiple doctest warnings

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111726]
# Bug report

Link: https://github.com/python/cpython/actions/runs/6753865568/job/18360794210?pr=111723#step:8:82

```pytb
Document: library/sqlite3
-------------------------
Exception ignored in: <sqlite3.Connection object at 0x7f1684307130>
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/functools.py", line 55, in update_wrapper
    pass
ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f1684307130>
Exception ignored in: <sqlite3.Connection object at 0x7f1684307ac0>
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/functools.py", line 55, in update_wrapper
    pass
ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f1684307ac0>
Exception ignored in: <sqlite3.Connection object at 0x7f16891eb680>
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/functools.py", line 55, in update_wrapper
    pass
ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f16891eb680>
Exception ignored in: <sqlite3.Connection object at 0x7f16891eb240>
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/functools.py", line 55, in update_wrapper
    pass
ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f16891eb240>
Exception ignored in: <sqlite3.Connection object at 0x7f16891ea9c0>
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/functools.py", line 55, in update_wrapper
    pass
ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f16891ea9c0>
Exception ignored in: <sqlite3.Connection object at 0x7f16891eb350>
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/functools.py", line 55, in update_wrapper
    pass
ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f16891eb350>
Exception ignored in: <sqlite3.Connection object at 0x7f16891eb130>
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/functools.py", line 55, in update_wrapper
    pass
ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f16891eb130>
Exception ignored in: <sqlite3.Connection object at 0x7f16891ea8b0>
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/functools.py", line 55, in update_wrapper
    pass
ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f16891ea8b0>
Exception ignored in: <sqlite3.Connection object at 0x7f16891e9bf0>
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/functools.py", line 55, in update_wrapper
    pass
ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f16891e9bf0>
4 items passed all tests:
  71 tests in default
   3 tests in sqlite3.cursor
   3 tests in sqlite3.limits
   8 tests in sqlite3.trace
85 tests in 4 items.
85 passed and 0 failed.
Test passed.
Exception ignored in sys.unraisablehook: <function debug at 0x7f167bb73c50>
Traceback (most recent call last):
  File "<doctest sqlite3.trace[4]>", line 2, in debug
AttributeError: 'sqlite3.Connection' object has no attribute '__name__'
Exception ignored in sys.unraisablehook: <function debug at 0x7f167bb73c50>
Traceback (most recent call last):
  File "<doctest sqlite3.trace[4]>", line 2, in debug
AttributeError: 'sqlite3.Connection' object has no attribute '__name__'
Exception ignored in sys.unraisablehook: <function debug at 0x7f167bb73c50>
Traceback (most recent call last):
  File "<doctest sqlite3.trace[4]>", line 2, in debug
AttributeError: 'sqlite3.Connection' object has no attribute '__name__'
Exception ignored in sys.unraisablehook: <function debug at 0x7f167bb73c50>
Traceback (most recent call last):
  File "<doctest sqlite3.trace[4]>", line 2, in debug
AttributeError: 'sqlite3.Connection' object has no attribute '__name__'
Exception ignored in sys.unraisablehook: <function debug at 0x7f167bb73c50>
Traceback (most recent call last):
  File "<doctest sqlite3.trace[4]>", line 2, in debug
AttributeError: 'sqlite3.Connection' object has no attribute '__name__'
```

I will examine possible fixes and send a PR.

### Linked PRs
* gh-111730
* gh-117622
* gh-117623
* gh-117625
* gh-117630

**Comment by hugovk** [comment]
Triage: the linked PRs are merged, can this be closed?
