### ISSUE TITLE
раньше - в версии python - 3.11 этот код работал стабильно , но в версии python - 3.12.0 64-bit похоже перестала работать библиотека - pygame !.. )

### ISSUE THREAD

**Issue by Worker14** [python/cpython#112091]
# Bug report

### Bug description:

```python
# print( 0.1 * 0.1 * 0.1 )
# print( 0.1 ** 3 )

# # подсчитываем количество введённых символов
# first_string = input( "Здравствуйте! - как дела??? 😁 🌈 🤑 - " )
# number_of_characters = int(len( first_string ))
# print( "                                                 " )
# print( "В вашей фразе - ", first_string, " - ", number_of_characters, " символов" )
# print( "                                                 " )

# округляем число
# third_number = round(float(input( "Введите - любое число: " )))
# print( "                                                 " )
# print( "Вот - ваше округлённое число - ", third_number )
# # print( "Hello, Artem" )
# print( "                                                 " )
# print( "разработай - или - умри ! 😁 🌈 🤑" )
# print( "                                                 " )

# from graphics import *

# win = GraphWin("Окно для графики", 400, 400)
# win.setBackground("black")

# win.getMouse()
# win.close()

# from graphics import * # импортируем библиотеку graphics
# win = GraphWin("Окно для графики", 1000, 1000) # создаём окно для графики размером 400 на 400 пикселей
# win.setBackground("blaсk")

# obj = Point(400, 400) # создаём точку в координатах (50, 50)
# obj.draw(win) # отображаем точку в окне для графики
# win.getMouse() # ждём нажатия кнопки мыши
# win.close() # закрываем окно для графики

# from graphics import *

# win = GraphWin("Окно для графики - разработай или умри ! 😁 🌈 🤑", 1530, 1000)
# win.setBackground("black")

# obj = Point(765, 500) # создаём точку в координатах (400, 400)
# obj.setFill("green")
# obj.draw(win) # отображаем точку в окне для графики

# center = Point(765, 500)
# radius = 450
# circle = Circle(center, radius)
# circle.setOutline("red")
# circle.draw(win)

# # center_2 = Point(600, 600)
# # radius_2 = 75
# # circle_2 = Circle(center_2, radius_2)
# # circle_2.setFill("#f50521")
# # circle_2.draw(win)

# win.getMouse() # ждём нажатия кнопки мыши

# win.close() # закрываем окно для графики

# from graphics import *

# win = GraphWin("Окно для графики", 400, 400)

# center = Point(200, 200) # центр окружности
# radius = 100 # радиус окружности
# angle = 0 # начальный угол луча радара
# step = 5 # шаг изменения угла луча радара
# line_length = 80 # длина луча радара
# line_color = "white" # цвет луча радара
# background_color = "black" # цвет фона

# # рисуем окружность
# circle = Circle(center, radius)
# circle.setOutline(background_color)
# circle.draw(win)

# # рисуем луч радара
# while True:
#     # вычисляем координаты конца луча радара
#     x = center.getX() + line_length * math.cos(math.radians(angle))
#     y = center.getY() - line_length * math.sin(math.radians(angle))
#     end_point = Point(x, y)

#     # рисуем линию луча радара
#     line = Line(center, end_point)
#     line.setFill(line_color)
#     line.setWidth(2)
#     line.draw(win)

#     # ждём нажатия кнопки мыши или некоторое время
#     if win.checkMouse() is not None:
#         break
#     time.sleep(0.05)

#     # стираем линию луча радара
#     line.undraw()

#     # увеличиваем угол луча радара
#     angle += step

# win.close()

# from graphics import *
# import math

# win = GraphWin("Окно для графики", 400, 400)

# center = Point(200, 200) # центр окружности
# radius = 100 # радиус окружности
# angle = 0 # начальный угол луча радара
# step = 5 # шаг изменения угла луча радара
# line_length = 80 # длина луча радара
# line_color = "white" # цвет луча радара
# background_color = "black" # цвет фона

# # рисуем окружность
# for x in range(center.getX() - radius, center.getX() + radius):
#     y = math.sqrt(radius ** 2 - (x - center.getX()) ** 2) + center.getY()
#     point = Point(x, y)
#     point.setFill(background_color)
#     point.draw(win)

#     y = -math.sqrt(radius ** 2 - (x - center.getX()) ** 2) + center.getY()
#     point = Point(x, y)
#     point.setFill(background_color)
#     point.draw(win)

# # рисуем луч радара
# while True:
#     # вычисляем координаты конца луча радара
#     x = center.getX() + line_length * math.cos(math.radians(angle))
#     y = center.getY() - line_length * math.sin(math.radians(angle))
#     end_point = Point(x, y)

#     # рисуем линию луча радара
#     line = Line(center, end_point)
#     line.setFill(line_color)
#     line.setWidth(2)
#     line.draw(win)

#     # ждём нажатия кнопки мыши или некоторое время
#     if win.checkMouse() is not None:
#         break
#     time.sleep(0.05)

#     # стираем линию луча радара
#     line.undraw()

#     # увеличиваем угол луча радара
#     angle += step

# win.close()

from graphics import *
import math
import pygame
import threading
import datetime

start_time = datetime.datetime.now()



def play_music():
    pygame.mixer.music.load("C:\\Users\\Пользователь\\Music\\Кино — Хочу перемен (www.lightaudio.ru).mp3")
    pygame.mixer.music.play()

    while pygame.mixer.music.get_busy():
        pygame.time.Clock().tick(10)


def play_music_2():
    pygame.mixer.music.load("C:\\Users\\Пользователь\\Music\\Вера Брежнева — Любовь Спасет Мир (www.lightaudio.ru).mp3")
    pygame.mixer.music.play()

    while pygame.mixer.music.get_busy():
        pygame.time.Clock().tick(10)


pygame.init()

pygame.display.set_mode((600, 800))

# x = 0 # создаём - переменную - счётчик - цикла


t = threading.Thread(target=play_music)
t.start()


# while True:
#     # здесь можно добавить код для отображения графики
#     pass

# pygame.init()

# pygame.mixer.music.load("C:\\Music\\Кино — Хочу перемен (www.lightaudio.ru).mp3")
# pygame.mixer.music.play()

# while pygame.mixer.music.get_busy():
#     pygame.time.Clock().tick(10)

win = GraphWin("окно для графики 😁 🌈 🤑", 800, 800)

center = Point(400, 500) # центр окружности
radius = 200 # радиус окружности
angle = 0 # начальный угол луча радара
step = 5 # шаг изменения угла луча радара
line_length = radius - 1 # длина луча радара
line_color = "green" # цвет луча радара
background_color = "black" # цвет фона
circle_color = "red" # цвет окружности

win.setBackground(background_color)

# выводим - надписи

text = Text(Point(400, 100), "улыбайтесь !!!")
text.setSize(30)
text.setTextColor(circle_color)
text.draw(win)

# text = Text(Point(400, 200), "а - надо - выебать - всех баб!!! )")
# text.setSize(30)
# text.setTextColor(circle_color)
# text.draw(win)

# рисуем окружность

circle = Circle(center, radius)
circle.setOutline(circle_color)
circle.draw(win)

# for x in range(int(center.getX() - radius), int(center.getX() + radius)):
#     y = math.sqrt(radius ** 2 - (x - center.getX()) ** 2) + center.getY()
#     point = Point(x, y)
#     point.setFill(circle_color)
#     point.draw(win)

#     y = -math.sqrt(radius ** 2 - (x - center.getX()) ** 2) + center.getY()
#     point = Point(x, y)
#     point.setFill(circle_color)
#     point.draw(win)

# рисуем луч радара
while True:
    # вычисляем координаты конца луча радара
    x = center.getX() + line_length * math.cos(math.radians(angle))
    y = center.getY() - line_length * math.sin(math.radians(angle))
    end_point = Point(x, y)

    # рисуем линию луча радара
    line = Line(center, end_point)
    line.setFill(line_color)
    line.setWidth(2)
    line.draw(win)

    # ждём нажатия кнопки мыши или некоторое время
    if win.checkMouse() is not None:
        break
    time.sleep(0.05)

    # стираем линию луча радара
    line.undraw()

    # увеличиваем угол луча радара
    angle += step

    # while x <= 320:

    # ваш код здесь

    end_time = datetime.datetime.now()

    elapsed_time = (end_time - start_time).total_seconds()

    current_time = int(elapsed_time)

    # print("время выполнения: ", elapsed_time, " секунд")

    # print(type(elapsed_time))

    if current_time == 296:
        # # останавливаем проигрывание первой песни
        # pygame.mixer.music.stop(),

        t = threading.Thread(target=play_music_2);
        t.start()

        # time.sleep(1)

        # x = x + 1



win.close()
```

error - 

PS C:\Users\Пользователь> & C:/Python312/python.exe "c:/users2/my files/intellectual property/code/Python/work3.py"
Traceback (most recent call last):
  File "c:\users2\my files\intellectual property\code\Python\work3.py", line 158, in <module>
    import pygame
  File "C:\Python312\Lib\site-packages\pygame\__init__.py", line 92, in <module>
    from pygame.base import *  # pylint: disable=wildcard-import; lgtm[py/polluting-import]  
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pygame.base'

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Windows

**Comment by gaogaotiantian** [comment]
I'm not a Russian expert here but I'm pretty sure this is not a CPython issue. I believe it's because you did not install `pygame` correctly on 3.12.

**Comment by Eclips4** [comment]
Здравствуйте!
Ваша проблема не связана с этим репозиторием, репозиторий CPython используется как баг-трэкер. Чтобы решить вашу проблему вам нужно установить `pygame`. А еще, по хорошему, прочитайте про `venv`, создайте его, активируйте, и устанавливайте уже туда `pygame`.
Так же возможна ситуация, что `pygame` просто еще не поддерживает 3.12 версию питона, учитывайте это. 
В следующий раз, когда будете открывать issue, оформьте его по-английски, пожалуйста. Шанс помощи в этом случае куда выше.

**Comment by Worker14** [comment]
я уже установил библиотеку - pygame с помощью команды - pip install pygame - но выводит приведённое сообщение о ошибке !.. ) 15.11.2023, 03:10, "Kirill Podoprigora" ***@***.***>:
Здравствуйте!
Ваша проблема не связана с этим репозиторием, репозиторий CPython используется как баг-трэкер. Чтобы решить вашу проблему вам нужно установить pygame. А еще, по хорошему, прочитайте про venv, создайте его, активируйте, и устанавливайте уже туда pygame.
Так же возможна ситуация, что pygame просто еще не поддерживает 3.12 версию питона, учитывайте это.
В следующий раз, когда будете открывать issue, оформьте его по-английски, пожалуйста. Шанс помощи в этом случае куда выше.
