### ISSUE TITLE
mimalloc: warning: unable to directly request hinted aligned OS memory

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#112027]
# Bug report

### Bug description:

Configuration:
```sh
./configure --disable-gil --with-pydebug
```
Test Output:
```pytb
dietpi@DietPi:~/cpython$ ./python -m test test_cmd_line -v
======================================================================
FAIL: test_pythonmalloc (test.test_cmd_line.CmdLineTest.test_pythonmalloc) (env_var='mimalloc', name='mimalloc')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dietpi/cpython/Lib/test/test_cmd_line.py", line 845, in test_pythonmalloc
    self.check_pythonmalloc(env_var, name)
  File "/home/dietpi/cpython/Lib/test/test_cmd_line.py", line 811, in check_pythonmalloc
    self.assertEqual(proc.stdout.rstrip(), name)
AssertionError: 'mimalloc: warning: unable to directly request hin[119 chars]lloc' != 'mimalloc'
- mimalloc: warning: unable to directly request hinted aligned OS memory (error: 2 (0x2), size: 0x40000000 bytes, alignment: 0x2000000, hint address: 0x20000000000)
  mimalloc


======================================================================
FAIL: test_pythonmalloc (test.test_cmd_line.CmdLineTest.test_pythonmalloc) (env_var='mimalloc_debug', name='mimalloc_debug')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dietpi/cpython/Lib/test/test_cmd_line.py", line 845, in test_pythonmalloc
    self.check_pythonmalloc(env_var, name)
  File "/home/dietpi/cpython/Lib/test/test_cmd_line.py", line 811, in check_pythonmalloc
    self.assertEqual(proc.stdout.rstrip(), name)
AssertionError: 'mimalloc: warning: unable to directly request hin[125 chars]ebug' != 'mimalloc_debug'
- mimalloc: warning: unable to directly request hinted aligned OS memory (error: 2 (0x2), size: 0x40000000 bytes, alignment: 0x2000000, hint address: 0x20000000000)
  mimalloc_debug


----------------------------------------------------------------------
Ran 56 tests in 41.751s

FAILED (failures=2, skipped=2)
test test_cmd_line failed
test_cmd_line failed (2 failures) in 43.1 sec

== Tests result: FAILURE ==

1 test failed:
    test_cmd_line
```

Environment:
```
dietpi@DietPi:~/cpython$ uname -a
Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-113372

**Comment by vstinner** [comment]
cc @DinoV

**Comment by corona10** [comment]
Can not reproduce the issue on macOS.

**Comment by furkanonder** [comment]
The [same issue](https://github.com/python/cpython/issues/112951) occurs with the RISC-V architecture.

**Comment by vstinner** [comment]
> Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

Is that Raspberry Pi hardware with 64-bit ARM CPU?

**Comment by vstinner** [comment]
> Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

Is that Raspberry Pi hardware with 64-bit ARM CPU?

**Comment by colesbury** [comment]
We should disable this warning. There's a few warnings from mimalloc that are emitted in debug mode that happen during normal operation and don't signify anything wrong. This is one of them.

**Comment by colesbury** [comment]
I ran into this on Linux x86-64 today as well. It's not limited Raspberry Pi (arm64) or RSIC-V.

Most of the time mmap() will place the mapping at the suggested address, but not always. That's fine -- it doesn't lead to the allocation failing, mimalloc just falls back to a slightly slower path.

**Comment by corona10** [comment]
@furkanonder Please check that the issue is solved :)

**Comment by furkanonder** [comment]
@corona10 I checked, the problem seems to be solved. So I am closing the issue. Thanks @corona10 @colesbury
