### ISSUE TITLE
When ast.parse parses a function, if the parameter character contains \n, it will fail.

### ISSUE THREAD

**Issue by CoinXu** [python/cpython#112168]
# Bug report

### Bug description:

```pycon
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> ast.dump(ast.parse('foo("bar")'))
"Module(body=[Expr(value=Call(func=Name(id='foo', ctx=Load()), args=[Constant(value='bar')], keywords=[]))], type_ignores=[])"
>>> ast.dump(ast.parse('foo("b\nar")')) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\coin\AppData\Local\Programs\Python\Python310\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    foo("b
        ^
SyntaxError: unterminated string literal (detected at line 1)
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by chgnrdv** [comment]
That's because Python interprets newline character `\n` in your source code string `'foo("b\nar")'` as a line break in this string itself, not in the string that is passed as a parameter to `foo` function. You should escape `\n` character with leading `\` in order to make this work.
```python
>>> exec('print("foo\nbar")')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    print("foo
          ^
SyntaxError: unterminated string literal (detected at line 1)
>>> exec('print("foo\\nbar")')
foo
bar
>>> 
```

**Comment by JelleZijlstra** [comment]
What @chgnrdv said.

**Comment by CoinXu** [comment]
@chgnrdv Oh, i see, thank you
