### ISSUE TITLE
AttributeError in 'python -m dis -C'

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#112620]
# Bug report

### Bug description:

Sorry @iritkatriel, I hit another crash in the new `dis` code:

```pytb
~/cpython$ ./python.exe -m dis -C Lib/re/_compiler.py >/dev/null
Traceback (most recent call last):
  File "/Users/guido/cpython/Lib/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
                     "__main__", mod_spec)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guido/cpython/Lib/runpy.py", line 88, in _run_code
    exec(code, run_globals)
    ~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/guido/cpython/Lib/dis.py", line 991, in <module>
    main()
    ~~~~^^
  File "/Users/guido/cpython/Lib/dis.py", line 988, in main
    dis(code, show_caches=args.show_caches, show_offsets=args.show_offsets)
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guido/cpython/Lib/dis.py", line 114, in dis
    _disassemble_recursive(x, file=file, depth=depth, show_caches=show_caches, adaptive=adaptive, show_offsets=show_offsets)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guido/cpython/Lib/dis.py", line 714, in _disassemble_recursive
    disassemble(co, file=file, show_caches=show_caches, adaptive=adaptive, show_offsets=show_offsets)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guido/cpython/Lib/dis.py", line 706, in disassemble
    _disassemble_bytes(_get_code_array(co, adaptive),
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                       lasti, co._varname_from_oparg,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
                       co_positions=co.co_positions(), show_caches=show_caches,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                       original_code=co.co_code, show_offsets=show_offsets)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guido/cpython/Lib/dis.py", line 777, in _disassemble_bytes
    print(instr._disassemble(lineno_width, is_current_instr, offset_width),
          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guido/cpython/Lib/dis.py", line 493, in _disassemble
    fields.append(' ' * self.label_width)
                        ^^^^^^^^^^^^^^^^
AttributeError: 'Instruction' object has no attribute 'label_width'
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-112621

**Comment by iritkatriel** [comment]
Thanks, I'll fix. In the meantime you can replace locally the ``self.label_width`` with ``getattr(self, label_width, 4)`` so you can get on with your work.
