### ISSUE TITLE
Problem with Python 3.7.7 script

### ISSUE THREAD

**Issue by VincenzoValvano** [python/cpython#112810]
# Crash report

### What happened?

```python
C:\Users\thede\AppData\Local\Programs\Python\Python37\NAO TESI>python3 App.py
Traceback (most recent call last):
  File "App.py", line 5, in <module>
    from ultralytics import YOLO
  File "C:\Users\thede\AppData\Local\Programs\Python\Python37\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.yolo.engine.model import YOLO
  File "C:\Users\thede\AppData\Local\Programs\Python\Python37\lib\site-packages\ultralytics\yolo\__init__.py", line 3, in <module>
    from . import v8
  File "C:\Users\thede\AppData\Local\Programs\Python\Python37\lib\site-packages\ultralytics\yolo\v8\__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, segment
  File "C:\Users\thede\AppData\Local\Programs\Python\Python37\lib\site-packages\ultralytics\yolo\v8\classify\__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "C:\Users\thede\AppData\Local\Programs\Python\Python37\lib\site-packages\ultralytics\yolo\v8\classify\predict.py", line 3, in <module>
    import torch
  File "C:\Users\thede\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\__init__.py", line 676, in <module>
    from .storage import _StorageBase, TypedStorage, _LegacyStorage, UntypedStorage
  File "C:\Users\thede\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\storage.py", line 11, in <module>
    import numpy as np
  File "C:\Users\thede\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\__init__.py", line 148, in <module>
    from . import _distributor_init
  File "C:\Users\thede\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\thede\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application.
```
This is the error when i trey to compile a python script.

### CPython versions tested on:

3.8

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
Sadly, but Python 3.7 is no longer supported. If you can reproduce this issue on 3.11+, please let us know. And also, please, attach the minimal reproducible example.
