### ISSUE TITLE
mimalloc: warning: unable to directly request hinted aligned OS memory [RISC-V]

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#112951]
# Bug report

### Bug description:

# Bug report

### Bug description:

Configuration:
```sh
./configure --with-pydebug
```
Test:
```sh
./python -m test test_cmd_line -v
```
Output:
```python
======================================================================
FAIL: test_pythonmalloc (test.test_cmd_line.CmdLineTest.test_pythonmalloc) (env_var='mimalloc', name='mimalloc')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/cpython/Lib/test/test_cmd_line.py", line 845, in test_pythonmalloc
    self.check_pythonmalloc(env_var, name)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/user/cpython/Lib/test/test_cmd_line.py", line 811, in check_pythonmalloc
    self.assertEqual(proc.stdout.rstrip(), name)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'mimalloc: warning: unable to directly request hin[119 chars]lloc' != 'mimalloc'
- mimalloc: warning: unable to directly request hinted aligned OS memory (error: 2 (0x2), size: 0x40000000 bytes, alignment: 0x2000000, hint address: 0x20000000000)
  mimalloc


======================================================================
FAIL: test_pythonmalloc (test.test_cmd_line.CmdLineTest.test_pythonmalloc) (env_var='mimalloc_debug', name='mimalloc_debug')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/cpython/Lib/test/test_cmd_line.py", line 845, in test_pythonmalloc
    self.check_pythonmalloc(env_var, name)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/user/cpython/Lib/test/test_cmd_line.py", line 811, in check_pythonmalloc
    self.assertEqual(proc.stdout.rstrip(), name)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'mimalloc: warning: unable to directly request hin[125 chars]ebug' != 'mimalloc_debug'
- mimalloc: warning: unable to directly request hinted aligned OS memory (error: 2 (0x2), size: 0x40000000 bytes, alignment: 0x2000000, hint address: 0x20000000000)
  mimalloc_debug


----------------------------------------------------------------------
Ran 56 tests in 26.843s

FAILED (failures=2, skipped=2)
test test_cmd_line failed
test_cmd_line failed (2 failures)

== Tests result: FAILURE ==

1 test failed:
    test_cmd_line

Total duration: 27.3 sec
Total tests: run=56 failures=2 skipped=2
Total test files: run=1/1 failed=1
Result: FAILURE
```

Environment:
```
user@starfive:~/cpython$ uname -a
Linux starfive 5.15.0-starfive #1 SMP Fri Nov 24 07:22:28 UTC 2023 riscv64 GNU/Linux
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

**Comment by furkanonder** [comment]
The issue seems to be solved with this [PR](https://github.com/python/cpython/pull/113372).
