### ISSUE TITLE
test_variable_tzname fails in 3.11.7 and 3.12.1 due to timezone change

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#113027]
Commit 46407fe79ca78051cbf6c80e8b8e70a228f9fa50 seems to not be generic enough because running the test in a system where tests where passing before now fails:

```

 ======================================================================
FAIL: test_variable_tzname (test.test_email.test_utils.LocaltimeTests.test_variable_tzname)
] ----------------------------------------------------------------------
 Traceback (most recent call last):
 File "python3.12/test/support/__init__.py", line 890, in inner
 return func(*args, **kwds)
File "python3.12/test/test_email/test_utils.py", line 152, in test_variable_tzname
self.assertEqual(t1.tzname(), 'MSK')
AssertionError: 'Europe' != 'MSK'
 - Europe
+ MSK
----------------------------------------------------------------------
```

### Linked PRs
* gh-113821
* gh-113831
* gh-113832
* gh-113835
* gh-126438
* gh-126477

**Comment by pablogsal** [comment]
@jspricke @serhiy-storchaka

**Comment by jspricke** [comment]
I can't reproduce that problem on Debian unstable and the CI seems to be fine as well. Can you share some information on the system that has the bug or maybe even some way to reproduce it?

**Comment by pablogsal** [comment]
This is an RHEL 7 system with a custom tzdata package. It seems that using "Europe/Kyiv" in this system defaults to Europe and not to MSK. I can try to investigate a bit more but seems is just a matter of what the tzdata contains.

This means that there may be more systems where this test will break while it was working previously.

**Comment by jspricke** [comment]
what exactly do you mean by 'custom tzdata package'? Is there some way to reproduce the test result?

**Comment by pablogsal** [comment]
> what exactly do you mean by 'custom tzdata package'?

I mean that is a custom timezone database maintained independently and therefore is not the one provided by Debian or any other public distribution.

**Comment by pablogsal** [comment]
> Is there some way to reproduce the test result?

So far I have not able to do it outside this environment.

**Comment by ronaldoussoren** [comment]
#109692 seems to be related

**Comment by pablogsal** [comment]
Ok, there is something wrong here. The `TZ` environment variable doesn't respect the `zoneinfo` `TZPATH` so this check:

```
    @unittest.skipUnless("Europe/Kyiv" in zoneinfo.available_timezones(),
                          "Can't find a Kyiv timezone database")
```

it's incorrect because that can return True if `TZPATH` points to a db with `Europe/Kyiv` but the test can fail if the timezone is fetched from a different database.

I think we should revert https://github.com/python/cpython/commit/46407fe79ca78051cbf6c80e8b8e70a228f9fa50 or fix the test.

CC: @serhiy-storchaka @jspricke

**Comment by pablogsal** [comment]
This is because `datetime.datetime.astimezone()` it's consulting the system tz database.

**Comment by serhiy-storchaka** [comment]
Thank you @pablogsal. I used your investigation result to write #113821. Please test it.

**Comment by encukou** [comment]
This now breaks a buildbot worker on [3.10](https://buildbot.python.org/#/builders/602/builds/1320) & [3.9](https://buildbot.python.org/#/builders/557/builds/652) as well. I'll ask Miss Islington for backports.

**Comment by hugovk** [comment]
Merged and backported, I think we can close this now. Please re-open if still needed.
