### ISSUE TITLE
Ctrl-C Does Not Do Anything While A Subinterpreter Is Running in the Main Thread

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#113130]
# Bug report

```
$ cat > /tmp/bug-interp-not-interrupted.py << EOF
import threading
import time
from test.support import interpreters

done = False

# A subthread running the main interpreter does not get interrupted.
def task():
    while not done:
        time.sleep(0.1)
t = threading.Thread(target=task)
t.start()

interp = interpreters.create()

start = time.time()
try:
    interp.exec_sync("""if True:
        import time
        print('Hit Ctrl-C now!')
        for i in range(1, 6):
            time.sleep(1)
            print(i)
    """)
    # Ctrl-C isn't handled until the subinterpreter finishes.
finally:
    done = True

EOF
$ ./python /tmp/bug-interp-not-interrupted.py
1
^C^C2
3
4
^C5
Traceback (most recent call last):
  File "/tmp/bug-interp-not-interruptedpy", line 17, in <module>
    interp.exec_sync("""if True:
    ...
  File "./cpython/Lib/test/support/interpreters/__init__.py", line 178, in exec_sync
    excinfo = _interpreters.exec(self._id, code)
              ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

This sort of makes sense since signals are handled by the main thread of the main interpreter, and only via the eval breaker (triggered exclusively in the eval loop).  Thus if a subinterpreter is running in the main thread, signals (including from Ctrl-C) won't be handled until the next time the main interpreter is running in the main thread.

Possible solutions:

* handle signals in a dedicated thread, separate from the main thread (guaranteed to only run the main interpreter)
* handle signals in whichever interpreter happens to be running in the main thread

**Comment by 813gan** [comment]
Even if making sub-interpreters fully compatible with signals is impossible, would it be doable to make only KeyboardInterrupt work?
