### ISSUE TITLE
Adding length or length hint to IP networks in the ipaddress module

### ISSUE THREAD

**Issue by bartbroere** [python/cpython#113251]
# Feature or enhancement

### Proposal:

Some time ago I submitted a proposal to add length hints to the `itertools` module. These did not get merged for several valid reasons: #101790 

However, since `ipaddress` is a pure Python module, I think adding length (hints) is less hard to get right here.

Therefore I would like to propose adding `__len__` (or `__length_hint__`) to `IPv4Network` and `IPv6Network`. This can be useful for progress reporting (for example when scanning a range of IP addresses).

```python
from operator import length_hint
from ipaddress import IPv4Network

print(len(IPv4Network('10.10.10.0/24')))
# 256
assert len(IPv4Network('10.10.10.0/24')) == len(list(IPv4Network('10.10.10.0/24')))

# or

print(length_hint(IPv4Network('10.10.10.0/24')))
# 256
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by bartbroere** [comment]
Update: Adding this works fine for `IPv4Network`s, but a large `IPv6Network` will result in issues with integer sizes:

```
Traceback (most recent call last):
  File "cpython/Lib/ipaddress.py", line 2350, in <module>
    print(length_hint(IPv6Network('2607:fb10:2018::/45')))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C ssize_t
```

```
Traceback (most recent call last):
  File "cpython/Lib/ipaddress.py", line 2350, in <module>
    print(len(IPv6Network('2607:fb10:2018::/45')))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: cannot fit 'int' into an index-sized integer
```
