### ISSUE TITLE
GUI popup in test_builtins test_envar_unimportable

### ISSUE THREAD

**Issue by ronaldoussoren** [python/cpython#113366]
# Bug report

### Bug description:

When running "python3.12 -m test test_builtins" with a framework install of Python on macOS (installed using python.org installer) I get a file-open dialog followed by this dialog:

<img width="278" alt="image" src="https://github.com/python/cpython/assets/713966/95081648-8253-4f20-9fa3-78a29d365617">

My system language is English. This happens twice. 

There's also a test failure with this test module:

```
======================================================================
ERROR: test_envar_unimportable (test.test_builtin.TestBreakpoint.test_envar_unimportable) (envar='.foo.bar')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/test/test_builtin.py", line 2152, in test_envar_unimportable
    breakpoint()
ValueError: Empty module name

```

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

macOS

**Comment by ronaldoussoren** [comment]
This can easily be reproduced as follows:

```sh
env PYTHONBREAKPOINT=.foo.bar python3.12 -c 'breakpoint()'
```

This results in the same open dialog and message dialog, and also happens with 3.13 and 3.11.

In all of them I get a `ValueError` at the end:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: Empty module name
```

**Comment by ronaldoussoren** [comment]
Sigh....

And this turns out to be a problem on my machine, I had a throwaway script named "foo.py" in the directory where I ran the tests, and that script uses Tkinter...
