### ISSUE TITLE
Importing unittest.mock fails when CPython is built without docstrings

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#113407]
```
$ ./python -c 'import unittest.mock'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import unittest.mock
  File "/home/serhiy/py/cpython/Lib/unittest/mock.py", line 2233, in <module>
    _CODE_SIG = inspect.signature(partial(CodeType.__init__, None))
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serhiy/py/cpython/Lib/inspect.py", line 3378, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                   globals=globals, locals=locals, eval_str=eval_str)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serhiy/py/cpython/Lib/inspect.py", line 3108, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
                                    follow_wrapper_chains=follow_wrapped,
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                    globals=globals, locals=locals, eval_str=eval_str)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serhiy/py/cpython/Lib/inspect.py", line 2603, in _signature_from_callable
    wrapped_sig = _get_signature_of(obj.func)
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/serhiy/py/cpython/Lib/inspect.py", line 2599, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
                                   skip_bound_arg=skip_bound_arg)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serhiy/py/cpython/Lib/inspect.py", line 2398, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <slot wrapper '__init__' of 'object' objects>
```

### Linked PRs
* gh-113408
* gh-113454

**Comment by serhiy-storchaka** [comment]
This causes failing 109 of 469 tests.

**Comment by serhiy-storchaka** [comment]
It perhaps was caused by c5726b727e26b81a267933654cf26b760a90d9aa (gh-83076). @carljm

**Comment by carljm** [comment]
Thanks for this fix, @serhiy-storchaka !
