### ISSUE TITLE
pip install turtle - wont work (python 3.12, 3.11, 3.10, etc..

### ISSUE THREAD

**Issue by andr3wPex** [python/cpython#113512]
# Bug report

### Bug description:

```python
➜  ~ pip install turtle
Collecting turtle
  Using cached turtle-0.0.2.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Users/user/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/user/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/user/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/5c/sqxrdmr96g5ckd3vsdy9008c0000gn/T/pip-build-env-nzxa7v2f/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/5c/sqxrdmr96g5ckd3vsdy9008c0000gn/T/pip-build-env-nzxa7v2f/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/5c/sqxrdmr96g5ckd3vsdy9008c0000gn/T/pip-build-env-nzxa7v2f/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/5c/sqxrdmr96g5ckd3vsdy9008c0000gn/T/pip-build-env-nzxa7v2f/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 40
          except ValueError, ve:
                 ^^^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### CPython versions tested on:

3.9, 3.10, 3.11, 3.12

### Operating systems tested on:

macOS

**Comment by ronaldoussoren** [comment]
You don't have to `pip install turtle` if you're trying to use [the 'turtle' library from our standard library](https://docs.python.org/3/library/turtle.html>), it should just work out of the box.

On Linux systems you may have to make sure that Tkinter support is installed (for example using "yum install python3-tkinter" on Fedora).

**Comment by andr3wpex** [comment]
> You don't have to `pip install turtle` if you're trying to use [the 'turtle' library from our standard library](https://docs.python.org/3/library/turtle.html%3E), it should just work out of the box.
> 
> On Linux systems you may have to make sure that Tkinter support is installed (for example using "yum install python3-tkinter" on Fedora).

Thank you [ronaldoussoren](https://github.com/ronaldoussoren)
It turned out that pyenv for some reason does not include tkinter which causes all kinds of mess one of which resulted me tryong to pip install turtle. You gave me an idea and I fixed the brew pyenv python installation and it works now.
in case anyone has the same issue on a mac with brew, the steps are:
1 pyenv uninstall xyz version of python
2 brew install openssl readline sqlite3 xz zlib
3 pyenv install xyz version of python

Thanks
