### ISSUE TITLE
tarfile: _Stream does not work correctly with a pipe

### ISSUE THREAD

**Issue by perillo** [python/cpython#113895]
# Bug report

### Bug description:

The documentation of `tarfile._Stream` says that "A stream-like object could be for example: sys.stdin, sys.stdout, a socket, a tape device etc.", but when using a pipe it raises `tarfile.StreamError: seeking backwards is not allowed` when the write end of the pipe is closed.

Not sure if this is a bug in the `tarfile` implementation or in my code.
The size of the tar file I used is 40M.

```python
#!/usr/bin/env python

import os
import os.path
from pathlib import Path
import sys
import tarfile
from threading import Thread


BUF_SIZE = 8 * 1024


def tar_strip_components(file, n=0):
    for info in file.getmembers():
        components = Path(info.path).parts
        info.path = Path(*components[1:])

        yield info


def tar_unpack_thread(path, size, wr):
    total_size = size
    size = 0
    with open(path, "rb") as f:
        buf = bytearray(BUF_SIZE)
        while True:
            rate = (size / total_size) * 100
            sys.stderr.write(f"{rate:.0f}%\r")
            n = f.readinto(buf)
            if n == 0:
                break

            size += n
            data = buf[:n]
            wr.write(data)

    sys.stderr.write("done\n")
    wr.close()


def tar_unpack(dest, path, size):
    rd, wr = os.pipe()
    rd = os.fdopen(rd, "rb")
    wr = os.fdopen(wr, "wb")
    t = Thread(target=tar_unpack_thread, args=(path, size, wr))
    t.start()

    # TODO: stream is not closed in case TarFile() raises an exception, but we
    # don't care.
    stream = tarfile._Stream(path, "r", "xz", rd, BUF_SIZE)
    with tarfile.TarFile(path, "r", stream) as file:
        members = tar_strip_components(file, 1)
        file.extractall(dest, members)

    rd.close()
    t.join()


def main():
    path = sys.argv[1]
    size = os.stat(path).st_size
    tar_unpack(".", path, size)


if __name__ == "__main__":
    main()
```

```console
$ ./test.py archive.tar.xz
done
Traceback (most recent call last):
  File "/home/manlio/src/python/pkg/mperillo/zig-installer/test/./test.py", line 67, in <module>
    main()
  File "/home/manlio/src/python/pkg/mperillo/zig-installer/test/./test.py", line 63, in main
    tar_unpack(".", path, size)
  File "/home/manlio/src/python/pkg/mperillo/zig-installer/test/./test.py", line 54, in tar_unpack
    file.extractall(dest, members)
  File "/usr/lib/python3.11/tarfile.py", line 2264, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.11/tarfile.py", line 2327, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.11/tarfile.py", line 2410, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.11/tarfile.py", line 2453, in makefile
    source.seek(tarinfo.offset_data)
  File "/usr/lib/python3.11/tarfile.py", line 520, in seek
    raise StreamError("seeking backwards is not allowed")
tarfile.StreamError: seeking backwards is not allowed
```

If I replace the use of `tarfile.TarFile()` with
```python
while True:
    buf = stream.read(BUF_SIZE)
    if buf == b"":
        sys.stderr.write("ok\n")
        return
```

the code works correctly.

Thanks.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by perillo** [comment]
The original example used an internal API.

Here is a different implementation using the public API.
In the `tar_unpack` function, replaced
```python
stream = tarfile._Stream(path, "r", "xz", rd, BUF_SIZE)
with tarfile.TarFile(path, "r", stream) as file:
```
with
```python 
with tarfile.open(path, "r:xz", rd) as file:
````

The output is:
```console
Traceback (most recent call last):
  File "/home/manlio/src/python/pkg/mperillo/zig-installer/test/test-public-api.py", line 64, in <module>
    main()
  File "/home/manlio/src/python/pkg/mperillo/zig-installer/test/test-public-api.py", line 60, in main
    tar_unpack(".", path, size)
  File "/home/manlio/src/python/pkg/mperillo/zig-installer/test/test-public-api.py", line 51, in tar_unpack
    file.extractall(dest, members)
  File "/usr/lib/python3.11/tarfile.py", line 2255, in extractall
    for member in members:
  File "/home/manlio/src/python/pkg/mperillo/zig-installer/test/test-public-api.py", line 15, in tar_strip_components
    for info in file.getmembers():
                ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tarfile.py", line 1994, in getmembers
    self._load()        # all members, we first have to
    ^^^^^^^^^^^^
  File "/usr/lib/python3.11/tarfile.py", line 2691, in _load
    tarinfo = self.next()
              ^^^^^^^^^^^
  File "/usr/lib/python3.11/tarfile.py", line 2596, in next
    self.fileobj.seek(self.offset - 1)
  File "/usr/lib/python3.11/lzma.py", line 260, in seek
    self._check_can_seek()
  File "/usr/lib/python3.11/_compression.py", line 29, in _check_can_seek
    raise io.UnsupportedOperation("The underlying file object "
io.UnsupportedOperation: The underlying file object does not support seeking
^CException ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1590, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

The documentation of `TarFile.open` (from https://docs.python.org/3.11/library/tarfile.html) says "If given, fileobj may be any object that has a read() or write() method (depending on the mode) that works with bytes".

It seems this is incorrect.

**Comment by perillo** [comment]
`LZMAFile.seek` documentation says "Note that seeking is emulated, so depending on the  parameters, this operation may be extremely slow."

However the `seek` method simply raise an exception, so that comment seems to be really wrong/confusing.

**Comment by TomiBelan** [comment]
It is a bug in your code and not in `tarfile`. Change your code like this:

```python
# Replace the tar_strip_components() definition with this:
def tar_strip_components(info, n=0):
    components = Path(info.path).parts
    info.path = Path(*components[1:])

...

# Replace the central part of tar_unpack() with this:
    ...
    with tarfile.open(path, "r|*", rd) as file:
        for info in file:
            tar_strip_components(info, 1)
            file.extract(info, dest)
    ...
```

The problem was that you can't call both getmembers() and extractall() if it's a stream/pipe. They both attempt to read the whole archive from beginning to end. Instead you must loop over the infos yourself and handle each info immediately in the loop (and extract it if needed).

But I definitely agree it should be better documented which methods are safe to use with streams.

I think this bug report can be closed now. (I'm just a random person who found it, not a CPython dev.)

**Comment by perillo** [comment]
@TomiBelan, thanks for the suggestion.  Now the code works correctly.

One issue is a deprecation warning:
```DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  file.extract(info, dest)
```

**Comment by perillo** [comment]
Another issue is that tar filters don't work with `pathlib`:
```python
file.extract(info, dest, filter="data")
```

```console
Traceback (most recent call last):
  File "/tmp/zigtmp/tar.py", line 63, in <module>
    main()
  File "/tmp/zigtmp/tar.py", line 59, in main
    tar_unpack(".", path, size)
  File "/tmp/zigtmp/tar.py", line 51, in tar_unpack
    file.extract(info, dest, filter="data")
  File "/usr/lib/python3.12/tarfile.py", line 2300, in extract
    tarinfo = self._get_extract_tarinfo(member, filter_function, path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tarfile.py", line 2313, in _get_extract_tarinfo
    tarinfo = filter_function(tarinfo, path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tarfile.py", line 828, in data_filter
    new_attrs = _get_filtered_attrs(member, dest_path, True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tarfile.py", line 761, in _get_filtered_attrs
    if name.startswith(('/', os.sep)):
       ^^^^^^^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute 'startswith'
^CException ignored in: <module 'threading' from '/usr/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1622, in _shutdown
    lock.acquire()
```

**Comment by TomiBelan** [comment]
Oops, I tried it with older Python. Try something like `info.path = str(Path(*components[1:]))` to make it a str. I'm not very familiar with filters though.

You might also want to skip extracting infos with a single-component path, because this changes them to ".".

If the problem is solved, you can probably close the issue.

**Comment by perillo** [comment]
@TomiBelan, Thanks for your help, I will close this issue hoping that the documentation will be improved.
