### ISSUE TITLE
``test_asyncgen`` raises a ``RuntimeWarning``

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#113980]
# Bug report

### Bug description:

Trace:
```python
./python.exe -m test -v test_asyncgen
== CPython 3.13.0a2+ (heads/main:e58334e4c9, Jan 12 2024, 08:03:56) [Clang 15.0.0 (clang-1500.1.0.2.5)]
== macOS-14.2.1-arm64-arm-64bit little-endian
== Python build: debug
== cwd: /Users/admin/Projects/cpython/build/test_python_worker_14547æ
== CPU count: 8
== encodings: locale=UTF-8 FS=utf-8
== resources: all test resources are disabled, use -u option to unskip tests

Using random seed: 3065327320
0:00:00 load avg: 2.91 Run 1 test sequentially
0:00:00 load avg: 2.91 [1/1] test_asyncgen
...many lines
test_async_gen_exception_12 (test.test_asyncgen.AsyncGenTest.test_async_gen_exception_12) ... /Users/admin/Projects/cpython/Lib/test/test_asyncgen.py:382: RuntimeWarning: coroutine method 'asend' of 'AsyncGenTest.test_async_gen_exception_12.<locals>.gen' was never awaited
  await anext(me)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-113981
* gh-113984
* gh-113990

**Comment by serhiy-storchaka** [comment]
More resource warnings are emitted when run tests one by one.
```sh
echo test_async_gen_asyncio_shutdown_exception_02 test_asyncgen_nonstarted_hooks_are_cancellable test_async_gen_exception_12 test_async_gen_3_arg_deprecation_warning | xargs -n1 ./python -We -m test -vuall test_asyncgen -m
```
<details>

```
== CPython 3.13.0a2+ (heads/main-dirty:0d8fec79ca, Jan 11 2024, 18:24:54) [GCC 11.4.0]
== Linux-5.15.0-94-generic-x86_64-with-glibc2.35 little-endian
== Python build: debug
== cwd: /home/serhiy/py/cpython/build/test_python_worker_95668æ
== CPU count: 8
== encodings: locale=UTF-8 FS=utf-8
== resources: all

Using random seed: 1374069189
0:00:00 load avg: 0.66 Run 1 test sequentially
0:00:00 load avg: 0.66 [1/1] test_asyncgen
test_async_gen_asyncio_shutdown_exception_02 (test.test_asyncgen.AsyncGenAsyncioTest.test_async_gen_asyncio_shutdown_exception_02) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.021s

OK
Warning -- Unraisable exception
Exception ignored in: <async_generator object AsyncGenAsyncioTest.test_async_gen_asyncio_shutdown_exception_02.<locals>.async_iterate at 0x7f95ebc8f690>
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/support/__init__.py", line 760, in gc_collect
    gc.collect()
RuntimeWarning: coroutine method 'aclose' of 'AsyncGenAsyncioTest.test_async_gen_asyncio_shutdown_exception_02.<locals>.async_iterate' was never awaited
test_asyncgen failed (env changed)

== Tests result: SUCCESS ==

1 test altered the execution environment (env changed):
    test_asyncgen

Total duration: 158 ms
Total tests: run=1 (filtered)
Total test files: run=1/1 (filtered) env_changed=1
Result: SUCCESS
== CPython 3.13.0a2+ (heads/main-dirty:0d8fec79ca, Jan 11 2024, 18:24:54) [GCC 11.4.0]
== Linux-5.15.0-94-generic-x86_64-with-glibc2.35 little-endian
== Python build: debug
== cwd: /home/serhiy/py/cpython/build/test_python_worker_95670æ
== CPU count: 8
== encodings: locale=UTF-8 FS=utf-8
== resources: all

Using random seed: 2396809240
0:00:00 load avg: 0.69 Run 1 test sequentially
0:00:00 load avg: 0.69 [1/1] test_asyncgen
test_asyncgen_nonstarted_hooks_are_cancellable (test.test_asyncgen.AsyncGenAsyncioTest.test_asyncgen_nonstarted_hooks_are_cancellable) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
Warning -- Unraisable exception
Exception ignored in: <async_generator object AsyncGenAsyncioTest.test_asyncgen_nonstarted_hooks_are_cancellable.<locals>.async_iterate at 0x7f1f15eb0940>
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/support/__init__.py", line 760, in gc_collect
    gc.collect()
RuntimeWarning: coroutine method 'aclose' of 'AsyncGenAsyncioTest.test_asyncgen_nonstarted_hooks_are_cancellable.<locals>.async_iterate' was never awaited
test_asyncgen failed (env changed)

== Tests result: SUCCESS ==

1 test altered the execution environment (env changed):
    test_asyncgen

Total duration: 115 ms
Total tests: run=1 (filtered)
Total test files: run=1/1 (filtered) env_changed=1
Result: SUCCESS
== CPython 3.13.0a2+ (heads/main-dirty:0d8fec79ca, Jan 11 2024, 18:24:54) [GCC 11.4.0]
== Linux-5.15.0-94-generic-x86_64-with-glibc2.35 little-endian
== Python build: debug
== cwd: /home/serhiy/py/cpython/build/test_python_worker_95672æ
== CPU count: 8
== encodings: locale=UTF-8 FS=utf-8
== resources: all

Using random seed: 3226685443
0:00:00 load avg: 0.69 Run 1 test sequentially
0:00:00 load avg: 0.69 [1/1] test_asyncgen
test_async_gen_exception_12 (test.test_asyncgen.AsyncGenTest.test_async_gen_exception_12) ... Warning -- Unraisable exception
Exception ignored in: <async_generator object AsyncGenTest.test_async_gen_exception_12.<locals>.gen at 0x7fa163e575b0>
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_asyncgen.py", line 382, in gen
    await anext(me)
RuntimeWarning: coroutine method 'asend' of 'AsyncGenTest.test_async_gen_exception_12.<locals>.gen' was never awaited
ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
test_asyncgen failed (env changed)

== Tests result: SUCCESS ==

1 test altered the execution environment (env changed):
    test_asyncgen

Total duration: 117 ms
Total tests: run=1 (filtered)
Total test files: run=1/1 (filtered) env_changed=1
Result: SUCCESS
== CPython 3.13.0a2+ (heads/main-dirty:0d8fec79ca, Jan 11 2024, 18:24:54) [GCC 11.4.0]
== Linux-5.15.0-94-generic-x86_64-with-glibc2.35 little-endian
== Python build: debug
== cwd: /home/serhiy/py/cpython/build/test_python_worker_95674æ
== CPU count: 8
== encodings: locale=UTF-8 FS=utf-8
== resources: all

Using random seed: 4006653288
0:00:00 load avg: 0.69 Run 1 test sequentially
0:00:00 load avg: 0.69 [1/1] test_asyncgen
test_async_gen_3_arg_deprecation_warning (test.test_asyncgen.AsyncGenTest.test_async_gen_3_arg_deprecation_warning) ... Warning -- Unraisable exception
Exception ignored in: <async_generator object AsyncGenTest.test_async_gen_3_arg_deprecation_warning.<locals>.gen at 0x7f19162e4940>
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_asyncgen.py", line 398, in test_async_gen_3_arg_deprecation_warning
    gen().athrow(GeneratorExit, GeneratorExit(), None)
RuntimeWarning: coroutine method 'athrow' of 'AsyncGenTest.test_async_gen_3_arg_deprecation_warning.<locals>.gen' was never awaited
ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
test_asyncgen failed (env changed)

== Tests result: SUCCESS ==

1 test altered the execution environment (env changed):
    test_asyncgen

Total duration: 114 ms
Total tests: run=1 (filtered)
Total test files: run=1/1 (filtered) env_changed=1
Result: SUCCESS
```

</details>
Some of them are only exposed if run with the `-We` option.

**Comment by serhiy-storchaka** [comment]
Not reproducible in 3.12.
