### ISSUE TITLE
import requests bug

### ISSUE THREAD

**Issue by Scrapingar** [python/cpython#113983]
# Bug report

### Bug description:

```python
import requests

def make_requests(url):
    import requests
    
    
    try:
        resp = requests.get(url, allow_redirects=True, timeout=10, verify=False)
    except:
        print('Error')
        
if __name__ == '__main__':
    
    make_requests('google.com')
    
    pass
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by WolframAlph** [comment]
Hi, please provide bug description, full source code and traceback

**Comment by Scrapingar** [comment]
Run the code provided it will make un error message

**Comment by Eclips4** [comment]
> Run the code provided it will make un error message

This repository is intended as CPython bug tracker. Is there any bug which we should fix?

**Comment by WolframAlph** [comment]
We cannot help you unless you provide full traceback.

**Comment by romeroyonatan** [comment]
Hi, I tried to run the code, the issue is related with the URL, you have to specify the protocol, for example `make_requests('https://google.com')`

This is not a bug related with cpython.

```
Traceback (most recent call last):
  File "/tmp/a.py", line 15, in <module>
    make_requests('google.com')
  File "/tmp/a.py", line 8, in make_requests
    resp = requests.get(url, allow_redirects=True, timeout=10, verify=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'google.com': No scheme supplied. Perhaps you meant https://google.com?
```

PD: I had to add a `raise` because the exception was hidden by the `except:` block

**Comment by ronaldoussoren** [comment]
Please use the python discussion board at https://discuss.python.org/c/users/7 for questions about using Python.
