### ISSUE TITLE
Python 3.11, MacOS source code build, RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)

### ISSUE THREAD

**Issue by MacDaddy1660B** [python/cpython#113926]
# Bug report

### Bug description:

I'm building Python 3.11.7 from source. I don't see much out there about how to do this on MacOS platforms.

Configure options (```config.log``` attached):

```
./configure --prefix=$PWD --disable-universalsdk TCLTK_CFLAGS='-I/Library/Frameworks/Tcl.framework/Headers/ -I/Library/Frameworks/Tk.framework/Headers/' TCLTK_LIBS='-L/Library/Frameworks/Tcl.framework/ -lTcl -L/Library/Frameworks/Tk.framework/ -lTk' --enable-optimizations --enable-framework
```

Tcl and Tk v.8.6.13 have been built from source and are installed in ```/Library/Frameworks/Tcl.framework/ ``` and ```/Library/Frameworks/Tk.framework/ ```, respectively. They're tested and seem to be behaving normally. They have no references to the Apple-provided TclTk libs

```
gmac@gmacs-iMac-Pro Python-3.11.7 % ls -l /Library/Frameworks/Tcl.framework 
total 0
lrwxr-xr-x  1 root  wheel   24 Jan  9 15:31 Headers -> Versions/Current/Headers
lrwxr-xr-x  1 root  wheel   31 Jan  9 15:31 PrivateHeaders -> Versions/Current/PrivateHeaders
lrwxr-xr-x  1 root  wheel   26 Jan  9 15:31 Resources -> Versions/Current/Resources
lrwxr-xr-x  1 root  wheel   20 Jan  9 15:31 Tcl -> Versions/Current/Tcl
drwxr-xr-x  4 root  wheel  128 Jan  9 15:31 Versions
lrwxr-xr-x  1 root  wheel   28 Jan  9 15:31 libtclstub8.6.a -> Versions/8.6/libtclstub8.6.a
lrwxr-xr-x  1 root  wheel   29 Jan  9 15:31 tclConfig.sh -> Versions/Current/tclConfig.sh
gmac@gmacs-iMac-Pro Python-3.11.7 % ls -l /Library/Frameworks/Tk.framework
total 0
lrwxr-xr-x  1 root  wheel   24 Jan 10 10:45 Headers -> Versions/Current/Headers
lrwxr-xr-x  1 root  wheel   31 Jan 10 10:45 PrivateHeaders -> Versions/Current/PrivateHeaders
lrwxr-xr-x  1 root  wheel   26 Jan 10 10:45 Resources -> Versions/Current/Resources
lrwxr-xr-x  1 root  wheel   19 Jan 10 10:45 Tk -> Versions/Current/Tk
drwxr-xr-x  4 root  wheel  128 Jan 10 10:45 Versions
lrwxr-xr-x  1 root  wheel   27 Jan 10 10:45 libtkstub8.6.a -> Versions/8.6/libtkstub8.6.a
lrwxr-xr-x  1 root  wheel   28 Jan 10 10:45 tkConfig.sh -> Versions/Current/tkConfig.sh
```

Apple-supplied TclTk v8.5 are installed in ```/System/Library/Frameworks/<Tcl | Tk>.framework/```, which I do not wish to use.

When I run the ```tkinter``` test I get the following.

```
gmac@gmacs-iMac-Pro Python-3.11.7 % /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m tkinter
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__main__.py", line 7, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 4618, in _test
    root = Tk()
           ^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 2328, in __init__
    self._loadtk()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 2344, in _loadtk
    raise RuntimeError("tk.h version (%s) doesn't match libtk.a version (%s)"
RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)
```

And my Python build still seems to be linking to the Apple-provided TclTk v8.5 libs, as evidenced by

```
gmac@gmacs-iMac-Pro Python-3.11.7 % otool -L /Library/Frameworks/Python.framework/Versions/3.11//lib/python3.11/lib-dynload/_tkinter.cpython-311-darwin.so
/Library/Frameworks/Python.framework/Versions/3.11//lib/python3.11/lib-dynload/_tkinter.cpython-311-darwin.so:
	/System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl (compatibility version 8.5.0, current version 8.5.9)
	/System/Library/Frameworks/Tk.framework/Versions/8.5/Tk (compatibility version 8.5.0, current version 8.5.9)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)
```

Here's the ```_tkinter``` build step

```
building '_tkinter' extension
gcc -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Frameworks/Tcl.framework/Headers -I/Library/Frameworks/Tk.framework/Headers -fno-semantic-interposition -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden -fprofile-instr-generate -I./Include/internal -DWITH_APPINIT=1 -I/Library/Frameworks/Tcl.framework/Headers/ -I/Library/Frameworks/Tk.framework/Headers/ -I./Include -I. -I/Library/Frameworks/Tcl.framework/Headers -I/Library/Frameworks/Tk.framework/Headers -I/usr/local/include -I/Users/gmac/src/Python-3.11.7/Include -I/Users/gmac/src/Python-3.11.7 -c /Users/gmac/src/Python-3.11.7/Modules/_tkinter.c -o build/temp.macosx-13.5-x86_64-3.11/Users/gmac/src/Python-3.11.7/Modules/_tkinter.o -Wno-strict-prototypes
gcc -bundle -undefined dynamic_lookup -L/Library/Frameworks/Tcl.framework -L/Library/Frameworks/Tk.framework -fno-semantic-interposition -fprofile-instr-generate -L/Library/Frameworks/Tcl.framework -L/Library/Frameworks/Tk.framework -I/Library/Frameworks/Tcl.framework/Headers -I/Library/Frameworks/Tk.framework/Headers -I/Library/Frameworks/Tcl.framework/Headers -I/Library/Frameworks/Tk.framework/Headers build/temp.macosx-13.5-x86_64-3.11/Users/gmac/src/Python-3.11.7/Modules/_multiprocessing/posixshmem.o -L/Library/Frameworks/Tcl.framework -L/Library/Frameworks/Tk.framework -L/usr/local/lib -o build/lib.macosx-13.5-x86_64-3.11/_posixshmem.cpython-311-darwin.so
gcc -bundle -undefined dynamic_lookup -L/Library/Frameworks/Tcl.framework -L/Library/Frameworks/Tk.framework -fno-semantic-interposition -fprofile-instr-generate -L/Library/Frameworks/Tcl.framework -L/Library/Frameworks/Tk.framework -I/Library/Frameworks/Tcl.framework/Headers -I/Library/Frameworks/Tk.framework/Headers -I/Library/Frameworks/Tcl.framework/Headers -I/Library/Frameworks/Tk.framework/Headers build/temp.macosx-13.5-x86_64-3.11/Users/gmac/src/Python-3.11.7/Modules/_multiprocessing/multiprocessing.o build/temp.macosx-13.5-x86_64-3.11/Users/gmac/src/Python-3.11.7/Modules/_multiprocessing/semaphore.o -L/Library/Frameworks/Tcl.framework -L/Library/Frameworks/Tk.framework -L/usr/local/lib -o build/lib.macosx-13.5-x86_64-3.11/_multiprocessing.cpython-311-darwin.so
...
gcc -bundle -undefined dynamic_lookup -L/Library/Frameworks/Tcl.framework -L/Library/Frameworks/Tk.framework -fno-semantic-interposition -L/Library/Frameworks/Tcl.framework -L/Library/Frameworks/Tk.framework -I/Library/Frameworks/Tcl.framework/Headers -I/Library/Frameworks/Tk.framework/Headers -I/Library/Frameworks/Tcl.framework/Headers -I/Library/Frameworks/Tk.framework/Headers build/temp.macosx-13.5-x86_64-3.11/Users/gmac/src/Python-3.11.7/Modules/_tkinter.o build/temp.macosx-13.5-x86_64-3.11/Users/gmac/src/Python-3.11.7/Modules/tkappinit.o -L/Library/Frameworks/Tcl.framework/ -L/Library/Frameworks/Tk.framework/ -L/Library/Frameworks/Tcl.framework -L/Library/Frameworks/Tk.framework -L/usr/local/lib -lTcl -lTk -o build/lib.macosx-13.5-x86_64-3.11/_tkinter.cpython-311-darwin.so
```

[config.log](https://github.com/python/cpython/files/13892064/config.log)

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by MacDaddy1660B** [comment]
BTW, using the Mac Developer Command line tools for the build ```xcode-select version 2397```.

**Comment by erlend-aasland** [comment]
> I'm building Python 3.11.7 from source. I don't see much out there about how to do this on MacOS platforms.

Instructions for installing dependencies for and building CPython 3.11 on macOS are documented in the devguide:
- https://devguide.python.org/getting-started/setup-building/#install-dependencies

If that guide is not complete, we should fix the devguide (and thus transfer this issue to the devguide repo).

**Comment by ronaldoussoren** [comment]
Looking at the configure line the problem is probably here:

```
... TCLTK_LIBS='-L/Library/Frameworks/Tcl.framework/ -lTcl -L/Library/Frameworks/Tk.framework/ -lTk'
```

This tries to link to the libraries in ``/Library/Frameworks/Tcl.framework`` and ``.../Tk.framework`` but that doesn't work because ``-lTcl`` and ``-lTk`` looks for ``libTcl.{dylib,a}`` and "libTk.{dylib,a}`` which aren't in the referenced framework directories.  Therefore the linker find ``/usr/lib/libtcl.dylib`` an ``/usr/lib/libtk.dylib`` from the macOS SDK instead.

Two ways to link to the library:

1. Check if there's a libtcl and libtk inside the frameworks, and add ``-L`` flags pointing to the directories containing those;
2. It should be possible to link directory to the framework using: ``TCLTK_LIBS='/Library/Frameworks/Tcl.framework/Tcl /Library/Frameworks/Tk.framework/Tk'``. That's fairly unclean though, and probably only works then `$(TCLTK_LIBS)` is the last bit of the command-line that links the tkinter extension module.

**Comment by ronaldoussoren** [comment]
I've checked my previous message.

Given the following program:

```c
#include <stdio.h>
#include "Python.h"

int main(void)
{
    printf("%p\n", Py_InitializeEx);
}
```

```sh
% cc -o repro repro.c -I /Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -L /Library/Frameworks/Python.framework/Versions/3.12 -lPython               (main)cpython
ld: library 'Python' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)

% cc -o repro repro.c -I /Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 /Library/Frameworks/Python.framework/Versions/3.12/Python

% otool -vL repro                                                                                                                                                           (main)cpython
repro:
	/Library/Frameworks/Python.framework/Versions/3.12/Python (compatibility version 3.12.0, current version 3.12.0)
	time stamp 2 Thu Jan  1 01:00:02 1970
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)
	time stamp 2 Thu Jan  1 01:00:02 1970

```

The first command failed because Apple doesn't ship ``libpython.dylib`` in ``/usr/lib``. The corresponding Tkinter build did work with unexpected results because Apple (at this time) still ships ``libtk.dylib`` in ``/usr/lib``

I propose closing this issue.

**Comment by MacDaddy1660B** [comment]
Thank you for the help!

I set the environment variable ```LDFLAGS=’-F/Library/Frameworks’``` which changes the search path for the linker, and that got around the problem.

Yes, I think we can close this. Thank you!
