### ISSUE TITLE
Python/flowgraph.c:497: _Bool no_redundant_jumps(cfg_builder *): Assertion `0' failed.

### ISSUE THREAD

**Issue by alex** [python/cpython#114083]
# Bug report

### Bug description:

Another crash in the compiler found by the fuzzer:

```
~/p/cpython ❯❯❯ ./python.exe -c 'compile("if 9<9<9and 9or 9or 9:9", "", "exec")'
:1: SyntaxWarning: invalid decimal literal
:1: SyntaxWarning: invalid decimal literal
:1: SyntaxWarning: invalid decimal literal
Assertion failed: (0), function no_redundant_jumps, file flowgraph.c, line 497.
fish: Job 1, './python.exe -c 'compile("if 9<…' terminated by signal SIGABRT (Abort)
```

cc: @iritkatriel 

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-114408

**Comment by alex** [comment]
Full stack for reference:

```

fuzz_pycompile: Python/flowgraph.c:497: _Bool no_redundant_jumps(cfg_builder *): Assertion `0' failed.
--
  | ==13546== ERROR: libFuzzer: deadly signal
  | #0 0x4f2869 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/msan/msan.cpp:735:3
  | #1 0x472388 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
  | #2 0x457063 in fuzzer::Fuzzer::CrashCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:233:3
  | #3 0x53fc48 in SignalAction(int, void*, void*) /src/llvm-project/compiler-rt/lib/msan/msan_interceptors.cpp:998:3
  | #4 0x7d9f29a0641f in libpthread.so.0
  | #5 0x7d9f2981c00a in __libc_signal_restore_set /build/glibc-SzIz7B/glibc-2.31/sysdeps/unix/sysv/linux/internal-signals.h:86:3
  | #6 0x7d9f2981c00a in raise /build/glibc-SzIz7B/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:48:3
  | #7 0x7d9f297fb858 in abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79:7
  | #8 0x7d9f297fb728 in __assert_fail_base /build/glibc-SzIz7B/glibc-2.31/assert/assert.c:92:3
  | #9 0x7d9f2980cfd5 in __assert_fail /build/glibc-SzIz7B/glibc-2.31/assert/assert.c:101:3
  | #10 0xc6b2e8 in no_redundant_jumps cpython3/Python/flowgraph.c:497:25
  | #11 0xc69fb0 in _PyCfg_OptimizedCfgToInstructionSequence cpython3/Python/flowgraph.c:2704:5
  | #12 0xb12816 in optimize_and_assemble_code_unit cpython3/Python/compile.c:7581:9
  | #13 0xb12816 in optimize_and_assemble cpython3/Python/compile.c:7616:12
  | #14 0xb03706 in compiler_mod cpython3/Python/compile.c:1779:24
  | #15 0xb03706 in _PyAST_Compile cpython3/Python/compile.c:555:24
  | #16 0xe44da9 in Py_CompileStringObject cpython3/Python/pythonrun.c:1452:10
  | #17 0xe45144 in Py_CompileStringExFlags cpython3/Python/pythonrun.c:1465:10
  | #18 0x54f518 in fuzz_pycompile cpython3/Modules/_xxtestfuzz/fuzzer.c:550:24
  | #19 0x54f518 in _run_fuzz cpython3/Modules/_xxtestfuzz/fuzzer.c:563:14
  | #20 0x54f518 in LLVMFuzzerTestOneInput cpython3/Modules/_xxtestfuzz/fuzzer.c:704:11
  | #21 0x458603 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
  | #22 0x443d62 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
  | #23 0x44960c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
  | #24 0x472b42 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
  | #25 0x7d9f297fd082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/libc-start.c:308:16
  | #26 0x439f2d in _start


<br class="Apple-interchange-newline">fuzz_pycompile: Python/flowgraph.c:497: _Bool no_redundant_jumps(cfg_builder *): Assertion `0' failed.
==13546== ERROR: libFuzzer: deadly signal
    #0 0x4f2869 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/msan/msan.cpp:735:3
    #1 0x472388 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x457063 in fuzzer::Fuzzer::CrashCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:233:3
    #3 0x53fc48 in SignalAction(int, void*, void*) /src/llvm-project/compiler-rt/lib/msan/msan_interceptors.cpp:998:3
    #4 0x7d9f29a0641f in libpthread.so.0
    #5 0x7d9f2981c00a in __libc_signal_restore_set /build/glibc-SzIz7B/glibc-2.31/sysdeps/unix/sysv/linux/internal-signals.h:86:3
    #6 0x7d9f2981c00a in raise /build/glibc-SzIz7B/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:48:3
    #7 0x7d9f297fb858 in abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79:7
    #8 0x7d9f297fb728 in __assert_fail_base /build/glibc-SzIz7B/glibc-2.31/assert/assert.c:92:3
    #9 0x7d9f2980cfd5 in __assert_fail /build/glibc-SzIz7B/glibc-2.31/assert/assert.c:101:3
    #10 0xc6b2e8 in no_redundant_jumps [cpython3/Python/flowgraph.c:497](https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Python/flowgraph.c#L497):25
    #11 0xc69fb0 in _PyCfg_OptimizedCfgToInstructionSequence [cpython3/Python/flowgraph.c:2704](https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Python/flowgraph.c#L2704):5
    #12 0xb12816 in optimize_and_assemble_code_unit [cpython3/Python/compile.c:7581](https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Python/compile.c#L7581):9
    #13 0xb12816 in optimize_and_assemble [cpython3/Python/compile.c:7616](https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Python/compile.c#L7616):12
    #14 0xb03706 in compiler_mod [cpython3/Python/compile.c:1779](https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Python/compile.c#L1779):24
    #15 0xb03706 in _PyAST_Compile [cpython3/Python/compile.c:555](https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Python/compile.c#L555):24
    #16 0xe44da9 in Py_CompileStringObject [cpython3/Python/pythonrun.c:1452](https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Python/pythonrun.c#L1452):10
    #17 0xe45144 in Py_CompileStringExFlags [cpython3/Python/pythonrun.c:1465](https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Python/pythonrun.c#L1465):10
    #18 0x54f518 in fuzz_pycompile [cpython3/Modules/_xxtestfuzz/fuzzer.c:550](https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Modules/_xxtestfuzz/fuzzer.c#L550):24
    #19 0x54f518 in _run_fuzz [cpython3/Modules/_xxtestfuzz/fuzzer.c:563](https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Modules/_xxtestfuzz/fuzzer.c#L563):14
    #20 0x54f518 in LLVMFuzzerTestOneInput [cpython3/Modules/_xxtestfuzz/fuzzer.c:704](https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Modules/_xxtestfuzz/fuzzer.c#L704):11
    #21 0x458603 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #22 0x443d62 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #23 0x44960c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #24 0x472b42 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #25 0x7d9f297fd082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/libc-start.c:308:16
    #26 0x439f2d in _start
````

**Comment by Eclips4** [comment]
cc @iritkatriel
