### ISSUE TITLE
Tools/build/generate_sbom.py fails in out-of-tree builds

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#114178]
# Bug report

```console
$ pwd
/Users/erlend.aasland/src/python/build-main
$ make regen-all
[...]
python3.13 /Users/erlend.aasland/src/python/main/Tools/build/generate_sbom.py
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/Users/erlend.aasland/src/python/main/Tools/build/generate_sbom.py", line 310, in <module>
    main()
  File "/Users/erlend.aasland/src/python/main/Tools/build/generate_sbom.py", line 270, in main
    paths = filter_gitignored_paths(paths)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erlend.aasland/src/python/main/Tools/build/generate_sbom.py", line 113, in filter_gitignored_paths
    assert git_check_ignore_proc.returncode in (0, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
make: *** [regen-sbom] Error 1
```

### Linked PRs
* gh-114179

**Comment by erlend-aasland** [comment]
Looks like we at least have to run Git in the source directory. I'm not sure this is enough to fix the problem, as I don't know anything about `generate_sbom.py` yet.

```diff
diff --git a/Tools/build/generate_sbom.py b/Tools/build/generate_sbom.py
index 282ee20cc4..317d48fee3 100644
--- a/Tools/build/generate_sbom.py
+++ b/Tools/build/generate_sbom.py
@@ -106,6 +106,7 @@ def filter_gitignored_paths(paths: list[str]) -> list[str]:
     # Non-matching files show up as '::<whitespace><path>'
     git_check_ignore_proc = subprocess.run(
         ["git", "check-ignore", "--verbose", "--non-matching", *paths],
+        cwd=CPYTHON_ROOT_DIR,
         check=False,
         stdout=subprocess.PIPE,
     )
```
