### ISSUE TITLE
PEP 695 type aliases not suitable as replacement for typing.TypeAlias

### ISSUE THREAD

**Issue by mjog** [python/cpython#114159]
# Bug report

### Bug description:

PEP 695 type aliases are the blessed replacement for the now-deprecated `typing.TypeAlias`, but are functionally not suitable as replacement.

A type alias designated as such using the `typing.TypeAlias` annotation could be used in many places that a PEP 695 type aliases cannot, including (at least) as a class's parent class, in calls to `isinstance` and `issubclass`. All of of these have been used in various codebases I maintain.

As such `typing.TypeAlias` should be un-deprecated, or the implementation of PEP 695 type aliases should be updated to work in all cases where a plain type should be.

With `typing.TypeAlias `:

```python
$ poetry run python3
Python 3.12.0 (main, Oct  4 2023, 06:27:34) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import typing
>>> StringAlias: typing.TypeAlias = str
>>> isinstance('test', StringAlias)
True
>>> issubclass(StringAlias, str)
True
>>> class GreaterString(StringAlias): pass
... 
>>> 
```

With PEP 695 type aliases:

```python
$ poetry run python3
Python 3.12.0 (main, Oct  4 2023, 06:27:34) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> type StringAlias = str
>>> isinstance('test', StringAlias)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
>>> issubclass(StringAlias, str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: issubclass() arg 1 must be a class
>>> class GreaterString(StringAlias): pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: typealias() takes exactly 2 positional arguments (3 given)
>>> 
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by mjog** [comment]
The examples above are moderately trivial, but my actual use case is to make extremely long class names (typically generic classes) more manageable.

An actual of example of this being:

```python
type ChassisMountable = _equip.Mountable[ChassisMount,ChassisSectionDescription]

class Engine(ChassisMountable, _equip.FixedMass, _equip.Equipment): ...

[snip: Several dozen other similar classes that also extend ChassisMountable]
```

**Comment by carljm** [comment]
To what extent would this meet your needs?

```
type ChassisMountableT = _equip.Mountable[ChassisMount,ChassisSectionDescription]
ChassisMountable = ChassisMountableT.__value__

class Engine(ChassisMountable, _equip.FixedMass, _equip.Equipment): ...

[snip: Several dozen other similar classes that also extend ChassisMountable]
```

**Comment by mjog** [comment]
The redundancy and resulting extra code and mental overhead of it makes me wonder why bother?

Why not fix it properly by either un-deprecating `typing.TypeAlias` and putting the docs for it back so that people know how it supposed to be used and are assured it won't be removed in some future 3.x version (unlike most deprecated 3.x features), or fix `type` so that it is actually a replacement?

**Comment by JelleZijlstra** [comment]
You can use `StringAlias = str` instead. Type checkers will still understand this as an alias, and you can use it at runtime in whatever way you desire.

**Comment by mjog** [comment]
Do static type checkers handle all the cases that PEP 613's motivation outlines?

How about for the person reading through the code? Or other tools that aren't static type checkers?

**Comment by bionicles** [comment]
my workaround: stop using types, just use exclusively runtime variables. python type system might be ready one day, but that day isn't today

i do think a Deref(Protocol) could solve the issues. right now the behavior is too surprising, gets frustrating, you get excited thinking you can define new classes of generics by type X = G[Thing], and then it doesn't work and you wind up needing to delete a bunch (100s of lines) of python type code. that'll make anyone mad

don't beat up python for this, rust is the same way, type systems are not easy to get right, a lot of subtle edge cases.

that said, I think the "only for annotations" pathway is a dead end, we need types that work at compile and runtime, that's the purpose of types, if they're just annotations and dont have the methods of the class, then it's a downgrade to use type alias type over just passing type at runtime, sadly

**Comment by sveinugu** [comment]
> Do static type checkers handle all the cases that PEP 613's motivation outlines?
> 
> How about for the person reading through the code? Or other tools that aren't static type checkers?

Pinging this issue, as these highly relevant comments have yet not been addressed.

As a long-time Python developer that has spent considerable time the last couple of years to understand the typing system, I suddenly found myself extremely surprised to find that the new `type` syntax for type aliases do not in fact define type aliases in the way that most developers would think of an alias, i.e. an identifier that can be used to replace the object it refers to.

Consider the following recursive type aliases, defining the Python equivalent of JSON types:

```python
from typing import TypeAlias

Json: TypeAlias = 'JsonScalar | JsonList | JsonDict'
JsonScalar: TypeAlias = None | int | float | str | bool
JsonList: TypeAlias = list[Json]
JsonDict: TypeAlias = dict[str, Json]

my_list = JsonList([1, 'a', True])
my_empty_dict = JsonDict()

assert type(my_list) is list
```

AFAIK, there is no non-deprecated 3.12+ alternative syntax that supports both static type checks and the runtime use of these (in my mind) completely reasonable type aliases that worked perfectly fine in 3.10 and 3.11. The `type` syntax completely fails as the resulting objects are not, in fact, type aliases in runtime at all:

```
type Json = 'JsonScalar | JsonList | JsonDict'
type JsonScalar = None | int | float | str | bool
type JsonList = list[Json]
type JsonDict = dict[str, Json]

my_list = JsonList([1, 'a', True])
```

Results in `TypeError: 'typing.TypeAliasType' object is not callable`.

Using the following syntax works, but is so cumbersome that it defeats much of the point of defining type aliases in the first place:

```
my_list = JsonList.__value__([1, 'a', True])
my_empty_dict = JsonDict.__value__()

assert type(my_list) is list
```

Using the `NewType` syntax does not work in the case of `my_empty_dict`:

```
Json = NewType('Json', 'JsonScalar | JsonList | JsonDict')
JsonScalar = NewType('JsonScalar', None | int | float | str | bool)
JsonList = NewType('JsonList', list[Json])
JsonDict = NewType('JsonDict', dict[str, Json])

my_list = JsonList([1, 'a', True])
my_empty_dict = JsonDict()
```

Fails with `TypeError: _typing._idfunc() takes exactly one argument (0 given)`. Also, `mypy` fails with `Argument 2 to NewType(...) must be subclassable (got "JsonScalar | JsonList | JsonDict")  [valid-newtype]` even though the code works in runtime. `pyright` also fails similarly.

Finally, just removing the `TypeAlias` type hints currently fails in `mypy`:
`Variable "typedefs. Json" is not valid as a type [valid-type]`, which was one of the use cases motivating [PEP613](https://peps.python.org/pep-0613/#forward-references) in the first place. And even given that type checkers are updated to work in such cases, then removing `TypeAlias` still makes the code less readable for humans.

With the deprecation of `TypeAlias` without providing a proper replacement, I think Python devs have painted themselves into a corner. As changing the new "type aliases" into actual type aliases in runtime seems to be out of the question (see e.g. https://discuss.python.org/t/run-time-behaviour-of-typealiastype/43774), then the logical conclusion should be, IMHO, to remove the deprecation of `TypeAlias` and rename the new `type` syntax to something else and stop confusing Python developers.
