### ISSUE TITLE
Managed resource finally block unexpectedly executed when managed by an ExitStack

### ISSUE THREAD

**Issue by Wenzel** [python/cpython#114237]
# Bug report

### Bug description:

# Issue

## Summary

A function `foobar.py:managed_resource` decorated by `context_manager`, and handled via an `ExiStack` unexpectedly execute it's `finally` block, even though the `ExitStack` `__exit__()` hasn't been invoked yet, while a second thread will properly execute the finally block upon `__exit()__` handled invocation, after sending a `KeyboardInterrupt`

## Output

```python
INFO:src.foobar.FooBar[Thread: 140165434152704]:Running
INFO:root:[140165425760000] Freeing the resource. We shouldn't be here at this point.
INFO:src.foobar.FooBar[Thread: 140165425760000]:Running
INFO:src.foobar.FooBar[Thread: 140165434152704]:Running
INFO:src.foobar.FooBar[Thread: 140165425760000]:Running
^CTraceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/src/__main__.py", line 50, in <module>
    main()
  File "/src/__main__.py", line 48, in main
    exec.run()
  File "/src/__main__.py", line 37, in run
    time.sleep(9999)
KeyboardInterrupt
INFO:root:[140165434152704] Freeing the resource. We shouldn't be here at this point.
```

# Code
## `main.py`
<details>
  <summary>Expand</summary>

```python
from concurrent.futures import Future, ThreadPoolExecutor
import logging
from threading import Event
from typing import List, Optional, Type
from .foobar import FooBar

JOBS = 2

def wrap_run_cls(foo_cls, shutdown_event: Event, buggy_prop):
    with foo_cls(shutdown_event, buggy_prop) as foo:
        foo.run()



class Executor():
    def __init__(self):
        self._logger = logging.getLogger(f"{self.__module__}.{self.__class__.__name__}")
        self._pool_inj: Optional[ThreadPoolExecutor] = None
        self._inj_fut_list: List[Future] = []
        self._shutdown_event: Optional[Event] = Event()

    def __enter__(self):

        self._pool_obj = ThreadPoolExecutor(max_workers=JOBS)
        self._pool_inj = self._pool_obj.__enter__()

        foo_cls = FooBar
        self._foo_fut_list = [
            self._pool_inj.submit(wrap_run_cls, foo_cls, self._shutdown_event, j)
            for j in range(JOBS)
        ]

        return self

    def run(self):
        import time
        time.sleep(9999)

    def __exit__(
        self, __exc_type: Optional[Type[BaseException]], __exc_value: Optional[BaseException], __traceback
    ) -> Optional[bool]:
        self._shutdown_event.set()
        return None

def main():
    logging.basicConfig(level=logging.DEBUG)
    with Executor() as exec:
        exec.run()

main()
```
</details>

## `foobar.py`

<details>
  <summary>Expand</summary>

```python
from typing import Any, Optional, Type
import logging
from abc import abstractclassmethod
from contextlib import AbstractContextManager
from threading import Event, get_ident
from typing import Dict, Optional
from contextlib import ExitStack, contextmanager

@contextmanager
def managed_resource():
    try:
        yield 42
    finally:
        # BUG ?: we shouldn't enter here if the __exit__ handler hasn't been called !
        logging.info("[%s] Freeing the resource. We shouldn't be here at this point.", get_ident())

class AbstractFooBar(AbstractContextManager):
    @abstractclassmethod
    def __init__(self, shutdown_event: Event, prop: int):
        super().__init__(self)
        self._logger: Optional[logging.Logger] = None
        self._shutdown_event: Event = shutdown_event
        self._ex = ExitStack()

    def __enter__(self) -> Any:
        super().__enter__()
        self._ex.__enter__()
        return self

    def __exit__(self, __exc_type: Optional[Type[BaseException]], __exc_value: Optional[BaseException], __traceback
    ) -> Optional[bool]:
        self._ex.__exit__(__exc_type, __exc_value, __traceback)
        return super().__exit__(__exc_type, __exc_value, __traceback)

    @property
    def logger(self):
        """instantiate the logger on first use, which will be with the concrete class type"""
        if self._logger is None:
            self._logger = logging.getLogger(f"{self.__module__}.{self.__class__.__name__}[Thread: {get_ident()}]")
        return self._logger

class FooBar(AbstractFooBar):

    def __init__(self, shutdown_event, prop: int):
        super().__init__(shutdown_event, prop)

    def __enter__(self) -> Any:
        super().__enter__()
        self._ex.enter_context(managed_resource())
        return self

    def run(self):
        while not self._shutdown_event.is_set():
            self.logger.info("Running")
            import time
            time.sleep(2)
```
</details>

# Repro

[archive.zip](https://github.com/python/cpython/files/13975050/archive.zip)

```
$ docker build -t bug .
$ docker run -ti bug
```

Rerpoducible on latest python `3.13-rc` as provided by the Docker image.

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
Why is `AbstractFooBar.__init__` a class method:

```python
class AbstractFooBar(AbstractContextManager):
    @abstractclassmethod
    def __init__(self, shutdown_event: Event, prop: int):
         ...
```

This results in initialising the *class* not the *instance*, which could explain things.

BTW. Also try to reproduce the issue to the absolute minimum.

**Comment by Wenzel** [comment]
Hi @ronaldoussoren,

Thank you for feedback on this issue.
You are totally right, this `abstractclassmethod` has slipped past my code reviews
I tested the code again with an `abstractmethod`, and it is behaving like I would expect. :100: 

> BTW. Also try to reproduce the issue to the absolute minimum.

You are right here as well, but I thought that the combination of `ThreadPoolExecutor`, `ExitStack` and inheritance was the source of the problem.

I'll close this issue, thanks again !
