### ISSUE TITLE
Thread name not a small integer, ever increasing, creating exception

### ISSUE THREAD

**Issue by aerilox** [python/cpython#114345]
# Bug report

### Bug description:

The subject had originally been covered [here](https://stackoverflow.com/questions/60347082/when-does-python-reset-the-thread-count)
The docu [of](https://docs.python.org/3/library/threading.html) threading.py says
"name is the thread name. By default, a unique name is constructed of the form “Thread-N” where N is a <b>small decimal number</b>, or “Thread-N (target)” where “target” is target.__name__ if the target argument is specified."
N is not a small decimal number, it is ever increasing with every thread that is started. Also Timer threads are affected.

```python
import time
tt=None
i=-1
st=time.time()
def test():
    global tt, i, st
    tt=threading.Timer(0.0, test)
    i+=1
    if i%100000==0:
        oldst=st
        st=time.time()
        print (tt.name, st-oldst )
    tt.start()
```
On a long-running daemon on Windows Server 2019 and Python 3.8 the code throws an exception passing through a number close to 16777216

```pytb
Exception in thread Thread-16711544:
Traceback (most recent call last):
  File "C:\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\python38\lib\threading.py", line 1252, in run
    self.finished.wait(self.interval)
  File "C:\python38\lib\threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "C:\python38\lib\threading.py", line 295, in wait
    waiter = _allocate_lock()
RuntimeError: can't allocate lock
```

The occurence can be solidely reproduced. Actual N varies for each occurence/exception +- a couple 100.
On a Win10/11 + Python 3.11 system the exception at that specific N range could not be observed.
Size of N and exception may not be related. Nevertheless it raises a concern about long-running daemons that may trespas some sort of integer barrier on N that could raise an exception after a very very long time. N should be limited to a small number/reused as written in the doc imo. 

### CPython versions tested on:

3.8

### Operating systems tested on:

Windows

**Comment by ericvsmith** [comment]
Please provide a complete example we can run. `test` is never called in the code you provided.

Also, please try this on a supported version of Python (3.11 or 3.12).

More likely than not, you're running out of resources.

**Comment by aerilox** [comment]
Code with additional line that shows active threads. (Time is there to calculate how long to wait until N=2**24 is reached)

```
import time
tt=None
i=-1
st=time.time()
def test():
    global tt, i, st
    tt=threading.Timer(0.0, test)
    i+=1
    if i%100000==0:
        oldst=st
        st=time.time()
        print(time.asctime(), 'Threads:', threading.active_count(), 'IDs:', threading.get_native_id(),
             threading.get_ident())
        print(threading.enumerate())
        print (tt.name, st-oldst )
    tt.start()
test()
```
Output with N ever increasing, at least doc is not correct, certainly not a small integer. Resources not an issue.
```
C:\test_stuff>thrd_test.py
Sat Jan 20 15:54:19 2024 Threads: 1 IDs: 3784 3784
[<_MainThread(MainThread, started 3784)>]
Thread-1 0.0
Sat Jan 20 15:54:37 2024 Threads: 3 IDs: 8248 8248
[<_MainThread(MainThread, stopped 3784)>, <Timer(Thread-100000, started 8248)>]
Thread-100001 17.394731521606445
Sat Jan 20 15:54:54 2024 Threads: 3 IDs: 5480 5480
[<_MainThread(MainThread, stopped 3784)>, <Timer(Thread-200000, started 5480)>]
Thread-200001 17.359288930892944
Sat Jan 20 15:55:14 2024 Threads: 3 IDs: 10884 10884
[<_MainThread(MainThread, stopped 3784)>, <Timer(Thread-300000, started 10884)>]
Thread-300001 20.31698966026306
Sat Jan 20 15:55:40 2024 Threads: 3 IDs: 4240 4240
[<_MainThread(MainThread, stopped 3784)>, <Timer(Thread-400000, started 4240)>]
Thread-400001 25.442877769470215
...
Sat Jan 20 15:57:45 2024 Threads: 3 IDs: 6964 6964
[<_MainThread(MainThread, stopped 3784)>, <Timer(Thread-900000, started 6964)>]
Thread-900001 26.170940399169922
Sat Jan 20 15:58:11 2024 Threads: 3 IDs: 6708 6708
[<_MainThread(MainThread, stopped 3784)>, <Timer(Thread-1000000, started 6708)>]
Thread-1000001 25.951912879943848
Sat Jan 20 15:58:36 2024 Threads: 3 IDs: 13320 13320
[<_MainThread(MainThread, stopped 3784)>, <Timer(Thread-1100000, started 13320)>]
Thread-1100001 25.01738214492798
Sat Jan 20 15:59:00 2024 Threads: 3 IDs: 5300 5300
[<_MainThread(MainThread, stopped 3784)>, <Timer(Thread-1200000, started 5300)>]
Thread-1200001 23.67398977279663
Sat Jan 20 15:59:22 2024 Threads: 3 IDs: 17144 17144
[<_MainThread(MainThread, stopped 3784)>, <Timer(Thread-1300000, started 17144)>]
Thread-1300001 21.73977255821228
```
We have a daemon running (Win server 2019) that creates and cancels about 2,000,000 timer threads per days. The number of active threads never exceeds 30 though. 26 threads are started at program run. up to 4 threads are short running timers, Resources are stable and not an issue. The exception is thrown every 8 days or so.

`Sat Jan 20 15:10:46 2024 Threads: 30 IDs: 12148 12148
[<_MainThread(MainThread, stopped 10088)>, <Thread(Thread-5, started 12176)>, <Thread(Thread-6, started 10300)>, <Thread(Thread-7, started 11748)>, <Thread(Thread-8, started 8540)>, <Thread(Thread-9, started 12104)>, <Thread(Thread-10, started 3044)>, <Thread(Thread-11, started 5032)>, <Thread(Thread-12, started 8056)>, <Thread(Thread-13, started 6352)>, <Thread(Thread-14, started 9828)>, <Thread(Thread-15, started 6196)>, <Thread(Thread-16, started 3556)>, <Thread(Thread-17, started 8600)>, <Thread(Thread-18, started 5336)>, <Thread(Thread-19, started 5852)>, <Thread(Thread-20, started 724)>, <Thread(Thread-21, started 4772)>, <Thread(Thread-22, started 10228)>, <Thread(Thread-23, started 4436)>, <Thread(Thread-24, started 9424)>, <Thread(Thread-25, started 11528)>, <Thread(Thread-26, started 6036)>, <Thread(Thread-29, started 12276)>, <Thread(Thread-30, started 8448)>, <Thread(Thread-31, started 5668)>, <Timer(Thread-968490, started 12148)>, <Timer(Thread-970350, started 10840)>, <Timer(Thread-970483, started 11888)>, <Timer(Thread-970484, started 7176)>]`

**Comment by ericvsmith** [comment]
I don't think the integer becoming large is your problem. Maybe the documentation could be tweaked, but I personally wouldn't bother.

You're running out of locks, since the error you get is that a lock cannot be allocated. Looking at the code, it looks like it's either running out of memory, or a conditional or mutex can't be initialized.

I suggest you upgrade to a newer python, and maybe tracemalloc could narrow down the problem.

(Also, you're missing "import threading")

**Comment by ericvsmith** [comment]
I can't duplicate this. I'm up to Thread-116100001 on 3.11.4 on Windows 10, or ~7 times as many threads as the OP.

**Comment by aerilox** [comment]
Thx. Agreed, see above

`On a Win10/11 + Python 3.11 system the exception at that specific N range could not be observed.`

This is about Win Server 2019 (not 2012 as originally stated) and Python 3.8
We will upgrade the (remote) server to 3.11 next week and report back here.

**Comment by ericvsmith** [comment]
> On a Win10/11 + Python 3.11 system the exception at that specific N range could not be observed.

Sorry I missed that part. I'll be interested if upgrading from 3.8 changes the problem.

**Comment by ericvsmith** [comment]
I think the nature of the number isn't important (small, large, medium, etc.), but the fact that it's not reused is. Maybe "unique number that is not reused"?  Or does "serial number" convey the same?

**Comment by aerilox** [comment]
I can report that upgrade to Python 3.11 resolved the issue of the crash at Thread-16xyzxyz, We are now at 22xyzxyz and keep it running.
Probably I am too old, but still ever growing numbers do not leave me comfortable, even on 64 bit machines ... ;-)
