### ISSUE TITLE
New test_termios fails on Alpinelinux

### ISSUE THREAD

**Issue by andypost** [python/cpython#114492]
# Bug report

### Bug description:

As reported https://github.com/python/cpython/issues/81002#issuecomment-1904867665 where the test was added

I'm upgrading Python in Alpinelinux to 3.11.7 and testing upgrade to 3.12.1 (both fails the same test)

```
Re-running test_termios in verbose mode (matching: test_tcgetattr)
test_tcgetattr (test.test_termios.TestFunctions.test_tcgetattr) ... FAIL

======================================================================
FAIL: test_tcgetattr (test.test_termios.TestFunctions.test_tcgetattr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/alpine/aports/main/python3/src/Python-3.11.7/Lib/test/test_termios.py", line 42, in test_tcgetattr
    self.assertEqual(termios.tcgetattr(self.stream), attrs)
AssertionError: Lists differ: [1280[227 chars]', b'P', b'\xed', b'\x1a', b'\xf7', b'*', b'z'[18 chars]'(']] != [1280[227 chars]', b'\x01', b'\x00', b'\x00', b'\x00', b' ', b[27 chars]d8']]

First differing element 6:
[b'\x[197 chars]', b'P', b'\xed', b'\x1a', b'\xf7', b'*', b'z'[17 chars]b'(']
[b'\x[197 chars]', b'\x01', b'\x00', b'\x00', b'\x00', b' ', b[26 chars]xd8']

  [1280,
   5,
   191,
   35387,
   15,
   15,
   [b'\x03',
    b'\x1c',
    b'\x7f',
    b'\x15',
    b'\x04',
    b'\x00',
    b'\x01',
    b'\x00',
    b'\x11',
    b'\x13',
    b'\x1a',
    b'\x00',
    b'\x12',
    b'\x0f',
    b'\x17',
    b'\x16',
    b'\x00',
    b'\x00',
    b'\x00',
    b'|',
    b'\xdc',
    b'\xc9',
    b'\xe7',
-   b'P',
-   b'\xed',
-   b'\x1a',
?        -

+   b'\x01',
?       +

+   b'\x00',
+   b'\x00',
+   b'\x00',
+   b' ',
+   b'\xd5',
+   b'$',
    b'\xf7',
+   b'\xd8']]
-   b'*',
-   b'z',
-   b'd',
-   b'\xf7',
-   b'(']]

----------------------------------------------------------------------
Ran 1 test in 0.003s
```

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-114495
* gh-114502
* gh-114503

**Comment by andypost** [comment]
Building 3.12.1 I see following log https://gitlab.alpinelinux.org/alpine/aports/-/jobs/1252337

So disabled both meanwhile
```
Re-running test_tty in verbose mode (matching: test_cfmakeraw, test_setcbreak, test_setraw)
test_cfmakeraw (test.test_tty.TestTty.test_cfmakeraw) ... ok
test_setcbreak (test.test_tty.TestTty.test_setcbreak) ... FAIL
test_setraw (test.test_tty.TestTty.test_setraw) ... FAIL
======================================================================
FAIL: test_setcbreak (test.test_tty.TestTty.test_setcbreak)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/alpine/aports/main/python3/src/Python-3.12.1/Lib/test/test_tty.py", line 74, in test_setcbreak
    self.assertEqual(mode1, mode0)
AssertionError: Lists differ: [1280[194 chars]', b'@', b'3', b'\x11', b'o', b'\xe3', b'\x7f'[54 chars]e3']] != [1280[194 chars]', b'\x10', b'W', b'%', b'o', b'\xe3', b'\x7f'[51 chars]e3']]
First differing element 6:
[b'\x[164 chars]', b'@', b'3', b'\x11', b'o', b'\xe3', b'\x7f'[53 chars]xe3']
[b'\x[164 chars]', b'\x10', b'W', b'%', b'o', b'\xe3', b'\x7f'[50 chars]xe3']
  [1280,
   5,
   191,
   35387,
   15,
   15,
   [b'\x03',
    b'\x1c',
    b'\x7f',
    b'\x15',
    b'\x04',
    b'\x00',
    b'\x01',
    b'\x00',
    b'\x11',
    b'\x13',
    b'\x1a',
    b'\x00',
    b'\x12',
    b'\x0f',
    b'\x17',
    b'\x16',
    b'\x00',
    b'\x00',
    b'\x00',
-   b'@',
-   b'3',
-   b'\x11',
?        ^
+   b'\x10',
?        ^
+   b'W',
+   b'%',
    b'o',
    b'\xe3',
    b'\x7f',
    b'\x00',
    b'\x00',
-   b'\x00',
-   b'\x8f',
-   b'%',
?     ^
+   b'v',
?     ^
+   b']',
+   b'\xb6',
    b'o',
    b'\xe3']]
======================================================================
FAIL: test_setraw (test.test_tty.TestTty.test_setraw)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/alpine/aports/main/python3/src/Python-3.12.1/Lib/test/test_tty.py", line 63, in test_setraw
    self.assertEqual(mode1, mode0)
AssertionError: Lists differ: [1280[194 chars]', b'@', b'3', b'\x11', b'o', b'\xe3', b'\x7f'[54 chars]e3']] != [1280[194 chars]', b'\x10', b'W', b'%', b'o', b'\xe3', b'\x7f'[51 chars]e3']]
First differing element 6:
[b'\x[164 chars]', b'@', b'3', b'\x11', b'o', b'\xe3', b'\x7f'[53 chars]xe3']
[b'\x[164 chars]', b'\x10', b'W', b'%', b'o', b'\xe3', b'\x7f'[50 chars]xe3']
  [1280,
   5,
   191,
   35387,
   15,
   15,
   [b'\x03',
    b'\x1c',
    b'\x7f',
    b'\x15',
    b'\x04',
    b'\x00',
    b'\x01',
    b'\x00',
    b'\x11',
    b'\x13',
    b'\x1a',
    b'\x00',
    b'\x12',
    b'\x0f',
    b'\x17',
    b'\x16',
    b'\x00',
    b'\x00',
    b'\x00',
-   b'@',
-   b'3',
-   b'\x11',
?        ^
+   b'\x10',
?        ^
+   b'W',
+   b'%',
    b'o',
    b'\xe3',
    b'\x7f',
    b'\x00',
    b'\x00',
-   b'\x00',
-   b'\x8f',
-   b'%',
?     ^
+   b'v',
?     ^
+   b']',
+   b'\xb6',
    b'o',
    b'\xe3']]
----------------------------------------------------------------------
Ran 3 tests in 0.004s
FAILED (failures=2)
test test_tty failed
1 test failed again:
    test_tty
```

**Comment by andypost** [comment]
and 3.11.7 https://gitlab.alpinelinux.org/alpine/aports/-/jobs/1252310

**Comment by sobolevn** [comment]
cc @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
Please add
```python
self.assertEqual(self.stream.fileno(), self.fd)
```
Does it fail?
