### ISSUE TITLE
ZoneInfo gives a surprising exception for `''`

### ISSUE THREAD

**Issue by asottile-sentry** [python/cpython#114713]
# Bug report

### Bug description:

```python
import zoneinfo
zoneinfo.ZoneInfo('')
```

results in the following exception:

```pycon
>>> zoneinfo.ZoneInfo('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/asottile/.pyenv/versions/3.11.6/lib/python3.11/zoneinfo/_tzpath.py", line 67, in find_tzfile
    _validate_tzfile_path(key)
  File "/Users/asottile/.pyenv/versions/3.11.6/lib/python3.11/zoneinfo/_tzpath.py", line 91, in _validate_tzfile_path
    raise ValueError(
ValueError: ZoneInfo keys must be normalized relative paths, got: 
```

I expect `zoneinfo.ZoneInfoNotFound` instead, or some other error that's more specific about this case

it seems this stems from the code internally using the length of the `normpath`'d result of this string and:

```pycon
>>> normpath('')
'.'
```

a small improvement would be to use `!r` in the error message as well

### CPython versions tested on:

3.11, CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-114731
* gh-132563
* gh-132582
* gh-133330
* gh-133331

**Comment by BartCodeLearning** [comment]
bikes.insert(-1, "BNL")
             
print(bikes)
             
['KTM', 'Honda', 'Yamaha', 'BNL', 'Suzuki']

#why .insert( -1) means different place with bikes[-1]


print (bikes[-1])
             
Suzuki



Why this happened? 
(Thanks a lot for that! I know it quite sily, but really confused me as a beginner...)
