### ISSUE TITLE
Possibly unintentional change in ssl

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#114905]
There is a possibly unintentional effect of #25455.

In Python 3.9:
```pycon
>>> import ssl
>>> ssl._create_stdlib_context(ssl.PROTOCOL_TLSv1_2, cert_reqs=ssl.CERT_NONE, check_hostname=True)
<ssl.SSLContext object at 0x7f93d68253c0>
```

In Python 3.10:
```pycon
>>> import ssl
>>> ssl._create_stdlib_context(ssl.PROTOCOL_TLSv1_2, cert_reqs=ssl.CERT_NONE, check_hostname=True)
/home/serhiy/py/cpython3.10/Lib/ssl.py:806: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
  context = SSLContext(protocol)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/py/cpython3.10/Lib/ssl.py", line 809, in _create_unverified_context
    context.verify_mode = cert_reqs
  File "/home/serhiy/py/cpython3.10/Lib/ssl.py", line 738, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.
```

This code not only emits a DeprecationWarning (it was expected), but also raises a ValueError.

This change left a confusing remnant in the code (see #103625) which can be safely deleted if this change was intentional. But this corner case is not covered by tests, this effect was not documented, so it is not known whether it was intentional change or error.

cc @tiran

**Comment by mbyrnepr2** [comment]
Howdy folks.
Sorry for the lack of detail here but I found this issue after a colleague drew my attention to the reported ValueError in our CI.

In our case it happens on Python 3.11 when running a pip install command in our CI. I haven't been able to reproduce it on my machine. I know pip vendors truststore which uses the standard library ssl module under the hood. Does it make sense that this can happen via pip also?

<details>
<summary>traceback</summary>

WARNING: There was an error checking the latest version of pip.
ERROR: Exception:
Traceback (most recent call last):
2025-07-31T12:51:46.5900390Z   File "C:\Python311\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
2025-07-31T12:51:46.5900846Z     status = _inner_run()
2025-07-31T12:51:46.5901198Z              ^^^^^^^^^^^^
2025-07-31T12:51:46.5901475Z   File "C:\Python311\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
2025-07-31T12:51:46.5901749Z     return self.run(options, args)
2025-07-31T12:51:46.5901974Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5902238Z   File "C:\Python311\Lib\site-packages\pip\_internal\cli\req_command.py", line 68, in wrapper
2025-07-31T12:51:46.5902520Z     return func(self, options, args)
2025-07-31T12:51:46.5902756Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5903031Z   File "C:\Python311\Lib\site-packages\pip\_internal\commands\install.py", line 387, in run
2025-07-31T12:51:46.5903317Z     requirement_set = resolver.resolve(
2025-07-31T12:51:46.5903540Z                       ^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5904844Z   File "C:\Python311\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 96, in resolve
2025-07-31T12:51:46.5905153Z     result = self._result = resolver.resolve(
2025-07-31T12:51:46.5905398Z                             ^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5905689Z   File "C:\Python311\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 515, in resolve
2025-07-31T12:51:46.5906009Z     state = resolution.resolve(requirements, max_rounds=max_rounds)
2025-07-31T12:51:46.5906601Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5907029Z   File "C:\Python311\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 388, in resolve
2025-07-31T12:51:46.5907529Z     self._add_to_criteria(self.state.criteria, r, parent=None)
2025-07-31T12:51:46.5909650Z   File "C:\Python311\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 141, in _add_to_criteria
2025-07-31T12:51:46.5910129Z     if not criterion.candidates:
2025-07-31T12:51:46.5910664Z   File "C:\Python311\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 194, in __bool__
2025-07-31T12:51:46.5911066Z     return bool(self._sequence)
2025-07-31T12:51:46.5911299Z            ^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5911589Z   File "C:\Python311\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 163, in __bool__
2025-07-31T12:51:46.5911890Z     self._bool = any(self)
2025-07-31T12:51:46.5912106Z                  ^^^^^^^^^
2025-07-31T12:51:46.5912377Z   File "C:\Python311\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 147, in <genexpr>
2025-07-31T12:51:46.5912687Z     return (c for c in iterator if id(c) not in self._incompatible_ids)
2025-07-31T12:51:46.5912940Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5913230Z   File "C:\Python311\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 33, in _iter_built
2025-07-31T12:51:46.5913513Z     for version, func in infos:
2025-07-31T12:51:46.5913818Z   File "C:\Python311\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 307, in iter_index_candidate_infos
2025-07-31T12:51:46.5914129Z     result = self._finder.find_best_candidate(
2025-07-31T12:51:46.5914368Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5914630Z   File "C:\Python311\Lib\site-packages\pip\_internal\index\package_finder.py", line 906, in find_best_candidate
2025-07-31T12:51:46.5914930Z     candidates = self.find_all_candidates(project_name)
2025-07-31T12:51:46.5915180Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5915457Z   File "C:\Python311\Lib\site-packages\pip\_internal\index\package_finder.py", line 843, in find_all_candidates
2025-07-31T12:51:46.5915748Z     page_candidates = list(page_candidates_it)
2025-07-31T12:51:46.5915976Z                       ^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5916239Z   File "C:\Python311\Lib\site-packages\pip\_internal\index\sources.py", line 193, in page_candidates
2025-07-31T12:51:46.5916535Z     yield from self._candidates_from_page(self._link)
2025-07-31T12:51:46.5916765Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5917042Z   File "C:\Python311\Lib\site-packages\pip\_internal\index\package_finder.py", line 801, in process_project_url
2025-07-31T12:51:46.5917346Z     index_response = self._link_collector.fetch_response(project_url)
2025-07-31T12:51:46.5917593Z                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5917863Z   File "C:\Python311\Lib\site-packages\pip\_internal\index\collector.py", line 448, in fetch_response
2025-07-31T12:51:46.5918170Z     return _get_index_content(location, session=self.session)
2025-07-31T12:51:46.5918427Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5919029Z   File "C:\Python311\Lib\site-packages\pip\_internal\index\collector.py", line 352, in _get_index_content
2025-07-31T12:51:46.5920230Z     resp = _get_simple_response(url, session=session)
2025-07-31T12:51:46.5920563Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5920947Z   File "C:\Python311\Lib\site-packages\pip\_internal\index\collector.py", line 131, in _get_simple_response
2025-07-31T12:51:46.5921328Z     resp = session.get(
2025-07-31T12:51:46.5921625Z            ^^^^^^^^^^^^
2025-07-31T12:51:46.5922002Z   File "C:\Python311\Lib\site-packages\pip\_vendor\requests\sessions.py", line 602, in get
2025-07-31T12:51:46.5922400Z     return self.request("GET", url, **kwargs)
2025-07-31T12:51:46.5922724Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5923108Z   File "C:\Python311\Lib\site-packages\pip\_internal\network\session.py", line 523, in request
2025-07-31T12:51:46.5924235Z     return super().request(method, url, *args, **kwargs)
2025-07-31T12:51:46.5924600Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5924951Z   File "C:\Python311\Lib\site-packages\pip\_vendor\requests\sessions.py", line 589, in request
2025-07-31T12:51:46.5925415Z     resp = self.send(prep, **send_kwargs)
2025-07-31T12:51:46.5925742Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5926106Z   File "C:\Python311\Lib\site-packages\pip\_vendor\requests\sessions.py", line 703, in send
2025-07-31T12:51:46.5926347Z     r = adapter.send(request, **kwargs)
2025-07-31T12:51:46.5926545Z         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5926764Z   File "C:\Python311\Lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 77, in send
2025-07-31T12:51:46.5927017Z     resp = super().send(request, stream, timeout, verify, cert, proxies)
2025-07-31T12:51:46.5927233Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5927468Z   File "C:\Python311\Lib\site-packages\pip\_vendor\requests\adapters.py", line 667, in send
2025-07-31T12:51:46.5927689Z     resp = conn.urlopen(
2025-07-31T12:51:46.5927862Z            ^^^^^^^^^^^^^
2025-07-31T12:51:46.5928091Z   File "C:\Python311\Lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 716, in urlopen
2025-07-31T12:51:46.5928339Z     httplib_response = self._make_request(
2025-07-31T12:51:46.5928533Z                        ^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5928750Z   File "C:\Python311\Lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 404, in _make_request
2025-07-31T12:51:46.5928988Z     self._validate_conn(conn)
2025-07-31T12:51:46.5929236Z   File "C:\Python311\Lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 1061, in _validate_conn
2025-07-31T12:51:46.5929470Z     conn.connect()
2025-07-31T12:51:46.5929690Z   File "C:\Python311\Lib\site-packages\pip\_vendor\urllib3\connection.py", line 406, in connect
2025-07-31T12:51:46.5929942Z     context.verify_mode = resolve_cert_reqs(self.cert_reqs)
2025-07-31T12:51:46.5930149Z     ^^^^^^^^^^^^^^^^^^^
2025-07-31T12:51:46.5930354Z   File "C:\Python311\Lib\site-packages\pip\_vendor\truststore\_api.py", line 292, in verify_mode
2025-07-31T12:51:46.5930612Z     _original_super_SSLContext.verify_mode.__set__(  # type: ignore[attr-defined]
2025-07-31T12:51:46.5930864Z ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.
</details>

**Comment by vstinner** [comment]
> ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.

This error is quite old, it was introduced by commit 1aa9a75fbff2333fd07574e3de8710c629483258 in 2013.

The commit 2875c603b2a7691b55c2046aca54831c91efda8e (2021) modified `ssl._create_unverified_context()` to set `context.check_hostname = check_hostname` even if *check_hostname* is true, before setting `context.verify_mode = cert_reqs`.

Python 3.9 code:

```py
    if not check_hostname:
        context.check_hostname = False
    if cert_reqs is not None:
        context.verify_mode = cert_reqs
    if check_hostname:
        context.check_hostname = True
```

Python 3.10 code:

```
    context.check_hostname = check_hostname  # CHANGED CODE
    if cert_reqs is not None:
        context.verify_mode = cert_reqs
    if check_hostname:
        context.check_hostname = True
```

IMO this change was made on purpose.

Example:

```py
import ssl
ctx=ssl._create_stdlib_context(ssl.PROTOCOL_TLSv1_2, cert_reqs=ssl.CERT_NONE, check_hostname=True)
ctx.verify_mode = ssl.CERT_NONE
```

On Python 3.9, this code fails with:

```
Traceback (most recent call last):
  File "/home/vstinner/python/3.9/../main/x.py", line 3, in <module>
    ctx.verify_mode = ssl.CERT_NONE
  File "/home/vstinner/python/3.9/Lib/ssl.py", line 723, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.
```

---

If *verify_mode* is CERT_NONE, setting `context.check_hostname` to `True` sets *verify_mode* to CERT_REQUIRED.

In Python 3.9, `context.verify_mode = cert_reqs` sets the *verify_mode* to CERT_NONE. But then, `context.check_hostname = True` sets the *verify_mode* to CERT_REQUIRED.

**Comment by gpshead** [comment]
FWIW if it has been this way for so many years and we're not getting complaints about the behavior my gut feeling is not to worry about it and just document it as intentional with a test keeping it that way?

**Comment by serhiy-storchaka** [comment]
If there is any way to trigger this error using the public API, we should add tests and document the change together with other changes in 3.11. If there is no such way, we can still add a test for private API.

**Comment by serhiy-storchaka** [comment]
Nothing in the standard library reaches this: no caller of `_create_stdlib_context()` passes *check_hostname*. poplib, smtplib, imaplib and ftplib call it with no arguments, `logging.handlers` passes only *certfile*/*keyfile*, and `get_server_certificate()` passes *cert_reqs* but never *check_hostname*. The `ValueError` that is reachable publicly, for example by assigning `CERT_NONE` to `verify_mode` on a `PROTOCOL_TLS_CLIENT` context, is the older rule from 2013, not this change.

The change is also narrower than the title suggests. `PROTOCOL_TLS_CLIENT`, for which this is always an error, became the default protocol in the very same commit. With an explicitly specified legacy protocol the combination used to succeed, silently raising *verify_mode* to `CERT_REQUIRED` and ignoring the requested `CERT_NONE`.

Both rules are documented for `SSLContext.check_hostname`, so nothing needs changing in the docs.

I propose a test for the private API pinning the current behaviour, plus a comment explaining why *check_hostname* is assigned before *verify_mode*. Then the remnant can be deleted as #103625 does.
