### ISSUE TITLE
[Windows] test_int.test_denial_of_service failed: took 15ms

### ISSUE THREAD

**Issue by encukou** [python/cpython#114911]
`test_int` recently [failed on a buildbot](https://buildbot.python.org/all/#/builders/1115/builds/437/steps/4/logs/stdio):
```
======================================================================
FAIL: test_denial_of_service_prevented_str_to_int (test.test_int.IntSubclassStrDigitLimitsTests.test_denial_of_service_prevented_str_to_int)
Regression test: ensure we fail before performing O(N**2) work.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "b:\uildarea\3.12.ware-win11.nondebug\build\Lib\test\test_int.py", line 743, in test_denial_of_service_prevented_str_to_int
    self.assertLessEqual(seconds_to_fail_extra_huge, seconds_to_convert/2)
AssertionError: 0.015625 not less than or equal to 0.0078125
```

I don't know for sure, but my guess is that a GC collection got triggered at the wrong time.

I'd like to add a test helper for timing CPU-bound tasks. It should disable GC and use `process_time`; perhaps it can do other tricks in the future too.

### Linked PRs
* gh-114912
* gh-131469

**Comment by vstinner** [comment]
> AssertionError: 0.015625 not less than or equal to 0.0078125

The problem here is that time.monotonic() has a resolution of 15.6 ms on Windows. It can return 0 or 15.6 ms for short timing, nothing in between. I added "CLOCK_RES" to some tests:

```
$ grep 'CLOCK_RES =' Lib/test/ -R
Lib/test/test_asyncio/utils.py:CLOCK_RES = 0.050
Lib/test/_test_eintr.py:CLOCK_RES = 0.020
Lib/test/_test_multiprocessing.py:CLOCK_RES = 0.100
Lib/test/test_os.py:    CLOCK_RES = CLOCK_RES_NS * 1e-9
```

**Comment by vstinner** [comment]
> The problem here is that time.monotonic() has a resolution of 15.6 ms on Windows

I don't know if it's the root issue or not. I will try to reproduce to debug the issue on Windows.

**Comment by encukou** [comment]
Hm, this is using`process_time`. Should it use `perf_counter` instead?

**Comment by sobolevn** [comment]
Happened again: https://github.com/python/cpython/pull/115504#issuecomment-1947841117

**Comment by encukou** [comment]
@terryjreedy, do you see this on a machine where you could test a fix?

**Comment by terryjreedy** [comment]
I observed 2 failures in about 18 tries on installed 3.13.0 no-debug gil.  I could hand-patch (copy-patch) a bit of test_int.

On fairly fresh local debug no-gil build I got 0 failures in 40 tries.  Easy to patch from PR, but need something that fails to test fix.

**Comment by vstinner** [comment]
> The problem here is that time.monotonic() has a resolution of 15.6 ms on Windows.

I changed time.monotonic() in Python 3.13 to use QueryPerformanceCounter(). It now has a resolution better than 1 microsecond.

**Comment by chris-eibl** [comment]
> The problem here is that time.monotonic() has a resolution of 15.6 ms on Windows.

`test_denial_of_service_prevented_str_to_int` uses **`process_time`** (before and after Petr's PR https://github.com/python/cpython/pull/114912).

`process_times` claims a resolution of 1e-07 for Windows, but that's just the "units" which are used to report, see e.g. https://github.com/python/cpython/issues/82040#issuecomment-1093831784.

Like @eryksun mentioned there, the "real" resolution is 15.625 ms by default, hence the `0.015625` in the traceback.

On my PC `sw_convert.seconds` is in the order of 20 milliseconds (wall time). 
Here are example frequencies for `process_times` of  `sw_convert.seconds` for 100 runs using [collections.Counter](https://docs.python.org/3/library/collections.html#collections.Counter):
`Counter({0.015625: 67, 0.03125: 30, 0.0: 3})`
which means, that in about two out of three cases `sw_convert.seconds` equals `0.015625`, 3 times the test bails out using [SkipTest('"slow" conversion')](https://github.com/python/cpython/blob/main/Lib/test/test_int.py#L637) and 30% I end up with  `0.03125`.

> It can return 0 or 15.6 ms for short timing, nothing in between.

Exactly this happens in very rare cases for [sw_fail_huge.seconds](https://github.com/python/cpython/blob/bb9d955e16c5578bdbc72750fbbffc8313559109/Lib/test/test_int.py#L646) or [sw_fail_extra_huge.seconds](https://github.com/python/cpython/blob/bb9d955e16c5578bdbc72750fbbffc8313559109/Lib/test/test_int.py#L657) even though they are only 2 to 4 **micro**seconds wall time on my PC. Almost always this results in `process_time=0`, but sometimes you get `process_time=15.625 ms` and then the test fails.

If we fix the reported resolution of `process_time`, then we will have to increase the [digits](https://github.com/python/cpython/blob/bb9d955e16c5578bdbc72750fbbffc8313559109/Lib/test/test_int.py#L627) for Windows, because otherwise we would almost always skip the test.
Or calculate the needed digits at runtime instead of hard coding, like @time-one suggests in #118686.

> Hm, this is using `process_time`. Should it use `perf_counter` instead?

This would fix Windows and other OSs having such poor resolution for `process_times`. All platforms should have "good enough" resolution in case of [perf_counter](https://docs.python.org/3/library/time.html#time.perf_counter):

>  [...] i.e. a clock with the highest available resolution to measure a short duration.

But then `CPUStopwatch` should be renamed to just `Stopwatch` or `WalltimeStopwatch`?

**Comment by chris-eibl** [comment]
Can I open a PR using `time.monotonic` in `class CPUStopwatch`? The few users of it IMHO all would be fine with wall time, since they  do CPU intense stuff and then wall time should be process time, anyway.

**Comment by chris-eibl** [comment]
The only other user of `CPUStopwatch` I found is
https://github.com/python/cpython/blob/7ae9c5dd25cccfc4e44fae6c6974ab9f32c5e985/Lib/test/test_re.py#L2474-L2485
where according to the comment `time.monotonic` would do its job, too.

**Comment by chris-eibl** [comment]
IMHO, wall time is a better fit, because https://docs.python.org/3/library/time.html#time.process_time
https://github.com/python/cpython/blob/7ae9c5dd25cccfc4e44fae6c6974ab9f32c5e985/Lib/test/support/__init__.py#L2587-L2588

**Comment by encukou** [comment]
AFAIK the test suite doesn't have a threaded mode, so this should not matter much? It definitely would be better if it didn't include time spent in other threads, but, at least it doesn't include time spent in other *processes*.
On a loaded system (or if I run tests with `-j30` on a 20-core machine, to fill in all the sleeps `test_asyncio` does), I'd expect wall-clock time to be less accurate.

`time.perf_counter` might be a better fit than `time.monotonic`, though in practice they're the same thing.

> Can I open a PR using time.monotonic in class CPUStopwatch?

Go ahead. You could also rename it to Stopwatch. That way we can see the change on buildbots.

**Comment by encukou** [comment]
> in theory, CPU time would be the better fit

That makes me think: should this continue using `process_time` on non-Windows platforms?

**Comment by chris-eibl** [comment]
IMHO it is better to use the same clock for all platforms. Otherwise, we might end up with an `if` for specific platforms, if `process_time` and `perf_counter` deviate. Let's try to go with a "one fits all"?

**Comment by encukou** [comment]
Thanks for the PR!
Merged; let's see if we start getting failures on other systems.

**Comment by encukou** [comment]
I just saw a [failure on Windows](https://buildbot.python.org/#/builders/914/builds/4886):
```
======================================================================
FAIL: test_denial_of_service_prevented_str_to_int (test.test_int.IntStrDigitLimitsTests.test_denial_of_service_prevented_str_to_int)
Regression test: ensure we fail before performing O(N**2) work.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "b:\uildarea\3.x.ware-win11.nondebug\build\Lib\test\test_int.py", line 659, in test_denial_of_service_prevented_str_to_int
    self.assertLessEqual(sw_fail_extra_huge.seconds, sw_convert.seconds/2)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 0.0491769015789032 not less than or equal to 0.019058849662542343

----------------------------------------------------------------------
Ran 51 tests in 39.698s

FAILED (failures=1)
```

**Comment by encukou** [comment]
> better skip it on platforms where we cannot reliably test it

Yeah, it might be better to skip it on platforms that don't have a reliable high-resolution per-thread CPU time counter. Which is... all of them.

So, give up and remove the test?

I'm not aware of any other part of the codebase that's tested for accidental quadratic behaviour.

**Comment by chris-eibl** [comment]
> I'm not aware of any other part of the codebase that's tested for accidental quadratic behaviour.

Just recently, in https://github.com/python/cpython/pull/134874 a test was requested.

There, just `time.time()` is used. Well, if the test lasts long enough, the resolution doesn't matter (but it is then unnecessarily CPU intense). Hopefully, this doesn't end in similar problems like `test_denial_of_service_prevented_str_to_int`.

Here, the implementation was optimized a lot but the initial test left untouched AFAICT, and so we dropped below the resolution on Windows.

We could increase
https://github.com/python/cpython/blob/28d91d06f13ceda3df0cefacec497c370eff4802/Lib/test/test_int.py#L629
or just
>So, give up and remove the test?

**Comment by picnixz** [comment]
> I'm not aware of any other part of the codebase that's tested for accidental quadratic behaviour.

We have some tests, mainly for ReDoS:

https://github.com/python/cpython/blob/28d91d06f13ceda3df0cefacec497c370eff4802/Lib/test/test_http_cookiejar.py#L189
https://github.com/python/cpython/blob/28d91d06f13ceda3df0cefacec497c370eff4802/Lib/test/test_http_cookiejar.py#L128
https://github.com/python/cpython/blob/28d91d06f13ceda3df0cefacec497c370eff4802/Lib/test/test_poplib.py#L356
https://github.com/python/cpython/blob/28d91d06f13ceda3df0cefacec497c370eff4802/Lib/test/test_difflib.py#L530

And once I find a way to fix the issues in `email/_header_value_parser.py`, I also plan to add some tests.

**Comment by chris-eibl** [comment]
And the interesting thing for all those tests above: they do not measure the time :)

**Comment by picnixz** [comment]
Yes, we just check that we're not spending hours because in general that's what it does otherwise. Unfortunately, I don't know if this would be the case for `test_denial_of_service`. I don't know if there's an input that can be done "fast" if the algorithm is correct but that would be "very slow" otherwise.

**Comment by johnzhou721** [comment]
> There, just `time.time()` is used. Well, if the test lasts long enough, the resolution doesn't matter (but it is then unnecessarily CPU intense). Hopefully, this doesn't end in similar problems like `test_denial_of_service_prevented_str_to_int`.

Hmm... not sure but it *should* be longer than 15ms... it's processing a string with around 20000 characters, going through most of them one by one in linear time complexity.  Also that fix is essentially a non-issue since IDLE isn't used in production... and the problem happens only if indent size is very huge and things are adjusted carefully.

Again, sorry for my lack of experience and using time.time.  Would anyone like to suggest a better approach?
