### ISSUE TITLE
``dis.dis`` can not disassemble code that uses hexadecimal number formatting

### ISSUE THREAD

**Issue by Toggoren** [python/cpython#114987]
# Bug report

### Expected behavior

Same as 
```sh
>>> import dis;dis.dis((lambda: format(1, 'X'))())
  0           0 RESUME                   0

  1           2 RETURN_CONST             0 (1)
```

### Actual behavior

``SyntaxError``

### Reproduction Case

```sh
>>> import dis;dis.dis((lambda: f'{42:X}')())
Traceback (most recent call last):
  File "C:\Python\x64\3.8.10\lib\dis.py", line 38, in _try_compile
    c = compile(source, name, 'eval')
  File "<dis>", line 1
    2A
     ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\x64\3.8.10\lib\dis.py", line 83, in dis
    _disassemble_str(x, file=file, depth=depth)
  File "C:\Python\x64\3.8.10\lib\dis.py", line 415, in _disassemble_str
    _disassemble_recursive(_try_compile(source, '<dis>'), **kwargs)
  File "C:\Python\x64\3.8.10\lib\dis.py", line 40, in _try_compile
    c = compile(source, name, 'exec')
  File "<dis>", line 1
    2A
     ^
SyntaxError: invalid syntax

>>> import dis;dis.dis((lambda: format(42, 'X'))())
Traceback (most recent call last):
  File "C:\Python\x64\3.8.10\lib\dis.py", line 38, in _try_compile
    c = compile(source, name, 'eval')
  File "<dis>", line 1
    2A
     ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\x64\3.8.10\lib\dis.py", line 83, in dis
    _disassemble_str(x, file=file, depth=depth)
  File "C:\Python\x64\3.8.10\lib\dis.py", line 415, in _disassemble_str
    _disassemble_recursive(_try_compile(source, '<dis>'), **kwargs)
  File "C:\Python\x64\3.8.10\lib\dis.py", line 40, in _try_compile
    c = compile(source, name, 'exec')
  File "<dis>", line 1
    2A
     ^
SyntaxError: invalid syntax
```

```sh
>>> import dis;dis.dis((lambda: f'{42:X}')())
Traceback (most recent call last):
  File "C:\Python\x64\3.11.2\Lib\dis.py", line 63, in _try_compile
    c = compile(source, name, 'eval')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<dis>", line 1
    2A
    ^
SyntaxError: invalid decimal literal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\x64\3.11.2\Lib\dis.py", line 108, in dis
    _disassemble_str(x, file=file, depth=depth, show_caches=show_caches, adaptive=adaptive)
  File "C:\Python\x64\3.11.2\Lib\dis.py", line 584, in _disassemble_str
    _disassemble_recursive(_try_compile(source, '<dis>'), **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\x64\3.11.2\Lib\dis.py", line 65, in _try_compile
    c = compile(source, name, 'exec')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<dis>", line 1
    2A
    ^
SyntaxError: invalid decimal literal

>> import dis;dis.dis((lambda: format(42, 'X'))())
Traceback (most recent call last):
  File "C:\Python\x64\3.11.2\Lib\dis.py", line 63, in _try_compile
    c = compile(source, name, 'eval')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<dis>", line 1
    2A
    ^
SyntaxError: invalid decimal literal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\x64\3.11.2\Lib\dis.py", line 108, in dis
    _disassemble_str(x, file=file, depth=depth, show_caches=show_caches, adaptive=adaptive)
  File "C:\Python\x64\3.11.2\Lib\dis.py", line 584, in _disassemble_str
    _disassemble_recursive(_try_compile(source, '<dis>'), **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\x64\3.11.2\Lib\dis.py", line 65, in _try_compile
    c = compile(source, name, 'exec')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<dis>", line 1
    2A
    ^
SyntaxError: invalid decimal literal
```

```sh
>>> import dis;dis.dis((lambda: f'{42:X}')())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\x64\3.12.0\Lib\dis.py", line 117, in dis
    _disassemble_str(x, file=file, depth=depth, show_caches=show_caches, adaptive=adaptive)
  File "C:\Python\x64\3.12.0\Lib\dis.py", line 613, in _disassemble_str
    _disassemble_recursive(_try_compile(source, '<dis>'), **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\x64\3.12.0\Lib\dis.py", line 75, in _try_compile
    return compile(source, name, 'exec')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<dis>", line 1
    2A
    ^
SyntaxError: invalid decimal literal

>>> import dis;dis.dis((lambda: format(42, 'X'))())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\x64\3.12.0\Lib\dis.py", line 117, in dis
    _disassemble_str(x, file=file, depth=depth, show_caches=show_caches, adaptive=adaptive)
  File "C:\Python\x64\3.12.0\Lib\dis.py", line 613, in _disassemble_str
    _disassemble_recursive(_try_compile(source, '<dis>'), **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\x64\3.12.0\Lib\dis.py", line 75, in _try_compile
    return compile(source, name, 'exec')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<dis>", line 1
    2A
    ^
SyntaxError: invalid decimal literal
```

### CPython versions tested on:

3.8, 3.11, 3.12

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
If you pass dis.dis a string, it must be valid code that compiles without error.  "2A" is not legal Python code, so a error is proper.  `(lambda: format(1, 'X'))()` evaluates to '1' and this is a legal expression statement.  The 'x' formatting make no difference in the resulting string.

In the future, please submit questions about possible bugs and unmet expectations to a help forum such as https://discuss.python.org/c/users/7.
