### ISSUE TITLE
`email.message.Message.as_bytes`: exception with policy change

### ISSUE THREAD

**Issue by d-maurer** [python/cpython#115162]
# Bug report

### Bug description:

```python
# -*- coding: utf-8 -*-
from email import message_from_string
from email.policy import SMTP

m = message_from_string("""\
From: dieter
To: dieter
Subject: Test äöü

A test""")

m.as_bytes()
m.as_bytes(policy=SMTP)
```
```pycon
>>> m.as_bytes()
b'From: dieter\nTo: dieter\nSubject: =?utf-8?b?VGVzdCDDpMO2w7w=?=\n\nA test'
>>> m.as_bytes()
b'From: dieter\nTo: dieter\nSubject: =?utf-8?b?VGVzdCDDpMO2w7w=?=\n\nA test'
>>> m.as_bytes(policy=SMTP)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/email/message.py", line 208, in as_bytes
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/local/lib/python3.12/email/generator.py", line 115, in flatten
    self._write(msg)
  File "/usr/local/lib/python3.12/email/generator.py", line 198, in _write
    self._write_headers(msg)
  File "/usr/local/lib/python3.12/email/generator.py", line 421, in _write_headers
    self._fp.write(self.policy.fold_binary(h, v))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/policy.py", line 202, in fold_binary
    return folded.encode(charset, 'surrogateescape')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-16: ordinal not in range(128)
```

### CPython versions tested on:

3.12

**Comment by d-maurer** [comment]
> What exactly is the Python version?

3.12.1

**Comment by d-maurer** [comment]
I can confirm that the problem is gone in Python 3.12.2
