### ISSUE TITLE
AssertionError: Thread.__init__() not called

### ISSUE THREAD

**Issue by wilson3q** [python/cpython#115121]
# Bug report

### Bug description:

I use gevent + gunicorn in my python app, I do monkey patch for all. After upgrading to python 3.12.2, i started to observe a lot assertion failure errors in my app logs.

```
Exception ignored in: <function _after_fork at 0x7f04dd0b0400>
Traceback (most recent call last):
  File "/home/scm/lib/python3.12/threading.py", line 1691, in _after_fork
    thread._set_tstate_lock()
  File "/home/scm/lib/python3.12/threading.py", line 1051, in _set_tstate_lock
    if not self.daemon:
           ^^^^^^^^^^^
  File "/home/scm/lib/python3.12/threading.py", line 1246, in daemon
    assert self._initialized, "Thread.__init__() not called"
AssertionError: Thread.__init__() not called
```
Please take a look at the code sections below.

```python
 def _set_tstate_lock(self):
        """
        Set a lock object which will be released by the interpreter when
        the underlying thread state (see pystate.h) gets deleted.
        """
        self._tstate_lock = _set_sentinel()
        self._tstate_lock.acquire()

        if not self.daemon:
            with _shutdown_locks_lock:
                _maintain_shutdown_locks()
                _shutdown_locks.add(self._tstate_lock)
....

@property
    def daemon(self):
        """A boolean value indicating whether this thread is a daemon thread.

        This must be set before start() is called, otherwise RuntimeError is
        raised. Its initial value is inherited from the creating thread; the
        main thread is not a daemon thread and therefore all threads created in
        the main thread default to daemon = False.

        The entire Python program exits when only daemon threads are left.

        """
        assert self._initialized, "Thread.__init__() not called"
        return self._daemonic
....


def _after_fork():
    """
    Cleanup threading module state that should not exist after a fork.
    """
    # Reset _active_limbo_lock, in case we forked while the lock was held
    # by another (non-forked) thread.  http://bugs.python.org/issue874900
    global _active_limbo_lock, _main_thread
    global _shutdown_locks_lock, _shutdown_locks
    _active_limbo_lock = RLock()

    # fork() only copied the current thread; clear references to others.
    new_active = {}

    try:
        current = _active[get_ident()]
    except KeyError:
        # fork() was called in a thread which was not spawned
        # by threading.Thread. For example, a thread spawned
        # by thread.start_new_thread().
        current = _MainThread()

    _main_thread = current

    # reset _shutdown() locks: threads re-register their _tstate_lock below
    _shutdown_locks_lock = _allocate_lock()
    _shutdown_locks = set()

    with _active_limbo_lock:
        # Dangling thread instances must still have their locks reset,
        # because someone may join() them.
        threads = set(_enumerate())
        threads.update(_dangling)
        for thread in threads:
            # Any lock/condition variable may be currently locked or in an
            # invalid state, so we reinitialize them.
            if thread is current:
                # There is only one active thread. We reset the ident to
                # its new value since it can have changed.
                thread._reset_internal_locks(True)
                ident = get_ident()
                if isinstance(thread, _DummyThread):
                    thread.__class__ = _MainThread
                    thread._name = 'MainThread'
                    thread._daemonic = False
                    thread._set_tstate_lock()
                thread._ident = ident
                new_active[ident] = thread
            else:
                # All the others are already stopped.
                thread._reset_internal_locks(False)
                thread._stop()

        _limbo.clear()
        _active.clear()
        _active.update(new_active)
        assert len(_active) == 1
```
source code all from Lib/threading.py.

line 1691 in Lib/threading.py, **_set_tstate_lock** was invoked for **_DummyThread** instance.
But in **_set_tstate_lock** function, it invokes **self.daemon**, which instead triggered assertion failure. 

Should it simply call **self._daemonic** instead?

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by serhiy-storchaka** [comment]
`_initialized` is set to True in `Thread.__init__()` which is called in `_DummyThread.__init__()`. How can it be not true?

**Comment by wilson3q** [comment]
Issue was found in gevent [monkey patch](https://github.com/gevent/gevent/blob/master/src/gevent/threading.py). __init__ was not called for **_DummyThread**.

**Comment by wilson3q** [comment]
BTW, I have reported the issue to [gevent repo](https://github.com/gevent/gevent/issues/2020) as well.

**Comment by serhiy-storchaka** [comment]
Then I'm closing this.

**Comment by serhiy-storchaka** [comment]
Perhaps it will be possible to add special hooks for gevent, so they will no longer need to monkey-patch implementation details of the stdlib. But I am not well familiar with this library, so I do not know what they need for this.
