### ISSUE TITLE
datetime.datetime.isoformat parses input incorrectly

### ISSUE THREAD

**Issue by xitop** [python/cpython#115225]
# Bug report

### Bug description:

```python
import datetime as dt
print(dt.time.fromisoformat("T1250.50"))
```

Actual result is `12:50:00.500000`, but according to ISO 8601 the string represents `12:50:30`
(50 and half minutes, format "HHMM.mmm", because _"a decimal fraction may be added
to the lowest order time element present"_)

if partial minutes are not supported by Python as stated in the docs, a `ValueError` should be raised.

Affected are versions 3.10+.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-115313
* gh-119339

**Comment by pganssle** [comment]
> if partial minutes are not supported by Python as stated in the docs, a `ValueError` should be raised.

Fractional hours and minutes should not be supported. We should change the `time.fromisoformat` docs to reflect that and raise a `ValueError` in this case.

The reason why they are not supported is that we decided that a string like `T12:00.50` is much more likely to be a typo for something like `T12:00:50` than to be an actual fractional hour or minute, because this is a particularly obscure feature of ISO-8601.

@xitop How did you discover this? Were you using something that actually generates a string like that, or was this an attempt to find bugs? I'm curious to know if my reasoning about no one _really_ using these features is correct.

**Comment by StanFromIreland** [comment]
The implementation causes odd behavior for the pure Python implementation

```
>>> import _pydatetime as dt
... print(dt.time.fromisoformat("T1250.50"))
... 
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/_pydatetime.py", line 1633, in fromisoformat
    return cls(*_parse_isoformat_time(time_string)[0])
                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/_pydatetime.py", line 466, in _parse_isoformat_time
    time_comps = _parse_hh_mm_ss_ff(timestr)
  File "/usr/local/lib/python3.14/_pydatetime.py", line 418, in _parse_hh_mm_ss_ff
    time_comps[comp] = int(tstr[pos:pos+2])
                       ~~~^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '.5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<python-input-0>", line 2, in <module>
    print(dt.time.fromisoformat("T1250.50"))
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/_pydatetime.py", line 1635, in fromisoformat
    raise ValueError(f'Invalid isoformat string: {time_string!r}')
ValueError: Invalid isoformat string: '1250.50'
```

C for reference:

```
>>> import datetime as dt
... print(dt.time.fromisoformat("T1250.50"))
... 
Traceback (most recent call last):
  File "<python-input-1>", line 2, in <module>
    print(dt.time.fromisoformat("T1250.50"))
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
ValueError: Invalid isoformat string: 'T1250.50'

```

**Comment by encukou** [comment]
The PR was merged some time ago.

> The implementation causes odd behavior for the pure Python implementation

IMO, exception chaining is perfectly fine. The final exception is the same; we don't really need to hide the reason.
