### ISSUE TITLE
python3.10 does not work

### ISSUE THREAD

**Issue by reitcircles** [python/cpython#115880]
# Crash report

### What happened?

```python
# 

Python 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycardano
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nsaha/.local/lib/python3.8/site-packages/pycardano/__init__.py", line 3, in <module>
    from .address import *
  File "/home/nsaha/.local/lib/python3.8/site-packages/pycardano/address.py", line 14, in <module>
    from pycardano.crypto.bech32 import decode, encode
  File "/home/nsaha/.local/lib/python3.8/site-packages/pycardano/crypto/__init__.py", line 3, in <module>
    from .bip32 import *
  File "/home/nsaha/.local/lib/python3.8/site-packages/pycardano/crypto/bip32.py", line 17, in <module>
    from nacl import bindings
  File "/home/nsaha/.local/lib/python3.8/site-packages/nacl/bindings/__init__.py", line 16, in <module>
    from nacl.bindings.crypto_aead import (
  File "/home/nsaha/.local/lib/python3.8/site-packages/nacl/bindings/crypto_aead.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]

**Comment by hugovk** [comment]
This is the issue tracker for CPython itself.

Please report problems with pycardano at https://github.com/Python-Cardano/pycardano
