### ISSUE TITLE
"make regen-global-objects "is broken

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#115893]
```pytb
iritkatriel@Irits-MBP cpython-1 % make regen-global-objects
python3.13 ./Tools/clinic/clinic.py --make --exclude Lib/test/clinic.test.c --srcdir .
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/./Tools/clinic/clinic.py", line 6271, in <module>
    main()
    ~~~~^^
  File "/Users/iritkatriel/src/cpython-1/./Tools/clinic/clinic.py", line 6262, in main
    run_clinic(parser, args)
    ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/./Tools/clinic/clinic.py", line 6241, in run_clinic
    parse_file(path,
    ~~~~~~~~~~^^^^^^
               verify=not ns.force, limited_capi=ns.limited_capi)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/./Tools/clinic/clinic.py", line 2450, in parse_file
    cooked = clinic.parse(raw)
             ~~~~~~~~~~~~^^^^^
  File "/Users/iritkatriel/src/cpython-1/./Tools/clinic/clinic.py", line 2329, in parse
    parser.parse(block)
    ~~~~~~~~~~~~^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/./Tools/clinic/clinic.py", line 4995, in parse
    block.output.extend(self.clinic.language.render(self.clinic, block.signatures))
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/./Tools/clinic/clinic.py", line 573, in render
    return self.render_function(clinic, function)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/./Tools/clinic/clinic.py", line 1531, in render_function
    templates = self.output_templates(f, clinic)
                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/./Tools/clinic/clinic.py", line 933, in output_templates
    parsearg = converters[0].parse_arg(argname, displayname, limited_capi=limited_capi)
               ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cache_struct_converter.parse_arg() got an unexpected keyword argument 'limited_capi'
make: *** [clinic] Error 1
```

**Comment by iritkatriel** [comment]
the type of the converter it's failing on is <class 'main.cache_struct_converter'>
I believe that's defined in Modules/_struct.c

**Comment by iritkatriel** [comment]
Works on a fresh clone, so must be something in my repo (make clean did not help).
