### ISSUE TITLE
Inner decorator makes failing unittests appear to pass - `DeprecationWarning` wrongfully triggered.

### ISSUE THREAD

**Issue by Achwalt** [python/cpython#115862]
# Bug report

### Issue Summary
When applying a custom decorator to a test method within a `unittest.TestCase` class, if the decorator's inner function (wrapper) returns a value (even implicitly) and it itself is wrapped by an internal decorating function and the returned value is `None`, Python 3.11's `unittest` framework generates a `DeprecationWarning`.

**Even worse:** It makes failing/broken unittests appear to be okay.

### Expected Behavior:
(Generally valid and usable) Decorators should be able to (also) wrap test methods without altering the interface or expectations of the unittest framework, including not triggering warnings when the decorator's wrapper function returns a value.
The test case should be run and fail accordingly.

### Steps to reproduce
Run this code with _Python v3.11_. Observe that only two cases are failing.
 
```python
import unittest
from unittest.mock import patch
from functools import wraps

def okay_decorator(func):
    "This decorator works fine with python unittesting"
    @wraps(func)
    def wrapper(*args, **kwargs):
        print("Before test function execution")
        result = func(*args, **kwargs)
        print("After test function execution")
        return result
    return wrapper

def not_okay_decorator(custom_response=None):
    "This decorator breaks python unittesting if custom_response=None"
    def decorator(func):
        @wraps(func) # Just to preserve the name, technically not needed
        def wrapper(*args, **kwargs):
            # Simulate patching with custom_response if provided, else call the original function
            with patch('builtins.print', return_value=custom_response):
                print("This print call is patched to return a custom response.")
            return func(*args, **kwargs)  # This line is key: it returns the func's return value -> Deprecated
        return wrapper
    return decorator

class MyTestCase(unittest.TestCase):
    
    @okay_decorator
    def test_sample_simple(self):
        self.assertEqual(1, 2)
    
    @not_okay_decorator
    def test_sample_not_okay(self):
        self.assertEqual(1, 2) # Does NOT fail!

    @not_okay_decorator(custom_response="test-me")
    def test_sample_okay(self):
        self.assertEqual(1, 2)

if __name__ == '__main__':
    unittest.main()
    # Notice there are only 2 failed test cases. 3 were run, 3 should have failed.
```

**This should lead to the following outcome:**
```
(va) USER@LAPTOP:~/Development/PROJECT$ python -m test.test_failure
/home/USER/anaconda3/envs/va/lib/python3.11/unittest/case.py:678: DeprecationWarning: It is deprecated to return a value that is not None from a test case (<bound method not_okay_decorator.<locals>.decorator of <__main__.MyTestCase testMethod=test_sample_not_okay>>)
  return self.run(*args, **kwds)
.FBefore test function execution
F
======================================================================
FAIL: test_sample_okay (__main__.MyTestCase.test_sample_okay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/USER/Development/PROJECT/test/test_failure.py", line 23, in wrapper
    return func(*args, **kwargs)  # This line is key: it returns the func's return value -> Deprecated
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/Development/PROJECT/test/test_failure.py", line 39, in test_sample_okay
    self.assertEqual(1, 2)
AssertionError: 1 != 2

======================================================================
FAIL: test_sample_simple (__main__.MyTestCase.test_sample_simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/USER/Development/PROJECT/test/test_failure.py", line 10, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/Development/PROJECT/test/test_failure.py", line 31, in test_sample_simple
    self.assertEqual(1, 2)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=2) # EDIT: Plz indicate the missing third test case was not successful because of the deprecation
```

_Please not that the paths and the username are replaced by PROJECT and USER. Also see the tagged comment. The rest of the output is unchanged._
### Environment:
- Python Version: Python 3.11.7
- Operating System: Kubuntu 22.04
(unittest framework version included with Python 3.11.7)

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by sobolevn** [comment]
This does seem like a bug in your code. When `@not_okay_decorator` is applied right now it expects an argument.

```python
    @not_okay_decorator
    def test_sample_not_okay(self):
        self.assertEqual(1, 2) # Does NOT fail!
```

This means that `not_okay_decorator(custom_response=test_sample_not_okay)` 

To solve this try:

```python
def not_okay_decorator(fn=None, *, custom_response=None):
    "This decorator breaks python unittesting if custom_response=None"
    def decorator(func):
        @wraps(func) # Just to preserve the name, technically not needed
        def wrapper(*args, **kwargs):
            # Simulate patching with custom_response if provided, else call the original function
            with patch('builtins.print', return_value=custom_response):
                print("This print call is patched to return a custom response.")
            return func(*args, **kwargs)  # This line is key: it returns the func's return value -> Deprecated
        return wrapper
    if fn is not None:
        return decorator(fn)
    return decorator
```

It produces:

```
FFBefore test function execution
F
======================================================================
FAIL: test_sample_not_okay (__main__.MyTestCase.test_sample_not_okay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython2/ex.py", line 23, in wrapper
    return func(*args, **kwargs)  # This line is key: it returns the func's return value -> Deprecated
           ~~~~^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython2/ex.py", line 37, in test_sample_not_okay
    self.assertEqual(1, 2) # Does NOT fail!
    ~~~~~~~~~~~~~~~~^^^^^^
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (failures=3)
```

----

**However**, the test report does seem strange to me.
It reports to run 3 tests, but actually runs 2 🤔

**Comment by sobolevn** [comment]
Ok, after some debugging, here are my thoughts:
1. It is correctly loading 3 test cases, because it loads all methods that start with `test_` prefix
2. It tries to run all three cases, the problem one just returns `return wrapper`, so the non-`None` warning is generated and no expected work is done 
3. To fix this, you can run your tests with `-We`

```
» ./python.exe -W error ex.py
E
======================================================================
ERROR: test_sample_not_okay (__main__.MyTestCase.test_sample_not_okay)
----------------------------------------------------------------------
DeprecationWarning: It is deprecated to return a value that is not None from a test case (<bound method not_okay_decorator.<locals>.decorator of <__main__.MyTestCase testMethod=test_sample_not_okay>>)

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

I don't think that anything can be done here (except the fact that this warning will become an exception one day in the future versions).

**Comment by Achwalt** [comment]
Taking a step back to reflect sometimes goes a very long way.
Using `@not_okay_decorator()` (ie calling the decorator) was an avoidable oversight on my end.

Thank you for your time and patience.
