### ISSUE TITLE
`_xxinterpqueues.create` documentation is outdated

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#116266]
Documentation says:
https://github.com/python/cpython/blob/87faec28c78f6fa8eaaebbd1ababf687c7508e71/Modules/_xxinterpqueuesmodule.c#L1316-L1319

That's not true because `create` accepts `maxsize` and `fmt` arguments:
```python
>>> import _xxinterpqueues
>>> _xxinterpqueues.create()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    _xxinterpqueues.create()
    ~~~~~~~~~~~~~~~~~~~~~~^^
TypeError: create() missing required argument 'maxsize' (pos 1)
>>> _xxinterpqueues.create(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    _xxinterpqueues.create(5)
    ~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: create() missing required argument 'fmt' (pos 2)
```

**Comment by Eclips4** [comment]
Resolved by 4402b3cbcf8323bfa908ef86a687a5a7d46d27f3
