### ISSUE TITLE
Multiprocessing module doesn't work in REPL

### ISSUE THREAD

**Issue by itsme300** [python/cpython#116403]
# Bug report

### Bug description:

```batch
(base) C:\Users\AEU5COB\Documents\CCS2>python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from multiprocessing import Process
>>> import os
>>>
>>> def info(title):
...     print(title)
...     print('module name:', __name__)
...     print('parent process:', os.getppid())
...     print('process id:', os.getpid())
...
>>> def f(name):
...     info('function f')
...     print('hello', name)
...
>>> if __name__ == '__main__':
...     info('main line')
...     p = Process(target=f, args=('bob',))
...     p.start()
...     p.join()
...
main line
module name: __main__
parent process: 20076
process id: 15144
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
```
works when excuted as a python script. Example taken from https://docs.python.org/3.9/library/multiprocessing.html#module-multiprocessing

### CPython versions tested on:

3.9

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello! Thanks for the report!
For me it seems this reproducible only in python REPL.

**Comment by Eclips4** [comment]
This behaviour described in documentation: https://docs.python.org/3/library/multiprocessing.html#using-a-pool-of-workers
So, there's no bug.

**Comment by itsme300** [comment]
Works though on Ubuntu GNU/Linux
```bash
Python 3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def info(title):
...     print(title)
...     print('module name:', __name__)
...     print('parent process:', os.getppid())
...     print('process id:', os.getpid())
...
>>> def f(name):
...     info('function f')
...     print('hello', name)
...
>>> if __name__ == '__main__':
...     info('main line')
...     p = Process(target=f, args=('bob',))
...     p.start()
...     p.join()
...
main line
module name: __main__
parent process: 3996
process id: 9801
function f
module name: __main__
parent process: 9801
process id: 10360
hello bob
```

**Comment by zware** [comment]
`multiprocessing` [currently](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) defaults to `fork()` on Linux, which accidentally allows that to work.  It should not be relied upon.
