### ISSUE TITLE
`test.test_httpservers.CGIHTTPServerTestCase` OSError: [Errno 39] Directory not empty

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#116575]
### Bug description:

Configuration:
```sh
./configure --enable-optimizations --with-valgrind --enable-profiling --enable-pystats --with-pydebug --with-trace-refs --with-assertions --with-lto=full --disable-gil
```

Test:
```python
./python -m unittest -v test.test_httpservers.CGIHTTPServerTestCase
```
Output:
```python
test_accept (test.test_httpservers.CGIHTTPServerTestCase.test_accept) ... ERROR
test_authorization (test.test_httpservers.CGIHTTPServerTestCase.test_authorization) ... ERROR
test_cgi_path_in_sub_directories (test.test_httpservers.CGIHTTPServerTestCase.test_cgi_path_in_sub_directories) ... ERROR
test_headers_and_content (test.test_httpservers.CGIHTTPServerTestCase.test_headers_and_content) ... ERROR
test_invaliduri (test.test_httpservers.CGIHTTPServerTestCase.test_invaliduri) ... ok
test_issue19435 (test.test_httpservers.CGIHTTPServerTestCase.test_issue19435) ... ok
test_nested_cgi_path_issue21323 (test.test_httpservers.CGIHTTPServerTestCase.test_nested_cgi_path_issue21323) ... ERROR
test_no_leading_slash (test.test_httpservers.CGIHTTPServerTestCase.test_no_leading_slash) ... ERROR
test_os_environ_is_not_altered (test.test_httpservers.CGIHTTPServerTestCase.test_os_environ_is_not_altered) ... ERROR
test_post (test.test_httpservers.CGIHTTPServerTestCase.test_post) ... ERROR
test_query_with_continuous_slashes (test.test_httpservers.CGIHTTPServerTestCase.test_query_with_continuous_slashes) ... ERROR
test_query_with_multiple_question_mark (test.test_httpservers.CGIHTTPServerTestCase.test_query_with_multiple_question_mark) ... ERROR
test_url_collapse_path (test.test_httpservers.CGIHTTPServerTestCase.test_url_collapse_path) ... ok
test_urlquote_decoding_in_cgi_check (test.test_httpservers.CGIHTTPServerTestCase.test_urlquote_decoding_in_cgi_check) ... ERROR

======================================================================
ERROR: test_accept (test.test_httpservers.CGIHTTPServerTestCase.test_accept)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_httpservers.py", line 818, in tearDown
    os.rmdir(self.parent_dir)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/tmp/tmpfe6jcaez'

======================================================================
ERROR: test_authorization (test.test_httpservers.CGIHTTPServerTestCase.test_authorization)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_httpservers.py", line 818, in tearDown
    os.rmdir(self.parent_dir)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/tmp/tmpvrs3934b'

======================================================================
ERROR: test_cgi_path_in_sub_directories (test.test_httpservers.CGIHTTPServerTestCase.test_cgi_path_in_sub_directories)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_httpservers.py", line 818, in tearDown
    os.rmdir(self.parent_dir)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/tmp/tmpsdveqvmu'

======================================================================
ERROR: test_headers_and_content (test.test_httpservers.CGIHTTPServerTestCase.test_headers_and_content)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_httpservers.py", line 818, in tearDown
    os.rmdir(self.parent_dir)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/tmp/tmp750tkq3k'

======================================================================
ERROR: test_nested_cgi_path_issue21323 (test.test_httpservers.CGIHTTPServerTestCase.test_nested_cgi_path_issue21323)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_httpservers.py", line 818, in tearDown
    os.rmdir(self.parent_dir)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/tmp/tmpvn66kyr7'

======================================================================
ERROR: test_no_leading_slash (test.test_httpservers.CGIHTTPServerTestCase.test_no_leading_slash)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_httpservers.py", line 818, in tearDown
    os.rmdir(self.parent_dir)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/tmp/tmp4n554svm'

======================================================================
ERROR: test_os_environ_is_not_altered (test.test_httpservers.CGIHTTPServerTestCase.test_os_environ_is_not_altered)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_httpservers.py", line 818, in tearDown
    os.rmdir(self.parent_dir)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/tmp/tmp_td7nngk'

======================================================================
ERROR: test_post (test.test_httpservers.CGIHTTPServerTestCase.test_post)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_httpservers.py", line 818, in tearDown
    os.rmdir(self.parent_dir)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/tmp/tmpac62ifdo'

======================================================================
ERROR: test_query_with_continuous_slashes (test.test_httpservers.CGIHTTPServerTestCase.test_query_with_continuous_slashes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_httpservers.py", line 818, in tearDown
    os.rmdir(self.parent_dir)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/tmp/tmpgy_ltxhz'

======================================================================
ERROR: test_query_with_multiple_question_mark (test.test_httpservers.CGIHTTPServerTestCase.test_query_with_multiple_question_mark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_httpservers.py", line 818, in tearDown
    os.rmdir(self.parent_dir)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/tmp/tmp8z1w_ek8'

======================================================================
ERROR: test_urlquote_decoding_in_cgi_check (test.test_httpservers.CGIHTTPServerTestCase.test_urlquote_decoding_in_cgi_check)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_httpservers.py", line 818, in tearDown
    os.rmdir(self.parent_dir)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/tmp/tmp5wbjpkr7'

----------------------------------------------------------------------
Ran 14 tests in 2.793s

FAILED (errors=11)
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by terryjreedy** [comment]
Win 10, fresh main: above 14 run ok with `f:\dev\3x>python -m test -m CGIHTTPServerTestCase test_httpservers`.

**Comment by furkanonder** [comment]
Since the issue is no longer present in version 3.13, 3.12, and the main branch, I am closing the issue.
