### ISSUE TITLE
FAIL: `test.test_regrtest.ArgsTestCase.test_add_python_opts (opt='--fast-ci')`

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#116574]
### Bug description:

Configuration:
```sh
./configure --enable-optimizations --with-valgrind --enable-profiling --enable-pystats --with-pydebug --with-trace-refs --with-assertions --with-lto=full --disable-gil
```

Test:
```python
./python -m unittest -v test.test_regrtest.ArgsTestCase.test_add_python_opts
```
Output:
```python
test_add_python_opts (test.test_regrtest.ArgsTestCase.test_add_python_opts) ... 
  test_add_python_opts (test.test_regrtest.ArgsTestCase.test_add_python_opts) (opt='--fast-ci') ... FAIL

======================================================================
FAIL: test_add_python_opts (test.test_regrtest.ArgsTestCase.test_add_python_opts) (opt='--fast-ci')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_regrtest.py", line 2165, in test_add_python_opts
    self.check_add_python_opts(opt)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/arf/cpython/Lib/test/test_regrtest.py", line 2160, in check_add_python_opts
    self.assertEqual(proc.returncode, 0, proc)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: -27 != 0 : CompletedProcess(args=['/home/arf/cpython/python', '-m', 'test', '--fast-ci', '--testdir=/tmp/tmppfd0yyna', 'test_regrtest_noop1'], returncode=-27, stdout='+ /home/arf/cpython/python -u -W default -bb -E -m test --fast-ci --testdir=/tmp/tmppfd0yyna test_regrtest_noop1 --dont-add-python-opts\n')

----------------------------------------------------------------------
Ran 1 test in 2.733s

FAILED (failures=1)
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by sobolevn** [comment]
It does not reproduce on macos m2:

```
» ./python.exe -m unittest -v test.test_regrtest.ArgsTestCase.test_add_python_opts
test_add_python_opts (test.test_regrtest.ArgsTestCase.test_add_python_opts) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.566s

OK
```

**Comment by vstinner** [comment]
Can you still reproduce the issue on Python 3.13.2?

**Comment by terryjreedy** [comment]
`py -3.12 -m unittest -v test.test_regrtest.ArgsTestCase.test_add_python_opts` and same for 3.13 and 3.14 are OK on my Win 10.

**Comment by vstinner** [comment]
I close the issue. Please reopen it if you can still reproduce it.
