### ISSUE TITLE
object.__init_subclass__ should take keyword arguments but doesn't

### ISSUE THREAD

**Issue by blhsing** [python/cpython#116697]
# Bug report

### Bug description:

When defining a custom `__init_subclass__` for a class, it's almost always a good practice to call `super().__init_subclass__` to make the class cooperative with other classes which may also have `__init_subclass__` defined. And that cooperation includes passing on any given keyword arguments.

[PEP-487](https://peps.python.org/pep-0487/#proposal) suggests as much, with the first demonstrated use case of `__init_subclass__` being one with a call to `super().__init_subclass__(**kwargs)`.

And yet, the actual implementation of [`object.__init_subclass__`](https://github.com/python/cpython/blob/bf121d6a694bea4fe9864a19879fe0c70c4e0656/Objects/typeobject.c#L6698) does not take keyword arguments, making it unnecessarily difficult to call `super().__init_subclass__(**kwargs)` without fear of producing a `TypeError`.

Consider the following use case where both `Foo` and `Bar` are designed to look for a `debug` keyword argument when subclassed:

```python
class Foo:
    def __init_subclass__(cls, **kwargs):
        if kwargs.get('debug'):
            print(f'initialized from {Foo.__init_subclass__}')
        super().__init_subclass__(**kwargs)

class Bar:
    def __init_subclass__(cls, **kwargs):
        if kwargs.get('debug'):
            print(f'initialized from {Bar.__init_subclass__}')
        super().__init_subclass__(**kwargs)

class Baz(Foo, Bar, debug=True):
    pass
```
This outputs:
```
initialized from <bound method Foo.__init_subclass__ of <class '__main__.Foo'>>
initialized from <bound method Bar.__init_subclass__ of <class '__main__.Bar'>>
Traceback (most recent call last):
  File "./prog.py", line 13, in <module>
  File "./prog.py", line 5, in __init_subclass__
  File "./prog.py", line 11, in __init_subclass__
TypeError: Baz.__init_subclass__() takes no keyword arguments
```
The fix should be to simply make `object.__init_subclass__` accept keyword arguments and ignore them.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, Windows

**Comment by blhsing** [comment]
Per a [discussion](https://discuss.python.org/t/allow-object-init-subclass-to-take-keyword-arguments/48343/8) at Python Discourse I realized that `object.__init_subclass__` is not supposed to take keyword arguments because it makes typos harder to catch, and that a common and elegant workaround is to use a base class to consume known keyword arguments before pass them to `super().__init_subclass__`:
```
class Base:
    def __init_subclass__(cls, **kwargs):
        kwargs.pop('debug', None)
        super().__init_subclass__(**kwargs)

class Foo(Base):
    def __init_subclass__(cls, **kwargs):
        if kwargs.get('debug'):
            print(f'initialized from {Foo.__init_subclass__}')
        super().__init_subclass__(**kwargs)

class Bar(Base):
    def __init_subclass__(cls, **kwargs):
        if kwargs.get('debug'):
            print(f'initialized from {Bar.__init_subclass__}')
        super().__init_subclass__(**kwargs)

class Baz(Foo, Bar, debug=True):
    pass
```
