### ISSUE TITLE
test_capi.test_misc fails with `-u all`

### ISSUE THREAD

**Issue by Yhg1s** [python/cpython#116656]
# Bug report

### Bug description:

In current `main`, test_capi.test_misc fails when run with `-uall`. 

```
centurion:/tmp/testbuild/Python-3.13.0a5 > ./python -m test -uall test_capi.test_misc
Using random seed: 468383501
0:00:00 load avg: 7.27 Run 1 test sequentially
0:00:00 load avg: 7.27 [1/1] test_capi.test_misc
Unknown option: -a
usage: ./python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
Traceback (most recent call last):
  File "<string>", line 8, in <module>
SystemError: _PyErr_SetFromPyStatus() status is not an error
test test_capi.test_misc failed -- Traceback (most recent call last):
  File "/tmp/testbuild/Python-3.13.0a5/Lib/test/test_capi/test_misc.py", line 1806, in test_py_config_isoloated_per_interpreter
    self.assertEqual(support.run_in_subinterp(code), 0,
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     'subinterp code failure, check stderr.')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: -1 != 0 : subinterp code failure, check stderr.

test_capi.test_misc failed (1 failure)

== Tests result: FAILURE ==

1 test failed:
    test_capi.test_misc

Total duration: 11.0 sec
Total tests: run=260 failures=1 skipped=3
Total test files: run=1/1 failed=1
Result: FAILURE
```

This came up during the release process for alpha 5, since we actually enable all resources for one of the test runs. I know we disable most resources on CI, but apparently we have no buildbots with the right resources enabled either?

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-116658
* gh-116668

**Comment by vstinner** [comment]
I proposed a fix: https://github.com/python/cpython/pull/116658
