### ISSUE TITLE
CPython 3.11 fails under WASI SDK 21

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#116831]
# Bug report

### Bug description:

https://buildbot.python.org/all/#/builders/1370/builds/146/steps/11/logs/stdio

```
======================================================================
ERROR: test_issue16421_multiple_modules_in_one_dll (test.test_imp.ImportTests.test_issue16421_multiple_modules_in_one_dll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Lib/test/test_imp.py", line 249, in test_issue16421_multiple_modules_in_one_dll
    fileobj, pathname, description = imp.find_module(m)
                                     ^^^^^^^^^^^^^^^^^^
  File "/Lib/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_testimportmultiple'
======================================================================
ERROR: test_issue24748_load_module_skips_sys_modules_check (test.test_imp.ImportTests.test_issue24748_load_module_skips_sys_modules_check)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Lib/test/test_imp.py", line 295, in test_issue24748_load_module_skips_sys_modules_check
    module = imp.load_dynamic(name, spec.origin)
                                    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'origin'
======================================================================
ERROR: test_load_module_extension_file_is_None (test.test_imp.ImportTests.test_load_module_extension_file_is_None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Lib/test/test_imp.py", line 278, in test_load_module_extension_file_is_None
    found = imp.find_module(name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Lib/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_testimportmultiple'
----------------------------------------------------------------------
Ran 29 tests in 0.131s
FAILED (errors=3, skipped=2)
test test_imp failed
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Other

### Linked PRs
* gh-116933

**Comment by brettcannon** [comment]
If the decision is made not to fix this, then the buildbot config should be updated to select the appropriate WASI SDK version when building CPython 3.11 (or bite the bullet and define builders based on the WASI SDK version).

**Comment by brettcannon** [comment]
Simplest solution may be to just skip those tests under WASI that involve extension modules.

**Comment by brettcannon** [comment]
And now everything passes under WASI SDK 21 on Python 3.11! https://buildbot.python.org/all/#/builders/1370/builds/155

Thanks, @kushaldas !
