### ISSUE TITLE
Stack trace of re-raised exception is wrong

### ISSUE THREAD

**Issue by pelson** [python/cpython#116862]
# Bug report

### Bug description:

If you catch an exception and hold on to it for later handling, and then re-raise the exception, the stack trace is wrong (the stack is a blend of the two stacks). 

A simple example:

```py
def err_returning_call() -> Exception:
    try:
        raise ValueError('foo')
    except Exception as err:
        return err

def raise_err(err):
    raise err

err = err_returning_call()

raise_err(err)
```

Produces a traceback with:

```pytb
$ python simplest_cpython_bug.py 
Traceback (most recent call last):
  File "example.py", line 14, in <module>
    raise_err(err)
    ~~~~~~~~~^^^^^
  File "example.py", line 10, in raise_err
    raise err
  File "example.py", line 3, in err_returning_call
    raise ValueError('foo')
ValueError: foo
```

Note that the previously caught exception (raise err) produces a traceback that mixes the original stack and the new stack, rather than a clean traceback from the point where it is re-raised.

----

Raising the exception from another (adapting ``err_returning_call`` to ``raise ValueError('another') from err``) produces a logical stack trace:

```pytb
$ ./build/bin/python3 simplest_cpython_bug.py 
Traceback (most recent call last):
  File "example.py", line 3, in err_returning_call
    raise ValueError('foo')
ValueError: foo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example.py", line 14, in <module>
    raise_err(err)
    ~~~~~~~~~^^^^^
  File "example.py", line 10, in raise_err
    raise ValueError('another') from err
ValueError: another
```

----

The deeper the stacks, the more confusing the tb. It also seems to drop an important step in the traceback (even if we use the ``raise new_error from original_error`` pattern):

```py
def root_call():
    return err_returning_call()

def err_returning_call() -> Exception:
    try:
        error_raising()
    except Exception as err:
        return err

def error_raising():
    raise ValueError('foo')


err = root_call()


def raise_err(err):
    raise err

def indirect_raise_err(err):
    raise_err(err)


indirect_raise_err(err)
```

With the result:

```pytb
Traceback (most recent call last):
  File "example.py", line 24, in <module>
    indirect_raise_err(err)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "example.py", line 21, in indirect_raise_err
    raise_err(err)
    ~~~~~~~~~^^^^^
  File "example.py", line 18, in raise_err
    raise err
  File "example.py", line 6, in err_returning_call
    error_raising()
    ~~~~~~~~~~~~~^^
  File "example.py", line 11, in error_raising
    raise ValueError('foo')
ValueError: foo
```

Note that with the raise from included, the traceback is:

```pytb
Traceback (most recent call last):
  File "example.py", line 6, in err_returning_call
    error_raising()
    ~~~~~~~~~~~~~^^
  File "example.py", line 11, in error_raising
    raise ValueError('foo')
ValueError: foo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example.py", line 24, in <module>
    indirect_raise_err(err)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "example.py", line 21, in indirect_raise_err
    raise_err(err)
    ~~~~~~~~~^^^^^
  File "example.py", line 18, in raise_err
    raise ValueError('bar') from err
ValueError: bar
```

Notice how even in this case, the original traceback is missing the ``root_call`` call (possibly reasonable?).

The expected behaviour would be to simply raise the exception with the stack trace of the final ``raise`` call. This would be analogous to what happens when you capture an exception in a variable without raising it:

```py
exception = ValueError('not raised directly')

raise exception
```

Which produces the following traceback:

```pytb
Traceback (most recent call last):
  File "/media/important/github/python/cpython/./exception_var.py", line 3, in <module>
    raise exception
ValueError: not raised directly
```

This report is against main (at 2cf18a4430 - the latest commit on 15/3/2024), but applies all the way back to Python 3.7 at least.

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13, CPython main branch

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
This is long standing behaviour in Python, even it is not documented clearly in [the language reference](https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement).  The [documentation for Exception.with_traceback](https://docs.python.org/3/library/exceptions.html#BaseException.with_traceback) also implies this is intentional behaviour.

**Comment by pelson** [comment]
Thanks for the relevant links! I don't see in there that the traceback would actually be _wrong_. The new behaviour in Python 3.11 in the language reference docs talks about modification of the traceback, but in this case I am simply raising a traceback that has been raised (and caught) previously.

Perhaps, with sufficient interpretation of the docs in ``from_traceback``, we could say that this is documented behaviour (the wording is not particularly clear here):

> Once raised, the current frame is pushed onto the traceback of the [exception to be raised], as would have happened to the traceback of the original SomeException had we allowed it to propagate to the caller

But even so, the behaviour is questionable (wrong IMO), and there is now a well established mechanism for chaining exceptions. I can't see any justification for the behaviour being different to my final example (where the traceback is reported from where the object is being raised from, not from a traceback that occurred previously [and was already handled]). 

With thanks to your input, I was also able to realise that I can get the proposed behaviour by clearing the traceback on the object ``exception.__traceback__ = None``, which then results in a good traceback when the object is raised.

**Comment by ronaldoussoren** [comment]
> But even so, the behaviour is questionable (wrong IMO) ...

Regardless of that, the language has behaved like this since at least 2.7 (the oldest version I can easily test on). That makes it hard to change the behaviour, especially for edge cases like this.   It would be helpful to clearly document the behaviour.

What's your use case for storing a raised exception and raising that stored value in a different context?

**Comment by pelson** [comment]
> What's your use case for storing a raised exception and raising that stored value in a different context?

I have a few obscure ones, but the obvious one is the use of futures. I spotted this in a `StackOverflow` question recently at https://stackoverflow.com/questions/75289851/why-does-calling-future-exception-in-a-done-callback-change-the-traceback. Ultimately, the user is:

1. Raising in the func of the future
2. Accessing the result of the future with `future.result()`, but passing if any exception occurs
3. Accessing the result of the future again, but this time observing that the traceback is wrong

This seems like a completely valid use of storing exceptions, and is clearly resulting in behaviour which confuses.

> That makes it hard to change the behaviour, especially for edge cases like this

I appreciate the difficulty very much. At the same time, could you come up with any use cases where the existing behaviour is actually desired? I see no way to avoid calling the behaviour a bug, given that it produces a garbage (not real/correct) traceback.

**Comment by powellnorma** [comment]
I just spend quite some time trying to figure out where my code got stuck. Turned out the tracebacks were truncated since I used a `task.add_done_callback` which calls `task.result()` + ignores `asyncio.CancelledError`.

So I just got:

```
File "/some/path/1", line 475, in some_function
	await self.gather_future
asyncio.exceptions.CancelledError
```

Instead of the much more helpful:

```
File "/some/path/1", line 475, in some_function
	await self.gather_future
File "/some/path/2", line 426, in some_function_2
	await check(ctx)
[..]
File "/some/path/15", line 112, in some_function_15
	await asyncio.wait_for(cookie_new.wait(), timeout)
File "/usr/lib64/python3.11/asyncio/tasks.py", line 476, in wait_for
	await waiter
asyncio.exceptions.CancelledError
```

> Regardless of that, the language has behaved like this since at least 2.7

Ok, but I don't think anyone is depending on this (unhelpful) behavior, right?

I believe this would be a valuable feature to implement, as it can take quite a while to discover this behavior when it affects you.
