### ISSUE TITLE
argparse: parse_args with a subparser + namespace tries to setdefault on a mappingproxy object

### ISSUE THREAD

**Issue by alex-tianhuang** [python/cpython#116850]
# Bug report

### Bug description:

I was using the namespace argument in parse_args and found that argparse tries to setdefault on a mapping proxy when parsing unknown extra attributes:

```python
import argparse


parser = argparse.ArgumentParser()
subparser = argparse.ArgumentParser()
subparsers = parser.add_subparsers()
subparsers.add_parser(name="sub", add_help=False)


class MyNamespace:
    pass


try:
    parser.parse_args(["sub", "oops"], namespace=MyNamespace)
except SystemExit:
    pass
```

```plaintext
Traceback (most recent call last):
File "<path_to_script>", line 16, in <module>
parser.parse_args(["sub", "oops"], namespace=MyNamespace)
File "<python_installation>/lib/python3.12/argparse.py", line 1891, in parse_args
args, argv = self.parse_known_args(args, namespace)
File "<python_installation>/lib/python3.12/argparse.py", line 1924, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
File "<python_installation>/lib/python3.12/argparse.py", line 2139, in _parse_known_args
stop_index = consume_positionals(start_index)
File "<python_installation>/lib/python3.12/argparse.py", line 2095, in consume_positionals
take_action(action, args)
File "<python_installation>/lib/python3.12/argparse.py", line 2000, in take_action
action(self, namespace, argument_values, option_string)
File "<python_installation>/lib/python3.12/argparse.py", line 1268, in call
vars(namespace).setdefault(_UNRECOGNIZED_ARGS_ATTR, [])
AttributeError: 'mappingproxy' object has no attribute 'setdefault'
```

I suspect this is because we're attempting to do vars(MyNamespace) instead of vars(argparse.Namespace) but I don't know much more than that. 

I skimmed the top couple entries on the issue tracker with keywords 'argparse mappingproxy / argparse namespace' and found nothing, so I've decided that maybe nobody has reported this yet.

Using python 3.12.1 / argparse 1.1 / osx-arm64.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-124667
* gh-124757
* gh-124758

**Comment by mimros** [comment]
Hi, I had same issue. I think you have to create instance of your namespace class.


```python
class MyNamespace:
    pass


try:
    my_namespace = MyNamespace() <---------------------------------------------
    parser.parse_args(["sub", "oops"], namespace=my_namespace)
except SystemExit:
    pass
```

https://docs.python.org/3/library/argparse.html#argparse.Namespace
