### ISSUE TITLE
Cannot use "name" attribute for Dataclass Enum

### ISSUE THREAD

**Issue by kbumsik** [python/cpython#117060]
# Bug report

### Bug description:

I try using Dataclass Support for Enum class, as newly mentioned in [Enum HOWTO document in Python 3.12](https://docs.python.org/3/howto/enum.html#dataclass-support).

```python
from enum import Enum
from dataclasses import dataclass, field

@dataclass
class CreatureDataMixin:
    size: str
    legs: int
    tail: bool = field(repr=False, default=True)

class Creature(CreatureDataMixin, Enum):
    BEETLE = 'small', 6
    DOG = 'medium', 4

Creature.DOG
<Creature.DOG: size='medium', legs=4>
```

This works well as described in the documentation. But I got `AttributeError: <enum 'Enum'> cannot set attribute 'name'` in the following code:

```diff
from enum import Enum
from dataclasses import dataclass, field

@dataclass
class CreatureDataMixin:
-    size: str
+    name: str
    legs: int
    tail: bool = field(repr=False, default=True)

class Creature(CreatureDataMixin, Enum):
    BEETLE = 'small', 6
    DOG = 'medium', 4

Creature.DOG
```

Here is the error log:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/kbumsik/Library/CloudStorage/Dropbox/Work/DeepAuto/Projects/console-pod-server/app/src/deepauto/app/cmd/test/__init__.py", line 14, in <module>
    class Creature(CreatureDataMixin, Enum):
  File "/Users/kbumsik/anaconda3/envs/pod-app/lib/python3.12/enum.py", line 593, in __new__
    raise exc.with_traceback(tb)
  File "/Users/kbumsik/anaconda3/envs/pod-app/lib/python3.12/enum.py", line 583, in __new__
    enum_class = super().__new__(metacls, cls, bases, classdict, **kwds)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kbumsik/anaconda3/envs/pod-app/lib/python3.12/enum.py", line 282, in __set_name__
    enum_member.__init__(*args)
  File "<string>", line 3, in __init__
  File "/Users/kbumsik/anaconda3/envs/pod-app/lib/python3.12/enum.py", line 225, in __set__
    raise AttributeError(
AttributeError: <enum 'Enum'> cannot set attribute 'name'
```

I am not sure this behavior is expected.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by blhsing** [comment]
This is because `name` and `value` are already read-only properties of all `Enum` members. Since `name` and `value` are rather common attribute names, perhaps it makes sense to add a constructor option to rename these properties?

**Comment by ethanfurman** [comment]
@kbumsik, in your example, the `name` attribute is already being set to `BEETLE` and `DOG`.  When using a dataclass mix-in with Enum, it is not possible to have a `name` attribute with different values because the enum members are also instances of the dataclass mix-in.  In other words, you can do:

```python
>>> Creature.DOG.size
'medium'
>>> Creature.BEETLE.legs
6
>>> Creature.DOG.name
'DOG'
```
