### ISSUE TITLE
Potential string parsing regression in 3.12

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#117212]
# Bug report

I have this test case for my linter:

```python
import io
import tokenize

code = '''
a = """abc
abc
""".split('\n')
'''
```

It used to work just fine. It is a multiline string that contains a multiline string. With different quotes.

But, starting from 3.12 it does not work anymore:

```python
lines = io.StringIO(code)
list(tokenize.generate_tokens(lambda: next(lines)))
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#     list(tokenize.generate_tokens(lambda: next(lines)))
#     ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/Users/sobolev/Desktop/cpython2/Lib/tokenize.py", line 580, in _generate_tokens_from_c_tokenizer
#     raise TokenError(msg, (e.lineno, e.offset)) from None
# tokenize.TokenError: ('unterminated string literal (detected at line 4)', (4, 11))

```python
exec(code)
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#     exec(code)
#     ~~~~^^^^^^
#   File "<string>", line 4
#     """.split('
#               ^
# SyntaxError: unterminated string literal (detected at line 4)
```

This looks incorrect to me, but I want to double check that with parser experts.
CC @pablogsal and @lysnikolaou

**Comment by pablogsal** [comment]
Hummm, I don't get the second part. That's what's supposed to happen, and indeed this is what happens in 3.11:

```
❯ python --version
Python 3.11.6

~
❯ python test.py
Traceback (most recent call last):
  File "/Users/pgalindo3/lel.py", line 6, in <module>
    exec(code)
  File "<string>", line 4
    """.split('
              ^
SyntaxError: unterminated string literal (detected at line 4)

❯ python3.12 --version
Python 3.12.2

~
❯ python3.12 lel.py
Traceback (most recent call last):
  File "/Users/pgalindo3/lel.py", line 6, in <module>
    exec(code)
  File "<string>", line 4
    """.split('
              ^
SyntaxError: unterminated string literal (detected at line 4)
```

**Comment by pablogsal** [comment]
(Note if you want this to work with `exec` you should scape the newline):

```
code = '''
a = """abc
abc
""".split('\\n')
print(a)
'''
exec(code)
```

**Comment by pablogsal** [comment]
Given that this is technically invalid code (it doesn't parse correctly, even in old versions), it's not technically a regression. Remember the warning in the `tokenizer` docs:
![Screenshot 2024-03-25 at 12 54 07](https://github.com/python/cpython/assets/11718525/23a5dad7-dc9f-4244-93b0-66af2b313b25)

**Comment by sobolevn** [comment]
Ok, got it. Then we can count this as an improvement instead: it detected invalid escape :)
Thanks!

**Comment by pablogsal** [comment]
Yeah, this is definitely expected. Notice that in 3.11 the list of tokens contains a lot of `ERRORTOKEN` in any case:

```
[TokenInfo(type=62 (NL), string='\n', start=(1, 0), end=(1, 1), line='\n'),
 TokenInfo(type=1 (NAME), string='a', start=(2, 0), end=(2, 1), line='a = """abc\n'),
 TokenInfo(type=54 (OP), string='=', start=(2, 2), end=(2, 3), line='a = """abc\n'),
 TokenInfo(type=3 (STRING), string='"""abc\nabc\n"""', start=(2, 4), end=(4, 3), line='a = """abc\nabc\n""".split(\'\n'),
 TokenInfo(type=54 (OP), string='.', start=(4, 3), end=(4, 4), line='""".split(\'\n'),
 TokenInfo(type=1 (NAME), string='split', start=(4, 4), end=(4, 9), line='""".split(\'\n'),
 TokenInfo(type=54 (OP), string='(', start=(4, 9), end=(4, 10), line='""".split(\'\n'),
 TokenInfo(type=60 (ERRORTOKEN), string="'", start=(4, 10), end=(4, 11), line='""".split(\'\n'),
 TokenInfo(type=62 (NL), string='\n', start=(4, 11), end=(4, 12), line='""".split(\'\n'),
 TokenInfo(type=60 (ERRORTOKEN), string="'", start=(5, 0), end=(5, 1), line="')\n"),
 TokenInfo(type=54 (OP), string=')', start=(5, 1), end=(5, 2), line="')\n"),
 TokenInfo(type=4 (NEWLINE), string='\n', start=(5, 2), end=(5, 3), line="')\n"),
 TokenInfo(type=0 (ENDMARKER), string='', start=(6, 0), end=(6, 0), line='')]
```

So in general, given that this is not valid Python code, there is no guarantees on what this code will do when tokenised
