### ISSUE TITLE
ABCs with bogus __subclasses__ break instance/subclass checks for other ABCs

### ISSUE THREAD

**Issue by hroncok** [python/cpython#117255]
# Bug report

### Bug description:

Consider this evil class:

```python
import abc

class EvilABC(abc.ABC):
    __subclasses__ = ...
```

Now all instance/subclass checks for other ABCs fail:

```pycon
>>> isinstance(..., abc.ABC)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    isinstance(..., abc.ABC)
    ~~~~~~~~~~^^^^^^^^^^^^^^
  File "<frozen abc>", line 119, in __instancecheck__
  File "<frozen abc>", line 123, in __subclasscheck__
  File "<frozen abc>", line 123, in __subclasscheck__
TypeError: attribute of type 'ellipsis' is not callable
```

This happens because the recursive call to `__subclasses__` in https://github.com/python/cpython/blob/v3.13.0a5/Lib/_py_abc.py#L141 trusts that `__subclasses__`  will always be callable and return an iterable (or a list in the C implementation).

----

You might argue that the EvilABC class is evil and whoever does that is doomed to be punished. However, it can easily be done by a mistake. This class has a broken `__subclasses__` without explicitly defining it:

```python
class Crossbreed(abc.ABCMeta, os.PathLike):
    ...
```

```pycon
>>> isinstance("/", os.PathLike)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    isinstance("/", os.PathLike)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 119, in __instancecheck__
  File "<frozen abc>", line 123, in __subclasscheck__
  File "<frozen abc>", line 123, in __subclasscheck__
TypeError: unbound method type.__subclasses__() needs an argument
```

It is very surprising that by defining a class we can break checks for other classes and hence third party code, even from the standard library:

```
$ python3 -c 'import abc, os, subprocess
> class A(abc.ABCMeta, os.PathLike): pass
> subprocess.run(("echo",))'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/lib64/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.12/subprocess.py", line 1802, in _execute_child
    elif isinstance(args, os.PathLike):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 119, in __instancecheck__
  File "<frozen abc>", line 123, in __subclasscheck__
  File "<frozen abc>", line 123, in __subclasscheck__
TypeError: unbound method type.__subclasses__() needs an argument
```

In my opinion, the `__subclasses__` call should be guarded by a try-except and either:

 - skip broken subclasses, or
 - skip broken subclasses and warn about them, or
 - raise a better exception message, saying which subclass is broken

See also https://discuss.python.org/t/abcmeta-change-isinstancecheck-of-additional-parent-class/19908

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13, CPython main branch

**Comment by blhsing** [comment]
According to the documentation, the [`class.__subclasses__`](https://docs.python.org/3/library/stdtypes.html#class.__subclasses__) method is supposed to work on any class. Since `type` itself is a class, `type.__subclasses__` should be expected to work instead of producing `TypeError: unbound method type.__subclasses__() needs an argument`.

This can be fixed by making the first parameter of `type.__subclasses__` optional, defaulting its value to `type`.

[Demo](https://ato.pxeger.com/run?1=fVK9TsMwEJYY_RTe4lTBEhtCypB2BcTAhiorP9fWamJHPkdRnoWlCzwUT4OdOiW0VW-wz_d995Mv9_ndDnan1eHw1dnN_ePPXSWbVhtLcUAS3KKTtZUKCSnrHJG-Qv8-tMCsO-InQp1VsKFCKOiFYGWNCV3kZuuvxb73XqB5kxtag2JjlKYpffiDvBmwnVFUG7kVvgEbK8XkDMeuBcNifrMpmc2GXTFOD3hkp7Ppr_Xllymu3gmmKfUXmbThIRi0IRXUXkLe6KqrAT8ikRdltE7-B6_FNEbrSXmfNJbyDveHkEraCfZocPXp76yMRiwMQMV8UrZcvYDNE8fgb7ndPcv99Nmc8ykpY40jjf5cmNa9A2PJsnmQtEYqy2ZFzwWL48DJLpHjsoWdm3bvFw) of a quick fix:
```python
import sys
import builtins

class NewType(type):
    def __new__(cls, *args, **kwargs):
        if len(args) == 1:
            return orig_type(*args)
        return super().__new__(cls, *args, **kwargs)

    def __subclasses__(cls=type):
        return orig_type.__subclasses__(cls)

orig_type = type
builtins.type = NewType
del sys.modules['_abc'], sys.modules['abc'], sys.modules['os']
import _abc
del _abc._abc_init
import abc
import os

class Crossbreed(abc.ABCMeta, os.PathLike):
    ...
print(os.PathLike.__subclasses__())

class A(metaclass=type):
    pass
class B(A):
    pass
print(A.__subclasses__())
```
