### ISSUE TITLE
3.10.14: test suite fails in `test_zlib` unit in build env with installed zlib-ng

### ISSUE THREAD

**Issue by kloczek** [python/cpython#117424]
# Bug report

### Bug description:

````console
0:00:08 load avg: 15.76 [213/424/1] test_zlib failed (1 error)
test test_zlib failed -- Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/Python-3.10.14/Lib/test/test_zlib.py", line 448, in test_flushes
    ver = tuple(int(v) for v in zlib.ZLIB_RUNTIME_VERSION.split('.'))
  File "/home/tkloczko/rpmbuild/BUILD/Python-3.10.14/Lib/test/test_zlib.py", line 448, in <genexpr>
    ver = tuple(int(v) for v in zlib.ZLIB_RUNTIME_VERSION.split('.'))
ValueError: invalid literal for int() with base 10: 'zlib-ng'
```


### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by kloczek** [comment]
Closing as duplicate of #98567
