### ISSUE TITLE
test_multiprocessing_forkserver OSError: [Errno 39] Directory not empty: '/tmp/test_python_8uqlpn0m/tmp5h9be3ji'

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#117555]
# Bug report

### Bug description:

The problem is seen in a [buildbot](https://buildbot.python.org/all/#/builders/1376/builds/53).

[Configuration](https://buildbot.python.org/all/#/builders/1376/builds/53/steps/2/logs/stdio):
```sh
./configure --prefix '$(PWD)/target' --with-pydebug
 in dir /home/ubuntu/buildarea/3.12.onder-riscv64/build (timeout 1200 secs)
 watching logfiles {}
 argv: [b'./configure', b'--prefix', b'$(PWD)/target', b'--with-pydebug']
 environment:
  DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
  DEBUGINFOD_URLS=https://debuginfod.ubuntu.com 
  HOME=/home/ubuntu
  LANG=C.UTF-8
  LESSCLOSE=/usr/bin/lesspipe %s %s
  LESSOPEN=| /usr/bin/lesspipe %s
  LOGNAME=ubuntu
  LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:
  PATH=/home/ubuntu/.local/bin:/usr/local/bin:/home/ubuntu/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
  PWD=/home/ubuntu/buildarea/3.12.onder-riscv64/build
  SHELL=/bin/bash
  SHLVL=1
  SSH_CLIENT=192.168.1.117 45138 22
  SSH_CONNECTION=192.168.1.117 45138 192.168.1.11 22
  SSH_TTY=/dev/pts/0
  TERM=xterm-256color
  USER=ubuntu
  XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
  XDG_RUNTIME_DIR=/run/user/1000
  XDG_SESSION_CLASS=user
  XDG_SESSION_ID=1
  XDG_SESSION_TYPE=tty
  _=/usr/bin/buildbot-worker
 using PTY: False
```

[Tests:](https://buildbot.python.org/all/#/builders/1376/builds/53/steps/5/logs/stdio)
```sh
make buildbottest 'TESTOPTS=-j2 --junit-xml test-results.xml -j4 ${BUILDBOT_TESTOPTS}' TESTPYTHONOPTS= TESTTIMEOUT=1200
 in dir /home/ubuntu/buildarea/3.12.onder-riscv64/build (timeout 1800 secs) (maxTime 14400 secs)
 watching logfiles {}
 argv: [b'make', b'buildbottest', b'TESTOPTS=-j2 --junit-xml test-results.xml -j4 ${BUILDBOT_TESTOPTS}', b'TESTPYTHONOPTS=', b'TESTTIMEOUT=1200']
 environment:
  DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
  DEBUGINFOD_URLS=https://debuginfod.ubuntu.com 
  HOME=/home/ubuntu
  LANG=C.UTF-8
  LESSCLOSE=/usr/bin/lesspipe %s %s
  LESSOPEN=| /usr/bin/lesspipe %s
  LOGNAME=ubuntu
  LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:
  PATH=/home/ubuntu/.local/bin:/usr/local/bin:/home/ubuntu/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
  PWD=/home/ubuntu/buildarea/3.12.onder-riscv64/build
  SHELL=/bin/bash
  SHLVL=1
  SSH_CLIENT=192.168.1.117 45138 22
  SSH_CONNECTION=192.168.1.117 45138 192.168.1.11 22
  SSH_TTY=/dev/pts/0
  TERM=xterm-256color
  USER=ubuntu
  XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
  XDG_RUNTIME_DIR=/run/user/1000
  XDG_SESSION_CLASS=user
  XDG_SESSION_ID=1
  XDG_SESSION_TYPE=tty
  _=/usr/bin/buildbot-worker
 using PTY: False
```

Output:
```sh
0:51:52 load avg: 36.33 [437/488] test_eof passed -- running (3): test_math (16 min 22 sec), test.test_multiprocessing_forkserver.test_processes (3 min 55 sec), test_tools (20 min 8 sec)
Warning -- regrtest worker thread failed: Traceback (most recent call last):
Warning --   File "/home/ubuntu/buildarea/3.12.onder-riscv64/build/Lib/test/support/__init__.py", line 197, in _force_run
Warning --     return func(*args)
Warning --            ^^^^^^^^^^^
Warning -- OSError: [Errno 39] Directory not empty: '/tmp/test_python_8uqlpn0m/tmp5h9be3ji'
Warning -- 
Warning -- During handling of the above exception, another exception occurred:
Warning -- 
Warning -- Traceback (most recent call last):
Warning --   File "/home/ubuntu/buildarea/3.12.onder-riscv64/build/Lib/test/libregrtest/run_workers.py", line 389, in run
Warning --     mp_result = self._runtest(test_name)
Warning --                 ^^^^^^^^^^^^^^^^^^^^^^^^
Warning --   File "/home/ubuntu/buildarea/3.12.onder-riscv64/build/Lib/test/libregrtest/run_workers.py", line 349, in _runtest
Warning --     retcode, tmp_files = self.run_tmp_files(worker_runtests,
Warning --                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning --   File "/home/ubuntu/buildarea/3.12.onder-riscv64/build/Lib/test/libregrtest/run_workers.py", line 289, in run_tmp_files
Warning --     os_helper.rmtree(tmp_dir)
Warning --   File "/home/ubuntu/buildarea/3.12.onder-riscv64/build/Lib/test/support/os_helper.py", line 448, in rmtree
Warning --     _rmtree(path)
Warning --   File "/home/ubuntu/buildarea/3.12.onder-riscv64/build/Lib/test/support/os_helper.py", line 432, in _rmtree
Warning --     _rmtree_inner(path)
Warning --   File "/home/ubuntu/buildarea/3.12.onder-riscv64/build/Lib/test/support/os_helper.py", line 429, in _rmtree_inner
Warning --     _force_run(path, os.rmdir, fullname)
Warning --   File "/home/ubuntu/buildarea/3.12.onder-riscv64/build/Lib/test/support/__init__.py", line 208, in _force_run
Warning --     return func(*args)
Warning --            ^^^^^^^^^^^
Warning -- OSError: [Errno 39] Directory not empty: '/tmp/test_python_8uqlpn0m/tmp5h9be3ji'
Kill <WorkerThread #1 running test=test_unicode pid=1130692 time=417 ms> process group
Kill <WorkerThread #2 running test=test_math pid=1123005 time=16 min 23 sec> process group
Kill <WorkerThread #3 running test=test.test_multiprocessing_forkserver.test_processes pid=1126560 time=3 min 55 sec> process group
== Tests result: FAILURE, WORKER BUG ==
10 slowest tests:
- test_json: 19 min 32 sec
- test_capi: 7 min 5 sec
- test_lib2to3: 6 min 19 sec
- test_tokenize: 6 min 17 sec
- test_unparse: 6 min 13 sec
- test_peg_generator: 4 min 40 sec
- test_regrtest: 4 min 22 sec
- test_compileall: 4 min 20 sec
- test_tarfile: 3 min 32 sec
- test_venv: 3 min 27 sec
51 tests omitted:
    test.test_asyncio.test_base_events
    test.test_asyncio.test_eager_task_factory
    test.test_asyncio.test_events test.test_asyncio.test_sendfile
    test.test_asyncio.test_timeouts
    test.test_concurrent_futures.test_wait
    test.test_future_stmt.test_future test.test_gdb.test_cfunction
    test.test_inspect.test_inspect
    test.test_multiprocessing_forkserver.test_processes
    test.test_multiprocessing_forkserver.test_threads
    test.test_multiprocessing_spawn.test_processes test_bdb
    test_bisect test_code_module test_codecencodings_iso2022
    test_codecmaps_tw test_dbm test_dynamicclassattribute
    test_exception_hierarchy test_exception_variations test_fstring
    test_hashlib test_heapq test_httpservers test_io test_ioctl
    test_listcomps test_lltrace test_math test_opcache test_opcodes
    test_perf_profiler test_pkg test_pkgutil test_pyexpat test_richcmp
    test_shutil test_socket test_ssl test_startfile test_strftime
    test_time test_tools test_ttk_textonly test_type_annotations
    test_unicode test_unicodedata test_userstring test_weakref
    test_yield_from
10 tests skipped:
    test.test_asyncio.test_windows_events
    test.test_asyncio.test_windows_utils test_devpoll test_kqueue
    test_launcher test_msilib test_winconsoleio test_winreg
    test_winsound test_wmi
4 tests skipped (resource denied):
    test_tix test_tkinter test_ttk test_zipfile64
1 test failed:
    <regrtest worker>
423 tests OK.
0:51:53 load avg: 36.33 Re-running 1 failed tests in verbose mode in subprocesses
0:51:53 load avg: 36.33 Run 1 test in parallel using 1 worker process (timeout: 20 min, worker timeout: 25 min)
0:51:54 load avg: 33.50 [1/1/1] <regrtest worker> failed (uncaught exception)
Re-running <regrtest worker> in verbose mode
test <regrtest worker> crashed -- Traceback (most recent call last):
  File "/home/ubuntu/buildarea/3.12.onder-riscv64/build/Lib/test/libregrtest/single.py", line 178, in _runtest_env_changed_exc
    _load_run_test(result, runtests)
  File "/home/ubuntu/buildarea/3.12.onder-riscv64/build/Lib/test/libregrtest/single.py", line 125, in _load_run_test
    test_mod = importlib.import_module(module_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/buildarea/3.12.onder-riscv64/build/Lib/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'test.<regrtest worker>'
1 test failed again:
    <regrtest worker>
== Tests result: FAILURE, WORKER BUG then FAILURE, WORKER BUG ==
10 slowest tests:
- test_json: 19 min 32 sec
- test_capi: 7 min 5 sec
- test_lib2to3: 6 min 19 sec
- test_tokenize: 6 min 17 sec
- test_unparse: 6 min 13 sec
- test_peg_generator: 4 min 40 sec
- test_regrtest: 4 min 22 sec
- test_compileall: 4 min 20 sec
- test_tarfile: 3 min 32 sec
- test_venv: 3 min 27 sec
10 tests skipped:
    test.test_asyncio.test_windows_events
    test.test_asyncio.test_windows_utils test_devpoll test_kqueue
    test_launcher test_msilib test_winconsoleio test_winreg
    test_winsound test_wmi
4 tests skipped (resource denied):
    test_tix test_tkinter test_ttk test_zipfile64
1 re-run test:
    <regrtest worker>
1 test failed:
    <regrtest worker>
423 tests OK.
Total duration: 51 min 54 sec
Total tests: run=37,898 skipped=1,014
Total test files: run=435/488 failed=1 skipped=10 resource_denied=4 rerun=1
Result: FAILURE, WORKER BUG then FAILURE, WORKER BUG
make: *** [Makefile:2019: buildbottest] Error 2
program finished with exit code 2
elapsedTime=3124.124326
```

When I run the `test_regrtest` separately, all pass.
```
./python -m test test_regrtest --junit-xml test-resuls.xml -j4 --timeout 1200
Using random seed: 3667040113
0:00:00 load avg: 0.68 Run 1 test in parallel using 1 worker process (timeout: 20 min, worker timeout: 25 min)
0:00:30 load avg: 0.81 running (1): test_regrtest (30.0 sec)
0:01:00 load avg: 1.04 running (1): test_regrtest (1 min)
0:01:30 load avg: 1.02 running (1): test_regrtest (1 min 30 sec)
0:02:00 load avg: 1.14 running (1): test_regrtest (2 min)
0:02:30 load avg: 1.08 running (1): test_regrtest (2 min 30 sec)
0:03:00 load avg: 1.25 running (1): test_regrtest (3 min)
0:03:02 load avg: 1.71 [1/1] test_regrtest passed (3 min 1 sec)

== Tests result: SUCCESS ==

1 test OK.

Total duration: 3 min 2 sec
Total tests: run=113 skipped=2
Total test files: run=1/1
Result: SUCCESS
```

## Environment
```sh
uname -a
Linux starfive 6.1.31-starfive #1 SMP Mon Mar  4 21:31:49 CST 2024 riscv64 GNU/Linux
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by furkanonder** [comment]
The problem was solved by changing the buildbot operating system from DietPi to Ubuntu.
