### ISSUE TITLE
unittest.mock.patch of a subclass poisons base class

### ISSUE THREAD

**Issue by asottile-sentry** [python/cpython#117507]
# Bug report

### Bug description:

this is an entirely silly example boiled down from a much more complex one to demonstrate the behaviour.  the actual code here is nonsensical (Test2 will always fail) but Test1 should work just fine -- the decoration of the subclass `Test2` seems to also decorate `Test1`'s methods unexpectedly

```python
from unittest import mock

s = 0

@mock.patch(f"{__name__}.s", 5)
class Test1:
    def test_1(self):
        assert s == 5, s


@mock.patch(f"{__name__}.s", 2)
class Test2(Test1): pass

Test1().test_1()
```

```console
$ python3.12 t2.py
Traceback (most recent call last):
  File "/Users/asottile/workspace/sentry/t2.py", line 14, in <module>
    Test1().test_1()
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/mock.py", line 1387, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/asottile/workspace/sentry/t2.py", line 8, in test_1
    assert s == 5, s
AssertionError: 2
```

the problem appears to be here: https://github.com/python/cpython/blob/ea94b3b149eeadf33c2f7c46f16dcda0adc7cf4e/Lib/unittest/mock.py#L1412

whereas I think it should always return a new callable instead of mutating a potentially unrelated method

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-117665
* gh-117667
* gh-117687

**Comment by sobolevn** [comment]
Interesting, right now docs do not specify how `patch` should work for regular classes and its subclasses:

> Patch can be used as a TestCase class decorator. It works by decorating each test method in the class. This reduces the boilerplate code when your test methods share a common patchings set. [patch()](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch) finds tests by looking for method names that start with patch.TEST_PREFIX. By default this is 'test', which matches the way [unittest](https://docs.python.org/3/library/unittest.html#module-unittest) finds tests. You can specify an alternative prefix by setting patch.TEST_PREFIX.

There are no other promises.
Docs also do not specify how subclasses should behave.

There are also no tests that ensure any undocumented behavior (as far as I can find).

Source: https://github.com/python/cpython/blob/fc5f68e58ecfbc8c452e1c2f33a2a53d3f2d7ea2/Lib/unittest/mock.py#L1380-L1391

BUT! If you add `TestCase`, it is rather broken too:

```python
from unittest import mock, main, TestCase

s = 0

@mock.patch(f"{__name__}.s", 5)
class Test1(TestCase):
    def test_1(self):
        assert s == 5, s


@mock.patch(f"{__name__}.s", 2)
class Test2(Test1): pass

main()
```

Produces:

```
» ./python.exe ex.py
FF
======================================================================
FAIL: test_1 (__main__.Test1.test_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython2/Lib/unittest/mock.py", line 1420, in patched
    return func(*newargs, **newkeywargs)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython2/ex.py", line 8, in test_1
    assert s == 5, s
           ^^^^^^
AssertionError: 2

======================================================================
FAIL: test_1 (__main__.Test2.test_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython2/Lib/unittest/mock.py", line 1420, in patched
    return func(*newargs, **newkeywargs)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython2/ex.py", line 8, in test_1
    assert s == 5, s
           ^^^^^^
AssertionError: 2

----------------------------------------------------------------------
Ran 2 tests in 0.002s

FAILED (failures=2)
```

@asottile-sentry what's your opinion on that?

CC @cjw296

**Comment by asottile-sentry** [comment]
@sobolevn adding `TestCase` doesn't matter -- I factored it out in my minimal example (notice the call to `test_1` explicitly)

I don't really think it matters whether this is documented or not -- it's clearly broken

**Comment by blhsing** [comment]
@asottile-sentry What would you expect from running `Test2().test_1()`? Do you expect `Test2().test_1()` to behave differently from `Test1().test_1()`?

**Comment by blhsing** [comment]
@asottile-sentry I agree with your assessment that this should be considered a bug, since one should not expect the behavior of a method of a parent class to change just by decorating a child class. To avoid unnecessarily creating layers of wrappers I think it's best for the decorator to still retain the original logics of appending patchers to a list but only return a new callable when it's determined that the callable is inherited from a parent class.

I've gone ahead to create PR #117667, which has passed all tests.

**Comment by tirkarthi** [comment]
Related issue https://github.com/python/cpython/issues/93582
