### ISSUE TITLE
importlib.util._find_spec_from_path('__main__') fails

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#117742]
# Bug report

Module pyclbr cannot browse a file named `__main__` because it cannot get the spec.
```python
>>> from importlib import util
>>> util._find_spec_from_path('__init__')
ModuleSpec(name='__init__', loader=<_frozen_importlib_external.SourceFileLoader object at 0x000001C6C2462DB0>, origin='C:\\Programs\\Python313\\Lib\\idlelib\\__init__.py')
>>> util._find_spec_from_path('__main__')
Traceback (most recent call last):
  File "<pyshell#14>", line 1, in <module>
    util._find_spec_from_path('__main__')
  File "<frozen importlib.util>", line 67, in _find_spec_from_path
ValueError: __main__.__spec__ is None
```
This is 3.13.0a5 but same in prior versions.

**Comment by Xiaokang2022** [comment]
> perhaps changing the way IDLE is started can solve this problem.

FYI, on the Windows system, we changed the launch command of the shortcut to launch IDLE to the following:

```sh
\Python313\pythonw.exe -m idlelib
```

The preceding of Python313 in the path above does not need to be changed, and is omitted here.

At this point, running IDLE with this shortcut won't raise exception about `pyclbr`. This change is imperceptible to the user. I don't know if there are any other consequences of doing so, but it does solve the above problem on Windows.

**Comment by terryjreedy** [comment]
The current icon 'target' is `C:\Programs\Python314\pythonw.exe "C:\Programs\Python314\Lib\idlelib\idle.pyw`.  I presume you are suggesting changing to end with `-m idlelib`.  After reading the linked doc, I see why.

But I don't think this will properly resolve the issue, which is that find_spec treats `__main__` as a reserved *module* name, whereas as pyclbr needs to read the users `.../__main__.py`, which a user may be editing, not `idlelib/__main__.py`, which usually will be a different file.  I need to sleep, but I wonder if pyclbr really needs to use find_spec, especially if the file is being edited.
