### ISSUE TITLE
test_inspect: ValueError: no signature found for builtin <built-in function getobjects>

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#117907]
# Bug report

### Configuration:
```sh
./configure --with-trace-refs
```
### Tests
```python
./python -m test test_inspect
```
Output:
```python
sing random seed: 1177238287
0:00:00 load avg: 2.78 Run 1 test sequentially
0:00:00 load avg: 2.78 [1/1] test_inspect.test_inspect
test test_inspect.test_inspect failed -- Traceback (most recent call last):
  File "/home/arf/cpython/Lib/test/test_inspect/test_inspect.py", line 5261, in _test_module_has_signatures
    self.assertIsNotNone(inspect.signature(obj))
                         ~~~~~~~~~~~~~~~~~^^^^^
  File "/home/arf/cpython/Lib/inspect.py", line 3360, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                   globals=globals, locals=locals, eval_str=eval_str)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arf/cpython/Lib/inspect.py", line 3090, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
                                    follow_wrapper_chains=follow_wrapped,
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                    globals=globals, locals=locals, eval_str=eval_str)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arf/cpython/Lib/inspect.py", line 2605, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
                                   skip_bound_arg=skip_bound_arg)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arf/cpython/Lib/inspect.py", line 2395, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in function getobjects>

test_inspect.test_inspect failed (1 error)

== Tests result: FAILURE ==

1 test failed:
    test_inspect.test_inspect

Total duration: 947 ms
Total tests: run=330
Total test files: run=1/1 failed=1
Result: FAILURE
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-117922

**Comment by furkanonder** [comment]
Bisected to https://github.com/python/cpython/commit/c50cb6dd09d5a1bfdd1b896cc31ccdc96c72e561
cc @serhiy-storchaka
