### ISSUE TITLE
test.test_socket.GeneralModuleTests.test_sendall_interrupted: ZeroDivisionError not raised

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#118198]
# Bug report

### Bug description:

The problem is seen in a [buildbot](https://buildbot.python.org/all/#/builders/1376/builds/53).

[Configuration](https://buildbot.python.org/all/#/builders/1376/builds/90/steps/2/logs/stdio):
```sh
./configure --prefix '$(PWD)/target'
```

[Tests:](https://buildbot.python.org/all/#/builders/1376/builds/90/steps/7/logs/stdio)
```sh
./target/bin/python3.12 -Wdefault -bb -E -m test -rwW -uall -j2 --timeout=2400 -j4
```

Output:
```sh
======================================================================
FAIL: test_sendall_interrupted (test.test_socket.GeneralModuleTests.test_sendall_interrupted)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dietpi/buildarea/3.12.onder-riscv64.installed/build/target/lib/python3.12/test/test_socket.py", line 1708, in test_sendall_interrupted
    self.check_sendall_interrupted(False)
  File "/home/dietpi/buildarea/3.12.onder-riscv64.installed/build/target/lib/python3.12/test/test_socket.py", line 1693, in check_sendall_interrupted
    with self.assertRaises(ZeroDivisionError):
AssertionError: ZeroDivisionError not raised
======================================================================
FAIL: test_sendall_interrupted_with_timeout (test.test_socket.GeneralModuleTests.test_sendall_interrupted_with_timeout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dietpi/buildarea/3.12.onder-riscv64.installed/build/target/lib/python3.12/test/test_socket.py", line 1711, in test_sendall_interrupted_with_timeout
    self.check_sendall_interrupted(True)
  File "/home/dietpi/buildarea/3.12.onder-riscv64.installed/build/target/lib/python3.12/test/test_socket.py", line 1693, in check_sendall_interrupted
    with self.assertRaises(ZeroDivisionError):
AssertionError: ZeroDivisionError not raised
----------------------------------------------------------------------
Ran 726 tests in 92.562s
FAILED (failures=2, skipped=102)
test test_socket failed
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by furkanonder** [comment]
The issue was resolved using the following changes.
```sh
sudo sysctl -w net.core.rmem_default=65536
sudo sysctl -w net.core.rmem_max=16777216
sudo sysctl -w net.core.wmem_default=65536
sudo sysctl -w net.core.wmem_max=16777216
```
