### ISSUE TITLE
UnboundLocalError while running run_coroutine_threadsafe

### ISSUE THREAD

**Issue by Sirorezka** [python/cpython#118340]
Hello,

Could you please help me with the following error. I'm getting the exception in this lines when trying to use `run_coroutine_threadsafe` function.

https://github.com/python/cpython/blob/1d3392517698170e270eb7d847b6a8c28bfaca0f/Lib/asyncio/tasks.py#L993-L995

Exception message is the following.
`UnboundLocalError: local variable 'loop' referenced before assignment`

**What needs to be done**

Basically to fix this you need to add `nonlocal loop` in the `def callback()` function.
```python
    def callback():
        nonlocal loop
        try:
```

**How to reproduce the error**

The code that triggers an error:
```python
## hello.py

import asyncio
import threading
import time


async def coro_func():
    return await asyncio.sleep(3, 42)


def another_thread(_loop):
    coro = coro_func()  # is local thread coroutine which we would like to run in another thread

    # _loop is a loop which was created in another thread

    future = asyncio.run_coroutine_threadsafe(coro, _loop)
    print(f"{threading.current_thread().name}: {future.result()}")
    time.sleep(15)
    print(f"{threading.current_thread().name} is Finished")


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    main_th_cor = asyncio.sleep(10)
    # main_th_cor  is used to make loop busy with something until another_thread will not send coroutine to it
    print("START MAIN")
    x = threading.Thread(target=another_thread, args=(loop, ), name="Some_Thread")
    x.start()
    time.sleep(1)
    loop.run_until_complete(main_th_cor)
    print("FINISH MAIN")
```

**My runtime details**

**macOs 14.4.1 (23E224)**
Python 3.10.13
asyncio 3.4.3

Full error stack
```
Exception in thread Some_Thread:
Traceback (most recent call last):
  File "/Users/ivanpetrov/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/ivanpetrov/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ivanpetrov/codebase/deep_school_2_speed/hello.py", line 16, in another_thread
    print(f"{threading.current_thread().name}: {future.result()}")
  File "/Users/ivanpetrov/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 458, in result
Exception in callback run_coroutine_threadsafe.<locals>.callback() at /Users/ivanpetrov/.pyenv/versions/3.10.13/lib/python3.10/asyncio/tasks.py:882
handle: <Handle run_coroutine_threadsafe.<locals>.callback() at /Users/ivanpetrov/.pyenv/versions/3.10.13/lib/python3.10/asyncio/tasks.py:882>
Traceback (most recent call last):
  File "/Users/ivanpetrov/.pyenv/versions/3.10.13/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ivanpetrov/.pyenv/versions/3.10.13/lib/python3.10/asyncio/tasks.py", line 884, in callback
    futures._chain_future(ensure_future(coro, loop=loop), future)
UnboundLocalError: local variable 'loop' referenced before assignment
    return self.__get_result()
  File "/Users/ivanpetrov/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/ivanpetrov/.pyenv/versions/3.10.13/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ivanpetrov/.pyenv/versions/3.10.13/lib/python3.10/asyncio/tasks.py", line 884, in callback
    futures._chain_future(ensure_future(coro, loop=loop), future)
UnboundLocalError: local variable 'loop' referenced before assignment
```

**Comment by JelleZijlstra** [comment]
I can't reproduce this. The code you post can't be the full repro case, because your stacktrace includes this file too:

```
  File "/Users/ivanpetrov/codebase/deep_school_2_speed/hello.py", line 16, in another_thread
    print(f"{threading.current_thread().name}: {future.result()}")
```

Your proposed fix is unnecessary because the inner function doesn't write to the `loop` variable, so it doesn't need an explicit `nonlocal` declaration.

**Comment by Sirorezka** [comment]
Hello @JelleZijlstra thx for quick response. `hello.py` is the code that I've shared above in the question (edited my question to reflect this) - `hello.py` is the simple case where event loop is passed to the new thread.

**Comment by Sirorezka** [comment]
Ah, sorry, checked the code again - error was on my side. I'll close the issue.
