### ISSUE TITLE
REPL: Ctrl-R and arrow key trips assertion

### ISSUE THREAD

**Issue by barneygale** [python/cpython#118682]
# Bug report

Seen in `main` / b4bdf83cc67434235d9630c92c84a5261992b235 on Linux

1. Open the Python REPL
2. Press Ctrl-R to pull up the `(r-search )` prompt
3. Press any arrow key

```python
(r-search `') Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/barney/projects/cpython/Lib/_pyrepl/__main__.py", line 47, in <module>
    interactive_console()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/barney/projects/cpython/Lib/_pyrepl/__main__.py", line 44, in interactive_console
    return run_interactive(mainmodule)
  File "/home/barney/projects/cpython/Lib/_pyrepl/simple_interact.py", line 140, in run_multiline_interactive_console
    statement = multiline_input(more_lines, ps1, ps2)
  File "/home/barney/projects/cpython/Lib/_pyrepl/readline.py", line 301, in multiline_input
    return reader.readline()
           ~~~~~~~~~~~~~~~^^
  File "/home/barney/projects/cpython/Lib/_pyrepl/reader.py", line 646, in readline
    self.handle1()
    ~~~~~~~~~~~~^^
  File "/home/barney/projects/cpython/Lib/_pyrepl/reader.py", line 629, in handle1
    self.do_cmd(cmd)
    ~~~~~~~~~~~^^^^^
  File "/home/barney/projects/cpython/Lib/_pyrepl/reader.py", line 570, in do_cmd
    assert isinstance(cmd[0], str)
           ~~~~~~~~~~^^^^^^^^^^^^^
AssertionError
```

### Linked PRs
* gh-118709

**Comment by savannahostrowski** [comment]
I can also repro this on an M3 Mac

**Comment by lysnikolaou** [comment]
Fixed in https://github.com/python/cpython/pull/118709.
