### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'is_absolute' " occurs when building 3.13.0 beta 1 from source on Windows

### ISSUE THREAD

**Issue by i-shenl** [python/cpython#118876]
# Bug report

### Bug description:

The above error occurs when building python 3.13 beta 1 from source on Windows. Have determined that ns.temp not being defined before its is_absolute() method is invoked. Below is the full trace of the AttributeError. Will submit a PR with a patch that is working for me. 

```pytb
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\builds\sources\1\Python-3.13.0b1\PC\layout\__main__.py", line 14, in <module>

    sys.exit(int(main() or 0))

                 ~~~~^^

  File "C:\builds\sources\1\Python-3.13.0b1\PC\layout\main.py", line 606, in main

    if not ns.temp.is_absolute():

           ^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'is_absolute'
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-118880
* gh-118994
* gh-118995

**Comment by zooba** [comment]
Thank you!
