### ISSUE TITLE
"Windows fatal Exception: access violation" while testing 3.13.0b1 free-threading build (related to tkinter ?)

### ISSUE THREAD

**Issue by stonebig** [python/cpython#118973]
# Crash report

### What happened?

doing pytest on my github repository ["sqlite-bro"](https://github.com/stonebig/sqlite_bro) , with Python-3.13.0b1 augmented per:
- "with free-threading binaries download"  option checked
- tempfile.py patched with "_os.mkdir(file)" (zooba magic potion)
- python3.13t.exe renamed python.exe  
- pythonw3.13t.exe renamed pythonw.exe

I get a crash
<details>

```text
C:\Users\stonebig\Documents\GitHub\sqlite_bro>pytest
====================================================================== test session starts =======================================================================
platform win32 -- Python 3.13.0b1, pytest-8.2.0, pluggy-1.5.0
rootdir: C:\Users\stonebig\Documents\GitHub\sqlite_bro
configfile: pyproject.toml
collecting ... Windows fatal exception: access violation

Current thread 0x00006b84 (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1315 in create_module
  File "<frozen importlib._bootstrap>", line 813 in module_from_spec
  File "<frozen importlib._bootstrap>", line 921 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\tkinter\__init__.py", line 38 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1021 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\stonebig\Documents\GitHub\sqlite_bro\sqlite_bro\sqlite_bro.py", line 23 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1021 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1415 in _handle_fromlist
  File "C:\Users\stonebig\Documents\GitHub\sqlite_bro\sqlite_bro\tests\test_general.py", line 7 in <module>
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\assertion\rewrite.py", line 178 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 1387 in _gcd_import
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\importlib\__init__.py", line 88 in import_module
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\pathlib.py", line 591 in import_path
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\python.py", line 487 in importtestmodule
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\python.py", line 540 in _getobj
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\python.py", line 282 in obj
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\python.py", line 556 in _register_setup_module_fixture
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\python.py", line 543 in collect
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\runner.py", line 389 in collect
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\runner.py", line 341 in from_call
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\runner.py", line 391 in pytest_make_collect_report
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\pluggy\_callers.py", line 103 in _multicall
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\pluggy\_manager.py", line 120 in _hookexec
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\pluggy\_hooks.py", line 513 in __call__
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\runner.py", line 565 in collect_one_node
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\main.py", line 837 in _collect_one_node
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\main.py", line 974 in genitems
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\main.py", line 979 in genitems
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\main.py", line 979 in genitems
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\main.py", line 979 in genitems
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\main.py", line 811 in perform_collect
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\main.py", line 349 in pytest_collection
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\pluggy\_callers.py", line 103 in _multicall
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\pluggy\_manager.py", line 120 in _hookexec
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\pluggy\_hooks.py", line 513 in __call__
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\main.py", line 338 in _main
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\main.py", line 285 in wrap_session
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\main.py", line 332 in pytest_cmdline_main
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\pluggy\_callers.py", line 103 in _multicall
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\pluggy\_manager.py", line 120 in _hookexec
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\pluggy\_hooks.py", line 513 in __call__
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\config\__init__.py", line 178 in main
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\site-packages\_pytest\config\__init__.py", line 206 in console_main
  File "C:...\WPy64-31300b1\python-3.13.0b1.amd64\Scripts\pytest.exe\__main__.py", line 7 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main
```

</details>

on 3.13.0b1 patched the same but not Free-threading all seems ok
<details>

```text
================================================= test session starts =================================================
platform win32 -- Python 3.13.0b1, pytest-8.2.0, pluggy-1.5.0
rootdir: C:\Users\stonebig\Documents\GitHub\sqlite_bro
configfile: pyproject.toml
collected 3 items

sqlite_bro\tests\test_general.py ...                                                                             [100%]

================================================== 3 passed in 0.76s ==================================================
```

</details>

I did that test because IDLE doesn't want to start and doesn't say why.
Package set used:

```
Package         Version      Summary
_______________ ____________ ______________________________________________________________________
build           1.1.1        A simple, correct Python build frontend
colorama        0.4.6        Cross-platform colored terminal text.
iniconfig       2.0.0        brain-dead simple config-ini parsing
packaging       23.2         Core utilities for Python packages
pip             24.0         The PyPA recommended tool for installing Python packages.
pluggy          1.5.0        plugin and hook calling mechanisms for python
pyproject-hooks 1.0.0        Wrappers to call pyproject.toml-based build backend hooks.
pytest          8.2.0        pytest: simple powerful testing with Python
setuptools      69.2.0       Easily download, build, install, upgrade, and uninstall Python package
sqlite-bro      0.13.1       a graphic SQLite Client in 1 Python file
wheel           0.43.0       A built-package format for Python
winpython       8.0.20240512 WinPython distribution tools, including WPPM
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### Output from running 'python -VV' on the command line:

Python 3.13.0b1 (tags/v3.13.0b1:2268289, May  8 2024, 12:31:50) [MSC v.1938 64 bit (AMD64)]

### Linked PRs
* gh-126768
* gh-126867

**Comment by stonebig** [comment]
maybe related to this still missing piece ?  https://github.com/colesbury/nogil-3.12/commit/78825e0508
![image](https://github.com/python/cpython/assets/4312421/13ba1d2d-04d2-48bb-b980-be1cb503e932)

**Comment by KRRT7** [comment]
simply importing 
```py
from tkinter.filedialog import askopenfile
```
crashes 3.13t for me, which is imported in the sqlite_bro project. hope this helps narrow down the issue.

**Comment by stonebig** [comment]
By the look of current early state of free-threading, we may assume the tkinter/free-threading is rather a 2025 question, with uncertain fate.

**Comment by mishaturnbull** [comment]
+1 for this happening on Windows only, version 3.13.0 (non-beta, release day build).  I see exactly the same error as @python-zhong when running `python3.13t.exe -m tkinter` under WinDbg (no pytest involved).  I tested the same command on a Debian platform (compiled the same 3.13.0 tag), and it worked flawlessly.  Don't have a mac to test on, unfortunately.

**Comment by colesbury** [comment]
@zooba The official Windows installer (with free-threading binaries) only includes a `Python313\DLLs\_tkinter.pyd`. There's no `_tkinter.cp313t-win_amd64`, so importing `tkinter` in `py -3.13t` crashes as it tries to load an incompatible extension.

Do you know why that's happening?

**Comment by terryjreedy** [comment]
As noted in https://github.com/python/cpython/issues/125179#issuecomment-2402681892, I have run tkinter and IDLE on debug +  free-threading builds since last March.  But I never tried the installers.  Of course, PCbuild/amd64 has a full set of _xyz_d.cp314t-win_amd64.ext files.  I'm sorry I did not notice this issue before.

**Comment by mishaturnbull** [comment]
Yep, figured out the free-threading build on the same Windows box (sorry about the delay, Visual Studio noob), and when compiled locally `tkinter` operates flawlessly on free-threading.

Admittedly, I've just compiled Cpython for the first time yesterday -- but, if this is simple to fix, I'd be happy to submit a PR for it if that would help?

**Comment by zooba** [comment]
> The official Windows installer (with free-threading binaries) only includes a `Python313\DLLs\_tkinter.pyd`. There's no `_tkinter.cp313t-win_amd64`

Yeah, looks like I copied the list of extensions from the `lib` package but not the `tcltk` package. Easy enough to add it in, I'll get it

**Comment by leycec** [comment]
**Necrobump.** I just hit something like this at @beartype. For unknown reasons,  @beartype's `pytest` test suite [fails with a similar inscrutable threading error in Python `3.13.0` under the GitHub Actions Windows runner](https://github.com/beartype/beartype/actions/runs/11985049286/job/33416513391):

```python
============================= test session starts =============================
platform win32 -- Python 3.13.0, pytest-8.3.3, pluggy-1.5.0 -- D:\a\beartype\beartype\.tox\py313-coverage\Scripts\python.exe
cachedir: .tox\py313-coverage\.pytest_cache
rootdir: D:\a\beartype\beartype
configfile: pytest.ini
plugins: anyio-4.6.2.post1, typeguard-4.4.1
Windows fatal exception: access violation

Current thread 0x00001508 (most recent call first):
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\numpy\core\getlimits.py", line 52 in __init__
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\numpy\core\getlimits.py", line 230 in _register_known_types
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\numpy\__init__.py", line 235 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1022 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\outcomes.py", line 281 in importorskip
  File "D:\a\beartype\beartype\beartype_test\_util\mark\pytskip.py", line 468 in _skip_if_callable_raises_exception
  File "D:\a\beartype\beartype\beartype_test\_util\mark\pytskip.py", line 402 in skip_unless_module
  File "D:\a\beartype\beartype\beartype_test\_util\mark\pytskip.py", line 352 in skip_unless_package
  File "D:\a\beartype\beartype\beartype_test\a00_unit\a40_api\test_api_cave.py", line 707 in <module>
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\assertion\rewrite.py", line 184 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 1387 in _gcd_import
  File "C:\hostedtoolcache\windows\Python\3.13.0\x64\Lib\importlib\__init__.py", line 88 in import_module
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\pathlib.py", line 582 in import_path
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\python.py", line 493 in importtestmodule
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\python.py", line 546 in _getobj
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\python.py", line 284 in obj
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\python.py", line 562 in _register_setup_module_fixture
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\python.py", line 549 in collect
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\runner.py", line 389 in collect
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\runner.py", line 341 in from_call
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\runner.py", line 391 in pytest_make_collect_report
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\pluggy\_callers.py", line 103 in _multicall
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\pluggy\_manager.py", line 120 in _hookexec
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\pluggy\_hooks.py", line 513 in __call__
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\runner.py", line 567 in collect_one_node
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\main.py", line 835 in _collect_one_node
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\main.py", line 970 in genitems
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\main.py", line 975 in genitems
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\main.py", line 975 in genitems
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\main.py", line 975 in genitems
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\main.py", line 975 in genitems
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\main.py", line 809 in perform_collect
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\main.py", line 347 in pytest_collection
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\pluggy\_callers.py", line 103 in _multicall
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\pluggy\_manager.py", line 120 in _hookexec
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\pluggy\_hooks.py", line 513 in __call__
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\main.py", line 336 in _main
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\main.py", line 283 in wrap_session
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\main.py", line 330 in pytest_cmdline_main
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\pluggy\_callers.py", line 103 in _multicall
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\pluggy\_manager.py", line 120 in _hookexec
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\pluggy\_hooks.py", line 513 in __call__
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\config\__init__.py", line 175 in main
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\_pytest\config\__init__.py", line 201 in console_main
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\pytest\__main__.py", line 9 in <module>
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\coverage\execfile.py", line 208 in run
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\coverage\cmdline.py", line 858 in do_run
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\coverage\cmdline.py", line 681 in command_line
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\coverage\cmdline.py", line 970 in main
  File "D:\a\beartype\beartype\.tox\py313-coverage\Lib\site-packages\coverage\__main__.py", line 10 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main
collecting ... py313-coverage: exit 3221225477 (3.11 seconds) D:\a\beartype\beartype\.tox\py313-coverage\tmp> D:\a\beartype\beartype\.tox\py313-coverage\Scripts\python.exe -m coverage run -m pytest --maxfail=1 -p no:asyncio -p no:xvfb D:\a\beartype\beartype pid=1876
.pkg: _exit> python C:\hostedtoolcache\windows\Python\3.13.0\x64\Lib\site-packages\pyproject_api\_backend.py True hatchling.build
Exception ignored on threading shutdown:
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.13.0\x64\Lib\threading.py", line 1524, in _shutdown
    if _main_thread._handle.is_done() and _is_main_interpreter():
SystemError: <method 'is_done' of '_thread._ThreadHandle' objects> returned a result with an exception set
  py313-coverage: FAIL code 3221225477 (376.20=setup[372.55]+cmd[0.01,0.52,3.11] seconds)
  evaluation failed :( (376.30 seconds)
```

Tkinter doesn't appear to be implicated here. Threading, however, does.

Does the GitHub Actions Windows runner actually ship a free-threading build of Python 3.13? That... would be super-weird. Since I can't meaningfully parse the above stacktrace, I'm reluctantly blacklisting the Python 3.13 + Windows combo in our build matrix. Weep for @beartype's QA, GitHub! :sob:

**Comment by colesbury** [comment]
>Does the GitHub Actions Windows runner actually ship a free-threading build of Python 3.13?

No it doesn't.

The error message:

> SystemError: <method 'is_done' of '_thread._ThreadHandle' objects> returned a result with an exception set

Looks the same as in https://github.com/python/cpython/issues/125842, which is fixed in the upcoming 3.13.1 release.

**Comment by leycec** [comment]
**Wondressness!** Thanks so much for the heads up, @colesbury. Google came up surprisingly empty when I grepped that `SystemError`. I can now rest easy knowing that someone smarter than me has fixed something I don't understand. :smile:

**Comment by colesbury** [comment]
I think this is fixed now.

**Comment by stonebig** [comment]
indeed... Free-threading is working now on this test, in 3.14.0a6
