### ISSUE TITLE
OOM a potential denial of service in the CGI server on Windows

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#119452]
When `http.server.CGIHTTPRequestHandler` on Windows (and other platforms without `fork()`) handles the POST request, it reads the whole body of the POST request in memory before sending it to the subprocess running the script. The underlying SocketIO allocates the amount of memory specified in the `Content-Length` header before actual reading the data, so a small request with incorrect `Content-Length` can cause consumption of the large amount of memory and CPU time and can be used in the DOS attack on the server.

### Linked PRs
* gh-119455
* gh-142130
* gh-142131
* gh-142132
* gh-142133
* gh-142176
* gh-142178
* gh-142180
* gh-142181
* gh-142184
* gh-142185
* gh-142216
* gh-142296
* gh-142297
* gh-142298
* gh-142299

**Comment by picnixz** [comment]
Correct me if I'm wrong, but the incriminated lines are the following right:

https://github.com/python/cpython/blob/c85e3526736d1cf8226686fdf4f5117e105a7b13/Lib/http/server.py#L1226-L1227

If so, could I perhaps take on this one? (I never directly contributed to CPython so I think I can take this one to setup everything that's needed, unless you are already working on it).

**Comment by serhiy-storchaka** [comment]
Thank you for volunteering @picnixz, but I already have a solution. I have been somewhat delayed in publishing it because I discovered other problem: the large body was truncated on Windows, because `SocketIO.read()` is unbuffered and can return a partial data.

**Comment by picnixz** [comment]
No worries! I think you are much faster than me on that since I'm not really familiar with the http and IO-related codebase.

**Comment by cmaloney** [comment]
Given this code has been removed for 3.15 (gh-133810), do we need to fix this on older versions or can we close this issue?

**Comment by picnixz** [comment]
Yes we need because those versions are still supported from a security perspective. So only 3.9-3.14 fixes.

**Comment by gpshead** [comment]
@colesbury flagged a buildbot failure - https://github.com/python/cpython/pull/119455#issuecomment-3600324733

looks like the select is non-blocking rather than blocking when we still needed more data.  https://github.com/python/cpython/pull/119455/files#r2580013415

**Comment by vstinner** [comment]
The test is a little bit fragile. Example of failure on "AMD64 FreeBSD Refleaks 3.13" buildbot: https://buildbot.python.org/#/builders/1615/builds/1722

```
ERROR: test_large_content_length_truncated (test.test_httpservers.CGIHTTPServerTestCase.test_large_content_length_truncated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/buildbot/buildarea/3.13.ware-freebsd.refleak/build/Lib/test/test_httpservers.py", line 1028, in test_large_content_length_truncated
    res = self.request('/cgi-bin/file1.py', 'POST', b'x', headers)
  File "/buildbot/buildarea/3.13.ware-freebsd.refleak/build/Lib/test/test_httpservers.py", line 89, in request
    return self.connection.getresponse()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/buildbot/buildarea/3.13.ware-freebsd.refleak/build/Lib/http/client.py", line 1450, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/buildbot/buildarea/3.13.ware-freebsd.refleak/build/Lib/http/client.py", line 336, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/buildbot/buildarea/3.13.ware-freebsd.refleak/build/Lib/http/client.py", line 297, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/buildbot/buildarea/3.13.ware-freebsd.refleak/build/Lib/socket.py", line 723, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
ConnectionResetError: [Errno 54] Connection reset by peer
```

One explanation is the hardcoded timeout of 1 ms in the test:

```py
with support.swap_attr(self.request_handler, 'timeout', 0.001):
```

This timeout is too low if the machine running the test has high system load.

For example, `./python -m test test_httpservers -v -m test_large_content_length_truncated -F -j10` fails quickly.
