### ISSUE TITLE
Improve ``NameError`` message when non-mangled name exists in the global scope

### ISSUE THREAD

**Issue by PC-Killer** [python/cpython#119901]
# Bug report

### Bug description:

Here is the code:
```python
def __a():
    print("A")


class A:
    def b(self):
        __a()


a = A()
a.b()

```
It was expected to show a short message "A". However, I got a NameError:
```python
❯ python3.12 bug\ represent.py
Traceback (most recent call last):
  File "/home/PC-Killer/python_work/Demos/bug represent.py", line 11, in <module>
    a.b()
  File "/home/PC-Killer/python_work/Demos/bug represent.py", line 7, in b
    __a()
    ^^^
NameError: name '_A__a' is not defined
❯ python3.13 bug\ represent.py
Traceback (most recent call last):
  File "/home/PC-Killer/python_work/Demos/bug represent.py", line 11, in <module>
    a.b()
    ~~~^^
  File "/home/PC-Killer/python_work/Demos/bug represent.py", line 7, in b
    __a()
    ^^^
NameError: name '_A__a' is not defined
```
It seems that the name had been translated in an unexpected way.

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
This is intended behaviour. Explanation: https://docs.python.org/3.12/faq/programming.html#i-try-to-use-spam-and-i-get-an-error-about-someclassname-spam.

**Comment by PC-Killer** [comment]
Hmm...... But I'm trying to call a function outside the class. Why should it "mangled"? Shouldn't it happen only I am trying to get a class method?
&nbsp;


Anonymous
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kirill ***@***.***&gt;; 
发送时间: 2024年6月1日(星期六) 晚上7:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [python/cpython] Unexpected NameError (Issue #119901)














 
This is intended behaviour. Explanation: https://docs.python.org/3.12/faq/programming.html#i-try-to-use-spam-and-i-get-an-error-about-someclassname-spam.

**Comment by Eclips4** [comment]
> Hmm...... But I'm trying to call a function outside the class. Why should it "mangled"? Shouldn't it happen only I am trying to get a class method?

In an ideal world, yes. But how do we determine that some lookups inside the class body are class-specific? These slow down performance due to additional lookups and just slightly increase user experience. To summarize, just don't name your functions with double leading underscores. :)

**Comment by PC-Killer** [comment]
That's perhaps the best solution:) But, could the interpreter tell the user the problem when it show the error? I don't think showing error needs to be as fast as possible :)&nbsp;


Anonymous
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kirill ***@***.***&gt;; 
发送时间: 2024年6月1日(星期六) 晚上7:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [python/cpython] Unexpected NameError (Issue #119901)














  
Hmm...... But I'm trying to call a function outside the class. Why should it "mangled"? Shouldn't it happen only I am trying to get a class method?
  
In an ideal world, yes. But how do we determine that some lookups inside the class body are class-specific? These slow down performance due to additional lookups and just slightly increase user experience. To summarize, just don't name your functions with double leading underscores. :)

**Comment by Eclips4** [comment]
> That's perhaps the best solution:) But, could the interpreter tell the user the problem when it show the error? I don't think showing error needs to be as fast as possible :)

Yes, that's sounds reasonable for me.

**Comment by Eclips4** [comment]
cc @pablogsal Do you think it's worth improving the error message for "NameError" in such cases?

**Comment by pablogsal** [comment]
I can take a look this weekend 👍

**Comment by SweetyAngel** [comment]
I want to extend this issue.
This code:
```python
def __a():
    print("A")


class A:
    def b(self):
        self.__a()


a = A()
a.b()
```
throws an error:
```python
AttributeError: 'A' object has no attribute '_A__a'
```

If NameError is planning to be improved, this should be also fixed

**Comment by pablogsal** [comment]
Yeah they normally go in tandem. I will let you know what we decide here once I have some time to play with this
