### ISSUE TITLE
Python 3.13 beta 2 fails to build when --enable-experimental-jit is attempted -- FIXED

### ISSUE THREAD

**Issue by wbeebe** [python/cpython#120275]
# Bug report

### Environment:
Linux Mint 21.3 x86_64
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### Configure Invocation:
../Python-3.13.0b2/configure --enable-optimizations --disable-gil --enable-experimental-jit

### Compilation Error Messages:
```python
==========================================================
JIT support for x86_64-pc-linux-gnu is still experimental!
         Please report any issues you encounter.          
==========================================================

  + Exception Group Traceback (most recent call last):
  |   File "/home/mint/Develop/build-python/../Python-3.13.0b2/Tools/jit/build.py", line 28, in <module>
  |     args.target.build(pathlib.Path.cwd(), comment=comment, force=args.force)
  |     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/mint/Develop/Python-3.13.0b2/Tools/jit/_targets.py", line 214, in build
  |     stencil_groups = asyncio.run(self._build_stencils())
  |   File "/usr/local/lib/python3.13/asyncio/runners.py", line 194, in run
  |     return runner.run(main)
  |            ~~~~~~~~~~^^^^^^
  |   File "/usr/local/lib/python3.13/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  |   File "/usr/local/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
  |     return future.result()
  |            ~~~~~~~~~~~~~^^
  |   File "/home/mint/Develop/Python-3.13.0b2/Tools/jit/_targets.py", line 189, in _build_stencils
  |     async with asyncio.TaskGroup() as group:
  |     ...<4 lines>...
  |             tasks.append(group.create_task(coro, name=opname))
  |   File "/usr/local/lib/python3.13/asyncio/taskgroups.py", line 154, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/mint/Develop/Python-3.13.0b2/Tools/jit/_targets.py", line 164, in _compile
    |     await _llvm.run("clang", args_ll, echo=self.verbose)
    |   File "/home/mint/Develop/Python-3.13.0b2/Tools/jit/_llvm.py", line 99, in run
    |     raise RuntimeError(f"Can't find {tool}-{_LLVM_VERSION}!")
    | RuntimeError: Can't find clang-18!
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/home/mint/Develop/Python-3.13.0b2/Tools/jit/_targets.py", line 164, in _compile
    |     await _llvm.run("clang", args_ll, echo=self.verbose)
    |   File "/home/mint/Develop/Python-3.13.0b2/Tools/jit/_llvm.py", line 99, in run
    |     raise RuntimeError(f"Can't find {tool}-{_LLVM_VERSION}!")
    | RuntimeError: Can't find clang-18!
    +------------------------------------
make[2]: *** [Makefile:3019: jit_stencils.h] Error 1
make[2]: Leaving directory '/home/mint/Develop/build-python'
make[1]: *** [Makefile:877: profile-gen-stamp] Error 2
make[1]: Leaving directory '/home/mint/Develop/build-python'
make: *** [Makefile:889: profile-run-stamp] Error 2
```

I've already built this beta without the GIL and it built and is working fine for my experimental purposes. I decided to rebuild with JIT enabled as well as the disabled GIL and this is what happened. This was just an attempt to experiment with Python with JIT enabled, so I'm not at all upset this happened. But it is interesting.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by aisk** [comment]
Hi, there is a README file for the JIT feature: https://github.com/python/cpython/blob/main/Tools/jit/README.md

According to it, you need install llvm18 before build Python with JIT.

**Comment by sobolevn** [comment]
Can you please provide more info about your system? What deps do you have (llvm / clang / etc)? What are their versions?

**Comment by erlend-aasland** [comment]
You need to install Clang 18 in order to build the JIT. See the README posted by AN.

**Comment by wbeebe** [comment]
I didn't see this until today. I'm in the process of doing a git pull from llvm and building the latest version of llvm/clang (llvm-project 18.1.7).

I'll try to build Python 3.13 with JIT enabled once I have llvm/clang 18 built.

I currently have 14.0.0 installed from Ubuntu 22.04, which isn't going to be any help at all.

**Comment by wbeebe** [comment]
I don't have the fastest machine, but still, the build has been going on for two hours now, and it's not finished yet.
![Screenshot from 2024-06-17 12-54-39](https://github.com/python/cpython/assets/4269487/78b11d91-3aed-48b4-864d-da36ddca79e6)

**Comment by wbeebe** [comment]
Finally finished building. Now to install and build Python 3.13 beta 2 again...

**Comment by wbeebe** [comment]
It failed again. Turns out I built clang/llvm version 19. So I give up. I'll try this later.

**Comment by wbeebe** [comment]
```
~ python
Python 3.13.0b2 experimental free-threading build (main, Jun 17 2024, 16:24:34) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> help('modules')

Please wait a moment while I gather a list of all available modules...

test_sqlite3: testing with SQLite version 3.37.2
__future__          _statistics         fcntl               readline
__hello__           _string             filecmp             reprlib
__phello__          _strptime           fileinput           resource
_abc                _struct             fnmatch             rlcompleter
_aix_support        _suggestions        fractions           runpy
_android_support    _symtable           ftplib              sched
_ast                _sysconfig          functools           secrets
_asyncio            _sysconfigdata__linux_x86_64-linux-gnu gc                  select
_bisect             _sysconfigdata_t_linux_x86_64-linux-gnu genericpath         selectors
_blake2             _testbuffer         getopt              shelve
_bz2                _testcapi           getpass             shlex
_codecs             _testclinic         gettext             shutil
_codecs_cn          _testclinic_limited glob                signal
_codecs_hk          _testexternalinspection graphlib            site
_codecs_iso2022     _testimportmultiple grp                 smtplib
_codecs_jp          _testinternalcapi   gzip                socket
_codecs_kr          _testlimitedcapi    hashlib             socketserver
_codecs_tw          _testmultiphase     heapq               sqlite3
_collections        _testsinglephase    hmac                sre_compile
_collections_abc    _thread             html                sre_constants
_colorize           _threading_local    http                sre_parse
_compat_pickle      _tkinter            idlelib             ssl
_compression        _tokenize           imaplib             stat
_contextvars        _tracemalloc        importlib           statistics
_csv                _typing             inspect             string
_ctypes             _uuid               io                  stringprep
_ctypes_test        _warnings           ipaddress           struct
_curses             _weakref            itertools           subprocess
_curses_panel       _weakrefset         json                symtable
_datetime           _xxtestfuzz         keyword             sys
_dbm                _zoneinfo           linecache           sysconfig
_decimal            abc                 locale              syslog
_elementtree        antigravity         logging             tabnanny
_functools          argparse            lzma                tarfile
_gdbm               array               mailbox             tempfile
_hashlib            ast                 marshal             termios
_heapq              asyncio             math                test
_imp                atexit              mimetypes           textwrap
_interpchannels     base64              mmap                this
_interpqueues       bdb                 modulefinder        threading
_interpreters       binascii            multiprocessing     time
_io                 bisect              netrc               timeit
_ios_support        builtins            ntpath              tkinter
_json               bz2                 nturl2path          token
_locale             cProfile            numbers             tokenize
_lsprof             calendar            opcode              tomllib
_lzma               cmath               operator            trace
_markupbase         cmd                 optparse            traceback
_md5                code                os                  tracemalloc
_multibytecodec     codecs              pathlib             tty
_multiprocessing    codeop              pdb                 turtle
_opcode             collections         pickle              turtledemo
_opcode_metadata    colorsys            pickletools         types
_operator           compileall          pip                 typing
_osx_support        concurrent          pkgutil             unicodedata
_pickle             configparser        platform            unittest
_posixshmem         contextlib          plistlib            urllib
_posixsubprocess    contextvars         poplib              uuid
_py_abc             copy                posix               venv
_pydatetime         copyreg             posixpath           warnings
_pydecimal          csv                 pprint              wave
_pyio               ctypes              profile             weakref
_pylong             curses              pstats              webbrowser
_pyrepl             dataclasses         pty                 wsgiref
_queue              datetime            pwd                 xml
_random             dbm                 py_compile          xmlrpc
_sha1               decimal             pyclbr              xxlimited
_sha2               difflib             pydoc               xxlimited_35
_sha3               dis                 pydoc_data          xxsubtype
_signal             doctest             pyexpat             zipapp
_sitebuiltins       email               python-config       zipfile
_socket             encodings           python-gdb          zipimport
_sqlite3            ensurepip           queue               zlib
_sre                enum                quopri              zoneinfo
_ssl                errno               random              
_stat               faulthandler        re                  

Enter any module name to get more help.  Or, type "modules spam" to search
for modules whose name or summary contain the string "spam".

>>> 
```
