### ISSUE TITLE
Python pickler unable to pickle object the native pickler can

### ISSUE THREAD

**Issue by apmorton** [python/cpython#120380]
# Bug report

### Bug description:

```python
import io
import pickle


class ZeroCopyByteArray(bytearray):
    def __reduce_ex__(self, protocol):
        return type(self), (pickle.PickleBuffer(self),), None


data = [
    ZeroCopyByteArray(),
    ZeroCopyByteArray(),
]

# this works
f = io.BytesIO()
pickler = pickle.Pickler(f, protocol=5)
pickler.dump(data)

# this hits memo assertion
f = io.BytesIO()
pickler = pickle._Pickler(f, protocol=5)
pickler.dump(data)
```

```pytb
Traceback (most recent call last):
  File "bug.py", line 24, in <module>
    pickler.dump(data)
  File "/pickle.py", line 487, in dump
    self.save(obj)
  File "/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/pickle.py", line 932, in save_list
    self._batch_appends(obj)
  File "/pickle.py", line 956, in _batch_appends
    save(x)
  File "/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/pickle.py", line 692, in save_reduce
    save(args)
  File "/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/pickle.py", line 887, in save_tuple
    save(element)
  File "/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/pickle.py", line 842, in save_picklebuffer
    self.save_bytearray(m.tobytes())
  File "/pickle.py", line 821, in save_bytearray
    self.memoize(obj)
  File "/pickle.py", line 508, in memoize
    assert id(obj) not in self.memo
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-120422
* gh-120832
* gh-120833

**Comment by picnixz** [comment]
I'd say it's not a bug because `pickle._Pickler` is private and should not be used directly. Why do you need the private one?

**Comment by aisk** [comment]
> I'd say it's not a bug because `pickle._Pickler` is private and should not be used directly. Why do you need the private one?

`pickle.Pickler` may be provided by `pickle._Pickler` if the native extension `_pickle` is not presented:

https://github.com/python/cpython/blob/42b25dd61ff3593795c4cc2ffe876ab766098b24/Lib/pickle.py#L1782

**Comment by picnixz** [comment]
Oh! yes, my bad! I'll hide my comment to reduce the noise!

**Comment by picnixz** [comment]
The ZeroCopyBytearray buffer appears to need the following implementation (it's actually in `Lib/test/pickletester`) but I confirmed that the issue remains but only if the buffer is empty (otherwise it's fine). The implementation is roughly

```python
class ZeroCopyBytearray(bytearray):
    def __reduce_ex__(self, protocol):
        if protocol >= 5:
            return type(self)._reconstruct, (pickle.PickleBuffer(self),), None
        else:
            return type(self)._reconstruct, (bytes(self),)

    @classmethod
    def _reconstruct(cls, obj):
        with memoryview(obj) as m:
            obj = m.obj
            if type(obj) is cls:
                # Zero-copy
                return obj
            else:
                return cls(obj)
```

So, the `__reduce_ex__` method makes more things than what you provided in your example, but it does not fix the issue at all.
