### ISSUE TITLE
JIT 3.13 job: test_logging: qemu_plugin_vcpu_init_hook: assertion failed: (success)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#121050]
3 test_logging tests are failing on AArch64 JIT job of the 3.13 branch:

* ERROR: test_111615 (test.test_logging.ConfigDictTest.test_111615)
* ERROR: test_config_queue_handler (test.test_logging.ConfigDictTest.test_config_queue_handler)
* ERROR: test_multiprocessing_queues (test.test_logging.ConfigDictTest.test_multiprocessing_queues)

Example: https://github.com/python/cpython/actions/runs/9652183693/job/26621991775

```
test_multiprocessing_queues (test.test_logging.ConfigDictTest.test_multiprocessing_queues) ...

** ERROR:../../plugins/core.c:221:qemu_plugin_vcpu_init_hook: assertion failed: (success)
Bail out! ERROR:../../plugins/core.c:221:qemu_plugin_vcpu_init_hook: assertion failed: (success)
aarch64-binfmt-P: ./include/qemu/rcu.h:101: rcu_read_unlock: Assertion `p_rcu_reader->depth != 0' failed.

ERROR

(...)

ERROR: test_multiprocessing_queues (test.test_logging.ConfigDictTest.test_multiprocessing_queues)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/test/test_logging.py", line 3937, in test_multiprocessing_queues
    q2 = MM().Queue()  # a proxy queue for use when pickling is needed
  File "/home/runner/work/cpython/cpython/Lib/multiprocessing/managers.py", line 729, in temp
    token, exp = self._create(typeid, *args, **kwds)
                 ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cpython/cpython/Lib/multiprocessing/managers.py", line 609, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/home/runner/work/cpython/cpython/Lib/multiprocessing/connection.py", line 525, in Client
    answer_challenge(c, authkey)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/runner/work/cpython/cpython/Lib/multiprocessing/connection.py", line 953, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/runner/work/cpython/cpython/Lib/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/runner/work/cpython/cpython/Lib/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
  File "/home/runner/work/cpython/cpython/Lib/multiprocessing/connection.py", line 395, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

(...)

Warning -- test_logging leaked temporary files (3): pymp-3d0tq8rv, pymp-crignnt_, pymp-ppx004wz
```

**Comment by vstinner** [comment]
cc @brandtbucher @ambv

**Comment by vstinner** [comment]
The error looks like: https://gitlab.com/qemu-project/qemu/-/issues/1147

> Recompiling with clang produces this crash instead: ... include/qemu/rcu.h:102: void rcu_read_unlock(void): Assertion 'p_rcu_reader->depth != 0' failed.

**Comment by brandtbucher** [comment]
See GH-120977. I think I forgot to backport it when it was first merged.
