### ISSUE TITLE
Thread sanitizer (free-threading) tests fail: test_signal raises RecursionError

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#121065]
# Bug report

```
 0:02:53 load avg: 5.00 [ 9/22/1] test_signal failed (1 error) (1 min 1 sec) -- running (3): test_logging (2 min 13 sec), test_io (2 min 17 sec), test_queue (1 min 52 sec)
test test_signal failed -- Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/test/test_signal.py", line 1384, in test_stress_modifying_handlers
    cycle_handlers()
    ~~~~~~~~~~~~~~^^
  File "/home/runner/work/cpython/cpython/Lib/test/test_signal.py", line 1374, in cycle_handlers
    signal.signal(signum, handler)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cpython/cpython/Lib/signal.py", line 58, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
                             ~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/runner/work/cpython/cpython/Lib/signal.py", line 41, in _enum_to_int
    return int(value)
  File "/home/runner/work/cpython/cpython/Lib/test/test_signal.py", line 1359, in custom_handler
    def custom_handler(signum, frame):
    
  File "/home/runner/work/cpython/cpython/Lib/test/test_signal.py", line 1359, in custom_handler
    def custom_handler(signum, frame):
    
  File "/home/runner/work/cpython/cpython/Lib/test/test_signal.py", line 1359, in custom_handler
    def custom_handler(signum, frame):
    
  [Previous line repeated 237 more times]
RecursionError: maximum recursion depth exceeded
```

Link: https://github.com/python/cpython/actions/runs/9686054998/job/26727620578

### Linked PRs
* gh-121100

**Comment by skirpichev** [comment]
I don't see similar failures before this merge: https://github.com/python/cpython/commit/22b0de2755ee2d0e2dd21cd8761f15421ed2da3d

**Comment by Fidget-Spinner** [comment]
Another example: https://github.com/python/cpython/pull/121083 came after that commit, and still passes that test.

**Comment by vstinner** [comment]
Maybe we can reduce the number of signals sent, or increase the recursion limit.

**Comment by colesbury** [comment]
Let's disable the test for now and then investigate the root cause.

**Comment by befeleme** [comment]
We have experienced this issue in Fedora Linux in the past, but haven't seen this happening in Python 3.15.0~a2, a3 or a5.
