### ISSUE TITLE
Support `allow_nan` for `json.load[s]()` for JSON compliance

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#121189]
# Feature or enhancement

### Proposal:

`json.dump[s]()` supports `allow_nan` for JSON compliance (see www.json.org), but `json.load[s]()` does not:

```python
>>> import json, math
>>> json.dumps(math.nan, allow_nan=False) # JSON compliant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wanne\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\wanne\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wanne\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
ValueError: Out of range float values are not JSON compliant: nan
>>> json.loads('NaN') # not JSON compliant
nan
```

This could lead to confusing error messages. instead of telling you the location in the json file.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by nineteendo** [comment]
Oops, looks like it's already possible with `parse_constant`.
