### ISSUE TITLE
test_pyrepl fails on s390x SLES: 'sys', 'ver' variables are unexpected

### ISSUE THREAD

**Issue by vstinner** [python/cpython#121206]
s390x SLES PR build: https://buildbot.python.org/all/#/builders/332/builds/1460

I suppose that `'sys', 'ver'` is unexpected in the test.

Output:

```
['__annotations__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'sys', 'ver']
```

Full logs:

```
======================================================================
FAIL: test_exposed_globals_in_repl (test.test_pyrepl.test_pyrepl.TestMain.test_exposed_globals_in_repl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/pull_request.edelsohn-sles-z/build/Lib/test/support/__init__.py", line 2622, in wrapper
    return func(*args, **kwargs)
  File "/home/dje/cpython-buildarea/pull_request.edelsohn-sles-z/build/Lib/test/test_pyrepl/test_pyrepl.py", line 865, in test_exposed_globals_in_repl
    self.assertTrue(case1 or case2 or case3 or case4, output)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: False is not true : sorted(dir())
exit

Python 3.14.0a0 (heads/refs/pull/121195/merge:ddec5b2192d, Jul  1 2024, 04:27:41) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

[?2004h
[?1h=
[?25l
[1A

[1;35m>>> [0m[4D
[?12l[?25h[4C
[?25l[4D
[1;35m>>> [0ms[5D
[?12l[?25h[5C
[?25l[5D
[1;35m>>> [0mso[6D
[?12l[?25h[6C
[?25l[6D[1;35m>>> [0msor
[7D
[?12l[?25h[7C
[?25l[7D
[1;35m>>> [0msort[8D
[?12l[?25h[8C
[?25l[8D
[1;35m>>> [0msorte[9D
[?12l[?25h[9C
[?25l[9D
[1;35m>>> [0msorted[10D
[?12l[?25h[10C
[?25l[10D
[1;35m>>> [0msorted([11D
[?12l[?25h[11C
[?25l[11D
[1;35m>>> [0msorted(d[12D
[?12l[?25h[12C
[?25l[12D
[1;35m>>> [0msorted(di[13D
[?12l[?25h[13C
[?25l[13D
[1;35m>>> [0msorted(dir[14D[?12l[?25h[14C
[?25l
[14D[1;35m>>> [0msorted(dir(
[15D
[?12l[?25h[15C
[?25l[15D
[1;35m>>> [0msorted(dir()[16D
[?12l[?25h[16C
[?25l[16D
[1;35m>>> [0msorted(dir())[17D
[?12l[?25h[17C
[17D

[?2004l
[?1l>
['__annotations__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'sys', 'ver']

[?2004h
[?1h=[?25l
[1A

[1;35m>>> [0m[4D
[?12l[?25h[4C
[?25l[4D
[1;35m>>> [0me[5D
[?12l[?25h[5C
[?25l[5D
[1;35m>>> [0mex[6D
[?12l[?25h[6C
[?25l[6D
[1;35m>>> [0mexi[7D
[?12l[?25h[7C
[?25l[7D
[1;35m>>> [0mexit[8D
[?12l[?25h[8C
[8D

[?2004l
[?1l>

----------------------------------------------------------------------
Ran 117 tests in 3.352s

FAILED (failures=1, skipped=1)
test test_pyrepl failed
```

**Comment by vstinner** [comment]
The builder is green, I close the issue: https://buildbot.python.org/all/#/builders/540/builds/9505
