### ISSUE TITLE
test_posixpath.test_expanduser_pwd2() fails on s390x Fedora Rawhide 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#121200]
build: https://buildbot.python.org/all/#/builders/538/builds/4698

```
FAIL: test_expanduser_pwd2 (test.test_posixpath.PosixPathTest.test_expanduser_pwd2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-fedora-rawhide-z/build/Lib/test/test_posixpath.py", line 366, in test_expanduser_pwd2
    self.assertEqual(posixpath.expanduser('~' + name), home)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: '/nonexisting' != '/'
- /nonexisting
+ /
```

### Linked PRs
* gh-121207
* gh-121213
* gh-121214
* gh-121226
* gh-121228
* gh-121231
* gh-121232

**Comment by vstinner** [comment]
With more logs:

```
FAIL: test_expanduser_pwd2 (test.test_posixpath.PosixPathTest.test_expanduser_pwd2) (pwd=pwd.struct_passwd(pw_name='cockpit-ws', pw_passwd='x', pw_uid=996, pw_gid=996, pw_gecos='Dynamic User', pw_dir='/', pw_shell='/usr/sbin/nologin'))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-fedora-rawhide-z/build/Lib/test/test_posixpath.py", line 367, in test_expanduser_pwd2
    self.assertEqual(posixpath.expanduser('~' + name), home)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: '/nonexisting' != '/'
- /nonexisting
+ /
```
