### ISSUE TITLE
test.test__interpchannels.ChannelTests.test_channel_list_interpreters_released hangs on 32-bit ARM --pydebug builds

### ISSUE THREAD

**Issue by stefanor** [python/cpython#121460]
# Bug report

### Bug description:

It looks like there's a memory handling error in interpreter cleanup, that manifests on 32-bit ARM `--pydebug` builds.

In Debian tests of 3.13.0 beta 3 on `armhf` and `armel` (32-bit ARM), `test__interpchannels` was hanging forever, specifically in the `test_channel_list_interpreters_released` test. Likewise, `test_interpreters` hangs in `test_after_destroy_all`.

Attaching to hung interpreter with gdb shows that we're caught in a faulthandler loop:
```
Program received signal SIGSEGV, Segmentation fault.
0x0002a734 in __errno_location@plt ()
(gdb) bt
#0  0x0002a734 in __errno_location@plt ()
#1  0x0024f242 in faulthandler_fatal_error (signum=11) at ../Modules/faulthandler.c:289
#2  <signal handler called>
#3  0x0002a734 in __errno_location@plt ()
#4  0x0024f242 in faulthandler_fatal_error (signum=11) at ../Modules/faulthandler.c:289
#5  <signal handler called>
#6  0x0002a734 in __errno_location@plt ()
#7  0x0024f242 in faulthandler_fatal_error (signum=11) at ../Modules/faulthandler.c:289
#8  <signal handler called>
#9  0x0002a734 in __errno_location@plt ()
#10 0x0024f242 in faulthandler_fatal_error (signum=11) at ../Modules/faulthandler.c:289
#11 <signal handler called>
#12 0x0002a734 in __errno_location@plt ()
#13 0x0024f242 in faulthandler_fatal_error (signum=11) at ../Modules/faulthandler.c:289
```
etc.

Running the process entirely under GDB I catch the SEGV early, before the faulthandler loop:

```
$ gdb --args python3.13d -W default -bb -E -R test/regrtest.py test__interpchannels -m test_channel_list_interpreters_released   GNU gdb (Debian 13.2-1+b3) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3.13d...
r(gdb) run
Starting program: /usr/bin/python3.13d -W default -bb -E -R test/regrtest.py test__interpchannels -m test_channel_list_interpreters_released
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Using random seed: 1504835330
0:00:00 load avg: 0.16 Run 1 test sequentially
0:00:00 load avg: 0.16 [1/1] test__interpchannels

Program received signal SIGSEGV, Segmentation fault.
0x0002a3e0 in munmap@plt ()
(gdb) bt
#0  0x0002a3e0 in munmap@plt ()
#1  0x000e6f32 in _PyMem_ArenaFree (_unused_ctx=<optimized out>, ptr=<optimized out>,
    size=<optimized out>) at ../Objects/obmalloc.c:391
#2  0x000e7588 in free_obmalloc_arenas (interp=interp@entry=0x715920)
    at ../Objects/obmalloc.c:3172
#3  0x000e7f10 in _PyInterpreterState_FinalizeAllocatedBlocks (interp=interp@entry=0x715920)
    at ../Objects/obmalloc.c:1484
#4  0x001d3da0 in PyInterpreterState_Delete (interp=interp@entry=0x715920)
    at ../Python/pystate.c:957
#5  0x001cfee2 in finalize_interp_delete (interp=0x715920) at ../Python/pylifecycle.c:1908
#6  0x001d13c8 in Py_EndInterpreter (tstate=tstate@entry=0x72de40)
    at ../Python/pylifecycle.c:2409
#7  0x0019e800 in _PyXI_EndInterpreter (interp=interp@entry=0x715920, tstate=0x72de40,
    tstate@entry=0x0, p_save_tstate=p_save_tstate@entry=0x0) at ../Python/crossinterp.c:1910
#8  0xb67826ae in interp_destroy (self=<optimized out>, args=<optimized out>,
    kwds=<optimized out>) at ../Modules/_interpretersmodule.c:707
#9  0x000d0d08 in cfunction_call (
    func=<built-in method destroy of module object at remote 0xb67b6b40>, args=(1,),
    kwargs=0x0) at ../Objects/methodobject.c:540
#10 0x0009321e in _PyObject_MakeTpCall (tstate=tstate@entry=0x51b1d0 <_PyRuntime+157112>,
    callable=callable@entry=<built-in method destroy of module object at remote 0xb67b6b40>,
    args=args@entry=0xb6fd8884, nargs=nargs@entry=1, keywords=keywords@entry=0x0)
    at ../Objects/call.c:242
#11 0x000933a6 in _PyObject_VectorcallTstate (tstate=0x51b1d0 <_PyRuntime+157112>,
    callable=callable@entry=<built-in method destroy of module object at remote 0xb67b6b40>,
    args=args@entry=0xb6fd8884, nargsf=nargsf@entry=2147483649, kwnames=<optimized out>,
    kwnames@entry=0x0) at ../Include/internal/pycore_call.h:166
#12 0x0009340a in PyObject_Vectorcall (
    callable=callable@entry=<built-in method destroy of module object at remote 0xb67b6b40>,
    args=args@entry=0xb6fd8884, nargsf=nargsf@entry=2147483649, kwnames=kwnames@entry=0x0)
    at ../Objects/call.c:327
#13 0x0017a044 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0xb6fd8848,
    throwflag=0) at ../Python/generated_cases.c.h:813
#14 0x00185e72 in _PyEval_EvalFrame (tstate=tstate@entry=0x51b1d0 <_PyRuntime+157112>,
    frame=<optimized out>, throwflag=throwflag@entry=0)
    at ../Include/internal/pycore_ceval.h:119
#15 0x00185f6e in _PyEval_Vector (tstate=0x51b1d0 <_PyRuntime+157112>, func=0xb69b6cf0,
    locals=locals@entry=0x0, args=0xbeffe5a4, argcount=<optimized out>,
    kwnames=<optimized out>) at ../Python/ceval.c:1819
#16 0x000930d0 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>,
    nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:413
#17 0x0009529a in _PyObject_VectorcallTstate (
    tstate=tstate@entry=0x51b1d0 <_PyRuntime+157112>,
    callable=callable@entry=<function at remote 0xb69b6cf0>, args=args@entry=0xbeffe5a4,
    nargsf=nargsf@entry=2, kwnames=<optimized out>, kwnames@entry=0x0)
--Type <RET> for more, q to quit, c to continue without paging--q
Quit  
(gdb) py-bt
Traceback (most recent call first):
  <built-in method destroy of module object at remote 0xb67b6b40>
  File "/usr/lib/python3.13/test/test__interpreters.py", line 82, in clean_up_interpreters
    _interpreters.destroy(id)
  File "/usr/lib/python3.13/test/test__interpchannels.py", line 249, in tearDown
    clean_up_interpreters()
  File "/usr/lib/python3.13/unittest/case.py", line 611, in _callTearDown
    self.tearDown()
  File "/usr/lib/python3.13/unittest/case.py", line 654, in run
    self._callTearDown()
  File "/usr/lib/python3.13/unittest/case.py", line 707, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.13/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.13/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.13/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.13/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.13/test/libregrtest/testresult.py", line 146, in run
    test(self.result)
  File "/usr/lib/python3.13/test/libregrtest/single.py", line 57, in _run_suite
    result = runner.run(suite)
  File "/usr/lib/python3.13/test/libregrtest/single.py", line 37, in run_unittest
    return _run_suite(tests)
  File "/usr/lib/python3.13/test/libregrtest/single.py", line 135, in test_func
    return run_unittest(test_mod)
  File "/usr/lib/python3.13/test/libregrtest/single.py", line 91, in regrtest_runner
    test_result = test_func()
  File "/usr/lib/python3.13/test/libregrtest/single.py", line 138, in _load_run_test
    regrtest_runner(result, test_func, runtests)
  File "/usr/lib/python3.13/test/libregrtest/single.py", line 181, in _runtest_env_changed_exc
    _load_run_test(result, runtests)
  File "/usr/lib/python3.13/test/libregrtest/single.py", line 281, in _runtest
    _runtest_env_changed_exc(result, runtests,
  File "/usr/lib/python3.13/test/libregrtest/single.py", line 310, in run_single_test
    _runtest(result, runtests)
  File "/usr/lib/python3.13/test/libregrtest/main.py", line 355, in run_test
    result = run_single_test(test_name, runtests)
  File "/usr/lib/python3.13/test/libregrtest/main.py", line 389, in run_tests_sequentially
    result = self.run_test(test_name, runtests, tracer)
  File "/usr/lib/python3.13/test/libregrtest/main.py", line 533, in _run_tests
    self.run_tests_sequentially(runtests)
--Type <RET> for more, q to quit, c to continue without paging--
```

This doesn't seem to be reproducible on amd64 or without `--pydebug`.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-121491
* gh-121589

**Comment by ericsnowcurrently** [comment]
Just to be sure I've understood, the linked PR fixes the problem, right?

**Comment by stefanor** [comment]
> Just to be sure I've understood, the linked PR fixes the problem, right?

It appears to, yes.
