### ISSUE TITLE
DLL load failed while importing _sqlite3: Not enough memory resources are available to process this command

### ISSUE THREAD

**Issue by MubinTokhi** [python/cpython#121614]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
import sys
from src.logger import logging
from src.exception import CustomException
from src.components.data_ingestion import DataIngestion
from src.components.data_transformation import DataTransformation

 
obj = DataIngestion()
raw_data = obj.initaite_data_ingestion()
data_transformation = DataTransformation()
data_transformation.initiate_data_transformation(raw_data)

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from src.components.data_transformation import DataTransformation
  File "C:\Users\mobin\DATASIENCE\INTERNSHIP\Job Recommendation Engine\New folder\src\components\data_transformation.py", line 7, in <module>
    from src.utils import cleaning_text
  File "C:\Users\mobin\DATASIENCE\INTERNSHIP\Job Recommendation Engine\New folder\src\utils.py", line 3, in <module>
    import nltk
  File "C:\Users\mobin\DATASIENCE\INTERNSHIP\Job Recommendation Engine\New folder\job_venv\lib\site-packages\nltk\__init__.py", line 153, in <module>
    from nltk.translate import *
  File "C:\Users\mobin\DATASIENCE\INTERNSHIP\Job Recommendation Engine\New folder\job_venv\lib\site-packages\nltk\translate\__init__.py", line 24, in <module>
    from nltk.translate.meteor_score import meteor_score as meteor
  File "C:\Users\mobin\DATASIENCE\INTERNSHIP\Job Recommendation Engine\New folder\job_venv\lib\site-packages\nltk\translate\meteor_score.py", line 13, in <module>
    from nltk.corpus import WordNetCorpusReader, wordnet
  File "C:\Users\mobin\DATASIENCE\INTERNSHIP\Job Recommendation Engine\New folder\job_venv\lib\site-packages\nltk\corpus\__init__.py", line 64, in <module>
    from nltk.corpus.reader import *
  File "C:\Users\mobin\DATASIENCE\INTERNSHIP\Job Recommendation Engine\New folder\job_venv\lib\site-packages\nltk\corpus\reader\__init__.py", line 106, in <module>
    from nltk.corpus.reader.panlex_lite import *
  File "C:\Users\mobin\DATASIENCE\INTERNSHIP\Job Recommendation Engine\New folder\job_venv\lib\site-packages\nltk\corpus\reader\panlex_lite.py", line 15, in <module>
    import sqlite3
  File "C:\Users\mobin\DATASIENCE\INTERNSHIP\Job Recommendation Engine\New folder\job_venv\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\mobin\DATASIENCE\INTERNSHIP\Job Recommendation Engine\New folder\job_venv\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: Not enough memory resources are available to process this command.

### CPython versions tested on:

3.11, 3.12, 3.13

### Operating systems tested on:

Windows

**Comment by ZeroIntensity** [comment]
There's not really anything CPython can do about this -- your system is out of memory.
