### ISSUE TITLE
Issue with map object having both int and map types when using map with max or sum functions

### ISSUE THREAD

**Issue by OnePi-1pi** [python/cpython#121683]
# Bug report

### Bug description:

```python
m = map(max,['a'])
list(m)
['a']
m = map(max,[1])
list(m)
Traceback (most recent call last):
  File "<pyshell#14>", line 1, in <module>
    list(m)
TypeError: 'int' object is not iterable
type(m)
<class 'map'>
dir(m)
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__ne__', '__new__', '__next__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
next(m)
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    next(m)
TypeError: 'int' object is not iterable
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
Yes, `max` accept a iterable as first argument:
```python
>>> max(1)
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    max(1)
    ~~~^^^
TypeError: 'int' object is not iterable
>>> max([1])
1
```
So, there's no bug.
Please note that this repository is intended as a CPython bug tracker, for python-related questions you can use https://discuss.python.org/c/users/

**Comment by OnePi-1pi** [comment]
"Sorry, I forgot that the `map` function is lazily evaluated. Thank you for your patient explanation."
