### ISSUE TITLE
OSError: [WinError 87] i am begginer, i cant solve that issue

### ISSUE THREAD

**Issue by Ryuk0Mat0i** [python/cpython#122080]
# Crash report

### What happened?
```pytb
Traceback (most recent call last):
  File "C:\Users\mcazm\OneDrive\Masaüstü\rospeed-main\main.py", line 6, in <module>     
    main.main()
  File "C:\Users\mcazm\OneDrive\Masaüstü\rospeed-main\src\threading.py", line 73, in main
    self.run_procfunc()
  File "C:\Users\mcazm\OneDrive\Masaüstü\rospeed-main\src\threading.py", line 47, in run_procfunc
    p.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\popen_spawn_win32.py", line 95, in __init__        
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
PS C:\Users\mcazm\OneDrive\Masaüstü\rospeed-main> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 108, in spawn_main
    source_process = _winapi.OpenProcess(
                     ^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] Parametre hatalı
```
### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by hugovk** [comment]
Hello! This issue tracker is for bugs with Python itself, not for bugs in your or others' code or help getting set up.

We have a help forum though, please post your question at https://discuss.python.org/c/users/7 and pleas also explain what you were trying to do. Good luck!
