### ISSUE TITLE
Make REPL completions match only syntactically valid keywords and values

### ISSUE THREAD

**Issue by HarryLHW** [python/cpython#122379]
# Bug report

### Bug description:

<img width="571" alt="image" src="https://github.com/user-attachments/assets/ae7ded6b-5098-4db6-b646-1025acd6648b">
<img width="572" alt="image" src="https://github.com/user-attachments/assets/b2449aa3-9e0b-4443-b60b-05529c963ed9">

The completion in the above case shows `[ not unique ]` and gives several suggestions. However, `case ` is the only word to form a valid syntax at this point. It is better to just complete it with `case `.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-122380

**Comment by HarryLHW** [comment]
I have a PR ready. The implementation is running `compile()` with `flags=PyCF_ALLOW_INCOMPLETE_INPUT` for each potential matched word preceded by the console code buffer (in the above example, _source_ would be `match x:\n    case `), and iif it raises no exceptions or it raises `_IncompleteInputError`, the match is considered to be syntactically valid and kept. 

It seems that the new REPL can run several statements together, e.g.
```pytb
>>> if True:
...     "foo"
... "bar"
... 
'bar'
>>> 
```

Contrary to the old REPL,
```pytb
>>> if True:
...     "foo"
... "bar"
  File "<stdin>", line 3
    "bar"
    ^^^^^
SyntaxError: invalid syntax
>>> 
```

I see the implementation of the new REPL is (hide irrelevant details):
```python3
class InteractiveColoredConsole(code.InteractiveConsole):
    ...
    def runsource(self, source, filename="<input>", symbol="single"):
        ...
        for stmt in tree.body:
            ...
            the_symbol = symbol if stmt is last_stmt else "exec"
            ...
                code = self.compile.compiler(item, filename, the_symbol, dont_inherit=True)
            ...
```
It runs the first several statements with `"exec"` except the last one with `"single"`. 

This means that I have to use `mode="exec"` for `InteractiveColoredConsole` and `mode="single"` for regular ones. `mode="single"` with `PyCF_ALLOW_INCOMPLETE_INPUT` works as expected, but `mode="exec" with `PyCF_ALLOW_INCOMPLETE_INPUT` can give unexpected results. For example,
```pytb
>>> import codeop
>>> compile("if True", "<test>", "exec", codeop.PyCF_ALLOW_INCOMPLETE_INPUT)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<test>", line 1
    if True
           ^
SyntaxError: expected ':'
>>> 
```

This is because as in `helpers.c` `_PyTokenizer_translate_newlines()`,
```C
    /* If this is exec input, add a newline to the end of the string if
       there isn't one already. */
    if (exec_input && c != '\n' && c != '\0') {
        *current = '\n';
        current++;
    }
```
which makes `"if True"` become `"if True\n"` which is not incomplete.

In my PR, I made it add a newline for exec input only when flag includes `PyCF_ALLOW_INCOMPLETE_INPUT` and excludes `PyCF_DONT_IMPLY_DEDENT`. I am not sure if this change is okay. `codeop` is using `PyCF_ALLOW_INCOMPLETE_INPUT | PyCF_DONT_IMPLY_DEDENT` and I have make this case unchanged. The backward-incompatible case would be using `PyCF_ALLOW_INCOMPLETE_INPUT` without `PyCF_DONT_IMPLY_DEDENT`, which I didn't find any in the standard library. Or should I add a new flag to make it completely backward-compatible, or should it be considered as a bug so that it is okay t fix it?

I am sorry for the long paragraphs above, and I hope I described the problem clearly.
