### ISSUE TITLE
Crash in _curses when calling .initscr() after ignoring exception from .resizeterm()

### ISSUE THREAD

**Issue by devdanzin** [python/cpython#122398]
# Crash report

### What happened?

Running this test script segfaults on main, with the following backtrace. 
`$ ./python test.py`
test.py:
```python
import _curses
_curses.initscr()
try:
    _curses.resizeterm(40000, 40000)
except:
    pass
_curses.initscr()
```

```gdb
#0  0x00007ffff79985aa in ?? () from /lib/x86_64-linux-gnu/libncursesw.so.6
#1  0x00007ffff799ad0a in doupdate_sp () from /lib/x86_64-linux-gnu/libncursesw.so.6
#2  0x00007ffff798e6d8 in wrefresh () from /lib/x86_64-linux-gnu/libncursesw.so.6
#3  0x00007ffff79ce89f in _curses_initscr_impl (module=<optimized out>) at ./Modules/_cursesmodule.c:3272
#4  0x00007ffff79cf62f in _curses_initscr (module=<optimized out>, _unused_ignored=<optimized out>)
    at ./Modules/clinic/_cursesmodule.c.h:2661
#5  0x00005555556fb6e9 in cfunction_vectorcall_NOARGS (func=0x7ffff7ac7fb0, args=<optimized out>,
    nargsf=<optimized out>, kwnames=<optimized out>) at Objects/methodobject.c:484
```

Seems fixable by setting `initialised` to `FALSE` in ` _curses_resizeterm_impl` for the error paths, not sure this is a valid fix:
```diff
diff --git a/Modules/_cursesmodule.c b/Modules/_cursesmodule.c
index b5854e8c33f..10f1c4b14c5 100644
--- a/Modules/_cursesmodule.c
+++ b/Modules/_cursesmodule.c
@@ -4106,9 +4106,12 @@ _curses_resizeterm_impl(PyObject *module, int nlines, int ncols)
     PyCursesInitialised;

     result = PyCursesCheckERR(resizeterm(nlines, ncols), "resizeterm");
-    if (!result)
+    if (!result) {
+        initialised = FALSE;
         return NULL;
+    }
     if (!update_lines_cols()) {
+        initialised = FALSE;
         Py_DECREF(result);
         return NULL;
     }
```

Found in https://github.com/pypy/pypy/issues/4989.

### CPython versions tested on:

3.11, CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.14.0a0 (heads/main:9187484dd97, Jul 29 2024, 09:25:22) [GCC 11.4.0]

**Comment by devdanzin** [comment]
This is a duplicate of #120378.
