### ISSUE TITLE
Existence of import of sub-module causes module to become variable

### ISSUE THREAD

**Issue by stranma** [python/cpython#122305]
# Bug report

### Bug description:

```python
import some_package

if __name__ == '__main__':
    def test_import():
        if False:                                    # note this!
            import some_package.sub
            print(some_package.sub.B)
        print(some_package.A)

    test_import()
```

This code with some expected project structure (see down below) fails:

```
Traceback (most recent call last):
  File "...\show_strange_import_behaviour\this_imports_some_package.py", line 10, in <module>
    test_import()
  File "...\testImport\show_strange_import_behaviour\this_imports_some_package.py", line 8, in test_import
    print(some_package.A)
          ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'some_package' where it is not associated with a value
```

The following two code snippets does not result in error

```python
import some_package

if __name__ == '__main__':
    def test_import():
        if False:
            pass
            # import some_package.sub
            # print(some_package.sub.B)
        print(some_package.A)

    test_import()
```
```python
import some_package

if __name__ == '__main__':
    def test_import():
        import some_package.sub
        print(some_package.sub.B)
        print(some_package.A)

    test_import()
```

I have found real world example of this issue in [python-mip](https://github.com/coin-or/python-mip/blob/0ccb81115543e737ab74a4f1309891ce5650c8d5/mip/model.py#L87)

![image](https://github.com/user-attachments/assets/0f3c0b36-78b5-40a3-ba82-4b1404b2e259)

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Windows

**Comment by chopin57otu** [comment]
Thank you very much for clarification.
