### ISSUE TITLE
Import hashlib leads to an error (can't install PIP)

### ISSUE THREAD

**Issue by eugenesmsk** [python/cpython#122458]
# Bug report

### Bug description:

[discuss.python.org link with this problem](https://discuss.python.org/t/cant-install-pip/59526)

Hello everyone, a more detailed description of the error can be found at the link above. In short: I can't install PIP. It didn't install automatically with Python. I can't install it either through ensurepip or get-pip.py.

Via ensurepip:

```
C:\Users\Evgeny\AppData\Local\Programs\Python\Python313>python -m ensurepip --upgrade
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Evgeny\AppData\Local\Programs\Python\Python313\Lib\ensurepip\__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
             ~~~~~~~~~~~~~~~^^
  File "C:\Users\Evgeny\AppData\Local\Programs\Python\Python313\Lib\ensurepip\__init__.py", line 257, in _main
    return _bootstrap(
        root=args.root,
    ...<4 lines>...
        default_pip=args.default_pip,
    )
  File "C:\Users\Evgeny\AppData\Local\Programs\Python\Python313\Lib\ensurepip\__init__.py", line 172, in _bootstrap
    return _run_pip([*args, "pip"], [os.fsdecode(tmp_wheel_path)])
  File "C:\Users\Evgeny\AppData\Local\Programs\Python\Python313\Lib\ensurepip\__init__.py", line 87, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Evgeny\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\Evgeny\\AppData\\Local\\Programs\\Python\\Python313\\python.exe', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'C:\\\\Users\\\\Evgeny\\\\AppData\\\\Local\\\\Temp\\\\tmpud9wn6u5\\\\pip-24.1.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'C:\\\\Users\\\\Evgeny\\\\AppData\\\\Local\\\\Temp\\\\tmpud9wn6u5\', \'--upgrade\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 3221225477.
```

Via get-pip.py:

`Process finished with exit code -1073741819 (0xC0000005)`

With faulthandler:

```
C:\Python312\Scripts> py -X faulthandler get-pip.py
Windows fatal exception: access violation

Current thread 0x00004238 (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1297 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Python312\Lib\hashlib.py", line 170 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\Evgeny\AppData\Local\Temp\tmpwg_904oz\pip.zip\pip\_internal\utils\misc.py", line 3 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\Evgeny\AppData\Local\Temp\tmpwg_904oz\pip.zip\pip\_internal\utils\logging.py", line 29 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\Evgeny\AppData\Local\Temp\tmpwg_904oz\pip.zip\pip\_internal\configuration.py", line 26 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\Evgeny\AppData\Local\Temp\tmpwg_904oz\pip.zip\pip\_internal\cli\parser.py", line 12 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\Evgeny\AppData\Local\Temp\tmpwg_904oz\pip.zip\pip\_internal\cli\cmdoptions.py", line 24 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1415 in _handle_fromlist
  File "C:\Users\Evgeny\AppData\Local\Temp\tmpwg_904oz\pip.zip\pip\_internal\cli\base_command.py", line 15 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\Evgeny\AppData\Local\Temp\tmpwg_904oz\pip.zip\pip\_internal\commands\__init__.py", line 9 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1310 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Python312\Scripts\get-pip.py", line 95 in monkeypatch_for_cert
  File "C:\Python312\Scripts\get-pip.py", line 119 in bootstrap
  File "C:\Python312\Scripts\get-pip.py", line 144 in main
  File "C:\Python312\Scripts\get-pip.py", line 28433 in <module>
```

And trying import hashlib:

```
C:\ProgramData\chocolatey> py
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import faulthandler
>>> faulthandler.enable()
>>> import hashlib
Windows fatal exception: access violation

Current thread 0x000046f4 (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1297 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Python312\Lib\hashlib.py", line 170 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<stdin>", line 1 in <module>
```
  
  

### CPython versions tested on:

3.10, 3.11, 3.12, 3.13

### Operating systems tested on:

Windows

**Comment by picnixz** [comment]
What happens if you just try to import `hashlib` itself? Does it happen with other modules or only with hashlib? Also, what are the outputs of the following commands:

- `py -I -c 'import _hashlib; print(_hashlib)'`
- `py -I -c 'import hashlib; print(hashlib)'`
- `py -I -c 'import sys;sys.modules.pop("hashlib", None);sys.modules["_hashlib"]=None;import hashlib;print(hashlib)'`

**Comment by eugenesmsk** [comment]
@picnixz 
For some reason, it doesn't want to work in one line. But I ran it like this:

```
C:\Python312\Lib>py
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys;sys.modules.pop("hashlib", None)
>>> sys.modules["_hashlib"]=None
>>> import hashlib
>>> print(hashlib)
<module 'hashlib' from 'C:\\Python312\\Lib\\hashlib.py'>
>>> exit()
```

import _hashlib and import hashlib doesn't work. Trying with faulthandler:

```
C:\Python312\Lib>py
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import faulthandler
>>> faulthandler.enable()
>>> import _hashlib
Windows fatal exception: access violation

Current thread 0x000023f4 (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1297 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<stdin>", line 1 in <module>
```


```
C:\Python312\Lib>py
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import faulthandler
>>> faulthandler.enable()
>>> import hashlib
Windows fatal exception: access violation

Current thread 0x000013f8 (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1297 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Python312\Lib\hashlib.py", line 170 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<stdin>", line 1 in <module>
```

**Comment by picnixz** [comment]
Can you try to launch `py` with `py -I` and not just `py` (and try the other two). I want to be sure that Python is in isolated mode.

**Comment by eugenesmsk** [comment]
-I works. Wait a minute

**Comment by eugenesmsk** [comment]
```
C:\Python312\Lib>py -I
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import faulthandler
>>> faulthandler.enable()
>>> import _hashlib
Windows fatal exception: access violation

Current thread 0x00000f10 (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1297 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<stdin>", line 1 in <module>
```

```
C:\Python312\Lib>py -I
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import faulthandler
>>> faulthandler.enable()
>>> import hashlib
Windows fatal exception: access violation

Current thread 0x00001270 (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1297 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Python312\Lib\hashlib.py", line 170 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<stdin>", line 1 in <module>

C:\Python312\Lib>
```

**Comment by picnixz** [comment]
Ok, so I can confidently say that there is an issue when importing `_hashlib` but I don't know how I can personally help. By the way, how did you install Python? was it built from sources or was it simply downloaded online? (or maybe using Windows store or something like that?)

@Eclips4 Since you have a Windows machine, could you perhaps investigate in my place?

**Comment by eugenesmsk** [comment]
At the moment, I have installed Python via Chocolatey. However, I experienced the same behavior when installing via the official installer downloaded from the website.

So I can confidently say that the issue is not due to installing via Chocolatey (especially since I installed it on another laptop through it and everything is fine).

**Comment by eugenesmsk** [comment]
@Eclips4 
```
C:\cpython>"C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\msbuild.exe" "C:\cpython\PCbuild\pcbuild.proj" /t:Build /m /nologo /v:m /clp:summary /p:Configuration=Release /p:Platform=x64 /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=true /p:DisableGil= /p:UseTestMarker= /p:GIT="C:\Program Files\Git\cmd\git.exe" /p:UseJIT= /p:UseTIER2= -C debug
MSBUILD : error MSB1001: Unknown switch.
    Full command line: '"C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\msbuild.exe"  "C:\cpython\PCbuild\pcbuild.proj" /t:Build /m /nologo /v:m /clp:summary /p:Configuration=Release /p:Platform=x64 /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=true /p:DisableGil= /p:UseTestMarker= /p:GIT="C:\Program Files\Git\cmd\git.exe" /p:UseJIT= /p:UseTIER2= -C debug       '
  Switches appended by response files:
'' came from 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.rsp'
Switch: -C
```

I'll try without the -C debug flag

**Comment by eugenesmsk** [comment]
@Eclips4 @picnixz 

Errors still appear

```
C:\cpython>./python.bat -I
Running Release|x64 interpreter...
Python 3.14.0a0 (heads/main:8fb88b22b7, Jul 30 2024, 19:31:31) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import faulthandler
>>> faulthandler.enable()
>>> import _hashlib
Windows fatal exception: access violation

Current thread 0x000037bc (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1327 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<python-input-2>", line 1 in <module>
  File "C:\cpython\Lib\code.py", line 91 in runcode
  File "C:\cpython\Lib\_pyrepl\console.py", line 200 in runsource
  File "C:\cpython\Lib\code.py", line 303 in push
  File "C:\cpython\Lib\_pyrepl\simple_interact.py", line 157 in run_multiline_interactive_console
  File "C:\cpython\Lib\_pyrepl\main.py", line 59 in interactive_console
  File "C:\cpython\Lib\_pyrepl\__main__.py", line 6 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main
```

```
C:\cpython>./python.bat -I
Running Release|x64 interpreter...
Python 3.14.0a0 (heads/main:8fb88b22b7, Jul 30 2024, 19:31:31) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import faulthandler
>>> faulthandler.enable()
>>> import hashlib
Windows fatal exception: access violation

Current thread 0x00002b90 (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1327 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\cpython\Lib\hashlib.py", line 170 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1025 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<python-input-2>", line 1 in <module>
  File "C:\cpython\Lib\code.py", line 91 in runcode
  File "C:\cpython\Lib\_pyrepl\console.py", line 200 in runsource
  File "C:\cpython\Lib\code.py", line 303 in push
  File "C:\cpython\Lib\_pyrepl\simple_interact.py", line 157 in run_multiline_interactive_console
  File "C:\cpython\Lib\_pyrepl\main.py", line 59 in interactive_console
  File "C:\cpython\Lib\_pyrepl\__main__.py", line 6 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main
```

**Comment by eugenesmsk** [comment]
In the Event viewer there is an error:

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/python/cpython/issues/122458#) <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2024-07-30T18:24:21.9315496Z" /> 
  <EventRecordID>70647</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="14240" ThreadID="3676" /> 
  <Channel>Application</Channel> 
  <Computer>LAPTOP-M5LC7GTA</Computer> 
  <Security UserID="S[-](https://github.com/python/cpython/issues/122458#)1-5-21-2791829737-3493195482-1977325991-1001" /> 
  </System>
- <EventData>
  <Data Name="AppName">python.exe</Data> 
  <Data Name="AppVersion">3.14.100.1013</Data> 
  <Data Name="AppTimeStamp">66a915c9</Data> 
  <Data Name="ModuleName">ntdll.dll</Data> 
  <Data Name="ModuleVersion">10.0.22621.3733</Data> 
  <Data Name="ModuleTimeStamp">67ca8829</Data> 
  <Data Name="ExceptionCode">c0000005</Data> 
  <Data Name="FaultingOffset">0000000000021a9d</Data> 
  <Data Name="ProcessId">0x5200</Data> 
  <Data Name="ProcessCreationTime">0x1dae2adab2d1474</Data> 
  <Data Name="AppPath">C:\cpython\PCbuild\amd64\python.exe</Data> 
  <Data Name="ModulePath">C:\WINDOWS\SYSTEM32\ntdll.dll</Data> 
  <Data Name="IntegratorReportId">8f12d083-2963-41db-8001-e5d909c39131</Data> 
  <Data Name="PackageFullName" /> 
  <Data Name="PackageRelativeAppId" /> 
  </EventData>
  </Event>
```

**Comment by zooba** [comment]
ntdll is a weird place to have this error.

Can you check your System32 directory for `libcrypto-3.dll`? This ought to be the only directory that can pre-empt our own copy, and that's the most likely reason to get a crash on import. It's possible that another app has installed a copy globally instead of in its own directory.

However, crashing in ntdll often indicates memory corruption, which can be harder to track down. If you're up for it, could you install [WinDbg](https://apps.microsoft.com/detail/9pgjgd53tn86) (the debugger) and run `windbgx /g C:\cpython\PCbuild\amd64\python.exe -c "import _hashlib"`? That ought to spit out additional information about why it's crashing, which I only expect you to copy-paste here (unless you can figure out what it means, but as I have no real idea what you'll see, I can't even hazard a guess!)

**Comment by eugenesmsk** [comment]
@zooba 
Hi, here is the log:
```

************* Preparing the environment for Debugger Extensions Gallery repositories **************
   ExtensionRepository : Implicit
   UseExperimentalFeatureForNugetShare : true
   AllowNugetExeUpdate : true
   NonInteractiveNuget : true
   AllowNugetMSCredentialProviderInstall : true
   AllowParallelInitializationOfLocalRepositories : true
   EnableRedirectToChakraJsProvider : false

   -- Configuring repositories
      ----> Repository : LocalInstalled, Enabled: true
      ----> Repository : UserExtensions, Enabled: true

>>>>>>>>>>>>> Preparing the environment for Debugger Extensions Gallery repositories completed, duration 0.016 seconds

************* Waiting for Debugger Extensions Gallery to Initialize **************

>>>>>>>>>>>>> Waiting for Debugger Extensions Gallery to Initialize completed, duration 0.656 seconds
   ----> Repository : UserExtensions, Enabled: true, Packages count: 0
   ----> Repository : LocalInstalled, Enabled: true, Packages count: 42

Microsoft (R) Windows Debugger Version 10.0.27668.1000 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

CommandLine: C:\cpython\cpython\PCbuild\amd64\python.exe -c "import _hashlib"

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00007ff7`833b0000 00007ff7`833ca000   python.exe
ModLoad: 00007ffc`34890000 00007ffc`34aa7000   ntdll.dll
ModLoad: 00007ffc`32fb0000 00007ffc`33074000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 00007ffc`32020000 00007ffc`323cd000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 00007ffc`31d90000 00007ffc`31ea1000   C:\WINDOWS\System32\ucrtbase.dll
ModLoad: 00007ffc`235e0000 00007ffc`235fe000   C:\cpython\cpython\PCbuild\amd64\VCRUNTIME140.dll
ModLoad: 00007ffb`cb5b0000 00007ffb`cbd3f000   C:\cpython\cpython\PCbuild\amd64\python314.dll
ModLoad: 00007ffc`32f30000 00007ffc`32fa1000   C:\WINDOWS\System32\WS2_32.dll
ModLoad: 00007ffc`33880000 00007ffc`33994000   C:\WINDOWS\System32\RPCRT4.dll
ModLoad: 00007ffc`2f1f0000 00007ffc`2f1fa000   C:\WINDOWS\SYSTEM32\VERSION.dll
ModLoad: 00007ffc`32400000 00007ffc`32428000   C:\WINDOWS\System32\bcrypt.dll
ModLoad: 00007ffc`33d50000 00007ffc`33df7000   C:\WINDOWS\System32\msvcrt.dll
ModLoad: 00007ffc`328d0000 00007ffc`32982000   C:\WINDOWS\System32\ADVAPI32.dll
ModLoad: 00007ffc`33e00000 00007ffc`33ea9000   C:\WINDOWS\System32\sechost.dll
ModLoad: 00007ffc`31c50000 00007ffc`31ccb000   C:\WINDOWS\System32\bcryptprimitives.dll
ModLoad: 000002ac`bc0b0000 000002ac`bc0c0000   C:\cpython\cpython\PCbuild\amd64\python3.DLL
ModLoad: 000002ac`bc0b0000 000002ac`bc0c0000   C:\cpython\cpython\PCbuild\amd64\python3.DLL
ModLoad: 00007ffc`231f0000 00007ffc`23200000   C:\cpython\cpython\PCbuild\amd64\_hashlib.pyd
ModLoad: 00007ffb`cd230000 00007ffb`cd729000   C:\cpython\cpython\PCbuild\amd64\libcrypto-3.dll
ModLoad: 00007ffc`32c70000 00007ffc`32e1e000   C:\WINDOWS\System32\USER32.dll
ModLoad: 00007ffc`323d0000 00007ffc`323f6000   C:\WINDOWS\System32\win32u.dll
ModLoad: 00007ffc`32a20000 00007ffc`32a49000   C:\WINDOWS\System32\GDI32.dll
ModLoad: 00007ffc`324a0000 00007ffc`325b9000   C:\WINDOWS\System32\gdi32full.dll
ModLoad: 00007ffc`31bb0000 00007ffc`31c4a000   C:\WINDOWS\System32\msvcp_win.dll
ModLoad: 00007ffc`34810000 00007ffc`34841000   C:\WINDOWS\System32\IMM32.DLL
ModLoad: 00007ffc`0dc80000 00007ffc`0dcd8000   C:\OpenSSL-Win64\bin\gost.dll
ModLoad: 00007ffc`29150000 00007ffc`29159000   C:\WINDOWS\SYSTEM32\WSOCK32.dll
ModLoad: 00007ffb`cead0000 00007ffb`cee1c000   C:\WINDOWS\SYSTEM32\libcrypto-1_1-x64.dll
(34ac.4064): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify checksum for C:\WINDOWS\SYSTEM32\libcrypto-1_1-x64.dll
ntdll!RtlEnterCriticalSection+0xd:
00007ffc`348b1a9d f00fba710800    lock btr dword ptr [rcx+8],0 ds:00000000`00000008=????????
```

**Comment by zooba** [comment]
```
ModLoad: 00007ffc`0dc80000 00007ffc`0dcd8000   C:\OpenSSL-Win64\bin\gost.dll
ModLoad: 00007ffc`29150000 00007ffc`29159000   C:\WINDOWS\SYSTEM32\WSOCK32.dll
ModLoad: 00007ffb`cead0000 00007ffb`cee1c000   C:\WINDOWS\SYSTEM32\libcrypto-1_1-x64.dll
```

You've definitely got some non-standard files being loaded here. I suggest looking at what apps you've got installed and which ones have inserted themselves into your `PATH` variable. It's likely one of them causing you issues.

**Comment by eugenesmsk** [comment]
Thank you very much, I indeed found an environment variable related to OpenSSL.
