### ISSUE TITLE
The new REPL outputs different tracebeck when custom sys.excepthook is used

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#122478]
# Bug report

If `sys.systemhook` is not `sys.__systemhook__`, the new REPL outputs the line in the code module in the traceback:
```pycon
>>> xxx
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    xxx
NameError: name 'xxx' is not defined
>>> import sys; sys.excepthook = lambda *args: sys.__excepthook__(*args)
>>> xxx
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/code.py", line 91, in runcode
    exec(code, self.locals)
    ~~~~^^^^^^^^^^^^^^^^^^^
  File "<python-input-2>", line 1, in <module>
    xxx
NameError: name 'xxx' is not defined
```

### Linked PRs
* gh-122528
* gh-122816
* gh-122817
* gh-123227

**Comment by serhiy-storchaka** [comment]
And for compile-time errors:
```pycon
>>> ?
  File "<unknown>", line 1
    ?
    ^
SyntaxError: invalid syntax
>>> import sys; sys.excepthook = lambda *args: sys.__excepthook__(*args)
>>> ?
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/_pyrepl/console.py", line 172, in runsource
    tree = ast.parse(source)
  File "/home/serhiy/py/cpython/Lib/ast.py", line 53, in parse
    return compile(source, filename, mode, flags,
                   _feature_version=feature_version, optimize=optimize)
  File "<unknown>", line 1
    ?
    ^
SyntaxError: invalid syntax
```

**Comment by devdanzin** [comment]
Seems to be done on purpose in `code.InteractiveInterpreter.showsyntaxerror`:
https://github.com/python/cpython/blob/bd3d31f380cd451a4ab6da5fbfde463fed95b5b5/Lib/code.py#L126-L132

I suppose this could be overridden in _pyrepl to always output with `.write()`?

**Comment by serhiy-storchaka** [comment]
`sys.excepthook` is of course called on purpose, but the traceback was not corrected for it. And `sys.last_traceback` was not always correct even with the default `sys.excepthook`.

**Comment by skirpichev** [comment]
@serhiy-storchaka, can this be closed?
