### ISSUE TITLE
Python 3.13.0 RC1 fails to build with experimental jit enabled

### ISSUE THREAD

**Issue by wbeebe** [python/cpython#122585]
# Bug report

### Bug description:

Downloaded Python 3.13.0 RC1.

Configured with  `--enable-optimizations --disable-gil --enable-experimental-jit=yes`

This has worked in the past with beta releases. There was nothing in the README to indicate anything had changed, and executing `configure --help` still produces the same CL switch.

After configuration ran `make`:

```python
  + Exception Group Traceback (most recent call last):
  |   File "/home/mint/Develop/Python-3.13.0rc1/Tools/jit/_targets.py", line 189, in _build_stencils
  |     async with asyncio.TaskGroup() as group:
  |     ...<4 lines>...
  |             tasks.append(group.create_task(coro, name=opname))
  |   File "/usr/local/lib/python3.13/asyncio/taskgroups.py", line 154, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/mint/Develop/Python-3.13.0rc1/Tools/jit/_targets.py", line 181, in _compile
    |     return await self._parse(o)
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "/home/mint/Develop/Python-3.13.0rc1/Tools/jit/_targets.py", line 80, in _parse
    |     output = await _llvm.run("llvm-readobj", args, echo=self.verbose)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/mint/Develop/Python-3.13.0rc1/Tools/jit/_llvm.py", line 99, in run
    |     raise RuntimeError(f"Can't find {tool}-{_LLVM_VERSION}!")
    | RuntimeError: Can't find llvm-readobj-18!
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/home/mint/Develop/Python-3.13.0rc1/Tools/jit/_targets.py", line 181, in _compile
    |     return await self._parse(o)
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "/home/mint/Develop/Python-3.13.0rc1/Tools/jit/_targets.py", line 80, in _parse
    |     output = await _llvm.run("llvm-readobj", args, echo=self.verbose)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/mint/Develop/Python-3.13.0rc1/Tools/jit/_llvm.py", line 99, in run
    |     raise RuntimeError(f"Can't find {tool}-{_LLVM_VERSION}!")
    | RuntimeError: Can't find llvm-readobj-18!
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mint/Develop/build-python/../Python-3.13.0rc1/Tools/jit/build.py", line 28, in <module>
    args.target.build(pathlib.Path.cwd(), comment=comment, force=args.force)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Develop/Python-3.13.0rc1/Tools/jit/_targets.py", line 214, in build
    stencil_groups = asyncio.run(self._build_stencils())
  File "/usr/local/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/mint/Develop/Python-3.13.0rc1/Tools/jit/_targets.py", line 187, in _build_stencils
    with tempfile.TemporaryDirectory() as tempdir:
    ...<6 lines>...
                tasks.append(group.create_task(coro, name=opname))
  File "/usr/local/lib/python3.13/tempfile.py", line 946, in __exit__
    self.cleanup()
    ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/tempfile.py", line 950, in cleanup
    self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/tempfile.py", line 930, in _rmtree
    _shutil.rmtree(name, onexc=onexc)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/shutil.py", line 763, in rmtree
    _rmtree_safe_fd(stack, onexc)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/shutil.py", line 707, in _rmtree_safe_fd
    onexc(func, path, err)
    ~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/shutil.py", line 658, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=dirfd)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/tmp/tmpjdmfpk8t'
```
I'm rebuilding with JIT enabled.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by brandtbucher** [comment]
It looks like you need to install LLVM (specifically, `llvm-readobj`).

Did you follow the install instructions in the [JIT README](https://github.com/python/cpython/blob/main/Tools/jit/README.md#installing-llvm)? Are you able to run `llvm-readobj --version` or `llvm-readobj-18 --version` on the command line?

**Comment by wbeebe** [comment]
Yes, I did. That was what I did with the betas.

**Comment by brandtbucher** [comment]
So you can find `llvm-readobj-18` on the command line, but the build script can't?

I ask because there was a recent LLVM packaging issue where this tool wasn't correctly installed. I think it's since been fixed, but if you recently reinstalled LLVM on Ubuntu then the botched release might have messed things up. Nothing related to how we find these tools has changed recently.

**Comment by wbeebe** [comment]
Just delete this.
