### ISSUE TITLE
ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by ksch6719** [python/cpython#122639]
# Bug report

### Bug description:

Hi,

when installing pyload-ng with pip (Synology DSM 7.1.1-42962 Update 5, Entware) I get the python error listed below. What could be the reason for this? The package cffi is installed, I have already tried to reinstall it - but that didn't help.

...

Collecting zstandard (from Flask-Compress~=1.8->pyload-ng)
Using cached zstandard-0.23.0.tar.gz (681 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error

Ã Getting requirements to build wheel did not run successfully.
â exit code: 1
â°â> [22 lines of output]
:41: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
:42: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
Traceback (most recent call last):
File "/opt/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in
File "/opt/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
File "/opt/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
File "/opt/tmp/pip-build-env-cm07uzhp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
return self._get_build_requires(config_settings, requirements=['wheel'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/tmp/pip-build-env-cm07uzhp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
self.run_setup()
File "/opt/tmp/pip-build-env-cm07uzhp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
File "/opt/tmp/pip-build-env-cm07uzhp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
exec(code, locals())
File "", line 112, in
File "/opt/tmp/pip-install-gw8o4f6x/zstandard_b8382a9755bc478f9f173324aa2c2ec3/make_cffi.py", line 161, in
ffi = cffi.FFI()
^^^^^^^^^^
File "/opt/tmp/pip-build-env-cm07uzhp/overlay/lib/python3.11/site-packages/cffi/api.py", line 48, in init
import _cffi_backend as backend
ModuleNotFoundError: No module named '_cffi_backend'
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Ã Getting requirements to build wheel did not run successfully.
â exit code: 1
â°â> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Hello!
This repository is intended as a bug tracker for CPython.
Your question isn't related to CPython, please ask it there: https://discuss.python.org/c/help
