### ISSUE TITLE
test.support.socket_helper fails to handle test_urllib2net.TimeoutTest exception

### ISSUE THREAD

**Issue by encukou** [python/cpython#122967]
Recent  buildbot runs like [bigmem](https://buildbot.python.org/#/builders/1079/builds/4538/steps/5/logs/stdio) or [Fedora](https://buildbot.python.org/#/builders/1426/builds/274/steps/6/logs/stdio) show this in `test_urllib2net.TimeoutTest`:

- `ftplib` raises its TimeoutError (`error_temp`: 421 Timeout -- `temp` because FTP 4xx is ”Transient [=temporary] Negative Completion reply”)
- `urllib` wraps it in `urllib.error.URLError`
- `test.support.socket_helper` assumes the error's `reason` is a string, put it's a `error_temp` object.

```
======================================================================
ERROR: test_ftp_no_timeout (test.test_urllib2net.TimeoutTest.test_ftp_no_timeout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\urllib\request.py", line 1548, in ftp_open
    fp, retrlen = fw.retrfile(file, type)
                  ~~~~~~~~~~~^^^^^^^^^^^^
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\urllib\request.py", line 2443, in retrfile
    conn, retrlen = self.ftp.ntransfercmd(cmd)
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\ftplib.py", line 353, in ntransfercmd
    host, port = self.makepasv()
                 ~~~~~~~~~~~~~^^
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\ftplib.py", line 327, in makepasv
    untrusted_host, port = parse227(self.sendcmd('PASV'))
                                    ~~~~~~~~~~~~^^^^^^^^
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\ftplib.py", line 281, in sendcmd
    return self.getresp()
           ~~~~~~~~~~~~^^
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\ftplib.py", line 252, in getresp
    raise error_temp(resp)
ftplib.error_temp: 421 Timeout.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\test\support\socket_helper.py", line 249, in transient_internet
    yield
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\test\test_urllib2net.py", line 364, in test_ftp_no_timeout
    u = _urlopen_with_retry(self.FTP_HOST, timeout=None)
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\test\test_urllib2net.py", line 29, in wrapped
    return _retry_thrice(func, exc, *args, **kwargs)
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\test\test_urllib2net.py", line 25, in _retry_thrice
    raise last_exc
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\test\test_urllib2net.py", line 21, in _retry_thrice
    return func(*args, **kwargs)
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\urllib\request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\urllib\request.py", line 489, in open
    response = self._open(req, data)
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\urllib\request.py", line 506, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
                              '_open', req)
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\urllib\request.py", line 1558, in ftp_open
    raise URLError(exp) from exp
urllib.error.URLError: <urlopen error 421 Timeout.>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\test\test_urllib2net.py", line 361, in test_ftp_no_timeout
    with socket_helper.transient_internet(self.FTP_HOST):
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\test\support\socket_helper.py", line 264, in transient_internet
    filter_error(err)
    ~~~~~~~~~~~~^^^^^
  File "R:\buildarea\3.x.ambv-bb-win11.bigmem\build\Lib\test\support\socket_helper.py", line 237, in filter_error
    (("ConnectionRefusedError" in err.reason) or
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'error_temp' is not a container or iterable
```

**Comment by encukou** [comment]
#122999 has more info, closing this as duplicate
