### ISSUE TITLE
test_asyncio test_sendfile_close_peer_in_the_middle_of_receiving fails on ppc64le Linux 6.10.x

### ISSUE THREAD

**Issue by hroncok** [python/cpython#123384]
# Bug report

### Bug description:

Since the Fedora builders were upgraded to Linux kernel 6.10.4 and/or 6.10.5, we see the following test failures when we build CPython on Fedora Linux 39, 40, 41, or 42:

```
======================================================================
FAIL: test_sendfile_close_peer_in_the_middle_of_receiving (test.test_asyncio.test_sendfile.EPollEventLoopTests.test_sendfile_close_peer_in_the_middle_of_receiving)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.12/test/test_asyncio/test_sendfile.py", line 466, in test_sendfile_close_peer_in_the_middle_of_receiving
    with self.assertRaises(ConnectionError):
AssertionError: ConnectionError not raised

======================================================================
FAIL: test_sendfile_close_peer_in_the_middle_of_receiving (test.test_asyncio.test_sendfile.PollEventLoopTests.test_sendfile_close_peer_in_the_middle_of_receiving)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.12/test/test_asyncio/test_sendfile.py", line 466, in test_sendfile_close_peer_in_the_middle_of_receiving
    with self.assertRaises(ConnectionError):
AssertionError: ConnectionError not raised

======================================================================
FAIL: test_sendfile_close_peer_in_the_middle_of_receiving (test.test_asyncio.test_sendfile.SelectEventLoopTests.test_sendfile_close_peer_in_the_middle_of_receiving)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.12/test/test_asyncio/test_sendfile.py", line 466, in test_sendfile_close_peer_in_the_middle_of_receiving
    with self.assertRaises(ConnectionError):
AssertionError: ConnectionError not raised

----------------------------------------------------------------------
Ran 3 tests in 0.103s
```

I was able to reproduce this by upgrading a Fedora Linxu 39 ppc64le machine from an older kernel (6.8.x) to 6.10.6-100.fc39.ppc64le. The failures were not present with the older kernel but are present with the new one. No need to rebuild Python on the new kernel, just run it (e.g. via `python3.12 -m test test_asyncio -wW -j8`).

This is similar to https://github.com/python/cpython/issues/122136 but unlike that, this only happens on ppc64le. This also affects all the supported CPython versions we ship.

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13

### Operating systems tested on:

Linux

**Comment by hroncok** [comment]
a7584245661102a5768c643fbd7db8395fd3c90e

**Comment by hroncok** [comment]
This is a duplicate of https://github.com/python/cpython/issues/120226
