### ISSUE TITLE
Python implementation of traceback limit does not default to 1000 as documented in 3.13

### ISSUE THREAD

**Issue by blhsing** [python/cpython#123596]
# Bug report

### Bug description:

According to the documentation of [`sys.tracebacklimit`](https://docs.python.org/3/library/sys.html#sys.tracebacklimit), it should default to 1000 if not set, so the following snippet:
```
import sys

def f():
    f()

sys.setrecursionlimit(2000)
f()
```
produces a traceback of 1000 frames as expected in 3.12:
```
Traceback (most recent call last):
  File "t.py", line 4, in f
    f()
    ~^^
  File "t.py", line 4, in f
    f()
    ~^^
  File "t.py", line 4, in f
    f()
    ~^^
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded
```
But in 3.13 and the current master, it produces a traceback of all 2000 frames:
```
Traceback (most recent call last):
  File "t.py", line 4, in f
    f()
    ~^^
  File "t.py", line 4, in f
    f()
    ~^^
  File "t.py", line 4, in f
    f()
    ~^^
  File "t.py", line 4, in f
    f()
    ~^^
  [Previous line repeated 1996 more times]
RecursionError: maximum recursion depth exceeded
```
This is because with issue #110721, traceback is now printed with the traceback module by default, and the traceback module defaults `sys.tracebacklimit` to `None` when not set:
https://github.com/python/cpython/blob/c3ed775899eedd47d37f8f1840345b108920e400/Lib/traceback.py#L458

whereas the C implementation of the traceback printer has a proper default of 1000 for `sys.tracebacklimit` as documented:
https://github.com/python/cpython/blob/c3ed775899eedd47d37f8f1840345b108920e400/Python/traceback.c#L707

I will submit a PR to make 1000 the default value for `sys.tracebacklimit` in the Python implementation of the traceback module.

### CPython versions tested on:

3.13, CPython main branch

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-125719
* gh-125777

**Comment by rruuaanng** [comment]
Are you still studying the problem? If you are ready to submit, maybe I will close my submission. Be sorry.:)

**Comment by blhsing** [comment]
> Are you still studying the problem? If you are ready to submit, maybe I will close my submission. Be sorry.:)

I went with the `limit = getattr(sys, 'tracebacklimit', 1000)` route in my attempt to fix the code but had been dealing with a failed existing test. I think your approach of simply setting `sys.tracebacklimit` to `1000` is both easier and cleaner. 👍

**Comment by rruuaanng** [comment]
@blhsing  Are you still working on it? If you are done, you can submit a PR. My PR is waiting for your submission before it can be merged.
