### ISSUE TITLE
test_socket failed when compiling from source (Python 3.12.5)

### ISSUE THREAD

**Issue by Cryo81** [python/cpython#123645]
### Bug description:

Hello, I'm running into several compilation error when compiling python from source on a clean debian on WSL2 (Windows 10)
```
0:01:24 load avg: 0.52 [393/489/26] test_socket failed (205 errors, 48 failures) (1 min) -- running (4): test_signal (39.4 sec), test.test_concurrent_futures.test_deadlock (35.4 sec), test_json (35.5 sec), test_hashlib (35.8 sec)
Warning -- Unraisable exception
Exception ignored in thread started by: <bound method ThreadableTest.clientRun of <test.test_socket.BasicUDPLITETest testMethod=testRecvFrom>>
Traceback (most recent call last):
  File "REDACTED/Python-3.12.5/Lib/test/test_socket.py", line 376, in clientRun
    self.clientTearDown()
  File "REDACTED/Python-3.12.5/Lib/test/test_socket.py", line 439, in clientTearDown
    self.cli.close()
    ^^^^^^^^
AttributeError: 'BasicUDPLITETest' object has no attribute 'cli'
Warning -- Unraisable exception
Exception ignored in thread started by: <bound method ThreadableTest.clientRun of <test.test_socket.BasicUDPLITETest testMethod=testRecvFromNegative>>
Traceback (most recent call last):
  File "REDACTED/Python-3.12.5/Lib/test/test_socket.py", line 376, in clientRun
    self.clientTearDown()
  File "REDACTED/Python-3.12.5/Lib/test/test_socket.py", line 439, in clientTearDown
    self.cli.close()
    ^^^^^^^^
[...]
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Other

**Comment by Cryo81** [comment]
Don't mind me I solved my issues by reinstalling WSL 2 from scratch and installing the dependencies following "https://devguide.python.org/getting-started/setup-building/index.html#deps-on-linux"

Especially :
1. Adding this line in /etc/apt/sources.list
```
deb-src http://deb.debian.org/debian bookworm main
```
2. Downloading the dependencies with:
```
sudo apt-get build-dep python3
sudo apt-get install pkg-config
sudo apt-get install build-essential gdb lcov pkg-config \
      libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
      libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev \
      lzma lzma-dev tk-dev uuid-dev zlib1g-dev libmpdec-dev
```
Have a good day!

**Comment by picnixz** [comment]
Closing as `OP fixed the issue`
