### ISSUE TITLE
test_pyrepl fails on x86-64 macOS buildbot -- setupterm: could not find terminfo database

### ISSUE THREAD

**Issue by encukou** [python/cpython#123944]
`test_pyrepl` fails on a specific buildbot on 3.14 (e.g. [here](https://buildbot.python.org/#/builders/366/builds/7631)) and 3.13 (e.g. [here](https://buildbot.python.org/#/builders/1483/builds/97)):

```
test_readline_history_file (test.test_pyrepl.test_pyrepl.TestMain.test_readline_history_file) ... FAIL
======================================================================
FAIL: test_readline_history_file (test.test_pyrepl.test_pyrepl.TestMain.test_readline_history_file)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.13.billenstein-macos/build/Lib/test/test_pyrepl/test_pyrepl.py", line 1305, in test_readline_history_file
    output, exit_code = self.run_repl("exit\n", env=env)
                        ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/buildbot/buildarea/3.13.billenstein-macos/build/Lib/test/test_pyrepl/test_pyrepl.py", line 1225, in run_repl
    return self._run_repl(
           ~~~~~~~~~~~~~~^
        repl_input, env=env, cmdline_args=cmdline_args, cwd=cwd
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/buildbot/buildarea/3.13.billenstein-macos/build/Lib/test/test_pyrepl/test_pyrepl.py", line 1276, in _run_repl
    self.fail(f"Timeout while waiting for output, got: {''.join(output)}")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Timeout while waiting for output, got: exit
Python 3.13.0rc2+ (heads/3.13:660baa14d69, Sep  6 2024, 17:27:02) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
warning: can't use pyrepl: setupterm: could not find terminfo database
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> 
```
This looks similar to #121988. The test was added in #121779.

**Comment by emilyemorehouse** [comment]
This is duplicated by https://github.com/python/cpython/issues/123870 and is fixed in https://github.com/python/cpython/pull/124396
