### ISSUE TITLE
Calling typing.get_type_hints with a class or instance method with PEP 695 type parameters fails if PEP 563 is enabled

### ISSUE THREAD

**Issue by Parnassius** [python/cpython#124089]
# Bug report

### Bug description:

```python
from __future__ import annotations

import typing

class Test[M]:
    def foo(self, arg: M) -> None:
        pass

print(typing.get_type_hints(Test.foo))
```

```
$ python3.12 pep_695_pep_563.py 
Traceback (most recent call last):
  File "/run/host/tmp/test/pep_695_pep_563.py", line 9, in <module>
    print(typing.get_type_hints(Test.foo))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/typing.py", line 2310, in get_type_hints
    hints[name] = _eval_type(value, globalns, localns, type_params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/typing.py", line 415, in _eval_type
    return t._evaluate(globalns, localns, type_params, recursive_guard=recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/typing.py", line 947, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'M' is not defined
```

This seems very similar to #114053, but with class methods (or instance methods, the result is the same) instead of classes themselves.

Removing the `from __future__ import annotations` import works fine:
```python
import typing

class Test[M]:
    def foo(self, arg: M) -> None:
        pass

print(typing.get_type_hints(Test.foo))
```

```
$ python3.12 pep_695_no_563.py 
{'arg': M, 'return': <class 'NoneType'>}
```

Using the pre PEP-695 syntax, with or without `from __future__ import annotations`, works fine as well:
```python
from __future__ import annotations

import typing

M = typing.TypeVar("M")

class Test(typing.Generic[M]):
    def foo(self, arg: M) -> None:
        pass

print(typing.get_type_hints(Test.foo))
```

```
$ python3.12 no_695_pep_563.py 
{'arg': ~M, 'return': <class 'NoneType'>}
```

```python
import typing

M = typing.TypeVar("M")

class Test(typing.Generic[M]):
    def foo(self, arg: M) -> None:
        pass

print(typing.get_type_hints(Test.foo))
```

```
$ python3.12 no_695_no_563.py 
{'arg': ~M, 'return': <class 'NoneType'>}
```

This happens on both 3.12.5 and 3.13.0rc2

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Linux

**Comment by sobolevn** [comment]
Can replicate it on `main`:

```
» ./python.exe ex.py
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython2/ex.py", line 9, in <module>
    print(typing.get_type_hints(Test.foo))
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython2/Lib/typing.py", line 2465, in get_type_hints
    hints[name] = _eval_type(value, globalns, localns, type_params, format=format, owner=obj)
                  ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython2/Lib/typing.py", line 481, in _eval_type
    return evaluate_forward_ref(t, globals=globalns, locals=localns,
                                type_params=type_params, owner=owner,
                                _recursive_guard=recursive_guard, format=format)
  File "/Users/sobolev/Desktop/cpython2/Lib/typing.py", line 1073, in evaluate_forward_ref
    value = forward_ref.evaluate(globals=globals, locals=locals,
                                 type_params=type_params, owner=owner)
  File "/Users/sobolev/Desktop/cpython2/Lib/annotationlib.py", line 152, in evaluate
    value = eval(code, globals=globals, locals=locals)
  File "<string>", line 1, in <module>
NameError: name 'M' is not defined
```

I will take a look, thanks for the report.

**Comment by sobolevn** [comment]
From the first sight - there's not much of what can be done, because `Test.foo` does not have any refences to `Test` and has a type `<function>`. It also does not have any `__type_params__` set. And `__annotate__` of `<function>` does not even get called.

There are literally no ways of accessing `Test.__type_params__` from `Test.foo` that I am aware of.

Except for this piece of hackery: `obj.__globals__[obj.__qualname__.split('.')[0]]`
But, I don't think that it is good enough. 

I think that we might need some special handling for this.

**Comment by JelleZijlstra** [comment]
I don't think we should change anything here. `from __future__ import annotations` does not interact well with runtime introspection, and that's a major part of why in Python 3.14 we're likely to deprecate it (PEP-749).

In the meantime, if you want reliable runtime introspection, don't use `from __future__ import annotations`.

**Comment by ncanceill** [comment]
(Not sure if worth its own bug report so I am adding here.)

This issue also affects quoted forward references to PEP695-style generic types:
```python
from typing import get_type_hints

class Foo[T]:
    def foo(self) -> "Bar[T]":
        ...

class Bar[T]:
    def bar(self, _: T) -> None:
        ...

get_type_hints(Foo[int].foo)  # NameError: name 'T' is not defined
```

(Is this because `from __future__ import annotations` has the same behavior as quoted annotations?)

Hopefully this is all fixed by PEP649 in 3.14 🤞 

Out of curiosity, I tested `reveal_type` with a couple type checkers. No errors from `mypy` 1.13.0 but still meh:
```python
reveal_type(Foo[int].foo)  # Revealed type is "def (self: Foo[T`1]) -> Bar[T`1]"
```
Much better result with `pyright` 1.1.389:
```python
reveal_type(Foo[int].foo)  # Type of "Foo[int].foo" is "(self: Foo[int]) -> Bar[int]"
```

**Comment by JelleZijlstra** [comment]
@ncanceill yes, that seems like the same thing. `from __future__ import annotations` is broadly equivalent to putting quotes around all of your annotations.
