### ISSUE TITLE
test_strsignal fails on NetBSD with TypeError

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#124083]
# Bug report

### Bug description:

```sh
-bash-5.2$ ./python -m test test_signal -m test_strsignal
Using random seed: 3137472754
0:00:00 load avg: 5.12 Run 1 test sequentially in a single process
0:00:00 load avg: 5.12 [1/1] test_signal
test test_signal failed -- Traceback (most recent call last):
  File "/home/blue/cpython/Lib/test/test_signal.py", line 127, in test_strsignal
    self.assertIn("Interrupt", signal.strsignal(signal.SIGINT))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/blue/cpython/Lib/unittest/case.py", line 1180, in assertIn
    if member not in container:
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not a container or iterable

test_signal failed (1 error)

== Tests result: FAILURE ==

1 test failed:
    test_signal

Total duration: 142 ms
Total tests: run=1 (filtered)
Total test files: run=1/1 (filtered) failed=1
Result: FAILURE
```

OS: `NetBSD 10.0 amd64`

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

### Linked PRs
* gh-124084
* gh-124223
* gh-124224

**Comment by furkanonder** [comment]
The `SIGTERM` and `SIGHUP` signals also fail.

```python
Python 3.14.0a0 (heads/main:b1d6f8a2ee0, Sep 14 2024, 03:26:32) [GCC 10.5.0] on netbsd10
Type "help", "copyright", "credits" or "license" for more information.
warning: can't use pyrepl: No module named 'msvcrt'
>>> import signal
>>> signal.strsignal(signal.SIGINT) is None
True
>>> signal.strsignal(signal.SIGTERM) is None
True
>>> signal.strsignal(signal.SIGHUP) is None
True
>>>
```

```c
-bash-5.2$ cat test_signals.c
#include <stdio.h>
#include <signal.h>
#include <errno.h>
#include <string.h>

int main() {
    int signalnums[] = {2, 15, 1}; // Signal numbers for SIGINT (2), SIGTERM (15), and SIGHUP (1)
    const char *res;
    int num_signals = sizeof(signalnums) / sizeof(signalnums[0]);

    for (int i = 0; i < num_signals; i++) {
        errno = 0;
        res = strsignal(signalnums[i]);

        printf("Signal number: %d\n", signalnums[i]);
        printf("Str of signal: %s\n", res);
        printf("errno: %d\n", errno);
    }

    return 0;
}
-bash-5.2$ gcc test_signals.c
-bash-5.2$ ./a.out
Signal number: 2
Str of signal: Interrupt
errno: 2
Signal number: 15
Str of signal: Terminated
errno: 2
Signal number: 1
Str of signal: Hangup
errno: 2

```

**Comment by vstinner** [comment]
Fixed by the change https://github.com/python/cpython/commit/36682c091407dc9c7e750c22fb71e62466952662. Backports will follow.
