### ISSUE TITLE
`get_type_hints(K format=FORWARDREF)` raises when `K` is dynamically created class

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#124206]
# Bug report

On `main` this raises:

```python
>>> from typing import get_type_hints
>>> K = type('K', (), {})
>>> get_type_hints(K)
{}
>>> get_type_hints(K, format=2)
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    get_type_hints(K, format=2)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython2/Lib/typing.py", line 2393, in get_type_hints
    ann = annotationlib.get_annotations(base, format=format)
  File "/Users/sobolev/Desktop/cpython2/Lib/annotationlib.py", line 634, in get_annotations
    annotate = get_annotate_function(obj)
  File "/Users/sobolev/Desktop/cpython2/Lib/annotationlib.py", line 578, in get_annotate_function
    return _BASE_GET_ANNOTATE(obj)
AttributeError: type object 'object' has no attribute '__annotate__'
```

However, this does not raise:

```python
>>> from inspect import get_annotations
>>> K = type('K', (), {})
>>> get_annotations(K)
{}
>>> get_annotations(K, format=2)
{}
```

I suppose that this is a bug.

### Linked PRs
* gh-124208

**Comment by JelleZijlstra** [comment]
Note this isn't limited to dynamic creation:

```
>>> class C:
...     x: int
...     
>>> import typing
>>> import annotationlib
>>> typing.get_type_hints(C, format=annotationlib.Format.FORWARDREF)
Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    typing.get_type_hints(C, format=annotationlib.Format.FORWARDREF)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jelle/py/cpython/Lib/typing.py", line 2393, in get_type_hints
    ann = annotationlib.get_annotations(base, format=format)
  File "/Users/jelle/py/cpython/Lib/annotationlib.py", line 634, in get_annotations
    annotate = get_annotate_function(obj)
  File "/Users/jelle/py/cpython/Lib/annotationlib.py", line 578, in get_annotate_function
    return _BASE_GET_ANNOTATE(obj)
AttributeError: type object 'object' has no attribute '__annotate__'
```

Thanks for the report, sending a PR with a fix in a moment.
