### ISSUE TITLE
Do not raise an Exception when exiting pdb

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#124703]
# Feature or enhancement

### Proposal:

Currently, if you set a `breakpoint()` in your code, and exit with `q` or `ctrl+D`, the output is just ugly:

```
Traceback (most recent call last):
  File "/Users/gaotian/programs/cpython/example.py", line 11, in <module>
    while True:
          ^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
                      ^^^^^^^^^^^^^
bdb.BdbQuit
```

It makes no sense to print a trackback of an exception just because I want to quit pdb and stop debugging. Now that we have an indicator for inline mode, we can deal with this.

What I propose is - for inline mode debugging, any quit attempt(`q`, `ctrl+D`, etc.) will trigger a confirm prompt (like `gdb` or `lldb`), the user can say no and go back to debugging, or they can confirm and quit the program.

There are a few design details which I will list in the following PR.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-124704
* gh-129768
* gh-129818
* gh-130286
* gh-130395
* gh-133013

**Comment by ADThomas-astro** [comment]
I'd like to reopen this issue.

The committed changes mean that quitting pdb also quits the REPL.  This was mentioned on PR 124704 but I don't think there was enough discussion.  It's been longstanding in Python that you can call breakpoint() in a REPL session and then return to the REPL prompt after debugging.  I agree that the traceback was ugly but I think not being able to return to the REPL from pdb is a regression and a worse user experience problem than a short traceback being printed.  There could be a lot of state in a REPL session that a user of older versions of Python would not expect to lose.  And I at least like to jump in and out of the debugger in a REPL session a lot (admittedly in ipython, but with the new PyREPL I'd like to do it in PyREPL too!)

I propose a compromise (PR on the way).  The recently merged PR 124704 adds a prompt "Quit anyway? [y/n]".  Since we're prompting the user now, why not let them choose how to quit?  If they're stuck in an infinite loop or finished with interactive work they can choose to kill the process immediately and cleanly, but they can also exit normally (raise BdbQuit) and return to the REPL.

In my proposed changes I also added some code to shorten the BdbQuit traceback.  It's still ugly though, and I don't know how to remove or further improve it.

**Comment by gaogaotiantian** [comment]
I think the correct way to "return from breakpoint to repl" should be `continue`, not `quit` - you can do that now.

We can see how many people are affected by this change, because personally I never use `breakpoint()` in REPL, debugging some interactive code seems a bit weird to me, but other people might use it.

I don't believe the PR works though, we should keep the normal path clean (`y/n` is much more common than some random options). If we had to deal with this, we should make `pdb` or PyREPL consider this a special case and deal with it. The last spot is to revert the change, shortening the traceback does not help that much.

**Comment by gaogaotiantian** [comment]
Quick question - did you try this on ipython and confirm it will exit the shell? I don't think it will exit ipython as ipython catches `SystemExit`.

**Comment by ADThomas-astro** [comment]
> Quick question - did you try this on ipython and confirm it will exit the shell?

Nope 🤦 I intended to but forgot.  Indeed ipython does catch SystemExit.  This is what it looks like:

![Image](https://github.com/user-attachments/assets/68c1d255-a4da-461b-a1eb-9e75f8eb1320)

Thankfully it doesn't exit the process but I still think this is a worse experience than the BdbQuit traceback printed previously.

Summary
---------
When using breakpoint()/set_trace() in an interactive REPL session then entering q/quit/exit in pdb, previously in all cases a BdbQuit traceback was printed and the user returned to the REPL.  But now:
 - iPython - There is a prompt that warns that the process will be terminated; if the user proceeds then the process isn't terminated; SystemError is caught and iPython issues a confusing UserWarning when returning to the REPL
 - PyREPL - There is a prompt that warns the process will be terminated; if the user proceeds the process _is_ terminated, with no reliable way to exit back to the REPL.
 - Vanilla Python REPL - Same as PyREPL.

I think the change makes the experience of doing serious work in REPLs worse.

I think we could return to the previous behaviour with the following code in set_trace:

```
        mode = 'inline-repl' if hasattr(sys, 'ps1') else 'inline'
        pdb = Pdb(mode=mode)
```

This would keep much of the benefit of the existing code while preventing the experience in REPLs from becoming worse.

**Comment by ADThomas-astro** [comment]
Actually on further investigation, iPython has been catching bdb.BdbQuit for a while now, so users don't even see a traceback. (I've mostly been using older versions).

**Comment by gaogaotiantian** [comment]
We don't need another mode, that's just too complicated. We can add the `hasattr(sys, "ps1")` check in `do_quit` to keep the previous behavior for interactive consoles.

**Comment by ADThomas-astro** [comment]
That also works; want me to send a PR?

**Comment by gaogaotiantian** [comment]
Sure, it's your idea, feel free to send a PR. I don't know how easy it is to create a regression test with repl. If it's possible, that would also be appreciated.

**Comment by asottile** [comment]
hi -- just ran into this for the first time -- I feel like exiting `0` is problematic because previously it would exit nonzero and cancel the process

consider something like:

```bash
python some_program_with_debugger.py && do-dangerous-thing
```

previously when debugging if you quit in the middle of the program that would result in an unsuccessful exit code -- but after this patch it now exits 0 (despite the program not being successful -- in fact it was *explicitly* cancelled)

**Comment by gaogaotiantian** [comment]
I think you are right. The example might be a bit artificial but I agree a return code of something other than `0` makes more sense. #133013 is made to change it - it's lucky that you caught this before beta freeze, everything is simpler :).

**Comment by UltraGreed** [comment]
Hello. Is there a way to disable this confirmation prompt?

**Comment by gaogaotiantian** [comment]
> Hello. Is there a way to disable this confirmation prompt?

In what way and what's the incentive? If you don't like typing `y` (I also think that's a bit extra work), you can do `Ctrl+D` twice, which is almost as fast as before. If you are inheriting `pdb.Pdb`, you can set `mode` to anything other than `inline`. If you just do a `breakpoint()` in your code, what would be an expected way to turn this off? An env var? I don't think that exists at this point. Also I don't think any of the pdb behaviors is controlled by an env var. Or a `.pdbrc`? That is not available either.
