### ISSUE TITLE
Improve tracebacks for C functions (pass information about arguments)

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#124819]
# Feature or enhancement

### Proposal:

Right now tracebacks look like this:
```pycon
>>> math.log(2,-2)
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    math.log(2,-2)
    ~~~~~~~~^^^^^^
ValueError: expected a positive input
```
i.e. the whole list of parameters is highlighted.

But in many cases errors in C functions coming e.g. from input validation and related to very specific argument.  I think we can pass this additional information with exception to get traceback like this instead:
```pycon
>>> math.log(2,-2)
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    math.log(2,-2)
    ~~~~~~~~   ^^
ValueError: expected a positive input
```

### Has this already been discussed elsewhere?

No response given

**Comment by JelleZijlstra** [comment]
I think this would be useful, but it might not be feasible. By the time we get to the function call, the arguments are just a tuple, and we don't know where they came from. But maybe @pablogsal can think of a way to make this work.

**Comment by skirpichev** [comment]
> the arguments are just a tuple, and we don't know where they came from

I hope that the argument index is all we need to pass.

**Comment by pablogsal** [comment]
Will try to design something. We have the same challenge in any case in Python functions because the error happens in the callee not in the caller.

**Comment by skirpichev** [comment]
@pablogsal, if you don't see reasons to reject this - it's already helps.

**Comment by pablogsal** [comment]
> @pablogsal, if you don't see reasons to reject this 

No reasons to reject it! We just need to find a way to make it generic without introducing too much complexity or performance hits. 

> - it's already helps.

Not sure I understand this. What do you mean?

**Comment by skirpichev** [comment]
> What do you mean?

Well, if someone with a better knowledge in topic can't reject some idea - it might worth to dig into and try to implement the proposal.  At least for me.

**Comment by pablogsal** [comment]
Ah I get what you mean now! Don't worry I will do some research first to evaluate how complicated will be to add some generic support for this and will report back

**Comment by pablogsal** [comment]
I have tried this a bunch of ways and I could not find a way to implement this without adding a ton of complexity everywhere  so I am afraid that unless someone has some better idea we will reject this :(
