### ISSUE TITLE
3.9 GHA: "Ubuntu SSL tests with OpenSSL (3.1.3)" fails

### ISSUE THREAD

**Issue by encukou** [python/cpython#125185]
Ubuntu SSL tests with OpenSSL (3.1.3) fail on a 3.9 PR with:

```
*** Installing runtime programs
install apps/openssl -> /home/runner/work/cpython/cpython/multissl/openssl/3.1.3/bin/openssl
install tools/c_rehash -> /home/runner/work/cpython/cpython/multissl/openssl/3.1.3/bin/c_rehash
/home/runner/work/cpython/cpython/multissl/openssl/3.1.3/bin/openssl: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "Tools/ssl/multissltests.py", line 531, in <module>
    main()
  File "Tools/ssl/multissltests.py", line 488, in main
    build.install()
  File "Tools/ssl/multissltests.py", line 336, in install
    version = self.openssl_version
  File "Tools/ssl/multissltests.py", line 206, in openssl_version
    return self._subprocess_output(cmd)
  File "Tools/ssl/multissltests.py", line 242, in _subprocess_output
    out = subprocess.check_output(cmd, env=env, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/runner/work/cpython/cpython/multissl/openssl/3.1.3/bin/openssl', 'version']' returned non-zero exit status 127.
```
See: https://github.com/python/cpython/actions/runs/11253059317/job/31291630236?pr=125176

The SSL tests are usually skipped, so this might have been the case for some time.

**Comment by encukou** [comment]
Looks like #100454 needs backporting. Let's see if that fixes things.

**Comment by encukou** [comment]
Yup, that was it.
