### ISSUE TITLE
test_importlib test_multiprocessing_pool_circular_import() fails randomly on Thread sanitizer (free-threading) on GitHub Actions

### ISSUE THREAD

**Issue by vstinner** [python/cpython#125221]
Example: https://github.com/python/cpython/actions/runs/11263361511/job/31321078076?pr=125219

```
 0:01:54 load avg: 4.86 [ 9/22/1] test_importlib failed (1 failure) (1 min 35 sec) -- running (2): test_io (1 min 20 sec), test_queue (1 min 3 sec)
test test_importlib failed -- Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/test/test_importlib/test_threaded_import.py", line 255, in test_multiprocessing_pool_circular_import
    script_helper.assert_python_ok(fn)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
  File "/home/runner/work/cpython/cpython/Lib/test/support/script_helper.py", line 182, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "/home/runner/work/cpython/cpython/Lib/test/support/script_helper.py", line 167, in _assert_python
    res.fail(cmd_line)
    ~~~~~~~~^^^^^^^^^^
  File "/home/runner/work/cpython/cpython/Lib/test/support/script_helper.py", line 80, in fail
    raise AssertionError(f"Process return code is {exitcode}\n"
    ...<10 lines>...
                         f"---")
AssertionError: Process return code is 66
command line: ['/home/runner/work/cpython/cpython/python', '-X', 'faulthandler', '-I', '/home/runner/work/cpython/cpython/Lib/test/test_importlib/partial/pool_in_threads.py']

stdout:
---

---

stderr:
---

---
```

### Linked PRs
* gh-125267
* gh-125305

**Comment by colesbury** [comment]
Looks like a data race on `objreduce`:

https://github.com/python/cpython/blob/0c5a48c1c9039eb1ce25a96c43505c4de0a0b9d7/Objects/typeobject.c#L7399-L7409

**Comment by vstinner** [comment]
Thank you for the quick fix @colesbury!
