### ISSUE TITLE
test_resource_tracker_sigkill fails on NetBSD: AssertionError for warning count in test_multiprocessing_fork

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#125620]
# Bug report

### Bug description:

```sh
-bash-5.2$ ./python -m test test_multiprocessing_fork.test_misc -m test_resource_tracker_sigkill
```
```sh
Using random seed: 1947163462
0:00:00 load avg: 0.16 Run 1 test sequentially in a single process
0:00:00 load avg: 0.16 [1/1] test_multiprocessing_fork.test_misc
test test_multiprocessing_fork.test_misc failed -- Traceback (most recent call last):
  File "/home/blue/cpython/Lib/test/_test_multiprocessing.py", line 5766, in test_resource_tracker_sigkill
    self.check_resource_tracker_death(signal.SIGKILL, True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/blue/cpython/Lib/test/_test_multiprocessing.py", line 5748, in check_resource_tracker_death
    self.assertEqual(len(all_warn), 1)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
AssertionError: 0 != 1

test_multiprocessing_fork.test_misc failed (1 failure) in 3 min

== Tests result: FAILURE ==

1 test failed:
    test_multiprocessing_fork.test_misc
```
OS:  NetBSD 10.0

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

### Linked PRs
* gh-125621
* gh-125624
* gh-125627
* gh-125628
* gh-125672
* gh-125673

**Comment by hugovk** [comment]
Triage: closing as I see merged backports, but please re-open if there's more to do.
