### ISSUE TITLE
Exception that calls `super().__init__` breaks `copy.copy`

### ISSUE THREAD

**Issue by jakkdl** [python/cpython#125782]
# Bug report

### Bug description:

For some reason calling `Exception.__init__` breaks `copy.copy`s ability to detect `args`. The following code
```python
import copy

class MyException(Exception):
    def __init__(self, x):
        super().__init__()
        self.x = x

my_exc = MyException(5)
copy.copy(my_exc)
```
gives
```
Traceback (most recent call last):
  File "./foo.py", line 9, in <module>
    copy.copy(my_exc)
  File "/usr/lib/python3.12/copy.py", line 97, in copy
    return _reconstruct(x, None, *rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 253, in _reconstruct
    y = func(*args)
        ^^^^^^^^^^^
TypeError: MyException.__init__() missing 1 required positional argument: 'x'
```

Removing the `super().__init__()` line makes everything work as expected, but given that it's generally seen as good practice to call `super().__init__()` in child classes, and you may be working with a more complex class structure, this seems like pretty bad behavior.
I haven't dug deep enough into `copy.copy` or `BaseException.__init__` to decide which one deserves the blame.

For the reason why I want to copy exceptions, see https://github.com/python-trio/flake8-async/issues/298

### CPython versions tested on:

3.9, 3.10, 3.11, 3.12, 3.13, 3.14

### Operating systems tested on:

Linux

**Comment by jakkdl** [comment]
> Your code would have `copy.copy()` execute `MyException()` directly without passing in `x` and therefore report an error, which is not a Python problem.

no? `copy.copy()` is perfectly capable of passing attributes to `__init__`. This works:
```python
import copy

class MyException(Exception):
    def __init__(self, x):
        # no call to super().__init__()
        self.x = x

my_exc = MyException(5)
my_copy = copy.copy(my_exc)
assert my_copy.x == 5
```

**Comment by ZeroIntensity** [comment]
Yeah, this looks like a bug. Confirmed it on the main branch. Thank you for the report!

**Comment by ZeroIntensity** [comment]
I suspect this is an issue with `copy` rather than `Exception` itself, so I'm marking this as a standard library problem for now. Would you like to try and fix this, @jakkdl?

**Comment by oremanj** [comment]
> copy.copy() is perfectly capable of passing attributes to __init__. This works:

That's a manifestation of the fact that BaseException saves the args on both `__new__` and `__init__`. If you don't override them by calling `__init__` with no arguments, then you get `self.args == (5,)` based on what was passed to the original object's `__new__`.

**Comment by catmeowjiao** [comment]
I'm sorry for my mistake.
