### ISSUE TITLE
Setting an `int` type value to `category` argument of `warnings.warn()` gets a wrong error message

### ISSUE THREAD

**Issue by hyperkai** [python/cpython#125854]
# Bug report

### Bug description:

Setting the `int` type value `100` to `category` argument of [warnings.warn()](https://docs.python.org/3/library/warnings.html#warnings.warn) gets the error message as shown below:

```python
import warnings
                                         # ↓ ↓ Here ↓ ↓
warnings.warn(message='This is a warning', category=100) # Error
```

> TypeError: category must be a Warning subclass, not 'int'

But the superclass [Warning](https://docs.python.org/3/library/exceptions.html#Warning) also works as shown below:

```python
import warnings
                                         # ↓ ↓ ↓ Here ↓ ↓ ↓
warnings.warn(message='This is a warning', category=Warning)
# Warning: This is a warning
#   warnings.warn(message='This is a warning', category=Warning)
```

So, the error message should be something like as shown below:

> TypeError: category must be a Warning superclass or Warning subclass, not 'int'

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-137750

**Comment by asottile-sentry** [comment]
while pedantic I think the error message is already correct for your examples:

```pycon
>>> issubclass(Warning, Warning)
True
```

and your recommendation is incorrect: if a superclass is attempted that's not acceptable:

```pycon
>>> warnings.warn('wat', category=Exception)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: category must be a Warning subclass, not 'type'
```

 (though maybe for things for which `type(category)` is `type` the error message should just show the class itself?)

**Comment by picnixz** [comment]
By convention, a type T is considered to be a subclass of itself, so the message is correct. Closing as a `non-CPython issue`.

**Comment by picnixz** [comment]
Sorry, I didn't see the second comment: 

> (though maybe for things for which type(category) is type the error message should just show the class itself?)

That may be improved so we could probably re-use that issue. Re-opening.

**Comment by picnixz** [comment]
@ncoghlan Should we improve the error message here when someone passes a type object but not a warning subclass? 

```pycon
>>> warnings.warn('wat', category=int)
Traceback (most recent call last):
  File "<python-input-15>", line 1, in <module>
    warnings.warn('wat', category=int)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: category must be a Warning subclass, not 'type'
```

This is not really helpful to have "type" and perhaps it'd be better to have a nicer message for invalid type objects.

**Comment by serhiy-storchaka** [comment]
#137750 fixes a bug reported by @picnixz.
