### ISSUE TITLE
inspect.getsource returns irrelevant text when used in repl on a class defined in place 

### ISSUE THREAD

**Issue by evle-zzz** [python/cpython#126019]
# Bug report

### Bug description:

Run interactive cpython 3.13 with following input.
```python
>>> import inspect
>>> class B: pass
...
>>> inspect.getsource(B)
"# Important: don't add things to this module, as they will end up in the REPL's\n"
```
Instead of class code we get a piece of repl internals. 

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-126032

**Comment by devdanzin** [comment]
Seems related to #122071 and its associated issues, probably due to how linecache works.

**Comment by evle-zzz** [comment]
Just in case, similar small issue nearby:
```python
>>> import dataclasses
>>> inspect.getsource(type(dataclasses)('test'))
Traceback (most recent call last):
  File "<python-input-72>", line 1, in <module>
    inspect.getsource(type(dataclasses)('test'))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\evlez\AppData\Local\Programs\Python\Python313\Lib\inspect.py", line 1256, in getsource
    lines, lnum = getsourcelines(object)
                  ~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\evlez\AppData\Local\Programs\Python\Python313\Lib\inspect.py", line 1238, in getsourcelines
    lines, lnum = findsource(object)
                  ~~~~~~~~~~^^^^^^^^
  File "C:\Users\evlez\AppData\Local\Programs\Python\Python313\Lib\inspect.py", line 1060, in findsource
    file = getsourcefile(object)
  File "C:\Users\evlez\AppData\Local\Programs\Python\Python313\Lib\inspect.py", line 963, in getsourcefile
    filename = getfile(object)
  File "C:\Users\evlez\AppData\Local\Programs\Python\Python313\Lib\inspect.py", line 924, in getfile
    raise TypeError('{!r} is a built-in module'.format(object))
TypeError: <module 'test'> is a built-in module
```
"built-in" is misleading here. That's actually a regular module.
