### ISSUE TITLE
Inconsistent current directory after drive dismount/mount

### ISSUE THREAD

**Issue by k128** [python/cpython#126000]
# Bug report

### Bug description:

After disconnecting and reconnecting my external hard drive (with my current working directory on it), I get surprising results from the os:
```python
>>> os.path.exists('test.csv')
False
>>> os.path.exists(os.path.join(os.getcwd(),'test.csv'))
True
>>> 'test.csv' in list(os.listdir())
True
>>> file=open('test.csv','r')
Traceback (most recent call last):
  File "<python-input-200>", line 1, in <module>
    file=open('test.csv','r')
OSError: [Errno 22] Invalid argument: 'test.csv'

```

Expected behavior: Keep the same working directory and only throw an error or return os.path.exists()=False if it is inaccessible at runtime.  

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by ericvsmith** [comment]
The current directory is invalid. Programs need to be able to deal with this. The only thing that surprises me is that `os.listdir` doesn't return an error. And maybe the first example of `exists` should raise an exception, but I think there's a history of `exists` swallowing exceptions.

**Comment by donBarbos** [comment]
I ran your use case on linux and I got the same result on versions from `3.10` to `main` branch
```python
>>> os.path.exists('test.csv')
False
>>> os.path.exists(os.path.join(os.getcwd(),'test.csv'))
False
>>> 'test.csv' in list(os.listdir())
False
>>> file=open('test.csv','r')
Traceback (most recent call last):
  File "<python-input-5>", line 1, in <module>
    file=open('test.csv','r')
FileNotFoundError: [Errno 2] No such file or directory: 'test.csv'
```

**Comment by encukou** [comment]
This is expected behaviour.

In this situation, the current directory *does not exist* any more. Paths relative to it can't refer to existing files.

But there's a new directory with the *same name*, so an absolute path (via `os.path.join(os.getcwd(), ...)` can name an existing file.

(At least that's how it is on Unix, but based on your report, Windows seems to behave the same way.)
