### ISSUE TITLE
`test_math` fails on Windows

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#126252]
# Bug report

### Bug description:

```python
./python -m test -v test_math
======================================================================
ERROR: test_fma_overflow (test.test_math.FMATests.test_fma_overflow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\eclips4\programming\cpython\Lib\test\test_math.py", line 2801, in test_fma_overflow
    self.assertEqual(math.fma(a, b, -c),
                     ~~~~~~~~^^^^^^^^^^
OverflowError: overflow in fma

======================================================================
FAIL: test_fma_zero_result (test.test_math.FMATests.test_fma_zero_result)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\eclips4\programming\cpython\Lib\test\test_math.py", line 2760, in test_fma_zero_result
    self.assertIsNegativeZero(math.fma(tiny, -tiny, 0.0))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eclips4\programming\cpython\Lib\test\test_math.py", line 2876, in assertIsNegativeZero
    self.assertTrue(
    ~~~~~~~~~~~~~~~^
        value == 0 and math.copysign(1, value) < 0,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        msg="Expected a negative zero, got {!r}".format(value)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
AssertionError: False is not true : Expected a negative zero, got 0.0

======================================================================
FAIL: test_random (test.test_math.FMATests.test_random)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\eclips4\programming\cpython\Lib\test\test_math.py", line 2859, in test_random
    self.assertEqual(math.fma(a, b, c), expected)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 0.5506672157701096 != 0.5506672157701097

----------------------------------------------------------------------
Ran 87 tests in 14.275s

FAILED (failures=2, errors=1, skipped=2)
test test_math failed
test_math failed (1 error, 2 failures)

== Tests result: FAILURE ==

1 test failed:
    test_math

Total duration: 16.3 sec
Total tests: run=87 failures=2 skipped=2
Total test files: run=1/1 failed=1
Result: FAILURE
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

**Comment by tim-one** [comment]
Please show the first line displayed when you open an interactive shell. For example, with the released Python 3.13,.0 on 64-bit Windows from python.org:

```
$ python
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
```

**Comment by Eclips4** [comment]
> Please show the first line displayed when you open an interactive shell. For example, with the released Python 3.13,.0 on 64-bit Windows from python.org:
> 
> ```
> $ python
> Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
> ```

```
Python 3.14.0a1+ (heads/main:0e8665554b2, Oct 31 2024, 18:03:04) [MSC v.1941 64 bit (AMD64)] on win32
```

**Comment by clairvoyante** [comment]
https://developercommunity.visualstudio.com/t/MSVCs-fma-implementation-is-incorrect-o/10594003 ?

**Comment by zooba** [comment]
Given the linked issue, this will be solved by an OS update that we can't control and don't need to do anything about.

Unless someone wants to add a platform-specific tolerance to the test so that the failure goes away (without losing bigger failures such as it starting to return zero), there's no need to keep this open.
