### ISSUE TITLE
`test_embed.InitConfigTests.test_initconfig_api` fails when cpython is built with `--enable-experimental-jit=interpreter`

### ISSUE THREAD

**Issue by mpage** [python/cpython#126255]
# Bug report

### Bug description:

The `test_embed.InitConfigTests.test_initconfig_api` is failing on main when cpython is built with `--enable-experimental-jit=interpreter` at commit `0e8665554b2`. 

To reproduce, build cpython with:

```
> ./configure --enable-experimental-jit=interpreter --with-pydebug && make -j
```

then run

```
> ./python -m test test_embed --match test_initconfig_api

== CPython 3.14.0a1+ (bisect/bad:2d37c719ed7, Oct 31 2024, 11:39:42) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)]
== Linux-5.19.0-0_fbk21_hardened_12633_g4db063a1bcb5-x86_64-with-glibc2.34 little-endian
== Python build: debug JIT-interpreter
== cwd: /data/users/mpage/cpython/build/test_python_worker_1315808æ
== CPU count: 56
== encodings: locale=UTF-8 FS=utf-8
== resources: all test resources are disabled, use -u option to unskip tests

Using random seed: 2318555454
0:00:00 load avg: 1.23 Run 1 test sequentially in a single process
0:00:00 load avg: 1.23 [1/1] test_embed
test_initconfig_api (test.test_embed.InitConfigTests.test_initconfig_api)
configure_locale ... FAIL

======================================================================
FAIL: test_initconfig_api (test.test_embed.InitConfigTests.test_initconfig_api)
configure_locale
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/mpage/cpython/Lib/test/test_embed.py", line 1783, in test_initconfig_api
    self.check_all_configs("test_initconfig_api", config, preconfig,
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                           api=API_ISOLATED)
                           ^^^^^^^^^^^^^^^^^
  File "/data/users/mpage/cpython/Lib/test/test_embed.py", line 928, in check_all_configs
    self.assertEqual(err.rstrip(), stderr)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
AssertionError: '<sys>:0: RuntimeWarning: JIT deactivated as perf profiling support is active' != ''
- <sys>:0: RuntimeWarning: JIT deactivated as perf profiling support is active


----------------------------------------------------------------------
Ran 1 test in 0.112s

FAILED (failures=1)
test test_embed failed
test_embed failed (1 failure)

== Tests result: FAILURE ==

1 test failed:
    test_embed

Total duration: 182 ms
Total tests: run=1 (filtered) failures=1
Total test files: run=1/1 (filtered) failed=1
Result: FAILURE
>
```

The failure bisects to https://github.com/python/cpython/pull/124856. cc @pablogsal 

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-126302

**Comment by Eclips4** [comment]
This is a known issue, see https://github.com/python/cpython/pull/126166
