### ISSUE TITLE
``test_os.test_attributes()`` fails on Windows

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#126253]
# Bug report

### Bug description:

```python
./python -m test -v test_os
======================================================================
FAIL: test_attributes (test.test_os.TestScandir.test_attributes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\eclips4\programming\cpython\Lib\test\test_os.py", line 5040, in test_attributes
    self.check_entry(entry, 'dir', True, False, False)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eclips4\programming\cpython\Lib\test\test_os.py", line 5008, in check_entry
    self.assert_stat_equal(entry.stat(),
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
                           entry_stat,
                           ^^^^^^^^^^^
                           os.name == 'nt' and not is_symlink)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eclips4\programming\cpython\Lib\test\test_os.py", line 4967, in assert_stat_equal
    self.assertEqual(getattr(stat1, attr),
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
                     getattr(stat2, attr),
                     ^^^^^^^^^^^^^^^^^^^^^
                     (stat1, stat2, attr))
                     ^^^^^^^^^^^^^^^^^^^^^
AssertionError: 16 != 268435472 : (os.stat_result(st_mode=16895, st_ino=0, st_dev=0, st_nlink=0, st_uid=0, st_gid=0, st_size=0, st_atime=1730398311, st_mtime=1730398311, st_ctime=1730398311), os.stat_result(st_mode=16895, st_ino=5066549580979864, st_dev=2642700522657803134, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1730398311, st_mtime=1730398311, st_ctime=1730398311), 'st_file_attributes')

----------------------------------------------------------------------
Ran 367 tests in 16.254s

FAILED (failures=1, skipped=146)
test test_os failed
test_os failed (1 failure)

== Tests result: FAILURE ==

1 test failed:
    test_os

Total duration: 21.1 sec
Total tests: run=367 failures=1 skipped=146
Total test files: run=1/1 failed=1
Result: FAILURE
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

**Comment by zooba** [comment]
What's your exact OS build number? This function will have been affected by more recent Windows updates, though I've never seen this behaviour before.

**Comment by Eclips4** [comment]
> What's your exact OS build number?

Not that familiar with Windows so not sure what do you mean
```
PS C:\Users\eclips4> (Get-ComputerInfo).WindowsBuildLabEx
26100.1.amd64fre.ge_release.240331-1435
```
FWIW, this is a Windows 11 which I downloaded two days ago. So, yes, this build should be pretty new.

**Comment by zooba** [comment]
Okay, so I have the same build and it doesn't repro here, but I noticed that `268435472` = `0x10000010` which is 16 plus an invalid bit. So my guess is that the API underlying the regular `stat()` call is not filtering out unknown bits and your file system is somehow deciding to return one.

Not sure what the best approach here would be. There's a `FILE_ATTRIBUTE_VALID_FLAGS` constant but it changes with our build settings. Masking inside `stat` would clear out the extra bit, but if it ever became meaningful then we'd need to update Python to see it. We can probably filter the test quite reasonably to mask with `0x0000FFFF` first (any actual use of this field should be checking for certain bits, so the extra one isn't an issue), so maybe that's good enough here?
