### ISSUE TITLE
Thread sanitizer (free-threading) / Thread sanitizer test failure

### ISSUE THREAD

**Issue by Zheaoli** [python/cpython#126445]
# Bug report

### Bug description:

```text
0:00:00 load avg: 1.17 Run 22 tests in parallel using 4 worker processes
0:00:04 load avg: 1.40 [ 1/22] test_capi.test_pyatomic passed
0:00:10 load avg: 1.60 [ 2/22] test_code passed
0:00:18 load avg: 1.80 [ 3/22] test_functools passed
0:00:18 load avg: 1.80 [ 4/22] test_capi.test_mem passed
0:00:34 load avg: 2.22 [ 5/22] test_httpservers passed -- running (1): test_enum (34.0 sec)
0:00:40 load avg: 2.42 [ 6/22] test_imaplib passed -- running (1): test_enum (40.6 sec)
0:00:51 load avg: 2.66 [ 7/22] test_enum passed (51.0 sec) -- running (1): test_importlib (32.4 sec)
0:01:21 load avg: 4.29 running (4): test_importlib (1 min 2 sec), test_logging (40.4 sec), test_io (47.1 sec), test_queue (30.0 sec)
0:01:31 load avg: 5.08 [ 8/22] test_logging passed (50.9 sec) -- running (3): test_importlib (1 min [12](https://github.com/python/cpython/actions/runs/11683874532/job/32533990920?pr=126437#step:12:13) sec), test_io (57.5 sec), test_queue (40.5 sec)
0:01:59 load avg: 6.72 [ 9/22/1] test_importlib failed (1 failure) (1 min 40 sec) -- running (2): test_io (1 min 25 sec), test_queue (1 min 8 sec)
test test_importlib failed -- Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/test/test_importlib/test_threaded_import.py", line 255, in test_multiprocessing_pool_circular_import
    script_helper.assert_python_ok(fn)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
  File "/home/runner/work/cpython/cpython/Lib/test/support/script_helper.py", line 182, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "/home/runner/work/cpython/cpython/Lib/test/support/script_helper.py", line [16](https://github.com/python/cpython/actions/runs/11683874532/job/32533990920?pr=126437#step:12:17)7, in _assert_python
    res.fail(cmd_line)
    ~~~~~~~~^^^^^^^^^^
  File "/home/runner/work/cpython/cpython/Lib/test/support/script_helper.py", line 80, in fail
    raise AssertionError(f"Process return code is {exitcode}\n"
    ...<10 lines>...
                         f"---")
AssertionError: Process return code is 66
command line: ['/home/runner/work/cpython/cpython/python', '-X', 'faulthandler', '-I', '/home/runner/work/cpython/cpython/Lib/test/test_importlib/partial/pool_in_threads.py']
```
Seems first failure in https://github.com/python/cpython/actions/runs/11680305719

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by Zheaoli** [comment]
I can't reproduce the failure on local...
