### ISSUE TITLE
No proper validation for month in Calendar Module

### ISSUE THREAD

**Issue by gugupy** [python/cpython#126476]
# Bug report

### Bug description:

In the calendar module, `IllegalMonthError` is not handled properly. For months greater than 12, an IndexError is raised instead.

`formatmonthname ` do not raise IndexError for negative integer because list support negative integer indexing.

```python
>>> import calendar

>>> calendar.month(2024, -1)
Traceback (most recent call last):
  File "<python-input-12>", line 1, in <module>
    calendar.month(2024, -1)
    ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/gugu/Code/cpython/Lib/calendar.py", line 395, in formatmonth
    for week in self.monthdays2calendar(theyear, themonth):
                ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/gugu/Code/cpython/Lib/calendar.py", line 284, in monthdays2calendar
    days = list(self.itermonthdays2(year, month))
  File "/Users/gugu/Code/cpython/Lib/calendar.py", line 240, in itermonthdays2
    for i, d in enumerate(self.itermonthdays(year, month), self.firstweekday):
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gugu/Code/cpython/Lib/calendar.py", line 228, in itermonthdays
    day1, ndays = monthrange(year, month)
                  ~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/gugu/Code/cpython/Lib/calendar.py", line 165, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number -1; must be 1-12

>>> calendar.month(2024, 13)
Traceback (most recent call last):
  File "<python-input-13>", line 1, in <module>
    calendar.month(2024, 13)
    ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/gugu/Code/cpython/Lib/calendar.py", line 390, in formatmonth
    s = self.formatmonthname(theyear, themonth, 7 * (w + 1) - 1)
  File "/Users/gugu/Code/cpython/Lib/calendar.py", line 373, in formatmonthname
    s = month_name[themonth]
        ~~~~~~~~~~^^^^^^^^^^
  File "/Users/gugu/Code/cpython/Lib/calendar.py", line 103, in __getitem__
    funcs = self._months[i]
            ~~~~~~~~~~~~^^^
IndexError: list index out of range
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-126484
* gh-126878
* gh-126879

**Comment by tomasr8** [comment]
I think it'd make sense to raise `IllegalMonthError` in both cases. Would you like to send a PR?

**Comment by gugupy** [comment]
@Zheaoli Also add the validation for arguments, right after get options.

```python
    if options.month is not None and options.month not in range(1, 13):
        parser.error(IllegalMonthError(options.month).__str__())
        sys.exit(1)
```

**Comment by gugupy** [comment]
> I think it'd make sense to raise `IllegalMonthError` in both cases. Would you like to send a PR?

Yes, but @Zheaoli already did it.

**Comment by ZeroIntensity** [comment]
@Zheaoli For future reference, it's a good idea to let an issue author send a PR if asked, especially for first time contributors.
