### ISSUE TITLE
ConfigParser chokes on conflict markers in stdin and throws AttributeError

### ISSUE THREAD

**Issue by myxoid** [python/cpython#126541]
# Bug report

### Bug description:

This is probably a duplicate of bug 107625, but I do not have a recent enough version of Python to check the behaviour.

Whether it is worth specially detecting conflict markers is something the code owners can decide.

To reproduce:

`/tmp/py`:

```python
#!/usr/bin/python3

import configparser
import sys

sl = configparser.ConfigParser(allow_no_value=True)
sl.read_file(sys.stdin)
```

`/tmp/z`:

```
[list]
<<<<<<<< HEAD   (f12435 blah)
 foo
|||||||| BASE
 bar
========
 baz
>>>>>>>> CHANGE (faa768 blah)
```

```shell
$ </tmp/z /tmp/py
Traceback (most recent call last):
  File "/tmp/py", line 7, in <module>
    sl.read_file(sys.stdin)
  File "/usr/lib/python3.11/configparser.py", line 734, in read_file
    self._read(f, source)
  File "/usr/lib/python3.11/configparser.py", line 1077, in _read
    cursect[optname].append(value)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append'
```

Notes:

- `sys.stdin` seems to be needed to trigger this - deserves further investigation because it may point to a bad assumption or similar in the parser
- `allow_no_value` is needed to trigger this

Finger of blame:

```python
            if (cursect is not None and optname and
                cur_indent_level > indent_level):
                cursect[optname].append(value)
```

This does not check that `cursect[optname]` is present.

### CPython versions tested on:

3.10, 3.11, 3.12

### Operating systems tested on:

Linux

**Comment by picnixz** [comment]
While it's similar to #107625, I wouldn't count this as a duplicate since it fails on a different input. So this is a legitimate bug report (if it happens on 3.12, then it likely happens on 3.13+ as well).

**Comment by ritvikpasham** [comment]
Hi, is it already if I investigate this bug?

**Comment by picnixz** [comment]
Go ahead! Thank you in advance!

**Comment by myxoid** [comment]
The more general description of the problem should be "chokes on differing indentation". Here is an even simpler example:

```
[list]
 foo
  bar
 baz
```
