### ISSUE TITLE
Issue in Installing Certificates.command

### ISSUE THREAD

**Issue by FlightSimFan94** [python/cpython#126520]
Hi there,

I am trying to install the `Install Certificates.command` and have come across the following issue through the Mac Terminal:
```pytb
/Applications/Python\ 3.12/Install\ Certificates.command ; exit;                
"My user name @ My computer name" ~ % /Applications/Python\ 3.12/Install\ Certificates.command ; exit;
 -- pip install --upgrade certifi
Collecting certifi
  Obtaining dependency information for certifi from https://files.pythonhosted.org/packages/12/90/3c9ff0512038035f59d279fddeb79f5f1eccd8859f06d6163c58798b9487/certifi-2024.8.30-py3-none-any.whl.metadata
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Installing collected packages: certifi
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/certifi'
Consider using the `--user` option or check the permissions.

WARNING: There was an error checking the latest version of pip.
Traceback (most recent call last):
  File "<stdin>", line 44, in <module>
  File "<stdin>", line 24, in main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12', '-E', '-s', '-m', 'pip', 'install', '--upgrade', 'certifi']' returned non-zero exit status 1.

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]
```
Would someone be able to help me fix this issue please?

Many thanks

**Comment by skirpichev** [comment]
This is related to the certifi package.  Please read it's documentation and report issues where it's appropriate: https://github.com/certifi/python-certifi/issues

**Comment by hugovk** [comment]
Triage: this is part of the CPython installation, let's re-open and check if there's something we need to improve.
