### ISSUE TITLE
TEST  failed:     test_posix

### ISSUE THREAD

**Issue by perovskikh** [python/cpython#126863]
Os fedora 41 podman run Ubuntu 24.04

```
root@4e3e51c58d28:~/workspace/ROCmLol/build/Python# uname -a
Linux 4e3e51c58d28 6.11.7-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov  8 19:23:10 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
root@4e3e51c58d28:~/workspace/ROCmLol/build/Python# cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
root@4e3e51c58d28:~/workspace/ROCmLol/build/Python#
```

# Bug report

```text
== Tests result: FAILURE ==

17 tests skipped:
    test.test_asyncio.test_windows_events
    test.test_asyncio.test_windows_utils test.test_gdb.test_backtrace
    test.test_gdb.test_cfunction test.test_gdb.test_cfunction_full
    test.test_gdb.test_misc test.test_gdb.test_pretty_print
    test_devpoll test_ioctl test_kqueue test_launcher test_msilib
    test_startfile test_winapi test_winconsoleio test_winreg test_wmi

6 tests skipped (resource denied):
    test_ossaudiodev test_tix test_tkinter test_ttk test_winsound
    test_zipfile64

1 test failed:
    test_posix

466 tests OK.

0:01:39 load avg: 4.15 Re-running 1 failed tests in verbose mode in subprocesses
0:01:39 load avg: 4.15 Run 1 test in parallel using 1 worker process
0:01:39 load avg: 4.15 [1/1/1] test_posix failed (3 errors)
Re-running test_posix in verbose mode (matching: test_chown, test_fchown, test_lchown)
test_chown (test.test_posix.PosixTester.test_chown) ... ERROR
test_fchown (test.test_posix.PosixTester.test_fchown) ... ERROR
test_lchown (test.test_posix.PosixTester.test_lchown) ... ERROR
test_chown (test.test_posix.TestPosixWeaklinking.test_chown) ... skipped 'test weak linking on macOS'

======================================================================
ERROR: test_chown (test.test_posix.PosixTester.test_chown)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/workspace/ROCmLol/build/Python/Lib/test/test_posix.py", line 816, in test_chown
    self._test_all_chown_common(posix.chown, os_helper.TESTFN, posix.stat)
  File "/root/workspace/ROCmLol/build/Python/Lib/test/test_posix.py", line 780, in _test_all_chown_common
    chown_func(first_param, big_value, big_value)
OSError: [Errno 22] Invalid argument: '@test_261835_tmpæ'

======================================================================
ERROR: test_fchown (test.test_posix.PosixTester.test_fchown)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/workspace/ROCmLol/build/Python/Lib/test/test_posix.py", line 828, in test_fchown
    self._test_all_chown_common(posix.fchown, fd,
  File "/root/workspace/ROCmLol/build/Python/Lib/test/test_posix.py", line 780, in _test_all_chown_common
    chown_func(first_param, big_value, big_value)
OSError: [Errno 22] Invalid argument

======================================================================
ERROR: test_lchown (test.test_posix.PosixTester.test_lchown)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/workspace/ROCmLol/build/Python/Lib/test/test_posix.py", line 839, in test_lchown
    self._test_all_chown_common(posix.lchown, os_helper.TESTFN,
  File "/root/workspace/ROCmLol/build/Python/Lib/test/test_posix.py", line 780, in _test_all_chown_common
    chown_func(first_param, big_value, big_value)
OSError: [Errno 22] Invalid argument: '@test_261835_tmpæ'

----------------------------------------------------------------------
Ran 4 tests in 0.002s

FAILED (errors=3, skipped=1)
test test_posix failed
1 test failed again:
    test_posix

== Tests result: FAILURE then FAILURE ==

17 tests skipped:
    test.test_asyncio.test_windows_events
    test.test_asyncio.test_windows_utils test.test_gdb.test_backtrace
    test.test_gdb.test_cfunction test.test_gdb.test_cfunction_full
    test.test_gdb.test_misc test.test_gdb.test_pretty_print
    test_devpoll test_ioctl test_kqueue test_launcher test_msilib
    test_startfile test_winapi test_winconsoleio test_winreg test_wmi

6 tests skipped (resource denied):
    test_ossaudiodev test_tix test_tkinter test_ttk test_winsound
    test_zipfile64

1 re-run test:
    test_posix

1 test failed:
    test_posix

466 tests OK.

Total duration: 1 min 39 sec
Total tests: run=42,695 skipped=1,265
Total test files: run=485/490 failed=1 skipped=17 resource_denied=6 rerun=1
Result: FAILURE then FAILURE
make: *** [Makefile:1987: test] Error 2
```

### CPython versions tested on:

3.11, 3.12, 3.13

### Operating systems tested on:

Linux

**Comment by nineteendo** [comment]
What happens if you run `touch @test_261835_tmpæ` in the shell?

**Comment by perovskikh** [comment]
root@4e3e51c58d28:~/workspace/ROCmLol/build/Python# touch @test_261835_tmpæ
root@4e3e51c58d28:~/workspace/ROCmLol/build/Python#

**Comment by nineteendo** [comment]
Does `chown` even work in the Python build directory?

**Comment by perovskikh** [comment]
> `chown`Does from the shell even work in the Python build directory?

`root@4e3e51c58d28:~/workspace/ROCmLol/build/Python# sudo chown root test_261835_tmpae
root@4e3e51c58d28:~/workspace/ROCmLol/build/Python# ls -l test_261835_tmpae
-rw-r--r--. 1 root root 0 Nov 15 15:09 test_261835_tmpae
root@4e3e51c58d28:~/workspace/ROCmLol/build/Python# 
`
