### ISSUE TITLE
Assertion failure for `socket` with too large default timeout (larger than INT_MAX)

### ISSUE THREAD

**Issue by devdanzin** [python/cpython#126876]
# Crash report

### What happened?

A debug build will abort when calling `socket._fallback_socketpair()` after a call to `socket.setdefaulttimeout` with too high a value:

```python
python -c "import socket; socket.setdefaulttimeout(2**31) ; socket._fallback_socketpair()"
python: ./Modules/socketmodule.c:819: internal_select: Assertion `ms <= INT_MAX' failed.
Aborted (core dumped)
```
Found using fusil by @vstinner.

### CPython versions tested on:

3.12, 3.13, 3.14, CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.13.0+ (heads/3.13:7be8743, Nov 15 2024, 15:20:16) [GCC 13.2.0]

### Linked PRs
* gh-126968
* gh-127002
* gh-127003
* gh-127517

**Comment by sobolevn** [comment]
Here's my idea:

```diff
diff --git Modules/socketmodule.c Modules/socketmodule.c
index 2764bd6e2b2..4c0aac92a76 100644
--- Modules/socketmodule.c
+++ Modules/socketmodule.c
@@ -810,7 +810,7 @@ internal_select(PySocketSockObject *s, int writing, PyTime_t interval,
 
     /* s->sock_timeout is in seconds, timeout in ms */
     ms = _PyTime_AsMilliseconds(interval, _PyTime_ROUND_CEILING);
-    assert(ms <= INT_MAX);
+    assert(ms <= PyTime_MAX);
 
     /* On some OSes, typically BSD-based ones, the timeout parameter of the
        poll() syscall, when negative, must be exactly INFTIM, where defined,
                                               
```

After that:

```
» ./python.exe -c "import socket; socket.setdefaulttimeout(2**31) ; socket._fallback_socketpair()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import socket; socket.setdefaulttimeout(2**31) ; socket._fallback_socketpair()
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/sobolev/Desktop/cpython2/Lib/socket.py", line 633, in _fallback_socketpair
    ssock, _ = lsock.accept()
               ~~~~~~~~~~~~^^
  File "/Users/sobolev/Desktop/cpython2/Lib/socket.py", line 298, in accept
    fd, addr = self._accept()
               ~~~~~~~~~~~~^^
TimeoutError: timed out
                       
```

**Comment by sobolevn** [comment]
If others agree with me - I can open a PR :)

**Comment by vstinner** [comment]
```
-    assert(ms <= INT_MAX);
+    assert(ms <= PyTime_MAX);
```

This change is wrong: poll() last argument type is `int`. A better fix would be:

```diff
diff --git a/Modules/socketmodule.c b/Modules/socketmodule.c
index 2764bd6e2b2..0ba5b4af6bc 100644
--- a/Modules/socketmodule.c
+++ b/Modules/socketmodule.c
@@ -810,7 +810,9 @@ internal_select(PySocketSockObject *s, int writing, PyTime_t interval,
 
     /* s->sock_timeout is in seconds, timeout in ms */
     ms = _PyTime_AsMilliseconds(interval, _PyTime_ROUND_CEILING);
-    assert(ms <= INT_MAX);
+    if (ms > INT_MAX) {
+        ms = INT_MAX;
+    }
 
     /* On some OSes, typically BSD-based ones, the timeout parameter of the
        poll() syscall, when negative, must be exactly INFTIM, where defined,
```

**Comment by vstinner** [comment]
I propose PR gh-126968 to fix the issue.

**Comment by tomasr8** [comment]
Can this be closed? All linked PRs have been merged.
