### ISSUE TITLE
Environment colision between regular and free-threaded builds when using the Windows installer

### ISSUE THREAD

**Issue by FFY00** [python/cpython#127294]
# Bug report

### Bug description:

From https://github.com/pypa/distutils/pull/310

> When free threaded CPython is installed from the official Windows installer it doesn't have the macro `Py_GIL_DISABLED` properly set becuase its `pyconfig.h` file is shared across the co-installed default build.

### CPython versions tested on:

CPython main branch

**Comment by FFY00** [comment]
This is mentioned in https://docs.python.org/3/howto/free-threading-extensions.html#windows. That text was added in https://github.com/python/cpython/commit/02b272b7026b68e70b4a4d9a0ca080904aed374c, which mentions was based on https://github.com/Quansight-Labs/free-threaded-compatibility/, but I was unable to find any references to this Windows quirk there, so I don't know if there was any prior discussion about it.

@colesbury, perhaps you could help clarify if there was any prior discussion?

I think it's important to understand why this limitation exists, and what we could possibly do to get around it.

**Comment by colesbury** [comment]
See https://github.com/python/cpython/issues/115582#issuecomment-1954174595

**Comment by FFY00** [comment]
That seems... bad.

From what I can conjecture from https://github.com/python/cpython/issues/115582#issuecomment-1953215343, it seems like we have a single installer that installs both free-threaded and regular binaries under the same prefix (`sys.base_prefix`). I am not sure what happens to `sys.prefix` here, but I hope it's not shared (not set to the same as `sys.base_prefix`), as that would mean site-packages is shared between the free-threaded and regular interpreters, which wouldn't be great.

The approach we have taken with Python installations on Windows is that each installation must have its own prefix. On POSIX, the prefix can be shared, as all paths containing installation-specific files include the version and ABI flags.

If we want to fix this issue, I think free-threaded builds on Windows should either be installed to a different prefix, or adopt the POSIX approach [^1]. To keep in line with the usual expectations of how programs work on Windows, I think it's better to keep the paths as-is, and simply install free-threaded builds to a different prefix.

Steve mentions the issue with that approach: 

> - separate the entire prefix, which messes with anyone trying to launch/reference python3.13t.exe

I don't think I understand which specific use-case this is referencing. @zooba could you clarify?

[^1]: This would be nice, as we could use the same paths across all platforms.

**Comment by zooba** [comment]
I am not prepared to produce a second set of installers in order to install to a separate prefix, nor do I want to modify the existing installer in order to do that. It is too big a risk for regular users. I presented this to the steering council and they agreed with the current design. We also don't want to confuse users further by having a much longer list of installers to choose from on the downloads page.

One day, the separate free-threaded builds go away and we'll just have one install again (potentially with free-threaded enabled all the time by default). I don't care to over-design this scenario now, since we know it'll go away.

POSIX is different because a build-time generated `Makefile` and `_sysconfig_data` is distributed as part of the install. On Windows, we don't do this, so the only way to get at compile-time options is by running the interpreter and looking at `sys` or `sysconfig` (one day we'll get that static JSON file with all the info in it, right? ;) )

So basically, we need an idea that:
* doesn't add more than (probably) one new download option to the downloads page
* installs an entire copy of the runtime, not just the freethreaded build
* modifies otherwise static files at compile time (potentially only when producing the installer)
* doesn't interfere with a regular install (shortcuts, associations, etc.)
* satisfies the steering council

My best recommendation right now is to get your freethreaded build through uv, which ought to be getting it from the Nuget packages, which already meet all of these requirements. For those who'd rather get their builds from Nuget directly (like cibuildwheel, IIUC), that's also pretty straightforward.

But I really don't want to mess with the installer too much. It's fragile enough already (I'd prefer to deprecate and replace it entirely, but haven't got a better option - [though I'm starting to discuss better options](https://discuss.python.org/t/windows-store-package-to-become-installer-launcher/71702/72)).

**Comment by zooba** [comment]
There's more context on why the current design is as it is at https://github.com/python/steering-council/issues/225 (with links to even more context)

**Comment by FFY00** [comment]
> I am not prepared to produce a second set of installers in order to install to a separate prefix, nor do I want to modify the existing installer in order to do that. It is too big a risk for regular users.

That's fair, though it's not clear to me how installing to different prefixes would add a significant risk for users.

> I presented this to the steering council and they agreed with the current design.

Sorry I missed that, though reading the discussion there, it doesn't seem like the implications of having different build in the same prefix were properly considered.

> We also don't want to confuse users further by having a much longer list of installers to choose from on the downloads page.

I agree, I think the best option would be to modify the current installer to install both builds in a separate prefix, but if you aren't comfortable with that, that's okay.

> One day, the separate free-threaded builds go away and we'll just have one install again (potentially with free-threaded enabled all the time by default). I don't care to over-design this scenario now, since we know it'll go away.

Yes, but the [PEP 703 estimate for that](https://peps.python.org/pep-0703/#python-build-modes) is 2026–2027, so it'll still be a while. But I understand where you are coming from.

> POSIX is different because a build-time generated `Makefile` and `_sysconfig_data` is distributed as part of the install. On Windows, we don't do this, so the only way to get at compile-time options is by running the interpreter and looking at `sys` or `sysconfig` (one day we'll get that static JSON file with all the info in it, right? ;) )

I don't understand how that affects things here :sweat_smile: 

> So basically, we need an idea that:
> 
>     * doesn't add more than (probably) one new download option to the downloads page
> 
>     * installs an entire copy of the runtime, not just the freethreaded build
> 
>     * modifies otherwise static files at compile time (potentially only when producing the installer)
> 
>     * doesn't interfere with a regular install (shortcuts, associations, etc.)
> 
>     * satisfies the steering council

My proposal was to have the installer install a regular build to `...\Python\Python314`, and a free-threaded build to `...\Python\Python314t`. IMO the free-threaded build doesn't need shortcuts, associations, or anything like that, the installer can simply keep only providing that for the regular build.

Otherwise, the only other option I see is to add the version and ABI flags to the paths, like it's done for POSIX.

**Comment by zooba** [comment]
> it's not clear to me how installing to different prefixes would add a significant risk for users.

Yeah, it's really not obvious until you get pretty deep into Windows Installer (and have debugged a number of weird scenarios).

Basically it boils down to the installers being a mix of generated, calculated, and static UUIDs. These identify installable products, features and components, which may contain files. The files themselves don't matter to the installer, just the UUID. Which means if you get any unintentional overlap, you get corrupted installs - files won't be properly added, or they'll be removed or moved to a different location.

The advantages are all for in-place updates - we can reliably detect previous versions of the same thing, and handle them efficiently. It doesn't matter so much these days, because we no longer care about the difference between downloading 100KB vs 1MB, or copying 100 files vs 1000 files. So it seems just as efficient to just download/copy everything all the time, and the effort to minimise things seems wasted.

But anyway, with all these UUIDs around, forking the installer to be parallel to the original requires very carefully making sure all the static UUIDs are new, and all the calculated ones aren't going to generate conflicts. Otherwise, users who have a regular install and the freethreaded install will get weird behaviour - weird as in individual files just disappearing, or install steps being skipped no matter how you try to trigger them, or entire features being skipped because they're "already installed".

And this is before we get to things like registry keys or environment variables.

Like I said, I'd love to deprecate and replace the whole thing. But I won't do that without an equally user friendly alternative, because literally millions of people rely on clicking through this on a regular basis. I've been thinking about/designing alternatives for years, and am only just starting to get towards something I'm happy with, but we're a few years away from being able to deprecate this current installer. Free threading will likely be merged by then ;)

**Comment by FFY00** [comment]
Gotcha, I understand now.

What about the alternative, then? Changing the install layout to include the version and ABI flags.

**Comment by zooba** [comment]
From the installer POV, that's just a different default install directory. That's the trivial part - it's being able to install the second installer at the same time as the main one and have them both work correctly that adds all the risk.

I suspect the people who are trying to validate free-threaded binaries at this point would be just as happy to download a zip file and manage it themselves? If so, they can go to [python-freethreaded](https://www.nuget.org/packages/python-freethreaded), [pythonx86-freethreaded](https://www.nuget.org/packages/pythonx86-freethreaded) or [pythonarm64-freethreaded](https://www.nuget.org/packages/pythonarm64-freethreaded) and use the "Download package" link on the right to get them (it's a zip file renamed to .nupkg, and the binaries are under the `tools` directory). And before anyone asks, I don't consider this a suitable alternative to the installer for most users most of the time, and putting the download links directly on python.org makes the list too long.

The challenge is the install method, not the layout.

**Comment by FFY00** [comment]
> From the installer POV, that's just a different default install directory. That's the trivial part - it's being able to install the second installer at the same time as the main one and have them both work correctly that adds all the risk.

Ah, right :facepalm:

Other thought, would changing between the regular and free-threading binaries based on a user selection in the installer be viable? This would add the limitation of only allowing either one, but I personally think that's okay.

> I suspect the people who are trying to validate free-threaded binaries at this point would be just as happy to download a zip file and manage it themselves? If so, they can go to [python-freethreaded](https://www.nuget.org/packages/python-freethreaded), [pythonx86-freethreaded](https://www.nuget.org/packages/pythonx86-freethreaded) or [pythonarm64-freethreaded](https://www.nuget.org/packages/pythonarm64-freethreaded) and use the "Download package" link on the right to get them (it's a zip file renamed to .nupkg, and the binaries are under the `tools` directory). And before anyone asks, I don't consider this a suitable alternative to the installer for most users most of the time, and putting the download links directly on python.org makes the list too long.
> 
> The challenge is the install method, not the layout.

I am happy with any of those scenarios, and would be +1 towards dropping the free-threaded support from the installer. Having two builds with the same paths is problematic, and I am sure we will see more issues other than the `pyconfig.h` one.

**Comment by rgommers** [comment]
> Having two builds with the same paths is problematic, and I am sure we will see more issues other than the `pyconfig.h` one.

I wouldn't be sure of that at all, given that no other issues have materialized yet and testing by package authors and end users has been pretty heavy recently.

Dropping the option for what is at this point a hypothetical second issue does not seem like a good idea, since it incurs a bunch of work for docs, breaks blog posts already published, and may break CI systems that rely on scripts pointing at the current installers (e.g., if using the `Invoke-WebRequest` method documented at https://py-free-threading.github.io/installing_cpython/#pythonorg-installers).

Doing nothing and closing this issue seems preferable here, unless more bugs show up.

**Comment by FFY00** [comment]
> I wouldn't be sure of that at all, given that no other issues have materialized yet and testing by package authors and end users has been pretty heavy recently.

The current user base is small and technical, I am not worried about those users. As this gets further adoption, less technical users will start experimenting with it and will eventually run into issues they absolutely shouldn't, like mismatched package installations.

Sharing `sys.prefix` on Windows means that site-packages are also shared, so you could pip install something on the free-threaded build and then have the regular build failing to load it.

```shell
ffy00@DESKTOP-VP183NR C:\Program Files\Python313>python3.13t -m pip install numpy
Collecting numpy
  Downloading numpy-2.1.3-cp313-cp313t-win_amd64.whl.metadata (60 kB)
Downloading numpy-2.1.3-cp313-cp313t-win_amd64.whl (12.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 3.8 MB/s eta 0:00:00
Installing collected packages: numpy
  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Program Files\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-2.1.3

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python3.13t.exe -m pip install --upgrade pip

ffy00@DESKTOP-VP183NR C:\Program Files\Python313>python
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\site-packages\numpy\_core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Program Files\Python313\Lib\site-packages\numpy\_core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Program Files\Python313\Lib\site-packages\numpy\_core\overrides.py", line 8, in <module>
    from numpy._core._multiarray_umath import (
        add_docstring,  _get_implementing_args, _ArrayFunctionDispatcher)
ModuleNotFoundError: No module named 'numpy._core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\site-packages\numpy\__init__.py", line 127, in <module>
    from numpy.__config__ import show as show_config
  File "C:\Program Files\Python313\Lib\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
    ...<3 lines>...
    )
  File "C:\Program Files\Python313\Lib\site-packages\numpy\_core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.13 from "C:\Program Files\Python313\python.exe"
  * The NumPy version is: "2.1.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy._core._multiarray_umath'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import numpy
  File "C:\Program Files\Python313\Lib\site-packages\numpy\__init__.py", line 132, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
>>>
```

And since pretty much all projects ship separate wheels for free-threaded and non-free-threaded builds, making it impossible to have a package installation that is valid in both builds, as it stands you pretty much have to decide whether you want a free-threaded or non-free-threaded environment.

While I think this is okay while we are still working on the free-threaded adoption by the bigger packages, as soon as that is done, and we start getting the broader community to test free-threading and adding support to their own projects, I personally don't think this UX is acceptable.

> Dropping the option for what is at this point a hypothetical second issue does not seem like a good idea, since it incurs a bunch of work for docs, breaks blog posts already published, and may break CI systems that rely on scripts pointing at the current installers (e.g., if using the `Invoke-WebRequest` method documented at [py-free-threading.github.io/installing_cpython#pythonorg-installers](https://py-free-threading.github.io/installing_cpython/#pythonorg-installers)).

You are right in pointing out the impact of changes in the installer, and that should be a consideration while deciding how to proceed, but I disagree with the severity of the issue. Like I said, I don't think it's a major issue right now, but I think it will be as free-threading starts seeing more adoption.

> Doing nothing and closing this issue seems preferable here, unless more bugs show up.

I disagree with you on this :face_with_diagonal_mouth:

I think if it's possible to select between the free-threaded and regular build on the installer, we should consider that. I'll wait for Steve to say if that's viable or not.

If that is not possible, I think we should, at the minimum, add the ABI flags to the site-packages path on Windows.

**Comment by zooba** [comment]
We can make changes for 3.14, no problem. It's just deciding what those changes will be.

Having the installer switch is basically as bad as having two parallel installers, or alternatively it's confusing in that `python.exe` goes away and only `python3.14t.exe` remains (if the only thing we change is to make the current `exe` component optional).

Merging the `site-packages` folder is pretty bad, yeah. But it shouldn't matter if the only thing you do is create a venv and work in that. I'd rather not force everyone through having to deal with renamed `site-packages` for a couple of versions (particularly the package installers). _Maybe_ they're abstracted enough from it, but I'm not sure.

Alternatively, we take it out of the installer entirely and figure out some reasonable way to link to three ZIP files (or three "cheap" installers) from the downloads page? Some way that ensures the 99% of downloads who don't want it won't choose it by mistake - the existing six entries on there are already confusing enough.

> https://py-free-threading.github.io/installing_cpython/#pythonorg-installers

I wish this pointed to the Nuget packages instead :(

**Comment by zooba** [comment]
We're also way off the topic of `Py_GIL_DISABLED` not being set, so perhaps this is the wrong venue for this discussion?

IMHO, I really don't like dynamically generating header files at build time, and would much prefer build tools determine whether they want this option themselves. If that's really not going to work, then I'd prefer to generate it at installer build time (or perhaps just select it), which would mean that in-tree builds get harder to work with (compared to the build tool setting it; not compared to compile-time generation).

**Comment by rgommers** [comment]
> I wish this pointed to the Nuget packages instead :(

Happy to make that change. Do you have a preferred invocation (I don't know much about Nuget, sorry)?

**Comment by zooba** [comment]
> Do you have a preferred invocation

You can stick with the `Invoke-WebRequest` and `Expand-Archive` PowerShell commands, just say to grab the download link from the "Download package" link on the Nuget page:

![image](https://github.com/user-attachments/assets/c2c0c062-6eb7-4c88-bd0c-85495881fd6f)

Users who already know Nuget may choose to use that themselves. It doesn't do version resolution - you have to pin stuff - so the difference between `nuget install python -version 3.13 ...` and `iwr <URL to 3.13 package> ...` are pretty minimal.

**Comment by FFY00** [comment]
> Having the installer switch is basically as bad as having two parallel installers, or alternatively it's confusing in that `python.exe` goes away and only `python3.14t.exe` remains (if the only thing we change is to make the current `exe` component optional).

Is there a way to register two `python.exe` entries and select which one to install, or do the entries have to be unique?

> Merging the `site-packages` folder is pretty bad, yeah. But it shouldn't matter if the only thing you do is create a venv and work in that. I'd rather not force everyone through having to deal with renamed `site-packages` for a couple of versions (particularly the package installers). _Maybe_ they're abstracted enough from it, but I'm not sure.

The package installers should be getting data from `sysconfig`, so they shouldn't care. That said, the site-packages renaming would only be a mitigation measure anyway, if we can figure out a way to not have two installations on the same prefix, that would be preferred.

With GH-112984, venv will only copy the correct Python, but I am not sure if virtualenv and other environment managers will do the same, so that's a possible issue. If you want to focus on the venv-only use-case and don't want to rename site-packages, we could possibly add a [PEP 668](https://peps.python.org/pep-0668/) `EXTERNALLY-MANAGED` file, warning the users about the possibility for a mismatch. But again, this isn't a great solution, and is only a mitigation measure anyway.

> Alternatively, we take it out of the installer entirely and figure out some reasonable way to link to three ZIP files (or three "cheap" installers) from the downloads page? Some way that ensures the 99% of downloads who don't want it won't choose it by mistake - the existing six entries on there are already confusing enough.

Yeah, I feel like the current UI isn't cohesive for experimental releases like these. Since this isn't urgent, we could try asking the PSF if there are any resources to help us do a small redesign of the download pages? I would not be opposed to do that work myself, but I don't think I am knowledgeable enough in UI/UX to do a good job :sweat_smile:. We could also do some outreach and see if any community members experienced in UI/UX would be willing to help?

Do you think it makes sense to go back to the SC for a new opinion?

> We're also way off the topic of `Py_GIL_DISABLED` not being set, so perhaps this is the wrong venue for this discussion?

It's related, as that issue is caused by sharing the prefix between builds, but maybe we should move it.

**Comment by zooba** [comment]
> Do you think it makes sense to go back to the SC for a new opinion?

When there's a new SC, yeah, it won't hurt. But they'll want no more than two options to choose between, so we should come up with concrete proposals.

> It's related, as that issue is caused by sharing the prefix between builds

It's also caused by us not properly generating headers at compile time, which is something that we've never done here before and I would prefer to undo the hack that we have. So either we're going to drastically change part of the Windows build (and significantly break/upset in-tree builds), or we push that generation out to install time (and break experimental build in-tree users), or we push the option to sysconfig/the build tools and everyone is happy.

**Comment by ngoldbaum** [comment]
> Other thought, would changing between the regular and free-threading binaries based on a user selection in the installer be viable? This would add the limitation of only allowing either one, but I personally think that's okay

Just a note that it's pretty common to simultaneously have all the python versions needed for testing or wheel building simultaneously loaded on CI. Not being able to do this, but only for free threading on windows, will be surprising.

**Comment by FFY00** [comment]
@zooba, if [PEP 773](https://peps.python.org/pep-0773/) goes forward, that means we can drop the current installer, right?

**Comment by zooba** [comment]
Correct, though not for a couple of releases.

**Comment by FFY00** [comment]
Do you think that should make it to the first 3.14 final release? Because if not, I think we should setup a discussion with the SC to figure out what to do. I'm not meaning to be a pain, but I really think this is a very big UX issue.

**Comment by zooba** [comment]
What's the UX issue? That build backends need to specify when they want a free-threaded build? That seems like a better place to be than trying to figure it out automatically - you'd still need a way to override it anyway, and they can check whether the current runtime has already set it for a default. There's no issue with cross-compiling (provided the import libraries are available, as usual).

**Comment by FFY00** [comment]
That there's two installations on the same prefix. We should probably change the issue name.

**Comment by zooba** [comment]
So `site-packages` is the issue then?

It might actually be worth a new issue with a more concise description of what we need to change.

**Comment by FFY00** [comment]
Perhaps, but if you preview the installation manager will not be ready for 3.14, I think we should open an issue directly on the SC repo highlighting the issue, and proposing a couple of different solutions.

**Comment by zooba** [comment]
I'm not even clear on what the issue or the solutions would be, so if you've got ideas, having that list for discussion would be a good starting point.

I'm hoping the install manager will be ready for 3.14, though distracting me (and the SC) with other issues may guarantee that it isn't 😉

**Comment by FFY00** [comment]
I have a couple of possible approaches. I'll open an issue on the SC repo explaining the issue more clearly, and provide a couple of possible approaches to handle it, acknowledging the install manager as the optimal solution, if possible.

**Comment by ngoldbaum** [comment]
In case anyone gets to this issue because of a runtime crash, the best way forward is probably to *not* use the python.org Python and instead install free-threaded Python using nuget. It's pretty straightforward and doesn't require anything besides powershell. See the instructions on the py-free-threading guide: https://py-free-threading.github.io/installing_cpython/#__tabbed_1_1

**Comment by Avnsx** [comment]
This just took 2 hours of my life trying to figure out why this exact bug was happening and holding me back from importing numpy and opencv on 3.13.2 thread-unlocked 😥

**Comment by ngoldbaum** [comment]
Given that Python 3.16 will not have to deal with the MSI installer, does it make sense to start defining `Py_GIL_DISABLED` on Windows starting in 3.16? Or are there downsides to doing that because people have already worked around this in the ecosystem?

**Comment by rgommers** [comment]
That sounds like the right thing to do, so the workarounds in various build backends can eventually be dropped. A double define in the meantime shouldn't be a problem.

**Comment by zooba** [comment]
The downsides are largely due to trying to build out of the same locations, and a lot of tools assuming that there's only one `PC/pyconfig.h` that already exists in the source tree. We flushed out and fixed a few of these previously, but I'm sure more will exist.

Most of the issues with the build-time-updated `pyconfig.h` were due to our build system, and not to the end user. So I'm still hesitant to bring it back. It's actually _really nice_ to have a single set of headers that work everywhere (provided options such as target architecture and free-threadedness remain more or less mandatory). Particularly for those of us who cross-compile.

I don't think it would make sense to eventually drop the workarounds for at least a regular deprecation period, anyway. And I'd probably rather lean more towards the CFLAGS approach of `sysconfig` providing the options needed to build a matching runtime on Windows as well as on every other platform, so we have more consistency between platforms rather than less. That is further change for downstream tools, but at least then "do we pass `/D...` or not" is answered by "we always append `sysconfig.getconfigvar("CFLAGS")` on all  platforms". (Though it _would_ then make it harder to transition to Clang one day, unless we're really confident the flags are compatible.)

If we really want the standard packages to have custom sets of headers, then I'd rather it _not_ be a modification to `pyconfig.h`, but an extra additional header that gets entirely swapped out by `PC/layout` rather than the regular build system. Kind of like how we build `python3*.dll` multiple times for different ABIs and then the installer picks the one it wants to carry. It makes things more complicated for people running in the source tree (and directly led to us making the source tree even more complicated to handle it), but it's far more likely we won't ship broken headers again if it's done this way.

Until then, I personally don't have a concern with build backends having to know whether they're targeting free-threaded or not. The only benefit that comes from swapping the headers out for them is that they don't have to know, and I think that's actually going to make things worse if they try to pretend that it isn't relevant to the build.

**Comment by zooba** [comment]
The installer referred to in this issue has now been removed (#153511), and so this issue is expired. Please use the [Python install manager](https://www.python.org/downloads/latest/pymanager/) to install Python, and file any issues [on the pymanager repo](https://github.com/python/pymanager).
