### ISSUE TITLE
double_abs test failures in  3.0.11

### ISSUE THREAD

**Issue by apteryks** [python/cpython#127437]
# Bug report

### Bug description:

Hi,

Running the test suite of Cython 3.0.11 with GNU Guix, I see the following doctests failures:

```
======================================================================
FAIL: double_abs (complex_numbers_cpp)
Doctest: complex_numbers_cpp.double_abs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/lp8ch4rn10whzyajnzv216d2a2v163c7-python-3.10.7/lib/python3.10/doctest.py", line 2221, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for complex_numbers_cpp.double_abs
  File "/tmp/guix-build-python-cython-3.0.11.drv-0/cython-3.0.11/TEST_TMP/14/run/cpp/complex_numbers_cpp/complex_numbers_cpp.cpython-310-x86_64-linux-gnu.so", line unknown line number, in double_abs

----------------------------------------------------------------------
File "/tmp/guix-build-python-cython-3.0.11.drv-0/cython-3.0.11/TEST_TMP/14/run/cpp/complex_numbers_cpp/complex_numbers_cpp.cpython-310-x86_64-linux-gnu.so", line ?, in complex_numbers_cpp.double_abs
Failed example:
    double_abs(2 + 5j) == math.sqrt(29)
Expected:
    True
Got:
    False


======================================================================
FAIL: double_abs (complex_numbers_cpp)
Doctest: complex_numbers_cpp.double_abs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/lp8ch4rn10whzyajnzv216d2a2v163c7-python-3.10.7/lib/python3.10/doctest.py", line 2221, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for complex_numbers_cpp.double_abs
  File "/tmp/guix-build-python-cython-3.0.11.drv-0/cython-3.0.11/TEST_TMP/14/run/cpp/complex_numbers_cpp_directives_cpp_locals_True/complex_numbers_cpp.cpython-310-x86_64-linux-gnu.so", line unknown line number, in double_abs

----------------------------------------------------------------------
File "/tmp/guix-build-python-cython-3.0.11.drv-0/cython-3.0.11/TEST_TMP/14/run/cpp/complex_numbers_cpp_directives_cpp_locals_True/complex_numbers_cpp.cpython-310-x86_64-linux-gnu.so", line ?, in complex_numbers_cpp.double_abs
Failed example:
    double_abs(2 + 5j) == math.sqrt(29)
Expected:
    True
Got:
    False


----------------------------------------------------------------------
Ran 579 tests in 86.348s

FAILED (failures=2)
```

The only direct dependencies added to the build environment are: 
`libxcrypt@4.4.36 python@3.10.7`.  GCC is at version 11.4.0.

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by picnixz** [comment]
Isn't it a Cython-only issue? This should be reported to their repository instead I think.

**Comment by Apteryks** [comment]
And I thought I was reporting this to Cython!  Sorry for my bout of dyslexia.
