### ISSUE TITLE
CSV Writer Regression in Python 3.11+: Escaping Required but Unnecessary

### ISSUE THREAD

**Issue by cspurk** [python/cpython#128064]
# Bug report

### Bug description:

The following `csvtest.py` script works for Python 3.10 and earlier but fails for 3.11 and later:

```python
import csv
import io
b = io.StringIO()
csv.writer(b, quoting=csv.QUOTE_NONE, lineterminator='\n').writerow(["\r"])
print(repr(b.getvalue()))
```

For example, running the shell script …

```shell
for v in 9 10 11 12 13; do
    pyenv shell 3.$v
    python --version
    python csvtest.py
done
```
… yields:

```
Python 3.9.21
'\r\n'
Python 3.10.16
'\r\n'
Python 3.11.11
Traceback (most recent call last):
  File "/tmp/csvtest.py", line 4, in <module>
    csv.writer(b, quoting=csv.QUOTE_NONE, lineterminator='\n').writerow(["\r"])
_csv.Error: need to escape, but no escapechar set
Python 3.12.8
Traceback (most recent call last):
  File "/tmp/csvtest.py", line 4, in <module>
    csv.writer(b, quoting=csv.QUOTE_NONE, lineterminator='\n').writerow(["\r"])
_csv.Error: need to escape, but no escapechar set
Python 3.13.1
Traceback (most recent call last):
  File "/tmp/csvtest.py", line 4, in <module>
    csv.writer(b, quoting=csv.QUOTE_NONE, lineterminator='\n').writerow(["\r"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
_csv.Error: need to escape, but no escapechar set
```

As in Python 3.10 and earlier, escaping the carriage return character (`\r`) should not be necessary (due to the custom `lineterminator`), but Python 3.11+ still expects it.

### CPython versions tested on:

3.9, 3.10, 3.11, 3.12, 3.13

### Operating systems tested on:

Linux

**Comment by Berto575** [comment]
StuxNet Virus Shutdown the Nuclear Reactors in Iran. Yet they seem to have Spread their Threats to other Parts of this Fallen World. Otherwise. SSA Servers Admin wouldn't have had the Chance to Stop his Check from being Endorsed and Financially Supporting him after 2003. His Attorney in their Law Firm is trying to Dispute his Psychological Issues. Since I refuse to get Therapy for my Personality Disorder. He has reported my Downstairs Neighbor Ms Cassandra Swain for causing us to Unnecessarily clash heads over the Uncontrollable Infestation of Cockroaches Gnats intruding from Downstairs. He is researching ways to help Stop Ransomware and the Cyber Attacks that are being used to take down Human Trafficking Rings. Full Scholarships for his BA Degree in Cyber Security as an Analyst.

**Comment by ido123net** [comment]
When changing to `null character` instead of the `carriage return` it is the opposite.

```sh
$ for v in 10 11 12 13; do     python3.$v --version;     python3.$v csvtest.py; done
Python 3.10.20
Traceback (most recent call last):
  File "/homes/idof/csvtest.py", line 4, in <module>
    csv.writer(b, quoting=csv.QUOTE_NONE, lineterminator='\n').writerow(["\x00"])
_csv.Error: need to escape, but no escapechar set
Python 3.11.15
'\x00\n'
Python 3.12.13
'\x00\n'
Python 3.13.13
'\x00\n
```

**Comment by serhiy-storchaka** [comment]
This is intentional -- see gh-67044 (GH-115741).

The reader always treats `\r` and `\n` as end of line and ignores *lineterminator*. What 3.10 wrote for your example, `'\r\n'`, reads back as an empty record, and `['a\rb']` cannot be read back at all. With `QUOTE_NONE` and no *escapechar* there is no way to represent such a field, hence the error.

@ido123net, the `'\x00'` difference is unrelated: before 3.11 an unset *escapechar* was stored as `'\0'`, so a NUL in a field matched it (bpo-27580).
