### ISSUE TITLE
type(None).__module__ returns wrong module

### ISSUE THREAD

**Issue by rafalkrupinski** [python/cpython#128197]
# Bug report

### Bug description:

```python
t=type(None)
print(f'{t.__module__}.{t.__name__}')
# prints builtins.NoneType
# actual module: types
```

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Hello!
It's not a bug. `None` is defined as `builtins` attribute in the `builtins` module: https://github.com/python/cpython/blob/c5b0c90b62f1a10b0742db4bcd17da080d4e9111/Python/bltinmodule.c#L3336

**Comment by rafalkrupinski** [comment]
It's tot about `None`, but `NoneType`

**Comment by Eclips4** [comment]
> @Eclips4 It's tot about `None`, but `NoneType`

Oh, yes, I've misread your message. What made you think that `NoneType` was coming from `types` module?

**Comment by rafalkrupinski** [comment]
WDYM
```py
>>> from builtins import NoneType
Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    from builtins import NoneType
ImportError: cannot import name 'NoneType' from 'builtins' (unknown location)

>>> from types import NoneType
>>> print(NoneType)
<class 'NoneType'>
```

**Comment by Eclips4** [comment]
> WDYM
> 
> ```python
> >>> from builtins import NoneType
> Traceback (most recent call last):
>   File "<python-input-3>", line 1, in <module>
>     from builtins import NoneType
> ImportError: cannot import name 'NoneType' from 'builtins' (unknown location)
> 
> >>> from types import NoneType
> >>> print(NoneType)
> <class 'NoneType'>
> ```

That's doesnt mean that `NoneType` is coming from `types`. In fact, `NoneType` is defined in `Objects/object.c`:
https://github.com/python/cpython/blob/d61542b5ff1fe64705e5ce1bcc53048f14098dba/Objects/object.c#L2119-L2158

Why do you see `builtins `in the `__module__` of a `NoneType`? Well, because `NoneType` is a special object and doesn't actually have a module, so interpreter is doing some hacky stuff: https://github.com/python/cpython/blob/d61542b5ff1fe64705e5ce1bcc53048f14098dba/Objects/typeobject.c#L1418

This is a long-standing behavior and I don't think we should change it.

**Comment by rafalkrupinski** [comment]
NoneType was introduced in 3.10, so not that long, and #63637 says it was in types. How about adding an alias for compatibility?

**Comment by Eclips4** [comment]
> NoneType was introduced in 3.10, so not that long, and #63637 says it was in types. How about adding an alias for compatibility?

`NoneType` as type of `None` wasn't introduced in 3.10, it was introduced much earlier. I don't understand what alias could be added here.

**Comment by rafalkrupinski** [comment]
@Eclips4 I'm getting a feel you're being dismissive

> Why do you see builtins in the __module__ of a NoneType? Well, because NoneType is a special object and doesn't actually have a module, so interpreter is doing some hacky stuff: 

I don't have a problem with builtins in __module__, only with NoneType missing from builtins. it's just not there, from python perspective. importing NoneType from builtins raises ImportError!

**Comment by Eclips4** [comment]
> [@Eclips4](https://github.com/Eclips4) I'm getting a feeling you're being dismissive towards me.

Sorry, I just didn't understand you previously. I didn't mean to be dismissive or offend you.

I now understand your confusion and summarize our conversation for others:
`type(None).__module__` returns `"builtins"` and in fact if we would try to import `type(None).__name__` from `"builtins"` it would fail with `ImportError`. As possible solution we could change it module to `types` where in fact we have a `NoneType`.
The same applies for `type(some_function)`, `type(some_lambda)` and much others.

**Comment by picnixz** [comment]
Changing it to `types` may break existing introspection tools that do special-casing (I think we do something for that in Sphinx). While there is a discrepency, I don't think it's good to change it to `types` (unless we have guarantees that this won't break things).

Concerning the other builtins, their actual class name is usually different from the exposed name in `types`, so it wouldn't help to change their module to `types` (for instance, `type(...).__name__` is 'ellipsis' but it's exposed as `types.EllipsisType`). So we would need to sync the class names with those in `types` and I don't know if it can break existing code or not (even if such code is bad, it's not good to break stuff if we can avoid it). Surpsingly, `type(None)` was correctly named (namely `types.NoneType` exists)

**Comment by rafalkrupinski** [comment]
Would moving it to `types` and keeping a deprecated alias in builtins solve the problem for everone?

this would work
```py
from types import NoneType
from builtins import NoneType
```
this wouldn break
```py
assert type(None).__module__ == 'builtins'
```

**Comment by picnixz** [comment]
> Would moving it to types and keeping a deprecated alias in builtins solve the problem for everone?

Also, I think we should rather deprecate the `types` and move it to `builtins`. However, `builtins` is actually more used for anything that can be used without import and `NoneType` wouldn't be the case =/

**Comment by rafalkrupinski** [comment]
I don't mind which module it is in, as long it's consistent. It would simplify all code that relies on it.

My use case a code generator. For simple cases I can do `TypeModel.from(str)` or `TypeModel.from(list[str])` to create an object that outputs the input type, while other cases work with custom generated classes. Nothing that can't be worked around, but apparently I'm not the only one stumbling upon it.

**Comment by rafalkrupinski** [comment]
@picnixz 

> Strictly speaking, it is correct to assume that it's in the builtins module. It's just that it's not exposed from builtins

Can you elaborate?

For us humans anything goes, but when any metaprogramming or introspection is involved, it's just another special case to handle. I don't see any practical about it.

**Comment by picnixz** [comment]
All objects have a type but some types are special and not exposed as "global" names. The `builtins` module contains names that are available globally without the needs to import them (and they are also used if you shadow some of the built-in names). 

Now, yes, it's special-casing, but this has been a longstanding behaviour. We do not (likely) want to expose *globally* the type of None, namely we don't want to be able to write something like `x = NoneType()` without explicitly importing `types.NoneType` (I don't have access to 3.14 now but we can write `type(None)()` on 3.11 so I guess it stayed the same). Same holds for `function()` as `function` is the type of `lambda: None`. So we cannot really expose it at runtime to `builtins` (otherwise globals would be polluted).

While it's a special case, I'm not sure that changing it would work. Unless we expose them in `builtins` for consistency, I don't think we'll ever change this. I'd say special types require special treatments as well and implementation details were likely meant to be hidden.

Concerning the introspection tools, I think they should deal with it. At least, in Sphinx, we do (https://github.com/sphinx-doc/sphinx/blob/e18155fa106cf64d7b39dcc6506b60fd82703b10/sphinx/util/typing.py#L41) but this is not really hard to maintain. We know this discrepency but I think the standard library can put the burden of this on the tools.

I'm actually unusure of whether the interpreter would still work properly if we were to actually change the module name of built-in types such as functions or `type(None)`. For that, we need some other experts (maybe @brettcannon or @ncoghlan may have a say here?)

**Comment by rafalkrupinski** [comment]
OK, bringing those types to `builtins` might not be the best idea, and come to think about it, it wouldn't help any cases.

I agree it's not a huge problem, and even if it's awkward, it doesn't hit a large part of the user base. 

I can't imagine reasonable code that would rely on `type(None).__module__ == 'builtins'`. For example the sphinx code would keep working with `__module__` of these types fixed. And python has seen bigger changes in minor versions.

Then again, I've been surprised before, and I know not all code is reasonable.

**Comment by brettcannon** [comment]
There are a bunch of baseline types whose names are not directly exposed in the `builtins` module:

https://github.com/python/cpython/blob/29caec62ee0650493c83c778ee2ea50b0501bc41/Lib/types.py#L13-L16
https://github.com/python/cpython/blob/29caec62ee0650493c83c778ee2ea50b0501bc41/Lib/types.py#L327-L332

All of those types list "builtins" as the module because they are "builtins" as a concept and needed _some_ module name as the `__module__` attribute is on everything. But a key thing to know is the [`builtins` module only came into existence in Python 3.0](https://docs.python.org/3.0/library/builtins.html#module-builtins), so it isn't really a reference to the module as much as letting the user know the type is built into the language.

And adding **anything** to `builtins` is a **HUGE** deal as it's exposed to all Python code. So expanding `builtins` just for consistency isn't worth it in my opinion. And considering this is the first time I can remember bringing this up I don't think it's worth changing knowing it will break someone's code who special-cases "builtins" for these exact objects (there's no way there isn't some code out there that relies on this).

As such, I'm closing the issue as "won't fix".

**Comment by JelleZijlstra** [comment]
I do actually think it's worth improving the situation here. If the `__module__` attribute does not match the runtime location of the type, that means tools that introspect types at runtime need special casing. I'd rather move to a world where there are fewer such subtleties for introspection.

It's true that existing tools may need updates if we change e.g. `NoneType.__module__` to `types`. However, it's better in the long run to get this right and make it so users don't need to worry about the historical background.

**Comment by AlexWaygood** [comment]
> I do actually think it's worth improving the situation here. If the `__module__` attribute does not match the runtime location of the type, that means tools that introspect types at runtime need special casing. I'd rather move to a world where there are fewer such subtleties for introspection.

I agree, but there's an existing issue for discussing this: https://github.com/python/cpython/issues/100129
