### ISSUE TITLE
Defining iterator in a separate class no longer works in 3.13

### ISSUE THREAD

**Issue by antonio-rojas** [python/cpython#128161]
# Bug report

### Bug description:

Defining an interator for a class in a separate class no longer works properly in 3.13. With the following `test_iter.py`:
```python
class list2(list):
    def __iter__(self):
        return list2iterator(self)

class list2iterator:
    def __init__(self, X):
        self._X = X
        self._pointer = -1

    def __next__(self):
        self._pointer += 1
        if self._pointer == len(self._X):
            self._pointer = -1
            raise StopIteration
        return self._X[self._pointer]
```
With Python 3.13.1 one gets:
```python
>>> from test_iter import list2
>>> X=list2([1,2,3])
>>> [x for x in X]
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    [x for x in X]
                ^
TypeError: 'list2iterator' object is not iterable
```
With Python 3.12.7 it works:
```python
>>> from test_iter import list2
>>> X=list2([1,2,3])
>>> [x for x in X]
[1, 2, 3]
```
Bisected to https://github.com/python/cpython/commit/bcc7227e

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-134778
* gh-134788
* gh-134799

**Comment by Eclips4** [comment]
cc @efimov-mikhail @markshannon @JelleZijlstra

**Comment by ronaldoussoren** [comment]
https://docs.python.org/3/library/stdtypes.html#iterator-types says that iterators must also implement ``__iter__`` (returning ``self``).  That's a long standing requirement on iterators, and not one introduced in 3.13.

**Comment by antonio-rojas** [comment]
Alright, thanks

**Comment by Eclips4** [comment]
@ronaldoussoren You're right, and this code is definitely doing something weird, but it works in 3.12:
example.py:
```python
class list2(list):
    def __iter__(self):
        return list2iterator(self)

class list2iterator:
    def __init__(self, X):
        self._X = X
        self._pointer = -1

    def __next__(self):
        self._pointer += 1
        if self._pointer == len(self._X):
            self._pointer = -1
            raise StopIteration
        return self._X[self._pointer]


target = list2([1, 2, 3])
for i in target:
    print(i)


[print(i) for i in target]
```

3.12.8:
```python
eclips4@suffering ~/tmp> python3.12 example.py
1
2
3
1
2
3
```

3.13.1:
```python
1                                                                                  
2
3
Traceback (most recent call last):
  File "/Users/eclips4/tmp/example.py", line 23, in <module>
    [print(i) for i in target]
                       ^^^^^^
TypeError: 'list2iterator' object is not iterable
```

**Comment by ronaldoussoren** [comment]
> @ronaldoussoren You're right, and this code is definitely doing something weird, but it works in 3.12: example.py:

Right, the code from the OP is broken according to the data model, but we still did a change that's not backward compatible. I'm not deep enough into this to fully understand the ramifications.

**Comment by efimov-mikhail** [comment]
This behavior change is a direct consequence of change in bytecode generation in my PR. I don't think this is a bug.

**Comment by terryjreedy** [comment]
The exact example worked in the CPython implementation of 3.12, but that may be an accident, as it should not have by the language definition.  It might have already failed in 3.12 in other  implementations.  In any case, adding the following exposes the defect in list2iterable even in 3.12.
```
target2 = iter(target)  # A list2iterator object
target3 = iter(target2)  # Fails in 3.12.8 
# TypeError: 'list2iterator' object is not iterable
```
If there is still a question about changing anything, Guido might remember the original design discussions.

**Comment by pochmann3** [comment]
Relevant bit from [glossary: iterator](https://docs.python.org/3/glossary.html#term-iterator):

> **CPython implementation detail:** CPython does not consistently apply the requirement that an iterator define `__iter__()`.

**Comment by terryjreedy** [comment]
Right.  A defective iterator may or may not work, so skip the requirement at your own risk.  Int caching is another implementation detail.  Implementation details are 1. subject to change and 2. are sometimes noted to discourage the filing of issues.  I think the iterator note followed a discussion and decision that the inconsistency should not be treated as a bug.  But the note also reaffirms the requirement.  Removing it, at least for for-loops, would have required other implementations and future CPythons to allow the omission.  All that is needed for list2iterator is `def __iter__(self): return self`.  This is not a great burden.  Its presence would make list2iterator also work for iter(list2iterator(somelist)).

**Comment by rhettinger** [comment]
FWIW, the OP's code also works in PyPy3, so this is more than a C implementation detail.

**Comment by serhiy-storchaka** [comment]
I think that the original change was not needed snd should be reverted. It just slows dowsn everyone's code.

**Comment by HinTak** [comment]
Well, I am somewhat unhappy about this as we have 4-year old code that works on all python version from 3.8 to 3.13 until last month; then it broke with 3.13.1; I thought mistakenly that github did something stupid in their CI images between 3.13 and 3.13.1. Never thought that python would break existing code within a minor version upgrade...

**Comment by picnixz** [comment]
Considering we broke something in a minor release, we should probably consider reverting the change. In addition, we ourself say that we don't consistently apply the requirement on iterators. 

So even if it's a data model requirement... I think it would be nicer to users. Considering the bytecode generation stuff was for a probably rarer usecase, I would prefer the above code to work instead.

**Comment by donhatch** [comment]
The issue title could perhaps be improved.

Current title: "Defining iterator in a separate class no longer works in 3.13"
Suggested new title: "Iterator without __iter__ no longer works in 3.13.1"

Details:
- If I understand correctly, the iterator being defined in a separate class isn't really relevant; what's very relevant is that it doesn't have an __iter__ member function
- it's significant that the version in which this broke is minor release 3.13.1, not 3.13 (I observe the example code succeeds in 3.13.0)

**Comment by donhatch** [comment]
The title and text of committed https://github.com/python/cpython/pull/132351 seems to imply that maybe it fixes this, i.e. reverts the behavior to pre-3.13.1 in which the example code works (because the generated bytcode has no redundant GET_ITER on something already known to be an iterator).

Is that correct?

That would make me very happy, since I would very much like to go back to happily ignoring the IMO ill-advised "requirement" that iterators be iterable (in fact it is my hope that some day that requirement might be officially removed, for a brighter less-confusing future in which Iterator and Iterable are two clearly distinct non-overlapping concepts).

**Comment by donhatch** [comment]
@efimov-mikhail wrote:

> And maybe it's reasonable to do some changes in docs?
Some clear mention about generator expressions like `(x for x in None)`, for example.
> They aren't correct in Python 3.13.3 and before, an exception will be raised on this expression in code.
> But on current 3.13 branch this code is correct.

(Unfortunately I don't currently have anything higher than 3.13.0 to try this out on...)

In 3.13.0 I see that `(x for x in None)` throws `TypeError: 'NoneType' object is not iterable` which seems reasonable to me.
Are you saying that, in later versions, it returns something instead of throwing, and that it's correct?  Why?

**Comment by efimov-mikhail** [comment]
> The title and text of committed [#132351](https://github.com/python/cpython/pull/132351) seems to imply that maybe it fixes this, i.e. reverts the behavior to pre-3.13.1 in which the example code works (because the generated bytcode has no redundant GET_ITER on something already known to be an iterator).
> 
> Is that correct?

No, this is not correct.
On current main branch

```python
-> % cat test_list2.py
class list2(list):
    def __iter__(self):
        return list2iterator(self)

class list2iterator:
    def __init__(self, X):
        self._X = X
        self._pointer = -1

    def __next__(self):
        self._pointer += 1
        if self._pointer == len(self._X):
            self._pointer = -1
            raise StopIteration
        return self._X[self._pointer]

[print(i) for i in target]

-> % ./python test_list2.py
Traceback (most recent call last):
  File "/home/sikko/projects/cpython/test_iter.py", line 21, in <module>
    [print(i) for i in target]
                       ^^^^^^
TypeError: 'list2iterator' object is not iterable

>>> dis.dis('[print(i) for i in target]')
   0           RESUME                   0

   1           LOAD_NAME                0 (target)
               GET_ITER
               LOAD_FAST_AND_CLEAR      0 (i)
               SWAP                     2
       L1:     BUILD_LIST               0
               SWAP                     2
               GET_ITER
       L2:     FOR_ITER                11 (to L3)
               STORE_FAST               0 (i)
               LOAD_NAME                1 (print)
               PUSH_NULL
               LOAD_FAST_BORROW         0 (i)
               CALL                     1
               LIST_APPEND              2
               JUMP_BACKWARD           13 (to L2)
       L3:     END_FOR
               POP_ITER
       L4:     SWAP                     2
               STORE_FAST               0 (i)
               RETURN_VALUE

  --   L5:     SWAP                     2
               POP_TOP

   1           SWAP                     2
               STORE_FAST               0 (i)
               RERAISE                  0
ExceptionTable:
  L1 to L4 -> L5 [2]
```

This is because of changes in bytecode.
You can see two `GET_ITER` bytecodes for list comprehension here.

> Suggested new title: "Iterator without `__iter__` no longer works in 3.13.1"

It sounds reasonable for me.

> (Unfortunately I don't currently have anything higher than 3.13.0 to try this out on...)
> 
> In 3.13.0 I see that `(x for x in None)` throws `TypeError: 'NoneType' object is not iterable` which seems reasonable to me. Are you saying that, in later versions, it returns something instead of throwing, and that it's correct? Why?

Yes, on current main, 3.14 and 3.13 branches we can see the following result:
```python
>>> g = (x for x in None)
>>> g
<generator object <genexpr> at 0x7f923bb48130>
>>> list(g)
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    list(g)
    ~~~~^^^
  File "<python-input-2>", line 1, in <genexpr>
    g = (x for x in None)
                    ^^^^
TypeError: 'NoneType' object is not iterable
```

cc @sobolevn

**Comment by Roman513** [comment]
This is fixed in 3.13.4:
```
Python 3.13.4 (main, Jun  4 2025, 17:14:13) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from test_iter import list2
>>> X=list2([1,2,3])
>>> [x for x in X]
[1, 2, 3]
```
But in 3.14.0b2 it sill does not work.

However it could be reintroduced again, related issue https://github.com/python/cpython/issues/135171 and fix https://github.com/python/cpython/pull/135225

If there's a decision how this should work, do we need some additional tests to make the behavior stable?
cc: @picnixz @markshannon

**Comment by serhiy-storchaka** [comment]
Whatever we decide on the `main` branch, you're better off adding an `__iter__` method returning `self` to your iterator. There's no guarantee that this will always work in CPython or other implementations.

**Comment by efimov-mikhail** [comment]
I've started related d.p.o. thread here: https://discuss.python.org/t/generator-expressions-behavior-with-non-iterable-objects/96329.
