### ISSUE TITLE
In the new REPL, multiline input execution should fail fast

### ISSUE THREAD

**Issue by johnslavik** [python/cpython#128231]
# Bug report

### Bug description:

To reproduce, simply paste this to the new REPL:

```py
raise Exception
print("But I'm powerful enough to bypass it")
```

Make sure what you are seeing is:

```pycon
>>> raise Exception
... print("But I'm powerful enough to bypass it")
```

Once hit enter, the new REPL executes both statements `raise Exception` and `print("But I'm powerful enough to bypass it")` from the same, multi-line input block, despite the failure of the first one:

```pycon
>>> raise Exception
... print("But I'm powerful enough to bypass it")
... 
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    raise Exception
Exception
But I'm powerful enough to bypass it
```

This can get especially confusing if a statement defines a variable. Like

```pycon
>>> n = 1 / 0
... print(k-n)
```
causing

```py
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    n = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "<python-input-0>", line 2, in <module>
    print(k-n)
          ^
NameError: name 'k' is not defined
```

I'd expect different behavior: since those two statements belong to the same input, it is more logical for them to behave like a [suite](https://docs.python.org/3.14/reference/compound_stmts.html#grammar-token-python-grammar-suite), where the consecutive execution of a statement depends on a successful completion of the one before it.

### CPython versions tested on:

3.13, 3.14

### Operating systems tested on:

Linux, macOS, Windows

### Linked PRs
* gh-129488
* gh-130513
* gh-131834
* gh-131835

**Comment by bswck** [comment]
This can get especially confusing if a statement defines a variable. Like ```pycon
>>> n = 1 / 0
... print(k-n)
```
causing ```py
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    n = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "<python-input-0>", line 2, in <module>
    print(k-n)
          ^
NameError: name 'k' is not defined
```

**Comment by bswck** [comment]
Making a PR for the fix.

**Comment by Eclips4** [comment]
Hi! Thanks for the report.
From my perspective as a someone who using REPL everyday, I'm suspect that it would stop executing after first exception.
Let's imagine the next input:
```python
x = foo(arg)  # for some reason, foo raises an exception
y = x * 10  # Would fail with NameError
```
I'm think that usually lines of code in code blocks are related and depends on each other, so I'm in favor of changing current behavior to "fail on first exception".
