### ISSUE TITLE
test_interpreters.test_stress Failed on aarch64 Fedora Stable Clang 3.x Buildbot

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#128381]
# Bug report

### Bug description:

https://buildbot.python.org/#/builders/234/builds/6793/steps/6/logs/stdio

Key log text:

```
test_create_many_threaded (test.test_interpreters.test_stress.StressTests.test_create_many_threaded) ... Warning -- Uncaught thread exception: InterpreterError
Exception in thread Thread-30 (task):
RuntimeError: Failed to import encodings module

During handling of the above exception, another exception occurred:

interpreters.InterpreterError: sub-interpreter creation failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-stable-aarch64.clang/build/Lib/test/test_interpreters/test_stress.py", line 30, in task
  ...
interpreters.InterpreterError: interpreter creation failed
```

...and during cleanup of test_interpreters:

```
python: Objects/typeobject.c:297: void managed_static_type_state_clear(PyInterpreterState *, PyTypeObject *, int, int): Assertion `!_PyRuntime.types.managed_static.types[full_index].interp_count' failed.
```

<details>
<summary>(expand for full logs)</summary>

```
0:00:50 load avg: 23.78 [400/481/1] test_interpreters worker non-zero exit code (Exit code -6 (SIGABRT)) -- running (10): test_socket (35.3 sec), test_capi (35.7 sec), test_statistics (50.2 sec), test_hashlib (30.3 sec), test_math (37.2 sec), test_int (50.1 sec), test.test_concurrent_futures.test_wait (48.8 sec), test.test_asyncio.test_events (34.2 sec), test_regrtest (43.2 sec), test.test_asyncio.test_tasks (46.3 sec)
test_after_destroy_all (test.test_interpreters.test_api.CreateTests.test_after_destroy_all) ... ok
test_after_destroy_some (test.test_interpreters.test_api.CreateTests.test_after_destroy_some) ... ok
test_in_main (test.test_interpreters.test_api.CreateTests.test_in_main) ... ok
test_in_subinterpreter (test.test_interpreters.test_api.CreateTests.test_in_subinterpreter) ... ok
test_in_thread (test.test_interpreters.test_api.CreateTests.test_in_thread) ... ok
test_created_with_capi (test.test_interpreters.test_api.GetCurrentTests.test_created_with_capi) ... ok
test_idempotent (test.test_interpreters.test_api.GetCurrentTests.test_idempotent) ... ok
test_main (test.test_interpreters.test_api.GetCurrentTests.test_main) ... ok
test_subinterpreter (test.test_interpreters.test_api.GetCurrentTests.test_subinterpreter) ... ok
test_current (test.test_interpreters.test_api.GetMainTests.test_current) ... ok
test_id (test.test_interpreters.test_api.GetMainTests.test_id) ... ok
test_idempotent (test.test_interpreters.test_api.GetMainTests.test_idempotent) ... ok
test_equality (test.test_interpreters.test_api.InterpreterObjectTests.test_equality) ... ok
test_hashable (test.test_interpreters.test_api.InterpreterObjectTests.test_hashable) ... ok
test_id_readonly (test.test_interpreters.test_api.InterpreterObjectTests.test_id_readonly) ... ok
test_id_type (test.test_interpreters.test_api.InterpreterObjectTests.test_id_type) ... ok
test_idempotent (test.test_interpreters.test_api.InterpreterObjectTests.test_idempotent) ... ok
test_init_bad_id (test.test_interpreters.test_api.InterpreterObjectTests.test_init_bad_id) ... ok
test_init_does_not_exist (test.test_interpreters.test_api.InterpreterObjectTests.test_init_does_not_exist) ... ok
test_init_int (test.test_interpreters.test_api.InterpreterObjectTests.test_init_int) ... ok
test_init_interpreter_id (test.test_interpreters.test_api.InterpreterObjectTests.test_init_interpreter_id) ... ok
test_init_unsupported (test.test_interpreters.test_api.InterpreterObjectTests.test_init_unsupported) ... ok
test_pickle (test.test_interpreters.test_api.InterpreterObjectTests.test_pickle) ... ok
test_whence (test.test_interpreters.test_api.InterpreterObjectTests.test_whence) ... ok
test_after_creating (test.test_interpreters.test_api.ListAllTests.test_after_creating) ... ok
test_after_destroying (test.test_interpreters.test_api.ListAllTests.test_after_destroying) ... ok
test_created_with_capi (test.test_interpreters.test_api.ListAllTests.test_created_with_capi) ... ok
test_idempotent (test.test_interpreters.test_api.ListAllTests.test_idempotent) ... ok
test_initial (test.test_interpreters.test_api.ListAllTests.test_initial) ... ok
test_call (test.test_interpreters.test_api.LowLevelTests.test_call) ... ok
test_create (test.test_interpreters.test_api.LowLevelTests.test_create) ... ok
test_destroy (test.test_interpreters.test_api.LowLevelTests.test_destroy) ... ok
test_exec (test.test_interpreters.test_api.LowLevelTests.test_exec) ... ok
test_get_config (test.test_interpreters.test_api.LowLevelTests.test_get_config) ... ok
test_get_current (test.test_interpreters.test_api.LowLevelTests.test_get_current) ... ok
test_get_main (test.test_interpreters.test_api.LowLevelTests.test_get_main) ... ok
test_is_running (test.test_interpreters.test_api.LowLevelTests.test_is_running) ... ok
test_list_all (test.test_interpreters.test_api.LowLevelTests.test_list_all) ... ok
test_new_config (test.test_interpreters.test_api.LowLevelTests.test_new_config) ... ok
test_set___main___attrs (test.test_interpreters.test_api.LowLevelTests.test_set___main___attrs) ... ok
test_whence (test.test_interpreters.test_api.LowLevelTests.test_whence) ... ok
test_queue_aliases (test.test_interpreters.test_api.ModuleTests.test_queue_aliases) ... ok
test_call (test.test_interpreters.test_api.TestInterpreterCall.test_call) ... ok
test_call_in_thread (test.test_interpreters.test_api.TestInterpreterCall.test_call_in_thread) ... ok
test_all (test.test_interpreters.test_api.TestInterpreterClose.test_all) ... ok
test_already_destroyed (test.test_interpreters.test_api.TestInterpreterClose.test_already_destroyed) ... ok
test_basic (test.test_interpreters.test_api.TestInterpreterClose.test_basic) ... ok
test_created_with_capi (test.test_interpreters.test_api.TestInterpreterClose.test_created_with_capi) ... ok
test_from_current (test.test_interpreters.test_api.TestInterpreterClose.test_from_current) ... ok
test_from_other_thread (test.test_interpreters.test_api.TestInterpreterClose.test_from_other_thread) ... ok
test_from_sibling (test.test_interpreters.test_api.TestInterpreterClose.test_from_sibling) ... ok
test_main (test.test_interpreters.test_api.TestInterpreterClose.test_main) ... ok
test_still_running (test.test_interpreters.test_api.TestInterpreterClose.test_still_running) ... skipped 'Fails on FreeBSD'
test_subthreads_still_running (test.test_interpreters.test_api.TestInterpreterClose.test_subthreads_still_running) ... ok
test_already_running (test.test_interpreters.test_api.TestInterpreterExec.test_already_running) ... skipped 'Fails on FreeBSD'
test_bad_script (test.test_interpreters.test_api.TestInterpreterExec.test_bad_script) ... ok
test_bytes_for_script (test.test_interpreters.test_api.TestInterpreterExec.test_bytes_for_script) ... ok
test_created_with_capi (test.test_interpreters.test_api.TestInterpreterExec.test_created_with_capi) ... ok
test_display_preserved_exception (test.test_interpreters.test_api.TestInterpreterExec.test_display_preserved_exception) ... ok
test_failure (test.test_interpreters.test_api.TestInterpreterExec.test_failure) ... ok
test_fork (test.test_interpreters.test_api.TestInterpreterExec.test_fork) ... ok
test_in_thread (test.test_interpreters.test_api.TestInterpreterExec.test_in_thread) ... ok
test_success (test.test_interpreters.test_api.TestInterpreterExec.test_success) ... ok
test_with_background_threads_still_running (test.test_interpreters.test_api.TestInterpreterExec.test_with_background_threads_still_running) ... ok
test_already_destroyed (test.test_interpreters.test_api.TestInterpreterIsRunning.test_already_destroyed) ... ok
test_created_with_capi (test.test_interpreters.test_api.TestInterpreterIsRunning.test_created_with_capi) ... ok
test_finished (test.test_interpreters.test_api.TestInterpreterIsRunning.test_finished) ... ok
test_from_subinterpreter (test.test_interpreters.test_api.TestInterpreterIsRunning.test_from_subinterpreter) ... ok
test_main (test.test_interpreters.test_api.TestInterpreterIsRunning.test_main) ... ok
test_subinterpreter (test.test_interpreters.test_api.TestInterpreterIsRunning.test_subinterpreter) ... skipped 'Fails on FreeBSD'
test_with_only_background_threads (test.test_interpreters.test_api.TestInterpreterIsRunning.test_with_only_background_threads) ... ok
test_created_with_capi (test.test_interpreters.test_api.TestInterpreterPrepareMain.test_created_with_capi) ... ok
test_dict (test.test_interpreters.test_api.TestInterpreterPrepareMain.test_dict) ... ok
test_dict_and_kwargs (test.test_interpreters.test_api.TestInterpreterPrepareMain.test_dict_and_kwargs) ... ok
test_empty (test.test_interpreters.test_api.TestInterpreterPrepareMain.test_empty) ... ok
test_kwargs (test.test_interpreters.test_api.TestInterpreterPrepareMain.test_kwargs) ... ok
test_not_shareable (test.test_interpreters.test_api.TestInterpreterPrepareMain.test_not_shareable) ... ok
test_running (test.test_interpreters.test_api.TestInterpreterPrepareMain.test_running) ... ok
test_tuple (test.test_interpreters.test_api.TestInterpreterPrepareMain.test_tuple) ... ok
test_default_shareables (test.test_interpreters.test_api.TestIsShareable.test_default_shareables) ... ok
test_not_shareable (test.test_interpreters.test_api.TestIsShareable.test_not_shareable) ... ok
test_highlevel_reloaded (test.test_interpreters.test_channels.LowLevelTests.test_highlevel_reloaded) ... ok
test_create (test.test_interpreters.test_channels.TestChannels.test_create) ... ok
test_is_closed (test.test_interpreters.test_channels.TestChannels.test_is_closed) ... ok
test_list_all (test.test_interpreters.test_channels.TestChannels.test_list_all) ... ok
test_shareable (test.test_interpreters.test_channels.TestChannels.test_shareable) ... ok
test_custom_id (test.test_interpreters.test_channels.TestRecvChannelAttrs.test_custom_id) ... ok
test_equality (test.test_interpreters.test_channels.TestRecvChannelAttrs.test_equality) ... ok
test_id_readonly (test.test_interpreters.test_channels.TestRecvChannelAttrs.test_id_readonly) ... ok
test_id_type (test.test_interpreters.test_channels.TestRecvChannelAttrs.test_id_type) ... ok
test_pickle (test.test_interpreters.test_channels.TestRecvChannelAttrs.test_pickle) ... ok
test_custom_id (test.test_interpreters.test_channels.TestSendChannelAttrs.test_custom_id) ... ok
test_equality (test.test_interpreters.test_channels.TestSendChannelAttrs.test_equality) ... ok
test_id_readonly (test.test_interpreters.test_channels.TestSendChannelAttrs.test_id_readonly) ... ok
test_id_type (test.test_interpreters.test_channels.TestSendChannelAttrs.test_id_type) ... ok
test_pickle (test.test_interpreters.test_channels.TestSendChannelAttrs.test_pickle) ... ok
test_recv_channel_does_not_exist (test.test_interpreters.test_channels.TestSendRecv.test_recv_channel_does_not_exist) ... ok
test_recv_nowait_channel_does_not_exist (test.test_interpreters.test_channels.TestSendRecv.test_recv_nowait_channel_does_not_exist) ... ok
test_recv_nowait_default (test.test_interpreters.test_channels.TestSendRecv.test_recv_nowait_default) ... ok
test_recv_nowait_empty (test.test_interpreters.test_channels.TestSendRecv.test_recv_nowait_empty) ... ok
test_recv_timeout (test.test_interpreters.test_channels.TestSendRecv.test_recv_timeout) ... ok
test_send_buffer (test.test_interpreters.test_channels.TestSendRecv.test_send_buffer) ... ok
test_send_buffer_nowait (test.test_interpreters.test_channels.TestSendRecv.test_send_buffer_nowait) ... ok
test_send_channel_does_not_exist (test.test_interpreters.test_channels.TestSendRecv.test_send_channel_does_not_exist) ... ok
test_send_cleared_with_subinterpreter (test.test_interpreters.test_channels.TestSendRecv.test_send_cleared_with_subinterpreter) ... ok
test_send_cleared_with_subinterpreter_mixed (test.test_interpreters.test_channels.TestSendRecv.test_send_cleared_with_subinterpreter_mixed) ... ok
test_send_cleared_with_subinterpreter_multiple (test.test_interpreters.test_channels.TestSendRecv.test_send_cleared_with_subinterpreter_multiple) ... ok
test_send_nowait_channel_does_not_exist (test.test_interpreters.test_channels.TestSendRecv.test_send_nowait_channel_does_not_exist) ... ok
test_send_recv_different_interpreters (test.test_interpreters.test_channels.TestSendRecv.test_send_recv_different_interpreters) ... skipped 'broken (see BPO-...)'
test_send_recv_different_threads (test.test_interpreters.test_channels.TestSendRecv.test_send_recv_different_threads) ... ok
test_send_recv_main (test.test_interpreters.test_channels.TestSendRecv.test_send_recv_main) ... ok
test_send_recv_nowait_different_interpreters (test.test_interpreters.test_channels.TestSendRecv.test_send_recv_nowait_different_interpreters) ... skipped 'broken (see BPO-...)'
test_send_recv_nowait_main (test.test_interpreters.test_channels.TestSendRecv.test_send_recv_nowait_main) ... ok
test_send_recv_nowait_main_with_default (test.test_interpreters.test_channels.TestSendRecv.test_send_recv_nowait_main_with_default) ... ok
test_send_recv_nowait_same_interpreter (test.test_interpreters.test_channels.TestSendRecv.test_send_recv_nowait_same_interpreter) ... ok
test_send_recv_same_interpreter (test.test_interpreters.test_channels.TestSendRecv.test_send_recv_same_interpreter) ... ok
test_gh_109793 (test.test_interpreters.test_lifecycle.FinalizationTests.test_gh_109793) ... ok
test_sys_path_0 (test.test_interpreters.test_lifecycle.StartupTests.test_sys_path_0) ... ok
test_bind_release (test.test_interpreters.test_queues.LowLevelTests.test_bind_release) ... ok
test_create_destroy (test.test_interpreters.test_queues.LowLevelTests.test_create_destroy) ... ok
test_highlevel_reloaded (test.test_interpreters.test_queues.LowLevelTests.test_highlevel_reloaded) ... ok
test_not_destroyed (test.test_interpreters.test_queues.LowLevelTests.test_not_destroyed) ... ok
test_create (test.test_interpreters.test_queues.QueueTests.test_create) ... ok
test_custom_id (test.test_interpreters.test_queues.QueueTests.test_custom_id) ... ok
test_equality (test.test_interpreters.test_queues.QueueTests.test_equality) ... ok
test_hashable (test.test_interpreters.test_queues.QueueTests.test_hashable) ... ok
test_id_readonly (test.test_interpreters.test_queues.QueueTests.test_id_readonly) ... ok
test_id_type (test.test_interpreters.test_queues.QueueTests.test_id_type) ... ok
test_maxsize_readonly (test.test_interpreters.test_queues.QueueTests.test_maxsize_readonly) ... ok
test_pickle (test.test_interpreters.test_queues.QueueTests.test_pickle) ... ok
test_shareable (test.test_interpreters.test_queues.QueueTests.test_shareable) ... ok
test_empty (test.test_interpreters.test_queues.TestQueueOps.test_empty) ... ok
test_full (test.test_interpreters.test_queues.TestQueueOps.test_full) ... ok
test_get_nowait (test.test_interpreters.test_queues.TestQueueOps.test_get_nowait) ... ok
test_get_timeout (test.test_interpreters.test_queues.TestQueueOps.test_get_timeout) ... ok
test_put_cleared_with_subinterpreter (test.test_interpreters.test_queues.TestQueueOps.test_put_cleared_with_subinterpreter) ... ok
test_put_cleared_with_subinterpreter_mixed (test.test_interpreters.test_queues.TestQueueOps.test_put_cleared_with_subinterpreter_mixed) ... ok
test_put_cleared_with_subinterpreter_multiple (test.test_interpreters.test_queues.TestQueueOps.test_put_cleared_with_subinterpreter_multiple) ... ok
test_put_get_default_not_syncobj (test.test_interpreters.test_queues.TestQueueOps.test_put_get_default_not_syncobj) ... ok
test_put_get_default_syncobj (test.test_interpreters.test_queues.TestQueueOps.test_put_get_default_syncobj) ... ok
test_put_get_different_interpreters (test.test_interpreters.test_queues.TestQueueOps.test_put_get_different_interpreters) ... ok
test_put_get_different_threads (test.test_interpreters.test_queues.TestQueueOps.test_put_get_different_threads) ... ok
test_put_get_main (test.test_interpreters.test_queues.TestQueueOps.test_put_get_main) ... ok
test_put_get_same_interpreter (test.test_interpreters.test_queues.TestQueueOps.test_put_get_same_interpreter) ... ok
test_put_not_syncobj (test.test_interpreters.test_queues.TestQueueOps.test_put_not_syncobj) ... ok
test_put_nowait (test.test_interpreters.test_queues.TestQueueOps.test_put_nowait) ... ok
test_put_syncobj (test.test_interpreters.test_queues.TestQueueOps.test_put_syncobj) ... ok
test_put_timeout (test.test_interpreters.test_queues.TestQueueOps.test_put_timeout) ... ok
test_qsize (test.test_interpreters.test_queues.TestQueueOps.test_qsize) ... ok
test_create_many_sequential (test.test_interpreters.test_stress.StressTests.test_create_many_sequential) ... ok
test_create_many_threaded (test.test_interpreters.test_stress.StressTests.test_create_many_threaded) ... Warning -- Uncaught thread exception: InterpreterError
Exception in thread Thread-30 (task):
RuntimeError: Failed to import encodings module

During handling of the above exception, another exception occurred:

interpreters.InterpreterError: sub-interpreter creation failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-stable-aarch64.clang/build/Lib/threading.py", line 1054, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-stable-aarch64.clang/build/Lib/threading.py", line 996, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-stable-aarch64.clang/build/Lib/test/test_interpreters/test_stress.py", line 30, in task
    interp = interpreters.create()
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-stable-aarch64.clang/build/Lib/test/support/interpreters/__init__.py", line 76, in create
    id = _interpreters.create(reqrefs=True)
interpreters.InterpreterError: interpreter creation failed
ok
test_many_threads_running_interp_in_other_interp (test.test_interpreters.test_stress.StressTests.test_many_threads_running_interp_in_other_interp) ... ok

----------------------------------------------------------------------
Ran 152 tests in 34.741s

OK (skipped=5)
python: Objects/typeobject.c:297: void managed_static_type_state_clear(PyInterpreterState *, PyTypeObject *, int, int): Assertion `!_PyRuntime.types.managed_static.types[full_index].interp_count' failed.
```

</details>

### CPython versions tested on:

CPython main branch

**Comment by serhiy-storchaka** [comment]
See also #109700.

**Comment by mhsmith** [comment]
Or more recently:
* #127108

**Comment by kumaraditya303** [comment]
I'm fixing this in https://github.com/python/cpython/issues/109700
