### ISSUE TITLE
DeprecationWarning message applies to wrong context with exec()

### ISSUE THREAD

**Issue by c7898a41-d409-4bdb-93cd-025165dbc3a3** [python/cpython#47673]
BPO | [3423](https://bugs.python.org/issue3423)
--- | :---
Nosy | @terryjreedy, @zware

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-07-22.00:40:41.357>
labels = ['type-feature']
title = 'DeprecationWarning message applies to wrong context with exec()'
updated_at = <Date 2014-06-24.04:38:25.968>
user = 'https://bugs.python.org/ghazel'
```

bugs.python.org fields:
```python
activity = <Date 2014-06-24.04:38:25.968>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['None']
creation = <Date 2008-07-22.00:40:41.357>
creator = 'ghazel'
dependencies = []
files = []
hgrepos = []
issue_num = 3423
keywords = []
message_count = 8.0
messages = ['70129', '107441', '107444', '109683', '221294', '221315', '221333', '221396']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'ghazel', 'zach.ware', 'Michael.Wu']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue3423'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by iritkatriel** [comment]
I think this is out of date. I get:


```
iritkatriel@Irits-MBP cpython-1 % cat t.py 
# wrong line!

import string

x = "string.make" + "trans('fd', 'f')"

# this prints the deprecation warning on the wrong line
exec(x)


#######

iritkatriel@Irits-MBP cpython-1 % ./python.exe t.py
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/t.py", line 8, in <module>
    exec(x)
  File "<string>", line 1, in <module>
AttributeError: module 'string' has no attribute 'maketrans'

```

**Comment by terryjreedy** [comment]
I agree, hence closing as stale.  Similarly to Irit's example, a simplified version of my previous example
```
from warnings import simplefilter
simplefilter('always', DeprecationWarning)
s = "a = 2\nraise DeprecationWarning('obsolete')"
exec(s)
```
now produces
```
Traceback (most recent call last):
  File "F:\dev\tem\tem2.py", line 4, in <module>
    exec(s)
  File "<string>", line 2, in <module>
DeprecationWarning: obsolete
```
and this and Irit's tracebacks are both correct.
