### ISSUE TITLE
repr of time.struct_time type does not eval

### ISSUE THREAD

**Issue by b9fb2d7d-1e0b-4bec-9cde-3f544756ee2f** [python/cpython#50157]
BPO | [5907](https://bugs.python.org/issue5907)
--- | :---
Nosy | @loewis, @birkenfeld, @rhettinger, @abalkin, @merwok, @bitdancer, @lilydjwg
Dependencies | <li>bpo-1820: Enhance Object/structseq.c to match namedtuple and tuple api</li><li>bpo-8413: String interpolation doesn&#x27;t work with sys.version_info</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2009-05-02.16:30:42.125>
labels = ['extension-modules', 'type-feature', 'tests', '3.7']
title = 'repr of time.struct_time type does not eval'
updated_at = <Date 2016-10-03.16:20:14.137>
user = 'https://bugs.python.org/jwm'
```

bugs.python.org fields:
```python
activity = <Date 2016-10-03.16:20:14.137>
actor = 'belopolsky'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Tests']
creation = <Date 2009-05-02.16:30:42.125>
creator = 'jwm'
dependencies = ['1820', '8413']
files = []
hgrepos = []
issue_num = 5907
keywords = []
message_count = 9.0
messages = ['86958', '86963', '86979', '87042', '87053', '133333', '133336', '133356', '197168']
nosy_count = 10.0
nosy_names = ['loewis', 'georg.brandl', 'rhettinger', 'belopolsky', 'eric.araujo', 'Arfrever', 'r.david.murray', 'jwm', 'santoso.wijaya', 'lilydjwg']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue5907'
versions = ['Python 3.7']
```

</p></details>

**Comment by AA-Turner** [comment]
Confirmed this still fails:

```pycon
>>> eval(repr(time.gmtime()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in <module>
TypeError: structseq() takes at most 2 keyword arguments (9 given)
```

A

**Comment by merwok** [comment]
Reprs often round-trip but it is not a requirement, and if it’s not explicitly documented by the object then changing it would not qualify as a bug.  Given the age of this ticket, I would suggest closing it.
