### ISSUE TITLE
email.message.Message.set_payload and as_string given charset 'us-ascii' plus 8bit data produces invalid message

### ISSUE THREAD

**Issue by bitdancer** [python/cpython#51553]
BPO | [7304](https://bugs.python.org/issue7304)
--- | :---
Nosy | @warsaw, @bitdancer, @mitya57

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2009-11-10.22:32:46.554>
labels = ['type-bug', 'expert-email']
title = "email.message.Message.set_payload and as_string given charset 'us-ascii' plus 8bit data produces invalid message"
updated_at = <Date 2012-06-06.08:33:05.367>
user = 'https://github.com/bitdancer'
```

bugs.python.org fields:
```python
activity = <Date 2012-06-06.08:33:05.367>
actor = 'mitya57'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['email']
creation = <Date 2009-11-10.22:32:46.554>
creator = 'r.david.murray'
dependencies = []
files = []
hgrepos = []
issue_num = 7304
keywords = []
message_count = 2.0
messages = ['95133', '156629']
nosy_count = 3.0
nosy_names = ['barry', 'r.david.murray', 'mitya57']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue7304'
versions = ['Python 2.7', 'Python 3.2', 'Python 3.3']
```

</p></details>

**Comment by matthieucan** [comment]
This does not reproduce anymore:
```python
Python 3.15.0a0 (heads/main:acefb978dc, Jul 19 2025, 13:23:54) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import email.message
>>> m = email.message.Message()
>>> m.set_payload("""A few lines
... of 8-bit text
...
... One high-bit character: ².
... """, 'us-ascii')
Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    m.set_payload("""A few lines
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
    of 8-bit text
    ^^^^^^^^^^^^^


    One high-bit character: ².
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
    """, 'us-ascii')
    ^^^^^^^^^^^^^^^^
  File "/Users/matthieu/git/cpython/Lib/email/message.py", line 349, in set_payload
    payload = payload.encode(charset.output_charset, 'surrogateescape')
UnicodeEncodeError: 'ascii' codec can't encode character '\xb2' in position 51: ordinal not in range(128)
```

**Comment by bitdancer** [comment]
Agreed, this is no longer an issue.   At this point the error is the correct behavior for the legacy set_payload interface.
