### ISSUE TITLE
Add support for IEEE 754 contexts to decimal module.

### ISSUE THREAD

**Issue by mdickinson** [python/cpython#53032]
BPO | [8786](https://bugs.python.org/issue8786)
--- | :---
Nosy | @rhettinger, @terryjreedy, @facundobatista, @mdickinson, @tiran, @ezio-melotti, @skrah, @mmaker
Files | <li>[issue8786.patch](https://bugs.python.org/file27214/issue8786.patch "Uploaded as text/plain at 2012-09-18.07:53:42 by @mmaker")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-05-22.10:28:31.524>
labels = ['type-feature', 'library']
title = 'Add support for IEEE 754 contexts to decimal module.'
updated_at = <Date 2013-08-30.16:08:54.755>
user = 'https://github.com/mdickinson'
```

bugs.python.org fields:
```python
activity = <Date 2013-08-30.16:08:54.755>
actor = 'skrah'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2010-05-22.10:28:31.524>
creator = 'mark.dickinson'
dependencies = []
files = ['27214']
hgrepos = []
issue_num = 8786
keywords = ['patch']
message_count = 8.0
messages = ['106294', '106296', '106297', '106303', '106325', '170637', '172903', '196559']
nosy_count = 8.0
nosy_names = ['rhettinger', 'terry.reedy', 'facundobatista', 'mark.dickinson', 'christian.heimes', 'ezio.melotti', 'skrah', 'maker']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue8786'
versions = ['Python 3.4']
```

</p></details>

### Linked PRs
* gh-122003

**Comment by skirpichev** [comment]
It seems, this doesn't work anymore:
```
$ ./configure CFLAGS=-DEXTRA_FUNCTIONALITY -q && make -s
configure: WARNING: no system libmpdecimal found; falling back to bundled libmpdecimal (deprecated and scheduled for removal in Python 3.15)
In function ‘word_to_string’,
    inlined from ‘coeff_to_string’ at ./Modules/_decimal/libmpdec/io.c:411:13,
    inlined from ‘_mpd_to_string’ at ./Modules/_decimal/libmpdec/io.c:612:18:
./Modules/_decimal/libmpdec/io.c:349:40: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  349 |         if (s == dot) *s++ = '.'; *s++ = '0' + (char)(x / d); x %= d
      |                                   ~~~~~^~~~~~~~~~~~~~~~~~~~~
./Modules/_decimal/libmpdec/io.c:360:14: note: in expansion of macro ‘EXTRACT_DIGIT’
  360 |     case 15: EXTRACT_DIGIT(s, x, 100000000000000ULL, dot);
      |              ^~~~~~~~~~~~~
[... and similar warnings from issue #108562, hardly relevant]
Checked 112 modules (34 built-in, 77 shared, 1 n/a on linux-x86_64, 0 disabled, 0 missing, 0 failed on import)
$ ./python 
Python 3.14.0a0 (heads/main:cecaceea31, Jul 19 2024, 05:34:00) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from decimal import *
>>> IEEEContext(11)
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    IEEEContext(11)
    ~~~~~~~~~~~^^^^
ValueError: argument must be a multiple of 32, with a maximum of 512
>>> IEEEContext(1024)
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    IEEEContext(1024)
    ~~~~~~~~~~~^^^^^^
ValueError: argument must be a multiple of 32, with a maximum of 512
>>> IEEEContext(512)  # oops
Segmentation fault
```

I'm working on this.

**Comment by skirpichev** [comment]
PR is ready for review: https://github.com/python/cpython/pull/122003

**Comment by vstinner** [comment]
Implemented by the change https://github.com/python/cpython/commit/5bf0f3666e272798789ff900b1071760c73b46fd.
