### ISSUE TITLE
test_locale error on AIX

### ISSUE THREAD

**Issue by cf2aeb3c-f43f-407a-8d37-30a2b5033222** [python/cpython#55399]
BPO | [11190](https://bugs.python.org/issue11190)
--- | :---
Nosy | @vstinner, @aixtools

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-08-28.09:04:33.520>
created_at = <Date 2011-02-11.14:59:01.363>
labels = ['3.8', '3.7', 'tests']
title = 'test_locale error on AIX'
updated_at = <Date 2018-08-28.09:04:33.519>
user = 'https://bugs.python.org/sable'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-28.09:04:33.519>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-08-28.09:04:33.520>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2011-02-11.14:59:01.363>
creator = 'sable'
dependencies = []
files = []
hgrepos = []
issue_num = 11190
keywords = []
message_count = 7.0
messages = ['128398', '128407', '271286', '271288', '324095', '324226', '324227']
nosy_count = 4.0
nosy_names = ['vstinner', 'sable', 'alef', 'Michael.Felt']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue11190'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
I wonder if defining HAVE_NON_UNICODE_WCHAR_T_REPRESENTATION helps to fix this issue on AIX too. @aixtools, could you please test this?

**Comment by vstinner** [comment]
I built Python 3.15 on AIX 7.1: test_locale pass successfully. I close again the issue.

**Comment by serhiy-storchaka** [comment]
Note that they are currently skipped on AIX. Did you unskip them?

**Comment by vstinner** [comment]
Ah! I unskipped the tests, then they fail with:

```
======================================================================
FAIL: test_strcoll_with_diacritic (test.test_locale.TestEnUSCollation.test_strcoll_with_diacritic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vstinner/cpython/Lib/test/test_locale.py", line 363, in test_strcoll_with_diacritic
    self.assertLess(locale.strcoll('à', 'b'), 0)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 1 not less than 0

======================================================================
FAIL: test_strxfrm_with_diacritic (test.test_locale.TestEnUSCollation.test_strxfrm_with_diacritic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vstinner/cpython/Lib/test/test_locale.py", line 369, in test_strxfrm_with_diacritic
    self.assertLess(locale.strxfrm('à'), locale.strxfrm('b'))
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ǢĀ' not less than 'ŤĀ'
```
