### ISSUE TITLE
ConfigParser does not handle files without sections

### ISSUE THREAD

**Issue by 4c5a66fc-a623-4629-abbc-fd3d448e9ebf** [python/cpython#66449]
BPO | [22253](https://bugs.python.org/issue22253)
--- | :---
Nosy | @terryjreedy, @pfmoore, @ambv, @vadmium, @serhiy-storchaka, @kernc, @pslacerda, @johnlinp
PRs | <li>python/cpython#2735</li>
Files | <li>[nosection.patch](https://bugs.python.org/file43345/nosection.patch "Uploaded as text/plain at 2016-06-11.20:59:21 by @pslacerda")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ambv'
closed_at = None
created_at = <Date 2014-08-22.18:22:48.077>
labels = ['type-feature', 'library']
title = 'ConfigParser does not handle files without sections'
updated_at = <Date 2019-11-05.20:39:34.585>
user = 'https://github.com/kernc'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-05.20:39:34.585>
actor = 'Pedro Lacerda'
assignee = 'lukasz.langa'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2014-08-22.18:22:48.077>
creator = 'kernc'
dependencies = []
files = ['43345']
hgrepos = []
issue_num = 22253
keywords = ['patch']
message_count = 15.0
messages = ['225693', '225696', '225715', '226587', '226593', '226621', '226827', '226835', '226909', '226936', '227749', '268271', '298339', '298448', '356060']
nosy_count = 9.0
nosy_names = ['terry.reedy', 'paul.moore', 'lukasz.langa', 'tshepang', 'martin.panter', 'serhiy.storchaka', 'kernc', 'Pedro Lacerda', 'johnlinp']
pr_nums = ['2735']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue22253'
versions = []
```

</p></details>

### Linked PRs
* gh-117273
* gh-123874
* gh-123879

**Comment by 693f263f-a080-47dc-8f14-c27d15b50a75** [comment]
Hi Pedro Lacerda,

I think you should submit your patch as a GitHub pull request. Please correct me if I'm wrong. Thanks.

**Comment by e2c8937d-f61e-4a31-ac2a-eef3f6314aa5** [comment]
Thank you 林自均! I just made a pull-request with the relevant bits.

**Comment by hw-claudio** [comment]
> I also never found a mixture of sectionless options followed by sectioned options. So an unnamed section that is also the DEFAULTSECTION will probably work.

I would like to clarify a couple things on how INI files actually work in Windows. I started to see bugs in the wine project starting around 2007, where INI files where not properly loaded, or were ruined on save. See:

https://github.com/wine-mirror/wine/commit/be678a52e163111085ab3694b6c1f3af8e4d4a4a
https://bugs.winehq.org/show_bug.cgi?id=8036
https://bugs.winehq.org/show_bug.cgi?id=18099

That is when I started to research the topic, and discovered how Microsoft Windows actually handles INI files (which is slightly different depending on version, but mostly comparable).

First of all, the unnamed section, or empty string section, is absolutely a feature, albeit undocumented.
The Windows API documentation leaves the case, well, undocumented:
https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilestring

However, software actually uses this behavior.
Secondly, the unnamed section does coexist with named sections. INI files generated by the Multimedia Fusion framework for example, put the global/general options in the unnamed/empty string section, and the other options in the appropriate subsection.

If I understand the PR correctly, this is what the PR attempts to achieve, so it is absolutely correct if INI profiles are the model for this feature. I would actually like to use this module, but currently can't due to this missing feature.

Ciao,

Claudio

**Comment by pslacerda** [comment]
There are cases of INI-like files but with other extensions (eg. mdp file https://manual.gromacs.org/current/reference-manual/file-formats.html#mdp)

**Comment by jaraco** [comment]
This functionality is now available in the [backport](https://pypi.org/project/configparser) (version 7, available for Python 3.8+). Feel free to give it a test drive in your environment so we can work out any bugs.

**Comment by mtnpke** [comment]
Hi, just chiming in because I really love this new feature - however, I haven't managed to create a new INI file from scratch with an unnamed section yet. Is this possible? Here are my futile attempts with configparser 7.0.0 from backports:

```
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
>>> from backports.configparser import UNNAMED_SECTION, ConfigParser
>>> cp = ConfigParser(allow_unnamed_section=True)
>>> cp.set(UNNAMED_SECTION, "option1", "hello world")
Traceback (most recent call last):
    super().set(section, option, value)
    raise NoSectionError(section) from None
backports.configparser.NoSectionError: No section: <UNNAMED_SECTION>
>>> cp.add_section(UNNAMED_SECTION)
  File "C:\Users\kerling\AppData\Local\pypoetry\Cache\virtualenvs\non-package-mode-l42eA81v-py3.12\Lib\site-packages\backports\configparser\__init__.py", line 1294, in _validate_value_types
    raise TypeError("section names must be strings")
TypeError: section names must be strings
>>> cp[UNNAMED_SECTION]["option1"] = "hello world"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kerling\AppData\Local\pypoetry\Cache\virtualenvs\non-package-mode-l42eA81v-py3.12\Lib\site-packages\backports\configparser\__init__.py", line 1070, in __getitem__
    raise KeyError(key)
KeyError: <UNNAMED_SECTION>
>>> cp[UNNAMED_SECTION] = { "option1": "hello world" }
>>> cp.sections()
['<UNNAMED_SECTION>']
>>> import io
>>> fp = io.StringIO()
>>> cp.write(fp)
>>> fp.getvalue()
'[<UNNAMED_SECTION>]\noption1 = hello world\n\n'
```

**Comment by jaraco** [comment]
@mtnpke I opened a new issue to track your missed expectation. As far as I understand, the support was for reading unnamed sections and not authoring them. That's not to say it can't be added, but I think we should track it as a separate issue (on the near 10 year anniversary of this one).

**Comment by adorilson** [comment]
[Python 3.13 came with this feature](https://docs.python.org/pt-br/3.13/whatsnew/3.13.html#configparser), so I think this issue can be closed. Or is there some pendency?
