### ISSUE TITLE
webbrowser broken on Mac OS X when using the BROWSER variable

### ISSUE THREAD

**Issue by 1ff34f4a-5afa-4860-8a81-b0c796ebb44f** [python/cpython#69143]
BPO | [24955](https://bugs.python.org/issue24955)
--- | :---
Nosy | @ronaldoussoren, @orsenthil, @ned-deily, @dhellmann, @grimreaper, @hudelgado, @akulakov
PRs | <li>python/cpython#27751</li>
Files | <li>[webbrowser.patch](https://bugs.python.org/file40291/webbrowser.patch "Uploaded as text/plain at 2015-08-29.10:17:33 by sconseil")</li><li>[24955.diff](https://bugs.python.org/file49341/24955.diff "Uploaded as text/plain at 2020-07-27.03:16:47 by @hudelgado")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/orsenthil'
closed_at = None
created_at = <Date 2015-08-29.10:01:40.688>
labels = ['OS-mac', 'library', '3.11']
title = 'webbrowser broken on Mac OS X when using the BROWSER variable'
updated_at = <Date 2021-08-17.16:46:29.259>
user = 'https://bugs.python.org/sconseil'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-17.16:46:29.259>
actor = 'corona10'
assignee = 'orsenthil'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'macOS']
creation = <Date 2015-08-29.10:01:40.688>
creator = 'sconseil'
dependencies = []
files = ['40291', '49341']
hgrepos = []
issue_num = 24955
keywords = ['patch']
message_count = 13.0
messages = ['249316', '249317', '257198', '257962', '258120', '258122', '374220', '374221', '374223', '374231', '374358', '399394', '399488']
nosy_count = 10.0
nosy_names = ['ehuss', 'ronaldoussoren', 'orsenthil', 'ned.deily', 'doughellmann', 'eitan.adler', 'sconseil', '_kud', 'hudelgado', 'andrei.avk']
pr_nums = ['27751']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue24955'
versions = ['Python 3.11']
```

</p></details>

**Comment by ronaldoussoren** [comment]
This works in the current releases for 3.9, 3.10, 3.11 and 3.12: `BROWSER=chrome python3 -m webbrowser http://www.python.org/`. 

That means this issue is no longer needed.

**Comment by schiebel** [comment]
I do not see the behavior that @ronaldoussoren describes:
```
bash$ python -V
Python 3.10.13
bash$ BROWSER=chrome python -m webbrowser http://www.python.org/ ## OPENS IN DEFAULT BROWSER

bash$ BROWSER=safari python -m webbrowser http://www.python.org/ ## ALSO OPENS IN DEFAULT BROWSER

bash$ BROWSER=/Applications/Safari.app/Contents/MacOS/Safari python -m webbrowser http://www.python.org/
Traceback (most recent call last):
  File "/Users/drs/develop/python/conda/envs/bokeh-32/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/drs/develop/python/conda/envs/bokeh-32/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/drs/develop/python/conda/envs/bokeh-32/lib/python3.10/webbrowser.py", line 717, in <module>
    main()
  File "/Users/drs/develop/python/conda/envs/bokeh-32/lib/python3.10/webbrowser.py", line 712, in main
    open(url, new_win)
  File "/Users/drs/develop/python/conda/envs/bokeh-32/lib/python3.10/webbrowser.py", line 83, in open
    register_standard_browsers()
  File "/Users/drs/develop/python/conda/envs/bokeh-32/lib/python3.10/webbrowser.py", line 591, in register_standard_browsers
    cmd = _synthesize(cmdline, preferred=True)
  File "/Users/drs/develop/python/conda/envs/bokeh-32/lib/python3.10/webbrowser.py", line 127, in _synthesize
    if controller and name.lower() == controller.basename:
AttributeError: 'MacOSXOSAScript' object has no attribute 'basename'
bash$ 
```
Chrome is my default browser, but sometimes it is helpful to be able to test in Safari.
