### ISSUE TITLE
tarfile in stream mode always set zlib compression level to 9

### ISSUE THREAD

**Issue by 2a581834-dfb5-4565-8b4b-2539069a8bcf** [python/cpython#70441]
BPO | [26253](https://bugs.python.org/issue26253)
--- | :---
Nosy | @gustaebel, @vadmium, @wimglenn, @zhangyangyu, @jarondl
PRs | <li>python/cpython#2962</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-02-01.00:55:23.398>
labels = ['3.7', 'type-feature', 'library']
title = 'tarfile in stream mode always set zlib compression level to 9'
updated_at = <Date 2017-08-01.17:03:47.325>
user = 'https://bugs.python.org/PatrikDufresne'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-01.17:03:47.325>
actor = 'jarondl'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-02-01.00:55:23.398>
creator = 'Patrik Dufresne'
dependencies = []
files = []
hgrepos = []
issue_num = 26253
keywords = []
message_count = 6.0
messages = ['259304', '259308', '259987', '292628', '297220', '299622']
nosy_count = 6.0
nosy_names = ['lars.gustaebel', 'martin.panter', 'wim.glenn', 'xiang.zhang', 'Patrik Dufresne', 'jarondl']
pr_nums = ['2962']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue26253'
versions = ['Python 3.7']
```

</p></details>

**Comment by zhangyangyu** [comment]
\*compresslevel* takes effect for modes 'w:gz', 'r:gz', 'w:bz2', 'r:bz2', 'x:gz', 'x:bz2'. For stream modes, 'r|gz', 'w|gz', 'r|bz2', 'w|bz2', the \*compresslevel* doesn't make sense. It seems not hard to make it possible but I'm not sure it's worth it or there is any reason it's hard-coded.

**Comment by 310dd13a-adf5-42f8-b3ef-a4a4f2d763e3** [comment]
This issue also got me.  compresslevel kwarg works fine for tarfile.open(..., mode='w:gz') but raises exception for tarfile.open(..., mode='w|gz')

I want to use stream compression, and compresslevel=1 is more than enough for my use case, the default of 9 is way too slow.

**Comment by 9ebd57ca-3afd-4f57-a549-6a1ad70de606** [comment]
I have submitted a PR on GitHub https://github.com/python/cpython/pull/2962

**Comment by tiran** [comment]
The PR broke tests on systems without the optional bz2 module.

**Comment by tiran** [comment]
```
======================================================================
ERROR: test_wrong_compresslevels (test.test_tarfile.CompressLevelRaises.test_wrong_compresslevels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Lib/test/test_tarfile.py", line 1620, in test_wrong_compresslevels
    tarfile.open(tmpname, "w:bz2", fobj, compresslevel=0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Lib/tarfile.py", line 1654, in open
    return func(name, filemode, fileobj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Lib/tarfile.py", line 1732, in bz2open
    raise CompressionError("bz2 module is not available") from None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tarfile.CompressionError: bz2 module is not available
----------------------------------------------------------------------
```

**Comment by hauntsaninja** [comment]
Thanks, looks like this has been completed and the test has been fixed
