### ISSUE TITLE
multiprocessing Manager error:  send() called for a closed connection

### ISSUE THREAD

**Issue by b45b77b5-dec5-42e2-8733-520d0a9f52dc** [python/cpython#71936]
BPO | [27749](https://bugs.python.org/issue27749)
--- | :---
Nosy | @pfmoore, @tjguk, @bitdancer, @zware, @eryksun, @zooba, @applio, @AraHaan
Files | <li>[python.exe.8228.dmp](https://bugs.python.org/file44099/python.exe.8228.dmp "Uploaded as application/octet-stream at 2016-08-13.20:39:06 by @AraHaan")</li><li>[debug_AA1F93C2.JPG](https://bugs.python.org/file44116/debug_AA1F93C2.JPG "Uploaded as image/jpeg at 2016-08-15.10:01:09 by wevsty"): multiprocessing debug Screenshot</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-08-12.18:59:30.581>
labels = ['type-bug', '3.8', '3.9', '3.10', 'library', 'OS-windows']
title = 'multiprocessing Manager error:  send() called for a closed connection'
updated_at = <Date 2021-03-13.22:29:18.086>
user = 'https://bugs.python.org/wevsty'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-13.22:29:18.086>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2016-08-12.18:59:30.581>
creator = 'wevsty'
dependencies = []
files = ['44099', '44116']
hgrepos = []
issue_num = 27749
keywords = []
message_count = 14.0
messages = ['272557', '272577', '272581', '272584', '272589', '272615', '272616', '272647', '272653', '272743', '272861', '273007', '334464', '334628']
nosy_count = 10.0
nosy_names = ['paul.moore', 'tim.golden', 'r.david.murray', 'zach.ware', 'eryksun', 'steve.dower', 'davin', 'Decorater', 'wevsty', 'Michael Jacob2']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue27749'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-98274
* gh-124973
* gh-126869
* gh-126870

**Comment by basnijholt** [comment]
I can consistently reproduce this problem (unfortunately with a [third party library](https://github.com/pipefunc/pipefunc) that I maintain) on Python 3.12.3 on Ubuntu.

The code:
```python
from concurrent.futures import ProcessPoolExecutor
from pipefunc import pipefunc, Pipeline

for _ in range(100):

    @pipefunc(output_name="c", cache=True)
    def f(a, b):
        return a + b

    pipeline = Pipeline([f], cache_type="lru")
    func = pipeline.func("c")
    sequence = 100 * [{"a": 2, "b": 3}]
    with ProcessPoolExecutor(max_workers=1) as executor:
        results = executor.map(func.call_with_dict, sequence)
        list(results)
```
Which outputs:
```
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/bas.nijholt/micromamba/envs/pipefunc/lib/python3.12/concurrent/futures/process.py", line 263, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bas.nijholt/micromamba/envs/pipefunc/lib/python3.12/concurrent/futures/process.py", line 212, in _process_chunk
    return [fn(*args) for args in chunk]
            ^^^^^^^^^
  File "/home/bas.nijholt/repos/pipefunc/pipefunc/_pipeline.py", line 1304, in call_with_dict
    return self(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/bas.nijholt/repos/pipefunc/pipefunc/_pipeline.py", line 1274, in __call__
    return self.pipeline.run(output_name=self.output_name, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bas.nijholt/repos/pipefunc/pipefunc/_pipeline.py", line 490, in run
    self._run(
  File "/home/bas.nijholt/repos/pipefunc/pipefunc/_pipeline.py", line 422, in _run
    return_now, result_from_cache = _get_result_from_cache(
                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bas.nijholt/repos/pipefunc/pipefunc/_pipeline.py", line 1398, in _get_result_from_cache
    if cache_key is not None and cache_key in cache:
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/bas.nijholt/repos/pipefunc/pipefunc/_cache.py", line 316, in __contains__
    return key in self._cache_dict
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in __contains__
  File "/home/bas.nijholt/micromamba/envs/pipefunc/lib/python3.12/multiprocessing/managers.py", line 820, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/home/bas.nijholt/micromamba/envs/pipefunc/lib/python3.12/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/bas.nijholt/micromamba/envs/pipefunc/lib/python3.12/multiprocessing/connection.py", line 427, in _send_bytes
    self._send(header + buf)
  File "/home/bas.nijholt/micromamba/envs/pipefunc/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[1], line 19
     17 with ProcessPoolExecutor(max_workers=1) as executor:
     18     results = executor.map(func.call_with_dict, sequence)
---> 19     list(results)

File ~/micromamba/envs/pipefunc/lib/python3.12/concurrent/futures/process.py:642, in _chain_from_iterable_of_lists(iterable)
    636 def _chain_from_iterable_of_lists(iterable):
    637     """
    638     Specialized implementation of itertools.chain.from_iterable.
    639     Each item in *iterable* should be a list.  This function is
    640     careful not to keep references to yielded objects.
    641     """
--> 642     for element in iterable:
    643         element.reverse()
    644         while element:

File ~/micromamba/envs/pipefunc/lib/python3.12/concurrent/futures/_base.py:619, in Executor.map.<locals>.result_iterator()
    616 while fs:
    617     # Careful not to keep a reference to the popped future
    618     if timeout is None:
--> 619         yield _result_or_cancel(fs.pop())
    620     else:
    621         yield _result_or_cancel(fs.pop(), end_time - time.monotonic())

File ~/micromamba/envs/pipefunc/lib/python3.12/concurrent/futures/_base.py:317, in _result_or_cancel(***failed resolving arguments***)
    315 try:
    316     try:
--> 317         return fut.result(timeout)
    318     finally:
    319         fut.cancel()

File ~/micromamba/envs/pipefunc/lib/python3.12/concurrent/futures/_base.py:456, in Future.result(self, timeout)
    454     raise CancelledError()
    455 elif self._state == FINISHED:
--> 456     return self.__get_result()
    457 else:
    458     raise TimeoutError()

File ~/micromamba/envs/pipefunc/lib/python3.12/concurrent/futures/_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

TypeError: 'NoneType' object cannot be interpreted as an integer
```

I applied the patch in https://github.com/python/cpython/pull/98274 which seems to have solve the problem.

**Comment by encukou** [comment]
Merged in main. I'll watch the buildbots for a bit before backporting.

**Comment by basnijholt** [comment]
@encukou, sorry that it took me this long to reply but using the code in https://github.com/python/cpython/issues/71936#issuecomment-2164009639 and your patch from https://github.com/python/cpython/pull/124973, I can no longer reproduce the problem!

Thanks a lot!

**Comment by encukou** [comment]
The backports are in. Thank you to everyone involved!
