### ISSUE TITLE
is_zipfile false positives

### ISSUE THREAD

**Issue by 73104530-ea09-48eb-8e89-fbef1c14f7e7** [python/cpython#72680]
BPO | [28494](https://bugs.python.org/issue28494)
--- | :---
Nosy | @Yhg1s, @gpshead, @vstinner, @serhiy-storchaka, @thomaswaldmann, @jjolly, @miss-islington
PRs | <li>python/cpython#5053</li><li>python/cpython#15853</li><li>python/cpython#15891</li><li>python/cpython#15902</li><li>python/cpython#15912</li>
Files | <li>[isz_fail.py](https://bugs.python.org/file45162/isz_fail.py "Uploaded as text/plain at 2016-10-20.21:08:48 by @thomaswaldmann")</li><li>[isz_fail_fix.diff](https://bugs.python.org/file45164/isz_fail_fix.diff "Uploaded as text/plain at 2016-10-20.22:26:45 by @thomaswaldmann")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gpshead'
closed_at = None
created_at = <Date 2016-10-20.21:08:48.959>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = 'is_zipfile false positives'
updated_at = <Date 2019-09-11.11:09:56.949>
user = 'https://github.com/ThomasWaldmann'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-11.11:09:56.949>
actor = 'miss-islington'
assignee = 'gregory.p.smith'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-10-20.21:08:48.959>
creator = 'Thomas.Waldmann'
dependencies = []
files = ['45162', '45164']
hgrepos = []
issue_num = 28494
keywords = ['patch']
message_count = 16.0
messages = ['279084', '279088', '279089', '280341', '281805', '281817', '309245', '311281', '334595', '351723', '351749', '351750', '351751', '351755', '351802', '351823']
nosy_count = 9.0
nosy_names = ['twouters', 'gregory.p.smith', 'alanmcintyre', 'vstinner', 'serhiy.storchaka', 'Thomas.Waldmann', 'mryan1539', 'jjolly', 'miss-islington']
pr_nums = ['5053', '15853', '15891', '15902', '15912']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue28494'
versions = ['Python 2.7', 'Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-134250
* gh-134401

**Comment by vpv-csc** [comment]
Any chance https://github.com/python/cpython/pull/5053 could be merged? A user of ours has a TIFF file, for which `is_zipfile` returns `True`, but calling the `ZipFile` constructor results in `BadZipFile`. I probably can not give out the file, but here's an example run:

```
Python 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 14.0.1 20240411 (Red Hat 14.0.1-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zipfile
>>> zipfile.is_zipfile("testfile.tif")
True
>>> zipfile.ZipFile("testfile.tif")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.12/zipfile/__init__.py", line 1349, in __init__
    self._RealGetContents()
  File "/usr/lib64/python3.12/zipfile/__init__.py", line 1435, in _RealGetContents
    raise BadZipFile("Bad offset for central directory")
zipfile.BadZipFile: Bad offset for central directory
```

**Comment by gpshead** [comment]
Thanks for the PR work @jjolly and @thatch!  Finally merged.
