### ISSUE TITLE
importing ssl can fail with NameError: name 'PROTOCOL_TLS' is not defined

### ISSUE THREAD

**Issue by jdemeyer** [python/cpython#73774]
BPO | [29588](https://bugs.python.org/issue29588)
--- | :---
Nosy | @tiran, @jdemeyer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2017-09-06.19:50:40.509>
created_at = <Date 2017-02-17.11:35:23.374>
labels = ['expert-SSL', 'type-bug']
title = "importing ssl can fail with NameError: name 'PROTOCOL_TLS' is not defined"
updated_at = <Date 2017-09-06.19:50:40.508>
user = 'https://github.com/jdemeyer'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-06.19:50:40.508>
actor = 'christian.heimes'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2017-09-06.19:50:40.509>
closer = 'christian.heimes'
components = ['SSL']
creation = <Date 2017-02-17.11:35:23.374>
creator = 'jdemeyer'
dependencies = []
files = []
hgrepos = []
issue_num = 29588
keywords = []
message_count = 2.0
messages = ['287989', '287991']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'jdemeyer']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29588'
versions = ['Python 2.7']
```

</p></details>

**Comment by jdemeyer** [comment]
This is a regression introduced in Python 2.7.13:

Importing the ssl module can fail with

```pycon
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jdemeyer/sage/local/lib/python/ssl.py", line 133, in <module>
    PROTOCOL_SSLv23 = PROTOCOL_TLS
NameError: name 'PROTOCOL_TLS' is not defined
```


While getting an ImportError from the ssl module is expected if SSL is not available (httplib for example handles that fine), a NameError is not.

**Comment by tiran** [comment]
The \_ssl extension module always defines and exports PROTOCOL_TLS. The name is always available. I guess you somehow mixed a new ssl.py with an old \_ssl.so. Please verify that \_ssl is correct and defines the name.
