### ISSUE TITLE
ImportError when importing the package `queue`

### ISSUE THREAD

**Issue by e086f85f-51b6-4ac1-bf4e-527d65518b1d** [python/cpython#73790]
BPO | [29604](https://bugs.python.org/issue29604)
--- | :---
Nosy | @gvanrossum, @tiran, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-20.13:04:13.898>
created_at = <Date 2017-02-20.12:55:25.222>
labels = ['type-bug', 'invalid', 'expert-asyncio']
title = 'ImportError when importing the package `queue`'
updated_at = <Date 2017-02-20.13:04:13.889>
user = 'https://bugs.python.org/GianlucaRossi'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-20.13:04:13.889>
actor = 'christian.heimes'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-20.13:04:13.898>
closer = 'christian.heimes'
components = ['asyncio']
creation = <Date 2017-02-20.12:55:25.222>
creator = 'Gianluca Rossi'
dependencies = []
files = []
hgrepos = []
issue_num = 29604
keywords = []
message_count = 2.0
messages = ['288198', '288199']
nosy_count = 4.0
nosy_names = ['gvanrossum', 'christian.heimes', 'yselivanov', 'Gianluca Rossi']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29604'
versions = ['Python 3.5']
```

</p></details>

**Comment by e086f85f-51b6-4ac1-bf4e-527d65518b1d** [comment]
In Python 3.5.2 importing \*queue* raises an \*ImportError*.

```
Python 3.5.2 (default, Jul  5 2016, 12:43:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import queue
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gianluca/git/python/asyncio/queue.py", line 1, in <module>
    import asyncio
  File "/usr/lib/python3.5/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/lib/python3.5/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/lib/python3.5/concurrent/futures/__init__.py", line 17, in <module>
    from concurrent.futures.process import ProcessPoolExecutor
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 52, in <module>
    from queue import Full
ImportError: cannot import name 'Full'
```

I'm not very familiar with the \*asyncio* module since I've just recently started working with it. Please let me know if I can be of more help.

**Comment by tiran** [comment]
You have a queue module in your project which shadows the queue module from Python's standard library.
