### ISSUE TITLE
TarFile.extract() suffers from hard links inside tarball

### ISSUE THREAD

**Issue by 23834b0e-c55a-4440-b78c-d7d130f66533** [python/cpython#73798]
BPO | [29612](https://bugs.python.org/issue29612)
--- | :---
Nosy | @gustaebel, @ethanfurman, @j0ack
PRs | <li>python/cpython#5753</li><li>python/cpython#8700</li><li>python/cpython#16958</li>
Files | <li>[tartest.py](https://bugs.python.org/file46658/tartest.py "Uploaded as text/plain at 2017-02-21.10:10:45 by Jussi Judin")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-02-21.10:10:46.770>
labels = ['3.7', '3.8', 'type-bug', 'library', '3.9']
title = 'TarFile.extract() suffers from hard links inside tarball'
updated_at = <Date 2020-01-19.18:55:54.762>
user = 'https://bugs.python.org/JussiJudin'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-19.18:55:54.762>
actor = 'zach.ware'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-02-21.10:10:46.770>
creator = 'Jussi Judin'
dependencies = []
files = ['46658']
hgrepos = []
issue_num = 29612
keywords = ['patch']
message_count = 7.0
messages = ['288284', '289360', '312235', '312345', '312900', '314588', '320140']
nosy_count = 6.0
nosy_names = ['guettli', 'lars.gustaebel', 'ethan.furman', 'Jussi Judin', 'jtrouverie', 'Larry Cook']
pr_nums = ['5753', '8700', '16958']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29612'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by 23834b0e-c55a-4440-b78c-d7d130f66533** [comment]
I managed to create a tarball that brought out quite nasty behavior with tarfile.TarFile.extract() and tarfile.TarFile.extractall() functions when there are hard links inside a tarball that point to themselves with a file that is included in the tarball. In Python 2.7 it leads to an exception and with Python 3.4-3.6 it extracts the same file from the tarball multiple times.

First we create a tarball that causes this behavior:

```sh
$ mkdir -p tardata/1/2/3/4/5/6/7/8/9
$ dd if=/dev/zero of=tardata/1/2/3/4/5/6/7/8/9/zeros.data bs=1000000 count=500
# tar by default adds all directories recursively multiple times to the archive, but duplicates are created as hard links:
$ find tardata | xargs tar cvfz tardata.tar.gz
```


Then let's extract the tarball with tarfile module
Let following commands demonstrate what happens with the attached tartest.py file

```pytb
$ python2.7.13 tartest.py noskip tardata.tar.gz /tmp/tardata-python-2.7.13
...
tardata/1/2/3/4/5/6/7/8/9/zeros.data
...
tardata/1/2/3/4/5/6/7/8/9/zeros.data
Traceback (most recent call last):
  File "tartest.py", line 17, in <module>
    unarchive(skip, archive, dest)
  File "tartest.py", line 12, in unarchive
    tar_fd.extract(info, dest)
  File "python/2.7.13/lib/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "python/2.7.13/lib/python2.7/tarfile.py", line 2202, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "python/2.7.13/lib/python2.7/tarfile.py", line 2286, in makelink
    os.link(tarinfo._link_target, targetpath)
OSError: [Errno 2] No such file or directory
```


And with Python 3.6.0 (and earlier Python 3 series based Pythons that I have tested):

```sh
$ time python3.6.0 tartest.py noskip tardata.tar.gz /tmp/tardata-python-3.6.0
...
tardata/1/2/3/4/5/6/7/8/9/zeros.data <-- this is extracted 11 times
...
real    0m42.747s
user    0m17.564s
sys     0m6.144s
```


If we then make the tarfile skip extraction of hard links that point to themselves:

```sh
$ time python3.6.0 tartest.py skip tardata.tar.gz /tmp/tardata-python-3.6.0
...
tardata/1/2/3/4/5/6/7/8/9/zeros.data <-- this is extracted once
...
Skipping tardata/1/2/3/4/5/6/7/8/9/zeros.data <-- skipped hard links 10 times
...
real    0m2.688s
user    0m1.816s
sys     0m0.532s
```


From the used user CPU time it's obvious that there is happening a lot of unneeded decompression when we compare Python 3.6 results. If I use TarFile.extractall(), it behaves similarly as using TarFile.extract() individually on TarInfo objects. GNU tar seems to behave in such fashion that it skips over the extraction of the actual file data when it encounters this situation.

**Comment by dff66fbe-9795-4708-85c5-19bd22fd0f69** [comment]
I have the same issue on Python 2.7.12 (Ubuntu 16.04)

I tried to execute tartest.py. But I could not find a way how to create the tar which is needed for tartest.py.
