### ISSUE TITLE
unittest.TestCase.assertWarns raises RuntimeEror if sys.modules changes size

### ISSUE THREAD

**Issue by 4c5a66fc-a623-4629-abbc-fd3d448e9ebf** [python/cpython#73806]
BPO | [29620](https://bugs.python.org/issue29620)
--- | :---
Nosy | @akuchling, @ambv, @serhiy-storchaka, @wkschwartz, @kernc, @miss-islington
PRs | <li>python/cpython#4800</li><li>python/cpython#20816</li><li>python/cpython#20817</li><li>python/cpython#29605</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-06-11.18:36:06.899>
created_at = <Date 2017-02-22.16:22:51.894>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = 'unittest.TestCase.assertWarns raises RuntimeEror if sys.modules changes size'
updated_at = <Date 2021-11-18.16:09:52.825>
user = 'https://github.com/kernc'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-18.16:09:52.825>
actor = 'lukasz.langa'
assignee = 'none'
closed = True
closed_date = <Date 2020-06-11.18:36:06.899>
closer = 'akuchling'
components = ['Library (Lib)']
creation = <Date 2017-02-22.16:22:51.894>
creator = 'kernc'
dependencies = []
files = []
hgrepos = []
issue_num = 29620
keywords = ['patch']
message_count = 9.0
messages = ['288370', '323821', '356671', '361886', '371315', '371317', '371318', '371319', '406547']
nosy_count = 8.0
nosy_names = ['akuchling', 'lukasz.langa', 'serhiy.storchaka', 'William.Schwartz', 'kernc', 'miss-islington', 'Arthit Suriyawongkul', 'Maximilian Peters']
pr_nums = ['4800', '20816', '20817', '29605']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29620'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 4c5a66fc-a623-4629-abbc-fd3d448e9ebf** [comment]
If any of the objects in sys.modules is a module-like object that performs some additional imports in its \_\_getattribute__ (as appropriate) handler, the following simple unit test test case:

```py
    import unittest
    import warnings
```


    ... # Ensure one of the imported modules is a module-like object as above

```py
    class Case(unittest.TestCase):
        def test_assertWarns(self):
            with self.assertWarns(UserWarning):
                warnings.warn('Some warning')
```


fails with:

    \======================================================================
    ERROR: test_assertWarns (example.Case)
    \----------------------------------------------------------------------
```pytb
    Traceback (most recent call last):
      File "/tmp/example.py", line 9, in test_assertWarns
        with self.assertWarns(UserWarning):
      File "/usr/lib/python3.4/unittest/case.py", line 205, in __enter__
        for v in sys.modules.values():
    RuntimeError: dictionary changed size during iteration
    
```
----------------------------------------------------------------------

The problem is in the iteration over sys.modules in unittest.case.\_AssertWarnsContext.\_\_enter__() and accessing every module's \_\_warningregistry__ attribute. On this access, the module-like objects may perform arbitrary actions including importing of further modules which extends sys.modules.

https://github.com/python/cpython/blob/16ea19fc6653ee4ec1be7cd0206073962119ac08/Lib/unittest/case.py#L226-L227

The simple proposed fix with no foreseen side-effects is to wrap sys.modules.values() call as a tuple().
