### ISSUE TITLE
Making a Tuple or Dict with Callable[ ..., xxx ] gives error

### ISSUE THREAD

**Issue by 37b1100f-f179-4c66-a59c-347fb34dba0d** [python/cpython#73804]
BPO | [29618](https://bugs.python.org/issue29618)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-22.08:51:45.322>
created_at = <Date 2017-02-22.08:14:04.175>
labels = ['type-bug', 'library']
title = 'Making a Tuple or Dict with Callable[ ..., xxx\xc2\xa0] gives error'
updated_at = <Date 2017-02-22.08:51:45.320>
user = 'https://bugs.python.org/PauliSalmenrinne'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-22.08:51:45.320>
actor = 'Pauli Salmenrinne'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-22.08:51:45.322>
closer = 'Pauli Salmenrinne'
components = ['Library (Lib)']
creation = <Date 2017-02-22.08:14:04.175>
creator = 'Pauli Salmenrinne'
dependencies = []
files = []
hgrepos = []
issue_num = 29618
keywords = []
message_count = 2.0
messages = ['288343', '288345']
nosy_count = 1.0
nosy_names = ['Pauli Salmenrinne']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29618'
versions = ['Python 3.5']
```

</p></details>

**Comment by 37b1100f-f179-4c66-a59c-347fb34dba0d** [comment]
Hi all. 

I tried asking this on IRC channel, but ended up with no answear. Simple example:

```py
from typing import Dict, Callable
CmdFun    = Callable[ ... , int ]
CmdFull   = Dict[ str, CmdFun ]
```


```pytb
Gives error:
pauli@HPauli-U1604 ~ % python3 /tmp/silly.py
Traceback (most recent call last):
  File "/tmp/silly.py", line 5, in <module>
    CmdFull   = Dict[ str, CmdFun ]
  File "/usr/lib/python3.5/typing.py", line 1025, in __getitem__
    tvars = _type_vars(params)
  File "/usr/lib/python3.5/typing.py", line 284, in _type_vars
    _get_type_vars(types, tvars)
  File "/usr/lib/python3.5/typing.py", line 279, in _get_type_vars
    t._get_type_vars(tvars)
  File "/usr/lib/python3.5/typing.py", line 786, in _get_type_vars
    _get_type_vars(self.__args__, tvars)
  File "/usr/lib/python3.5/typing.py", line 277, in _get_type_vars
    for t in types:
TypeError: 'ellipsis' object is not iterable
```



The python intrepretter is the one shipped with ubuntu16.04 currently: Python 3.5.2

Based on the documentation i think this should be valid statement. The similar issue raises if the Dict is replaced with Tuple, but i did not try any other combinations.

**Comment by 37b1100f-f179-4c66-a59c-347fb34dba0d** [comment]
I tried to reproduce the issue with 3.5 branch from the current github, and the issue seems to be fixed.

Closing this as fixed, sorry for the trouble.
