### ISSUE TITLE
ast.get_docstring(): AttributeError: 'NoneType' object has no attribute 'expandtabs'

### ISSUE THREAD

**Issue by ec31e85c-a35c-494f-805f-21a63c135c1b** [python/cpython#73823]
BPO | [29637](https://bugs.python.org/issue29637)
--- | :---
Nosy | @jwilk, @methane, @Carreau
PRs | <li>python/cpython#267</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-25.17:52:34.186>
created_at = <Date 2017-02-23.21:50:11.498>
labels = ['type-bug', '3.7']
title = "ast.get_docstring(): AttributeError: 'NoneType' object has no attribute 'expandtabs'"
updated_at = <Date 2017-03-24.23:49:05.018>
user = 'https://github.com/jwilk'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.23:49:05.018>
actor = 'methane'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-25.17:52:34.186>
closer = 'methane'
components = []
creation = <Date 2017-02-23.21:50:11.498>
creator = 'jwilk'
dependencies = []
files = []
hgrepos = []
issue_num = 29637
keywords = []
message_count = 2.0
messages = ['288488', '290414']
nosy_count = 3.0
nosy_names = ['jwilk', 'methane', 'mbussonn']
pr_nums = ['267']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29637'
versions = ['Python 3.7']
```

</p></details>

**Comment by ec31e85c-a35c-494f-805f-21a63c135c1b** [comment]
With git master (4c78c527d215c37472145152cb0e95f196cdddc9) I get this:

```pycon
>>> import ast
>>> ast.get_docstring(ast.parse(''))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jwilk/opt/lib/python3.7/ast.py", line 203, in get_docstring
    text = inspect.cleandoc(text)
  File "/home/jwilk/opt/lib/python3.7/inspect.py", line 590, in cleandoc
    lines = doc.expandtabs().split('\n')
AttributeError: 'NoneType' object has no attribute 'expandtabs'
```

**Comment by methane** [comment]
New changeset 41cea70aa38de50c1d714209aa2b7694d86a7e0c by INADA Naoki (Matthias Bussonnier) in branch 'master':
bpo-29637: clean docstring only if not None (GH-267)
https://github.com/python/cpython/commit/41cea70aa38de50c1d714209aa2b7694d86a7e0c
