### ISSUE TITLE
errors raised by bytes() and bytearray() for invalid size argument

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#74027]
BPO | [29841](https://bugs.python.org/issue29841)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @orenmn

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-03-17.20:33:15.921>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'errors raised by bytes() and bytearray() for invalid size argument'
updated_at = <Date 2017-03-24.20:47:05.648>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.20:47:05.648>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2017-03-17.20:33:15.921>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 29841
keywords = []
message_count = 2.0
messages = ['289783', '289785']
nosy_count = 3.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'Oren Milman']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29841'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
```pycon
currently (on my Windows 10):
>>> bytes(-1 << 1000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot fit 'int' into an index-sized integer
>>> bytes(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: negative count
>>> bytes(sys.maxsize + 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot fit 'int' into an index-sized integer
```


for the same size arguments, bytearray raises the same errors.

thus, in accordance with bpo-29833 (this is a sub-issue of bpo-29833) for each of the
constructors of bytes and bytearray:
    1. ValueErrors with the same error message should be raised for any
       negative size argument (big negative as well as small negative).
    2. MemoryError should be raised for any size argument bigger than
       sys.maxsize.


```pycon
Moreover, currently:
>>> bytes(sys.maxsize - 25)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
>>> bytes(sys.maxsize - 24)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: byte string is too large
>>> bytes(sys.maxsize)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: byte string is too large
```


for each of these size arguments, bytearray raises a MemoryError.

IMHO, to make the error messages more consistent, the constructor of bytes
should raise a MemoryError for any too large size argument, as the constructor
of bytearray already does.

**Comment by serhiy-storchaka** [comment]
I worked on this issue. The simplest solution is calling PyNumber_AsSsize_t() with NULL rather than PyExc_OverflowError in bytes and bytearray constructors. Then both constructors will raise ValueError for large negative size and bytearray() will raise MemoryError for large positive size. For raising MemoryError in bytes() we should change OverflowError to MemoryError in other place.

But this is not the only difference between bytes and bytearray.

```pycon
>>> bytearray(b'abcd') * sys.maxsize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
>>> b'abcd' * sys.maxsize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: repeated bytes are too long
```


This looks related and I think that it is worth to change OverflowError to MemoryError in the repetition operation. But 'abcd' * sys.maxsize raises OverflowError too, therefore we should change exception types in str.

Concatenation also can raise OverflowError. If change OverflowError to MemoryError in above operations, it should be changed for concatenation too.
