### ISSUE TITLE
compileall hangs when accessing urandom even if number of workers is 1

### ISSUE THREAD

**Issue by a7ef1cfb-00d5-4c81-bd7b-531841219500** [python/cpython#74063]
BPO | [29877](https://bugs.python.org/issue29877)
--- | :---
Nosy | @brettcannon, @pitrou, @vstinner, @tiran, @methane, @PCManticore, @virtuald, @miss-islington
PRs | <li>python/cpython#4856</li><li>python/cpython#10686</li><li>python/cpython#10687</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-11-24.01:37:57.669>
created_at = <Date 2017-03-22.05:57:16.434>
labels = ['3.7', 'library', 'performance']
title = 'compileall hangs when accessing urandom even if number of workers is 1'
updated_at = <Date 2018-11-24.01:37:57.668>
user = 'https://github.com/virtuald'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-24.01:37:57.668>
actor = 'methane'
assignee = 'none'
closed = True
closed_date = <Date 2018-11-24.01:37:57.669>
closer = 'methane'
components = ['Library (Lib)']
creation = <Date 2017-03-22.05:57:16.434>
creator = 'virtuald'
dependencies = []
files = []
hgrepos = []
issue_num = 29877
keywords = ['patch']
message_count = 11.0
messages = ['289973', '308649', '308651', '308654', '308655', '308688', '308927', '330290', '330342', '330345', '330346']
nosy_count = 8.0
nosy_names = ['brett.cannon', 'pitrou', 'vstinner', 'christian.heimes', 'methane', 'Claudiu.Popa', 'virtuald', 'miss-islington']
pr_nums = ['4856', '10686', '10687']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue29877'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a7ef1cfb-00d5-4c81-bd7b-531841219500** [comment]
Found on Python 3.6 on a low-resource platform (NI RoboRIO), it seems that this occurs only because the ProcessPoolExecutor is being imported. A proposed fix would only import ProcessPoolExecutor if -j \> 1. Stacktrace follows:

```pytb
 /usr/local/bin/python3 -m compileall -j 1 /home/lvuser/py
^CTraceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "/usr/local/lib/python3.6/concurrent/futures/__init__.py", line 17, in <module>
    from concurrent.futures.process import ProcessPoolExecutor
  File "/usr/local/lib/python3.6/concurrent/futures/process.py", line 53, in <module>
    import multiprocessing
  File "/usr/local/lib/python3.6/multiprocessing/__init__.py", line 16, in <module>
    from . import context
  File "/usr/local/lib/python3.6/multiprocessing/context.py", line 5, in <module>
    from . import process
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 311, in <module>
    _current_process = _MainProcess()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 298, in __init__
    self._config = {'authkey': AuthenticationString(os.urandom(32)),
```
