### ISSUE TITLE
decode string:u"\ufffd" UnicodeEncodeError

### ISSUE THREAD

**Issue by 3883a5bd-3b4b-4ea8-9050-aee0554a9d45** [python/cpython#74131]
BPO | [29945](https://bugs.python.org/issue29945)
--- | :---
Nosy | @vstinner, @ezio-melotti, @eryksun, @bts_webber
Files | <li>[windows.jpg](https://bugs.python.org/file46767/windows.jpg "Uploaded as image/jpeg at 2017-03-30.08:17:40 by @bts_webber")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-30.11:06:04.993>
created_at = <Date 2017-03-30.08:15:37.937>
labels = ['invalid', 'expert-unicode']
title = 'decode string:u"\\ufffd" UnicodeEncodeError'
updated_at = <Date 2017-03-30.11:06:04.991>
user = 'https://github.com/btswebber'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-30.11:06:04.991>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-30.11:06:04.993>
closer = 'eryksun'
components = ['Unicode']
creation = <Date 2017-03-30.08:15:37.937>
creator = 'foxscheduler'
dependencies = []
files = ['46767']
hgrepos = []
issue_num = 29945
keywords = []
message_count = 3.0
messages = ['290834', '290835', '290839']
nosy_count = 4.0
nosy_names = ['vstinner', 'ezio.melotti', 'eryksun', 'foxscheduler']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29945'
versions = ['Python 2.7']
```

</p></details>

**Comment by 3883a5bd-3b4b-4ea8-9050-aee0554a9d45** [comment]
I use  python on linux, version is 2.7.13:

```pycon
[root@localhost bin]# ./python2.7
Python 2.7.13 (default, Mar 30 2017, 00:54:08) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> a=u"\ufffd"
>>> a.decode("utf=8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python2.7.13/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 0: ordinal not in range(128)
```


but,windows version run success!

**Comment by vstinner** [comment]
Decoding Unicode doesn't make any sense. You should take a look at http://unicodebook.readthedocs.io/ to understand what you are doing :-)

(On Python 3, Unicode strings, the str type, has no mode .decode() type.)

I suggest to close the issue has NOT A BUG.

**Comment by eryksun** [comment]
> windows version run success!

Trying to decode a non-ASCII unicode string should raise an exception on any platform:

```pycon
    Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40)
    [MSC v.1500 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> a=u"\ufffd"
    >>> a.decode("utf=8")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Program Files\Python27\lib\encodings\utf_8.py",
      line 16, in decode
        return codecs.utf_8_decode(input, errors, True)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd'
    in position 0: ordinal not in range(128)
```


Unless you've modified the default encoding to something other than ASCII. For example:

```pycon
    Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40)
    [MSC v.1500 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import sys, inspect, sitecustomize
    >>> print inspect.getsource(sitecustomize)
    import sys
    sys.setdefaultencoding('utf-8')

    >>> sys.getdefaultencoding()
    'utf-8'
    >>> a=u"\ufffd"
    >>> a.decode("utf=8")
    u'\ufffd'
```
