### ISSUE TITLE
Pickling and copying exceptions doesn't preserve non-__dict__ attributes

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74191]
BPO | [30005](https://bugs.python.org/issue30005)
--- | :---
Nosy | @avassalotti, @serhiy-storchaka, @iritkatriel
Dependencies | <li>bpo-29998: Pickling and copying ImportError doesn&#x27;t preserve name and path</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-04-06.05:59:35.082>
labels = ['interpreter-core', 'type-bug', '3.11']
title = "Pickling and copying exceptions doesn't preserve non-__dict__ attributes"
updated_at = <Date 2021-06-27.21:37:57.332>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-27.21:37:57.332>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2017-04-06.05:59:35.082>
creator = 'serhiy.storchaka'
dependencies = ['29998']
files = []
hgrepos = []
issue_num = 30005
keywords = []
message_count = 2.0
messages = ['291212', '396602']
nosy_count = 3.0
nosy_names = ['alexandre.vassalotti', 'serhiy.storchaka', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30005'
versions = ['Python 3.11']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Pickling and copying exceptions preserves only \_\_dict__ attributes.

This includes writeable internal fields initialized in constructor:

```pycon
>>> import pickle, copy
>>> e = StopIteration(12)
>>> e.value = 34
>>> e.value
34
>>> e2 = pickle.loads(pickle.dumps(e, 4))
>>> e2.value
12
>>> e2 = copy.copy(e)
>>> e2.value
12
```


And \_\_slots__:

```pycon
>>> class E(Exception): __slots__ = ('x', 'y')
... 
>>> e = E()
>>> e.x = 12
>>> e.x
12
>>> e2 = pickle.loads(pickle.dumps(e, 4))
>>> e2.x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: x
>>> e2 = copy.copy(e)
>>> e2.x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: x
```


\_\_context__, \_\_cause__ and \_\_traceback__ are lost too (see bpo-29466).

bpo-26579 is similar, but resolving it will not resolve this issue since BaseException has its own \_\_reduce__ and \_\_setstate__ implementations.

The solution of this issue will look similar to bpo-29998, but more complex and general.
