### ISSUE TITLE
missing iter(self) in _io._IOBase.readlines

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#74254]
BPO | [30068](https://bugs.python.org/issue30068)
--- | :---
Nosy | @benjaminp, @serhiy-storchaka, @zhangyangyu
PRs | <li>python/cpython#1130</li><li>python/cpython#1150</li><li>python/cpython#1151</li><li>python/cpython#1152</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-15.05:28:43.133>
created_at = <Date 2017-04-14.06:45:23.916>
labels = ['type-bug', '3.7', 'expert-IO']
title = 'missing iter(self) in _io._IOBase.readlines'
updated_at = <Date 2017-04-15.05:28:43.132>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-15.05:28:43.132>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-15.05:28:43.133>
closer = 'xiang.zhang'
components = ['IO']
creation = <Date 2017-04-14.06:45:23.916>
creator = 'xiang.zhang'
dependencies = []
files = []
hgrepos = []
issue_num = 30068
keywords = []
message_count = 5.0
messages = ['291641', '291699', '291701', '291702', '291703']
nosy_count = 4.0
nosy_names = ['benjamin.peterson', 'stutzbach', 'serhiy.storchaka', 'xiang.zhang']
pr_nums = ['1130', '1150', '1151', '1152']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30068'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by zhangyangyu** [comment]
In \_io.\_IOBase.readlines, it straightly uses PyIter_Next(self). But iter(_io.\_IOBase) does more work than just returning itself.

```pycon
>>> import _io
>>> f = _io._IOBase()
>>> f.close()
>>> f.readlines()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: I/O operation on closed file.
>>> f.readlines(10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_io._IOBase' object has no attribute 'read'
```

**Comment by zhangyangyu** [comment]
New changeset 026435ce49419a3366171416c68114dd8a1144c7 by Xiang Zhang in branch 'master':
bpo-30068: add missing iter(self) in \_io.\_IOBase.readlines when hint is present (bpo-1130)
https://github.com/python/cpython/commit/026435ce49419a3366171416c68114dd8a1144c7

**Comment by zhangyangyu** [comment]
New changeset 5fbdfc36f397ad46f4057d527855dfacb77242ce by Xiang Zhang in branch '2.7':
bpo-30068: add missing iter(self) in \_io.\_IOBase.readlines when hint is present (bpo-1152)
https://github.com/python/cpython/commit/5fbdfc36f397ad46f4057d527855dfacb77242ce

**Comment by zhangyangyu** [comment]
New changeset d5fa5f3ce7d9003bbd3975d1bf634043305ae18f by Xiang Zhang in branch '3.6':
bpo-30068: add missing iter(self) in \_io.\_IOBase.readlines when hint is present (bpo-1130) (bpo-1150)
https://github.com/python/cpython/commit/d5fa5f3ce7d9003bbd3975d1bf634043305ae18f

**Comment by zhangyangyu** [comment]
New changeset 4f43f87b6246e13e0eefc793a2c5415c915723c3 by Xiang Zhang in branch '3.5':
bpo-30068: add missing iter(self) in \_io.\_IOBase.readlines when hint is present (bpo-1130) (bpo-1151)
https://github.com/python/cpython/commit/4f43f87b6246e13e0eefc793a2c5415c915723c3
