### ISSUE TITLE
WeakSet should allow discard and remove on items that can't have weak references

### ISSUE THREAD

**Issue by 4665e6b7-82b0-4d2a-8e17-c4eb15ac0525** [python/cpython#74286]
BPO | [30100](https://bugs.python.org/issue30100)
--- | :---
Nosy | @freddrake, @rhettinger, @pitrou, @serhiy-storchaka, @donkopotamus
PRs | <li>python/cpython#1176</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-04-19.05:20:30.848>
labels = ['3.8', 'type-feature', 'library']
title = "WeakSet should allow discard and remove on items that can't have weak references"
updated_at = <Date 2018-03-27.03:24:05.729>
user = 'https://github.com/donkopotamus'
```

bugs.python.org fields:
```python
activity = <Date 2018-03-27.03:24:05.729>
actor = 'rhettinger'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-04-19.05:20:30.848>
creator = 'donkopotamus'
dependencies = []
files = []
hgrepos = []
issue_num = 30100
keywords = []
message_count = 7.0
messages = ['291861', '291867', '291868', '291878', '291880', '291918', '314495']
nosy_count = 6.0
nosy_names = ['fdrake', 'rhettinger', 'pitrou', 'stutzbach', 'serhiy.storchaka', 'donkopotamus']
pr_nums = ['1176']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30100'
versions = ['Python 3.8']
```

</p></details>

**Comment by 4665e6b7-82b0-4d2a-8e17-c4eb15ac0525** [comment]
Currently WeakSet().discard([]) will raise a TypeError as we cannot take a weak reference to a list.

However, that means a list can never be in a WeakSet, so WeakSet().discard([]) could instead be a no-op.  Similarly WeakSet().remove([]) could be a KeyError.

**Comment by serhiy-storchaka** [comment]
What about difference_update(), issubset(), issuperset(), \_\_eq__()?

Raising TypeError looks reasonable to me. Operations with ordinal sets can raise TypeError for unhashable values.

```pycon
>>> [] in set()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
>>> set().remove([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
>>> set().discard([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```


Unlike to set.\_\_contains__ WeakSet.\_\_contains__ returns False for unsupported types:

```pycon
>>> [] in weakref.WeakSet()
False
```


Shouldn't set.\_\_contains__ be changed to return False for unhashable values? Or may be make WeakSet.\_\_contains__ raising TypeError for values that can't have weak references?

**Comment by serhiy-storchaka** [comment]
dict.pop() supports unhashable values, but dict.\_\_contains__() and dict.get() don't:

```pycon
>>> [] in {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
>>> {}.get([], 42)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
>>> {}.pop([], 42)
42
```


OrderedDict.pop() also doesn't support unhashable values:

```pycon
>>> collections.OrderedDict().pop([], 42)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```

**Comment by rhettinger** [comment]
> Raising TypeError looks reasonable to me. 
> Operations with ordinal sets can raise TypeError 
> for unhashable values.

I agree.  TypeError looks the right exception in this case.

**Comment by serhiy-storchaka** [comment]
The argument for not raising TypeError for unsupported types:

This is just from the definition of a set. If the set can't contain the value of specific type, then checking if this value is contained in the set should return False, and discarding it from the set should be no-op.

The argument for raising TypeError for unsupported types:

Using a value of unsuitable type is likely a programming error. Silencing TypeError can hide an error. Since raising and catching an exception is costly (but it is cheaper in C than in Python), this also can lead to performance degradation which is hard to catch.

If the first argument is stronger then the second argument then we should change a number of set, dict, dict views and OrderedDict methods and make them returning a reasonable result rather than raising TypeError.

If the second argument is stronger then the first argument then we should change just WeakSet.\_\_contains__() and dict.pop(). Since this is a behavior change that can break third-party code they should first emit deprecation warnings for one or two releases.

**Comment by 4665e6b7-82b0-4d2a-8e17-c4eb15ac0525** [comment]
Just to add, I framed this slightly wrongly by using a list [] as an example, whereas my original motivating case was objects that are hashable but not weakly referenceable.   (eg () ).

So there are two cases to consider ... what to do in discard/remove etc when the value is (i) not weakly referenceable, and (ii) when the value is not hashable.
