### ISSUE TITLE
Command-line option to suppress "from None" for debugging

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#74283]
BPO | [30097](https://bugs.python.org/issue30097)
--- | :---
Nosy | @rhettinger, @ncoghlan, @ethanfurman, @vadmium, @serhiy-storchaka, @wm75, @Mariatta

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-04-18.22:11:52.228>
labels = ['interpreter-core', 'type-bug', '3.8']
title = 'Command-line option to suppress "from None" for debugging'
updated_at = <Date 2020-02-29.23:13:57.364>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-29.23:13:57.364>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2017-04-18.22:11:52.228>
creator = 'rhettinger'
dependencies = []
files = []
hgrepos = []
issue_num = 30097
keywords = []
message_count = 6.0
messages = ['291844', '291857', '293185', '293466', '362476', '362485']
nosy_count = 7.0
nosy_names = ['rhettinger', 'ncoghlan', 'ethan.furman', 'martin.panter', 'serhiy.storchaka', 'wolma', 'Mariatta']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30097'
versions = ['Python 3.8']
```

</p></details>

**Comment by rhettinger** [comment]
Filing this feature request on behalf of an engineering team that I work with.

This team creates Python tools for use by other departments.  Accordingly, their best practice is to use "raise CleanException from None" to give the cleanest error messages to their users while hiding the noise of implementation details and internal logic.  The exposed exceptions are a documented, guaranteed part of the API that users can reliably catch and handle.  This has worked well for them; however, when they are debugging the library itself it would be nice to have a way to suppress all the "from None" code and see fuller stack traces that indicate root causes.

One way to do this would be to have a command-line switch such as "python -C testcode.py".   Where the "-C" option means "Always show the cause of exceptions even when 'from None' is present.

**Comment by serhiy-storchaka** [comment]
The initial exception still is linked as \_\_context__. You can write own implementation of traceback.print_exception() that ignores \_\_suppress_context__. Alternatively you can just set \_\_suppress_context__ to False.

**Comment by vadmium** [comment]
This proposal would be useful. My use case is for when an API suppresses an external exception context:

```pycon
>>> import os
>>> try:
...     os.environ["NEW_VARIABLE"] = bug  # Hidden exception
... finally:
...     del os.environ["NEW_VARIABLE"]  # KeyError
... 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/lib/python3.5/os.py", line 699, in __delitem__
    raise KeyError(key) from None
KeyError: 'NEW_VARIABLE'
```


This feels like a step backwards to Python 2, and enabling the full backtrace would make this easier to analyze:

```pycon
>>> try:
...     os.environ["NEW_VARIABLE"] = bug  # TypeError
... finally:
...     del dict()["NEW_VARIABLE"]  # KeyError
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.5/os.py", line 688, in __setitem__
    value = self.encodevalue(value)
  File "/usr/lib/python3.5/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
KeyError: 'NEW_VARIABLE'
```

**Comment by vstinner** [comment]
See also my old PEP-490 -- Chain exceptions at C level, more or less abandonned :-p
