### ISSUE TITLE
python.core file created when running tests on AMD64 FreeBSD CURRENT Non-Debug 3.x buildbot

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74293]
BPO | [30107](https://bugs.python.org/issue30107)
--- | :---
Nosy | @vstinner, @koobs
PRs | <li>python/cpython#1235</li><li>python/cpython#1241</li><li>python/cpython#1279</li><li>python/cpython#1335</li><li>python/cpython#1344</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-02.22:45:38.390>
created_at = <Date 2017-04-19.23:22:57.543>
labels = ['3.7', 'tests']
title = 'python.core file created when running tests on AMD64 FreeBSD CURRENT Non-Debug 3.x buildbot'
updated_at = <Date 2017-05-02.22:45:38.388>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-02.22:45:38.388>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-02.22:45:38.390>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-04-19.23:22:57.543>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30107
keywords = []
message_count = 9.0
messages = ['291921', '292056', '292061', '292246', '292283', '292303', '292496', '292534', '292820']
nosy_count = 2.0
nosy_names = ['vstinner', 'koobs']
pr_nums = ['1235', '1241', '1279', '1335', '1344']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30107'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Example of buildbot build which created a python.core file.

Tests crashing Python on purpose should use test.support.SuppressCrashReport. I don't see which test can crash in the following list.

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Non-Debug%203.x/builds/175/steps/test/logs/stdio

0:04:54 [132/404/6] test_raise passed -- running: test_subprocess (61 sec)
0:04:54 [133/404/6] test_dict passed -- running: test_subprocess (62 sec)
0:04:54 [134/404/6] test_telnetlib passed -- running: test_subprocess (62 sec)
0:04:55 [135/404/6] test_robotparser passed -- running: test_subprocess (63 sec)
0:04:56 [136/404/6] test_py_compile passed -- running: test_subprocess (64 sec)
0:04:56 [137/404/6] test_listcomps passed -- running: test_subprocess (64 sec)
0:04:56 [138/404/6] test_pty passed -- running: test_subprocess (64 sec)
0:04:56 [139/404/6] test_defaultdict passed -- running: test_subprocess (64 sec)
running: test_io (30 sec), test_subprocess (94 sec)
0:05:27 [140/404/6] test_subprocess passed (94 sec) -- running: test_io (31 sec)
0:05:27 [141/404/6] test_unpack passed -- running: test_io (31 sec)
0:05:28 [142/404/6] test_bytes passed -- running: test_io (33 sec)
0:05:29 [143/404/6] test_weakset passed -- running: test_io (33 sec)
0:05:36 [144/404/6] test_eintr passed -- running: test_io (40 sec)
0:05:37 [145/404/6] test_userstring passed -- running: test_io (41 sec)
0:05:37 [146/404/6] test_support passed -- running: test_io (41 sec)
0:05:37 [147/404/6] test_ioctl skipped -- running: test_io (42 sec)
test_ioctl skipped -- Unable to open /dev/tty
0:05:40 [148/404/6] test_cmd_line passed -- running: test_io (44 sec)
0:05:41 [149/404/6] test_turtle skipped -- running: test_io (45 sec)
test_turtle skipped -- No module named '\_tkinter'
0:05:41 [150/404/6] test_subclassinit passed -- running: test_io (45 sec)
0:05:42 [151/404/6] test_set passed -- running: test_io (46 sec)
0:05:43 [152/404/6] test_xml_etree_c passed -- running: test_io (47 sec)
0:05:43 [153/404/6] test_binascii passed -- running: test_io (47 sec)
0:05:48 [154/404/6] test_normalization passed -- running: test_io (52 sec)
fetching http://www.pythontest.net/unicode/9.0.0/NormalizationTest.txt ...
0:05:49 [155/404/6] test_os passed -- running: test_io (54 sec)
stty: stdin isn't a terminal
0:05:50 [156/404/6] test_abc passed -- running: test_io (54 sec)
0:05:50 [157/404/6] test_dummy_threading passed -- running: test_io (54 sec)
0:05:50 [158/404/6] test_pkgutil passed -- running: test_io (54 sec)
0:05:50 [159/404/6] test_compile passed -- running: test_io (55 sec)
0:05:51 [160/404/6] test_largefile passed -- running: test_io (55 sec)
0:05:54 [161/404/6] test_io failed (env changed) (57 sec)
test_BufferedIOBase_destructor (test.test_io.CIOTest) ... ok
...
test_interrupted_write_unbuffered (test.test_io.PySignalsTest) ... ok
\----------------------------------------------------------------------
Ran 565 tests in 57.439s

OK (skipped=2)
Warning -- files was modified by test_io
  Before: []
  After:  ['python.core']

**Comment by vstinner** [comment]
New changeset 2a1aed04b0943636f605543522e16cca1dc23e70 by Victor Stinner in branch 'master':
bpo-30107: don't dump core on expected test_io crash (bpo-1235)
https://github.com/python/cpython/commit/2a1aed04b0943636f605543522e16cca1dc23e70

**Comment by vstinner** [comment]
New changeset b984a05d557e78b928f38098d0b6c0e95f737b9a by Victor Stinner in branch '3.6':
bpo-30107: don't dump core on expected test_io crash (bpo-1235) (bpo-1241)
https://github.com/python/cpython/commit/b984a05d557e78b928f38098d0b6c0e95f737b9a

**Comment by vstinner** [comment]
The commit 2a1aed04b0943636f605543522e16cca1dc23e70 introduced a regression on macOS. The PR https://github.com/python/cpython/pull/1279 should fix it.

http://buildbot.python.org/all/builders/x86-64%20El%20Capitan%203.x/builds/87/steps/test/logs/stdio

\======================================================================
FAIL: test_daemon_threads_shutdown_stderr_deadlock (test.test_io.CMiscIOTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/test_io.py", line 3772, in test_daemon_threads_shutdown_stderr_deadlock
    self.check_daemon_threads_shutdown_deadlock('stderr')
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/test_io.py", line 3766, in check_daemon_threads_shutdown_deadlock
    self.assertFalse(err.strip('.!'))
AssertionError: '2017-04-24 16:57:21.432 defaults[41046:2462851] \nThe domain/default pair of (com.apple.CrashReporter, DialogType) does not exist\n' is not false
```

**Comment by vstinner** [comment]
New changeset d819ad9832292d854e9710493ecdf959b69802e3 by Victor Stinner in branch 'master':
bpo-30107: Make SuppressCrashReport quiet on macOS (bpo-1279)
https://github.com/python/cpython/commit/d819ad9832292d854e9710493ecdf959b69802e3

**Comment by vstinner** [comment]
I'm waiting for buildbots to check if the issue is really fixed.

**Comment by vstinner** [comment]
New changeset c9ca57eeea4d9da748d84281506c5803512b79ac by Victor Stinner in branch '3.6':
bpo-30107: Make SuppressCrashReport quiet on macOS (bpo-1279) (bpo-1335)
https://github.com/python/cpython/commit/c9ca57eeea4d9da748d84281506c5803512b79ac

**Comment by vstinner** [comment]
New changeset 98c7a9e662b49029ff051b6699ddc0f542663c96 by Victor Stinner in branch '3.5':
[3.5] bpo-30107: don't dump core on expected test_io crash (bpo-1235) (bpo-1344)
https://github.com/python/cpython/commit/98c7a9e662b49029ff051b6699ddc0f542663c96

**Comment by vstinner** [comment]
Oh, I forgot that issue. I'm now happy to be able to close it ;-) The bug was fixed!
