### ISSUE TITLE
test_asyncore: test_handle_write() fails in tearDown()

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74292]
BPO | [30106](https://bugs.python.org/issue30106)
--- | :---
Nosy | @vstinner
PRs | <li>python/cpython#1194</li><li>python/cpython#1234</li><li>python/cpython#1336</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-02.22:46:23.971>
created_at = <Date 2017-04-19.22:54:22.249>
labels = ['3.7', 'tests']
title = 'test_asyncore: test_handle_write() fails in tearDown()'
updated_at = <Date 2017-07-04.14:52:46.215>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-04.14:52:46.215>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-02.22:46:23.971>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-04-19.22:54:22.249>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30106
keywords = []
message_count = 9.0
messages = ['291920', '291927', '291930', '291931', '291933', '292026', '292027', '292503', '297663']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = ['1194', '1234', '1336']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30106'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
On the AMD64 FreeBSD CURRENT Non-Debug 3.x buildbot, test_handle_write() of test_asyncore now fails on calling asyncore.close_all() in tearDown().

Moreover, since my commit 7b9619ae249ed637924d1c76687b411061753e5a, the following test_quick_connect() now fails on self.fail("join() timed out"). I guess that asyncore.socket_map still contains unwanted sockets from test_handle_write() which failed.

Attached PR should fix the test_handle_write() failure by calling asyncore.close_all() with ignore_all=True.

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Non-Debug%203.x/builds/174/steps/test/logs/stdio

\======================================================================
ERROR: test_handle_write (test.test_asyncore.TestAPI_UseIPv6Poll)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current.nondebug/build/Lib/test/test_asyncore.py", line 505, in tearDown
    asyncore.close_all()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current.nondebug/build/Lib/asyncore.py", line 561, in close_all
    x.close()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current.nondebug/build/Lib/asyncore.py", line 397, in close
    self.socket.close()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current.nondebug/build/Lib/socket.py", line 417, in close
    self._real_close()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current.nondebug/build/Lib/socket.py", line 411, in _real_close
    _ss.close(self)
ConnectionResetError: [Errno 54] Connection reset by peer
```


======================================================================
FAIL: test_quick_connect (test.test_asyncore.TestAPI_UseIPv6Poll)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current.nondebug/build/Lib/test/support/__init__.py", line 2042, in decorator
    return func(*args)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current.nondebug/build/Lib/test/test_asyncore.py", line 800, in test_quick_connect
    self.fail("join() timed out")
AssertionError: join() timed out
```

**Comment by vstinner** [comment]
New changeset 11470b6dcdbc170779499a4a040b93c842a0d194 by Victor Stinner in branch 'master':
bpo-30106: Fix tearDown() of test_asyncore (bpo-1194)
https://github.com/python/cpython/commit/11470b6dcdbc170779499a4a040b93c842a0d194

**Comment by vstinner** [comment]
It seems like the change 11470b6dcdbc170779499a4a040b93c842a0d194 fixed test_handle_write(), but test_quick_connect() fails on thread.join().

```pytb
test_quick_connect (test.test_asyncore.TestAPI_UseIPv4Poll) ... Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/test_asyncore.py", line 785, in <lambda>
    count=500))
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/asyncore.py", line 144, in poll
    r, w, e = select.select(r, w, e, timeout)
OSError: [Errno 9] Bad file descriptor
```


FAIL

```pytb
test_quick_connect (test.test_asyncore.TestAPI_UseIPv4Select) ... Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/test_asyncore.py", line 785, in <lambda>
    count=500))
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/asyncore.py", line 144, in poll
    r, w, e = select.select(r, w, e, timeout)
OSError: [Errno 9] Bad file descriptor
```


FAIL

\======================================================================
FAIL: test_quick_connect (test.test_asyncore.TestAPI_UseIPv4Poll)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/support/__init__.py", line 2042, in decorator
    return func(*args)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/test_asyncore.py", line 800, in test_quick_connect
    self.fail("join() timed out")
AssertionError: join() timed out
```


======================================================================
FAIL: test_quick_connect (test.test_asyncore.TestAPI_UseIPv4Select)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/support/__init__.py", line 2042, in decorator
    return func(*args)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/test_asyncore.py", line 800, in test_quick_connect
    self.fail("join() timed out")
AssertionError: join() timed out
```

**Comment by vstinner** [comment]
Since my change 7b9619ae249ed637924d1c76687b411061753e5a, test_asyncore now fails on the AMD64 FreeBSD CURRENT Debug 3.x buildbot, it wasn't the case before. First fail:
http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Debug%203.x/builds/174/

**Comment by vstinner** [comment]
I started to work on this issue because I noticed many "xxx modified by test_xxx" on the two FreeBSD CURRENT buildbots. Examples:

AMD64_FreeBSD_CURRENT_Debug_3.x/163:Warning -- threading.\_dangling was modified by test_logging

AMD64_FreeBSD_CURRENT_Debug_3.x/159:Warning -- asyncore.socket_map was modified by test_ssl

**Comment by vstinner** [comment]
> AssertionError: join() timed out

The following PR fixes this race condition which occurs on FreeBSD:
https://github.com/python/cpython/pull/1234 fixes

**Comment by vstinner** [comment]
New changeset a2c877c3985aba4adb19755e21f477e1c639cfd9 by Victor Stinner in branch 'master':
bpo-30106: Fix test_asyncore.test_quick_connect() (bpo-1234)
https://github.com/python/cpython/commit/a2c877c3985aba4adb19755e21f477e1c639cfd9

**Comment by vstinner** [comment]
New changeset caa59c156d1e6ff3d005e0112bb27c5bed4afb71 by Victor Stinner in branch '3.6':
[3.6] bpo-30106: Fix test_asyncore.test_quick_connect() (bpo-1336)
https://github.com/python/cpython/commit/caa59c156d1e6ff3d005e0112bb27c5bed4afb71

**Comment by vstinner** [comment]
File "/usr/home/buildbot/python/3.x.koobs-freebsd-current.nondebug/build/Lib/socket.py", line 411, in \_real_close
    \_ss.close(self)
ConnectionResetError: [Errno 54] Connection reset by peer


This bug was fixed by bpo-30319.
