### ISSUE TITLE
make reindent failed.

### ISSUE THREAD

**Issue by corona10** [python/cpython#74295]
BPO | [30109](https://bugs.python.org/issue30109)
--- | :---
Nosy | @serhiy-storchaka, @Mariatta, @csabella, @corona10
PRs | <li>python/cpython#1207</li><li>python/cpython#1208</li><li>python/cpython#1209</li><li>python/cpython#5637</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2018-02-12.18:17:44.154>
created_at = <Date 2017-04-20.03:17:36.584>
labels = ['type-bug', '3.7']
title = 'make reindent failed.'
updated_at = <Date 2018-02-12.18:17:44.153>
user = 'https://github.com/corona10'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-12.18:17:44.153>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2018-02-12.18:17:44.154>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-04-20.03:17:36.584>
creator = 'corona10'
dependencies = []
files = []
hgrepos = []
issue_num = 30109
keywords = ['patch']
message_count = 10.0
messages = ['291935', '291948', '291949', '291973', '291974', '311551', '311555', '312008', '312042', '312068']
nosy_count = 4.0
nosy_names = ['serhiy.storchaka', 'Mariatta', 'cheryl.sabella', 'corona10']
pr_nums = ['1207', '1208', '1209', '5637']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30109'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by corona10** [comment]
When I try to `make reindent`

It was failed with this messages.

````
./python.exe ./Tools/scripts/reindent.py -r ./Lib
Traceback (most recent call last):
  File "/Users/corona10/cpython/Lib/tokenize.py", line 404, in find_cookie
    codec = lookup(encoding)
LookupError: unknown encoding: uft-8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Tools/scripts/reindent.py", line 329, in <module>
    main()
  File "./Tools/scripts/reindent.py", line 101, in main
    check(arg)
  File "./Tools/scripts/reindent.py", line 115, in check
    check(fullname)
  File "./Tools/scripts/reindent.py", line 115, in check
    check(fullname)
  File "./Tools/scripts/reindent.py", line 121, in check
    encoding, _ = tokenize.detect_encoding(f.readline)
  File "/Users/corona10/cpython/Lib/tokenize.py", line 433, in detect_encoding
    encoding = find_cookie(first)
  File "/Users/corona10/cpython/Lib/tokenize.py", line 412, in find_cookie
    raise SyntaxError(msg)
SyntaxError: unknown encoding for './Lib/test/bad_coding.py': uft-8
make: *** [reindent] Error 1

```

**Comment by Mariatta** [comment]
New changeset 58f3c9dc8f5626abe09ac9738c34f6ba99ce2972 by Mariatta in branch 'master':
bpo-30109: Fix reindent.py (GH-1207)
https://github.com/python/cpython/commit/58f3c9dc8f5626abe09ac9738c34f6ba99ce2972

**Comment by serhiy-storchaka** [comment]
I don't know whether the fix for 2.7 is needed. The interface of tokenize is different in 2.7. Just run the new test and see if it fails.

**Comment by Mariatta** [comment]
New changeset 430020500c56259d31e07d32771f017952bad4e0 by Mariatta in branch '3.6':
[3.6] bpo-30109: Fix reindent.py (GH-1207) (GH-1208)
https://github.com/python/cpython/commit/430020500c56259d31e07d32771f017952bad4e0

**Comment by Mariatta** [comment]
New changeset 60d27f42a07d0b9d4a2c3fb160cac1683e91f196 by Mariatta in branch '3.5':
[3.5] bpo-30109: Fix reindent.py (GH-1207) (GH-1209)
https://github.com/python/cpython/commit/60d27f42a07d0b9d4a2c3fb160cac1683e91f196
