### ISSUE TITLE
test_venv failed without pip

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74309]
BPO | [30123](https://bugs.python.org/issue30123)
--- | :---
Nosy | @vsajip, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-21.06:51:08.373>
created_at = <Date 2017-04-21.06:01:20.328>
labels = ['type-bug', 'tests']
title = 'test_venv failed without pip'
updated_at = <Date 2017-04-21.06:51:08.372>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-21.06:51:08.372>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-21.06:51:08.373>
closer = 'serhiy.storchaka'
components = ['Tests']
creation = <Date 2017-04-21.06:01:20.328>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30123
keywords = []
message_count = 4.0
messages = ['292009', '292010', '292011', '292012']
nosy_count = 2.0
nosy_names = ['vinay.sajip', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30123'
versions = ['Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
```sh
$ ./python -m test.regrtest -vuall test_venv
...
```

======================================================================
FAIL: test_with_pip (test.test_venv.EnsurePipTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/serhiy/py/cpython3.5/Lib/test/test_venv.py", line 428, in test_with_pip
    self.do_test_with_pip(False)
  File "/home/serhiy/py/cpython3.5/Lib/test/test_venv.py", line 382, in do_test_with_pip
    self.assertEqual(err, "")
AssertionError: '/tmp/tmpxhgghyhm/bin/python: No module named pip\n' != ''
- /tmp/tmpxhgghyhm/bin/python: No module named pip
```


----------------------------------------------------------------------

**Comment by vsajip** [comment]
I can't reproduce this on the master branch, with the latest checkout. Was this the branch your failure occurred on?

```sh
$ ./python -m test.regrtest -vuall test_venv
== CPython 3.7.0a0 (heads/master:f60c9e5, Apr 21 2017, 07:19:01) [GCC 5.4.0 20160609]
==   Linux-4.4.0-72-generic-x86_64-with-debian-stretch-sid little-endian
==   hash algorithm: siphash24 64bit
==  cwd: /home/vinay/projects/python/master/build/test_python_4297
==  encodings: locale=UTF-8, FS=utf-8
Testing with flags: sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=0, no_site=0, ignore_environment=0, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=0)
Run tests sequentially
0:00:00 [1/1] test_venv
test_defaults (test.test_venv.BasicTest) ... ok
test_executable (test.test_venv.BasicTest) ... ok
test_executable_symlinks (test.test_venv.BasicTest) ... ok
test_isolation (test.test_venv.BasicTest) ... ok
test_overwrite_existing (test.test_venv.BasicTest) ... ok
test_prefixes (test.test_venv.BasicTest) ... ok
test_prompt (test.test_venv.BasicTest) ... ok
test_symlinking (test.test_venv.BasicTest) ... ok
test_unoverwritable_fails (test.test_venv.BasicTest) ... ok
test_upgrade (test.test_venv.BasicTest) ... ok
test_devnull (test.test_venv.EnsurePipTest) ... ok
test_explicit_no_pip (test.test_venv.EnsurePipTest) ... ok
test_no_pip_by_default (test.test_venv.EnsurePipTest) ... ok
test_with_pip (test.test_venv.EnsurePipTest) ... ok
```


----------------------------------------------------------------------
Ran 14 tests in 9.336s

OK
1 test OK.

**Comment by serhiy-storchaka** [comment]
Actually I tested on 3.5 and 3.6. I can't reproduce on master.

**Comment by serhiy-storchaka** [comment]
Hmm, seems this is local issue of my environment. I now use very small disk, and after building several Python branches and running tests only 16 MB of free space were left.
