### ISSUE TITLE
test_nntplib: random EOFError in setUpClass()

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74374]
BPO | [30188](https://bugs.python.org/issue30188)
--- | :---
Nosy | @pitrou, @vstinner, @methane, @koobs
PRs | <li>python/cpython#1322</li><li>python/cpython#1323</li><li>python/cpython#1324</li><li>python/cpython#2843</li><li>python/cpython#2892</li>
Files | <li>[koobs-freebsd-current-debug.py36.build.419.log](https://bugs.python.org/file47100/koobs-freebsd-current-debug.py36.build.419.log "Uploaded as text/plain at 2017-08-25.04:49:37 by @koobs")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-19.23:12:18.222>
created_at = <Date 2017-04-27.15:07:08.251>
labels = ['3.7', 'tests']
title = 'test_nntplib: random EOFError in setUpClass()'
updated_at = <Date 2018-09-19.23:12:18.221>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-19.23:12:18.221>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-19.23:12:18.222>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-04-27.15:07:08.251>
creator = 'vstinner'
dependencies = []
files = ['47100']
hgrepos = []
issue_num = 30188
keywords = []
message_count = 15.0
messages = ['292450', '292453', '292454', '292455', '292456', '292463', '292473', '292488', '298966', '298985', '299235', '300823', '300824', '302065', '303334']
nosy_count = 4.0
nosy_names = ['pitrou', 'vstinner', 'methane', 'koobs']
pr_nums = ['1322', '1323', '1324', '2843', '2892']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30188'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Example of failure:

\======================================================================
ERROR: setUpClass (test.test_nntplib.NetworkedNNTPTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/haypo/prog/python/master/Lib/test/test_nntplib.py", line 289, in setUpClass
    cls.server = cls.NNTP_CLASS(cls.NNTP_HOST, timeout=TIMEOUT, usenetrc=False)
  File "/home/haypo/prog/python/master/Lib/nntplib.py", line 1048, in __init__
    readermode, timeout)
  File "/home/haypo/prog/python/master/Lib/nntplib.py", line 330, in __init__
    self.welcome = self._getresp()
  File "/home/haypo/prog/python/master/Lib/nntplib.py", line 449, in _getresp
    resp = self._getline()
  File "/home/haypo/prog/python/master/Lib/nntplib.py", line 437, in _getline
    if not line: raise EOFError
EOFError
```


----------------------------------------------------------------------

Attached PR catch this error and skips the test.

See also issue bpo-19613 and bpo-19756.

**Comment by vstinner** [comment]
New changeset 5bccca58b9b2b3a925b16750bedbd907695ea8d7 by Victor Stinner in branch 'master':
bpo-30175: Skip client cert tests of test_imaplib (bpo-1320)
https://github.com/python/cpython/commit/5bccca58b9b2b3a925b16750bedbd907695ea8d7

**Comment by vstinner** [comment]
NetworkedNNTPTests uses the NNTP server news.trigofacile.com (port 119). It's possible to connect to this server (IPv4: 91.121.26.68), but recv() returns an empty string.

**Comment by vstinner** [comment]
I see 3 options:

* Contact news.trigofacile.com administrator to ask him to repair the NNTP server
* Run a NNTP server on pythontest.net
* Mock the server: see http://bugs.python.org/issue19756#msg268841

**Comment by vstinner** [comment]
The news.trigofacile.com server was chosen in the commit 1cb121eceae698b1be0b383de5d42dc9b9accd02 (Antoine Pitrou in 2010) which also added the new NetworkedNNTPTests test case.

**Comment by vstinner** [comment]
New changeset 4dc3b9cf2a868a8378ecbc2221a15e7b59e8e944 by Victor Stinner in branch '3.6':
bpo-30175: Skip client cert tests of test_imaplib (bpo-1320) (bpo-1323)
https://github.com/python/cpython/commit/4dc3b9cf2a868a8378ecbc2221a15e7b59e8e944

**Comment by vstinner** [comment]
New changeset 0eda2d43a7d5b262c979b944592999015a822395 by Victor Stinner in branch '3.5':
bpo-30175: Skip client cert tests of test_imaplib (bpo-1320) (bpo-1324)
https://github.com/python/cpython/commit/0eda2d43a7d5b262c979b944592999015a822395

**Comment by vstinner** [comment]
> Contact news.trigofacile.com administrator to ask him to repair the NNTP server

I did that and I got a reply: the server is now fixed! :-D

The test is now skipped on server failure (in 3.5, 3.6 and master), and the server is repaired. So I close the issue.

Note: Python 2.7 doesn't have the unit test and so is not impacted.

**Comment by vstinner** [comment]
Similar but different error (ssl.SSLEOFError) on AMD64 FreeBSD CURRENT Non-Debug 3.5:

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Non-Debug%203.5/builds/211/steps/test/logs/stdio

\======================================================================
ERROR: setUpClass (test.test_nntplib.NetworkedNNTP_SSLTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.5.koobs-freebsd-current.nondebug/build/Lib/test/test_nntplib.py", line 291, in setUpClass
    usenetrc=False)
  File "/usr/home/buildbot/python/3.5.koobs-freebsd-current.nondebug/build/Lib/nntplib.py", line 1077, in __init__
    self.sock = _encrypt_on(self.sock, ssl_context, host)
  File "/usr/home/buildbot/python/3.5.koobs-freebsd-current.nondebug/build/Lib/nntplib.py", line 292, in _encrypt_on
    return context.wrap_socket(sock, server_hostname=hostname)
  File "/usr/home/buildbot/python/3.5.koobs-freebsd-current.nondebug/build/Lib/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/home/buildbot/python/3.5.koobs-freebsd-current.nondebug/build/Lib/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/home/buildbot/python/3.5.koobs-freebsd-current.nondebug/build/Lib/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/home/buildbot/python/3.5.koobs-freebsd-current.nondebug/build/Lib/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:719)
```

**Comment by vstinner** [comment]
New changeset 5b4feb7e86ecb813b2c56560f86cda2fd46b9579 by Victor Stinner in branch 'master':
bpo-30188: test_nntplib catch also ssl.SSLEOFError (bpo-2843)
https://github.com/python/cpython/commit/5b4feb7e86ecb813b2c56560f86cda2fd46b9579

**Comment by methane** [comment]
New changeset 067931dd95ddfa34297be9c602a796d9f8d9bea3 by INADA Naoki in branch 'master':
bpo-30188: fix TypeError in test_nntplib (GH-2892)
https://github.com/python/cpython/commit/067931dd95ddfa34297be9c602a796d9f8d9bea3

**Comment by koobs** [comment]
bpo-30188 (and bpo-30188 ?) need merging to 3.6/3.5, 3.6 just failed with:

ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:748)

Full build log attached

**Comment by koobs** [comment]
Apologies I meant 5b4feb7e86 by haypo and 067931dd95d (also needs merge?)  by inada.naoki

**Comment by vstinner** [comment]
The SSL EOF error is still common, but in the test, not in setUpClass(). Example:

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%2010.x%20Shared%203.x/builds/874/steps/test/logs/stdio

\======================================================================
ERROR: test_with_statement (test.test_nntplib.NetworkedNNTP_SSLTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd10/build/Lib/test/test_nntplib.py", line 241, in wrapped
    meth(self)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd10/build/Lib/test/test_nntplib.py", line 263, in test_with_statement
    with self.NNTP_CLASS(self.NNTP_HOST, timeout=TIMEOUT, usenetrc=False) as server:
  File "/usr/home/buildbot/python/3.x.koobs-freebsd10/build/Lib/nntplib.py", line 1077, in __init__
    self.sock = _encrypt_on(self.sock, ssl_context, host)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd10/build/Lib/nntplib.py", line 292, in _encrypt_on
    return context.wrap_socket(sock, server_hostname=hostname)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd10/build/Lib/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd10/build/Lib/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd10/build/Lib/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd10/build/Lib/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:864)
```


pythininfo:

ssl.HAS_SNI: True
ssl.OPENSSL_VERSION: OpenSSL 1.0.1u-freebsd  22 Sep 2016
ssl.OPENSSL_VERSION_INFO: (1, 0, 1, 21, 15)
ssl.OP_ALL: 0x800003ff
ssl.OP_NO_TLSv1_1: 0x10000000

**Comment by vstinner** [comment]
Recent failure:

http://buildbot.python.org/all/builders/x86%20Gentoo%20Non-Debug%20with%20X%203.x/builds/1080/steps/test/logs/stdio

\======================================================================
ERROR: test_with_statement (test.test_nntplib.NetworkedNNTP_SSLTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/test_nntplib.py", line 241, in wrapped
    meth(self)
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/test_nntplib.py", line 263, in test_with_statement
    with self.NNTP_CLASS(self.NNTP_HOST, timeout=TIMEOUT, usenetrc=False) as server:
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/nntplib.py", line 1077, in __init__
    self.sock = _encrypt_on(self.sock, ssl_context, host)
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/nntplib.py", line 292, in _encrypt_on
    return context.wrap_socket(sock, server_hostname=hostname)
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/ssl.py", line 411, in wrap_socket
    _session=session
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/ssl.py", line 822, in __init__
    self.do_handshake()
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/ssl.py", line 1076, in do_handshake
    self._sslobj.do_handshake()
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/ssl.py", line 697, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:864)
```
