### ISSUE TITLE
Regex becomes invalid in python 3.6

### ISSUE THREAD

**Issue by 936c8c3e-c701-4317-9790-25fbd697a163** [python/cpython#74373]
BPO | [30187](https://bugs.python.org/issue30187)
--- | :---
Nosy | @ezio-melotti, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-27.14:59:38.489>
created_at = <Date 2017-04-27.14:07:54.375>
labels = ['expert-regex', 'type-bug', 'invalid']
title = 'Regex becomes invalid in python 3.6'
updated_at = <Date 2017-04-27.15:06:49.956>
user = 'https://bugs.python.org/ChrisSeto2'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-27.15:06:49.956>
actor = 'Chris Seto2'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-27.14:59:38.489>
closer = 'serhiy.storchaka'
components = ['Regular Expressions']
creation = <Date 2017-04-27.14:07:54.375>
creator = 'Chris Seto2'
dependencies = []
files = []
hgrepos = []
issue_num = 30187
keywords = []
message_count = 3.0
messages = ['292445', '292448', '292449']
nosy_count = 4.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'Chris Seto2']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30187'
versions = ['Python 3.6']
```

</p></details>

**Comment by 936c8c3e-c701-4317-9790-25fbd697a163** [comment]
```pycon
Expected behavior:
~ ❯❯❯ pyenv shell 3.5.2
~ ❯❯❯ python --version
Python 3.5.2
~ ❯❯❯ python
Python 3.5.2 (default, Oct 24 2016, 00:12:20)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.compile('[^\B]')
re.compile('[^\\B]')
>>> re.compile(r'[^\B]')
re.compile('[^\\B]')

Actual:
~ ❯❯❯ pyenv shell 3.6.0
~ ❯❯❯ python --version
Python 3.6.0
~ ❯❯❯ python
Python 3.6.0 (default, Apr 26 2017, 17:24:07)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.compile('[^\B]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/sre_parse.py", line 856, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, False)
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/sre_parse.py", line 526, in _parse
    code1 = _class_escape(source, this)
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/sre_parse.py", line 336, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
sre_constants.error: bad escape \B at position 2

>>> re.compile(r'[^\B]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/sre_parse.py", line 856, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, False)
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/sre_parse.py", line 526, in _parse
    code1 = _class_escape(source, this)
  File "/Users/chrisseto/.pyenv/versions/3.6.0/lib/python3.6/sre_parse.py", line 336, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
sre_constants.error: bad escape \B at position 2
```

**Comment by serhiy-storchaka** [comment]
This is ambiguous syntax. Unknown escapes consisting of '\\' and ASCII letter were deprecated in 3.5 (run the interpreter with the option -Wa to see all warnings) and are errors since 3.6. Note that the string literal '[^\\B]' itself produces a DeprecationWarning in 3.6.

**Comment by 936c8c3e-c701-4317-9790-25fbd697a163** [comment]
Thank you for pointing that out to me!
