### ISSUE TITLE
hashlib module breaks with 64-bit kernel and 32-bit user space

### ISSUE THREAD

**Issue by nascheme** [python/cpython#74378]
BPO | [30192](https://bugs.python.org/issue30192)
--- | :---
Nosy | @nascheme, @tiran, @berkerpeksag
PRs | <li>python/cpython#1332</li><li>python/cpython#2042</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-16.02:13:22.600>
created_at = <Date 2017-04-27.21:20:03.384>
labels = ['build', '3.7']
title = 'hashlib module breaks with 64-bit kernel and 32-bit user space'
updated_at = <Date 2017-06-16.02:13:22.599>
user = 'https://github.com/nascheme'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-16.02:13:22.599>
actor = 'Mariatta'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-16.02:13:22.600>
closer = 'Mariatta'
components = ['Build']
creation = <Date 2017-04-27.21:20:03.384>
creator = 'nascheme'
dependencies = []
files = []
hgrepos = []
issue_num = 30192
keywords = []
message_count = 5.0
messages = ['292485', '292703', '293048', '293118', '295584']
nosy_count = 3.0
nosy_names = ['nascheme', 'christian.heimes', 'berker.peksag']
pr_nums = ['1332', '2042']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30192'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by nascheme** [comment]
The test in setup.py to check for SSE2 support is incorrect.  Checking that arch == x86_64 is not sufficient.  If the kernel is 64-bit but Python is compiled with a 32-bit compiler, the \_blake2 module will fail to build.

The attached patch fixes this issue. I did a quick search of the x86_64 string, I don't see this mistake being made elsewhere but I imagine it could be done elsewhere.  Obviously a machine with a 64-bit kernel and 32-bit userspace is a rare as hen's teeth these days.  Still, I think it is worth fixing this bug.

```pycon
Python 3.6.1 (default, Apr 27 2017, 20:09:03) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
ERROR:root:code for hash blake2b was not found.
Traceback (most recent call last):
  File "/home/nas/PPython-3.6.1/Lib/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/nas/PPython-3.6.1/Lib/hashlib.py", line 119, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/home/nas/PPython-3.6.1/Lib/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type blake2b
ERROR:root:code for hash blake2s was not found.
Traceback (most recent call last):
  File "/home/nas/PPython-3.6.1/Lib/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/nas/PPython-3.6.1/Lib/hashlib.py", line 119, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/home/nas/PPython-3.6.1/Lib/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type blake2s
```

**Comment by tiran** [comment]
The issues seems to be resolved. In the future please add the expert for a topic or maintainer of a module to the nosy list of the ticket.

**Comment by berkerpeksag** [comment]
Neil, can this issue be closed or do you want to backport to 3.6?

**Comment by nascheme** [comment]
It should be backported in my opinion.

**Comment by nascheme** [comment]
Create [PR 2042](https://github.com/python/cpython/pull/2042) for backport to 3.6 branch.
