### ISSUE TITLE
AttributeError on opening ZipFile

### ISSUE THREAD

**Issue by 304441a1-3d9a-41c6-a49b-2aeefbb22eb4** [python/cpython#74380]
BPO | [30194](https://bugs.python.org/issue30194)
--- | :---
Nosy | @vstinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-28.01:20:15.005>
created_at = <Date 2017-04-28.01:15:03.382>
labels = ['invalid']
title = 'AttributeError on opening ZipFile'
updated_at = <Date 2017-04-28.01:20:14.994>
user = 'https://bugs.python.org/JacobB2'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-28.01:20:14.994>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-28.01:20:15.005>
closer = 'vstinner'
components = []
creation = <Date 2017-04-28.01:15:03.382>
creator = 'Jacob B2'
dependencies = []
files = []
hgrepos = []
issue_num = 30194
keywords = []
message_count = 2.0
messages = ['292494', '292495']
nosy_count = 2.0
nosy_names = ['vstinner', 'Jacob B2']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30194'
versions = ['Python 3.6']
```

</p></details>

**Comment by 304441a1-3d9a-41c6-a49b-2aeefbb22eb4** [comment]
The error occurs when I attempt to run the following code:

```py
from urllib.request import urlretrieve
from os import path
from zipfile import ZipFile

download_url = "https://www.dropbox.com/s/obiqvrt4m53pmoz/tesseract-4.0.0-alpha.zip?dl=1"


def setup_program():
    zip_name = urlretrieve(download_url)

    zip_file = ZipFile(zip_name, "r")
    zip_file.extractall(path.abspath("__tesseract/"))
    zip_file.close()

setup_program()  # REMOVE after test
```



I get the following traceback:

```pytb
$ python downloader.py
Traceback (most recent call last):
  File "downloader.py", line 15, in <module>
    setup_program()
  File "downloader.py", line 11, in setup_program
    zip_file = ZipFile(zip_name, "r")
  File "C:\Python36\lib\zipfile.py", line 1100, in __init__
    self._RealGetContents()
  File "C:\Python36\lib\zipfile.py", line 1163, in _RealGetContents
    endrec = _EndRecData(fp)
  File "C:\Python36\lib\zipfile.py", line 241, in _EndRecData
    fpin.seek(0, 2)
AttributeError: 'tuple' object has no attribute 'seek'
```

**Comment by vstinner** [comment]
urlretrieve() returns (filename, file-like object). It's a bug in your code, not in Python itself ;-)
