### ISSUE TITLE
[3.5] RecvmsgIntoSCMRightsStreamTest fails with "OSError: [Errno 12] Cannot allocate memory" on macOS El Capitan

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74387]
BPO | [30201](https://bugs.python.org/issue30201)
--- | :---
Nosy | @ronaldoussoren, @vstinner, @ned-deily
Superseder | <li>bpo-24725: test_socket testFDPassEmpty fails on OS X 10.11+ with &quot;Cannot allocate memory&quot;</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-03.10:17:00.647>
created_at = <Date 2017-04-28.16:20:49.304>
labels = ['OS-mac', 'tests']
title = '[3.5] RecvmsgIntoSCMRightsStreamTest fails with "OSError: [Errno 12] Cannot allocate memory" on macOS El Capitan'
updated_at = <Date 2017-05-03.10:17:00.646>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-03.10:17:00.646>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-03.10:17:00.647>
closer = 'vstinner'
components = ['macOS', 'Tests']
creation = <Date 2017-04-28.16:20:49.304>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30201
keywords = []
message_count = 2.0
messages = ['292538', '292880']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'vstinner', 'ned.deily']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '24725'
type = None
url = 'https://bugs.python.org/issue30201'
versions = ['Python 3.5']
```

</p></details>

**Comment by vstinner** [comment]
The test fails on Python 3.5 but pass on Python 3.6, I don't know why.

http://buildbot.python.org/all/builders/x86-64%20El%20Capitan%203.5/builds/31/steps/test/logs/stdio

\======================================================================
ERROR: testFDPassEmpty (test.test_socket.RecvmsgSCMRightsStreamTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.5.billenstein-elcapitan/build/Lib/test/test_socket.py", line 2851, in testFDPassEmpty
    len(MSG), 10240),
  File "/Users/buildbot/buildarea/3.5.billenstein-elcapitan/build/Lib/test/test_socket.py", line 1955, in doRecvmsg
    result = sock.recvmsg(bufsize, *args)
OSError: [Errno 12] Cannot allocate memory
```


======================================================================
ERROR: testFDPassEmpty (test.test_socket.RecvmsgIntoSCMRightsStreamTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.5.billenstein-elcapitan/build/Lib/test/test_socket.py", line 2851, in testFDPassEmpty
    len(MSG), 10240),
  File "/Users/buildbot/buildarea/3.5.billenstein-elcapitan/build/Lib/test/test_socket.py", line 2046, in doRecvmsg
    result = sock.recvmsg_into([buf], *args)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by vstinner** [comment]
Duplicate of issue bpo-24725, I proposed a backport to 3.5:
https://github.com/python/cpython/pull/1427
