### ISSUE TITLE
test_asyncore: test_handle_expt() fails on macOS Sierra

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74425]
BPO | [30239](https://bugs.python.org/issue30239)
--- | :---
Nosy | @ronaldoussoren, @vstinner, @ned-deily
Superseder | <li>bpo-28087: macOS 12 poll syscall returns prematurely</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-03.09:36:30.204>
created_at = <Date 2017-05-03.00:07:31.001>
labels = ['OS-mac', '3.7', 'tests']
title = 'test_asyncore: test_handle_expt() fails on macOS Sierra'
updated_at = <Date 2017-05-03.09:36:30.203>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-03.09:36:30.203>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-03.09:36:30.204>
closer = 'vstinner'
components = ['macOS', 'Tests']
creation = <Date 2017-05-03.00:07:31.001>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30239
keywords = []
message_count = 4.0
messages = ['292824', '292825', '292863', '292868']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'vstinner', 'ned.deily']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '28087'
type = None
url = 'https://bugs.python.org/issue30239'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86-64%20Sierra%203.5/builds/39/steps/test/logs/stdio

\======================================================================
FAIL: test_handle_expt (test.test_asyncore.TestAPI_UseIPv4Poll)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.5.billenstein-sierra/build/Lib/test/test_asyncore.py", line 671, in test_handle_expt
    self.loop_waiting_for_flag(client)
  File "/Users/buildbot/buildarea/3.5.billenstein-sierra/build/Lib/test/test_asyncore.py", line 511, in loop_waiting_for_flag
    self.fail("flag not set")
AssertionError: flag not set
```


======================================================================
FAIL: test_handle_expt (test.test_asyncore.TestAPI_UseIPv6Poll)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.5.billenstein-sierra/build/Lib/test/test_asyncore.py", line 671, in test_handle_expt
    self.loop_waiting_for_flag(client)
  File "/Users/buildbot/buildarea/3.5.billenstein-sierra/build/Lib/test/test_asyncore.py", line 511, in loop_waiting_for_flag
    self.fail("flag not set")
AssertionError: flag not set
```

**Comment by vstinner** [comment]
See also issue bpo-30201:
 [3.5] RecvmsgIntoSCMRightsStreamTest fails with "OSError: [Errno 12] Cannot allocate memory" on macOS El Capitan.

**Comment by vstinner** [comment]
This issue seems similar to issue bpo-28087.

**Comment by vstinner** [comment]
> This issue seems similar to issue bpo-28087.

Aaaah, it's not just similar, it's exactly the same bug: it's just that the 3.5 branch wasn't fixed yet. I proposed a backport:
https://github.com/python/cpython/pull/1424
