### ISSUE TITLE
distutils.version.LooseVersion's compare raises exception in corner-case

### ISSUE THREAD

**Issue by 86133129-c670-4fde-9d9f-486d3da4b65b** [python/cpython#74458]
BPO | [30272](https://bugs.python.org/issue30272)
--- | :---
Nosy | @merwok, @berkerpeksag, @dstufft
Superseder | <li>bpo-14894: distutils.LooseVersion fails to compare number and a word</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-05.18:26:05.875>
created_at = <Date 2017-05-04.19:54:49.076>
labels = ['type-bug', 'library']
title = "distutils.version.LooseVersion's compare raises exception in corner-case"
updated_at = <Date 2017-05-05.18:26:05.873>
user = 'https://bugs.python.org/ollieparanoid2'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-05.18:26:05.873>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-05.18:26:05.875>
closer = 'berker.peksag'
components = ['Distutils']
creation = <Date 2017-05-04.19:54:49.076>
creator = 'ollieparanoid2'
dependencies = []
files = []
hgrepos = []
issue_num = 30272
keywords = []
message_count = 2.0
messages = ['293009', '293133']
nosy_count = 4.0
nosy_names = ['eric.araujo', 'berker.peksag', 'dstufft', 'ollieparanoid2']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '14894'
type = 'behavior'
url = 'https://bugs.python.org/issue30272'
versions = ['Python 3.6']
```

</p></details>

**Comment by 86133129-c670-4fde-9d9f-486d3da4b65b** [comment]
This should return True and not raise an exception:

```pycon
>>> from distutils.version import LooseVersion
>>> LooseVersion("22.7-r1") < LooseVersion("22.7.3-r1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
>>>
```


Tested with Python 3.6.1.

**Comment by berkerpeksag** [comment]
Thanks for the report. This is a duplicate of bpo-14894.
