### ISSUE TITLE
test_timeout() of test_multiprocessing_spawn.WithManagerTestBarrier fails randomly on x86 Windows7 3.x buildbot

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74502]
BPO | [30317](https://bugs.python.org/issue30317)
--- | :---
Nosy | @vstinner, @zware, @applio, @pablogsal, @miss-islington
PRs | <li>python/cpython#1722</li><li>python/cpython#7957</li><li>python/cpython#7958</li><li>python/cpython#7959</li><li>python/cpython#8621</li><li>python/cpython#8637</li><li>python/cpython#8638</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-19.23:28:50.733>
created_at = <Date 2017-05-09.15:52:59.681>
labels = ['3.8', '3.7', 'tests']
title = 'test_timeout() of test_multiprocessing_spawn.WithManagerTestBarrier fails randomly on x86 Windows7 3.x buildbot'
updated_at = <Date 2018-09-19.23:28:50.731>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-19.23:28:50.731>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-19.23:28:50.733>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-05-09.15:52:59.681>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30317
keywords = ['patch', 'buildbot']
message_count = 20.0
messages = ['293328', '293333', '294166', '296443', '296466', '296529', '317947', '319413', '320058', '320556', '320557', '320559', '320561', '322934', '323003', '323005', '323006', '323076', '323090', '325826']
nosy_count = 5.0
nosy_names = ['vstinner', 'zach.ware', 'davin', 'pablogsal', 'miss-islington']
pr_nums = ['1722', '7957', '7958', '7959', '8621', '8637', '8638']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30317'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86%20Windows7%203.x/builds/588/steps/test/logs/stdio

```pytb
0:49:08 [225/405/1] test_multiprocessing_spawn failed
Process Process-59:
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1179, in task
    self.f(*self.args)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1385, in _test_timeout_f
    i = barrier.wait()
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\managers.py", line 1040, in wait
    return self._callmethod('wait', (timeout,))
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
threading.BrokenBarrierError
Process Process-60:
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1179, in task
    self.f(*self.args)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1385, in _test_timeout_f
    i = barrier.wait()
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\managers.py", line 1040, in wait
    return self._callmethod('wait', (timeout,))
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
threading.BrokenBarrierError
Process Process-62:
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1179, in task
    self.f(*self.args)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1385, in _test_timeout_f
    i = barrier.wait()
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\managers.py", line 1040, in wait
    return self._callmethod('wait', (timeout,))
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
threading.BrokenBarrierError
Process Process-61:
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1179, in task
    self.f(*self.args)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1385, in _test_timeout_f
    i = barrier.wait()
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\managers.py", line 1040, in wait
    return self._callmethod('wait', (timeout,))
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
threading.BrokenBarrierError
test_answer_challenge_auth_failure (test.test_multiprocessing_spawn.OtherTest) ... ok
test_deliver_challenge_auth_failure (test.test_multiprocessing_spawn.OtherTest) ... ok
```


(...)

\======================================================================
ERROR: test_timeout (test.test_multiprocessing_spawn.WithManagerTestBarrier)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1399, in test_timeout
    self.run_threads(self._test_timeout_f, (self.barrier, results))
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1228, in run_threads
    f(*args)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1385, in _test_timeout_f
    i = barrier.wait()
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\managers.py", line 1040, in wait
    return self._callmethod('wait', (timeout,))
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
threading.BrokenBarrierError
```


----------------------------------------------------------------------
Ran 277 tests in 762.297s

FAILED (errors=1, skipped=24)
test test_multiprocessing_spawn failed

**Comment by vstinner** [comment]
Other similar errors.

http://buildbot.python.org/all/builders/x86%20Windows7%203.6/builds/339/steps/test/logs/stdio

```pytb
1:05:52 [382/405/1] test_multiprocessing_spawn failed -- running: test_mmap (556 sec)
Process Process-129:
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1179, in task
    self.f(*self.args)
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1317, in _test_reset_f
    i = barrier.wait()
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\threading.py", line 603, in wait
    self._enter() # Block while the barrier drains.
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\threading.py", line 627, in _enter
    raise BrokenBarrierError
threading.BrokenBarrierError
Process Process-130:
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1179, in task
    self.f(*self.args)
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1317, in _test_reset_f
    i = barrier.wait()
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\threading.py", line 603, in wait
    self._enter() # Block while the barrier drains.
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\threading.py", line 627, in _enter
    raise BrokenBarrierError
threading.BrokenBarrierError
Process Process-132:
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1179, in task
    self.f(*self.args)
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1317, in _test_reset_f
    i = barrier.wait()
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\threading.py", line 603, in wait
    self._enter() # Block while the barrier drains.
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\threading.py", line 627, in _enter
    raise BrokenBarrierError
threading.BrokenBarrierError
Process Process-131:
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1179, in task
    self.f(*self.args)
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1317, in _test_reset_f
    i = barrier.wait()
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\threading.py", line 603, in wait
    self._enter() # Block while the barrier drains.
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\threading.py", line 627, in _enter
    raise BrokenBarrierError
threading.BrokenBarrierError
test_answer_challenge_auth_failure (test.test_multiprocessing_spawn.OtherTest) ... ok
test_deliver_challenge_auth_failure (test.test_multiprocessing_spawn.OtherTest) ... ok
```


(...)

test_barrier_10 (test.test_multiprocessing_spawn.WithProcessesTestBarrier) ... ok
test_default_timeout (test.test_multiprocessing_spawn.WithProcessesTestBarrier) ... ok
test_reset (test.test_multiprocessing_spawn.WithProcessesTestBarrier) ... ERROR
test_single_thread (test.test_multiprocessing_spawn.WithProcessesTestBarrier) ... ok
test_thousand (test.test_multiprocessing_spawn.WithProcessesTestBarrier) ... ok

(...)

\======================================================================
ERROR: test_reset (test.test_multiprocessing_spawn.WithProcessesTestBarrier)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1341, in test_reset
    (self.barrier, results1, results2, results3))
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1228, in run_threads
    f(*args)
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 1317, in _test_reset_f
    i = barrier.wait()
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\threading.py", line 612, in wait
    self._wait(timeout)
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\threading.py", line 650, in _wait
    raise BrokenBarrierError
threading.BrokenBarrierError
```


======================================================================
FAIL: test_timeout (test.test_multiprocessing_spawn.WithProcessesTestQueue)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 753, in test_timeout
    self.assertGreaterEqual(delta, 0.170)
AssertionError: 0.16138982772827148 not greater than or equal to 0.17
```


----------------------------------------------------------------------
Ran 277 tests in 579.477s

**Comment by applio** [comment]
To better accommodate very slow buildbots, a parameter is added in [PR-1722](https://github.com/python/cpython/pull/1722) to scale up the timeout durations where they are necessary on a per-machine basis.

Relevant tests have a timeout set to some default number of seconds times a multiplier value.

The multiplier value can be controlled by the environment variable 'CONF_TIMEOUT_MULTIPLIER' which defaults to a multiplier of 1.0 if not set.  On buildbots, this environment variable can be set by defining a parameter by that name in the buildbot configuration file for a machine.  Otherwise, this environment variable can be set in the usual way before running tests on non-buildbot machines.

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86%20Windows7%203.x/builds/770/steps/test/logs/stdio

\======================================================================
FAIL: test_timeout (test.test_multiprocessing_spawn.WithManagerTestQueue)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 788, in test_timeout
    self.assertGreaterEqual(delta, 0.170)
AssertionError: 0.15492773056030273 not greater than or equal to 0.17
```


======================================================================
FAIL: test_timeout (test.test_multiprocessing_spawn.WithThreadsTestQueue)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 788, in test_timeout
    self.assertGreaterEqual(delta, 0.170)
AssertionError: 0.16765165328979492 not greater than or equal to 0.17
```

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86%20Windows7%203.5/builds/299/steps/test/logs/stdio

\======================================================================
FAIL: test_timeout (test.test_multiprocessing_spawn.WithProcessesTestQueue)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.5.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 753, in test_timeout
    self.assertGreaterEqual(delta, 0.170)
AssertionError: 0.1293318271636963 not greater than or equal to 0.17
```

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86%20Windows7%203.x/builds/774/steps/test/logs/stdio



\======================================================================
FAIL: test_timeout (test.test_multiprocessing_spawn.WithProcessesTestQueue)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 788, in test_timeout
    self.assertGreaterEqual(delta, 0.170)
AssertionError: 0.15966796875 not greater than or equal to 0.17
```


======================================================================
FAIL: test_timeout (test.test_multiprocessing_spawn.WithThreadsTestQueue)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 788, in test_timeout
    self.assertGreaterEqual(delta, 0.170)
AssertionError: 0.1293318271636963 not greater than or equal to 0.17
```
