### ISSUE TITLE
test_default_timeout() of test_threading.BarrierTests: random failures on AMD64 FreeBSD CURRENT Debug 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74501]
BPO | [30316](https://bugs.python.org/issue30316)
--- | :---
Nosy | @tim-one, @pitrou, @kristjanvalur, @vstinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-07-11.21:49:45.584>
created_at = <Date 2017-05-09.15:49:35.706>
labels = ['3.7', 'tests']
title = 'test_default_timeout() of test_threading.BarrierTests: random failures on AMD64 FreeBSD CURRENT Debug 3.x'
updated_at = <Date 2018-07-11.21:49:45.583>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-11.21:49:45.583>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-07-11.21:49:45.584>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-05-09.15:49:35.706>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30316
keywords = ['buildbot']
message_count = 6.0
messages = ['293327', '293406', '293407', '295878', '301462', '321503']
nosy_count = 4.0
nosy_names = ['tim.peters', 'pitrou', 'kristjan.jonsson', 'vstinner']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30316'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
test_default_timeout() of test_threading.BarrierTests randomly fails on AMD64 FreeBSD CURRENT Debug 3.x:

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Debug%203.x/builds/246/steps/test/logs/stdio


```pytb
test_default_timeout (test.test_threading.BarrierTests) ... ERROR
test_reset (test.test_threading.BarrierTests) ... Unhandled exception in thread started by <function Bunch.__init__.<locals>.task at 0x8057bed48>
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/lock_tests.py", line 38, in task
Unhandled exception in thread started by <function Bunch.__init__.<locals>.task at 0x8057bed48>
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/lock_tests.py", line 38, in task
    f()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/lock_tests.py", line 917, in f
    i = barrier.wait()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 603, in wait
    self._enter() # Block while the barrier drains.
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 627, in _enter
    raise BrokenBarrierError
threading.BrokenBarrierError
Unhandled exception in thread started by <function Bunch.__init__.<locals>.task at 0x8057bed48>
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/lock_tests.py", line 38, in task
    f()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/lock_tests.py", line 917, in f
    i = barrier.wait()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 612, in wait
    self._wait(timeout)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 652, in _wait
    raise BrokenBarrierError
threading.BrokenBarrierError
Unhandled exception in thread started by <function Bunch.__init__.<locals>.task at 0x8057bed48>
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/lock_tests.py", line 38, in task
    f()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/lock_tests.py", line 917, in f
    i = barrier.wait()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 603, in wait
    self._enter() # Block while the barrier drains.
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 627, in _enter
    raise BrokenBarrierError
threading.BrokenBarrierError
    f()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/lock_tests.py", line 917, in f
    i = barrier.wait()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 612, in wait
    self._wait(timeout)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 652, in _wait
    raise BrokenBarrierError
threading.BrokenBarrierError
ok
```


(...)


test_frame_tstate_tracing (test.test_threading.ThreadTests) ... ok
test_ident_of_no_threading_threads (test.test_threading.ThreadTests) ... ok
test_is_alive_after_fork (test.test_threading.ThreadTests) ... Warning -- threading_cleanup() failed to cleanup 0 threads after 4 sec (count: 0, dangling: 21)
ok
test_join_nondaemon_on_shutdown (test.test_threading.ThreadTests) ... ok
test_limbo_cleanup (test.test_threading.ThreadTests) ... ok

(...)

\======================================================================
ERROR: test_default_timeout (test.test_threading.BarrierTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/lock_tests.py", line 922, in test_default_timeout
    self.run_threads(f)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/lock_tests.py", line 751, in run_threads
    f()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/lock_tests.py", line 917, in f
    i = barrier.wait()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 612, in wait
    self._wait(timeout)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/threading.py", line 650, in _wait
    raise BrokenBarrierError
threading.BrokenBarrierError
```

**Comment by vstinner** [comment]
Another similar bug different exception in test_thread on AMD64 FreeBSD CURRENT Debug 3.6:

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Debug%203.6/builds/145/steps/test/logs/stdio


test_save_exception_state_on_error (test.test_thread.ThreadRunningTests) ... FAIL
test_stack_size (test.test_thread.ThreadRunningTests) ... ok
...

\======================================================================
FAIL: test_save_exception_state_on_error (test.test_thread.ThreadRunningTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.6.koobs-freebsd-current/build/Lib/test/test_thread.py", line 148, in test_save_exception_state_on_error
    self.assertIn("Traceback", stderr.getvalue())
AssertionError: 'Traceback' not found in ''
```


----------------------------------------------------------------------
Ran 23 tests in 1.565s

FAILED (failures=1)
test test_thread failed

**Comment by vstinner** [comment]
Full test output.

```pytb
0:04:38 [ 86/405/1] test_thread failed -- running: test_multiprocessing_spawn (214 sec)
test_barrier (test.test_thread.BarrierTest) ... waiting for tasks to end
task 0 will run for 0us
task 0 entering 0
task 2 will run for 4us
task 2 entering 0
task 6 will run for 90us
task 4 will run for 15us
task 6 entering 0
task 1 will run for 7us
task 3 will run for 33us
task 5 will run for 85us
task 7 will run for 71us
task 7 entering 0
task 5 entering 0
task 9 will run for 45us
task 4 entering 0
task 8 will run for 62us
task 8 entering 0
task 1 entering 0
task 9 entering 0
task 3 entering 0
task 3 leaving barrier
task 3 will run for 15us
task 3 entering 1
task 0 leaving barrier
task 0 will run for 0us
task 0 entering 1
task 2 leaving barrier
task 2 will run for 98us
task 2 entering 1
task 6 leaving barrier
task 6 will run for 91us
task 7 leaving barrier
task 7 will run for 67us
task 6 entering 1
task 7 entering 1
task 4 leaving barrier
task 4 will run for 38us
task 4 entering 1
task 8 leaving barrier
task 8 will run for 84us
task 8 entering 1
task 5 leaving barrier
task 5 will run for 92us
task 5 entering 1
task 9 leaving barrier
task 9 will run for 1us
task 9 entering 1
task 1 leaving barrier
task 1 will run for 55us
task 1 entering 1
task 0 leaving barrier
task 0 will run for 0us
task 0 entering 2
task 9 leaving barrier
task 9 will run for 2us
task 2 leaving barrier
task 2 will run for 92us
task 9 entering 2
task 6 leaving barrier
task 6 will run for 43us
task 2 entering 2
task 7 leaving barrier
task 7 will run for 90us
task 6 entering 2
task 4 leaving barrier
task 4 will run for 1us
task 8 leaving barrier
task 8 will run for 20us
task 4 entering 2
task 8 entering 2
task 5 leaving barrier
task 5 will run for 86us
task 7 entering 2
task 3 leaving barrier
task 3 will run for 3us
task 5 entering 2
task 3 entering 2
task 1 leaving barrier
task 1 will run for 80us
task 1 entering 2
task 1 leaving barrier
task 0 leaving barrier
task 2 leaving barrier
task 9 leaving barrier
task 6 leaving barrier
task 8 leaving barrier
task 4 leaving barrier
task 7 leaving barrier
task 5 leaving barrier
task 3 leaving barrier
tasks done
ok
test_acquire_contended (test.test_thread.LockTests) ... ok
test_acquire_destroy (test.test_thread.LockTests) ... ok
test_acquire_release (test.test_thread.LockTests) ... ok
test_constructor (test.test_thread.LockTests) ... ok
test_different_thread (test.test_thread.LockTests) ... ok
test_locked_repr (test.test_thread.LockTests) ... ok
test_reacquire (test.test_thread.LockTests) ... ok
test_repr (test.test_thread.LockTests) ... ok
test_state_after_timeout (test.test_thread.LockTests) ... ok
test_thread_leak (test.test_thread.LockTests) ... ok
test_timeout (test.test_thread.LockTests) ... ok
test_try_acquire (test.test_thread.LockTests) ... ok
test_try_acquire_contended (test.test_thread.LockTests) ... ok
test_weakref_deleted (test.test_thread.LockTests) ... ok
test_weakref_exists (test.test_thread.LockTests) ... ok
test_with (test.test_thread.LockTests) ... ok
test_forkinthread (test.test_thread.TestForkInThread) ... ok
test__count (test.test_thread.ThreadRunningTests) ... ok
test_nt_and_posix_stack_size (test.test_thread.ThreadRunningTests) ... caught expected ValueError setting stack_size(4096)
successfully set stack_size(262144)
successfully set stack_size(1048576)
successfully set stack_size(0)
trying stack_size = (262144)
creating task 1
creating task 2
creating task 3
creating task 4
creating task 5
creating task 6
creating task 7
creating task 8
creating task 9
creating task 10
waiting for all tasks to complete
task 1 will run for 45us
task 2 will run for 22us
task 2 done
task 3 will run for 57us
task 4 will run for 61us
task 3 done
task 4 done
task 7 will run for 73us
task 9 will run for 46us
task 10 will run for 63us
task 8 will run for 71us
task 7 done
task 5 will run for 54us
task 6 will run for 6us
task 6 done
task 1 done
task 8 done
task 10 done
task 5 done
task 9 done
all tasks done
trying stack_size = (1048576)
creating task 1
creating task 2
creating task 3
creating task 4
creating task 5
creating task 6
creating task 7
creating task 8
creating task 9
creating task 10
waiting for all tasks to complete
task 1 will run for 74us
task 2 will run for 87us
task 4 will run for 76us
task 6 will run for 41us
task 3 will run for 23us
task 5 will run for 22us
task 2 done
task 9 will run for 0us
task 3 done
task 6 done
task 10 will run for 83us
task 4 done
task 8 will run for 35us
task 1 done
task 8 done
task 10 done
task 9 done
task 7 will run for 67us
task 5 done
task 7 done
all tasks done
ok
test_save_exception_state_on_error (test.test_thread.ThreadRunningTests) ... FAIL
test_stack_size (test.test_thread.ThreadRunningTests) ... ok
test_starting_threads (test.test_thread.ThreadRunningTests) ... creating task 1
creating task 2
creating task 3
creating task 4
creating task 5
creating task 6
creating task 7
creating task 8
creating task 9
creating task 10
waiting for tasks to complete...
task 2 will run for 38us
task 4 will run for 69us
task 8 will run for 41us
task 6 will run for 39us
task 2 done
task 10 will run for 9us
Unhandled exception in thread started by <function ThreadRunningTests.test_save_exception_state_on_error.<locals>.task at 0x805779a68>
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.6.koobs-freebsd-current/build/Lib/test/test_thread.py", line 131, in task
    raise SyntaxError
SyntaxError: None
task 1 will run for 96us
task 3 will run for 36us
task 1 done
task 9 will run for 38us
task 5 will run for 39us
task 5 done
task 8 done
task 4 done
task 7 will run for 36us
task 6 done
task 10 done
task 9 done
task 7 done
task 3 done
all tasks done
ok
```


======================================================================
FAIL: test_save_exception_state_on_error (test.test_thread.ThreadRunningTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.6.koobs-freebsd-current/build/Lib/test/test_thread.py", line 148, in test_save_exception_state_on_error
    self.assertIn("Traceback", stderr.getvalue())
AssertionError: 'Traceback' not found in ''
```


----------------------------------------------------------------------
Ran 23 tests in 1.565s

FAILED (failures=1)
test test_thread failed

**Comment by vstinner** [comment]
Similar failure on AMD64 Windows8 3.6:

http://buildbot.python.org/all/builders/AMD64%20Windows8%203.6/builds/425/steps/test/logs/stdio

```pytb
(...)
test_abort_and_reset (test.test_threading.BarrierTests) ... ok
test_action (test.test_threading.BarrierTests) ... ok
test_barrier (test.test_threading.BarrierTests) ... ok
test_barrier_10 (test.test_threading.BarrierTests) ... ok
test_default_timeout (test.test_threading.BarrierTests) ... Unhandled exception in thread started by <function Bunch.__init__.<locals>.task at 0x000000B21066D9B0>
Traceback (most recent call last):
  File "D:\buildarea\3.6.bolen-windows8\build\lib\test\lock_tests.py", line 38, in task
Unhandled exception in thread started by <function Bunch.__init__.<locals>.task at 0x000000B21066D9B0>
Traceback (most recent call last):
  File "D:\buildarea\3.6.bolen-windows8\build\lib\test\lock_tests.py", line 38, in task
Unhandled exception in thread started by <function Bunch.__init__.<locals>.task at 0x000000B21066D9B0>
Traceback (most recent call last):
  File "D:\buildarea\3.6.bolen-windows8\build\lib\test\lock_tests.py", line 38, in task
    f()
  File "D:\buildarea\3.6.bolen-windows8\build\lib\test\lock_tests.py", line 917, in f
    f()
  File "D:\buildarea\3.6.bolen-windows8\build\lib\test\lock_tests.py", line 917, in f
    f()
  File "D:\buildarea\3.6.bolen-windows8\build\lib\test\lock_tests.py", line 917, in f
    i = barrier.wait()
  File "D:\buildarea\3.6.bolen-windows8\build\lib\threading.py", line 612, in wait
Unhandled exception in thread started by <function Bunch.__init__.<locals>.task at 0x000000B21066D9B0>
Traceback (most recent call last):
  File "D:\buildarea\3.6.bolen-windows8\build\lib\test\lock_tests.py", line 38, in task
    i = barrier.wait()
  File "D:\buildarea\3.6.bolen-windows8\build\lib\threading.py", line 612, in wait
    self._wait(timeout)
  File "D:\buildarea\3.6.bolen-windows8\build\lib\threading.py", line 652, in _wait
    i = barrier.wait()
  File "D:\buildarea\3.6.bolen-windows8\build\lib\threading.py", line 612, in wait
    f()
  File "D:\buildarea\3.6.bolen-windows8\build\lib\test\lock_tests.py", line 917, in f
    self._wait(timeout)
  File "D:\buildarea\3.6.bolen-windows8\build\lib\threading.py", line 652, in _wait
    raise BrokenBarrierError
threading.BrokenBarrierError
    self._wait(timeout)
  File "D:\buildarea\3.6.bolen-windows8\build\lib\threading.py", line 652, in _wait
    i = barrier.wait()
  File "D:\buildarea\3.6.bolen-windows8\build\lib\threading.py", line 603, in wait
ERROR
test_reset (test.test_threading.BarrierTests) ...     raise BrokenBarrierError
threading.BrokenBarrierError
    self._enter() # Block while the barrier drains.
  File "D:\buildarea\3.6.bolen-windows8\build\lib\threading.py", line 627, in _enter
    raise BrokenBarrierError
threading.BrokenBarrierError
    raise BrokenBarrierError
threading.BrokenBarrierError
ok
test_single_thread (test.test_threading.BarrierTests) ... ok
```


(...)

\======================================================================
ERROR: test_default_timeout (test.test_threading.BarrierTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\buildarea\3.6.bolen-windows8\build\lib\test\lock_tests.py", line 922, in test_default_timeout
    self.run_threads(f)
  File "D:\buildarea\3.6.bolen-windows8\build\lib\test\lock_tests.py", line 751, in run_threads
    f()
  File "D:\buildarea\3.6.bolen-windows8\build\lib\test\lock_tests.py", line 917, in f
    i = barrier.wait()
  File "D:\buildarea\3.6.bolen-windows8\build\lib\threading.py", line 612, in wait
    self._wait(timeout)
  File "D:\buildarea\3.6.bolen-windows8\build\lib\threading.py", line 650, in _wait
    raise BrokenBarrierError
threading.BrokenBarrierError
```

**Comment by pitrou** [comment]
Similar failure on AppVeyor:
https://ci.appveyor.com/project/python/cpython/build/3.7.0a0.5987#L1146
