### ISSUE TITLE
test_eintr.test_sigwaitinfo(): race condition on AMD64 FreeBSD 10.x Shared 3.6

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74505]
BPO | [30320](https://bugs.python.org/issue30320)
--- | :---
Nosy | @vstinner, @vadmium
PRs | <li>python/cpython#1523</li><li>python/cpython#1524</li><li>python/cpython#1532</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-10.17:03:40.361>
created_at = <Date 2017-05-09.16:01:51.763>
labels = ['tests']
title = 'test_eintr.test_sigwaitinfo(): race condition on AMD64 FreeBSD 10.x Shared 3.6'
updated_at = <Date 2017-05-10.17:03:40.360>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-10.17:03:40.360>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-10.17:03:40.361>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-05-09.16:01:51.763>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30320
keywords = []
message_count = 6.0
messages = ['293332', '293361', '293367', '293383', '293405', '293441']
nosy_count = 2.0
nosy_names = ['vstinner', 'martin.panter']
pr_nums = ['1523', '1524', '1532']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30320'
versions = ['Python 3.6']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20FreeBSD%2010.x%20Shared%203.6/builds/129/steps/test/logs/stdio

running: test_eintr (584 sec)
0:16:01 [405/405/1] test_eintr failed
test_all (test.test_eintr.EINTRTests) ... FAIL

\======================================================================
FAIL: test_all (test.test_eintr.EINTRTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/test/test_eintr.py", line 18, in test_all
    script_helper.assert_python_ok("-u", tester)
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/test/support/script_helper.py", line 150, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/test/support/script_helper.py", line 136, in _assert_python
    err))
AssertionError: Process return code is 1
command line: ['/usr/home/buildbot/python/3.6.koobs-freebsd10/build/python', '-X', 'faulthandler', '-I', '-u', '/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/test/eintrdata/eintr_tester.py']
```


stdout:
\---
test_read (__main__.OSEINTRTest) ... ok
test_wait (__main__.OSEINTRTest) ... ok
test_wait3 (__main__.OSEINTRTest) ... ok
test_wait4 (__main__.OSEINTRTest) ... ok
test_waitpid (__main__.OSEINTRTest) ... ok
test_write (__main__.OSEINTRTest) ... ok
test_accept (__main__.SocketEINTRTest) ... ok
test_open (__main__.SocketEINTRTest) ... ok
test_os_open (__main__.SocketEINTRTest) ... ok
test_recv (__main__.SocketEINTRTest) ... ok
test_recvmsg (__main__.SocketEINTRTest) ... ok
test_send (__main__.SocketEINTRTest) ... ok
test_sendall (__main__.SocketEINTRTest) ... ok
test_sendmsg (__main__.SocketEINTRTest) ... ok
test_sleep (__main__.TimeEINTRTest) ... ok
test_sigtimedwait (__main__.SignalEINTRTest) ... ok
test_sigwaitinfo (__main__.SignalEINTRTest) ...
\---

stderr:
\---
Timeout (0:10:00)!
Thread 0x0000000802006400 (most recent call first):
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/test/eintrdata/eintr_tester.py", line 422 in test_sigwaitinfo
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/unittest/case.py", line 601 in run
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/unittest/case.py", line 649 in \_\_call__
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/unittest/suite.py", line 122 in run
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/unittest/suite.py", line 84 in \_\_call__
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/unittest/suite.py", line 122 in run
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/unittest/suite.py", line 84 in \_\_call__
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/unittest/runner.py", line 176 in run
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/test/support/__init__.py", line 1889 in \_run_suite
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/test/support/__init__.py", line 1923 in run_unittest
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/test/eintrdata/eintr_tester.py", line 492 in test_main
  File "/usr/home/buildbot/python/3.6.koobs-freebsd10/build/Lib/test/eintrdata/eintr_tester.py", line 496 in \<module\>
\---

\----------------------------------------------------------------------
Ran 1 test in 607.847s

FAILED (failures=1)
test test_eintr failed

**Comment by vstinner** [comment]
I checked manually in my FreeBSD CURRENT VM that:

* sigwaitinfo() and sigtimedwait() fail with EINTR and automatically restart the interrupted syscall
* running the test in a loop doesn't fail: I ran the test during 5 min in 10 shells (tests running 10 times in parallel) =\> no failure, the race condition seems to be gone. I hacked the test file to only run the sigwaitinfo() and sigtimedwait() unit tests.

**Comment by vstinner** [comment]
New changeset 211a392cc15f9a7b1b8ce65d8f6c9f8237d1b77f by Victor Stinner in branch 'master':
bpo-30320: test_eintr now uses pthread_sigmask() (bpo-1523)
https://github.com/python/cpython/commit/211a392cc15f9a7b1b8ce65d8f6c9f8237d1b77f

**Comment by vstinner** [comment]
New changeset 81ed53784608d44a8d196ad52288b55c7bf665db by Victor Stinner in branch '3.6':
bpo-30320: test_eintr now uses pthread_sigmask() (bpo-1523) (bpo-1524)
https://github.com/python/cpython/commit/81ed53784608d44a8d196ad52288b55c7bf665db

**Comment by vstinner** [comment]
New changeset dab10f4f5b52c6de1aac3a8b5dc87d2eb0223a6c by Victor Stinner in branch '3.5':
[3.5] bpo-30320, bpo-25277: backport test_eintr enhancements from master to 3.5 (bpo-1532)
https://github.com/python/cpython/commit/dab10f4f5b52c6de1aac3a8b5dc87d2eb0223a6c

**Comment by vstinner** [comment]
The bug occurs randomly, since it's hard to say at this point if my change fixes it for real or not. I close the bug, but will reopen it if the bug occurs again.

But I'm confident that blocking the signal is "the right fix" for such unit test.
