### ISSUE TITLE
[Windows] support.rmtree() should retry on WindowsError: [Error 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74519]
BPO | [30334](https://bugs.python.org/issue30334)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @jkloth, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-11.00:42:32.576>
created_at = <Date 2017-05-10.15:50:11.103>
labels = ['tests', 'OS-windows']
title = '[Windows] support.rmtree() should retry on WindowsError: [Error 32] The process cannot access the file because it is being used by another process'
updated_at = <Date 2017-05-11.00:42:32.575>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-11.00:42:32.575>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-11.00:42:32.576>
closer = 'vstinner'
components = ['Tests', 'Windows']
creation = <Date 2017-05-10.15:50:11.103>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30334
keywords = []
message_count = 5.0
messages = ['293428', '293429', '293432', '293433', '293467']
nosy_count = 6.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'jkloth', 'zach.ware', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30334'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
test_startfile uses a weak time.sleep(0.1) to wait until the process started by os.startfile() completes. Instead of a sleep, can't support.rmtree() retry on "WindowsError: [Error 32] The process cannot access the file because it is being used by another process" error? For example, retry every 100 ms during 10 seconds?

It's easy to reproduce the bug on Python 2.7: just remove the time.sleep() call in tests.

http://buildbot.python.org/all/builders/x86%20Windows7%202.7/builds/145/steps/test/logs/stdio

0:23:42 [363/402/1] test_startfile crashed

```pytb
[1, 5.638000011444092]
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\2.7.bolen-windows7\build\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\cygwin\home\db3l\buildarea\2.7.bolen-windows7\build\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\cygwin\home\db3l\buildarea\2.7.bolen-windows7\build\lib\test\regrtest.py", line 1877, in <module>
    main_in_temp_cwd()
  File "D:\cygwin\home\db3l\buildarea\2.7.bolen-windows7\build\lib\test\regrtest.py", line 1864, in main_in_temp_cwd
    main()
  File "D:\cygwin\home\db3l\buildarea\2.7.bolen-windows7\build\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\cygwin\home\db3l\buildarea\2.7.bolen-windows7\build\lib\test\support\__init__.py", line 769, in temp_cwd
    rmtree(name)
  File "D:\cygwin\home\db3l\buildarea\2.7.bolen-windows7\build\lib\test\support\__init__.py", line 293, in rmtree
    _rmtree(path)
  File "D:\cygwin\home\db3l\buildarea\2.7.bolen-windows7\build\lib\test\support\__init__.py", line 249, in _rmtree
    _waitfor(lambda p: _force_run(p, os.rmdir, p), path)
  File "D:\cygwin\home\db3l\buildarea\2.7.bolen-windows7\build\lib\test\support\__init__.py", line 202, in _waitfor
    func(pathname)
  File "D:\cygwin\home\db3l\buildarea\2.7.bolen-windows7\build\lib\test\support\__init__.py", line 249, in <lambda>
    _waitfor(lambda p: _force_run(p, os.rmdir, p), path)
  File "D:\cygwin\home\db3l\buildarea\2.7.bolen-windows7\build\lib\test\support\__init__.py", line 197, in _force_run
    return func(*args)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'D:\\cygwin\\home\\db3l\\buildarea\\2.7.bolen-windows7\\build\\build\\test_python_2944'
```


--

If it's too complex to implement a retry (too complex? really?), an obvious hack is to increase the sleep in test_startfile.py from 100 ms to 200 ms...

**Comment by vstinner** [comment]
For a very generic "retry" library, see https://pypi.python.org/pypi/tenacity

But I don't think that we need such advanced library, a simple loop should do the trick ;-)

**Comment by jkloth** [comment]
See http://bugs.python.org/issue15526

**Comment by vstinner** [comment]
> See http://bugs.python.org/issue15526

Oh, thanks for the hint :-)

I proposed a "backport" (modified for 2.7): https://github.com/python/cpython/pull/1537

**Comment by vstinner** [comment]
My following backport fixed test_startfile on x86 Windows7 3.x, so I close the issue.

New changeset 3837d9797c14c13d170256143c841d29645e772a by Victor Stinner in branch '2.7':
bpo-15526: test_startfile changes the cwd (bpo-1537)
https://github.com/python/cpython/commit/3837d9797c14c13d170256143c841d29645e772a
