### ISSUE TITLE
test_ssl.test_connect_with_context(): ConnectionResetError on AMD64 FreeBSD 9.x 3.6

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74513]
BPO | [30328](https://bugs.python.org/issue30328)
--- | :---
Nosy | @vstinner
Superseder | <li>bpo-30319: Change socket.close() to ignore ECONNRESET</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-04.14:50:02.031>
created_at = <Date 2017-05-10.12:24:06.528>
labels = ['tests']
title = 'test_ssl.test_connect_with_context(): ConnectionResetError on AMD64 FreeBSD 9.x 3.6'
updated_at = <Date 2017-07-04.14:50:02.030>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-04.14:50:02.030>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-04.14:50:02.031>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-05-10.12:24:06.528>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30328
keywords = ['buildbot']
message_count = 4.0
messages = ['293408', '293824', '297038', '297661']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30319'
type = None
url = 'https://bugs.python.org/issue30328'
versions = ['Python 3.6']
```

</p></details>

**Comment by vstinner** [comment]
See also bpo-30315 (test_ftplib) and bpo-30319 (test_imaplib).

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%209.x%203.6/builds/131/steps/test/logs/stdio

```pytb
test_connect_with_context (test.test_ssl.SimpleBackgroundTests) ...  server:  new connection from ('127.0.0.1', 53510)
 server: connection cipher is now ('ECDHE-RSA-AES256-SHA', 'TLSv1/SSLv3', 256)
 server: selected protocol is now None
Test server failure:
Traceback (most recent call last):
   File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/test/test_ssl.py", line 1944, in run
    self.close()
   File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/test/test_ssl.py", line 1919, in close
    self.sslconn.close()
   File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/socket.py", line 417, in close
    self._real_close()
   File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/ssl.py", line 1052, in _real_close
    socket._real_close(self)
   File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/socket.py", line 411, in _real_close
    _ss.close(self)
 ConnectionResetError: [Errno 54] Connection reset by peer
ERROR
```


...

\======================================================================
ERROR: test_connect_with_context (test.test_ssl.SimpleBackgroundTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/test/test_ssl.py", line 1541, in test_connect_with_context
    s.connect(self.server_addr)
  File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/ssl.py", line 1093, in connect
    self._real_connect(addr, False)
  File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/ssl.py", line 1084, in _real_connect
    self.do_handshake()
  File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer
```


----------------------------------------------------------------------
Ran 127 tests in 12.751s

FAILED (errors=1, skipped=7)
test test_ssl failed

**Comment by vstinner** [comment]
SimpleBackgroundTests uses a server running in a different thread, so running locally. The port is binded by support.bind_port(socket, "127.0.0.1").

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20FreeBSD%209.x%203.6/builds/137/steps/test/logs/stdio

\======================================================================
ERROR: test_connect_with_context (test.test_ssl.SimpleBackgroundTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/test/test_ssl.py", line 1541, in test_connect_with_context
    s.connect(self.server_addr)
  File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/ssl.py", line 1093, in connect
    self._real_connect(addr, False)
  File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/ssl.py", line 1084, in _real_connect
    self.do_handshake()
  File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/home/buildbot/python/3.6.koobs-freebsd9/build/Lib/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer
```

**Comment by vstinner** [comment]
Duplicate of bpo-30319.
