### ISSUE TITLE
test_socket.test_idna(): socket.gaierror: [Errno 11001] getaddrinfo failed on AMD64 Windows10 3.6

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74515]
BPO | [30330](https://bugs.python.org/issue30330)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-03.13:28:43.713>
created_at = <Date 2017-05-10.12:28:02.684>
labels = ['tests', 'OS-windows']
title = 'test_socket.test_idna(): socket.gaierror: [Errno 11001] getaddrinfo failed on AMD64 Windows10 3.6'
updated_at = <Date 2017-07-03.13:28:43.712>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-03.13:28:43.712>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-03.13:28:43.713>
closer = 'vstinner'
components = ['Tests', 'Windows']
creation = <Date 2017-05-10.12:28:02.684>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30330
keywords = ['buildbot']
message_count = 4.0
messages = ['293412', '293413', '293436', '297582']
nosy_count = 5.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30330'
versions = ['Python 3.6']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20Windows10%203.6/builds/356/steps/test/logs/stdio

\======================================================================
ERROR: test_idna (test.test_socket.GeneralModuleTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\buildarea\3.6.bolen-windows10\build\lib\test\test_socket.py", line 1359, in test_idna
    socket.getaddrinfo(domain,0,socket.AF_UNSPEC,socket.SOCK_STREAM)
  File "D:\buildarea\3.6.bolen-windows10\build\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

----------------------------------------------------------------------

**Comment by vstinner** [comment]
In the same build, a retry of the DNS request later succeeded:

test_idna (test.test_socket.GeneralModuleTests) ... ok

**Comment by vstinner** [comment]
I checked the last 50 builds of AMD64 Windows10 3.5, AMD64 Windows10 3.6 and AMD64 Windows10 3.x (total: 150 builds): the bug only occurred once.

http://buildbot.python.org/all/builders/AMD64%20Windows10%203.6/builds/356/

**Comment by vstinner** [comment]
I didn't see this failure recently, so I consider that it was a DNS failure which only occurred once :-/
