### ISSUE TITLE
test_multiprocessing_forkserver: poll() failed on AMD64 FreeBSD CURRENT Non-Debug 3.5

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74518]
BPO | [30333](https://bugs.python.org/issue30333)
--- | :---
Nosy | @vstinner, @koobs, @applio

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-30.16:36:06.017>
created_at = <Date 2017-05-10.15:24:33.687>
labels = ['tests']
title = 'test_multiprocessing_forkserver: poll() failed on AMD64 FreeBSD CURRENT Non-Debug 3.5'
updated_at = <Date 2017-10-30.16:36:06.016>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-30.16:36:06.016>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-30.16:36:06.017>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-05-10.15:24:33.687>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30333
keywords = []
message_count = 3.0
messages = ['293426', '293809', '305238']
nosy_count = 3.0
nosy_names = ['vstinner', 'koobs', 'davin']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30333'
versions = ['Python 3.5']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Non-Debug%203.5/builds/97/steps/test/logs/stdio

test_connection (test.test_multiprocessing_forkserver.WithThreadsTestConnection) ... FAIL

...

Dangling threads: {\<DummyProcess(Thread-110, started daemon 34437426432)\>}

\======================================================================
FAIL: test_connection (test.test_multiprocessing_forkserver.WithThreadsTestConnection)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.5.koobs-freebsd-current.nondebug/build/Lib/test/_test_multiprocessing.py", line 2359, in test_connection
    self.assertEqual(poll(TIMEOUT1), True)
AssertionError: False != True
```


----------------------------------------------------------------------
Ran 272 tests in 124.653s

FAILED (failures=1, skipped=16)
Warning -- threading.\_dangling was modified by test_multiprocessing_forkserver
  Before: \<_weakrefset.WeakSet object at 0x80493d080\>
  After:  \<_weakrefset.WeakSet object at 0x804956160\> 
test test_multiprocessing_forkserver failed[105/398/1] test_multiprocessing_forkserver

**Comment by vstinner** [comment]
Other test_multiprocessing_forkserver errors on AMD64 FreeBSD CURRENT Non-Debug 3.6.

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Non-Debug%203.6/builds/150/steps/test/logs/stdio

(...)
test_import (test.test_multiprocessing_forkserver.\_TestImportStar) ... ok
Dangling threads: {\<Thread(Thread-97, started daemon 34452785920)\>}

\======================================================================
FAIL: test_active_children (test.test_multiprocessing_forkserver.WithProcessesTestProcess)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.6.koobs-freebsd-current.nondebug/build/Lib/test/_test_multiprocessing.py", line 345, in test_active_children
    self.assertIn(p, self.active_children())
AssertionError: <Process(Process-226, stopped daemon)> not found in []
```


======================================================================
FAIL: test_notify (test.test_multiprocessing_forkserver.WithThreadsTestCondition)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.6.koobs-freebsd-current.nondebug/build/Lib/test/_test_multiprocessing.py", line 886, in test_notify
    self.assertReturnsIfImplemented(1, get_value, woken)
  File "/usr/home/buildbot/python/3.6.koobs-freebsd-current.nondebug/build/Lib/test/_test_multiprocessing.py", line 165, in assertReturnsIfImplemented
    return self.assertEqual(value, res)
AssertionError: 1 != 0
```


----------------------------------------------------------------------
Ran 277 tests in 92.148s

FAILED (failures=2, skipped=16)
Warning -- threading.\_dangling was modified by test_multiprocessing_forkserver
  Before: \<_weakrefset.WeakSet object at 0x805771518\>
  After:  \<_weakrefset.WeakSet object at 0x8009c6cf8\> 
test test_multiprocessing_forkserver failed

**Comment by vstinner** [comment]
I didn't see this bug recently. I fixed many bugs in the meanwhile, so maybe I fixed the bug?

See for example https://haypo.github.io/contrib-cpython-2017q3-part2.html
