### ISSUE TITLE
test_multiprocessing_main_handling: "RuntimeError: Timed out waiting for results" on x86 Windows7 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74524]
BPO | [30339](https://bugs.python.org/issue30339)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @jkloth, @zware, @zooba, @matrixise, @applio, @miss-islington
PRs | <li>python/cpython#1593</li><li>python/cpython#1978</li><li>python/cpython#7972</li><li>python/cpython#7973</li><li>python/cpython#7976</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-06-27.21:40:46.839>
created_at = <Date 2017-05-11.00:48:18.894>
labels = ['3.7', 'tests', 'OS-windows']
title = 'test_multiprocessing_main_handling: "RuntimeError: Timed out waiting for results" on x86 Windows7 3.x'
updated_at = <Date 2018-06-27.21:40:46.837>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-27.21:40:46.837>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-06-27.21:40:46.839>
closer = 'vstinner'
components = ['Tests', 'Windows']
creation = <Date 2017-05-11.00:48:18.894>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30339
keywords = ['patch']
message_count = 16.0
messages = ['293470', '293720', '293807', '293904', '294167', '294950', '295310', '296313', '296954', '297818', '305947', '311671', '320608', '320619', '320622', '320629']
nosy_count = 9.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'jkloth', 'zach.ware', 'steve.dower', 'matrixise', 'davin', 'miss-islington']
pr_nums = ['1593', '1978', '7972', '7973', '7976']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30339'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86%20Windows7%203.x/builds/597/steps/test/logs/stdio

0:26:29 [156/405/1] test_multiprocessing_main_handling failed
...
test_zipfile_compiled (test.test_multiprocessing_main_handling.ForkServerCmdLineTest) ... skipped "'forkserver' start method not available"
test_basic_script (test.test_multiprocessing_main_handling.SpawnCmdLineTest) ... ok
test_basic_script_no_suffix (test.test_multiprocessing_main_handling.SpawnCmdLineTest) ... FAIL
test_directory (test.test_multiprocessing_main_handling.SpawnCmdLineTest) ... ok
test_directory_compiled (test.test_multiprocessing_main_handling.SpawnCmdLineTest) ... ok
test_ipython_workaround (test.test_multiprocessing_main_handling.SpawnCmdLineTest) ... ok
...

\======================================================================
FAIL: test_basic_script_no_suffix (test.test_multiprocessing_main_handling.SpawnCmdLineTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\test_multiprocessing_main_handling.py", line 169, in test_basic_script_no_suffix
    self._check_script(script_name)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\test_multiprocessing_main_handling.py", line 157, in _check_script
    rc, out, err = assert_python_ok(*run_args, __isolated=False)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\support\script_helper.py", line 147, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\support\script_helper.py", line 133, in _assert_python
    err))
AssertionError: Process return code is 1
command line: ['D:\\cygwin\\home\\db3l\\buildarea\\3.x.bolen-windows7\\build\\PCbuild\\win32\\python_d.exe', '-X', 'faulthandler', '-E', 'd:\\temp\\tmp3iu335w1\\script', 'spawn']
```


stdout:
\---

\---

stderr:
\---
```pytb
Traceback (most recent call last):
```


  File "d:\\temp\\tmp3iu335w1\\script", line 34, in \<module\>

    raise RuntimeError("Timed out waiting for results")

RuntimeError: Timed out waiting for results
\---

\----------------------------------------------------------------------
Ran 39 tests in 81.399s

FAILED (failures=1, skipped=26)
test test_multiprocessing_main_handling failed

**Comment by vstinner** [comment]
New changeset 7d6320ba47a229543acc0af6a64bc4e414932273 by Victor Stinner in branch 'master':
bpo-30339: test_multiprocessing_main_handling timeout (bpo-1593)
https://github.com/python/cpython/commit/7d6320ba47a229543acc0af6a64bc4e414932273

**Comment by vstinner** [comment]
> New changeset 7d6320ba47a229543acc0af6a64bc4e414932273 by Victor Stinner in branch 'master':
> bpo-30339: test_multiprocessing_main_handling timeout (bpo-1593)
> https://github.com/python/cpython/commit/7d6320ba47a229543acc0af6a64bc4e414932273

Sadly, a new build failed at commit fca224f117d25bdfec1bf7160b67438c4fcf6dee, so with the new timeout of 60 seconds:
http://buildbot.python.org/all/builders/x86%20Windows7%203.x/builds/619/steps/test/logs/stdio

**Comment by vstinner** [comment]
Another failure on AMD64 Windows7 SP1 3.5:
http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%203.5/builds/145/steps/test/logs/stdio

\======================================================================
FAIL: test_directory (test.test_multiprocessing_main_handling.SpawnCmdLineTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\test_multiprocessing_main_handling.py", line 197, in test_directory
    self._check_script(script_dir)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\test_multiprocessing_main_handling.py", line 155, in _check_script
    rc, out, err = assert_python_ok(*run_args, __isolated=False)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\support\script_helper.py", line 150, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\support\script_helper.py", line 136, in _assert_python
    err))
AssertionError: Process return code is 1
command line: ['C:\\buildbot.python.org\\3.5.kloth-win64\\build\\PCbuild\\amd64\\python_d.exe', '-X', 'faulthandler', '-E', 'C:\\Users\\Buildbot\\AppData\\Local\\Temp\\tmpld1_lj4t', 'spawn']
```


stdout:
\---

\---

stderr:
\---
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Buildbot\AppData\Local\Temp\tmpld1_lj4t\__main__.py", line 23, in <module>
    raise RuntimeError("Timed out waiting for results")
RuntimeError: Timed out waiting for results
```
---

**Comment by applio** [comment]
Patch on bpo-30317 also addresses this issue in a more flexible way.

**Comment by vstinner** [comment]
New failure:

http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%203.5/builds/161/steps/test/logs/stdio


\======================================================================
FAIL: test_directory (test.test_multiprocessing_main_handling.SpawnCmdLineTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\test_multiprocessing_main_handling.py", line 197, in test_directory
    self._check_script(script_dir)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\test_multiprocessing_main_handling.py", line 155, in _check_script
    rc, out, err = assert_python_ok(*run_args, __isolated=False)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\support\script_helper.py", line 150, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\support\script_helper.py", line 136, in _assert_python
    err))
AssertionError: Process return code is 1
command line: ['C:\\buildbot.python.org\\3.5.kloth-win64\\build\\PCbuild\\amd64\\python_d.exe', '-X', 'faulthandler', '-E', 'C:\\Users\\Buildbot\\AppData\\Local\\Temp\\tmpa4gpo3nq', 'spawn']
```


stdout:
\---

\---

stderr:
\---
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Buildbot\AppData\Local\Temp\tmpa4gpo3nq\__main__.py", line 23, in <module>
    raise RuntimeError("Timed out waiting for results")
RuntimeError: Timed out waiting for results
```
---

**Comment by jkloth** [comment]
Added [PR1978](https://github.com/python/cpython/pull/1978) that resolves this issue on my buildbot at least.  Note that it is against 3.5 as that is the branch that has the issue, it seems.

I'm guessing improvements in startup time on newer Pythons is why it doesn't occur for them.

**Comment by jkloth** [comment]
Following up as the last run on my 3.5 buildslave:
  http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%203.5/builds/198
had the timeout again.  It is running at a 50% success rate with the only fault being warnings/errors due to this test.

**Comment by vstinner** [comment]
Similar but difference issue.

http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%203.5/builds/215/steps/test/logs/stdio

\======================================================================
FAIL: test_directory_compiled (test.test_multiprocessing_main_handling.SpawnCmdLineTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\test_multiprocessing_main_handling.py", line 207, in test_directory_compiled
    self._check_script(script_dir)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\test_multiprocessing_main_handling.py", line 155, in _check_script
    rc, out, err = assert_python_ok(*run_args, __isolated=False)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\support\script_helper.py", line 150, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\support\script_helper.py", line 136, in _assert_python
    err))
AssertionError: Process return code is 1
command line: ['C:\\buildbot.python.org\\3.5.kloth-win64\\build\\PCbuild\\amd64\\python_d.exe', '-X', 'faulthandler', '-E', 'C:\\Users\\Buildbot\\AppData\\Local\\Temp\\tmp47s9eead', 'spawn']
```


stdout:
\---

\---

stderr:
\---
```pytb
Traceback (most recent call last):
```


  File "C:\\buildbot.python.org\\3.5.kloth-win64\\build\\lib\\runpy.py", line 193, in \_run_module_as_main

    "__main__", mod_spec)

  File "C:\\buildbot.python.org\\3.5.kloth-win64\\build\\lib\\runpy.py", line 85, in \_run_code

```py
    exec(code, run_globals)
```


  File "C:\\Users\\Buildbot\\AppData\\Local\\Temp\\tmp47s9eead\\__main__.py", line 23, in \<module\>

RuntimeError: Timed out waiting for results
\---


Second run:


\======================================================================
FAIL: test_directory (test.test_multiprocessing_main_handling.SpawnCmdLineTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\test_multiprocessing_main_handling.py", line 197, in test_directory
    self._check_script(script_dir)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\test_multiprocessing_main_handling.py", line 155, in _check_script
    rc, out, err = assert_python_ok(*run_args, __isolated=False)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\support\script_helper.py", line 150, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\support\script_helper.py", line 136, in _assert_python
    err))
AssertionError: Process return code is 1
command line: ['C:\\buildbot.python.org\\3.5.kloth-win64\\build\\PCbuild\\amd64\\python_d.exe', '-X', 'faulthandler', '-E', 'C:\\Users\\Buildbot\\AppData\\Local\\Temp\\tmp3hfxysdu', 'spawn']
```


stdout:
\---

\---

stderr:
\---
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Buildbot\AppData\Local\Temp\tmp3hfxysdu\__main__.py", line 23, in <module>
    raise RuntimeError("Timed out waiting for results")
RuntimeError: Timed out waiting for results
---


```
======================================================================
FAIL: test_directory_compiled (test.test_multiprocessing_main_handling.SpawnCmdLineTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\test_multiprocessing_main_handling.py", line 207, in test_directory_compiled
    self._check_script(script_dir)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\test_multiprocessing_main_handling.py", line 155, in _check_script
    rc, out, err = assert_python_ok(*run_args, __isolated=False)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\support\script_helper.py", line 150, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\support\script_helper.py", line 136, in _assert_python
    err))
AssertionError: Process return code is 1
command line: ['C:\\buildbot.python.org\\3.5.kloth-win64\\build\\PCbuild\\amd64\\python_d.exe', '-X', 'faulthandler', '-E', 'C:\\Users\\Buildbot\\AppData\\Local\\Temp\\tmpvez1m7b1', 'spawn']
```


stdout:
\---

\---

stderr:
\---
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Buildbot\AppData\Local\Temp\tmpvez1m7b1\__main__.py", line 23, in <module>
RuntimeError: Timed out waiting for results
```
---

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%203.5/builds/229/steps/test/logs/stdio


\======================================================================
FAIL: test_directory (test.test_multiprocessing_main_handling.SpawnCmdLineTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\test_multiprocessing_main_handling.py", line 197, in test_directory
    self._check_script(script_dir)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\test_multiprocessing_main_handling.py", line 155, in _check_script
    rc, out, err = assert_python_ok(*run_args, __isolated=False)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\support\script_helper.py", line 150, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\test\support\script_helper.py", line 136, in _assert_python
    err))
AssertionError: Process return code is 1
command line: ['C:\\buildbot.python.org\\3.5.kloth-win64\\build\\PCbuild\\amd64\\python_d.exe', '-X', 'faulthandler', '-E', 'C:\\Users\\Buildbot\\AppData\\Local\\Temp\\tmp7w5hs4kq', 'spawn']
```


stdout:
\---

\---

stderr:
\---
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\buildbot.python.org\3.5.kloth-win64\build\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Buildbot\AppData\Local\Temp\tmp7w5hs4kq\__main__.py", line 23, in <module>
    raise RuntimeError("Timed out waiting for results")
RuntimeError: Timed out waiting for results
```
---

**Comment by vstinner** [comment]
Yet another similar bug on "x86 Windows7 3.x":

http://buildbot.python.org/all/#/builders/58/builds/134

\======================================================================
FAIL: test_ipython_workaround (test.test_multiprocessing_main_handling.SpawnCmdLineTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\test_multiprocessing_main_handling.py", line 179, in test_ipython_workaround
    self._check_script(script_name)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\test_multiprocessing_main_handling.py", line 156, in _check_script
    rc, out, err = assert_python_ok(*run_args, __isolated=False)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\support\script_helper.py", line 151, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\support\script_helper.py", line 137, in _assert_python
    res.fail(cmd_line)
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\support\script_helper.py", line 79, in fail
    err))
AssertionError: Process return code is 1
command line: ['D:\\cygwin\\home\\db3l\\buildarea\\3.x.bolen-windows7\\build\\PCbuild\\win32\\python_d.exe', '-X', 'faulthandler', '-E', 'd:\\temp\\tmponku8v2m\\ipython.py', 'spawn']
```


stdout:
\---

\---

stderr:
\---
```pytb
Traceback (most recent call last):
```


  File "d:\\temp\\tmponku8v2m\\ipython.py", line 23, in \<module\>

    raise RuntimeError("Timed out waiting for results")

RuntimeError: Timed out waiting for results
\---
