### ISSUE TITLE
test_multiprocessing.test_notify_all(): AssertionError: 6 != 5 on x86 Windows XP 2.7

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74529]
BPO | [30344](https://bugs.python.org/issue30344)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @zooba, @applio
PRs | <li>python/cpython#1591</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-15.15:33:31.087>
created_at = <Date 2017-05-11.14:36:47.251>
labels = ['tests', 'OS-windows']
title = 'test_multiprocessing.test_notify_all(): AssertionError: 6 != 5 on x86 Windows XP 2.7'
updated_at = <Date 2017-05-15.15:33:31.085>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-15.15:33:31.085>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-15.15:33:31.087>
closer = 'vstinner'
components = ['Tests', 'Windows']
creation = <Date 2017-05-11.14:36:47.251>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30344
keywords = ['buildbot']
message_count = 5.0
messages = ['293496', '293542', '293703', '293711', '293715']
nosy_count = 6.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'steve.dower', 'davin']
pr_nums = ['1591']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30344'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86%20Windows%20XP%202.7/builds/150/steps/test/logs/stdio

0:19:29 [214/402/1] test_multiprocessing crashed -- running: test_mmap (43 sec)

```pytb
[0, 0.0]
[76985 refs]
test test_multiprocessing failed -- Traceback (most recent call last):
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\test\test_multiprocessing.py", line 844, in test_notify_all
    self.assertReturnsIfImplemented(6, get_value, woken)
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\test\test_multiprocessing.py", line 149, in assertReturnsIfImplemented
    return self.assertEqual(value, res)
AssertionError: 6 != 5

Traceback (most recent call last):
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\test\regrtest.py", line 1882, in <module>
    main_in_temp_cwd()
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\test\regrtest.py", line 1869, in main_in_temp_cwd
    main()
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\test\support\__init__.py", line 769, in temp_cwd
    rmtree(name)
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\test\support\__init__.py", line 293, in rmtree
    _rmtree(path)
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\test\support\__init__.py", line 249, in _rmtree
    _waitfor(lambda p: _force_run(p, os.rmdir, p), path)
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\test\support\__init__.py", line 202, in _waitfor
    func(pathname)
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\test\support\__init__.py", line 249, in <lambda>
    _waitfor(lambda p: _force_run(p, os.rmdir, p), path)
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\test\support\__init__.py", line 197, in _force_run
    return func(*args)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'd:\\cygwin\\home\\db3l\\buildarea\\2.7.bolen-windows\\build\\build\\test_python_2512'
```

**Comment by vstinner** [comment]
Also failed on:
http://buildbot.python.org/all/builders/x86%20Windows%20XP%20VS9.0%202.7/builds/147/steps/test/logs/stdio

**Comment by vstinner** [comment]
New fail on x86 Windows XP VS9.0 2.7:
http://buildbot.python.org/all/builders/x86%20Windows%20XP%20VS9.0%202.7/builds/153/steps/test/logs/stdio

**Comment by vstinner** [comment]
I created https://github.com/python/cpython/pull/1591 : backport bpo-11790 to 2.7.

**Comment by vstinner** [comment]
I pushed my backport. Since the bug occurs randomly, I consider that it's now fixed and I close the issue. I may reopen if the bug reappears.

New changeset 9d1983be503012e750f49d31b569f3fe4554c628 by Victor Stinner in branch '2.7':
bpo-11790: Fix sporadic failures in test_multiprocessing.WithProcessesTestCondition. (bpo-1591)
https://github.com/python/cpython/commit/9d1983be503012e750f49d31b569f3fe4554c628
