### ISSUE TITLE
traceback.TracebackException.format shouldn't format_exc_only() when __traceback__ is None

### ISSUE THREAD

**Issue by 6fd3d553-ff50-40bd-a9a1-836658cb1a33** [python/cpython#74569]
BPO | [30384](https://bugs.python.org/issue30384)
--- | :---
Nosy | @asmeurer, @asmeurer, @iritkatriel
Files | <li>[test.py](https://bugs.python.org/file46867/test.py "Uploaded as text/plain at 2017-05-17.04:03:34 by @asmeurer")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-11-04.22:24:47.968>
created_at = <Date 2017-05-17.04:03:35.270>
labels = ['invalid', 'library']
title = "traceback.TracebackException.format shouldn't format_exc_only() when __traceback__ is None"
updated_at = <Date 2020-11-05.00:38:20.286>
user = 'https://github.com/asmeurer'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-05.00:38:20.286>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2020-11-04.22:24:47.968>
closer = 'iritkatriel'
components = ['Library (Lib)']
creation = <Date 2017-05-17.04:03:35.270>
creator = 'Aaron.Meurer'
dependencies = []
files = ['46867']
hgrepos = []
issue_num = 30384
keywords = []
message_count = 11.0
messages = ['293837', '380336', '380359', '380360', '380361', '380364', '380367', '380369', '380372', '380383', '380385']
nosy_count = 3.0
nosy_names = ['Aaron.Meurer', 'asmeurer', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30384'
versions = []
```

</p></details>

**Comment by 6fd3d553-ff50-40bd-a9a1-836658cb1a33** [comment]
I'm trying to completely hide an exception from the traceback module. From reading the source, it looks like the only way to do this is to set \_\_traceback__ to None (I can also set \_\_suppress_context__ to True, but that only works if I have another exception higher up in the context chain). 

However, this still prints the traceback itself, and the line for SyntaxErrors. Consider the attached test.py. It outputs

ValueError

```pytb
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    raise TypeError
TypeError
```


  File "\<string\>", line 1
    a b
      ^
SyntaxError: unexpected EOF while parsing

```pytb
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    raise TypeError
TypeError
```


I suppose it should also not print the "During handling of the above exception, another exception occurred:" part.
