### ISSUE TITLE
multiprocessing Array create for ctypes.c_char, TypeError unless 1 char string arg used

### ISSUE THREAD

**Issue by 91313bfa-ca3f-4e3d-b479-8570092cf00a** [python/cpython#74564]
BPO | [30379](https://bugs.python.org/issue30379)
--- | :---
Nosy | @applio, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-06-18.21:34:39.124>
created_at = <Date 2017-05-16.14:58:51.161>
labels = ['type-bug', 'invalid']
title = 'multiprocessing Array create for ctypes.c_char, TypeError unless 1 char string arg used'
updated_at = <Date 2021-06-18.21:34:39.123>
user = 'https://bugs.python.org/jgschaefer'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-18.21:34:39.123>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-06-18.21:34:39.124>
closer = 'iritkatriel'
components = []
creation = <Date 2017-05-16.14:58:51.161>
creator = 'jgschaefer'
dependencies = []
files = []
hgrepos = []
issue_num = 30379
keywords = []
message_count = 4.0
messages = ['293765', '293766', '293767', '396099']
nosy_count = 3.0
nosy_names = ['davin', 'jgschaefer', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30379'
versions = ['Python 2.7']
```

</p></details>

**Comment by 91313bfa-ca3f-4e3d-b479-8570092cf00a** [comment]
When creating a multiprocessing Array equivalent for unsigned chars, eg from a numpy.uint8 array, the first argument: typecode_or_type must be specified as a one character string, if a typecode is used the method raises a TypeError.

```pycon
>>> import numpy as np, multiprocessing as mp, ctypes
>>> arr = np.array(range(10), dtype=np.uint8)
>>> arr
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)
>>> mp.Array("B", arr)
<SynchronizedArray wrapper for <multiprocessing.sharedctypes.c_ubyte_Array_10 object
>>> mp.Array(ctypes.c_char, arr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 260, in Array
    return Array(typecode_or_type, size_or_initializer, **kwds)
  File "/usr/lib/python2.7/multiprocessing/sharedctypes.py", line 120, in Array
    obj = RawArray(typecode_or_type, size_or_initializer)
  File "/usr/lib/python2.7/multiprocessing/sharedctypes.py", line 94, in RawArray
    result.__init__(*size_or_initializer)
TypeError: one character string expected

This contrasts with behavior exhibited with other types:
>>> farr = np.array(range(10), dtype=np.float)
>>> mp.Array(ctypes.c_double, farr)
<SynchronizedArray wrapper...
```


thanks, John

**Comment by applio** [comment]
Maybe I missed your point but why would you not want to do this instead?

```pycon
>>> mp.Array(ctypes.c_int8, arr)
<SynchronizedArray wrapper for <multiprocessing.sharedctypes.c_byte_Array_10 object at ...>>
```

**Comment by applio** [comment]
Perhaps I should've used ctypes.c_uint8 in that example/question instead.
