### ISSUE TITLE
Cannot write to a tun interface file

### ISSUE THREAD

**Issue by 492aedd3-e03b-4e4b-81a9-9c8c3ee09707** [python/cpython#74615]
BPO | [30430](https://bugs.python.org/issue30430)
--- | :---
Nosy | @pitrou
Files | <li>[simple_incorrect.py](https://bugs.python.org/file46885/simple_incorrect.py "Uploaded as text/plain at 2017-05-22.12:34:41 by Rémy Léone")</li><li>[simple_incorrect.py](https://bugs.python.org/file46886/simple_incorrect.py "Uploaded as text/plain at 2017-05-22.15:36:01 by Rémy Léone")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-05-22.12:34:41.517>
labels = ['expert-IO']
title = 'Cannot write to a tun interface file'
updated_at = <Date 2017-05-22.15:36:01.391>
user = 'https://bugs.python.org/RmyLone'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-22.15:36:01.391>
actor = 'R\xc3\xa9my L\xc3\xa9one'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['IO']
creation = <Date 2017-05-22.12:34:41.517>
creator = 'R\xc3\xa9my L\xc3\xa9one'
dependencies = []
files = ['46885', '46886']
hgrepos = []
issue_num = 30430
keywords = []
message_count = 7.0
messages = ['294143', '294151', '294152', '294154', '294155', '294156', '294158']
nosy_count = 3.0
nosy_names = ['pitrou', 'neologix', 'R\xc3\xa9my L\xc3\xa9one']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue30430'
versions = ['Python 3.5']
```

</p></details>

**Comment by 492aedd3-e03b-4e4b-81a9-9c8c3ee09707** [comment]
I cannot write certain bytes object to a tun interface file. I've added a working and unworking example in the attached file.
I'm running on Ubuntu16.04 with Python 3.5.2

**Comment by pitrou** [comment]
Would you care to post the detailed error and traceback here?  Not everyone wants to set up a TUN interface to try to reproduce :-)

**Comment by 492aedd3-e03b-4e4b-81a9-9c8c3ee09707** [comment]
```pytb
Traceback (most recent call last):
  File "simple_incorrect.py", line 31, in <module>
    tun.write(incorrect_frame)
OSError: [Errno 22] Invalid argument
```

**Comment by 492aedd3-e03b-4e4b-81a9-9c8c3ee09707** [comment]
The question I'm the most interested about is why depending on what the bytes object contains I get a different result. In one case the bytes are written fine to the TUN interface file descriptor and in the other case I get an Errno22. My assumption is that the bytes to write are completely opaque for Python.

My current workaround is mainly to start the bytes I want to send to my tun interface with a non-0 byte.
Something strange that I have also noticed using strace python simple_incorrect.py is that I get EINVAL errors in the second case while I didn't change the mode with which I open the tun.

**Comment by pitrou** [comment]
So basically the write() system call seems to be returning EINVAL.  Can I suggest the following steps:

1. try to reproduce using os.open() and os.write() instead of open() and write() (just to make sure something doesn't get in the way)

2. if it still fails, try to reproduce using an equivalent C snippet

If 2 fails as well, then this is a system issue and not a Python issue.  Otherwise, we'll have to find out how Python differs from C.

**Comment by pitrou** [comment]
I know nothing about TUN but you may simply be hitting this code path:
https://github.com/spotify/linux/blob/master/drivers/net/tun.c#L601-L614

```pycon
Since:
>>> ('e'.encode()[0] & 0xf0) in (0x40, 0x60)
True
>>> ('é'.encode()[0] & 0xf0) in (0x40, 0x60)
False
```


writing 'é'.encode() will hit the EINVAL-returning path.  The bottom line is that TUN devices don't seem to support free-form data, but expect a certain format.

**Comment by 492aedd3-e03b-4e4b-81a9-9c8c3ee09707** [comment]
```pytb
I've tackle the 1. by replacing write/open with os.write/os.open. I still get :
$ python3 simple_incorrect.py
b'\xc3\xa9'
Traceback (most recent call last):
  File "simple_incorrect.py", line 32, in <module>
    os.write(tun, incorrect_frame)
OSError: [Errno 22] Invalid argument
```


I'm going to study more in depth the point you raised about tun.c
