### ISSUE TITLE
FileInput doesn't accept PathLike objects for file names

### ISSUE THREAD

**Issue by b0f82a92-4349-4a2a-bee4-a45118bc9ff6** [python/cpython#74617]
BPO | [30432](https://bugs.python.org/issue30432)
--- | :---
Nosy | @ambv, @rowillia, @arp11
PRs | <li>python/cpython#1732</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-23.05:36:55.708>
created_at = <Date 2017-05-22.18:51:08.616>
labels = ['3.7', 'expert-IO']
title = "FileInput doesn't accept PathLike objects for file names"
updated_at = <Date 2017-05-23.05:36:55.707>
user = 'https://github.com/rowillia'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-23.05:36:55.707>
actor = 'lukasz.langa'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-23.05:36:55.708>
closer = 'lukasz.langa'
components = ['IO']
creation = <Date 2017-05-22.18:51:08.616>
creator = 'Roy Williams'
dependencies = []
files = []
hgrepos = []
issue_num = 30432
keywords = []
message_count = 4.0
messages = ['294169', '294185', '294199', '294224']
nosy_count = 3.0
nosy_names = ['lukasz.langa', 'Roy Williams', 'arp11']
pr_nums = ['1732']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30432'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by b0f82a92-4349-4a2a-bee4-a45118bc9ff6** [comment]
```
from fileinput import FileInput
from pathlib import Path

p = Path('.')
FileInput(p)
```

Results in:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 198, in __init__
    files = tuple(files)
TypeError: 'PosixPath' object is not iterable
```

**Comment by 15acd0e6-bb0d-4f10-a276-cfa4c0fd79f0** [comment]
You seem to be skipping a step, this is nothing to do with FileInput:

```pycon
>>> [n for n in Path('.')]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'PosixPath' object is not iterable

>>> [n for n in Path('.').iterdir()]
[PosixPath('build'), PosixPath('install-sh'), ...]
```


Are you proposing a feature that the Path instance should be implicitly iterable for the directory contents?

**Comment by b0f82a92-4349-4a2a-bee4-a45118bc9ff6** [comment]
@arp11 sorry for the too-minimal repro :D - the issue is with FileInput attempting to cast `files` to a tuple.  Instead, if passed a PathLike object FileInput should set `files` to a tuple just as it does with a str.

**Comment by ambv** [comment]
New changeset 002665a9da3a2924c4a08511ede62ff4d1dabc48 by Łukasz Langa (Roy Williams) in branch 'master':
bpo-30432: FileInput doesn't accept PathLike objects for file names (bpo-1732)
https://github.com/python/cpython/commit/002665a9da3a2924c4a08511ede62ff4d1dabc48
