### ISSUE TITLE
Documentation either unclear or incorrect on comparisons between bytes and strings in Python 3

### ISSUE THREAD

**Issue by f58a9c17-6a37-4b36-8038-42eaf3458d39** [python/cpython#74620]
BPO | [30435](https://bugs.python.org/issue30435)
--- | :---
Nosy | @ipatrol, @vadmium, @eryksun, @Mariatta, @bricsuc

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-05-22.23:32:59.195>
labels = ['type-feature', '3.8', '3.9', '3.10', 'docs']
title = 'Documentation either unclear or incorrect on comparisons between bytes and strings in Python 3'
updated_at = <Date 2021-03-13.03:53:49.482>
user = 'https://github.com/ipatrol'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-13.03:53:49.482>
actor = 'eryksun'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2017-05-22.23:32:59.195>
creator = 'ipatrol'
dependencies = []
files = []
hgrepos = []
issue_num = 30435
keywords = []
message_count = 4.0
messages = ['294200', '294226', '294233', '294267']
nosy_count = 6.0
nosy_names = ['ipatrol', 'docs@python', 'martin.panter', 'eryksun', 'Mariatta', 'Brian Ward']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30435'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by f58a9c17-6a37-4b36-8038-42eaf3458d39** [comment]
https://docs.python.org/3/reference/expressions.html#comparisons says that "Strings and binary sequences cannot be directly compared." That would seem to me to imply that an equality between them would raise an exception, as also claimed by https://wiki.python.org/moin/BytesStr

However, that is manifestly incorrect. Bytes and strings can be compared: they are always unequal. This appears to be a result of the operation falling through to the default comparison, which returns False since they are not identical objects. Equality is a comparison, though it is not an order comparison. A brief search of the word "cannot" in the documentation suggest that saying a certain thing cannot be done usually implies that attempting to do so anyway will raise an exception, typically a TypeError. That this is not the case for string-bytes comparisons should be mentioned.

**Comment by eryksun** [comment]
How about "cannot be compared by value" or "cannot be ordered by value"? Emphasizing the value aspect doesn't conflict with the default equality comparison by identity.

Note that starting Python with the -b option causes the bytes type to raise a warning in this case:

```pycon
    >>> sys.flags.bytes_warning
    1
    >>> 'a'.__eq__(b'a')
    NotImplemented

    >>> b'a'.__eq__('a')
    __main__:1: BytesWarning: Comparison between bytes and string
    NotImplemented
```

**Comment by vadmium** [comment]
Also, “-bb” turns it into an exception, and the same applies to bytes vs int:

```pycon
>>> b"a" == "a"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
BytesWarning: Comparison between bytes and string
>>> b"a" == 0x61
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
BytesWarning: Comparison between bytes and int
```


Perhaps the documentation should say “should not be compared” rather than “cannot”. Or perhaps it should mention “-b”.

Mariatta: I don’t think this is relevant to 2.7. In 2.7, you do get an error with bytearray vs unicode, but bytearray is not discussed in this bit of the Py 2 documentation.

**Comment by 9562d477-4c17-4346-9b04-e98ab6200789** [comment]
The "should" recommendation seems like the right direction, but feels like it needs an explanation (in case someone's trying to run some 2.7 code and is wondering why their comparisons don't work anymore). Unfortunately, it's a little complicated to pile into a section like this. Putting it somewhere else (that includes a reference to -b) might work.

A somewhat related aside is that I've sometimes thought that there ought to be something a little more extensive regarding converting bytes to strings, as it's the kind of thing that can lead you down this road anyway.
