### ISSUE TITLE
[Selenium 3.4.2-geckodriver 0.16.1] Python 3.6.1 unable to initialize webdriver with "marionette" set to True

### ISSUE THREAD

**Issue by e9207e60-4727-426f-80db-ec53adaac990** [python/cpython#74657]
BPO | [30472](https://bugs.python.org/issue30472)
--- | :---
Nosy | @pitrou

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-26.07:38:12.697>
created_at = <Date 2017-05-25.11:23:31.313>
labels = ['build']
title = '[Selenium 3.4.2-geckodriver 0.16.1] Python 3.6.1 unable to initialize webdriver with "marionette" set to True'
updated_at = <Date 2017-05-26.07:38:12.696>
user = 'https://bugs.python.org/debanjan'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-26.07:38:12.696>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-26.07:38:12.697>
closer = 'pitrou'
components = []
creation = <Date 2017-05-25.11:23:31.313>
creator = 'debanjan'
dependencies = []
files = []
hgrepos = []
issue_num = 30472
keywords = []
message_count = 2.0
messages = ['294470', '294535']
nosy_count = 2.0
nosy_names = ['pitrou', 'debanjan']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30472'
versions = ['Python 3.6']
```

</p></details>

**Comment by e9207e60-4727-426f-80db-ec53adaac990** [comment]
Python 3.6.1 unable to initialize webdriver (geckodriver) for Selenium with "marionette" set to True.

Here is my code block written in PyCharm:

```py
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
caps = DesiredCapabilities().FIREFOX
caps["marionette"] = True
driver = webdriver.Firefox(capabilities=caps, executable_path="C:\\Utility\\BrowserDrivers\\geckodriver.exe")
driver.set_page_load_timeout(30)
driver.get("https://www.facebook.com/")
driver.maximize_window()
driver.implicitly_wait(20)
```


```pytb
The error reads as:
C:\Python\python.exe C:/Users/AtechM_03/PycharmProjects/Webinar/SeleniumScripts/MyForthSeleniumScript.py
Traceback (most recent call last):
  File "C:/Users/AtechM_03/PycharmProjects/Webinar/SeleniumScripts/MyForthSeleniumScript.py", line 7, in <module>
    driver = webdriver.Firefox(capabilities=caps, executable_path="C:\\Utility\\BrowserDrivers\\geckodriver.exe")
  File "C:\Python\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 152, in __init__
    keep_alive=True)
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 188, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unable to find a matching set of capabilities
```


When "marionette" set back to False URL open up perfect.

**Comment by pitrou** [comment]
This is the bug tracker for Python itself.  What you're having is an issue with selenium, which is a third-party library.  I recommend you post your issue on the selenium bug tracker instead.
