### ISSUE TITLE
test_timeout fails on AMD64 FreeBSD CURRENT Debug 3.x: ConnectionResetError: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74728]
BPO | [30543](https://bugs.python.org/issue30543)
--- | :---
Nosy | @vstinner
Superseder | <li>bpo-30319: Change socket.close() to ignore ECONNRESET</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-04.14:48:56.650>
created_at = <Date 2017-06-01.21:27:02.870>
labels = ['3.7', 'tests']
title = 'test_timeout fails on AMD64 FreeBSD CURRENT Debug 3.x: ConnectionResetError: [Errno 54] Connection reset by peer'
updated_at = <Date 2017-07-04.14:48:56.649>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-04.14:48:56.649>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-04.14:48:56.650>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-06-01.21:27:02.870>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30543
keywords = ['buildbot']
message_count = 2.0
messages = ['294971', '296739']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30319'
type = None
url = 'https://bugs.python.org/issue30543'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Debug%203.x/builds/350/steps/test/logs/stdio

testAcceptTimeout (test.test_timeout.TCPTimeoutTestCase) ... ok
testConnectTimeout (test.test_timeout.TCPTimeoutTestCase) ... skipped "Resource 'blackhole.snakebite.net' is not available"
testRecvTimeout (test.test_timeout.TCPTimeoutTestCase) ... ok
testSend (test.test_timeout.TCPTimeoutTestCase) ... ERROR
testSendall (test.test_timeout.TCPTimeoutTestCase) ... ok
testSendto (test.test_timeout.TCPTimeoutTestCase) ... ERROR
testRecvfromTimeout (test.test_timeout.UDPTimeoutTestCase) ... test test_timeout failed
ok

\======================================================================
ERROR: testSend (test.test_timeout.TCPTimeoutTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/test_timeout.py", line 151, in tearDown
    self.sock.close()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/socket.py", line 417, in close
    self._real_close()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/socket.py", line 411, in _real_close
    _ss.close(self)
ConnectionResetError: [Errno 54] Connection reset by peer
```


======================================================================
ERROR: testSendto (test.test_timeout.TCPTimeoutTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/test_timeout.py", line 151, in tearDown
    self.sock.close()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/socket.py", line 417, in close
    self._real_close()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/socket.py", line 411, in _real_close
    _ss.close(self)
ConnectionResetError: [Errno 54] Connection reset by peer
```


----------------------------------------------------------------------
Ran 14 tests in 10.084s

FAILED (errors=2, skipped=1)
1 test failed again:
    test_timeout

Total duration: 17 min 14 sec
Tests result: FAILURE

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Debug%203.6/builds/266/steps/test/logs/stdio

\======================================================================
ERROR: testSend (test.test_timeout.TCPTimeoutTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.6.koobs-freebsd-current/build/Lib/test/test_timeout.py", line 151, in tearDown
    self.sock.close()
  File "/usr/home/buildbot/python/3.6.koobs-freebsd-current/build/Lib/socket.py", line 417, in close
    self._real_close()
  File "/usr/home/buildbot/python/3.6.koobs-freebsd-current/build/Lib/socket.py", line 411, in _real_close
    _ss.close(self)
ConnectionResetError: [Errno 54] Connection reset by peer
```
