### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by b6ff01e2-4ed0-4f3e-831a-cfe8e45a6a2e** [python/cpython#74736]
BPO | [30551](https://bugs.python.org/issue30551)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-02.11:29:15.659>
created_at = <Date 2017-06-02.11:06:01.220>
labels = ['build']
title = 'Attribute Error'
updated_at = <Date 2017-06-02.11:29:15.658>
user = 'https://bugs.python.org/Mahira'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-02.11:29:15.658>
actor = 'Mahira'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-02.11:29:15.659>
closer = 'Mahira'
components = []
creation = <Date 2017-06-02.11:06:01.220>
creator = 'Mahira'
dependencies = []
files = []
hgrepos = []
issue_num = 30551
keywords = []
message_count = 2.0
messages = ['295004', '295009']
nosy_count = 1.0
nosy_names = ['Mahira']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30551'
versions = ['Python 3.6']
```

</p></details>

**Comment by b6ff01e2-4ed0-4f3e-831a-cfe8e45a6a2e** [comment]
```pytb
Hai, I am New to python and I am training with some open source projects now am Practising GUI....
I get the Error Message 
 
Traceback (most recent call last):
  File "C:/Users/Mahira/AppData/Local/Programs/Python/Python36/Lib/graphics_setup/Shape Gra Ex.py", line 6, in <module>
    circle.draw("win")
  File "C:/Users/Mahira/AppData/Local/Programs/Python/Python36/Lib/graphics_setup\graphics.py", line 482, in draw
    if graphwin.isClosed(): raise GraphicsError("Can't draw to closed window")
AttributeError: 'str' object has no attribute 'isClosed'
```


And my Program is Following below:
from graphics import *
win=GraphWin('Shapes')
center=Point(100,100)
circle=Circle(center,30)
circle.setFill('red')
circle.draw("win")
label=Text(center,"Red Circle")
label.draw(win)
rect=Rectangle(Point(30,30),Point(70,70))
r.draw(win)
line=Line(Point(20,30),Point(180,199))
line.draw(win)
oval=Oval(Point(20,150),Point(180,199))
oval.draw(win)

**Comment by b6ff01e2-4ed0-4f3e-831a-cfe8e45a6a2e** [comment]
hey issue Cleared
