### ISSUE TITLE
re.compile fails when compiling bytes under `-bb` mode

### ISSUE THREAD

**Issue by b0f82a92-4349-4a2a-bee4-a45118bc9ff6** [python/cpython#74790]
BPO | [30605](https://bugs.python.org/issue30605)
--- | :---
Nosy | @ezio-melotti, @serhiy-storchaka, @rowillia
PRs | <li>python/cpython#2016</li><li>python/cpython#2214</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-06-15.14:18:21.126>
created_at = <Date 2017-06-09.00:48:51.019>
labels = ['expert-regex', 'type-bug', '3.7']
title = 're.compile fails when compiling bytes under `-bb` mode'
updated_at = <Date 2017-06-15.14:18:21.125>
user = 'https://github.com/rowillia'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-15.14:18:21.125>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-06-15.14:18:21.126>
closer = 'serhiy.storchaka'
components = ['Regular Expressions']
creation = <Date 2017-06-09.00:48:51.019>
creator = 'Roy Williams'
dependencies = []
files = []
hgrepos = []
issue_num = 30605
keywords = []
message_count = 4.0
messages = ['295473', '295474', '295612', '296090']
nosy_count = 4.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'Roy Williams']
pr_nums = ['2016', '2214']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30605'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by b0f82a92-4349-4a2a-bee4-a45118bc9ff6** [comment]
```py
import re
re.compile(br'^(.*?)$(?m)')
```

**Comment by b0f82a92-4349-4a2a-bee4-a45118bc9ff6** [comment]
Repro:

```
import re
re.compile(br'^(.*?)$(?m)')
```

Results in
```
Traceback (most recent call last):
  File "test_compile.py", line 2, in <module>
    re.compile(br'^(.*?)$(?m)')
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 856, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, False)
  File "/usr/lib/python3.6/sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "/usr/lib/python3.6/sre_parse.py", line 741, in _parse
    ' (truncated)' if len(source.string) > 20 else '',
BytesWarning: str() on a bytes instance
```

**Comment by serhiy-storchaka** [comment]
New changeset 171b9a354e816eebc6d4c3a8553303942e9c5025 by Serhiy Storchaka (Roy Williams) in branch 'master':
bpo-30605: Fix compiling binary regexs with BytesWarnings enabled. (bpo-2016)
https://github.com/python/cpython/commit/171b9a354e816eebc6d4c3a8553303942e9c5025

**Comment by serhiy-storchaka** [comment]
New changeset 523a243840feb4d5f444a1b128e540876afac3d2 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30605: Fix compiling binary regexs with BytesWarnings enabled. (GH-2016) (bpo-2214)
https://github.com/python/cpython/commit/523a243840feb4d5f444a1b128e540876afac3d2
