### ISSUE TITLE
test_utime_current_old() of test_os fails randomy on x86 Windows7 3.6

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74834]
BPO | [30649](https://bugs.python.org/issue30649)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @zooba
PRs | <li>python/cpython#2156</li><li>python/cpython#2175</li><li>python/cpython#2176</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-03.13:22:59.434>
created_at = <Date 2017-06-13.09:29:59.194>
labels = ['3.7', 'tests', 'OS-windows']
title = 'test_utime_current_old() of test_os fails randomy on x86 Windows7 3.6'
updated_at = <Date 2017-07-03.13:22:59.432>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-03.13:22:59.432>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-03.13:22:59.434>
closer = 'vstinner'
components = ['Tests', 'Windows']
creation = <Date 2017-06-13.09:29:59.194>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30649
keywords = ['buildbot']
message_count = 4.0
messages = ['295879', '295960', '295997', '296000']
nosy_count = 5.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'steve.dower']
pr_nums = ['2156', '2175', '2176']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30649'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86%20Windows7%203.6/builds/416/steps/test/logs/stdio

\======================================================================
FAIL: test_utime_current_old (test.test_os.UtimeTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\test_os.py", line 644, in test_utime_current_old
    self._test_utime_current(set_time)
  File "D:\cygwin\home\db3l\buildarea\3.6.bolen-windows7\build\lib\test\test_os.py", line 632, in _test_utime_current
    delta=delta, msg=msg)
AssertionError: 1497323613.108506 != 1497323613.0692456 within 0.02 delta : st_time=1497323613.108506, current=1497323613.0692456, dt=0.0392603874206543
```


----------------------------------------------------------------------
Ran 238 tests in 16.382s

FAILED (failures=1, skipped=81)
test test_os failed

And then test_os passed.

**Comment by vstinner** [comment]
New changeset c94caca65cd38802243b5279cf85ee44ffb2abb8 by Victor Stinner in branch 'master':
bpo-30649: test_os tolerates 50 ms delta for utime (bpo-2156)
https://github.com/python/cpython/commit/c94caca65cd38802243b5279cf85ee44ffb2abb8

**Comment by vstinner** [comment]
New changeset 3402f7268897db15053866e1e68404cfa0e02706 by Victor Stinner in branch 'master':
bpo-30649: Revert utime delta in test_os (bpo-2176)
https://github.com/python/cpython/commit/3402f7268897db15053866e1e68404cfa0e02706

**Comment by vstinner** [comment]
New changeset c2a506e40e9135bfd17b59fffc62261dc95bc535 by Victor Stinner in branch '3.6':
[3.6] bpo-30649: test_os tolerates 50 ms delta for utime (bpo-2156) (bpo-2175)
https://github.com/python/cpython/commit/c2a506e40e9135bfd17b59fffc62261dc95bc535
