### ISSUE TITLE
__aexit__ not called when `run_until_complete` is interrupted by SIGINT

### ISSUE THREAD

**Issue by 31360d5f-129c-4f2f-8d9b-f689d60cf0a5** [python/cpython#74864]
BPO | [30679](https://bugs.python.org/issue30679)
--- | :---
Nosy | @1st1, @arthurdarcet
PRs | <li>python/cpython#2219</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-06-15.15:27:28.279>
labels = ['3.7', 'expert-asyncio']
title = '__aexit__ not called when `run_until_complete` is interrupted by SIGINT'
updated_at = <Date 2017-06-15.16:06:49.345>
user = 'https://github.com/arthurdarcet'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-15.16:06:49.345>
actor = 'rthr'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2017-06-15.15:27:28.279>
creator = 'rthr'
dependencies = []
files = []
hgrepos = []
issue_num = 30679
keywords = []
message_count = 3.0
messages = ['296106', '296110', '296112']
nosy_count = 2.0
nosy_names = ['yselivanov', 'rthr']
pr_nums = ['2219']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue30679'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 31360d5f-129c-4f2f-8d9b-f689d60cf0a5** [comment]
Here is the example code I am running:

```
import asyncio

class it:
	async def __aenter__(self):
		return self
	async def __aexit__(self, *_):
		print('EXIT')

async def main():
	async with it():
		await asyncio.sleep(100)

asyncio.get_event_loop().run_until_complete(main())
```


When this gets interrupted by a SIGINT, I would expect this code to display `EXIT` before the `KeyboardInterrupt` stacktrace. But instead the `__aexit__` function is simply not called.

**Comment by 1st1** [comment]
Yes, this is a known limitation of asyncio -- keyboardinterrupt exceptions kills the loop rather abruptly. One way to handle this is to use 'signal.signal' for sigint to raise custom exception instead of keyboardinterrupt.

**Comment by 31360d5f-129c-4f2f-8d9b-f689d60cf0a5** [comment]
Ok, thank you. I'm guessing the patch I proposed in the PR is not an option, for my curiosity, why is that?

**Comment by kumaraditya303** [comment]
This is fixed on main branch:

```console 
@kumaraditya303 ➜ /workspaces/cpython (main ✗) $ ./python main.py 
^CEXIT
Traceback (most recent call last):
  File "/workspaces/cpython/Lib/asyncio/runners.py", line 115, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/cpython/Lib/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/workspaces/cpython/main.py", line 11, in main
    await asyncio.sleep(100)
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/cpython/Lib/asyncio/tasks.py", line 648, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/cpython/main.py", line 13, in <module>
    asyncio.run(main())
    ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/cpython/Lib/asyncio/runners.py", line 181, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/workspaces/cpython/Lib/asyncio/runners.py", line 118, in run
    raise KeyboardInterrupt()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

Duplicate of https://github.com/python/cpython/issues/83803
