### ISSUE TITLE
Exception parsing certain invalid email address headers

### ISSUE THREAD

**Issue by 6e8ac999-bcea-4305-ad43-2258dd92a832** [python/cpython#74886]
BPO | [30701](https://bugs.python.org/issue30701)
--- | :---
Nosy | @warsaw, @ncoghlan, @bitdancer, @timb07, @tirkarthi, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-01-08.14:13:55.145>
created_at = <Date 2017-06-19.09:25:47.372>
labels = ['type-bug', '3.7', 'expert-email']
title = 'Exception parsing certain invalid email address headers'
updated_at = <Date 2021-01-08.14:13:55.145>
user = 'https://github.com/timb07'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-08.14:13:55.145>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-01-08.14:13:55.145>
closer = 'iritkatriel'
components = ['email']
creation = <Date 2017-06-19.09:25:47.372>
creator = 'timb07'
dependencies = []
files = []
hgrepos = []
issue_num = 30701
keywords = []
message_count = 5.0
messages = ['296309', '296371', '296397', '352238', '382343']
nosy_count = 6.0
nosy_names = ['barry', 'ncoghlan', 'r.david.murray', 'timb07', 'xtreak', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30701'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 6e8ac999-bcea-4305-ad43-2258dd92a832** [comment]
According to RFC 5322, an email address like this isn't valid:

user@example.com \<user@example.com\>

(The display-name "user@example.com" contains "@", which isn't in the set of atext characters used to form an atom.)

How it's handled by the email package varies by policy:

```pycon
>>> import email
>>> from email.policy import default
>>> email.message_from_bytes(b'To: user@example.com <user@example.com>')['to']
'user@example.com <user@example.com>'
>>> email.message_from_bytes(b'To: user@example.com <user@example.com>', policy=default)['to']
'user@example.com'
>>> email.message_from_bytes(b'To: user@example.com <user@example.com>', policy=default).defects
[]
```


The difference between the behaviour under the compat32 vs "default" policy may or may not be significant.

However, if coupled with a further invalid feature, namely a space after the "\>", here's what happens:

```pycon
>>> email.message_from_bytes(b'To: user@example.com <user@example.com> ')['to']
'user@example.com <user@example.com> '
>>> email.message_from_bytes(b'To: user@example.com <user@example.com> ', policy=default)['to']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/message.py", line 391, in __getitem__
    return self.get(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/policy.py", line 162, in header_fetch_parse
    return self.header_factory(name, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/headerregistry.py", line 586, in __call__
    return self[name](name, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/headerregistry.py", line 197, in __new__
    cls.parse(value, kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/headerregistry.py", line 337, in parse
    kwds['parse_tree'] = address_list = cls.value_parser(value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/headerregistry.py", line 328, in value_parser
    address_list, value = parser.get_address_list(value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/_header_value_parser.py", line 2368, in get_address_list
    token, value = get_invalid_mailbox(value, ',')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/_header_value_parser.py", line 2166, in get_invalid_mailbox
    token, value = get_phrase(value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/_header_value_parser.py", line 1770, in get_phrase
    token, value = get_word(value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/_header_value_parser.py", line 1745, in get_word
    if value[0]=='"':
IndexError: string index out of range
>>> email.message_from_bytes(b'To: user@example.com <user@example.com> ', policy=default).defects
[]
```


I believe that the preferred behaviour would be to add a defect to the message object during parsing instead of throwing an exception when the invalid header value is accessed.

**Comment by bitdancer** [comment]
Yep, you found an edge case I didn't write a test for.  The defect should get added to the header object during parsing.  (Those are supposed to get copied to the message object...)

**Comment by 6e8ac999-bcea-4305-ad43-2258dd92a832** [comment]
I'm using the email package to ingest a firehose of spam; spammers aren't known for following norms or standards, so it's not surprising that I'm discovering lots of edge cases.

I'll supply fixes for what I find where I can, time permitting.
