### ISSUE TITLE
fileinput inplace clobbers file without leaving backup on decode errors

### ISSUE THREAD

**Issue by 891d0578-da4b-43cc-a9fb-956ce9a96490** [python/cpython#74885]
BPO | [30700](https://bugs.python.org/issue30700)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-06-19.04:14:47.793>
labels = ['type-bug', 'expert-IO']
title = 'fileinput inplace clobbers file without leaving backup on decode errors'
updated_at = <Date 2020-09-21.23:10:20.062>
user = 'https://bugs.python.org/switchnode'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-21.23:10:20.062>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['IO']
creation = <Date 2017-06-19.04:14:47.793>
creator = 'switchnode'
dependencies = []
files = []
hgrepos = []
issue_num = 30700
keywords = []
message_count = 1.0
messages = ['296304']
nosy_count = 1.0
nosy_names = ['switchnode']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30700'
versions = ['Python 3.6']
```

</p></details>

**Comment by 891d0578-da4b-43cc-a9fb-956ce9a96490** [comment]
Consider the script:

```sh
$ cat nop.py
#!/usr/bin/env python
import fileinput
srt = fileinput.input(inplace=True)
print(srt.readline(), end='')
for line in srt:
        print(line, end='')
```


Called on text files, it will do nothing.

```sh
$ ls -alh test.*
-rw-r--r-- 1 501 utmp 1.3G Jun 18 22:17 test.mp4
-rw-r--r-- 1 501 utmp  71K Jun 18  2017 test.srt
$ ./nop.py test.srt
$ ls -alh test.*
-rw-r--r-- 1 501 utmp 1.3G Jun 18 22:17 test.mp4
-rw-r--r-- 1 501 utmp  71K Jun 18  2017 test.srt
```


However, if the user accidentally supplies the filename of a video instead of the associated srt...

```pytb
$ ./nop.py test.mp4
Traceback (most recent call last):
  File "./nop.py", line 4, in <module>
    print(srt.readline(), end='')
  File "/usr/lib/python3.6/fileinput.py", line 299, in readline
    line = self._readline()
  File "/usr/lib/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 43: invalid start byte
$ ls -alh test.*
-rw-r--r-- 1 501 utmp    0 Jun 18  2017 test.mp4
-rw-r--r-- 1 501 utmp  71K Jun 18  2017 test.srt
$ ls -alh * | grep 'bak'
$
```


Oops! It is gone.

I'm not sure why this happens. (Without the context-manager syntax, I would expect the program to end by excepting, fail to close the FileInput, and leave the backup file behind—certainly that would be the merciful option.)

**Comment by smheidrich** [comment]
Well the docs do say

> If the backup parameter is given (typically as backup='.<some extension>'), it specifies the extension for the backup file, and the backup file remains around; by default, the extension is '.bak' and it is deleted when the output file is closed.

So this is the desired behavior, although I wouldn't have noticed it while skimming the docs either. Perhaps it could be made clearer, e.g. bold **Note** instead of hiding this information away in one half-sentence?

**Comment by smheidrich** [comment]
On the other hand, what is the point of having a backup file by default at all then if it's never actually preserved? :thinking: 

The same thing happens if an exception happens for any other reason even when you do use the context manager:

```python
import fileinput

with fileinput.input(inplace=True) as srt:
    print(srt.readline(), end="")
    raise ValueError("nonsense")
    # now all lines except the first are gone
```

So I think it makes sense to either preserve the backup file on exceptions like @switchnode suggested or just don't create it in the first place. Unless I'm missing something?
