### ISSUE TITLE
pypi ssl errors [CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by c727457d-2967-48a7-abd3-394d46bb14f3** [python/cpython#74924]
BPO | [30739](https://bugs.python.org/issue30739)
--- | :---
Nosy | @ned-deily, @dstufft

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-01.00:33:17.291>
created_at = <Date 2017-06-23.13:07:06.673>
labels = []
title = 'pypi ssl errors [CERTIFICATE_VERIFY_FAILED]'
updated_at = <Date 2017-07-01.00:33:17.276>
user = 'https://bugs.python.org/LucZimmermann'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-01.00:33:17.276>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-01.00:33:17.291>
closer = 'ned.deily'
components = []
creation = <Date 2017-06-23.13:07:06.673>
creator = 'Luc Zimmermann'
dependencies = []
files = []
hgrepos = []
issue_num = 30739
keywords = []
message_count = 2.0
messages = ['296708', '297459']
nosy_count = 3.0
nosy_names = ['ned.deily', 'dstufft', 'Luc Zimmermann']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30739'
versions = ['Python 2.7']
```

</p></details>

**Comment by c727457d-2967-48a7-abd3-394d46bb14f3** [comment]
Hi Guys, 

I've a strange behavior. 
We use python for configure our new boxes with openWRT and coovaChilli.

But since yesterday, when i ask to pip to dowload PyJWT, json-cfg and speedtest-cli, 

some boxes can download these packages, and some can't.

root@OpenWrt:~# cat /root/.pip/pip.log
\------------------------------------------------------------
```pytb
/usr/bin/pip run on Thu Apr 13 18:46:19 2017
Downloading/unpacking PyJWT
  Getting page https://pypi.python.org/simple/PyJWT/
  Could not fetch URL https://pypi.python.org/simple/PyJWT/: connection error: [SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c)
  Will skip URL https://pypi.python.org/simple/PyJWT/ when looking for download links for PyJWT
  Getting page https://pypi.python.org/simple/
  Could not fetch URL https://pypi.python.org/simple/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max r)
  Will skip URL https://pypi.python.org/simple/ when looking for download links for PyJWT
  Cannot fetch index base URL https://pypi.python.org/simple/
  URLs to search for versions for PyJWT:
  * https://pypi.python.org/simple/PyJWT/
  Getting page https://pypi.python.org/simple/PyJWT/
  Could not fetch URL https://pypi.python.org/simple/PyJWT/: connection error: [SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c)
  Will skip URL https://pypi.python.org/simple/PyJWT/ when looking for download links for PyJWT
  Could not find any downloads that satisfy the requirement PyJWT
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions at all found for PyJWT
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for PyJWT
```

**Comment by ned-deily** [comment]
It looks like there was a certificate validation error when pip tried to make a TLS (https) connection.  If you are still having problems, suggest you check the pip issue tracker and, if needed, ask for help over there.

https://github.com/pypa/pip/issues
