### ISSUE TITLE
Python 3.6.1 test_asyncio fails on Solaris 11

### ISSUE THREAD

**Issue by 0a8138bd-e4ab-4a36-b81e-9117d13194bd** [python/cpython#74920]
BPO | [30735](https://bugs.python.org/issue30735)
--- | :---
Nosy | @vstinner, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-10-21.10:23:46.798>
created_at = <Date 2017-06-22.13:45:02.225>
labels = ['expert-asyncio']
title = 'Python 3.6.1 test_asyncio fails on Solaris 11'
updated_at = <Date 2019-10-21.10:23:46.797>
user = 'https://bugs.python.org/petriborg'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-21.10:23:46.797>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2019-10-21.10:23:46.798>
closer = 'vstinner'
components = ['asyncio']
creation = <Date 2017-06-22.13:45:02.225>
creator = 'petriborg'
dependencies = []
files = []
hgrepos = []
issue_num = 30735
keywords = []
message_count = 2.0
messages = ['296629', '355042']
nosy_count = 3.0
nosy_names = ['vstinner', 'yselivanov', 'petriborg']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30735'
versions = ['Python 3.6']
```

</p></details>

**Comment by 0a8138bd-e4ab-4a36-b81e-9117d13194bd** [comment]
I was building all the latest Python (2.7.13, 3.4.6, 3.5.3 and 3.6.1) on Solaris 11 using gcc 4.9.2 and found that Python 3.6.1 test_asyncio consistently fails while the other versions don't.

Details:


```pytb
$ ./python -W default -bb -E -W error::BytesWarning -m test -r -w -j 0 test_asyncio
Using random seed 44984
Run tests in parallel using 10 child processes
0:00:28 [1/1/1] test_asyncio failed
Executing <Handle Future.set_result(None) created at /usr/local/src/Python-3.6.1/Lib/test/test_asyncio/test_base_events.py:329> took 0.178 seconds
test test_asyncio failed -- Traceback (most recent call last):
  File "/usr/local/src/Python-3.6.1/Lib/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/usr/local/src/Python-3.6.1/Lib/test/test_asyncio/test_base_events.py", line 1232, in test_create_connection_service_name
    t, p = self.loop.run_until_complete(coro)
  File "/usr/local/src/Python-3.6.1/Lib/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/local/src/Python-3.6.1/Lib/asyncio/base_events.py", line 732, in create_connection
    infos = f1.result()
  File "/usr/local/src/Python-3.6.1/Lib/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/src/Python-3.6.1/Lib/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 9] service name not available for the specified socket type
```


1 test failed:
    test_asyncio
Re-running failed tests in verbose mode
Re-running test 'test_asyncio' in verbose mode

... snipped ...

\======================================================================
ERROR: test_create_connection_service_name (test.test_asyncio.test_base_events.BaseEventLoopWithSelectorTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/local/src/Python-3.6.1/Lib/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/usr/local/src/Python-3.6.1/Lib/test/test_asyncio/test_base_events.py", line 1232, in test_create_connection_service_name
    t, p = self.loop.run_until_complete(coro)
  File "/usr/local/src/Python-3.6.1/Lib/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/local/src/Python-3.6.1/Lib/asyncio/base_events.py", line 732, in create_connection
    infos = f1.result()
  File "/usr/local/src/Python-3.6.1/Lib/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/src/Python-3.6.1/Lib/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 9] service name not available for the specified socket type
```


======================================================================
ERROR: test_server_close (test.test_asyncio.test_events.PollEventLoopTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/local/src/Python-3.6.1/Lib/test/test_asyncio/test_events.py", line 1340, in test_server_close
    ConnectionRefusedError, client.connect, ('127.0.0.1', port))
  File "/usr/local/src/Python-3.6.1/Lib/unittest/case.py", line 728, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/local/src/Python-3.6.1/Lib/unittest/case.py", line 177, in handle
    callable_obj(*args, **kwargs)
TimeoutError: [Errno 145] Connection timed out
```


======================================================================
ERROR: test_sock_client_fail (test.test_asyncio.test_events.PollEventLoopTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/local/src/Python-3.6.1/Lib/test/test_asyncio/test_events.py", line 471, in test_sock_client_fail
    self.loop.sock_connect(sock, address))
  File "/usr/local/src/Python-3.6.1/Lib/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/local/src/Python-3.6.1/Lib/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/usr/local/src/Python-3.6.1/Lib/asyncio/selector_events.py", line 481, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
TimeoutError: [Errno 145] Connect call failed ('127.0.0.1', 56937)
```


======================================================================
ERROR: test_server_close (test.test_asyncio.test_events.SelectEventLoopTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/local/src/Python-3.6.1/Lib/test/test_asyncio/test_events.py", line 1340, in test_server_close
    ConnectionRefusedError, client.connect, ('127.0.0.1', port))
  File "/usr/local/src/Python-3.6.1/Lib/unittest/case.py", line 728, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/local/src/Python-3.6.1/Lib/unittest/case.py", line 177, in handle
    callable_obj(*args, **kwargs)
TimeoutError: [Errno 145] Connection timed out
```


======================================================================
ERROR: test_sock_client_fail (test.test_asyncio.test_events.SelectEventLoopTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/local/src/Python-3.6.1/Lib/test/test_asyncio/test_events.py", line 471, in test_sock_client_fail
    self.loop.sock_connect(sock, address))
  File "/usr/local/src/Python-3.6.1/Lib/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/local/src/Python-3.6.1/Lib/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/usr/local/src/Python-3.6.1/Lib/asyncio/selector_events.py", line 481, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
TimeoutError: [Errno 145] Connect call failed ('127.0.0.1', 43072)
```


----------------------------------------------------------------------
Ran 1402 tests in 785.313s

FAILED (errors=5, skipped=4)
test test_asyncio failed
1 test failed again:
    test_asyncio

Total duration: 13 min 34 sec
Tests result: FAILURE

```sh
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/sparc-sun-solaris2.11/4.9.2/lto-wrapper
Target: sparc-sun-solaris2.11
Configured with: ../gcc-4.9.2/configure --prefix=/usr/local --enable-languages=c,c++ --disable-nls --with-gnu-as --with-gnu-ld --target=sparc-sun-solaris2.11
Thread model: posix
gcc version 4.9.2 (GCC)
```
