### ISSUE TITLE
ttk: GUI tests fail on Ubuntu

### ISSUE THREAD

**Issue by csabella** [python/cpython#74941]
BPO | [30756](https://bugs.python.org/issue30756)
--- | :---
Nosy | @terryjreedy, @serhiy-storchaka, @csabella, @DahlitzFlorian

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-06-25.19:02:20.478>
labels = ['3.7', 'tests', 'type-bug', 'expert-tkinter']
title = 'ttk: GUI tests fail on Ubuntu'
updated_at = <Date 2020-05-23.14:22:52.586>
user = 'https://github.com/csabella'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-23.14:22:52.586>
actor = 'DahlitzFlorian'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests', 'Tkinter']
creation = <Date 2017-06-25.19:02:20.478>
creator = 'cheryl.sabella'
dependencies = []
files = []
hgrepos = []
issue_num = 30756
keywords = []
message_count = 4.0
messages = ['296835', '296843', '369717', '369722']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'serhiy.storchaka', 'cheryl.sabella', 'DahlitzFlorian']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30756'
versions = ['Python 3.7']
```

</p></details>

**Comment by csabella** [comment]
Running the tests over up to date build on Ubuntu 16.04 64-bit.

./python -m test.test_ttk_guionly -v


Sometimes this runs without failure and sometimes it 'hangs' and then produces failures.  When it hangs, my computer freezes completely.  As you can see, it can run for 8 minutes.

It seems to hang most often on test_idenify in EntryTest.

Here's one set of failures:

\======================================================================
FAIL: test_identify (tkinter.test.test_ttk.test_widgets.EntryTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/cheryl/cpython/Lib/tkinter/test/test_ttk/test_widgets.py", line 332, in test_identify
    self.assertEqual(self.entry.identify(5, 5), "textarea")
AssertionError: '' != 'textarea'
+ textarea
```


======================================================================
FAIL: test_get (tkinter.test.test_ttk.test_widgets.ScaleTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/cheryl/cpython/Lib/tkinter/test/test_ttk/test_widgets.py", line 807, in test_get
    self.assertEqual(self.scale.get(scale_width, 0), self.scale['to'])
AssertionError: 0.0 != 1.0
```


======================================================================
FAIL: test_set (tkinter.test.test_ttk.test_widgets.ScaleTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/cheryl/cpython/Lib/tkinter/test/test_ttk/test_widgets.py", line 849, in test_set
    self.assertEqual(conv(self.scale.get(self.scale.winfo_width(), 0)), max)
AssertionError: 0.0 != 1.0
```


======================================================================
FAIL: test_identify (tkinter.test.test_ttk.test_widgets.WidgetTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/cheryl/cpython/Lib/tkinter/test/test_ttk/test_widgets.py", line 71, in test_identify
    ), "label")
AssertionError: '' != 'label'
+ label
```


----------------------------------------------------------------------
Ran 272 tests in 491.572s

FAILED (failures=4)



Here's another set from a different run:

\======================================================================
FAIL: test_get (tkinter.test.test_ttk.test_widgets.ScaleTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/cheryl/cpython/Lib/tkinter/test/test_ttk/test_widgets.py", line 807, in test_get
    self.assertEqual(self.scale.get(scale_width, 0), self.scale['to'])
AssertionError: 0.0 != 1.0
```


======================================================================
FAIL: test_set (tkinter.test.test_ttk.test_widgets.ScaleTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/cheryl/cpython/Lib/tkinter/test/test_ttk/test_widgets.py", line 849, in test_set
    self.assertEqual(conv(self.scale.get(self.scale.winfo_width(), 0)), max)
AssertionError: 0.0 != 1.0
```


======================================================================
FAIL: test_identify (tkinter.test.test_ttk.test_widgets.WidgetTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/cheryl/cpython/Lib/tkinter/test/test_ttk/test_widgets.py", line 71, in test_identify
    ), "label")
AssertionError: '' != 'label'
+ label
```


======================================================================
FAIL: test_horizontal_range (tkinter.test.test_ttk.test_extensions.LabeledScaleTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/cheryl/cpython/Lib/tkinter/test/test_ttk/test_extensions.py", line 122, in test_horizontal_range
    self.assertEqual(prev_xcoord, int(linfo_1['x']))
AssertionError: 16 != 1
```


----------------------------------------------------------------------
Ran 272 tests in 353.180s

FAILED (failures=4)

**Comment by terryjreedy** [comment]
My Win 10 machine consistently runs 272 tests OK in 3 seconds.

**Comment by serhiy-storchaka** [comment]
These failures are all fixed by the test hardening in gh-69134 (#152499, backported to 3.13/3.14/3.15).

The named tests no longer assert on unmapped geometry or block on `wait_visibility()`; they now wait for the window manager to map the widget (or skip cleanly):

- `EntryTest.test_identify` (`'' != 'textarea'`) and `ScaleTest.test_get`/`test_set` now guard the geometry assertions with `wait_until_mapped()`.
- The `LabeledScale` hang at `wait_visibility()` (bpo-40722) is gone — that test uses `require_mapped()` instead, which never blocks indefinitely.

Closing as completed.
