### ISSUE TITLE
test_open() of test_eintr timeout after 10 min on "x86-64 El Capitan 3.x"

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74999]
BPO | [30816](https://bugs.python.org/issue30816)
--- | :---
Nosy | @ronaldoussoren, @vstinner, @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-19.23:27:38.889>
created_at = <Date 2017-06-30.14:17:08.504>
labels = ['OS-mac', '3.7', 'tests']
title = 'test_open() of test_eintr timeout after 10 min on "x86-64 El Capitan 3.x"'
updated_at = <Date 2018-09-19.23:27:38.889>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-19.23:27:38.889>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-19.23:27:38.889>
closer = 'vstinner'
components = ['macOS', 'Tests']
creation = <Date 2017-06-30.14:17:08.504>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30816
keywords = ['buildbot']
message_count = 2.0
messages = ['297407', '301560']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'vstinner', 'ned.deily']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30816'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86-64%20El%20Capitan%203.x/builds/413/steps/test/logs/stdio

0:32:36 load avg: 1.58 [328/406/1] test_eintr failed
test_all (test.test_eintr.EINTRTests) ... FAIL

\======================================================================
FAIL: test_all (test.test_eintr.EINTRTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/test_eintr.py", line 18, in test_all
    script_helper.assert_python_ok("-u", tester)
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/support/script_helper.py", line 151, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/support/script_helper.py", line 137, in _assert_python
    res.fail(cmd_line)
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/support/script_helper.py", line 79, in fail
    err))
AssertionError: Process return code is 1
command line: ['/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/python.exe', '-X', 'faulthandler', '-I', '-u', '/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/eintrdata/eintr_tester.py']
```


stdout:
\---
test_read (__main__.OSEINTRTest) ... ok
test_wait (__main__.OSEINTRTest) ... ok
test_wait3 (__main__.OSEINTRTest) ... ok
test_wait4 (__main__.OSEINTRTest) ... ok
test_waitpid (__main__.OSEINTRTest) ... ok
test_write (__main__.OSEINTRTest) ... ok
test_accept (__main__.SocketEINTRTest) ... ok
test_open (__main__.SocketEINTRTest) ...
\---

stderr:
\---
Timeout (0:10:00)!
Thread 0x00007fff79b17000 (most recent call first):
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/eintrdata/eintr_tester.py", line 343 in python_open
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/eintrdata/eintr_tester.py", line 339 in \_test_open
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/support/__init__.py", line 556 in wrapper
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/eintrdata/eintr_tester.py", line 348 in test_open
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/unittest/case.py", line 615 in run
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/unittest/case.py", line 663 in \_\_call__
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/unittest/suite.py", line 122 in run
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/unittest/suite.py", line 84 in \_\_call__
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/unittest/suite.py", line 122 in run
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/unittest/suite.py", line 84 in \_\_call__
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/unittest/runner.py", line 176 in run
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/support/__init__.py", line 1896 in \_run_suite
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/support/__init__.py", line 1940 in run_unittest
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/eintrdata/eintr_tester.py", line 488 in test_main
  File "/Users/buildbot/buildarea/3.x.billenstein-elcapitan/build/Lib/test/eintrdata/eintr_tester.py", line 492 in \<module\>
\---

\----------------------------------------------------------------------
Ran 1 test in 603.735s

FAILED (failures=1)
Warning -- files was modified by test_eintr
  Before: []
  After:  ['@test_40253_tmp'] 
test test_eintr failed

**Comment by vstinner** [comment]
The test also failed on x86-64 Sierra 3.x... twice:

http://buildbot.python.org/all/builders/x86-64%20Sierra%203.x/builds/680
