### ISSUE TITLE
'Cannot serialize socket object' after ssl.wrap_socket

### ISSUE THREAD

**Issue by 930bd4ac-e7c4-4057-a64e-e62382234b29** [python/cpython#75012]
BPO | [30829](https://bugs.python.org/issue30829)
--- | :---
Nosy | @pitrou, @tiran, @Anderseta

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2017-07-03.07:53:59.380>
created_at = <Date 2017-07-02.23:23:29.584>
labels = ['expert-SSL']
title = "'Cannot serialize socket object' after ssl.wrap_socket"
updated_at = <Date 2017-07-03.07:53:59.379>
user = 'https://github.com/Anderseta'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-03.07:53:59.379>
actor = 'pitrou'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2017-07-03.07:53:59.380>
closer = 'pitrou'
components = ['SSL']
creation = <Date 2017-07-02.23:23:29.584>
creator = 'Anderseta'
dependencies = []
files = []
hgrepos = []
issue_num = 30829
keywords = []
message_count = 2.0
messages = ['297526', '297536']
nosy_count = 3.0
nosy_names = ['pitrou', 'christian.heimes', 'Anderseta']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30829'
versions = ['Python 3.6']
```

</p></details>

**Comment by 930bd4ac-e7c4-4057-a64e-e62382234b29** [comment]
\---------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/storage_server/server_tcp.py", line 121, in process_request
    self.pipes[self.proc_turn][1].send((request, client_address))
  File "/usr/local/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.6/socket.py", line 185, in __getstate__
    raise TypeError("Cannot serialize socket object")
TypeError: Cannot serialize socket object
```

---------------------------------------

I am trying to send a ssl wrapped socket object (server side) into a pipe to another process using multiprocessing.

Btw, without ssl_wrap it works.

Basically this:

newsocket, fromaddr = self.socket.accept()

```py
connstream = ssl.wrap_socket(newsocket, server_side=True, certfile=self.certfile, keyfile=self.keyfile)

pipe = multiprocessing.Pipe()
proc = multiprocessing.Process(target=proc_run, args=(pipe[0],), daemon=False)
proc.start()
```


#Error here
pipe[1].send((connstream, fromaddr))

I am sorry if this is intentional.

**Comment by pitrou** [comment]
It is simply not possible to serialize the state of a SSL socket.
(theoretically it should be possible, but AFAIK OpenSSL offers no API for it).
