### ISSUE TITLE
[2.7] Lib/test/bisect.py conflicts with Lib/bisect.py when running tests

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75026]
BPO | [30843](https://bugs.python.org/issue30843)
--- | :---
Nosy | @vstinner
PRs | <li>python/cpython#2563</li><li>python/cpython#2567</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-04.09:45:29.676>
created_at = <Date 2017-07-03.22:14:29.002>
labels = ['tests']
title = '[2.7] Lib/test/bisect.py conflicts with Lib/bisect.py when running tests'
updated_at = <Date 2017-07-05.07:41:21.480>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-05.07:41:21.480>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-04.09:45:29.676>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-07-03.22:14:29.002>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30843
keywords = []
message_count = 6.0
messages = ['297618', '297633', '297636', '297637', '297706', '297710']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = ['2563', '2567']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30843'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
I added [Lib/test/bisect.py](https://github.com/python/cpython/blob/main/Lib/test/bisect.py) in the commit d7955b8196578306e9d86f6c61c9cb3ee72edab0, bpo-29512.

When a test is loaded by [Lib/test/regrtest.py](https://github.com/python/cpython/blob/main/Lib/test/regrtest.py) when regrtest.py runs with "python -m test", test files like [Lib/test/test_bisect.py](https://github.com/python/cpython/blob/main/Lib/test/test_bisect.py) are created with \_\_package__ = ['test']. In this case, "import bisect" loads [Lib/test/bisect.py](https://github.com/python/cpython/blob/main/Lib/test/bisect.py) rather than [Lib/bisect.py](https://github.com/python/cpython/blob/main/Lib/bisect.py). For test_bisect.py, I worked around the issue using "from \_\_future__ import absolute_import".

But then I saw this bug:

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Non-Debug%202.7/builds/159/steps/test/logs/stdio

```pytb
Run tests in parallel using 2 child processes
(...)
0:02:41 [144/403/1] test_multiprocessing failed
test test_multiprocessing failed -- Traceback (most recent call last):
  File "/usr/home/buildbot/python/2.7.koobs-freebsd-current.nondebug/build/Lib/test/test_multiprocessing.py", line 1669, in test_connection
    self.assertEqual(poll(TIMEOUT1), True)
AssertionError: False != True
(...)
Re-running test 'test_multiprocessing' in verbose mode
(...)
```

======================================================================
ERROR: test_array (test.test_multiprocessing.WithProcessesTestArray)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/2.7.koobs-freebsd-current.nondebug/build/Lib/test/test_multiprocessing.py", line 1027, in test_array
    arr = self.Array('i', seq)
  File "/usr/home/buildbot/python/2.7.koobs-freebsd-current.nondebug/build/Lib/multiprocessing/__init__.py", line 260, in Array
    return Array(typecode_or_type, size_or_initializer, **kwds)
  File "/usr/home/buildbot/python/2.7.koobs-freebsd-current.nondebug/build/Lib/multiprocessing/sharedctypes.py", line 120, in Array
    obj = RawArray(typecode_or_type, size_or_initializer)
  File "/usr/home/buildbot/python/2.7.koobs-freebsd-current.nondebug/build/Lib/multiprocessing/sharedctypes.py", line 93, in RawArray
    result = _new_value(type_)
  File "/usr/home/buildbot/python/2.7.koobs-freebsd-current.nondebug/build/Lib/multiprocessing/sharedctypes.py", line 68, in _new_value
    wrapper = heap.BufferWrapper(size)
  File "/usr/home/buildbot/python/2.7.koobs-freebsd-current.nondebug/build/Lib/multiprocessing/heap.py", line 243, in __init__
    block = BufferWrapper._heap.malloc(size)
  File "/usr/home/buildbot/python/2.7.koobs-freebsd-current.nondebug/build/Lib/multiprocessing/heap.py", line 223, in malloc
    (arena, start, stop) = self._malloc(size)
  File "/usr/home/buildbot/python/2.7.koobs-freebsd-current.nondebug/build/Lib/multiprocessing/heap.py", line 115, in _malloc
    i = bisect.bisect_left(self._lengths, size)
AttributeError: 'module' object has no attribute 'bisect_left'
```



The wrong bisect module was picked when test_multiprocessing was run for the second time.

The first run was done in a slave process. The second run was done in the main regrtest process.

**Comment by vstinner** [comment]
This bug only impacts the Python test suite.

I see two options:

* Add "from \_\_future__ import absolute_import" to all .py files in Lib/... I would prefer to not modify too many files to fix a regression caused by a new debug tool

* Rename [Lib/test/bisect.py](https://github.com/python/cpython/blob/main/Lib/test/bisect.py) to [Lib/test/bisectcmd.py](https://github.com/python/cpython/blob/main/Lib/test/bisectcmd.py).

I prefer the second option :-)

**Comment by vstinner** [comment]
New changeset 28b72baf3c1e57af0c9338fb41c89d62aa47a355 by Victor Stinner in branch '2.7':
bpo-30843: Rename [Lib/test/bisect.py](https://github.com/python/cpython/blob/main/Lib/test/bisect.py) to [Lib/test/bisectcmd.py](https://github.com/python/cpython/blob/main/Lib/test/bisectcmd.py) (bpo-2563)
https://github.com/python/cpython/commit/28b72baf3c1e57af0c9338fb41c89d62aa47a355

**Comment by vstinner** [comment]
Fixed: I renamed [Lib/test/bisect.py](https://github.com/python/cpython/blob/main/Lib/test/bisect.py) to [Lib/test/bisectcmd.py](https://github.com/python/cpython/blob/main/Lib/test/bisectcmd.py).

**Comment by vstinner** [comment]
New changeset 3050987d85d7cf8cdd4b3c053e673d13cd8dfb12 by Victor Stinner in branch '2.7':
bpo-30843: regrtest fixes sys.path, restore test.bisect (bpo-2567)
https://github.com/python/cpython/commit/3050987d85d7cf8cdd4b3c053e673d13cd8dfb12

**Comment by vstinner** [comment]
With the help of Nick Coghlan, I fixed regrtest.py to remove '' and [Lib/test/](https://github.com/python/cpython/blob/main/Lib/test) from sys.path, so multiprocessing should now pick [Lib/bisect.py](https://github.com/python/cpython/blob/main/Lib/bisect.py), and I was able to rename again [Lib/test/bisectcmd.py](https://github.com/python/cpython/blob/main/Lib/test/bisectcmd.py) to [Lib/test/bisect.py](https://github.com/python/cpython/blob/main/Lib/test/bisect.py).
