### ISSUE TITLE
[3.6] test_rapid_restart() of test_multiprocessing_fork fails randomly on AMD64 Debian PGO 3.6

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75029]
BPO | [30846](https://bugs.python.org/issue30846)
--- | :---
Nosy | @vstinner, @applio
Superseder | <li>bpo-31069: test_multiprocessing_spawn and test_multiprocessing_forkserver leak dangling processes</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-16.08:46:19.182>
created_at = <Date 2017-07-04.11:10:14.396>
labels = ['library']
title = '[3.6] test_rapid_restart() of test_multiprocessing_fork fails randomly on AMD64 Debian PGO 3.6'
updated_at = <Date 2017-08-16.08:46:19.180>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-16.08:46:19.180>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-16.08:46:19.182>
closer = 'vstinner'
components = ['Library (Lib)']
creation = <Date 2017-07-04.11:10:14.396>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30846
keywords = []
message_count = 3.0
messages = ['297641', '300136', '300335']
nosy_count = 2.0
nosy_names = ['vstinner', 'davin']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '31069'
type = None
url = 'https://bugs.python.org/issue30846'
versions = ['Python 3.6']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20Debian%20PGO%203.6/builds/517/steps/test/logs/stdio

\======================================================================
ERROR: test_rapid_restart (test.test_multiprocessing_fork.WithProcessesTestManagerRestart)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.6.gps-debian-profile-opt.nondebug/build/Lib/test/_test_multiprocessing.py", line 2410, in test_rapid_restart
    manager.start()
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.6.gps-debian-profile-opt.nondebug/build/Lib/multiprocessing/managers.py", line 517, in start
    self._address = reader.recv()
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.6.gps-debian-profile-opt.nondebug/build/Lib/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.6.gps-debian-profile-opt.nondebug/build/Lib/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.6.gps-debian-profile-opt.nondebug/build/Lib/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
(...)
Re-running test 'test_multiprocessing_fork' in verbose mode
(...)
test_rapid_restart (test.test_multiprocessing_fork.WithManagerTestManagerRestart) ... ok
```

**Comment by vstinner** [comment]
See also bpo-31069.

**Comment by vstinner** [comment]
I'm not 100% sure that it's a duplicate of bpo-31069, but it's similar.
