### ISSUE TITLE
test_stress_delivery_dependent() of test_signal randomly fails on AMD64 Debian root 3.6/3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75032]
BPO | [30849](https://bugs.python.org/issue30849)
--- | :---
Nosy | @pitrou, @vstinner, @zware, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/pitrou'
closed_at = <Date 2021-05-26.22:47:39.082>
created_at = <Date 2017-07-04.15:16:51.076>
labels = ['tests']
title = 'test_stress_delivery_dependent() of test_signal randomly fails on AMD64 Debian root 3.6/3.x'
updated_at = <Date 2021-09-08.12:47:26.384>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-08.12:47:26.384>
actor = 'vstinner'
assignee = 'pitrou'
closed = True
closed_date = <Date 2021-05-26.22:47:39.082>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-07-04.15:16:51.076>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30849
keywords = []
message_count = 15.0
messages = ['297674', '297732', '299948', '299985', '299986', '300017', '300181', '300182', '300550', '318313', '320891', '320900', '321019', '394492', '401380']
nosy_count = 4.0
nosy_names = ['pitrou', 'vstinner', 'zach.ware', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30849'
versions = ['Python 3.6']
```

</p></details>

**Comment by vstinner** [comment]
Antoine: I told you that such stess-test is going to require work to polish it. So here is another example of failure. Enjoy :-)

http://buildbot.python.org/all/builders/AMD64%20Debian%20root%203.6/builds/534/steps/test/logs/stdio


== CPython 3.6.2rc1+ (heads/3.6:580cd5c, Jul 5 2017, 00:47:42) [GCC 4.9.2]
== Linux-3.16.0-4-amd64-x86_64-with-debian-8.7 little-endian
...
== CPU count: 1
...
Run tests in parallel using 2 child processes
0:11:40 load avg: 1.29 [383/405/1] test_signal failed -- running: test_datetime (38 sec)
...
\======================================================================
FAIL: test_stress_delivery_dependent (test.test_signal.StressTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/root/buildarea/3.6.angelico-debian-amd64/build/Lib/test/test_signal.py", line 1053, in test_stress_delivery_dependent
    self.assertEqual(len(sigs), N, "Some signals were lost")
AssertionError: 4602 != 10000 : Some signals were lost
```


======================================================================
FAIL: test_stress_delivery_simultaneous (test.test_signal.StressTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/root/buildarea/3.6.angelico-debian-amd64/build/Lib/test/test_signal.py", line 1086, in test_stress_delivery_simultaneous
    self.assertEqual(len(sigs), N, "Some signals were lost")
AssertionError: 8206 != 10000 : Some signals were lost
```

**Comment by vstinner** [comment]
Another fail. The test pass when run again later.

http://buildbot.python.org/all/builders/AMD64%20Debian%20root%203.6/builds/538/steps/test/logs/stdio

\======================================================================
FAIL: test_stress_delivery_dependent (test.test_signal.StressTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/root/buildarea/3.6.angelico-debian-amd64/build/Lib/test/test_signal.py", line 1053, in test_stress_delivery_dependent
    self.assertEqual(len(sigs), N, "Some signals were lost")
AssertionError: 4073 != 10000 : Some signals were lost
```

**Comment by vstinner** [comment]
Hey Antoine, as expected, your test fails randomly on the CI :-(

Another failure:

http://buildbot.python.org/all/builders/x86%20Gentoo%20Non-Debug%20with%20X%203.x/builds/829/steps/test/logs/stdio

test_stress_delivery_dependent (test.test_signal.StressTest) ... Timeout (0:15:00)!
Thread 0xb74bd700 (most recent call first):
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/test_signal.py", line 973 in measure_itimer_resolution
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/test_signal.py", line 985 in decide_itimer_count
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/test_signal.py", line 1001 in test_stress_delivery_dependent
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/unittest/case.py", line 615 in run
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/unittest/case.py", line 663 in \_\_call__
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/unittest/suite.py", line 122 in run
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/unittest/suite.py", line 84 in \_\_call__
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/unittest/suite.py", line 122 in run
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/unittest/suite.py", line 84 in \_\_call__
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/unittest/suite.py", line 122 in run
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/unittest/suite.py", line 84 in \_\_call__
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/unittest/runner.py", line 176 in run
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/support/__init__.py", line 1896 in \_run_suite
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/support/__init__.py", line 1940 in run_unittest
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/libregrtest/runtest.py", line 168 in test_runner
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/libregrtest/runtest.py", line 169 in runtest_inner
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/libregrtest/runtest.py", line 137 in runtest
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/libregrtest/main.py", line 290 in rerun_failed_tests
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/libregrtest/main.py", line 540 in \_main
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/libregrtest/main.py", line 510 in main
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/libregrtest/main.py", line 585 in main
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/test/__main__.py", line 2 in \<module\>
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/runpy.py", line 85 in \_run_code
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.nondebug/build/Lib/runpy.py", line 193 in \_run_module_as_main

**Comment by pitrou** [comment]
Hmm.  Perhaps someone can give me temporary shell access to one of those buildbots?

**Comment by vstinner** [comment]
Antoine: "Hmm.  Perhaps someone can give me temporary shell access to one of those buildbots?"

Contact directly the owners:

* AMD64 Debian root 3.6: Chris Angelico \<rosuav@gmail.com\> 
* x86 Gentoo Non-Debug with X 3.x: Zachary Ware \<zachary.ware+bb@gmail.com\>

**Comment by zware** [comment]
> Hmm.  Perhaps someone can give me temporary shell access to one of those buildbots?

Check your @python.org inbox.

**Comment by pitrou** [comment]
Victor, Zachary, http://buildbot.python.org/all/builders/x86%20Gentoo%20Non-Debug%20with%20X%203.x/builds/830 corresponds to a very old changeset (more than one month old) before itimer() was fixed in 729780a810bbcb12b245a1b652302a601fc9f6fd.

**Comment by vstinner** [comment]
Oh, Zach's Gentoo buildbot was offline for a long time. Maybe it ran tests
on old commits? What about the first messages of this issue on the other
buildbot? Maybe it's also outdated? I am fine with closing the issue if you
fixed a bug in the meanwhile. Don't worry, I will reopen it if it comes
back :-D

**Comment by vstinner** [comment]
test_stress_delivery_dependent() failed on AMD64 Debian root 3.x too, it's not specific to 3.6:

http://buildbot.python.org/all/builders/AMD64%20Debian%20root%203.x/builds/1192/steps/test/logs/stdio

http://buildbot.python.org/all/builders/AMD64%20Debian%20root%203.x/builds/1191/steps/test/logs/stdio

**Comment by vstinner** [comment]
See also issue gh-110083: test_signal: test_stress_modifying_handlers() crash with SIGSEGV on GHA macOS (macOS-12.7).

**Comment by vstinner** [comment]
Now that tests are re-run in verbose mode when they fail, the test no longer makes a whole test suite to be marked as failed. I close the issue again, so nobody seems to be eagger to fix the test or the code.
