### ISSUE TITLE
_PyObject_GC_UNTRACK corruption when call a lambda function with C API

### ISSUE THREAD

**Issue by ghost** [python/cpython#75035]
BPO | [30852](https://bugs.python.org/issue30852)
--- | :---
Nosy | @vstinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-06-25.09:43:48.751>
created_at = <Date 2017-07-05.03:49:48.128>
labels = ['interpreter-core', 'type-crash']
title = '_PyObject_GC_UNTRACK corruption when call a lambda function with C API'
updated_at = <Date 2020-06-25.09:43:48.749>
user = None
```

bugs.python.org fields:
```python
activity = <Date 2020-06-25.09:43:48.749>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2020-06-25.09:43:48.751>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2017-07-05.03:49:48.128>
creator = '\xe7\x9b\x9b\xe8\x8c\x82\xe5\xae\xb6'
dependencies = []
files = []
hgrepos = []
issue_num = 30852
keywords = []
message_count = 2.0
messages = ['297696', '372328']
nosy_count = 2.0
nosy_names = ['vstinner', '\xe7\x9b\x9b\xe8\x8c\x82\xe5\xae\xb6']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30852'
versions = ['Python 2.7']
```

</p></details>

**Comment by ghost** [comment]
This corruption is so strange that I can't even reappear it.

(gdb) bt
#0  0x00000000006d7e9f in func_dealloc.lto_priv () at [Objects/funcobject.c:451](https://github.com/python/cpython/blob/main/Objects/funcobject.c#L451)
#1  0x00000000005c730b in ask (printException=true, okIfFunctionNull=\<optimized out\>, errorPrefix=0x884bca "", pArgs=0x300dd440, pFunction=0x1d1f1de8) at script.cpp:758
#2  Script::call(_object*, \_object*, char const*, bool) (pFunction=0x1d1f1de8, pArgs=0x300dd440, errorPrefix=0x884bca "", okIfFunctionNull=\<optimized out\>) at /home/smj/original/bwengine/src/lib/pyscript/script.ipp:25

now I know that in \_PyObject_GC_UNTRACK, 
(gdb) x/40x  op
0x1d1f1da8:	0x6d	0x6f	0x6e	0x5f	0x73	0x65	0x72	0x76
0x1d1f1db0:	0x65	0x72	0x2f	0x72	0x75	0x6e	0x5f	0x73
0x1d1f1db8:	0x63	0x72	0x69	0x70	0x74	0x2e	0x70	0x79
0x1d1f1dc0:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x1d1f1dc8:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00        -\>  mov  -0x20(%rdi),%rax    -\> %rax = 0
0x1d1f1dd0:	0xf8	0x4d	0xc5	0x2a	0x00	0x00	0x00	0x00        -\>  mov  -0x18(%rdi),%rdx    -\> %rdx = 0x2ac54df8
0x1d1f1dd8:	0xfe	0xff	0xff	0xff	0xff	0xff	0xff	0xff
0x1d1f1de0:	0xff	0xff	0xff	0xff	0xff	0xff	0xff	0xff
0x1d1f1de8:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00         \<--PyFunctionObject      ob_refcnt 0         %rdi
0x1d1f1df0:	0x00	0xff	0xba	0x00	0x00	0x00	0x00	0x00        -\> \_typeobject* -\> name function
0x1d1f1df8:	0x30	0x1e	0x78	0x21	0x00	0x00	0x00	0x00
0x1d1f1e00:	0x28	0xaa	0xba	0x24	0x00	0x00	0x00	0x00
0x1d1f1e08:	0x10	0x53	0xfb	0x2f	0x00	0x00	0x00	0x00

When corruption,
the ob_refcnt is 0, the gc_refs is \_PyGC_REFS_UNTRACKED, the gc_next is NULL but gc_prev is not.

How can it be? Is there some unknown bug in GC?
