### ISSUE TITLE
_elementtree: assertion error if stdlib copy module is overriden

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75075]
BPO | [30892](https://bugs.python.org/issue30892)
--- | :---
Nosy | @vstinner
PRs | <li>python/cpython#2647</li><li>python/cpython#2649</li><li>python/cpython#2650</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-24.13:53:42.074>
created_at = <Date 2017-07-10.16:47:29.347>
labels = ['3.7']
title = '_elementtree: assertion error if stdlib copy module is overriden'
updated_at = <Date 2017-07-24.13:53:42.073>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-24.13:53:42.073>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-24.13:53:42.074>
closer = 'vstinner'
components = []
creation = <Date 2017-07-10.16:47:29.347>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30892
keywords = []
message_count = 5.0
messages = ['298073', '298080', '298085', '298086', '298970']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = ['2647', '2649', '2650']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30892'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
The \_elementtree fails with an assertion error if the stdlib copy module is overriden by the user.

haypo@selma$ mkdir copy/
haypo@selma$ touch copy/__init__.py
haypo@selma$ ./python -c 'import \_elementtree'
python: [Objects/abstract.c:153](https://github.com/python/cpython/blob/main/Objects/abstract.c#L153): PyObject_GetItem: Assertion \`(item != NULL) ^ (PyErr_Occurred() != NULL)' failed.
Aborted (core dumped)

**Comment by vstinner** [comment]
New changeset b136f11f3a51f9282ae992bac68f170ca5563b55 by Victor Stinner in branch 'master':
bpo-30892: Fix \_elementtree module initialization (bpo-2647)
https://github.com/python/cpython/commit/b136f11f3a51f9282ae992bac68f170ca5563b55

**Comment by vstinner** [comment]
New changeset 044e156426825acac8b6c6d1ce14d5b7bcb20bc9 by Victor Stinner in branch '3.6':
bpo-30892: Fix \_elementtree module initialization (bpo-2647) (bpo-2649)
https://github.com/python/cpython/commit/044e156426825acac8b6c6d1ce14d5b7bcb20bc9

**Comment by vstinner** [comment]
New changeset 7f567e7472dd6c3d066eec1c204301df251484b5 by Victor Stinner in branch '3.5':
bpo-30892: Fix \_elementtree module initialization (bpo-2647) (bpo-2650)
https://github.com/python/cpython/commit/7f567e7472dd6c3d066eec1c204301df251484b5

**Comment by vstinner** [comment]
Python 2.7 doesn't seem to be affected:

```pycon
$ python2
Python 2.7.13+ (heads/2.7:598f26b, Jul 21 2017, 01:18:41) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
>>> import _elementtree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in <module>
ImportError: cannot import name copy
```
