### ISSUE TITLE
KeyError with cgitb inspecting exception in generator expression

### ISSUE THREAD

**Issue by jaraco** [python/cpython#75109]
BPO | [30926](https://bugs.python.org/issue30926)
--- | :---
Nosy | @jaraco, @ZackerySpytz

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-09-01.13:20:29.992>
created_at = <Date 2017-07-13.20:46:43.343>
labels = ['interpreter-core', 'library']
title = 'KeyError with cgitb inspecting exception in generator expression'
updated_at = <Date 2020-09-01.13:20:29.992>
user = 'https://github.com/jaraco'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-01.13:20:29.992>
actor = 'jaraco'
assignee = 'none'
closed = True
closed_date = <Date 2020-09-01.13:20:29.992>
closer = 'jaraco'
components = ['Interpreter Core', 'Library (Lib)']
creation = <Date 2017-07-13.20:46:43.343>
creator = 'jaraco'
dependencies = []
files = []
hgrepos = []
issue_num = 30926
keywords = []
message_count = 2.0
messages = ['298314', '376182']
nosy_count = 2.0
nosy_names = ['jaraco', 'ZackerySpytz']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30926'
versions = ['Python 2.7']
```

</p></details>

**Comment by jaraco** [comment]
Consider this script, which runs successfully on Python 3:

```py
import cgitb
import sys


def fiter():
    assert False
    yield 1, 1
    yield 2, 2
    yield 3, 3
```



try:
    x = set(id_ for id_, _ in fiter())
except:
    print cgitb.html(sys.exc_info())


Run the same script on Python 2.7.13 and you get this error:

```pytb
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    print(cgitb.html(sys.exc_info()))
  File ".../cgitb.py", line 130, in html
    formatvalue=lambda value: '=' + pydoc.html.repr(value))
  File ".../inspect.py", line 887, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File ".../inspect.py", line 840, in strseq
    return join(map(lambda o, c=convert, j=join: strseq(o, c, j), object))
  File ".../inspect.py", line 840, in <lambda>
    return join(map(lambda o, c=convert, j=join: strseq(o, c, j), object))
  File ".../inspect.py", line 842, in strseq
    return convert(object)
  File ".../inspect.py", line 884, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'id_'
```



Wrap the generator expression in [] and it also succeeds.

Given that the issue only exists on Python 2.7, it may not need to be addressed, but I wanted to log the issue nonetheless.
