### ISSUE TITLE
ERROR: testRegularFile (test.test_socket.SendfileUsingSendTest) random failure on AppVeyor

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75205]
BPO | [31022](https://bugs.python.org/issue31022)
--- | :---
Nosy | @vstinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-11.22:07:33.997>
created_at = <Date 2017-07-25.00:36:10.787>
labels = ['3.7', 'tests']
title = 'ERROR: testRegularFile (test.test_socket.SendfileUsingSendTest) random failure on AppVeyor'
updated_at = <Date 2017-09-11.22:07:33.996>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-11.22:07:33.996>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-11.22:07:33.997>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-07-25.00:36:10.787>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31022
keywords = []
message_count = 3.0
messages = ['299035', '299406', '301915']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31022'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
https://ci.appveyor.com/project/python/cpython/build/3.7.0a0.4809

(...)
testNonRegularFile (test.test_socket.SendfileUsingSendTest) ... ok
testOffset (test.test_socket.SendfileUsingSendTest) ... ok
testRegularFile (test.test_socket.SendfileUsingSendTest) ... ERROR
testWithTimeout (test.test_socket.SendfileUsingSendTest) ... ok
testWithTimeoutTriggeredSend (test.test_socket.SendfileUsingSendTest) ... ok
(...)
\======================================================================
ERROR: testRegularFile (test.test_socket.SendfileUsingSendTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\projects\cpython\lib\test\test_socket.py", line 5225, in testRegularFile
    data = self.recv_data(conn)
  File "C:\projects\cpython\lib\test\test_socket.py", line 5201, in recv_data
    chunk = conn.recv(self.BUFSIZE)
socket.timeout: timed out
```
----------------------------------------------------------------------

**Comment by vstinner** [comment]
I tried to reproduce the bug on my Windows 8.1 VM. I ran the test more than 1,000 times. In parallel, I ran "python -m test -j0 -rW" to increase the system load, but it wasn't enough to reproduce the bug.

**Comment by vstinner** [comment]
I didn't see this issue recently, but I didn't check much Appveyor. Let's hope that the bug was fixed in the meanwhile. I will reopen the issue if the bug comes back.
