### ISSUE TITLE
test_ssl

### ISSUE THREAD

**Issue by matrixise** [python/cpython#75215]
BPO | [31032](https://bugs.python.org/issue31032)
--- | :---
Nosy | @tiran, @matrixise, @stratakis
Superseder | <li>bpo-30714: test_ssl fails with openssl 1.1.0f: test_alpn_protocols()</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-25.13:15:06.269>
created_at = <Date 2017-07-25.13:13:10.126>
labels = ['3.7']
title = 'test_ssl'
updated_at = <Date 2017-07-25.13:17:30.321>
user = 'https://github.com/matrixise'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-25.13:17:30.321>
actor = 'cstratak'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-25.13:15:06.269>
closer = 'christian.heimes'
components = []
creation = <Date 2017-07-25.13:13:10.126>
creator = 'matrixise'
dependencies = []
files = []
hgrepos = []
issue_num = 31032
keywords = []
message_count = 3.0
messages = ['299075', '299076', '299077']
nosy_count = 3.0
nosy_names = ['christian.heimes', 'matrixise', 'cstratak']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30714'
type = None
url = 'https://bugs.python.org/issue31032'
versions = ['Python 3.7']
```

</p></details>

**Comment by matrixise** [comment]
Last commit on master

commit ccfdb60af7b2db578c1aceb7742cec0330766667 (HEAD -\> master, upstream/master, upstream/HEAD)

Fedora 26 

openssl-libs-1.1.0f-7.fc26.x86_64
openssl-devel-1.1.0f-7.fc26.x86_64
openssl-1.1.0f-7.fc26.x86_64

```
Run tests sequentially
0:00:00 load avg: 1.07 [1/1] test_ssl
Exception in thread Thread-85:
Traceback (most recent call last):
  File "/home/stephane/src/github.com/python/cpython/Lib/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/stephane/src/github.com/python/cpython/Lib/test/test_ssl.py", line 1936, in run
    if not self.wrap_conn():
  File "/home/stephane/src/github.com/python/cpython/Lib/test/test_ssl.py", line 1881, in wrap_conn
    self.sock, server_side=True)
  File "/home/stephane/src/github.com/python/cpython/Lib/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/home/stephane/src/github.com/python/cpython/Lib/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/home/stephane/src/github.com/python/cpython/Lib/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/home/stephane/src/github.com/python/cpython/Lib/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

test test_ssl failed -- Traceback (most recent call last):
  File "/home/stephane/src/github.com/python/cpython/Lib/test/test_ssl.py", line 3273, in test_alpn_protocols
    self.assertIsInstance(stats, ssl.SSLError)
AssertionError: {'compression': None, 'cipher': ('ECDHE-RSA-AES256-GCM-SHA384', 'TLSv1.2', 256), 'peercert': {}, 'client_alpn_protocol': None, 'client_npn_protocol': None, 'version': 'TLSv1.2', 'session_reused': False, 'session': <_ssl.Session object at 0x7f7ed8110a80>, 'server_alpn_protocols': [None], 'server_npn_protocols': [None], 'server_shared_ciphers': [[('ECDHE-ECDSA-AES256-GCM-SHA384', 'TLSv1.2', 256), ('ECDHE-RSA-AES256-GCM-SHA384', 'TLSv1.2', 256), ('ECDHE-ECDSA-AES128-GCM-SHA256', 'TLSv1.2', 128), ('ECDHE-RSA-AES128-GCM-SHA256', 'TLSv1.2', 128), ('ECDHE-ECDSA-CHACHA20-POLY1305', 'TLSv1.2', 256), ('ECDHE-RSA-CHACHA20-POLY1305', 'TLSv1.2', 256), ('DHE-DSS-AES256-GCM-SHA384', 'TLSv1.2', 256), ('DHE-RSA-AES256-GCM-SHA384', 'TLSv1.2', 256), ('DHE-DSS-AES128-GCM-SHA256', 'TLSv1.2', 128), ('DHE-RSA-AES128-GCM-SHA256', 'TLSv1.2', 128), ('DHE-RSA-CHACHA20-POLY1305', 'TLSv1.2', 256), ('ECDHE-ECDSA-AES256-CCM8', 'TLSv1.2', 256), ('ECDHE-ECDSA-AES256-CCM', 'TLSv1.2', 256), ('ECDHE-ECDSA-AES256-SHA384', 'TLSv1.2', 256), ('ECDHE-RSA-AES256-SHA384', 'TLSv1.2', 256), ('ECDHE-ECDSA-AES256-SHA', 'TLSv1.0', 256), ('ECDHE-RSA-AES256-SHA', 'TLSv1.0', 256), ('DHE-RSA-AES256-CCM8', 'TLSv1.2', 256), ('DHE-RSA-AES256-CCM', 'TLSv1.2', 256), ('DHE-RSA-AES256-SHA256', 'TLSv1.2', 256), ('DHE-DSS-AES256-SHA256', 'TLSv1.2', 256), ('DHE-RSA-AES256-SHA', 'SSLv3', 256), ('DHE-DSS-AES256-SHA', 'SSLv3', 256), ('ECDHE-ECDSA-AES128-CCM8', 'TLSv1.2', 128), ('ECDHE-ECDSA-AES128-CCM', 'TLSv1.2', 128), ('ECDHE-ECDSA-AES128-SHA256', 'TLSv1.2', 128), ('ECDHE-RSA-AES128-SHA256', 'TLSv1.2', 128), ('ECDHE-ECDSA-AES128-SHA', 'TLSv1.0', 128), ('ECDHE-RSA-AES128-SHA', 'TLSv1.0', 128), ('DHE-RSA-AES128-CCM8', 'TLSv1.2', 128), ('DHE-RSA-AES128-CCM', 'TLSv1.2', 128), ('DHE-RSA-AES128-SHA256', 'TLSv1.2', 128), ('DHE-DSS-AES128-SHA256', 'TLSv1.2', 128), ('DHE-RSA-AES128-SHA', 'SSLv3', 128), ('DHE-DSS-AES128-SHA', 'SSLv3', 128), ('ECDHE-ECDSA-CAMELLIA256-SHA384', 'TLSv1.2', 256), ('ECDHE-RSA-CAMELLIA256-SHA384', 'TLSv1.2', 256), ('ECDHE-ECDSA-CAMELLIA128-SHA256', 'TLSv1.2', 128), ('ECDHE-RSA-CAMELLIA128-SHA256', 'TLSv1.2', 128), ('DHE-RSA-CAMELLIA256-SHA256', 'TLSv1.2', 256), ('DHE-DSS-CAMELLIA256-SHA256', 'TLSv1.2', 256), ('DHE-RSA-CAMELLIA128-SHA256', 'TLSv1.2', 128), ('DHE-DSS-CAMELLIA128-SHA256', 'TLSv1.2', 128), ('DHE-RSA-CAMELLIA256-SHA', 'SSLv3', 256), ('DHE-DSS-CAMELLIA256-SHA', 'SSLv3', 256), ('DHE-RSA-CAMELLIA128-SHA', 'SSLv3', 128), ('DHE-DSS-CAMELLIA128-SHA', 'SSLv3', 128), ('AES256-GCM-SHA384', 'TLSv1.2', 256), ('AES128-GCM-SHA256', 'TLSv1.2', 128), ('AES256-CCM8', 'TLSv1.2', 256), ('AES256-CCM', 'TLSv1.2', 256), ('AES128-CCM8', 'TLSv1.2', 128), ('AES128-CCM', 'TLSv1.2', 128), ('AES256-SHA256', 'TLSv1.2', 256), ('AES128-SHA256', 'TLSv1.2', 128), ('AES256-SHA', 'SSLv3', 256), ('AES128-SHA', 'SSLv3', 128), ('CAMELLIA256-SHA256', 'TLSv1.2', 256), ('CAMELLIA128-SHA256', 'TLSv1.2', 128), ('CAMELLIA256-SHA', 'SSLv3', 256), ('CAMELLIA128-SHA', 'SSLv3', 128)]]} is not an instance of <class 'ssl.SSLError'>

test_ssl failed

1 test failed:
    test_ssl

Total duration: 1 sec
Tests result: FAILURE
```

**Comment by tiran** [comment]
Duplicate of bpo-30714

**Comment by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [comment]
This is a duplicate of http://bugs.python.org/issue30714
