### ISSUE TITLE
test_multiprocessing_spawn and test_multiprocessing_forkserver leak dangling processes

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75252]
BPO | [31069](https://bugs.python.org/issue31069)
--- | :---
Nosy | @vstinner
PRs | <li>python/cpython#3103</li><li>python/cpython#3104</li><li>python/cpython#3105</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-15.16:40:24.678>
created_at = <Date 2017-07-28.15:02:05.743>
labels = ['3.7', 'tests']
title = 'test_multiprocessing_spawn and test_multiprocessing_forkserver leak dangling processes'
updated_at = <Date 2017-09-15.16:40:24.676>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-15.16:40:24.676>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-15.16:40:24.678>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-07-28.15:02:05.743>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31069
keywords = []
message_count = 16.0
messages = ['299392', '300118', '300122', '300137', '300334', '300337', '300343', '300345', '300348', '300349', '300350', '301339', '301969', '301977', '302061', '302273']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = ['3103', '3104', '3105']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31069'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
It's just a warning, but later I would like to make a buildbot fail on such warnings, so I would like to first fix all these warnings.

http://buildbot.python.org/all/builders/AMD64%20Windows8.1%20Refleaks%203.x/builds/59/steps/test/logs/stdio

0:46:17 [119/406] test_multiprocessing_spawn passed (2667 sec) -- running: test_asyncio (290 sec), test_userstring (54 sec), test_regrtest (471 sec)
beginning 6 repetitions
123456
...Warning -- Dangling processes: {\<Process(Process-1235, stopped daemon)\>}
...

**Comment by vstinner** [comment]
With the commit 957d0e9b59bd27ca7c473560634d8b5dbe66338c (bpo-26762), \_test_multiprocessing now fails with ENV_CHANGED if a warning is emitted. It allowed to catch a warning on x86-64 El Capitan 3.x:

http://buildbot.python.org/all/builders/x86-64%20El%20Capitan%203.x/builds/581/steps/test/logs/stdio

test_enable_logging (test.test_multiprocessing_spawn.WithProcessesTestLogging) ... ok
test_level (test.test_multiprocessing_spawn.WithProcessesTestLogging) ... ok
test_rapid_restart (test.test_multiprocessing_spawn.WithProcessesTestManagerRestart) ... ok
Warning -- Dangling processes: {\<Process(Process-181, stopped daemon)\>}
test_access (test.test_multiprocessing_spawn.WithProcessesTestPicklingConnections) ... ok
test_pickling (test.test_multiprocessing_spawn.WithProcessesTestPicklingConnections) ... ok
test_boundaries (test.test_multiprocessing_spawn.WithProcessesTestPoll) ... ok

**Comment by vstinner** [comment]
Another warning on x86 Tiger 3.x:

http://buildbot.python.org/all/builders/x86%20Tiger%203.x/builds/1043/steps/test/logs/stdio

test_rapid_restart (test.test_multiprocessing_forkserver.WithProcessesTestManagerRestart) ... ok
Warning -- Dangling processes: {\<Process(Process-181, stopped daemon)\>}
test_access (test.test_multiprocessing_forkserver.WithProcessesTestPicklingConnections) ... ok

**Comment by vstinner** [comment]
See also bpo-30846.

**Comment by vstinner** [comment]
I marked bpo-30846 as a duplicate of this issue. Copy of its message:

http://buildbot.python.org/all/builders/AMD64%20Debian%20PGO%203.6/builds/517/steps/test/logs/stdio

\======================================================================
ERROR: test_rapid_restart (test.test_multiprocessing_fork.WithProcessesTestManagerRestart)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.6.gps-debian-profile-opt.nondebug/build/Lib/test/_test_multiprocessing.py", line 2410, in test_rapid_restart
    manager.start()
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.6.gps-debian-profile-opt.nondebug/build/Lib/multiprocessing/managers.py", line 517, in start
    self._address = reader.recv()
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.6.gps-debian-profile-opt.nondebug/build/Lib/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.6.gps-debian-profile-opt.nondebug/build/Lib/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.6.gps-debian-profile-opt.nondebug/build/Lib/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
(...)
Re-running test 'test_multiprocessing_fork' in verbose mode
(...)
test_rapid_restart (test.test_multiprocessing_fork.WithManagerTestManagerRestart) ... ok
```

**Comment by vstinner** [comment]
AppVeyor:

https://ci.appveyor.com/project/python/cpython/build/3.7.0a0.5341

test_lock_context (test.test_multiprocessing_spawn.WithProcessesTestLock) ... ok
test_rlock (test.test_multiprocessing_spawn.WithProcessesTestLock) ... ok
test_enable_logging (test.test_multiprocessing_spawn.WithProcessesTestLogging) ... ok
test_level (test.test_multiprocessing_spawn.WithProcessesTestLogging) ... ok
test_rapid_restart (test.test_multiprocessing_spawn.WithProcessesTestManagerRestart) ... ok
Warning -- Dangling processes: {\<Process(Process-174, stopped daemon)\>}
test_access (test.test_multiprocessing_spawn.WithProcessesTestPicklingConnections) ... ok

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86-64%20El%20Capitan%203.x/builds/590/steps/test/logs/stdio

test_enable_logging (test.test_multiprocessing_forkserver.WithProcessesTestLogging) ... ok
test_level (test.test_multiprocessing_forkserver.WithProcessesTestLogging) ... ok
test_rapid_restart (test.test_multiprocessing_forkserver.WithProcessesTestManagerRestart) ... ok
Warning -- Dangling processes: {\<Process(Process-181, stopped daemon)\>}
test_access (test.test_multiprocessing_forkserver.WithProcessesTestPicklingConnections) ... ok
test_pickling (test.test_multiprocessing_forkserver.WithProcessesTestPicklingConnections) ... ok

(...)


test_level (test.test_multiprocessing_spawn.WithProcessesTestLogging) ... ok
test_rapid_restart (test.test_multiprocessing_spawn.WithProcessesTestManagerRestart) ... ok
Warning -- Dangling processes: {\<Process(Process-181, stopped daemon)\>}
test_access (test.test_multiprocessing_spawn.WithProcessesTestPicklingConnections) ... ok
test_pickling (test.test_multiprocessing_spawn.WithProcessesTestPicklingConnections) ... ok

**Comment by vstinner** [comment]
New changeset 17657bb9458ff8f8804b7637d61686a68f4b9471 by Victor Stinner in branch 'master':
bpo-31069, test_multiprocessing: Fix dangling process (bpo-3103)
https://github.com/python/cpython/commit/17657bb9458ff8f8804b7637d61686a68f4b9471

**Comment by vstinner** [comment]
New changeset 78c66a641a0d4fe61356ebfae8772e4fae24dcb7 by Victor Stinner in branch '3.6':
bpo-31069, test_multiprocessing: Fix dangling process (bpo-3103) (bpo-3104)
https://github.com/python/cpython/commit/78c66a641a0d4fe61356ebfae8772e4fae24dcb7

**Comment by vstinner** [comment]
New changeset 883520a846d87f01a14636978cfa9cee1ecc07c1 by Victor Stinner in branch '2.7':
bpo-31069, test_multiprocessing: Fix dangling process (bpo-3103) (bpo-3105)
https://github.com/python/cpython/commit/883520a846d87f01a14636978cfa9cee1ecc07c1

**Comment by vstinner** [comment]
Ok, the main bug should have been fixed. I will reopen it if it's not the case, or open a new issue if a second bug is seen on buildbots.

**Comment by vstinner** [comment]
Too bad, the bug is not dead, I reopen the issue.

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%2010.x%20Shared%203.x/builds/800/steps/test/logs/stdio

test_rlock (test.test_multiprocessing_forkserver.WithThreadsTestLock) ... ok
test_rapid_restart (test.test_multiprocessing_forkserver.WithThreadsTestManagerRestart) ... ok
Warning -- Dangling processes: {\<ForkServerProcess(QueueManager-465, stopped)\>}
test_boundaries (test.test_multiprocessing_forkserver.WithThreadsTestPoll) ... ok
test_dont_merge (test.test_multiprocessing_forkserver.WithThreadsTestPoll) ... ok

**Comment by vstinner** [comment]
Failure on AMD64 FreeBSD 10.x Shared 3.x:

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%2010.x%20Shared%203.x/builds/868/steps/test/logs/stdio

...
test_map_chunksize (test.test_multiprocessing_forkserver.WithThreadsTestPool) ... ok
test_map_handle_iterable_exception (test.test_multiprocessing_forkserver.WithThreadsTestPool) ... ok
test_map_no_failfast (test.test_multiprocessing_forkserver.WithThreadsTestPool) ... ok
test_map_unplicklable (test.test_multiprocessing_forkserver.WithThreadsTestPool) ... skipped 'test not appropriate for threads'
test_release_task_refs (test.test_multiprocessing_forkserver.WithThreadsTestPool) ... ok
test_starmap (test.test_multiprocessing_forkserver.WithThreadsTestPool) ... ok
test_starmap_async (test.test_multiprocessing_forkserver.WithThreadsTestPool) ... ok
test_terminate (test.test_multiprocessing_forkserver.WithThreadsTestPool) ... ok
test_traceback (test.test_multiprocessing_forkserver.WithThreadsTestPool) ... ok
test_wrapped_exception (test.test_multiprocessing_forkserver.WithThreadsTestPool) ... ok
Warning -- Dangling threads: {\<DummyProcess(Thread-158, started daemon 34461984768)\>}
test_active_children (test.test_multiprocessing_forkserver.WithThreadsTestProcess) ... ok

**Comment by vstinner** [comment]
On the FreeBSD 10 buildbot, I ran test_multiprocessing_forkserver during 10 minutes twice in two terminals, while running "./python -m test -j2 -r -F" twice in two other terminals to stress the machine. I failed to reproduce the "Warning -- Dangling threads: {\<DummyProcess(Thread-158, started daemon 34461984768)\>}" warning.

**Comment by vstinner** [comment]
New test_multiprocessing_fork failure on AMD64 FreeBSD CURRENT Debug 3.x:

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Debug%203.x/builds/869/steps/test/logs/stdio

(...)
test_traceback (test.test_multiprocessing_fork.WithThreadsTestPool) ... ok
test_wrapped_exception (test.test_multiprocessing_fork.WithThreadsTestPool) ... ok
Warning -- Dangling threads: {\<DummyProcess(Thread-158, started daemon 34496780800)\>}
test_active_children (test.test_multiprocessing_fork.WithThreadsTestProcess) ... ok
(...)

**Comment by vstinner** [comment]
I continued the effort to fix all "dangling threads/processes" in bpo-31234, so I close this issue.
