### ISSUE TITLE
import error for numpy

### ISSUE THREAD

**Issue by db4b668c-5734-4ca5-a8b0-162f6c476f94** [python/cpython#75273]
BPO | [31090](https://bugs.python.org/issue31090)
--- | :---
Nosy | @mdickinson, @SriramSudharsan
Files | <li>[Capture.JPG](https://bugs.python.org/file47053/Capture.JPG "Uploaded as image/jpeg at 2017-07-31.14:44:19 by @SriramSudharsan"): ScreenShot for Failed lib</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-31.14:49:04.032>
created_at = <Date 2017-07-31.14:44:19.649>
labels = ['library']
title = 'import error for numpy'
updated_at = <Date 2017-07-31.16:15:24.446>
user = 'https://github.com/SriramSudharsan'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-31.16:15:24.446>
actor = 'SriramSudharsan'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-31.14:49:04.032>
closer = 'mark.dickinson'
components = ['Library (Lib)']
creation = <Date 2017-07-31.14:44:19.649>
creator = 'SriramSudharsan'
dependencies = []
files = ['47053']
hgrepos = []
issue_num = 31090
keywords = []
message_count = 3.0
messages = ['299559', '299560', '299570']
nosy_count = 2.0
nosy_names = ['mark.dickinson', 'SriramSudharsan']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31090'
versions = ['Python 3.6']
```

</p></details>

**Comment by db4b668c-5734-4ca5-a8b0-162f6c476f94** [comment]
When i tried to import numpy for any program in VS 2017, it returns with Import Error.

```pytb
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\TestApp1\TestApp1\TestApp1.py", line 1, in <module>
    import numpy as np
  File "C:\Program Files\Python36\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Program Files\Python36\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Program Files\Python36\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Program Files\Python36\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
```


Original error was: DLL load failed: The specified procedure could not be found.

Press any key to continue . . .

**Comment by mdickinson** [comment]
Hi Sriram,

NumPy is a third party package, not maintained by the Python core developers; you likely need to report this on the NumPy bug tracker (though it's probably worthwhile asking on the NumPy user mailing lists first).

Closing here, since this almost certainly isn't a core Python issue.

**Comment by db4b668c-5734-4ca5-a8b0-162f6c476f94** [comment]
Yes, i just found that after creating the issue, Sorry. 

Anyhow thanks for quick response, i have addressed this to numpy team.
https://github.com/numpy/numpy/issues/9501
