### ISSUE TITLE
ImportError: cannot import name HAS_ALPN

### ISSUE THREAD

**Issue by 29ad2596-6954-42c6-8ef0-cd51ba73b13b** [python/cpython#75307]
BPO | [31124](https://bugs.python.org/issue31124)
--- | :---
Nosy | @pfmoore, @tiran, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2017-08-05.14:55:02.568>
created_at = <Date 2017-08-05.13:41:21.559>
labels = ['expert-SSL', 'type-bug', 'OS-windows']
title = 'ImportError: cannot import name HAS_ALPN'
updated_at = <Date 2017-08-05.15:22:04.461>
user = 'https://bugs.python.org/Jhleite'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-05.15:22:04.461>
actor = 'Jhleite'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2017-08-05.14:55:02.568>
closer = 'christian.heimes'
components = ['Windows', 'SSL']
creation = <Date 2017-08-05.13:41:21.559>
creator = 'Jhleite'
dependencies = []
files = []
hgrepos = []
issue_num = 31124
keywords = []
message_count = 5.0
messages = ['299781', '299782', '299785', '299786', '299789']
nosy_count = 6.0
nosy_names = ['paul.moore', 'christian.heimes', 'tim.golden', 'zach.ware', 'steve.dower', 'Jhleite']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31124'
versions = ['Python 2.7']
```

</p></details>

**Comment by 29ad2596-6954-42c6-8ef0-cd51ba73b13b** [comment]
When Running Web2py with Python 2.7.11 or 2.7.13 in windows 10 I get the following error:

```pytb
Traceback (most recent call last):
File "C:\web2py\web2py.py", line 21, in 
import gluon.widget
File "C:\web2py\gluon\widget.py", line 26, in 
from gluon import main, newcron
File "C:\web2py\gluon\main.py", line 28, in 
import ssl
File "C:\Python27\lib\ssl.py", line 126, in 
from _ssl import HAS_SNI, HAS_ECDH, HAS_NPN, HAS_ALPN
ImportError: cannot import name HAS_ALPN
```


----------------------------------------------------
It seem like a windows Python bug in \_ssl.py

**Comment by tiran** [comment]
There is no \_ssl.py. The internal \_ssl module is a C extension module. Under Windows it is called \_ssl.pyd. Do you have a \_ssl.py  or \_ssl package in your project that may confict with \_ssl.pyd?

**Comment by 29ad2596-6954-42c6-8ef0-cd51ba73b13b** [comment]
Yes, there is such a file. I will report to web2py developers for windows version.
Thanks, renamed the file and everything seems fine.

**Comment by tiran** [comment]
Thanks!

**Comment by 29ad2596-6954-42c6-8ef0-cd51ba73b13b** [comment]
Thank You very much!!!
Thumbs up!
