### ISSUE TITLE
unittest mock's reset_mock throws an error when an attribute has been deleted

### ISSUE THREAD

**Issue by f8e93c29-ea26-4956-a7ed-0734d988510b** [python/cpython#75360]
BPO | [31177](https://bugs.python.org/issue31177)
--- | :---
Nosy | @vstinner, @cjw296, @voidspace, @eli-b, @mariocj89, @miss-islington, @tirkarthi
PRs | <li>python/cpython#9302</li><li>python/cpython#10807</li><li>python/cpython#10836</li><li>python/cpython#10842</li><li>python/cpython#10843</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-12-01.17:58:42.475>
created_at = <Date 2017-08-10.14:22:19.659>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = "unittest mock's reset_mock throws an error when an attribute has been deleted"
updated_at = <Date 2018-12-01.17:58:42.473>
user = 'https://bugs.python.org/hmvp'
```

bugs.python.org fields:
```python
activity = <Date 2018-12-01.17:58:42.473>
actor = 'xtreak'
assignee = 'none'
closed = True
closed_date = <Date 2018-12-01.17:58:42.475>
closer = 'xtreak'
components = ['Library (Lib)']
creation = <Date 2017-08-10.14:22:19.659>
creator = 'hmvp'
dependencies = []
files = []
hgrepos = []
issue_num = 31177
keywords = ['patch']
message_count = 8.0
messages = ['300090', '325340', '326322', '330740', '330846', '330847', '330848', '330857']
nosy_count = 8.0
nosy_names = ['vstinner', 'cjw296', 'michael.foord', 'Eli_B', 'mariocj89', 'hmvp', 'miss-islington', 'xtreak']
pr_nums = ['9302', '10807', '10836', '10842', '10843']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31177'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by f8e93c29-ea26-4956-a7ed-0734d988510b** [comment]
When using a mock and deleting a attribute reset_mock cannot be used anymore since it tries to call reset_mock on the \_deleted sentinel value.

Reproduction path:
```
from unittest.mock import MagicMock
mock = MagicMock()
mock.a = 'test'
del mock.a
mock.reset_mock()
```

Gives:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/unittest/mock.py", line 544, in reset_mock
    child.reset_mock(visited)
AttributeError: '_SentinelObject' object has no attribute 'reset_mock'
```

Expected result:
mock is reset without throwing an exception and the 'a' attribute is no longer in a deleted state

Only checked 3.5 and current master if bug is present
