### ISSUE TITLE
`python setup.py check --restructuredtext` fails when a include directive is present.

### ISSUE THREAD

**Issue by 0b4aa519-e666-44ff-8049-c1f789aa0036** [python/cpython#75473]
BPO | [31292](https://bugs.python.org/issue31292)
--- | :---
Nosy | @merwok, @flying-sheep, @dstufft, @csabella, @miss-islington
PRs | <li>python/cpython#3248</li><li>python/cpython#10605</li><li>python/cpython#12593</li><li>python/cpython#12594</li>
Files | <li>[check-test.py](https://bugs.python.org/file47104/check-test.py "Uploaded as text/plain at 2017-08-28.13:57:45 by @flying-sheep"): Demo script for this issue</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-03-27.21:49:22.114>
created_at = <Date 2017-08-28.13:57:45.748>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = '`python setup.py check --restructuredtext` fails when a include directive is present.'
updated_at = <Date 2019-03-27.22:26:00.429>
user = 'https://github.com/flying-sheep'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-27.22:26:00.429>
actor = 'miss-islington'
assignee = 'none'
closed = True
closed_date = <Date 2019-03-27.21:49:22.114>
closer = 'cheryl.sabella'
components = ['Distutils']
creation = <Date 2017-08-28.13:57:45.748>
creator = 'flying sheep'
dependencies = []
files = ['47104']
hgrepos = []
issue_num = 31292
keywords = ['patch']
message_count = 6.0
messages = ['300953', '301031', '338987', '338989', '338990', '338991']
nosy_count = 5.0
nosy_names = ['eric.araujo', 'flying sheep', 'dstufft', 'cheryl.sabella', 'miss-islington']
pr_nums = ['3248', '10605', '12593', '12594']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31292'
versions = ['Python 2.7', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 0b4aa519-e666-44ff-8049-c1f789aa0036** [comment]
If I have a setup.py containing a include directive, and use the command in the title, I get


```pytb
Traceback (most recent call last):
  [...]
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/directives/misc.py", line 59, in run
    source_dir = os.path.dirname(os.path.abspath(source))
  File "/usr/lib/python3.6/posixpath.py", line 369, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not _io.StringIO
```



The bug is in this method: distutils.command.check.check.\_check_rst_data

The first line already hints at it: `source_path = StringIO()`

StringIO instances aren’t paths, but at least the include directive (docutils.parsers.rst.directives.misc.Include) expects one.

**Comment by 0b4aa519-e666-44ff-8049-c1f789aa0036** [comment]
I should have linked the file: distutils/command/check.py
