### ISSUE TITLE
File paths in exception traceback resolve symlinks

### ISSUE THREAD

**Issue by 0c97e840-ae8b-4fa9-b95e-fe2331d61b5b** [python/cpython#75470]
BPO | [31289](https://bugs.python.org/issue31289)
--- | :---
Nosy | @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-06-14.20:04:45.707>
created_at = <Date 2017-08-27.20:17:56.591>
labels = ['interpreter-core', 'type-bug']
title = 'File paths in exception traceback resolve symlinks'
updated_at = <Date 2021-06-14.20:04:45.706>
user = 'https://bugs.python.org/PaulPinterits'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-14.20:04:45.706>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-06-14.20:04:45.707>
closer = 'iritkatriel'
components = ['Interpreter Core']
creation = <Date 2017-08-27.20:17:56.591>
creator = 'Paul Pinterits'
dependencies = []
files = []
hgrepos = []
issue_num = 31289
keywords = []
message_count = 3.0
messages = ['300926', '381405', '395844']
nosy_count = 2.0
nosy_names = ['Paul Pinterits', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31289'
versions = ['Python 2.7', 'Python 3.6']
```

</p></details>

**Comment by 0c97e840-ae8b-4fa9-b95e-fe2331d61b5b** [comment]
The file paths displayed in exception tracebacks have their symlinks resolved. I would prefer if the "original" path could be displayed instead, because resolved symlinks result in unexpected paths in the traceback and can be quite confusing.

An example:

rawing@localhost \~\> cat test_scripts/A.py
import B
B.throw()

rawing@localhost \~\> cat test_scripts/B.py
def throw():
    raise ValueError

rawing@localhost \~\> ln -s test_scripts test_symlink

```pytb
rawing@localhost ~> python3 test_symlink/A.py
Traceback (most recent call last):
  File "test_symlink/A.py", line 2, in <module>
    B.throw()
  File "/home/rawing/test_scripts/B.py", line 2, in throw
    raise ValueError
ValueError
```


As you can see, even though both scripts reside in the same directory, the file paths displayed in the traceback look very different. At first glance, it looks like B is in a completely different place than A.
Furthermore, this behavior tends to trip up IDEs - PyCharm for example does not understand that test_scripts/B.py and test_symlink/B.py are the same file, so I end up having the same file opened in two different tabs.

Would it be possible to change this behavior and have "/home/rawing/test_symlink/B.py" show up in the traceback instead?
