### ISSUE TITLE
Travis CI coverage job fails on Python 3.6

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75533]
BPO | [31352](https://bugs.python.org/issue31352)
--- | :---
Nosy | @vstinner, @nedbat
Superseder | <li>bpo-30445: test_traceback fails in coverage run</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-05.20:50:09.968>
created_at = <Date 2017-09-05.20:42:21.304>
labels = []
title = 'Travis CI coverage job fails on Python 3.6'
updated_at = <Date 2017-09-05.22:14:56.806>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-05.22:14:56.806>
actor = 'nedbat'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-05.20:50:09.968>
closer = 'vstinner'
components = []
creation = <Date 2017-09-05.20:42:21.304>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31352
keywords = []
message_count = 2.0
messages = ['301369', '301373']
nosy_count = 2.0
nosy_names = ['vstinner', 'nedbat']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30445'
type = None
url = 'https://bugs.python.org/issue31352'
versions = ['Python 3.6']
```

</p></details>

**Comment by vstinner** [comment]
haypo@selma$ ./python -m venv env
haypo@selma$ env/bin/python -m pip install coverage
haypo@selma$ ./env/bin/python -m coverage run --pylib -m test -uall,-cpu test_traceback
(...)
\======================================================================
FAIL: test_recursive_traceback_cpython_internal (test.test_traceback.TracebackFormatTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/haypo/prog/python/3.6/Lib/test/test_traceback.py", line 431, in test_recursive_traceback_cpython_internal
    self._check_recursive_traceback_display(render_exc)
  File "/home/haypo/prog/python/3.6/Lib/test/test_traceback.py", line 347, in _check_recursive_traceback_display
    self.assertEqual(actual[-1], expected[-1])
AssertionError: 'RecursionError: maximum recursion depth exceeded in comparison' != 'RecursionError: maximum recursion depth exceeded'
- RecursionError: maximum recursion depth exceeded in comparison
?                                                 
```
--------------
\+ RecursionError: maximum recursion depth exceeded


\======================================================================
FAIL: test_recursive_traceback_python (test.test_traceback.TracebackFormatTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/haypo/prog/python/3.6/Lib/test/test_traceback.py", line 423, in test_recursive_traceback_python
    self._check_recursive_traceback_display(traceback.print_exc)
  File "/home/haypo/prog/python/3.6/Lib/test/test_traceback.py", line 347, in _check_recursive_traceback_display
    self.assertEqual(actual[-1], expected[-1])
AssertionError: 'RecursionError: maximum recursion depth exceeded in comparison' != 'RecursionError: maximum recursion depth exceeded'
- RecursionError: maximum recursion depth exceeded in comparison
?                                                 
```
--------------
\+ RecursionError: maximum recursion depth exceeded

**Comment by vstinner** [comment]
Duplicate of bpo-30445.
