### ISSUE TITLE
Configure and make will fail with enabling --with-pydebug

### ISSUE THREAD

**Issue by 0ef32094-ac0f-4f5c-860c-3bd95790dfc5** [python/cpython#75577]
BPO | [31396](https://bugs.python.org/issue31396)
--- | :---
Nosy | @tiran, @kevin-coder

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-08.17:25:15.989>
created_at = <Date 2017-09-08.17:19:03.181>
labels = ['invalid', 'build', '3.7']
title = 'Configure and make will fail with enabling --with-pydebug'
updated_at = <Date 2017-09-08.17:25:15.987>
user = 'https://github.com/kevin-coder'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-08.17:25:15.987>
actor = 'christian.heimes'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-08.17:25:15.989>
closer = 'christian.heimes'
components = ['Build']
creation = <Date 2017-09-08.17:19:03.181>
creator = 'huzq85'
dependencies = []
files = []
hgrepos = []
issue_num = 31396
keywords = []
message_count = 2.0
messages = ['301701', '301702']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'huzq85']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31396'
versions = ['Python 3.7']
```

</p></details>

**Comment by 0ef32094-ac0f-4f5c-860c-3bd95790dfc5** [comment]
When I updated the source code into the latest version, and configure as well as build with following command:
./configure --with-pydebug && make -j4
Build will fail with following error message:
\==================================================================
```pytb
Could not import runpy module
Traceback (most recent call last):
  File "/home/kevin/research/openSource/cpython/Lib/runpy.py", line 14, in <module>
    import importlib.machinery # importlib first so we can test python/cpython#59591 via -m
  File "/home/kevin/research/openSource/cpython/Lib/importlib/__init__.py", line 57, in <module>
    import types
  File "/home/kevin/research/openSource/cpython/Lib/types.py", line 175, in <module>
    import functools as _functools
  File "/home/kevin/research/openSource/cpython/Lib/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/home/kevin/research/openSource/cpython/Lib/collections/__init__.py", line 32, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/home/kevin/research/openSource/cpython/Lib/reprlib.py", line 7, in <module>
    from _thread import get_ident
ModuleNotFoundError: No module named '_thread'
generate-posix-vars failed
Makefile:561: recipe for target 'pybuilddir.txt' failed
make: *** [pybuilddir.txt] Error 1
```
==================================================================

**Comment by tiran** [comment]
You have to restart with a clean checkout. Either run ``make distclean`` or ``git clean -xdf`` to get rid of all build files.
