### ISSUE TITLE
test_socket.SendfileUsingSendfileTest.testWithTimeoutTriggeredSend fails due to sendfile completing before timeout

### ISSUE THREAD

**Issue by 92f38d4c-d4b8-4acf-9bd6-fd130807dcf8** [python/cpython#75618]
BPO | [31437](https://bugs.python.org/issue31437)
--- | :---
Nosy | @bmoyles

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-12.22:46:44.387>
created_at = <Date 2017-09-12.22:32:54.351>
labels = ['tests']
title = 'test_socket.SendfileUsingSendfileTest.testWithTimeoutTriggeredSend fails due to sendfile completing before timeout'
updated_at = <Date 2017-09-12.22:46:44.386>
user = 'https://github.com/bmoyles'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-12.22:46:44.386>
actor = 'bmoyles'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-12.22:46:44.387>
closer = 'bmoyles'
components = ['Tests']
creation = <Date 2017-09-12.22:32:54.351>
creator = 'bmoyles'
dependencies = []
files = []
hgrepos = []
issue_num = 31437
keywords = []
message_count = 2.0
messages = ['301999', '302000']
nosy_count = 1.0
nosy_names = ['bmoyles']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31437'
versions = ['Python 3.6']
```

</p></details>

**Comment by 92f38d4c-d4b8-4acf-9bd6-fd130807dcf8** [comment]
In building Python 3.6.2 on Ubuntu 16.04, test_socket repeatedly fails at
\======================================================================
FAIL: testWithTimeoutTriggeredSend (test.test_socket.SendfileUsingSendfileTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/mnt/python/Python-3.6.2/Lib/test/test_socket.py", line 277, in _tearDown
    raise exc
  File "/mnt/python/Python-3.6.2/Lib/test/test_socket.py", line 295, in clientRun
    test_func()
  File "/mnt/python/Python-3.6.2/Lib/test/test_socket.py", line 5358, in _testWithTimeoutTriggeredSend
    self.assertRaises(socket.timeout, meth, file)
AssertionError: timeout not raised by _sendfile_use_sendfile
```


----------------------------------------------------------------------

It appears this is failing as \_sendfile_use_sendfile completes before the 0.01s timeout set in \_testWithTimeoutTriggeredSend

Adjusting FILESIZE in class SendfileUsingSendTest to 100MB instead of 10MB (or creating FILESIZE on class SendfileUsingSendfileTest so only that set of tests uses a 100MB file) succeeds.

bpo-17085 was a similar bug from a few years ago but I'm not sure that this can or should be solved in the same way...

**Comment by 92f38d4c-d4b8-4acf-9bd6-fd130807dcf8** [comment]
accidental double-submit, duplicates bpo-31436
