### ISSUE TITLE
test_normalization: test.support.open_urlresource() doesn't handle urllib.error.URLError timeout

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75692]
BPO | [31511](https://bugs.python.org/issue31511)
--- | :---
Nosy | @vstinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-21.23:06:11.252>
created_at = <Date 2017-09-18.16:29:16.022>
labels = ['3.7', 'tests']
title = "test_normalization: test.support.open_urlresource() doesn't handle urllib.error.URLError timeout"
updated_at = <Date 2018-09-21.23:06:11.251>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-21.23:06:11.251>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-21.23:06:11.252>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-09-18.16:29:16.022>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31511
keywords = []
message_count = 1.0
messages = ['302473']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31511'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20Debian%20PGO%203.x/builds/1316/steps/test/logs/stdio

\======================================================================
FAIL: test_main (test.test_normalization.NormalizationTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.x.gps-debian-profile-opt.nondebug/build/Lib/urllib/request.py", line 1316, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.x.gps-debian-profile-opt.nondebug/build/Lib/test/test_normalization.py", line 42, in test_main
    check=check_version)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/buildbot/slaves/enable-optimizations-bot/3.x.gps-debian-profile-opt.nondebug/build/Lib/test/test_normalization.py", line 47, in test_main
    self.fail(f"Could not retrieve {TESTDATAURL}")
AssertionError: Could not retrieve http://www.pythontest.net/unicode/10.0.0/NormalizationTest.txt
```
