### ISSUE TITLE
Report details of excess arguments in object_new & object_init

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#75708]
BPO | [31527](https://bugs.python.org/issue31527)
--- | :---
Nosy | @ncoghlan, @serhiy-storchaka
Dependencies | <li>bpo-31506: Improve the error message logic for object_new &amp; object_init</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-09-20.05:17:57.406>
labels = ['type-feature']
title = 'Report details of excess arguments in object_new & object_init'
updated_at = <Date 2017-09-20.06:14:25.997>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-20.06:14:25.997>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2017-09-20.05:17:57.406>
creator = 'ncoghlan'
dependencies = ['31506']
files = []
hgrepos = []
issue_num = 31527
keywords = []
message_count = 3.0
messages = ['302591', '302592', '302597']
nosy_count = 2.0
nosy_names = ['ncoghlan', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31527'
versions = []
```

</p></details>

**Comment by ncoghlan** [comment]
object_new and object_init currently use their own argument checking logic, and hence haven't benefited from the error reporting enhancements in PyArg_ParseTupleAndKeywords

Compare:

```pycon
>>> str(1, 2, 3, 4, 5, x=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: str() takes at most 3 arguments (6 given)
>>> str(x=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'x' is an invalid keyword argument for this function
```


To:

```pycon
>>> C(1, 2, 3, 4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object() takes no parameters
>>> C(x=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object() takes no parameters
```


bpo-31506 amends the latter to at least report the subclass name rather than the base class name, but doesn't cover any other enhancements, like reporting how many arguments were actually given, or the first unknown keyword argument name.

**Comment by ncoghlan** [comment]
Adding a dependency on bpo-31506, as this shouldn't be tackled until those simpler amendments are resolved.

**Comment by serhiy-storchaka** [comment]
str(x=1) is not the best example since str() takes keyword arguments. Look at tuple() and list():

```pycon
>>> tuple(x=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: tuple() takes no keyword arguments
>>> list(x=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: list() takes no keyword arguments
```


Initial version of my patch for bpo-31506 reported error messages similar to tuple() and list(), but at end I simplified it since in any case the error message was not perfect.
