### ISSUE TITLE
Inconsistent error message for TypeError with subscripting

### ISSUE THREAD

**Issue by 341ce0e2-bdbb-4bd4-99e6-746f11201a3f** [python/cpython#75731]
BPO | [31550](https://bugs.python.org/issue31550)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka, @asottile
PRs | <li>python/cpython#3692</li><li>python/cpython#6151</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2018-03-27.15:39:31.105>
created_at = <Date 2017-09-22.03:32:38.210>
labels = ['interpreter-core', 'type-bug']
title = 'Inconsistent error message for TypeError with subscripting'
updated_at = <Date 2018-03-27.15:39:31.104>
user = 'https://github.com/asottile'
```

bugs.python.org fields:
```python
activity = <Date 2018-03-27.15:39:31.104>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2018-03-27.15:39:31.105>
closer = 'rhettinger'
components = ['Interpreter Core']
creation = <Date 2017-09-22.03:32:38.210>
creator = 'Anthony Sottile'
dependencies = []
files = []
hgrepos = []
issue_num = 31550
keywords = ['patch']
message_count = 11.0
messages = ['302736', '302738', '302756', '302848', '302868', '314106', '314115', '314116', '314118', '314506', '314535']
nosy_count = 3.0
nosy_names = ['rhettinger', 'serhiy.storchaka', 'Anthony Sottile']
pr_nums = ['3692', '6151']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31550'
versions = ['Python 2.7']
```

</p></details>

**Comment by 341ce0e2-bdbb-4bd4-99e6-746f11201a3f** [comment]
There's a bit of history I don't understand and couldn't find the appropriate trail for.

The original error message from the 2.6 era:

```pytb
$ python2.6 -c 0[0]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'int' object is unsubscriptable
```



This was changed in https://github.com/python/cpython/commit/f5fd5239819c5dfb1d7a33484be49dc705544d02 for clarity

As seen in 2.7.1

```pytb
$ ./python2.7.1 -c 0[0]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'int' object is not subscriptable
```



It was later changed in the 2.7 era here: 
https://github.com/python/cpython/commit/7d1483cbadbe48620964348a2039690624e7dc8e


To this error message (as demonstrated with 2.7.12):

```pytb
$ python2.7 -c 0[0]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'int' object has no attribute '__getitem__'
```



However, this patch never made it into the 3.x branch:

```pytb
$ python3.6 -c 0[0]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'int' object is not subscriptable
```



Should this patch be (have been) cherry picked into master?

**Comment by serhiy-storchaka** [comment]
I'm not sure that this is an enhancement. It makes an error message inconsistent with other error messages.

```pycon
>>> class I(int): pass
... 
>>> I()[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'I' object does not support indexing
>>> 0[0] = 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object does not support item assignment
>>> del 0[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object does not support item deletion
>>> ''['']                                                                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                                           
  File "<stdin>", line 1, in <module>                                                                                                                                                                                                        
TypeError: string indices must be integers, not str                                                                                                                                                                                          
>>> iter(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not iterable
>>> reversed(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument to reversed() must be a sequence
>>> next(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int object is not an iterator
>>> {}[[]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```


And actually this message is misleading. An attribute '\_\_getitem__' is not looked up on objects.

```pycon
>>> class I(int): pass
... 
>>> x = I()
>>> x.__getitem__ = lambda *args: None
>>> I()[0:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'I' object has no attribute '__getitem__'
>>> x.__getitem__
<function <lambda> at 0x7f11b62dd648>
```

**Comment by 341ce0e2-bdbb-4bd4-99e6-746f11201a3f** [comment]
All I'm really looking for is consistency -- should the change to 2.7 be reverted instead?

**Comment by serhiy-storchaka** [comment]
I think it should. But let to hear Raymond's arguments.

**Comment by 341ce0e2-bdbb-4bd4-99e6-746f11201a3f** [comment]
Shouldn't you wait for Raymond's arguments before outright closing the PR?
