### ISSUE TITLE
test_distutils fails if current directory contains spaces

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75732]
BPO | [31551](https://bugs.python.org/issue31551)
--- | :---
Nosy | @merwok, @serhiy-storchaka, @zooba, @dstufft, @tirkarthi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-02-03.18:16:31.403>
created_at = <Date 2017-09-22.10:39:31.729>
labels = ['3.7', 'tests', '3.8', 'type-bug', 'library']
title = 'test_distutils fails if current directory contains spaces'
updated_at = <Date 2021-02-03.18:16:31.401>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-03.18:16:31.401>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2021-02-03.18:16:31.403>
closer = 'steve.dower'
components = ['Distutils', 'Tests']
creation = <Date 2017-09-22.10:39:31.729>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31551
keywords = []
message_count = 3.0
messages = ['302741', '326518', '386321']
nosy_count = 5.0
nosy_names = ['eric.araujo', 'serhiy.storchaka', 'steve.dower', 'dstufft', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31551'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Running tests from the directory containing a space: '/home/serhiy/py/cpy thon'.

```sh
$ ./python -m test -vuall test_distutils
== CPython 3.7.0a1+ (heads/master:5e02c7826f, Sep 22 2017, 13:23:33) [GCC 6.3.0 20170406]
== Linux-4.10.0-35-generic-x86_64-with-debian-stretch-sid little-endian
== cwd: /home/serhiy/py/cpy thon/build/test_python_11135
== CPU count: 8
== encodings: locale=UTF-8, FS=utf-8
Run tests sequentially
0:00:00 load avg: 0.09 [1/1] test_distutils
test_no_optimize_flag (distutils.tests.test_bdist_rpm.BuildRpmTestCase) ... /var/tmp/rpm-tmp.ufRiE4: 28: /var/tmp/rpm-tmp.ufRiE4: /home/serhiy/py/cpy: not found
error: Bad exit status from /var/tmp/rpm-tmp.ufRiE4 (%build)
    Bad exit status from /var/tmp/rpm-tmp.ufRiE4 (%build)
ERROR
test_quiet (distutils.tests.test_bdist_rpm.BuildRpmTestCase) ... /var/tmp/rpm-tmp.uBva85: 28: /var/tmp/rpm-tmp.uBva85: /home/serhiy/py/cpy: not found
error: Bad exit status from /var/tmp/rpm-tmp.uBva85 (%build)
    Bad exit status from /var/tmp/rpm-tmp.uBva85 (%build)
ERROR
...
```

======================================================================
ERROR: test_no_optimize_flag (distutils.tests.test_bdist_rpm.BuildRpmTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/serhiy/py/cpy thon/Lib/distutils/tests/test_bdist_rpm.py", line 120, in test_no_optimize_flag
    cmd.run()
  File "/home/serhiy/py/cpy thon/Lib/distutils/command/bdist_rpm.py", line 366, in run
    self.spawn(rpm_cmd)
  File "/home/serhiy/py/cpy thon/Lib/distutils/cmd.py", line 365, in spawn
    spawn(cmd, search_path, dry_run=self.dry_run)
  File "/home/serhiy/py/cpy thon/Lib/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/serhiy/py/cpy thon/Lib/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'rpmbuild' failed with exit status 1
```


======================================================================
ERROR: test_quiet (distutils.tests.test_bdist_rpm.BuildRpmTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/serhiy/py/cpy thon/Lib/distutils/tests/test_bdist_rpm.py", line 77, in test_quiet
    cmd.run()
  File "/home/serhiy/py/cpy thon/Lib/distutils/command/bdist_rpm.py", line 366, in run
    self.spawn(rpm_cmd)
  File "/home/serhiy/py/cpy thon/Lib/distutils/cmd.py", line 365, in spawn
    spawn(cmd, search_path, dry_run=self.dry_run)
  File "/home/serhiy/py/cpy thon/Lib/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/serhiy/py/cpy thon/Lib/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'rpmbuild' failed with exit status 1
```


----------------------------------------------------------------------

See also bpo-31548.
