### ISSUE TITLE
Enum doesn't allow name

### ISSUE THREAD

**Issue by f71c7f3d-2cb5-4391-957a-64cecae53714** [python/cpython#75768]
BPO | [31587](https://bugs.python.org/issue31587)
--- | :---
Nosy | @warsaw, @ethanfurman

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-26.09:52:05.070>
created_at = <Date 2017-09-26.06:58:17.041>
labels = ['3.7', 'type-bug', 'library']
title = "Enum doesn't allow name"
updated_at = <Date 2017-09-26.09:52:05.069>
user = 'https://bugs.python.org/RobertGomuka'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-26.09:52:05.069>
actor = 'Robert Gomu\xc5\x82ka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-26.09:52:05.070>
closer = 'Robert Gomu\xc5\x82ka'
components = ['Library (Lib)']
creation = <Date 2017-09-26.06:58:17.041>
creator = 'Robert Gomu\xc5\x82ka'
dependencies = []
files = []
hgrepos = []
issue_num = 31587
keywords = []
message_count = 3.0
messages = ['303017', '303018', '303027']
nosy_count = 4.0
nosy_names = ['barry', 'eli.bendersky', 'ethan.furman', 'Robert Gomu\xc5\x82ka']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31587'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by f71c7f3d-2cb5-4391-957a-64cecae53714** [comment]
Enum module handles "name" member incorrectly.
1. "name" can't be used as a member when decorated with unique:

```pycon
>>> import enum
>>> @enum.unique
... class A(enum.IntEnum):
...     a = 1
...     name = 2
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Python27\Lib\site-packages\enum\__init__.py", line 835, in unique
    (enumeration, duplicate_names)
ValueError: duplicate names found in <enum 'A'>: a -> A.name, name -> A.name
```


2. Without unique the names are assigned incorrectly:

```pycon
>>> class A(enum.IntEnum):
...     a = 1
...     name = 2
...
>>> A.__members__['a'].name
<A.name: 2>
>>> A.__members__['name'].name
<A.name: 2>
```


(Just for reference - spotted first on Python 2.7 + enum34 backports)

The same happens for value property, making the bug quite severe:

```pycon
>>> class A(enum.IntEnum):
...     a = 1
...     value = 3
...
>>> A.__members__['a'].value
<A.value: 3>
>>> A.__members__['value'].value
<A.value: 3>
```


I believe this comment is related:
# _RouteClassAttributeToGetattr is used to provide access to the `name`
# and `value` properties of enum members while keeping some measure of
# protection from modification, while still allowing for an enumeration
# to have members named `name` and `value`.  This works because enumeration
# members are not set directly on the enum class -- __getattr__ is
# used to look them up.


Platform: Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32

**Comment by f71c7f3d-2cb5-4391-957a-64cecae53714** [comment]
As a workaround, one can:
1. Rename the fields to not use name/value names
2. Use Enum instead of IntEnum, which somehow doesn't have this bug.

**Comment by f71c7f3d-2cb5-4391-957a-64cecae53714** [comment]
It turns out that enum34 backports module was the culprit (it was first on search path). When using enum native module, everything works as expected:

```pycon
> c:\Python\Python36-32\python.exe -I
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import enum
>>> enum
<module 'enum' from 'c:\\Python\\Python36-32\\lib\\enum.py'>
>>> @enum.unique
... class A(enum.IntEnum):
...     a = 1
...     name = 2
...     value = 3
...
>>> exit()

> c:\Python\Python36-32\python.exe
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import enum
>>> enum
<module 'enum' from 'C:\\Python27\\Lib\\site-packages\\enum\\__init__.py'>
>>> @enum.unique
... class A(enum.IntEnum):
...     a = 1
...     name = 2
...     value = 3
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Python27\Lib\site-packages\enum\__init__.py", line 835, in unique
    (enumeration, duplicate_names)
ValueError: duplicate names found in <enum 'A'>: a -> A.name, name -> A.name, value -> A.name
```


Sorry for the noise.
