### ISSUE TITLE
test_c_locale_coercion fails on OpenBSD

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75812]
BPO | [31631](https://bugs.python.org/issue31631)
--- | :---
Nosy | @ncoghlan, @vstinner, @serhiy-storchaka, @applio

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-09-29.08:55:25.391>
labels = ['type-bug', '3.7']
title = 'test_c_locale_coercion fails on OpenBSD'
updated_at = <Date 2017-09-29.09:45:23.505>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-29.09:45:23.505>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2017-09-29.08:55:25.391>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31631
keywords = []
message_count = 1.0
messages = ['303312']
nosy_count = 4.0
nosy_names = ['ncoghlan', 'vstinner', 'serhiy.storchaka', 'davin']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31631'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
```sh
$ ./python -m test -vuall test_c_locale_coercion
...
```


======================================================================
FAIL: test_external_target_locale_configuration (test.test_c_locale_coercion.LocaleConfigurationTests) (env_var='LC_CTYPE', configured_locale='UTF-8')
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/serhiy/py/cpython3.7/Lib/test/test_c_locale_coercion.py", line 254, in test_external_target_locale_configuration
    coercion_expected=False)
  File "/home/serhiy/py/cpython3.7/Lib/test/test_c_locale_coercion.py", line 209, in _check_child_encoding_details
    self.assertEqual(encoding_details, expected_details)
AssertionError: {'fsencoding': 'ascii', 'stdin_info': 'ascii:surrogateesc[128 chars]: ''} != {'fsencoding': 'utf-8', 'stdin_info': 'utf-8:surrogateesc[128 chars]: ''}
- {'fsencoding': 'ascii',
?                 ^^^^^
```


\+ {'fsencoding': 'utf-8',
?                 ^^^^^

   'lang': '',
   'lc_all': '',
   'lc_ctype': 'utf-8',
-  'stderr_info': 'ascii:backslashreplace',
?                  ^^^^^

\+  'stderr_info': 'utf-8:backslashreplace',
?                  ^^^^^

-  'stdin_info': 'ascii:surrogateescape',
?                 ^^^^^

\+  'stdin_info': 'utf-8:surrogateescape',
?                 ^^^^^

-  'stdout_info': 'ascii:surrogateescape'}
?                  ^^^^^

\+  'stdout_info': 'utf-8:surrogateescape'}
?                  ^^^^^


\----------------------------------------------------------------------

```sh
$ locale   
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_MESSAGES="C"
LC_ALL=
```


Similar issue is bpo-30836.
