### ISSUE TITLE
test_locale failure on OpenBSD

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75817]
BPO | [31636](https://bugs.python.org/issue31636)
--- | :---
Nosy | @malemburg, @loewis, @terryjreedy, @serhiy-storchaka, @applio, @tirkarthi
Superseder | <li>bpo-25191: test_getsetlocale_issue1813 failed on OpenBSD</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-12-08.13:42:43.080>
created_at = <Date 2017-09-29.09:39:33.419>
labels = ['3.7', 'type-bug', 'library']
title = 'test_locale failure on OpenBSD'
updated_at = <Date 2020-12-08.13:42:43.076>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-08.13:42:43.076>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2020-12-08.13:42:43.080>
closer = 'terry.reedy'
components = ['Library (Lib)']
creation = <Date 2017-09-29.09:39:33.419>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31636
keywords = ['patch']
message_count = 3.0
messages = ['303320', '326336', '382735']
nosy_count = 6.0
nosy_names = ['lemburg', 'loewis', 'terry.reedy', 'serhiy.storchaka', 'davin', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '25191'
type = 'behavior'
url = 'https://bugs.python.org/issue31636'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
```sh
$ ./python -m test -vuall -m test_getsetlocale_issue1813 test_locale 
...
test_getsetlocale_issue1813 (test.test_locale.TestMiscellaneous) ... testing with ('tr_TR', 'ISO8859-9') ERROR
```


======================================================================
ERROR: test_getsetlocale_issue1813 (test.test_locale.TestMiscellaneous)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/serhiy/py/cpython3.7/Lib/test/test_locale.py", line 531, in test_getsetlocale_issue1813
    locale.setlocale(locale.LC_CTYPE, loc)
  File "/home/serhiy/py/cpython3.7/Lib/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

----------------------------------------------------------------------
