### ISSUE TITLE
make install fails: no module _ctypes

### ISSUE THREAD

**Issue by 535c64bf-329b-4abc-b932-9e2fc55cda97** [python/cpython#75833]
BPO | [31652](https://bugs.python.org/issue31652)
--- | :---
Nosy | @ncoghlan, @bkline, @jwilk, @vadmium, @zware, @dstufft, @animalize, @stratakis, @dgspahn, @nigorol
Files | <li>[query.csv](https://bugs.python.org/file47793/query.csv "Uploaded as text/csv at 2018-09-08.19:50:20 by @dgspahn"): error query</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-02-28.12:57:28.242>
created_at = <Date 2017-09-30.23:04:21.847>
labels = ['invalid', 'build', '3.7']
title = 'make install fails: no module _ctypes'
updated_at = <Date 2020-03-05.16:50:16.410>
user = 'https://bugs.python.org/DandanLee'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-05.16:50:16.410>
actor = 'Alexander Stohr'
assignee = 'none'
closed = True
closed_date = <Date 2019-02-28.12:57:28.242>
closer = 'methane'
components = ['Build']
creation = <Date 2017-09-30.23:04:21.847>
creator = 'Dandan Lee'
dependencies = []
files = ['47793']
hgrepos = []
issue_num = 31652
keywords = []
message_count = 13.0
messages = ['303434', '303444', '321216', '321253', '321260', '321740', '324860', '325746', '325755', '337224', '340492', '348527', '363443']
nosy_count = 17.0
nosy_names = ['ncoghlan', 'bkline', 'jwilk', 'THRlWiTi', 'thomasahle', 'martin.panter', 'zach.ware', 'dstufft', 'malin', 'cstratak', 'Dandan Lee', 'bryanf', 'dgspahn', 'prabs003', 'Mr. Pligin', 'slink', 'Alexander Stohr']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31652'
versions = ['Python 3.7']
```

</p></details>

**Comment by 535c64bf-329b-4abc-b932-9e2fc55cda97** [comment]
The make install step fails with this error:

```pytb
Traceback (most recent call last):
  File "/home/dandan/Downloads/cpython-3.7.0a1/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dandan/Downloads/cpython-3.7.0a1/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dandan/Downloads/cpython-3.7.0a1/Lib/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/home/dandan/Downloads/cpython-3.7.0a1/Lib/ensurepip/__init__.py", line 189, in _main
    default_pip=args.default_pip,
  File "/home/dandan/Downloads/cpython-3.7.0a1/Lib/ensurepip/__init__.py", line 102, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/home/dandan/Downloads/cpython-3.7.0a1/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip
  File "/tmp/tmpcg658x_c/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 28, in <module>
  File "/tmp/tmpcg658x_c/pip-9.0.1-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/tmp/tmpcg658x_c/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 36, in <module>
  File "/tmp/tmpcg658x_c/pip-9.0.1-py2.py3-none-any.whl/pip/utils/glibc.py", line 4, in <module>
  File "/home/dandan/Downloads/cpython-3.7.0a1/Lib/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
Makefile:1080: recipe for target 'install' failed
make: *** [install] Error 1
```


Am I missing something?

**Comment by zware** [comment]
I expect that the root cause is missing libffi(-dev[el]) on your system, preventing \_ctypes from building, so your quick fix would be to install that and try again.

However, not having _ctypes shouldn't cause installation to fail.  Donald, is ctypes a hard requirement for pip to install itself?  If so, ensurepip as called by `make install` should either gracefully handle a lack of ctypes or be disabled when ctypes is not available.
