### ISSUE TITLE
xml.sax.parse won't accept path objects

### ISSUE THREAD

**Issue by 7e6c45ab-cd55-40b9-9429-49bb488ca339** [python/cpython#75839]
BPO | [31658](https://bugs.python.org/issue31658)
--- | :---
Nosy | @pitrou, @scoder, @mcepl
PRs | <li>python/cpython#8564</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-04-14.09:18:08.566>
created_at = <Date 2017-10-01.20:51:11.544>
labels = ['expert-XML', '3.8', 'type-bug', 'library']
title = "xml.sax.parse won't accept path objects"
updated_at = <Date 2019-04-14.09:18:33.555>
user = 'https://bugs.python.org/craigh'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-14.09:18:33.555>
actor = 'scoder'
assignee = 'none'
closed = True
closed_date = <Date 2019-04-14.09:18:08.566>
closer = 'scoder'
components = ['Library (Lib)', 'XML']
creation = <Date 2017-10-01.20:51:11.544>
creator = 'craigh'
dependencies = []
files = []
hgrepos = []
issue_num = 31658
keywords = ['patch']
message_count = 4.0
messages = ['303490', '340197', '340198', '340199']
nosy_count = 4.0
nosy_names = ['pitrou', 'scoder', 'mcepl', 'craigh']
pr_nums = ['8564']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31658'
versions = ['Python 3.8']
```

</p></details>

**Comment by 7e6c45ab-cd55-40b9-9429-49bb488ca339** [comment]
```pycon
>>> import xml.sax
>>> import pathlib
[...]
>>> xml.sax.parse(pathlib.Path('path/to/file'), handler)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 105, in parse
    source = saxutils.prepare_input_source(source)
  File "/usr/lib/python3.6/xml/sax/saxutils.py", line 355, in prepare_input_source
    if source.getCharacterStream() is None and source.getByteStream() is None:
AttributeError: 'PosixPath' object has no attribute 'getCharacterStream'
```
