### ISSUE TITLE
ssl.SSLSocket.send(b"") fails

### ISSUE THREAD

**Issue by 11ae746e-d782-4f33-a097-758c9f315fb2** [python/cpython#75892]
BPO | [31711](https://bugs.python.org/issue31711)
--- | :---
Nosy | @tiran, @alex, @njsmith, @slingamn, @dstufft, @joernheissler
PRs | <li>python/cpython#7559</li><li>python/cpython#17671</li>
Superseder | <li>bpo-42854: OpenSSL 1.1.1: use SSL_write_ex() and SSL_read_ex()</li>
Files | <li>[client.py](https://bugs.python.org/file47194/client.py "Uploaded as text/plain at 2017-10-06.09:42:59 by @joernheissler")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-04-19.04:01:15.793>
created_at = <Date 2017-10-06.09:43:00.138>
labels = ['expert-SSL', 'type-bug', '3.10', 'docs']
title = 'ssl.SSLSocket.send(b"") fails'
updated_at = <Date 2021-04-19.04:01:15.791>
user = 'https://github.com/joernheissler'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-19.04:01:15.791>
actor = 'christian.heimes'
assignee = 'docs@python'
closed = True
closed_date = <Date 2021-04-19.04:01:15.793>
closer = 'christian.heimes'
components = ['Documentation', 'SSL']
creation = <Date 2017-10-06.09:43:00.138>
creator = 'joernheissler'
dependencies = []
files = ['47194']
hgrepos = []
issue_num = 31711
keywords = ['patch']
message_count = 8.0
messages = ['303810', '312898', '312903', '312908', '312956', '346525', '358830', '391357']
nosy_count = 8.0
nosy_names = ['janssen', 'christian.heimes', 'alex', 'njs', 'docs@python', 'slingamn', 'dstufft', 'joernheissler']
pr_nums = ['7559', '17671']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = '42854'
type = 'behavior'
url = 'https://bugs.python.org/issue31711'
versions = ['Python 3.10']
```

</p></details>

**Comment by 11ae746e-d782-4f33-a097-758c9f315fb2** [comment]
```pytb
Traceback (most recent call last):
  File "client.py", line 10, in <module>
    conn.send(b'')
  File "/usr/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2074)
```


This error is not what I expected. I expected a noop instead.

My guess is, that python calls SSL_write (3.6 branch, \_ssl.c:2038) with that empty buffer.
The manpage states: "When calling SSL_write() with num=0 bytes to be sent the behaviour is undefined."

This undefined behaviour should either be documented in python, or defined to either raise an exception (ValueError?) or defined as a noop. I'd prefer the latter.
