### ISSUE TITLE
Better error message when failing to overload metaclass.mro

### ISSUE THREAD

**Issue by df79943f-4aee-4531-a00d-c6b12816eb70** [python/cpython#75970]
BPO | [31789](https://bugs.python.org/issue31789)
--- | :---
Nosy | @mr-nfamous

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-15.00:34:04.089>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Better error message when failing to overload metaclass.mro'
updated_at = <Date 2017-10-15.00:34:04.089>
user = 'https://github.com/mr-nfamous'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-15.00:34:04.089>
actor = 'bup'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2017-10-15.00:34:04.089>
creator = 'bup'
dependencies = []
files = []
hgrepos = []
issue_num = 31789
keywords = []
message_count = 1.0
messages = ['304406']
nosy_count = 1.0
nosy_names = ['bup']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31789'
versions = ['Python 3.7']
```

</p></details>

**Comment by df79943f-4aee-4531-a00d-c6b12816eb70** [comment]
```py
class meta(type):
    
    mros = (object,)
    
    def __new__(metacls, name, bases, namespace, fake_bases=()):
        print('entering __new__')
        metacls.fake_bases = fake_bases
        cls = type.__new__(metacls, name, bases, namespace)
        print('exiting __new__')
        return cls
    
    @staticmethod
    def mro(*args):
        print('entering mro')
        return meta.fake_bases + (object,)

class a(metaclass=meta, fake_bases=()): pass
```



That puts out the error message:

```pytb
entering meta.__new__
entering meta.mro
Traceback (most recent call last):
  File "<pyshell#5948>", line 1, in <module>
    exec(code, u)
  File "<string>", line 14, in <module>
  File "<string>", line 6, in __new__
TypeError: super(type, obj): obj must be an instance or subtype of type
```



That doesn't at all explain why it doesn't work because super was never explicitly called. If the argument fake_bases isn't empty, or if mro isn't made a staticmethod/classmethod, it returns an appropriate message

TypeError: mro() returned base with unsuitable layout ('tuple')
