### ISSUE TITLE
Issues with test.autotest

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75975]
BPO | [31794](https://bugs.python.org/issue31794)
--- | :---
Nosy | @terryjreedy, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-15.11:39:04.797>
labels = ['3.7', 'type-bug', 'tests']
title = 'Issues with test.autotest'
updated_at = <Date 2017-10-20.19:35:15.022>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-20.19:35:15.022>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2017-10-15.11:39:04.797>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31794
keywords = []
message_count = 2.0
messages = ['304433', '304673']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31794'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
There are issues with running tests by importing test.autotest.

1. test_builtin failed.

```pytb
0:00:00 load avg: 0.70 [  4/407] test_builtin
test test_builtin failed -- Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1735, in test_input_no_stdout_fileno
    lines = self.run_child(child, b"quux\r")
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1680, in run_child
    % (len(lines), child_output))
AssertionError: got 1 lines in pipe but expected 2, child output was:
quux
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1646, in run_child
    child(wpipe)
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1733, in child
    input("prompt")
EOFError: EOF when reading a line


0:00:00 load avg: 0.70 [  5/407/1] test_exceptions -- test_builtin failed
test test_builtin failed -- Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1735, in test_input_no_stdout_fileno
    lines = self.run_child(child, b"quux\r")
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1680, in run_child
    % (len(lines), child_output))
AssertionError: got 1 lines in pipe but expected 2, child output was:
quux
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1646, in run_child
    child(wpipe)
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1733, in child
    input("prompt")
EOFError: EOF when reading a line


0:00:01 load avg: 0.70 [  5/407/1] test_exceptions -- test_builtin failed
0:00:01 load avg: 0.70 [  4/407] test_builtin
Warning -- reap_children() reaped child process 4752
0:00:01 load avg: 0.70 [  4/407] test_builtin
0:00:01 load avg: 0.70 [  6/407/1] test_types
test test_builtin failed -- Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1735, in test_input_no_stdout_fileno
    lines = self.run_child(child, b"quux\r")
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1680, in run_child
    % (len(lines), child_output))
AssertionError: got 1 lines in pipe but expected 2, child output was:
quux
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1646, in run_child
    child(wpipe)
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1733, in child
    input("prompt")
EOFError: EOF when reading a line


0:00:01 load avg: 0.70 [  5/407/1] test_exceptions -- test_builtin failed
Warning -- reap_children() reaped child process 4755
0:00:01 load avg: 0.70 [  6/407/1] test_types
0:00:01 load avg: 0.70 [  7/407/1] test_unittest
Warning -- reap_children() reaped child process 4758
0:00:01 load avg: 1.12 [  6/407/1] test_types
0:00:01 load avg: 1.12 [  7/407/1] test_unittest
0:00:01 load avg: 1.12 [  7/407/1] test_unittest
test test_builtin failed -- Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1735, in test_input_no_stdout_fileno
    lines = self.run_child(child, b"quux\r")
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1680, in run_child
    % (len(lines), child_output))
AssertionError: got 1 lines in pipe but expected 2, child output was:
quux
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1646, in run_child
    child(wpipe)
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1733, in child
    input("prompt")
EOFError: EOF when reading a line


0:00:01 load avg: 1.12 [  5/407/1] test_exceptions -- test_builtin failed
test test_builtin failed -- Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1735, in test_input_no_stdout_fileno
    lines = self.run_child(child, b"quux\r")
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1680, in run_child
    % (len(lines), child_output))
AssertionError: got 1 lines in pipe but expected 2, child output was:
quux
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1646, in run_child
    child(wpipe)
  File "/home/serhiy/py/cpython/Lib/test/test_builtin.py", line 1733, in child
    input("prompt")
EOFError: EOF when reading a line
```



0:00:01 load avg: 1.12 [  5/407/1] test_exceptions -- test_builtin failed
Warning -- reap_children() reaped child process 4761
0:00:01 load avg: 1.12 [  6/407/1] test_types
Warning -- reap_children() reaped child process 4763

Note that warnings and errors are emitted even after reporting that test_builtin failed.


2. Tests are ran multiple times.

0:02:32 load avg: 4.82 [ 77/407/1] test_concurrent_futures
0:02:35 load avg: 4.82 [ 76/407/1] test_complex
0:02:35 load avg: 4.82 [ 77/407/1] test_concurrent_futures
test test_concurrent_futures failed -- multiple errors occurred; run in verbose mode for details
0:03:33 load avg: 1.77 [ 78/407/2] test_configparser -- test_concurrent_futures failed in 1 min 5 sec
test test_concurrent_futures failed -- multiple errors occurred; run in verbose mode for details
0:03:33 load avg: 1.77 [ 78/407/2] test_configparser -- test_concurrent_futures failed in 1 min 5 sec
0:03:34 load avg: 1.77 [ 79/407/2] test_contains
0:03:34 load avg: 1.77 [ 79/407/2] test_contains
0:03:34 load avg: 1.77 [ 80/407/2] test_contextlib
0:03:34 load avg: 1.77 [ 80/407/2] test_contextlib
0:03:34 load avg: 1.77 [ 81/407/2] test_contextlib_async
0:03:34 load avg: 1.77 [ 81/407/2] test_contextlib_async
0:03:34 load avg: 1.77 [ 82/407/2] test_copy
0:03:34 load avg: 1.77 [ 82/407/2] test_copy
0:03:34 load avg: 1.77 [ 83/407/2] test_copyreg
0:03:34 load avg: 1.77 [ 83/407/2] test_copyreg
0:03:34 load avg: 1.77 [ 84/407/2] test_coroutines
test test_concurrent_futures failed -- multiple errors occurred; run in verbose mode for details
0:03:35 load avg: 1.77 [ 84/407/2] test_coroutines
0:03:35 load avg: 1.77 [ 78/407/2] test_configparser -- test_concurrent_futures failed in 1 min 5 sec
0:03:35 load avg: 1.77 [ 85/407/2] test_cprofile
0:03:35 load avg: 1.77 [ 85/407/2] test_cprofile
0:03:35 load avg: 1.77 [ 79/407/2] test_contains
0:03:35 load avg: 1.77 [ 86/407/2] test_crashers
0:03:36 load avg: 1.77 [ 80/407/2] test_contextlib
0:03:36 load avg: 1.77 [ 86/407/2] test_crashers
0:03:36 load avg: 1.77 [ 87/407/2] test_crypt
0:03:36 load avg: 1.77 [ 87/407/2] test_crypt
0:03:36 load avg: 1.77 [ 88/407/2] test_csv
0:03:36 load avg: 1.77 [ 81/407/2] test_contextlib_async
0:03:36 load avg: 1.95 [ 88/407/2] test_csv
0:03:36 load avg: 1.95 [ 82/407/2] test_copy
0:03:36 load avg: 1.95 [ 83/407/2] test_copyreg
0:03:36 load avg: 1.95 [ 84/407/2] test_coroutines
0:03:37 load avg: 1.95 [ 85/407/2] test_cprofile
test test_concurrent_futures failed -- multiple errors occurred; run in verbose mode for details
0:03:37 load avg: 1.95 [ 78/407/2] test_configparser -- test_concurrent_futures failed in 1 min 6 sec


3. test_import changed the environment.

Warning -- files was modified by test_import
  Before: []
  After:  ['@test_4738_tmp.pyc'] 
0:06:18 load avg: 3.72 [178/407/3] test_importlib -- test_import failed (env changed)


4. test_logging failed.

```pytb
0:07:43 load avg: 3.39 [200/407/3] test_logging
test test_logging failed -- Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_logging.py", line 3667, in test_multiprocessing
    self.assertEqual(r.processName, 'MainProcess')
AssertionError: 'ForkServerProcess-192' != 'MainProcess'
- ForkServerProcess-192
+ MainProcess
```



5. test_mailbox changed the environment.

0:08:10 load avg: 3.13 [205/407/4] test_mailbox
Warning -- files was modified by test_mailbox
  Before: ['@test_4736_tmp.pyc']
  After:  [] 
0:08:11 load avg: 3.36 [206/407/5] test_mailcap -- test_mailbox failed (env changed)


6. test_multiprocessing_fork, test_multiprocessing_forkserver, test_multiprocessing_spawn failed.


7. test_os failed.

```pytb
test test_os failed -- Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_os.py", line 2923, in test_stty_match
    actual = os.get_terminal_size(sys.__stdin__.fileno())
ValueError: I/O operation on closed file
```


0:11:07 load avg: 2.82 [234/407/9] test_ossaudiodev -- test_os failed


8. The following traceback is output after reporting results.

```pytb
Exception in thread Thread-162:
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/serhiy/py/cpython/Lib/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serhiy/py/cpython/Lib/concurrent/futures/process.py", line 298, in _queue_management_worker
    shutdown_worker()
  File "/home/serhiy/py/cpython/Lib/concurrent/futures/process.py", line 256, in shutdown_worker
    call_queue.put_nowait(None)
  File "/home/serhiy/py/cpython/Lib/multiprocessing/queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "/home/serhiy/py/cpython/Lib/multiprocessing/queues.py", line 83, in put
    raise Full
queue.Full
```



9. After running all tests they are ran again from the start.

**Comment by terryjreedy** [comment]
As I reported on bpo-31761, the exact result of 'import test.autotest' depends on exactly how it is run and with what.  I suspect that OS might have an effect.
