### ISSUE TITLE
'import posixpath' fails if 'os.path' has not be imported already.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#75983]
BPO | [31802](https://bugs.python.org/issue31802)
--- | :---
Nosy | @markshannon, @serhiy-storchaka
PRs | <li>python/cpython#4017</li><li>python/cpython#5129</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2018-04-30.14:09:11.868>
created_at = <Date 2017-10-17.09:45:21.322>
labels = ['3.7', 'type-bug', 'library']
title = "'import posixpath' fails if 'os.path' has not be imported already."
updated_at = <Date 2018-04-30.14:09:11.867>
user = 'https://github.com/markshannon'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-30.14:09:11.867>
actor = 'Mark.Shannon'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2018-04-30.14:09:11.868>
closer = 'Mark.Shannon'
components = ['Library (Lib)']
creation = <Date 2017-10-17.09:45:21.322>
creator = 'Mark.Shannon'
dependencies = []
files = []
hgrepos = []
issue_num = 31802
keywords = ['patch']
message_count = 3.0
messages = ['304494', '309624', '309626']
nosy_count = 2.0
nosy_names = ['Mark.Shannon', 'serhiy.storchaka']
pr_nums = ['4017', '5129']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31802'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by markshannon** [comment]
```pycon
$ python3.7 -S
>>> import posixpath
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "--/Lib/posixpath.py", line 13, in <module>
    import os
  File "--/Lib/os.py", line 92, in <module>
    from os.path import (curdir, pardir, sep, pathsep, defpath, extsep, altsep,
ImportError: cannot import name 'curdir' from 'posixpath' (--/Lib/posixpath.py)
```


Whether this counts as a bug or not is debatable. It could be argued that you shouldn't be importing 'posixpath' directly, in which case it ought to be called '\_posixpath', but I guess it is too late to be changing the name.
