### ISSUE TITLE
pathlib: "Incorrect function" during resolve()

### ISSUE THREAD

**Issue by dd602496-28cc-4360-9fb4-7b7b694c6e12** [python/cpython#76023]
BPO | [31842](https://bugs.python.org/issue31842)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @earonesty, @earonesty, @Zombie110year, @christopher.pickering

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-22.21:31:13.027>
labels = ['type-bug', '3.9', 'OS-windows']
title = 'pathlib: "Incorrect function" during resolve()'
updated_at = <Date 2021-11-13.12:33:39.598>
user = 'https://github.com/earonesty'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-13.12:33:39.598>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2017-10-22.21:31:13.027>
creator = 'earonesty2'
dependencies = []
files = []
hgrepos = []
issue_num = 31842
keywords = []
message_count = 8.0
messages = ['304767', '356199', '357702', '357725', '381676', '390089', '406212', '406274']
nosy_count = 11.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'earonesty', 'earonesty2', 'zombie110year', 'maciozo', 'christopherpickering', 'riffitos']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31842'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-128316
* gh-128328
* gh-134203
* gh-134204

**Comment by dd602496-28cc-4360-9fb4-7b7b694c6e12** [comment]
When strict is "false", pathlib should not fail if the network share is inaccessible.  It should, as documented, catch the exception and continue with as much of the path as it has.



```pycon
>>> pathlib.Path("v:").resolve()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\erik\AppData\Local\Programs\Python\Python36\lib\pathlib.py", line 1119, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\erik\AppData\Local\Programs\Python\Python36\lib\pathlib.py", line 193, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 1] Incorrect function: 'v:'
```

**Comment by barneygale** [comment]
Could you re-test this in 3.10 or above? We changed `Path.resolve()` to use `os.path.realpath()`, which may not suffer from this bug.

**Comment by traits** [comment]
We are using symbolic names (example: \<XYZ\>/my.fil), so these files never exist in literal form. I would still expect from the documentation (3.10):  

> If the path doesn’t exist and strict is True, [FileNotFoundError](https://docs.python.org/3.10/library/exceptions.html#FileNotFoundError) is raised. If strict is False, the path is resolved as far as possible and any remainder is appended without checking whether it exists. If an infinite loop is encountered along the resolution path, [RuntimeError](https://docs.python.org/3.10/library/exceptions.html#RuntimeError) is raised.

that only two types of exceptions are possible: FileNotFoundError and RuntimeError, for strict==False only the later one. But we still get an OSError in this case:

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '\<XYZ\>\\my.fil'

OSError is a base class of FileNotFoundError, but not raised as such, but as a real OSError. It shouldn't do it in either case, because as mentioned for strict==False only RuntimeError should be allowed. And only for specific circumstances, otherwise the documentation suggests a noop/partial string resolve regarding the input.

**Comment by zooba** [comment]
I don't think any Python documentation _exhaustively_ lists exceptions. There are some that are always possible dependent on the arguments passed (`ValueError`, `TypeError`, etc.) and others dependent on state outside of the caller's control (`OSError`, `KeyboardInterrupt`, etc.). So to a certain extent, your expectation is wrong, and that's the fault of the documentation for not making that more obvious.

We'd welcome a pull request to add that particular error code into the "assume the path is correct and don't check" codepath pointed out in an earlier response.

**Comment by barneygale** [comment]
I'm removing the `topic-pathlib` tag because in Python 3.13+, `pathlib.Path.resolve()` calls straight through to `os.path.realpath()`. If this bug still exists, it's in `realpath()` and not `pathlib`.

https://github.com/python/cpython/blob/1619f4350ee431d2fa2f7c0b89702e897d9d14a2/Lib/pathlib.py#L1437-L1443

**Comment by serhiy-storchaka** [comment]
Why not ignore _all_ errors in non-strict mode, like on Posix?
