### ISSUE TITLE
test_nntplib failed with "nntplib.NNTPDataError: line too long"

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76031]
BPO | [31850](https://bugs.python.org/issue31850)
--- | :---
Nosy | @vstinner, @mcepl

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-05-21.12:14:53.848>
created_at = <Date 2017-10-23.17:45:15.843>
labels = ['3.7', 'tests']
title = 'test_nntplib failed with "nntplib.NNTPDataError: line too long"'
updated_at = <Date 2019-05-21.12:14:53.848>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-21.12:14:53.848>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2019-05-21.12:14:53.848>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-10-23.17:45:15.843>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31850
keywords = ['buildbot']
message_count = 4.0
messages = ['304829', '304830', '343021', '343030']
nosy_count = 2.0
nosy_names = ['vstinner', 'mcepl']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31850'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
test_nntplib failed on many buildbots yesterday with the "line too long" error. It may be related to bpo-28971.

Example:

http://buildbot.python.org/all/#/builders/12/builds/52

(...)
test_with_statement (test.test_nntplib.NetworkedNNTP_SSLTests) ... ok
test_xhdr (test.test_nntplib.NetworkedNNTP_SSLTests) ... ok
test_xover (test.test_nntplib.NetworkedNNTP_SSLTests) ... ERROR
test_zlogin (test.test_nntplib.NetworkedNNTP_SSLTests) ... ok
test_zzquit (test.test_nntplib.NetworkedNNTP_SSLTests) ... ok
test_module_all_attribute (test.test_nntplib.PublicAPITests) ... ok
test test_nntplib failed
test_we_are_in_reader_mode_after_connect (test.test_nntplib.SendReaderNNTPv2Tests) ... ok

\======================================================================
ERROR: test_xover (test.test_nntplib.NetworkedNNTP_SSLTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\buildarea\3.x.ware-win81-release\build\lib\test\test_nntplib.py", line 241, in wrapped
    meth(self)
  File "D:\buildarea\3.x.ware-win81-release\build\lib\test\test_nntplib.py", line 125, in test_xover
    resp, lines = self.server.xover(last - 5, last)
  File "D:\buildarea\3.x.ware-win81-release\build\lib\nntplib.py", line 804, in xover
    file)
  File "D:\buildarea\3.x.ware-win81-release\build\lib\nntplib.py", line 525, in _longcmdstring
    resp, list = self._getlongresp(file)
  File "D:\buildarea\3.x.ware-win81-release\build\lib\nntplib.py", line 494, in _getlongresp
    line = self._getline()
  File "D:\buildarea\3.x.ware-win81-release\build\lib\nntplib.py", line 434, in _getline
    raise NNTPDataError('line too long')
nntplib.NNTPDataError: line too long
```

**Comment by vstinner** [comment]
It also failed on Travis CI:

https://mail.python.org/pipermail/python-committers/2017-October/004910.html

Other buildbot failures:

http://buildbot.python.org/all/#builders/80/builds/17
http://buildbot.python.org/all/#/builders/3/builds/48
http://buildbot.python.org/all/#/builders/47/builds/51
http://buildbot.python.org/all/#/builders/99/builds/50
http://buildbot.python.org/all/#/builders/103/builds/50
http://buildbot.python.org/all/#/builders/88/builds/51
http://buildbot.python.org/all/#builders/85/builds/51
http://buildbot.python.org/all/#/builders/53/builds/52
http://buildbot.python.org/all/#/builders/12/builds/49
http://buildbot.python.org/all/#/builders/106/builds/51
http://buildbot.python.org/all/#/builders/13/builds/51
http://buildbot.python.org/all/#/builders/27/builds/50
http://buildbot.python.org/all/#/builders/16/builds/51
http://buildbot.python.org/all/#/builders/87/builds/50
http://buildbot.python.org/all/#/builders/90/builds/28
http://buildbot.python.org/all/#/builders/30/builds/47
http://buildbot.python.org/all/#/builders/32/builds/47
