### ISSUE TITLE
add timeout parameter for get_server_certificate in ssl.py

### ISSUE THREAD

**Issue by 66f9b400-da17-4190-b5b1-f8ea088c7bf6** [python/cpython#76051]
BPO | [31870](https://bugs.python.org/issue31870)
--- | :---
Nosy | @tiran, @alex, @dstufft, @nixawk, @ZackerySpytz, @miss-islington
PRs | <li>python/cpython#4126</li><li>python/cpython#22270</li><li>python/cpython#25570</li>
Files | <li>[ssl.py](https://bugs.python.org/file47238/ssl.py "Uploaded as text/plain at 2017-10-26.04:11:19 by @nixawk"): Added timeout support for func get_server_certificate in ssl module.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2021-04-24.04:57:49.322>
created_at = <Date 2017-10-26.04:11:25.449>
labels = ['expert-SSL', 'type-feature', '3.10']
title = 'add timeout parameter for get_server_certificate in ssl.py'
updated_at = <Date 2021-04-24.05:54:11.227>
user = 'https://github.com/Nixawk'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-24.05:54:11.227>
actor = 'christian.heimes'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2021-04-24.04:57:49.322>
closer = 'christian.heimes'
components = ['SSL']
creation = <Date 2017-10-26.04:11:25.449>
creator = 'Nixawk'
dependencies = []
files = ['47238']
hgrepos = []
issue_num = 31870
keywords = ['patch']
message_count = 4.0
messages = ['305021', '312879', '391758', '391760']
nosy_count = 7.0
nosy_names = ['janssen', 'christian.heimes', 'alex', 'dstufft', 'Nixawk', 'ZackerySpytz', 'miss-islington']
pr_nums = ['4126', '22270', '25570']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31870'
versions = ['Python 3.10']
```

</p></details>

**Comment by 66f9b400-da17-4190-b5b1-f8ea088c7bf6** [comment]
The original get_server_certificate in ssl.py does not support socket timeout,

```py
def get_server_certificate(addr, ssl_version=PROTOCOL_TLS, ca_certs=None):
    """Retrieve the certificate from the server at the specified address,
    and return it as a PEM-encoded string.
    If 'ca_certs' is specified, validate the server cert against it.
    If 'ssl_version' is specified, use it in the connection attempt."""
```


    host, port = addr
    if ca_certs is not None:
        cert_reqs = CERT_REQUIRED
    else:
        cert_reqs = CERT_NONE
    context = _create_stdlib_context(ssl_version,
                                     cert_reqs=cert_reqs,
                                     cafile=ca_certs)
    with  create_connection(addr) as sock:
        with context.wrap_socket(sock) as sslsock:
            dercert = sslsock.getpeercert(True)
    return DER_cert_to_PEM_cert(dercert)

If a timeout parameter, a sample demo can be here:

```pycon
>>> import ssl
>>> ssl.get_server_certificate(("www.qq.com", 443), timeout=6)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/ssl.py", line 1017, in get_server_certificate
    with closing(create_connection(addr, timeout)) as sock:
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 101] Network is unreachable
```
