### ISSUE TITLE
Support for file descriptor params in os.path

### ISSUE THREAD

**Issue by d81880cf-01f3-41ab-986e-1b76594962db** [python/cpython#76052]
BPO | [31871](https://bugs.python.org/issue31871)
--- | :---
Nosy | @merwok, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-26.05:33:13.367>
labels = ['type-feature', '3.7', 'docs']
title = 'Support for file descriptor params in os.path'
updated_at = <Date 2017-10-28.09:49:54.401>
user = 'https://bugs.python.org/MateuszKurek'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-28.09:49:54.401>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2017-10-26.05:33:13.367>
creator = 'Mateusz Kurek'
dependencies = []
files = []
hgrepos = []
issue_num = 31871
keywords = []
message_count = 3.0
messages = ['305023', '305129', '305152']
nosy_count = 4.0
nosy_names = ['eric.araujo', 'docs@python', 'serhiy.storchaka', 'Mateusz Kurek']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31871'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by d81880cf-01f3-41ab-986e-1b76594962db** [comment]
Since Python 3.3, some os module functions, like os.stat (https://docs.python.org/3/library/os.html#os.stat), support passing file descriptor instead of a path. os.path functions, on the other hand (like os.path.exists - https://docs.python.org/3/library/os.path.html#os.path.exists - or os.path.samefile - https://docs.python.org/3/library/os.path.html#os.path.samefile) mention using os.stat underneath, but according to documentation, does not support passing file descriptor instead of a path (at least it's not mentioned in the docs that this feature is supported). Is this intentional (os.path functions should not take file descriptor params) or this feature is officialy supported, but it's ommited in the docs?

**Comment by merwok** [comment]
> support passing file descriptor instead of a path. os.path functions

Are you sure about that?  The docs for os.stat show the dir_fd parameter, used to avoid directory renaming issues or attacks, but it doesn’t say that the \*path* argument can be an int file descriptor instead of a str file path.

**Comment by serhiy-storchaka** [comment]
Éric, see https://docs.python.org/3/library/os.html#files-and-directories.

Yes, now some os.path functions can accept a file descriptor as a path. I don't think this is intentional. And this may not work on all platforms.

```pycon
>>> os.path.isdir(1)
False
>>> os.path.islink(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/py/cpython/Lib/posixpath.py", line 169, in islink
    st = os.lstat(path)
TypeError: lstat: path should be string, bytes or os.PathLike, not int
```
