### ISSUE TITLE
Creating a UUID with a list throws bad exception

### ISSUE THREAD

**Issue by 904e84a6-5612-4c85-9c2c-09a905686ae0** [python/cpython#76069]
BPO | [31888](https://bugs.python.org/issue31888)
--- | :---
Nosy | @serhiy-storchaka, @TilmanK

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-28.07:53:22.437>
created_at = <Date 2017-10-28.05:40:10.660>
labels = ['invalid', 'type-bug', 'library']
title = 'Creating a UUID with a list throws bad exception'
updated_at = <Date 2017-10-28.07:53:22.435>
user = 'https://github.com/TilmanK'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-28.07:53:22.435>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-28.07:53:22.437>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-10-28.05:40:10.660>
creator = 'TilmanKrummeck'
dependencies = []
files = []
hgrepos = []
issue_num = 31888
keywords = []
message_count = 2.0
messages = ['305148', '305149']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'TilmanKrummeck']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31888'
versions = ['Python 3.5']
```

</p></details>

**Comment by 904e84a6-5612-4c85-9c2c-09a905686ae0** [comment]
I found a problem by accident on Python 3.5.3 with the uuid library.

Running this:

```py
from uuid import UUID
UUID(["string"])
```


```pytb
This throws an AttributeError:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Tilman Krummeck\AppData\Local\Programs\Python\Python35-32\lib\uuid.py", line 137, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'list' object has no attribute 'replace'
```


This is for sure not intended to work, but should throw a type error in my opinion even before trying to create that UUID object.

**Comment by serhiy-storchaka** [comment]
This is a consequence of duck-typing and is common in Python. If you pass a value of wrong type, it is expected that you can get an AttributeError.

Explicit type checks clutter and slow down the code, and make it less flexible.

You can test an explicit type before calling uuid.UUID() in your code if you need.
