### ISSUE TITLE
Saving bytearray to binary plist file doesn't work

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#76169]
BPO | [31988](https://bugs.python.org/issue31988)
--- | :---
Nosy | @ronaldoussoren, @serhiy-storchaka
Superseder | <li>bpo-32072: Issues with binary plists</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-12-25.09:32:28.367>
created_at = <Date 2017-11-08.23:20:21.244>
labels = ['3.7', 'type-bug', 'library']
title = "Saving bytearray to binary plist file doesn't work"
updated_at = <Date 2017-12-25.09:32:28.366>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-25.09:32:28.366>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-12-25.09:32:28.367>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-11-08.23:20:21.244>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31988
keywords = []
message_count = 2.0
messages = ['305921', '309034']
nosy_count = 2.0
nosy_names = ['ronaldoussoren', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '32072'
type = 'behavior'
url = 'https://bugs.python.org/issue31988'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
```pycon
>>> import plistlib
>>> plistlib.dumps(bytearray(), fmt=plistlib.FMT_BINARY)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/py/cpython/Lib/plistlib.py", line 962, in dumps
    dump(value, fp, fmt=fmt, skipkeys=skipkeys, sort_keys=sort_keys)
  File "/home/serhiy/py/cpython/Lib/plistlib.py", line 955, in dump
    writer.write(value)
  File "/home/serhiy/py/cpython/Lib/plistlib.py", line 703, in write
    self._flatten(value)
  File "/home/serhiy/py/cpython/Lib/plistlib.py", line 741, in _flatten
    if (type(value), value) in self._objtable:
TypeError: unhashable type: 'bytearray'
```
