### ISSUE TITLE
[2.7] test_urllib2net.test_sites_no_connection_close() randomly fails on Python 2.7

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76167]
BPO | [31986](https://bugs.python.org/issue31986)
--- | :---
Nosy | @vstinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-21.23:02:41.223>
created_at = <Date 2017-11-08.22:20:43.162>
labels = ['tests']
title = '[2.7] test_urllib2net.test_sites_no_connection_close() randomly fails on Python 2.7'
updated_at = <Date 2018-09-21.23:02:41.222>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-21.23:02:41.222>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-21.23:02:41.223>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-11-08.22:20:43.162>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31986
keywords = []
message_count = 1.0
messages = ['305913']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31986'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/#/builders/78/builds/20

ERROR: test_sites_no_connection_close (test.test_urllib2net.OtherNetworkTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/Lib/test/test_urllib2net.py", line 193, in test_sites_no_connection_close
    req = urllib2.urlopen(URL)
  File "/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/Lib/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/Lib/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/Lib/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/Lib/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/Lib/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/Lib/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
```
