### ISSUE TITLE
test_venv failed when the zlib module is not available

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#76180]
BPO | [31999](https://bugs.python.org/issue31999)
--- | :---
Nosy | @vsajip, @serhiy-storchaka
PRs | <li>python/cpython#4359</li><li>python/cpython#4360</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-11-10.11:01:06.919>
created_at = <Date 2017-11-10.09:28:58.183>
labels = ['3.7', 'type-bug', 'tests']
title = 'test_venv failed when the zlib module is not available'
updated_at = <Date 2017-11-10.11:01:06.918>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-10.11:01:06.918>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-11-10.11:01:06.919>
closer = 'serhiy.storchaka'
components = ['Tests']
creation = <Date 2017-11-10.09:28:58.183>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31999
keywords = ['patch']
message_count = 3.0
messages = ['306010', '306014', '306020']
nosy_count = 2.0
nosy_names = ['vinay.sajip', 'serhiy.storchaka']
pr_nums = ['4359', '4360']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31999'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
http://buildbot.python.org/all/#/builders/14/builds/160/steps/4/logs/stdio
\======================================================================
FAIL: test_with_pip (test.test_venv.EnsurePipTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/test/test_venv.py", line 363, in do_test_with_pip
    with_pip=True)
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/test/test_venv.py", line 56, in run_with_capture
    func(*args, **kwargs)
subprocess.CalledProcessError: Command '['/private/var/folders/sy/9hwmqyx14s11577cvgzwf2v40000gt/T/tmpljv28gk_/bin/python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/test/test_venv.py", line 421, in test_with_pip
    self.do_test_with_pip(False)
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/test/test_venv.py", line 369, in do_test_with_pip
    self.fail(msg.format(exc, details))
AssertionError: Command '['/private/var/folders/sy/9hwmqyx14s11577cvgzwf2v40000gt/T/tmpljv28gk_/bin/python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
**Subprocess Output**
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip
zipimport.ZipImportError: can't decompress data; zlib not available
```
----------------------------------------------------------------------

**Comment by serhiy-storchaka** [comment]
New changeset 5e0df74b3bc6391e9a7eba0fd84531ed99a78ae9 by Serhiy Storchaka in branch 'master':
bpo-31999: Fix test_venv in case the zlib module is not available. (bpo-4359)
https://github.com/python/cpython/commit/5e0df74b3bc6391e9a7eba0fd84531ed99a78ae9

**Comment by serhiy-storchaka** [comment]
New changeset 7997fa2e2159cfce0cfbe985a953174ac86694a4 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
bpo-31999: Fix test_venv in case the zlib module is not available. (GH-4359) (bpo-4360)
https://github.com/python/cpython/commit/7997fa2e2159cfce0cfbe985a953174ac86694a4
