### ISSUE TITLE
test_undecodable_filename in test_httpservers failed on Mac OS X

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#76181]
BPO | [32000](https://bugs.python.org/issue32000)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @serhiy-storchaka
Superseder | <li>bpo-31380: test_undecodable_filename() in Lib/test/test_httpservers.py broken on APFS</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-10.09:45:27.173>
created_at = <Date 2017-11-10.09:42:08.240>
labels = ['OS-mac', 'type-bug', 'tests', '3.7']
title = 'test_undecodable_filename in test_httpservers failed on Mac OS X'
updated_at = <Date 2017-11-10.09:45:27.172>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-10.09:45:27.172>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-10.09:45:27.173>
closer = 'serhiy.storchaka'
components = ['macOS', 'Tests']
creation = <Date 2017-11-10.09:42:08.240>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 32000
keywords = []
message_count = 2.0
messages = ['306011', '306012']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '31380'
type = 'behavior'
url = 'https://bugs.python.org/issue32000'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
http://buildbot.python.org/all/#/builders/14/builds/160/steps/4/logs/stdio
\======================================================================
ERROR: test_undecodable_filename (test.test_httpservers.SimpleHTTPServerTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/test/support/__init__.py", line 598, in wrapper
    return func(*args, **kw)
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/test/test_httpservers.py", line 395, in test_undecodable_filename
    with open(os.path.join(self.tempdir, filename), 'wb') as f:
OSError: [Errno 92] Illegal byte sequence: '/var/folders/sy/9hwmqyx14s11577cvgzwf2v40000gt/T/tmp0hrc3ckd/@test_54539_tmp\udce7w\udcf0.txt'
```
----------------------------------------------------------------------

**Comment by serhiy-storchaka** [comment]
Duplicate of bpo-31380.
