### ISSUE TITLE
multiprocessing.Array misleading error message in slice assignment

### ISSUE THREAD

**Issue by stevendaprano** [python/cpython#76186]
BPO | [32005](https://bugs.python.org/issue32005)
--- | :---
Nosy | @stevendaprano

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-11-10.23:53:08.892>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'multiprocessing.Array misleading error message in slice assignment'
updated_at = <Date 2021-06-22.11:57:27.362>
user = 'https://github.com/stevendaprano'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-22.11:57:27.362>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-11-10.23:53:08.892>
creator = 'steven.daprano'
dependencies = []
files = []
hgrepos = []
issue_num = 32005
keywords = []
message_count = 1.0
messages = ['306066']
nosy_count = 1.0
nosy_names = ['steven.daprano']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32005'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-110719

**Comment by stevendaprano** [comment]
multiprocessing.Array slice assignment claims to require a single character even if it requires more than one:

```pytb
py> arr = multiprocessing.Array('c', 3)
py> arr[:] = b'xyz'  # works
py> arr[:] = 'xyz'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/multiprocessing/sharedctypes.py", line 226, in __setitem__
    self._obj[i] = value
TypeError: one character bytes, bytearray or integer expected
```
