### ISSUE TITLE
Do not use the canonical path in pydoc test_mixed_case_module_names_are_lower_cased

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#76212]
BPO | [32031](https://bugs.python.org/issue32031)
--- | :---
Nosy | @xdegaye
PRs | <li>python/cpython#4441</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-18.17:21:38.016>
created_at = <Date 2017-11-15.09:37:41.679>
labels = ['3.7', 'type-bug', 'tests']
title = 'Do not use the canonical path in pydoc test_mixed_case_module_names_are_lower_cased'
updated_at = <Date 2017-11-18.17:21:38.015>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-18.17:21:38.015>
actor = 'xdegaye'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-18.17:21:38.016>
closer = 'xdegaye'
components = ['Tests']
creation = <Date 2017-11-15.09:37:41.679>
creator = 'xdegaye'
dependencies = []
files = []
hgrepos = []
issue_num = 32031
keywords = ['patch']
message_count = 4.0
messages = ['306259', '306423', '306424', '306487']
nosy_count = 1.0
nosy_names = ['xdegaye']
pr_nums = ['4441']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32031'
versions = ['Python 3.7']
```

</p></details>

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
test_mixed_case_module_names_are_lower_cased fails when there is a symlink in the directory path of the installed standard library.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
The error:

```pytb
generic_x86_64:/data/local/tmp/python $ python -m test test_pydoc
Run tests sequentially
0:00:00 [1/1] test_pydoc
test test_pydoc failed -- Traceback (most recent call last):
  File "/sdcard/org.python/lib/python3.7/test/test_pydoc.py", line 459, in test_mixed_case_module_names_are_lower_cased
    self.assertIn('xml.etree.elementtree', doc_link)
  File "/sdcard/org.python/lib/python3.7/unittest/case.py", line 1103, in assertIn
    if member not in container:
TypeError: argument of type 'NoneType' is not iterable
```


test_pydoc failed

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
The path returned by inspect.getabsfile(xml.etree.ElementTree) is not the canonical path, hence the test failure.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
New changeset ebfaa71c2e8c018f72c179395dafaf06dcaf29e2 by xdegaye in branch 'master':
bpo-32031: Fix pydoc `test_mixed_case_module_names_are_lower_cased` (GH-4441)
https://github.com/python/cpython/commit/ebfaa71c2e8c018f72c179395dafaf06dcaf29e2
