### ISSUE TITLE
test_multiprocessing_forkserver failed with OSError: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76244]
BPO | [32063](https://bugs.python.org/issue32063)
--- | :---
Nosy | @vstinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-06-27.21:16:24.760>
created_at = <Date 2017-11-17.14:48:44.801>
labels = ['tests']
title = 'test_multiprocessing_forkserver failed with OSError: [Errno 48] Address already in use'
updated_at = <Date 2018-06-27.21:16:24.759>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-27.21:16:24.759>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-06-27.21:16:24.760>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-11-17.14:48:44.801>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32063
keywords = []
message_count = 2.0
messages = ['306443', '320624']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32063'
versions = ['Python 3.6']
```

</p></details>

**Comment by vstinner** [comment]
x86-64 Sierra 3.6:
http://buildbot.python.org/all/#/builders/20/builds/62

```pytb
0:06:16 load avg: 3.45 [ 87/405/1] test_multiprocessing_forkserver failed -- running: test_tokenize (77 sec)
Process QueueManager-260:
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/multiprocessing/managers.py", line 539, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/multiprocessing/managers.py", line 139, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/multiprocessing/connection.py", line 576, in __init__
    self._socket.bind(address)
OSError: [Errno 48] Address already in use
(...)
```


test_rlock (test.test_multiprocessing_forkserver.WithThreadsTestLock) ... ok
test_rapid_restart (test.test_multiprocessing_forkserver.WithThreadsTestManagerRestart) ... ERROR
Warning -- Dangling processes: {\<ForkServerProcess(QueueManager-260, stopped[1])\>}
test_boundaries (test.test_multiprocessing_forkserver.WithThreadsTestPoll) ... ok
test_dont_merge (test.test_multiprocessing_forkserver.WithThreadsTestPoll) ... ok
(...)
test_timeout (test.test_multiprocessing_forkserver.WithThreadsTestSemaphore) ... skipped 'test not appropriate for threads'
test_import (test.test_multiprocessing_forkserver.\_TestImportStar) ... ok
Warning -- Dangling processes: {\<ForkServerProcess(QueueManager-260, stopped[1])\>}

\======================================================================
ERROR: test_rapid_restart (test.test_multiprocessing_forkserver.WithThreadsTestManagerRestart)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/test/_test_multiprocessing.py", line 2508, in test_rapid_restart
    manager.start()
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/multiprocessing/managers.py", line 517, in start
    self._address = reader.recv()
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```
