### ISSUE TITLE
test_httpservers.test_undecodable_filename() fails with [Errno 92] Illegal byte sequence on macOS Sierra

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76242]
BPO | [32061](https://bugs.python.org/issue32061)
--- | :---
Nosy | @ronaldoussoren, @vstinner, @ned-deily
Superseder | <li>bpo-31380: test_undecodable_filename() in Lib/test/test_httpservers.py broken on APFS</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-17.14:51:44.194>
created_at = <Date 2017-11-17.14:44:50.240>
labels = ['OS-mac', '3.7', 'tests']
title = 'test_httpservers.test_undecodable_filename() fails with [Errno 92] Illegal byte sequence on macOS Sierra'
updated_at = <Date 2017-11-17.14:51:44.192>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-17.14:51:44.192>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-17.14:51:44.194>
closer = 'vstinner'
components = ['macOS', 'Tests']
creation = <Date 2017-11-17.14:44:50.240>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32061
keywords = []
message_count = 2.0
messages = ['306441', '306445']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'vstinner', 'ned.deily']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '31380'
type = None
url = 'https://bugs.python.org/issue32061'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
x86-64 Sierra 3.6 failure:
http://buildbot.python.org/all/#/builders/20/builds/81

\======================================================================
ERROR: test_undecodable_filename (test.test_httpservers.SimpleHTTPServerTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/test/support/__init__.py", line 601, in wrapper
    return func(*args, **kw)
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/test/test_httpservers.py", line 381, in test_undecodable_filename
    with open(os.path.join(self.tempdir, filename), 'wb') as f:
OSError: [Errno 92] Illegal byte sequence: '/var/folders/sy/9hwmqyx14s11577cvgzwf2v40000gt/T/tmp19j_8j75/@test_98516_tmp\udce7w\udcf0.txt'
```

**Comment by vstinner** [comment]
Oh, it's a duplicate of bpo-31380.
