### ISSUE TITLE
range_iterator doesn't have length, leads to surprised result

### ISSUE THREAD

**Issue by cd65c590-98e9-41d1-9e7a-7754bceafdd7** [python/cpython#76246]
BPO | [32065](https://bugs.python.org/issue32065)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-18.01:20:38.612>
created_at = <Date 2017-11-17.23:11:12.185>
labels = ['interpreter-core', '3.7', 'invalid']
title = "range_iterator doesn't have length, leads to surprised result"
updated_at = <Date 2017-11-18.01:20:38.572>
user = 'https://bugs.python.org/yegle'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-18.01:20:38.572>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-18.01:20:38.612>
closer = 'r.david.murray'
components = ['Interpreter Core']
creation = <Date 2017-11-17.23:11:12.185>
creator = 'yegle'
dependencies = []
files = []
hgrepos = []
issue_num = 32065
keywords = []
message_count = 3.0
messages = ['306458', '306462', '306465']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'yegle']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32065'
versions = ['Python 2.7', 'Python 3.7']
```

</p></details>

**Comment by cd65c590-98e9-41d1-9e7a-7754bceafdd7** [comment]
This also affects xrange in Python2, so I chose the affected version as python27.

range object (and xrange in Python2) has \_\_len__(), but the range_iterator object created from \_\_reversed__() doesn't have \_\_len__.

```pycon
Python2:
>>> x = xrange(10)
>>> len(x)
10
>>> reversed(x)
<rangeiterator object at 0x7f86065684e0>
>>> y = reversed(x)
>>> len(y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'rangeiterator' has no len()

Python3.6
>>> x = range(10)
>>> len(x)
10
>>> len(reversed(x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'range_iterator' has no len()
```

**Comment by cd65c590-98e9-41d1-9e7a-7754bceafdd7** [comment]
Hmm I think this also applies to list_listiterator. In general I'd expect these to be true:

```py
l = [1,2,3]
r = range(3)
```


assert len(l) == len(reversed(l))
assert len(r) == len(reversed(r))

**Comment by bitdancer** [comment]
By design, iterators do not have a length (see [msg248496](https://bugs.python.org/msg248496)).
