### ISSUE TITLE
test_venv fails if zlib is not available

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76243]
BPO | [32062](https://bugs.python.org/issue32062)
--- | :---
Nosy | @vsajip, @vstinner
Superseder | <li>bpo-31999: test_venv failed when the zlib module is not available</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-17.14:50:55.785>
created_at = <Date 2017-11-17.14:46:32.848>
labels = ['tests']
title = 'test_venv fails if zlib is not available'
updated_at = <Date 2017-11-17.14:50:55.784>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-17.14:50:55.784>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-17.14:50:55.785>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-11-17.14:46:32.848>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32062
keywords = []
message_count = 2.0
messages = ['306442', '306444']
nosy_count = 2.0
nosy_names = ['vinay.sajip', 'vstinner']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '31999'
type = None
url = 'https://bugs.python.org/issue32062'
versions = ['Python 3.6']
```

</p></details>

**Comment by vstinner** [comment]
test_venv should skip test_with_pip() test when the zlib module is missing.

x86-64 Sierra 3.6 failure:
http://buildbot.python.org/all/#/builders/20/builds/62

test_with_pip (test.test_venv.EnsurePipTest) ... FAIL

\======================================================================
FAIL: test_with_pip (test.test_venv.EnsurePipTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/test/test_venv.py", line 368, in do_test_with_pip
    with_pip=True)
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/test/test_venv.py", line 61, in run_with_capture
    func(*args, **kwargs)
subprocess.CalledProcessError: Command '['/private/var/folders/sy/9hwmqyx14s11577cvgzwf2v40000gt/T/tmpzg_lamk1/bin/python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/test/test_venv.py", line 428, in test_with_pip
    self.do_test_with_pip(False)
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/test/test_venv.py", line 374, in do_test_with_pip
    self.fail(msg.format(exc, details))
AssertionError: Command '['/private/var/folders/sy/9hwmqyx14s11577cvgzwf2v40000gt/T/tmpzg_lamk1/bin/python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

**Subprocess Output**
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/Users/buildbot/buildarea/3.6.billenstein-sierra/build/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip
zipimport.ZipImportError: can't decompress data; zlib not available
```

**Comment by vstinner** [comment]
Oh, Serhiy already fixed it: bpo-31999.
