### ISSUE TITLE
mock.patch with autospec does not consume self / cls argument

### ISSUE THREAD

**Issue by 651e1c70-eaae-4801-8025-e18992128b87** [python/cpython#76273]
BPO | [32092](https://bugs.python.org/issue32092)
--- | :---
Nosy | @cjw296, @voidspace, @phmc, @lisroach, @mariocj89, @bclau, @tirkarthi
PRs | <li>python/cpython#4476</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-11-20.15:50:21.285>
labels = ['3.7', '3.8', 'type-bug', 'library', '3.9']
title = 'mock.patch with autospec does not consume self / cls argument'
updated_at = <Date 2019-10-28.20:46:16.247>
user = 'https://github.com/bclau'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-28.20:46:16.247>
actor = 'pconnell'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-11-20.15:50:21.285>
creator = 'cbelu'
dependencies = []
files = []
hgrepos = []
issue_num = 32092
keywords = ['patch']
message_count = 2.0
messages = ['306559', '306560']
nosy_count = 7.0
nosy_names = ['cjw296', 'michael.foord', 'pconnell', 'lisroach', 'mariocj89', 'cbelu', 'xtreak']
pr_nums = ['4476']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32092'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-146526

**Comment by 651e1c70-eaae-4801-8025-e18992128b87** [comment]
Currently, the autospec=True argument can be passed to mock.patch, but when trying to make assertions on the call and its arguments, it can fail, as it expects an instance / class instance reference as the first argument (self / cls arguments are not consumed when autospec-ing).

Steps to reproduce:

```pycon
>>> import mock
>>> from mock.tests import testmock
>>>
>>> with mock.patch.object(testmock.Something, 'meth', autospec=True):
...     smth = testmock.Something()
...     smth.meth(mock.sentinel.a, mock.sentinel.b, mock.sentinel.c, mock.sentinel.d)
...     smth.meth.assert_called_once_with(mock.sentinel.a, mock.sentinel.b, mock.sentinel.c, mock.sentinel.d)
...
<MagicMock name='meth()' id='139792133225424'>
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 318, in assert_called_once_with
    return mock.assert_called_once_with(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 948, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: meth(sentinel.a, sentinel.b, sentinel.c, sentinel.d)
Actual call: meth(<mock.tests.testmock.Something object at 0x7f23e456dcd0>, sentinel.a, sentinel.b, sentinel.c, sentinel.d)
```


Expected result: no AssertionError.

**Comment by 651e1c70-eaae-4801-8025-e18992128b87** [comment]
Currently, the autospec=True argument can be passed to mock.patch, but when trying to make assertions on the call and its arguments, it can fail, as it expects an instance / class instance reference as the first argument (self / cls arguments are not consumed when autospec-ing).

Steps to reproduce:

```pycon
ubuntu@ubuntu:/opt/stack/cpython$ ./python
Python 3.7.0a2+ (heads/mock-add-autospec:51a9270, Nov 20 2017, 06:48:44)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from unittest import mock
from unittest.test.testmock import testmock
```


```py
with mock.patch.object(testmock.Something, 'meth', autospec=True):
    smth = testmock.Something()
    smth.meth(mock.sentinel.a, mock.sentinel.b, mock.sentinel.c, mock.sentinel.d)
    smth.meth.assert_called_once_with(mock.sentinel.a, mock.sentinel.b, mock.sentinel.c, mock.sentinel.d)
```


```pycon
>>> >>> >>> ... ... ... ... <MagicMock name='meth()' id='140281858112024'>
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/opt/stack/cpython/Lib/unittest/mock.py", line 196, in assert_called_once_with
    return mock.assert_called_once_with(*args, **kwargs)
  File "/opt/stack/cpython/Lib/unittest/mock.py", line 856, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/opt/stack/cpython/Lib/unittest/mock.py", line 845, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: Expected call: meth(sentinel.a, sentinel.b, sentinel.c, sentinel.d)
Actual call: meth(<unittest.test.testmock.testmock.Something object at 0x7f95ea529a80>, sentinel.a, sentinel.b, sentinel.c, sentinel.d)
```


Expected result: no AssertionError.

**Comment by iritkatriel** [comment]
@bclau is this still relevant? The code changed quite a lot since 3.7.

**Comment by stephenfin** [comment]
@iritkatriel I don't have the ability to reopen this bug, but this is still relevant. Using the same reproducer, albeit with `unittest.mock` instead of `mock`.

```python
from unittest import mock

class Something(object):
    def meth(self, a, b, c, d=None): pass

    @classmethod
    def cmeth(cls, a, b, c, d=None): pass

    @staticmethod
    def smeth(a, b, c, d=None): pass

with mock.patch.object(Something, 'meth', autospec=True):
    smth = Something()
    smth.meth(mock.sentinel.a, mock.sentinel.b, mock.sentinel.c, mock.sentinel.d)
    smth.meth.assert_called_once_with(mock.sentinel.a, mock.sentinel.b, mock.sentinel.c, mock.sentinel.d
```

Running this with the most recent Python:

```shell
python3.14 test.py
```

```python
Traceback (most recent call last):
  File "/tmp/bar/test.py", line 15, in <module>
    smth.meth.assert_called_once_with(mock.sentinel.a, mock.sentinel.b, mock.sentinel.c, mock.sentinel.d)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/unittest/mock.py", line 245, in assert_called_once_with
    return mock.assert_called_once_with(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/unittest/mock.py", line 997, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/unittest/mock.py", line 985, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: meth(sentinel.a, sentinel.b, sentinel.c, sentinel.d)
  Actual: meth(<__main__.Something object at 0x7f30ac1c96a0>, sentinel.a, sentinel.b, sentinel.c, sentinel.d)
```

We have been carrying a fix for this in https://github.com/openstack/oslotest/ for a long time [here](https://github.com/openstack/oslotest/blob/master/oslotest/mock_fixture.py). I suspect an upstream solution would look very similar.
