### ISSUE TITLE
test_s_option() of test_site.HelperFunctionsTests failed on x86 Gentoo Refleaks 3.6

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76272]
BPO | [32091](https://bugs.python.org/issue32091)
--- | :---
Nosy | @vstinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-05-29.21:52:55.160>
created_at = <Date 2017-11-20.15:35:38.778>
labels = ['tests']
title = 'test_s_option() of test_site.HelperFunctionsTests failed on x86 Gentoo Refleaks 3.6'
updated_at = <Date 2018-05-29.21:52:55.159>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-29.21:52:55.159>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-05-29.21:52:55.160>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-11-20.15:35:38.778>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32091
keywords = []
message_count = 3.0
messages = ['306554', '306555', '318107']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32091'
versions = ['Python 2.7', 'Python 3.6']
```

</p></details>

**Comment by vstinner** [comment]
Failure on x86 Gentoo Refleaks 3.6:

http://buildbot.python.org/all/#/builders/72/builds/43


```pytb
0:58:35 load avg: 5.21 [135/406/1] test_site failed -- running: test_multiprocessing_forkserver (483 sec)
beginning 6 repetitions
123456
test test_site failed -- Traceback (most recent call last):
  File "/buildbot/buildarea/3.6.ware-gentoo-x86.refleak/build/Lib/test/test_site.py", line 186, in test_s_option
    self.assertIn(usersite, sys.path)
AssertionError: '/buildbot/buildarea/.local/lib/python3.6/site-packages' not found in ['', '/usr/local/lib/python36.zip', '/buildbot/buildarea/3.6.ware-gentoo-x86.refleak/build/Lib', '/buildbot/buildarea/3.6.ware-gentoo-x86.refleak/build/build/lib.linux-i686-3.6-pydebug', '/usr/local/lib/python3.6/site-packages']
(...)
Re-running test 'test_site' in verbose mode
(...)
FAIL: test_s_option (test.test_site.HelperFunctionsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/buildbot/buildarea/3.6.ware-gentoo-x86.refleak/build/Lib/test/test_site.py", line 186, in test_s_option
    self.assertIn(usersite, sys.path)
AssertionError: '/buildbot/buildarea/.local/lib/python3.6/site-packages' not found in ['', '/usr/local/lib/python36.zip', '/buildbot/buildarea/3.6.ware-gentoo-x86.refleak/build/Lib', '/buildbot/buildarea/3.6.ware-gentoo-x86.refleak/build/build/lib.linux-i686-3.6-pydebug', '/usr/local/lib/python3.6/site-packages']
```

**Comment by vstinner** [comment]
Same failure on x86 Gentoo Refleaks 2.7:

FAIL: test_s_option (test.test_site.HelperFunctionsTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/Lib/test/test_site.py", line 190, in test_s_option
    self.assertIn(usersite, sys.path)
AssertionError: '/buildbot/buildarea/.local/lib/python2.7/site-packages' not found in ['/usr/local/lib/python27.zip', '/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/Lib', '/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/Lib/plat-linux2', '/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/Lib/lib-tk', '/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/Lib/lib-old', '/buildbot/buildarea/2.7.ware-gentoo-x86.refleak/build/build/lib.linux-i686-2.7-pydebug', '/usr/local/lib/python2.7/site-packages']
```
