### ISSUE TITLE
[asyncio] test failure when the platform lacks a functional  sem_open()

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#76307]
BPO | [32126](https://bugs.python.org/issue32126)
--- | :---
Nosy | @xdegaye, @1st1
PRs | <li>python/cpython#4559</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-26.09:32:18.239>
created_at = <Date 2017-11-24.17:02:05.258>
labels = ['3.7', 'type-bug', 'tests', 'expert-asyncio']
title = '[asyncio] test failure when the platform lacks a functional  sem_open()'
updated_at = <Date 2017-11-26.09:32:18.238>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-26.09:32:18.238>
actor = 'xdegaye'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-26.09:32:18.239>
closer = 'xdegaye'
components = ['Tests', 'asyncio']
creation = <Date 2017-11-24.17:02:05.258>
creator = 'xdegaye'
dependencies = []
files = []
hgrepos = []
issue_num = 32126
keywords = ['patch']
message_count = 3.0
messages = ['306906', '306907', '306998']
nosy_count = 2.0
nosy_names = ['xdegaye', 'yselivanov']
pr_nums = ['4559']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32126'
versions = ['Python 3.7']
```

</p></details>

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
test_get_event_loop_new_process fails on Android API 24 with the error:

\======================================================================
ERROR: test_get_event_loop_new_process (test.test_asyncio.test_events.EPollEventLoopTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/sdcard/org.python/lib/python3.7/multiprocessing/synchronize.py", line 29, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'sem_unlink' from '_multiprocessing' (/data/local/tmp/python/lib/pyt
hon3.7/lib-dynload/_multiprocessing.cpython-37dm.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sdcard/org.python/lib/python3.7/test/test_asyncio/test_events.py", line 2239, in test_get_e
vent_loop_new_process
    self.loop.run_until_complete(main()),
  File "/sdcard/org.python/lib/python3.7/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/sdcard/org.python/lib/python3.7/test/test_asyncio/test_events.py", line 2230, in main
    pool = concurrent.futures.ProcessPoolExecutor()
  File "/sdcard/org.python/lib/python3.7/concurrent/futures/process.py", line 410, in __init__
    self._call_queue = mp_context.Queue(queue_size)
  File "/sdcard/org.python/lib/python3.7/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/sdcard/org.python/lib/python3.7/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/sdcard/org.python/lib/python3.7/multiprocessing/context.py", line 66, in Lock
    from .synchronize import Lock
  File "/sdcard/org.python/lib/python3.7/multiprocessing/synchronize.py", line 34, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required sync
hronization primitives needed will not function, see issue 3770.
```

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
See also the related issues:
bpo-3770: test_multiprocessing fails on systems with HAVE_SEM_OPEN=0
bpo-28668: instanciation of multiprocessing.Queue raises ImportError in test_logging
bpo-26924: android: test_concurrent_futures fails

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
New changeset a6fba9b827e395fc9583c07bc2d15cd11f684439 by xdegaye in branch 'master':
bpo-32126: Skip asyncio test when sem_open() is not functional (GH-4559)
https://github.com/python/cpython/commit/a6fba9b827e395fc9583c07bc2d15cd11f684439
