### ISSUE TITLE
test_nntplib: test_article_head_body() fails in SSL mode

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76309]
BPO | [32128](https://bugs.python.org/issue32128)
--- | :---
Nosy | @vstinner
PRs | <li>python/cpython#4552</li><li>python/cpython#4553</li><li>python/cpython#11612</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-19.23:07:48.137>
created_at = <Date 2017-11-25.01:23:42.090>
labels = ['3.7', 'tests']
title = 'test_nntplib: test_article_head_body() fails in SSL mode'
updated_at = <Date 2019-05-29.02:19:59.463>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-29.02:19:59.463>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-19.23:07:48.137>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-11-25.01:23:42.090>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32128
keywords = ['patch']
message_count = 3.0
messages = ['306930', '306931', '306933']
nosy_count = 1.0
nosy_names = ['vstinner']
pr_nums = ['4552', '4553', '11612']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32128'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
The news.trigofacile.com NNTP server used by test_nntplib currently has troubles on SSL:

```sh
$ ./python -m test -u all -v test_nntplib -m test_article_head_body  
```


======================================================================
FAIL: test_article_head_body (test.test_nntplib.NetworkedNNTP_SSLTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/haypo/prog/python/3.6/Lib/test/test_nntplib.py", line 242, in wrapped
    meth(self)
  File "/home/haypo/prog/python/3.6/Lib/test/test_nntplib.py", line 187, in test_article_head_body
    self.check_article_resp(resp, body, art_num)
  File "/home/haypo/prog/python/3.6/Lib/test/test_nntplib.py", line 167, in check_article_resp
    self.assertNotIn(article.lines[-1], (b".", b".\n", b".\r\n"))
AssertionError: b'.' unexpectedly found in (b'.', b'.\n', b'.\r\n')
```



See also bpo-19613.

**Comment by vstinner** [comment]
New changeset 706cb3162e15271ecfeba15909ed48a3a437009f by Victor Stinner in branch 'master':
bpo-32128: Skip test_nntplib.test_article_head_body() (bpo-4552)
https://github.com/python/cpython/commit/706cb3162e15271ecfeba15909ed48a3a437009f

**Comment by vstinner** [comment]
New changeset dde38b9cb3ff24f2f1f17cb681d30741e0090f51 by Victor Stinner (Miss Islington (bot)) in branch '3.6':
bpo-32128: Skip test_nntplib.test_article_head_body() (GH-4552) (bpo-4553)
https://github.com/python/cpython/commit/dde38b9cb3ff24f2f1f17cb681d30741e0090f51
