### ISSUE TITLE
bolen-dmg-3.x: compiled failed with: blurb: command not found

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76330]
BPO | [32149](https://bugs.python.org/issue32149)
--- | :---
Nosy | @db3l, @ronaldoussoren, @vstinner, @ned-deily, @zware
PRs | <li>python/cpython#4592</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-27.22:13:48.257>
created_at = <Date 2017-11-27.16:29:29.475>
labels = ['OS-mac', 'build', '3.7']
title = 'bolen-dmg-3.x: compiled failed with: blurb: command not found'
updated_at = <Date 2017-11-27.22:13:48.256>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-27.22:13:48.256>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-27.22:13:48.257>
closer = 'ned.deily'
components = ['Build', 'macOS']
creation = <Date 2017-11-27.16:29:29.475>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32149
keywords = ['patch', 'buildbot']
message_count = 7.0
messages = ['307065', '307066', '307069', '307078', '307083', '307096', '307099']
nosy_count = 5.0
nosy_names = ['db3l', 'ronaldoussoren', 'vstinner', 'ned.deily', 'zach.ware']
pr_nums = ['4592']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32149'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
/bin/sh: line 1: blurb: command not found

http://buildbot.python.org/all/#/builders/69/builds/51

```pytb
Running make frameworkinstallextras
(...)
copy /Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/Mac/../Tools/unittestgui/README.txt /Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/dmg/_root/Library/Frameworks/Python.framework/Versions/3.7/share/doc/python3.7/examples/Tools/unittestgui/README.txt
copy /Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/Mac/../Tools/unittestgui/unittestgui.py /Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/dmg/_root/Library/Frameworks/Python.framework/Versions/3.7/share/doc/python3.7/examples/Tools/unittestgui/unittestgui.py
Copying required shared libraries
Fix file modes
Install python documentation
rm -rf build/* ./venv/*
make: `venv' is up to date.
/bin/sh: line 1: blurb: command not found
make: *** [build] Error 127
Traceback (most recent call last):
mkdir -p build
Building NEWS from Misc/NEWS.d with blurb
  File "/Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/Mac/BuildScript/build-installer.py", line 1659, in <module>
    main()
  File "/Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/Mac/BuildScript/build-installer.py", line 1621, in main
    buildPythonDocs()
  File "/Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/Mac/BuildScript/build-installer.py", line 1094, in buildPythonDocs
    runCommand('make html PYTHON=venv/bin/python')
  File "/Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/Mac/BuildScript/build-installer.py", line 531, in runCommand
    raise RuntimeError("command failed: %s"%(commandline,))
RuntimeError: command failed: make html PYTHON=venv/bin/python
program finished with exit code 1
elapsedTime=1288.975592
```

**Comment by vstinner** [comment]
@David Bolen: Would you mind to take a look?

**Comment by zware** [comment]
This is likely due to a change I merged yesterday.

**Comment by db3l** [comment]
Yeah, I'm not sure if I can do anything on my side.  It looks like it's  an issue with the build patch (bpo-30487, commit d8d6b91, assuming that's what Zachary is referring to).  The blurb complaint is about something that appears should have been installed in a venv during the build process.  

If I need to upgrade or install something on the worker to support this change, I can certainly do that, but I don't immediately see what that should be.

**Comment by ned-deily** [comment]
I think the new change in bpo-30487 should be reverted.  It will likely break other build scripts.

**Comment by ned-deily** [comment]
New changeset 122fc136b34e11906466851e77bb6959946467ee by Ned Deily in branch 'master':
Revert "bpo-30487: automatically create a venv and install Sphinx when running make (GH-4346)" (bpo-4592)
https://github.com/python/cpython/commit/122fc136b34e11906466851e77bb6959946467ee

**Comment by ned-deily** [comment]
Reverting the change should now have fixed the build failure.  We'll see for sure next time the installer build runs.
