### ISSUE TITLE
mock.create_autospec fails if an attribute is a partial function

### ISSUE THREAD

**Issue by 651e1c70-eaae-4801-8025-e18992128b87** [python/cpython#76334]
BPO | [32153](https://bugs.python.org/issue32153)
--- | :---
Nosy | @cjw296, @berkerpeksag, @TonyFlury, @bclau, @tirkarthi
PRs | <li>python/cpython#10398</li><li>python/cpython#10855</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-12-12.08:05:43.105>
created_at = <Date 2017-11-28.10:23:15.019>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = 'mock.create_autospec fails if an attribute is a partial function'
updated_at = <Date 2018-12-12.08:05:43.104>
user = 'https://github.com/bclau'
```

bugs.python.org fields:
```python
activity = <Date 2018-12-12.08:05:43.104>
actor = 'cjw296'
assignee = 'none'
closed = True
closed_date = <Date 2018-12-12.08:05:43.105>
closer = 'cjw296'
components = ['Library (Lib)']
creation = <Date 2017-11-28.10:23:15.019>
creator = 'cbelu'
dependencies = []
files = []
hgrepos = []
issue_num = 32153
keywords = ['patch']
message_count = 12.0
messages = ['307115', '325465', '325466', '325467', '325487', '327529', '327531', '329433', '330907', '330909', '331675', '331677']
nosy_count = 5.0
nosy_names = ['cjw296', 'berker.peksag', 'anthony-flury', 'cbelu', 'xtreak']
pr_nums = ['10398', '10855']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32153'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 651e1c70-eaae-4801-8025-e18992128b87** [comment]
If an object's attribute is a partial function, mock.create_autospec will fail while trying to copy the partial functions' details to the mocked function, as the partial function does not have the \_\_name__ attribute.

Example:

```py
    import functools

    from unittest import mock


    class Proxy(object):
        def __init__(self, obj):
            self.obj

        def __getattr__(self, name):
            return functools.partial(self.__run_method, name)

        def __run_method(self, name, *args, **kwargs):
            return getattr(self.obj, name)(*args, **kwargs)

            
    a = mock.Mock()
    proxy = Proxy(a)

    mock.create_autospec(proxy)
```


Output:

```pytb
    Traceback (most recent call last):
      File "py3_mock_functools.py", line 20, in <module>
        mock.create_autospec(proxy)
      File "/usr/lib/python3.5/unittest/mock.py", line 2156, in create_autospec
        _check_signature(spec, mock, is_type, instance)
      File "/usr/lib/python3.5/unittest/mock.py", line 112, in _check_signature
        _copy_func_details(func, checksig)
      File "/usr/lib/python3.5/unittest/mock.py", line 117, in _copy_func_details
        funcopy.__name__ = func.__name__
    AttributeError: 'functools.partial' object has no attribute '__name__'
```
