### ISSUE TITLE
tab completion fails in pdb/ipdb/ipython for python3.7

### ISSUE THREAD

**Issue by 9e9aab4b-6760-455a-b3c4-6374cc9e0e53** [python/cpython#76368]
BPO | [32187](https://bugs.python.org/issue32187)
--- | :---
Nosy | @nartes
Files | <li>[Screenshot from 2017-11-30 23-04-28.png](https://bugs.python.org/file47310/Screenshot%20from%202017-11-30%2023-04-28.png "Uploaded as image/png at 2017-11-30.20:06:47 by @nartes")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-30.20:32:36.358>
created_at = <Date 2017-11-30.20:06:47.408>
labels = ['3.7', 'type-crash']
title = 'tab completion fails in pdb/ipdb/ipython for python3.7'
updated_at = <Date 2017-11-30.20:32:36.356>
user = 'https://github.com/nartes'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-30.20:32:36.356>
actor = 'nartes'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-30.20:32:36.358>
closer = 'nartes'
components = []
creation = <Date 2017-11-30.20:06:47.408>
creator = 'nartes'
dependencies = []
files = ['47310']
hgrepos = []
issue_num = 32187
keywords = []
message_count = 2.0
messages = ['307339', '307340']
nosy_count = 1.0
nosy_names = ['nartes']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue32187'
versions = ['Python 3.7']
```

</p></details>

**Comment by 9e9aab4b-6760-455a-b3c4-6374cc9e0e53** [comment]
Python 3.7.0a2+ (heads/master:bc8ac6b00e, Nov 30 2017, 22:14:00)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

```pytb
In [1]: import multiException in thread Thread-38:
Traceback (most recent call last):
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/parso/grammar.py", line 265, in load_grammar
    return _loaded_grammars[path]
KeyError: '/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/parso/python/grammar37.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/parso/grammar.py", line 268, in load_grammar
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/parso/python/grammar37.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 84, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 94, in _get_completions
    for c in completions:
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/core/completer.py", line 1791, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/core/completer.py", line 1831, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/core/completer.py", line 1998, in _complete
    cursor_pos, cursor_line, full_text)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/core/completer.py", line 1348, in _jedi_matches
    text, namespaces, column=cursor_column, line=cursor_line + 1)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/jedi/api/__init__.py", line 386, in __init__
    super(Interpreter, self).__init__(source, **kwds)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/jedi/api/__init__.py", line 110, in __init__
    self._grammar = parso.load_grammar()
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/parso/grammar.py", line 283, in load_grammar
    return load_grammar(**kwargs)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/parso/grammar.py", line 275, in load_grammar
    raise NotImplementedError(message)
NotImplementedError: Python version None is currently not supported.
```

**Comment by 9e9aab4b-6760-455a-b3c4-6374cc9e0e53** [comment]
installing parse 0.1.1 solves the issue
