### ISSUE TITLE
memoryview can set an exception in tp_clear

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#77894]
BPO | [33713](https://bugs.python.org/issue33713)
--- | :---
Nosy | @pitrou, @vstinner, @skrah, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-05-31.12:15:10.896>
labels = ['interpreter-core', '3.10', '3.9', 'type-crash', '3.11']
title = 'memoryview can set an exception in tp_clear'
updated_at = <Date 2021-10-18.20:19:58.191>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-18.20:19:58.191>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2018-05-31.12:15:10.896>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 33713
keywords = []
message_count = 14.0
messages = ['318288', '318291', '318295', '318296', '318297', '318298', '318299', '318300', '318306', '318316', '318318', '318319', '318320', '318586']
nosy_count = 4.0
nosy_names = ['pitrou', 'vstinner', 'skrah', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue33713'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-123898
* gh-123936
* gh-123937

**Comment by AlexSCFraser** [comment]
Several posts in the thread mention this is a purely theoretical concern, but I keep running into a crash bug that could be caused by this. The error I keep getting:

```Exception ignored in tp_clear of: <class 'memoryview'>
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
BufferError: memoryview has 1 exported buffer```

When this happens, the interpreter hard crashes, but I can just rerun my integration test or unit test without changing anything and then it will work. So it's some kind of uncommon intermittent error which is crashing the interpreter.

Unfortunately the error is intermittent and seems to happen very rarely. When it does happen, I can tell you that I am usually using the debugger to run code. I don't think it's happened to me when I'm not debugging. Also, the frequency of the error is greatly increased when using libraries which are actually wrappers to C or C++ code such as PyQT5. Most recently it happened to me during a subprocess.run() call to a binary executable on windows. I'm not sure if the underlying implementation of subprocess.run() has any non-python code that might be a source of errors as well. If I were to guess what the cause is, I imagine that there is an intermittent reference counting error in these foreign libraries the GC has no awareness of and this is somehow compounded by debugging because of additional variable references introduced by the debugger or something like that.

If I find a reliable method to reproduce this error I will document it and try to produce a minimal example, but it seems to occur very randomly even with the preconditions of running through the debugger and interfacing with C/C++ libraries.

**Comment by krzysgol** [comment]
Not sure if it helps but I'm getting 100% repro when starting the attached script using PyCharm debug. It never happens with debugger disconected.

Exception ignored in tp_clear of: <class 'memoryview'>
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 265, in __enter__
    return self._lock.__enter__()

[parallel.zip](https://github.com/python/cpython/files/12420202/parallel.zip)

**Comment by cyc1111111111** [comment]
> 该线程中的几篇文章提到这纯粹是理论上的问题，但我不断遇到可能由此引起的崩溃错误。我不断收到的错误：
> 
> ```
> Exception ignored in tp_clear of: <class 'memoryview'>
> Traceback (most recent call last):
>   File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
> BufferError: memoryview has 1 exported buffer
> ```
> 
> 发生这种情况时，解释器会严重崩溃，但我可以重新运行集成测试或单元测试而不更改任何内容，然后它就会工作。所以这是某种不常见的间歇性错误，导致解释器崩溃。
> 
> 不幸的是，该错误是间歇性的，并且似乎很少发生。当它确实发生时，我可以告诉你我通常使用调试器来运行代码。我不认为当我不调试时这会发生在我身上。此外，当使用实际上是 C 或 C++ 代码（例如 PyQT5）的包装器的库时，错误的频率会大大增加。最近，我在对 Windows 上的二进制可执行文件进行 subprocess.run() 调用时发生了这种情况。我不确定 subprocess.run() 的底层实现是否有任何非 python 代码也可能是错误来源。如果我要猜测原因是什么，我想这些外部库中存在间歇性引用计数错误，GC 没有意识到，并且由于调试器或类似的东西引入了额外的变量引用，调试在某种程度上使这种情况变得更加复杂。 。
> 
> 如果我找到一种可靠的方法来重现此错误，我将记录它并尝试生成一个最小的示例，但即使在运行调试器并与 C/C++ 库交互的前提下，它似乎也会非常随机地发生。
Have you solved this problem? I had the same problem

**Comment by cyc1111111111** [comment]
> 线程中的几篇文章中提到的这纯粹是理论上的问题，但我不断遇到可能不断引起的崩溃错误。我收到的错误：
> 
> ```
> Exception ignored in tp_clear of: <class 'memoryview'>
> Traceback (most recent call last):
>   File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
> BufferError: memoryview has 1 exported buffer
> ```
> 
> 发生这种情况时，解释器会严重崩溃，但我可以重新运行集成测试或单元测试而不更改任何内容，然后它就会工作。所以这是一种不常见的间歇性错误，导致解释器崩溃。
> 
> 不幸的是，该错误是间歇性的，而且似乎很少发生。当它确实发生时，我可以告诉你我通常使用调试器来发生运行代码。我不认为当我不调试时这会发生在我身上另外，当使用实际是 C 或 C++ 代码（如 PyQT5）的封装器的库时，错误的频率会大大增加。最近，我在对Windows 上的二进制执行文件进行 subprocess.run() 调用时发生了这种情况。我不确定 subprocess.run() 的底层实现是否有任何非 python 代码也可能是错误来源。如果我要猜测原因是什么，我想这些外部库中存在间歇性引用计数错误， GC 没有意识到，并且由于调试器或类似的东西引入了额外的引用，调试在某种程度上使这种情况变得更加复杂。
> 
> 如果我找到一种可靠的方法来修复此错误，我将记录它并尝试生成一个最小的样本，但即使在运行调试器并与 C/C++ 库交互的前提下，它似乎也非常随机地发生。

Have you solved this problem? I had the same problem

**Comment by serhiy-storchaka** [comment]
A reliable way to reproduce this issue using `pickle.PickleBuffer` was shown in #122306. There is other way that uses `memoryview.__getbuffer__`. Both ways were not available when this issue was opened. They may be the only ways, because I do not know other way to create an object that refers to a memoryview object exported via the buffer protocol.

So now, when we have reproducers and can write tests, I created #123898 which implements the idea proposed above -- only release the memoryview  object in `memory_clear()` if `self->exports == 0`.

**Comment by tjnd89** [comment]
@serhiy-storchaka If you are still looking for reproducible test cases, check out https://youtrack.jetbrains.com/issue/PY-54447. PyCharm users running under the debugger with code using `multiprocessing` and `concurrent.futures` have been seeing this since Python 3.10. Example code to reproduce is included.

**Comment by serhiy-storchaka** [comment]
I forgot to close this issue after merging #123898.

@tjnd89, thank you for reference. Did this change fix that issue? If no, it is perhaps not related.

**Comment by tjnd89** [comment]
@serhiy-storchaka I can confirm that the change seems to have fixed the issue. I ran the test code in the linked isue in Python 3.10 and reproduced the bug, then again in 3.12.7 with your fix and was not able to reproduce it. Thanks for chasing this down!

**Comment by lisa-gll** [comment]
It looks like all reproducers involve some kind of `getbuffer()` methods that expose a `memoryview` on the Python level.

The previous collection scheme apparently relied on not adding these methods, which is why https://github.com/python/cpython/issues/58006 has not been implemented for a long time.

The new scheme apparently swallows an exception:

```
class B(bytearray):
    def __buffer__(self, flags):
        return super().__buffer__(flags)
    def __release_buffer__(self, view):
        super().__release_buffer__(view)

X = B(b"xyz")
X.b = memoryview(X)
X.c = memoryview(X.b)
```

```
$ ./python swallow.py 
Exception ignored in __release_buffer__ of B:
AttributeError: __release_buffer__
SystemError: deallocated bytearray object has exported buffers
```

**Comment by lisa-gll** [comment]
The ignored exception comes from:

```
static void
bytearray_dealloc(PyByteArrayObject *self)
{
    if (self->ob_exports > 0) {
        PyErr_SetString(PyExc_SystemError,
                        "deallocated bytearray object has exported buffers");
        PyErr_Print();
    }
    if (self->ob_bytes != 0) {
        PyObject_Free(self->ob_bytes);
    }
    Py_TYPE(self)->tp_free((PyObject *)self);
}   
```

I have never seen this message before all `getbuffer()` methods were added, which I believe started in 3.10. This would be consistent with the Jetbrains issue (linked above in this issue), where people say 3.9 worked. I'm not sure why a bytearray with exports is allowed to be deallocated.
