### ISSUE TITLE
ProactorEventLoop raises AssertionError

### ISSUE THREAD

**Issue by 45bf83a6-23ac-4b3a-83de-214f929d7580** [python/cpython#78014]
BPO | [33833](https://bugs.python.org/issue33833)
--- | :---
Nosy | @vstinner, @asvetlov, @1st1, @twisteroidambassador, @miss-islington
PRs | <li>python/cpython#7632</li><li>python/cpython#7893</li><li>python/cpython#8575</li>
Files | <li>[test_proactor_force_close.py](https://bugs.python.org/file47639/test_proactor_force_close.py "Uploaded as text/plain at 2018-06-11.13:47:30 by @twisteroidambassador")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-07-30.20:14:24.359>
created_at = <Date 2018-06-11.13:47:30.402>
labels = ['3.8', 'type-bug', '3.7', 'expert-asyncio']
title = 'ProactorEventLoop raises AssertionError'
updated_at = <Date 2018-07-30.22:13:58.314>
user = 'https://github.com/twisteroidambassador'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-30.22:13:58.314>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-07-30.20:14:24.359>
closer = 'asvetlov'
components = ['asyncio']
creation = <Date 2018-06-11.13:47:30.402>
creator = 'twisteroid ambassador'
dependencies = []
files = ['47639']
hgrepos = []
issue_num = 33833
keywords = ['patch']
message_count = 8.0
messages = ['319302', '319306', '320584', '320642', '320643', '322685', '322687', '322693']
nosy_count = 5.0
nosy_names = ['vstinner', 'asvetlov', 'yselivanov', 'twisteroid ambassador', 'miss-islington']
pr_nums = ['7632', '7893', '8575']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue33833'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by BoilingNine** [comment]
I still get this problem when I call asyncio.run from a child thread in a loop
````python
Exception in callback _ProactorBaseWritePipeTransport._loop_writing(<_OverlappedF...hed result=27>)
handle: <Handle _ProactorBaseWritePipeTransport._loop_writing(<_OverlappedF...hed result=27>)>
Traceback (most recent call last):
  File "D:\software\.pyenv\pyenv-win-master\pyenv-win\versions\3.11.9\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "D:\software\.pyenv\pyenv-win-master\pyenv-win\versions\3.11.9\Lib\asyncio\proactor_events.py", line 381, in _loop_writing
    assert f is self._write_fut
           ^^^^^^^^^^^^^^^^^^^^
AssertionError  ```

**Comment by vstinner** [comment]
Please open a new issue, this issue is now closed.
