### ISSUE TITLE
python3 resource.setrlimit strange behaviour under macOS

### ISSUE THREAD

**Issue by 3bb821cc-a63f-44c5-9041-4ee21182864e** [python/cpython#78783]
BPO | [34602](https://bugs.python.org/issue34602)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @methane, @0-wiz-0, @ambv, @miss-islington, @vladima, @marche147
PRs | <li>python/cpython#13011</li><li>python/cpython#13013</li><li>python/cpython#13014</li><li>python/cpython#14546</li><li>python/cpython#14547</li><li>python/cpython#14548</li><li>python/cpython#14549</li><li>python/cpython#27309</li><li>python/cpython#28280</li><li>python/cpython#30490</li><li>python/cpython#30491</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-07-02.07:50:14.073>
created_at = <Date 2018-09-07.10:34:46.904>
labels = ['OS-mac', 'type-bug', '3.9', '3.10', '3.11', 'library']
title = 'python3 resource.setrlimit strange behaviour under macOS'
updated_at = <Date 2022-01-09.01:08:28.643>
user = 'https://github.com/marche147'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-09.01:08:28.643>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2019-07-02.07:50:14.073>
closer = 'ned.deily'
components = ['Library (Lib)', 'macOS']
creation = <Date 2018-09-07.10:34:46.904>
creator = 'marche147'
dependencies = []
files = []
hgrepos = []
issue_num = 34602
keywords = ['patch']
message_count = 22.0
messages = ['324731', '324737', '324818', '324824', '338868', '339197', '341112', '341114', '341118', '341120', '347110', '347113', '347115', '347117', '347119', '347167', '400984', '401879', '409803', '409879', '410032', '410126']
nosy_count = 9.0
nosy_names = ['ronaldoussoren', 'exarkun', 'ned.deily', 'methane', 'wiz', 'lukasz.langa', 'miss-islington', 'v2m', 'marche147']
pr_nums = ['13011', '13013', '13014', '14546', '14547', '14548', '14549', '27309', '28280', '30490', '30491']
priority = None
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue34602'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by ChannyClaus** [comment]
hi! sorry if i'm not being blind but is the new issue linked somewhere? i just ran into the same issue on python 3.12 😭 
```
$ cat test.py
import resource
s, h = resource.getrlimit(resource.RLIMIT_STACK)
resource.setrlimit(resource.RLIMIT_STACK, (h, h))
chan.kang@Chans-MacBook-Pro ~/test/resource - 
$ python test.py
Traceback (most recent call last):
  File "/Users/chan.kang/test/resource/test.py", line 3, in <module>
    resource.setrlimit(resource.RLIMIT_STACK, (h, h))
ValueError: current limit exceeds maximum limit
chan.kang@Chans-MacBook-Pro ~/test/resource - 
$ python --version
Python 3.12.1
chan.kang@Chans-MacBook-Pro ~/test/resource - 
$ uname -a
Darwin Chans-MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64
```

**Comment by bzamecnik** [comment]
Similar problem with setting `resource.RLIMIT_AS`:

Python 3.11.5 on MacOS 14.7.5 in Conda:
```
>>> import resource
>>> memory_limit = 2**31  # 2 GB
>>> resource.setrlimit(resource.RLIMIT_AS, (memory_limit, memory_limit))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: current limit exceeds maximum limit
```

**Comment by ronaldoussoren** [comment]
> Similar problem with setting `resource.RLIMIT_AS`:

This is a platform limitation the following program prints ``setrlimit: Invalid argument`` for me (macOS 15.4). The ``errno`` value is ``EINVAL`` which the resource module translates to a ``ValueError`` with the message "current limit exceeds maximum limit".

```c
#include <stdio.h>
#include <errno.h>
#include <sys/resource.h>

int main(void)
{
    struct rlimit limits = {
        (1ull << 31) - 1,
        (1ull << 31) - 1,
    };

    int r = setrlimit(RLIMIT_AS, &limits);
    if (r == -1) {
        perror("setrlimit");
        return 1;
    }
    return 0;
}
```

**Comment by skirpichev** [comment]
> This is a platform limitation the following program prints setrlimit: Invalid argument for me (macOS 15.4).

This seems not working for me also on macOS 14.8 and 15.7.   Is MacOS still POSIX-compliant?

**Comment by boomanaiden154** [comment]
The above example from @ronaldoussoren is failing because the limit being set in the program is `RLIMIT_AS`, not `RLIMIT_STACK` (which the issue is actually about). The following works for me while the above version with `RLIMIT_AS` does not:
```c++
#include <stdio.h>
#include <errno.h>
#include <sys/resource.h>

int main(void)
{
    struct rlimit limits = {
        4096 * 1024,
        4096 * 1024
    };

    int r = setrlimit(RLIMIT_STACK, &limits);
    if (r == -1) {
        perror("setrlimit");
        return 1;
    }
    return 0;
}
```
