### ISSUE TITLE
aexit called after loop close

### ISSUE THREAD

**Issue by 69038bab-3afc-4b0c-af11-cf6dc296e556** [python/cpython#79181]
BPO | [35000](https://bugs.python.org/issue35000)
--- | :---
Nosy | @asvetlov, @1st1, @pdxjohnny
Files | <li>[test.py](https://bugs.python.org/file47872/test.py "Uploaded as text/plain at 2018-10-16.15:49:58 by @pdxjohnny")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-10-16.15:49:11.621>
labels = ['3.7', '3.8', 'expert-asyncio']
title = 'aexit called after loop close'
updated_at = <Date 2018-10-16.15:49:58.345>
user = 'https://github.com/pdxjohnny'
```

bugs.python.org fields:
```python
activity = <Date 2018-10-16.15:49:58.345>
actor = 'pdxjohnny'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-10-16.15:49:11.621>
creator = 'pdxjohnny'
dependencies = []
files = ['47872']
hgrepos = []
issue_num = 35000
keywords = []
message_count = 1.0
messages = ['327839']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'pdxjohnny']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue35000'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
On main branch this is fixed, traceback:

```console
@kumaraditya303 ➜ /workspaces/cpython (main ✗) $ ./python  main.py 
^CHello!
Traceback (most recent call last):
  File "/workspaces/cpython/Lib/asyncio/runners.py", line 115, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/cpython/Lib/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/workspaces/cpython/main.py", line 39, in func
    await asyncio.sleep(5)
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/cpython/Lib/asyncio/tasks.py", line 648, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/cpython/main.py", line 44, in <module>
    main()
    ^^^^^^
  File "/workspaces/cpython/main.py", line 42, in main
    asyncio.run(func())
    ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/cpython/Lib/asyncio/runners.py", line 181, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/workspaces/cpython/Lib/asyncio/runners.py", line 118, in run
    raise KeyboardInterrupt()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

Closing as this is fixed.
