### ISSUE TITLE
Using skipTest with subTest gives a misleading UI.

### ISSUE THREAD

**Issue by pganssle** [python/cpython#79508]
BPO | [35327](https://bugs.python.org/issue35327)
--- | :---
Nosy | @rbtcollins, @ezio-melotti, @voidspace, @vadmium, @pganssle, @remilapeyre

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-11-27.15:24:27.966>
labels = ['3.8', '3.7', 'tests']
title = 'Using skipTest with subTest gives a misleading UI.'
updated_at = <Date 2018-11-30.11:12:16.149>
user = 'https://github.com/pganssle'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-30.11:12:16.149>
actor = 'martin.panter'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2018-11-27.15:24:27.966>
creator = 'p-ganssle'
dependencies = []
files = []
hgrepos = []
issue_num = 35327
keywords = []
message_count = 6.0
messages = ['330527', '330528', '330529', '330530', '330531', '330770']
nosy_count = 6.0
nosy_names = ['rbcollins', 'ezio.melotti', 'michael.foord', 'martin.panter', 'p-ganssle', 'remi.lapeyre']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue35327'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by freakboy3742** [comment]
I think this was resolved as part of #28082 as a fix for #70082, released in 3.11. 

If you modify the example provided to use a range of (1,5), it now renders as:
```
(venv3.12) rkm@eunectes local % python -m unittest -v
test_something (test_case.SomeTest.test_something) ... 
  test_something (test_case.SomeTest.test_something) [2] ... skipped 'Not supported'
  test_something (test_case.SomeTest.test_something) [3] ... skipped 'Not supported'
  test_something (test_case.SomeTest.test_something) [4] ... skipped 'Not supported'
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK (skipped=3)
```

However, if you modify the the `if i > 1` to `if i < 2`, it outputs:
```
(venv3.12) rkm@eunectes local % python -m unittest -v
test_something (test_case.SomeTest.test_something) ... 
  test_something (test_case.SomeTest.test_something) [1] ... skipped 'Not supported'
  test_something (test_case.SomeTest.test_something) [2] ... FAIL
  test_something (test_case.SomeTest.test_something) [3] ... FAIL
  test_something (test_case.SomeTest.test_something) [4] ... FAIL

======================================================================
FAIL: test_something (test_case.SomeTest.test_something) [2]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rkm/projects/python/cpython/local/test_case.py", line 11, in test_something
    self.assertEqual(i, 1)
AssertionError: 2 != 1

======================================================================
FAIL: test_something (test_case.SomeTest.test_something) [3]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rkm/projects/python/cpython/local/test_case.py", line 11, in test_something
    self.assertEqual(i, 1)
AssertionError: 3 != 1

======================================================================
FAIL: test_something (test_case.SomeTest.test_something) [4]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rkm/projects/python/cpython/local/test_case.py", line 11, in test_something
    self.assertEqual(i, 1)
AssertionError: 4 != 1

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=3, skipped=1)
```
