### ISSUE TITLE
get_lock() method is not present for Values created using multiprocessing.Manager()

### ISSUE THREAD

**Issue by 3f39b7df-87f5-469e-9817-0925c7b5c47c** [python/cpython#79967]
BPO | [35786](https://bugs.python.org/issue35786)
--- | :---
Nosy | @pfmoore, @pitrou, @tjguk, @zware, @MojoVampire, @applio, @websurfer5, @ian-bertolacci

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-01-19.21:50:32.910>
labels = ['3.7', 'library', 'docs']
title = 'get_lock() method is not present for Values created using multiprocessing.Manager()'
updated_at = <Date 2020-08-15.01:55:10.127>
user = 'https://bugs.python.org/LorenzoPersichetti'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-15.01:55:10.127>
actor = 'ned.deily'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Library (Lib)']
creation = <Date 2019-01-19.21:50:32.910>
creator = 'Lorenzo Persichetti'
dependencies = []
files = []
hgrepos = []
issue_num = 35786
keywords = []
message_count = 6.0
messages = ['334070', '334106', '349155', '349156', '349191', '373174']
nosy_count = 11.0
nosy_names = ['paul.moore', 'pitrou', 'tim.golden', 'docs@python', 'zach.ware', 'nemeskeyd', 'josh.r', 'davin', 'Lorenzo Persichetti', 'Jeffrey.Kintscher', 'IanBertolacci']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue35786'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by xintenseapple** [comment]
Are there any proposed solutions to this problem or any workaround aside from using an additional SyncManager.Lock object to synchronize access to a SyncManager.Value?

**Comment by rojikada** [comment]
This issue is still present since 2019, also just encountered this. I guess I will have to stick with additional Lock, but I welcome any updates on this.

**Comment by fearedbliss** [comment]
I just ran into this as well (expected `manager.Value` to be the same as `multiprocessing.Value`)

**Comment by lrlunin** [comment]
I've just encountered the same problem. I guess the main issue that the description of `ValueProxy` is missing in the official documentation. There is one variable `value` and two methods, namely `set()`/`get()`, available. I might guess that the `value` field of `ValueProxy` is identical to `Value`'s `value` field and is not thread-safe. I also guess that the `set()`/`get()` methods use some kind of locks internally and might be thread-safe interface for reading and writing to the variable.

It's nothing but my assumption and guess. I would ask the maintainers to describe this class in the documentation. Because right now there is even no mention of the `ValueProxy` in the docs.

**Comment by TheMatt2** [comment]
Ran into this as well. Surprised to find such a sharp corner in multiprocessing. Since `concurrent.futures.ProcessPoolExecutor` requires `multiprocessing.Manager()` objects, I was not able to use the normal value objects.
I would not have expected the current behavior based on the documentation.

**Comment by arrmansa** [comment]
Just ran into this as well while trying to increment a manager counter in `concurrent.futures.ProcessPoolExecutor`. If we can't change the existing `manager.Value` can we have a different attribute that is the same as `multiprocessing.Value` ? maybe `manager.cValue` or something else?

**Comment by RSKothari** [comment]
How is this issue still open? I am facing the same problem in Python 3.11.8.

```
    list(tqdm.tqdm(pool.starmap(process_event_file, [(event_file, path_figures, count_saccades, count_fixations, count_blinks) for event_file in event_files]), total=len(event_files)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
AttributeError: 'ValueProxy' object has no attribute 'get_lock'
```

**Comment by james-sullivan** [comment]
I ran into the same issue as well with Python 3.12.4

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/james/dev/PythonConcurrency/producer_consumer_practice.py", line 20, in produce
    with finished_producers.get_lock():
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ValueProxy' object has no attribute 'get_lock'
```

**Comment by brian030128** [comment]
ran into it today

**Comment by msaeedsaeedi** [comment]
😢 Tried today, but got this error too

**Comment by bbuman-meteomatics** [comment]
I also ran into that confusion today. I guess I will go with an extra lock.
