### ISSUE TITLE
get_type_hints exposes an instance of ForwardRef (internal class) in its result, with `from __future__ import annotations` enabled

### ISSUE THREAD

**Issue by 951a47db-0c43-4750-891c-b7e13e6fe23c** [python/cpython#80015]
BPO | [35834](https://bugs.python.org/issue35834)
--- | :---
Nosy | @gvanrossum, @ericvsmith, @stevendaprano, @ambv, @ilevkivskyi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-01-26.17:00:18.126>
labels = ['3.8', 'type-bug', '3.7']
title = 'get_type_hints exposes an instance of ForwardRef (internal class) in its result, with `from __future__ import annotations` enabled'
updated_at = <Date 2019-01-27.10:31:35.689>
user = 'https://bugs.python.org/LincolnQuirk'
```

bugs.python.org fields:
```python
activity = <Date 2019-01-27.10:31:35.689>
actor = 'levkivskyi'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2019-01-26.17:00:18.126>
creator = 'Lincoln Quirk'
dependencies = []
files = []
hgrepos = []
issue_num = 35834
keywords = []
message_count = 4.0
messages = ['334396', '334397', '334398', '334417']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'eric.smith', 'steven.daprano', 'lukasz.langa', 'levkivskyi', 'Lincoln Quirk']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue35834'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by AlexWaygood** [comment]
This seems to be fixed in 3.10, and may also be fixed in earlier versions:

```python
C:\Users\alexw\coding>python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import annotations
>>> import typing
>>> class A:
...     f: 'Undef'
...
>>> typing.get_type_hints(A)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1832, in get_type_hints
    value = _eval_type(value, base_globals, base_locals)
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\typing.py", line 699, in _evaluate
    self.__forward_value__ = _eval_type(
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Undef' is not defined
```

Cc. @LincolnQuirk
