### ISSUE TITLE
threading.Event().wait() not interruptable with Ctrl-C on Windows

### ISSUE THREAD

**Issue by e9052a66-9d25-42b8-b701-20e674176c81** [python/cpython#80116]
BPO | [35935](https://bugs.python.org/issue35935)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @chrisjbillington

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-02-08.01:12:57.458>
labels = ['3.10', 'type-bug', '3.8', '3.9', 'OS-windows']
title = 'threading.Event().wait() not interruptable with Ctrl-C on Windows'
updated_at = <Date 2021-03-03.17:50:09.938>
user = 'https://github.com/chrisjbillington'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-03.17:50:09.938>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2019-02-08.01:12:57.458>
creator = 'Chris Billington'
dependencies = []
files = []
hgrepos = []
issue_num = 35935
keywords = []
message_count = 7.0
messages = ['335049', '335050', '335056', '335086', '387997', '388028', '388037']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'Chris Billington', 'alegrigoriev']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue35935'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by vthemelis** [comment]
Hello,

Is anyone still looking at this?

**Comment by kumaraditya303** [comment]
This is fixed now as the underlying lock is interruptible now on Windows.

**Comment by alexchandel** [comment]
@kumaraditya303 Then this fixes a crazy hack I use to inject exceptions into running Python threads that are waiting `threading.Condition` variables.  What version of Python was it fixed it, 3.14.0?

**Comment by kumaraditya303** [comment]
> Then this fixes a crazy hack I use to inject exceptions into running Python threads that are waiting threading.Condition variables. What version of Python was it fixed it, 3.14.0?

Yes, it is fixed in 3.14

```console
❯ ./python.bat
Running Debug|x64 interpreter...
Python 3.14.0+ (heads/3.14:79c136f87b2, Nov 16 2025, 17:37:26) [MSC v.1944 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import threading
>>> threading.Event().wait()
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    threading.Event().wait()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\cpython\Lib\threading.py", line 670, in wait
    signaled = self._cond.wait(timeout)
  File "D:\cpython\Lib\threading.py", line 369, in wait
    waiter.acquire()
    ~~~~~~~~~~~~~~^^
KeyboardInterrupt
```
