### ISSUE TITLE
ipaddress.IPv4Network allows prefix > 32

### ISSUE THREAD

**Issue by afad9e83-6c14-4084-a82b-90e46d20c65e** [python/cpython#80170]
BPO | [35989](https://bugs.python.org/issue35989)
--- | :---
Nosy | @pitrou, @matrixise, @jheiv, @remilapeyre, @tirkarthi
PRs | <li>python/cpython#11844</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-02-13.16:13:55.267>
labels = ['3.7', 'type-bug', 'library']
title = 'ipaddress.IPv4Network allows prefix > 32'
updated_at = <Date 2019-05-18.12:19:37.025>
user = 'https://bugs.python.org/JohnFlorian'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-18.12:19:37.025>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-02-13.16:13:55.267>
creator = 'John Florian'
dependencies = []
files = []
hgrepos = []
issue_num = 35989
keywords = ['patch']
message_count = 5.0
messages = ['335460', '335475', '337228', '337230', '342795']
nosy_count = 6.0
nosy_names = ['pitrou', 'matrixise', 'jedwards', 'John Florian', 'remi.lapeyre', 'xtreak']
pr_nums = ['11844']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue35989'
versions = ['Python 3.7']
```

</p></details>

**Comment by furkanonder** [comment]
> See also [bpo-36845](https://bugs.python.org/issue?@action=redirect&bpo=36845) that seems to have fixed this.

Yes, the issue seems to be solved. I think we can close the issue.

```
>>> from ipaddress import IPv4Network
>>> n = IPv4Network(('192.168.123.234', 12345678))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/ipaddress.py", line 1513, in __init__
    self.netmask, self._prefixlen = self._make_netmask(mask)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ipaddress.py", line 1170, in _make_netmask
    cls._report_invalid_netmask(prefixlen)
  File "/usr/lib/python3.11/ipaddress.py", line 472, in _report_invalid_netmask
    raise NetmaskValueError(msg) from None
ipaddress.NetmaskValueError: 12345678 is not a valid netmask
>>> 
```

**Comment by devdanzin** [comment]
Seems completely fixed by #13298.
