### ISSUE TITLE
PyWeakref_NewRef docs are misleading

### ISSUE THREAD

**Issue by a23bc0d5-ffdb-42d1-b9e0-05244b380ebc** [python/cpython#80384]
BPO | [36203](https://bugs.python.org/issue36203)
--- | :---
Nosy | @Windsooon, @tekknolagi, @iritkatriel
PRs | <li>python/cpython#12244</li><li>python/cpython#26273</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-06.01:03:50.658>
labels = ['type-bug', '3.9', '3.10', '3.11', 'ctypes', 'docs']
title = 'PyWeakref_NewRef docs are misleading'
updated_at = <Date 2021-05-20.20:08:43.797>
user = 'https://github.com/tekknolagi'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-20.20:08:43.797>
actor = 'tekknolagi'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'ctypes']
creation = <Date 2019-03-06.01:03:50.658>
creator = 'tekknolagi'
dependencies = []
files = []
hgrepos = []
issue_num = 36203
keywords = ['patch']
message_count = 6.0
messages = ['337255', '337292', '337321', '337371', '337372', '394045']
nosy_count = 4.0
nosy_names = ['docs@python', 'Windson Yang', 'tekknolagi', 'iritkatriel']
pr_nums = ['12244', '26273']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36203'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
On Python side, `weakref.ref()` and `weakref.proxy()` also do not check that the callback argument is callable.

```pycon
>>> import weakref
>>> class A: pass
... 
>>> a = A()
>>> r = weakref.ref(a, 1)
>>> del a
Exception ignored while calling weakref callback 1:
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    del a
        ^
TypeError: 'int' object is not callable
>>> a = A()
>>> r = weakref.proxy(a, 1)
>>> del a
Exception ignored while calling weakref callback 1:
Traceback (most recent call last):
  File "<python-input-7>", line 1, in <module>
    del a
        ^
TypeError: 'int' object is not callable
```

The lack of the check here is not a bug. But it would be nice to check. For `PyWeakref_NewRef()`, the behavior does not match documentation, there is a bug. It can be fixed by changing the documentation, but it would be nice to have a check here. So, we can consider two issues here.

* Add the type check in `PyWeakref_NewRef()` and in Python interface. This is a new feature that fixes a bug.
* For older Python versions, simply change the documentation.

**Comment by serhiy-storchaka** [comment]
#151130 added a base for new C API tests. Now it is trivial to add new tests.

#151145 adds checks for callback in `weakref.ref()`, `weakref.proxy()`, `PyWeakref_NewRef()` and `PyWeakref_NewProxy()`.
#151146 fixes docs for `PyWeakref_NewRef()` and `PyWeakref_NewProxy()` in Python 3.15 (will be backported to 3.14 and 3.13).
