### ISSUE TITLE
Inconsistencies with datetime.fromtimestamp(t) when t < 0

### ISSUE THREAD

**Issue by a7079f5a-5350-4cd4-aae5-5fb4aeb13405** [python/cpython#80620]
BPO | [36439](https://bugs.python.org/issue36439)
--- | :---
Nosy | @zooba, @pganssle, @BoboTiG, @Dobatymo

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-26.15:18:26.163>
labels = ['3.8', 'type-bug', '3.7']
title = 'Inconsistencies with datetime.fromtimestamp(t) when t < 0'
updated_at = <Date 2020-10-14.01:11:02.349>
user = 'https://github.com/BoboTiG'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-14.01:11:02.349>
actor = 'Dobatymo'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2019-03-26.15:18:26.163>
creator = 'Tiger-222'
dependencies = []
files = []
hgrepos = []
issue_num = 36439
keywords = []
message_count = 8.0
messages = ['338893', '338894', '338896', '339038', '355822', '355831', '371200', '378591']
nosy_count = 5.0
nosy_names = ['steve.dower', 'p-ganssle', 'Tiger-222', 'Dobatymo', 'Paul Anton Letnes']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36439'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-134461
* gh-143463
* gh-143861

**Comment by StanFromIreland** [comment]
This is Windows specific and should be marked as such.

Unable to reproduce any of the errors presented here on Linux.

**Comment by wkoot** [comment]
Apart from the documented OverflowError, is there a possibility for a uniform solution - even if it's a custom calculation as suggested before?
Packages or code which relies on stdlib would need to implement a workaround for these far away dates.

NB: the upper range seems to have shifted to y3k'ish -
```python
Python 3.14.0 (tags/v3.14.0:ebf955d, Oct  7 2025, 10:15:03) [MSC v.1944 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from time import localtime
>>> 
>>> localtime(0)
time.struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=1, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=1, tm_isdst=0)
>>> localtime(-1)
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    localtime(-1)
    ~~~~~~~~~^^^^
OSError: [Errno 22] Invalid argument
>>> 
>>> localtime(32536799999)
time.struct_time(tm_year=3001, tm_mon=1, tm_mday=19, tm_hour=8, tm_min=59, tm_sec=59, tm_wday=0, tm_yday=19, tm_isdst=0)
>>> localtime(32536800000)
Traceback (most recent call last):
  File "<python-input-6>", line 1, in <module>
    localtime(32536800000)
    ~~~~~~~~~^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
>>>
>>>
>>> from datetime import datetime
>>>
>>> datetime.fromtimestamp(0)
datetime.datetime(1970, 1, 1, 1, 0)
>>> datetime.fromtimestamp(-1)
Traceback (most recent call last):
  File "<python-input-16>", line 1, in <module>
    datetime.fromtimestamp(-1)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^
OSError: [Errno 22] Invalid argument
>>>
>>> datetime.fromtimestamp(32536799999)
datetime.datetime(3001, 1, 19, 8, 59, 59)
>>> datetime.fromtimestamp(32536800000)
Traceback (most recent call last):
  File "<python-input-18>", line 1, in <module>
    datetime.fromtimestamp(32536800000)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
```

**Comment by vstinner** [comment]
Negative timestamps are now accepted on Windows:

```
Python 3.15.0a5+ (heads/main:f5685a266b2, Jan 15 2026, 10:57:22) [MSC v.1944 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> from time import localtime
>>> localtime(-1)
time.struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=13, tm_min=59, tm_sec=59, tm_wday=3, tm_yday=1, tm_isdst=-1)
```

**Comment by encukou** [comment]
This broke `test_time` on some buildbots.

**Comment by encukou** [comment]
Thank you!
