### ISSUE TITLE
__aexit__ is not called when a context manager is used in an async generator

### ISSUE THREAD

**Issue by 8438cdbe-fae7-4ba1-9faf-263073c896be** [python/cpython#80630]
BPO | [36449](https://bugs.python.org/issue36449)
--- | :---
Nosy | @asvetlov, @1st1, @tirkarthi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-27.11:28:56.769>
labels = ['3.7', 'expert-asyncio']
title = '__aexit__ is not called when a context manager is used in an async generator'
updated_at = <Date 2019-03-27.11:44:22.602>
user = 'https://bugs.python.org/AndreyLemets'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-27.11:44:22.602>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-03-27.11:28:56.769>
creator = 'Andrey Lemets'
dependencies = []
files = []
hgrepos = []
issue_num = 36449
keywords = []
message_count = 2.0
messages = ['338953', '338954']
nosy_count = 5.0
nosy_names = ['asvetlov', 'asksol', 'yselivanov', 'xtreak', 'Andrey Lemets']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue36449'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by kumaraditya303** [comment]
Fixed on main branch:

```console
@kumaraditya303 ➜ /workspaces/cpython (main ✗) $ ./python main.py 
aenter
aexit
Traceback (most recent call last):
  File "/workspaces/cpython/main.py", line 24, in <module>
    asyncio.run(main())
    ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/cpython/Lib/asyncio/runners.py", line 181, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/workspaces/cpython/Lib/asyncio/runners.py", line 115, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/cpython/Lib/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/workspaces/cpython/main.py", line 20, in main
    raise Exception
    ^^^^^^^^^^^^^^^
Exception
```
