### ISSUE TITLE
functools.singledispatchmethod interacts poorly with subclasses

### ISSUE THREAD

**Issue by bfff79b6-afcb-495e-a64e-24c5375ac80a** [python/cpython#80638]
BPO | [36457](https://bugs.python.org/issue36457)
--- | :---
Nosy | @methane, @ambv, @tim-mitchell
Files | <li>[methoddispatch36.py](https://bugs.python.org/file48235/methoddispatch36.py "Uploaded as text/plain at 2019-03-28.03:42:38 by @tim-mitchell"): alternate implementation from methoddispatch package</li><li>[singledispatchmethod.py](https://bugs.python.org/file48261/singledispatchmethod.py "Uploaded as text/plain at 2019-04-12.04:43:16 by @tim-mitchell"): improved implementation</li><li>[singledispatchmethod.py](https://bugs.python.org/file50688/singledispatchmethod.py "Uploaded as text/plain at 2022-03-18.06:05:55 by @tim-mitchell")</li><li>[test_sdm.py](https://bugs.python.org/file50689/test_sdm.py "Uploaded as text/plain at 2022-03-18.06:10:24 by @tim-mitchell"): implementation tests</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-28.03:42:39.296>
labels = ['3.8', 'type-bug', 'library']
title = 'functools.singledispatchmethod interacts poorly with subclasses'
updated_at = <Date 2022-03-18.06:10:24.323>
user = 'https://github.com/tim-mitchell'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-18.06:10:24.323>
actor = 'Tim Mitchell2'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-03-28.03:42:39.296>
creator = 'Tim Mitchell2'
dependencies = []
files = ['48235', '48261', '50688', '50689']
hgrepos = []
issue_num = 36457
keywords = []
message_count = 5.0
messages = ['339008', '340005', '370758', '371014', '415470']
nosy_count = 5.0
nosy_names = ['methane', 'lukasz.langa', 'Tim Mitchell2', 'dschaumont', 'bojan.jovanovic.gtech']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36457'
versions = ['Python 3.8']
```

</p></details>

**Comment by ivan-sanchez-frontiers** [comment]
I'd love this!

**Comment by ivan-sanchez-frontiers** [comment]
Should perhaps the issue be re-issued/modified since it's for python 3.8?

**Comment by surister** [comment]
The latest `singledispatchmethod.py` uploaded in 2022 breaks in this situation:

Tried on python 3.8.10, 3.10.8

```python
from implementation_3 import singledispatchmethod


class Base:
    @singledispatchmethod
    def method_1(self, a):
        raise NotImplementedError()

    @singledispatchmethod
    def method_2(self, a):
        raise NotImplementedError()

    @method_1.register(int)
    def _(self, a):
        print('Int in method_1')

    @method_2.register(int)
    def _(self, a):
        print('Int in method_"')


class Child(Base):
    pass


c = Child()
c.method_1(1)
c.method_2(1)

```

```python
Traceback (most recent call last):
  File "/opt/project/singledispatchmethod_bug.py", line 27, in <module>
    c.method_1(1)
  File "/opt/project/implementation_3.py", line 211, in __call__
    return self.dispatch(args[0].__class__)(self._instance, *args, **kwargs)
  File "/opt/project/singledispatchmethod_bug.py", line 7, in method_1
    raise NotImplementedError()
NotImplementedError

Process finished with exit code 1
```

It's because I named the functions as '_' which I expect most people to do as it's how it is teached on the docs.

If you change 
```py
@method_1.register(int)
def _(self, a): ...
```
to
```py
@method_1.register(int)
def method_1(self, a): ...
```
It works as expected.

**Comment by surister** [comment]
Also:

```python
from implementation_3 import singledispatchmethod


class Base:
    @singledispatchmethod
    def method_1(self, a):
        raise NotImplementedError()

    @singledispatchmethod
    def method_2(self, a):
        raise NotImplementedError()

    @method_1.register(int)
    def method_1(self, a):
        print('Int in method_1')


c = Base()
c.method_1(1)
c.method_2(1)
```

```python
Traceback (most recent call last):
  File "/opt/project/singledispatchmethod_bug2.py", line 26, in <module>
    c.method_2(1)
  File "/opt/project/implementation_3.py", line 132, in __get__
    _fixup_class_attributes(base)
  File "/opt/project/implementation_3.py", line 241, in _fixup_class_attributes
    generic._register(cls, value)
AttributeError: 'function' object has no attribute '_register'
```
