### ISSUE TITLE
Distutils VC 6.0 Errors When Using mingw-w64 GCC

### ISSUE THREAD

**Issue by b5e37b4c-357a-42eb-ab8f-24ed2c64ec0f** [python/cpython#80720]
BPO | [36539](https://bugs.python.org/issue36539)
--- | :---
Nosy | @merwok, @dstufft, @lazka, @danyeaw

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-04-07.01:15:00.747>
created_at = <Date 2019-04-05.21:13:22.368>
labels = ['3.7', 'invalid', 'build', 'library']
title = 'Distutils VC 6.0 Errors When Using mingw-w64 GCC'
updated_at = <Date 2019-04-07.01:15:00.743>
user = 'https://github.com/danyeaw'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-07.01:15:00.743>
actor = 'danyeaw'
assignee = 'none'
closed = True
closed_date = <Date 2019-04-07.01:15:00.747>
closer = 'danyeaw'
components = ['Distutils']
creation = <Date 2019-04-05.21:13:22.368>
creator = 'danyeaw'
dependencies = []
files = []
hgrepos = []
issue_num = 36539
keywords = []
message_count = 3.0
messages = ['339520', '339525', '339551']
nosy_count = 4.0
nosy_names = ['eric.araujo', 'dstufft', 'lazka', 'danyeaw']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue36539'
versions = ['Python 3.7']
```

</p></details>

**Comment by uday18git** [comment]
pip install numpy==1.19.3
Collecting numpy==1.19.3
  Using cached numpy-1.19.3.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Traceback (most recent call last):
        File "C:\msys64\mingw64\lib\python3.9\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\msys64\mingw64\lib\python3.9\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\msys64\mingw64\lib\python3.9\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
        File "C:\msys64\mingw64\lib\python3.9\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
        File "C:\msys64\mingw64\lib\python3.9\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "C:\Users\kcuda\AppData\Local\Temp\pip-build-env-lwb36tz1\overlay\lib\python3.9\site-packages\setuptools\__init__.py", line 253, in <module>
          monkey.patch_all()
        File "C:\Users\kcuda\AppData\Local\Temp\pip-build-env-lwb36tz1\overlay\lib\python3.9\site-packages\setuptools\monkey.py", line 101, in patch_all
          patch_for_msvc_specialized_compiler()
        File "C:\Users\kcuda\AppData\Local\Temp\pip-build-env-lwb36tz1\overlay\lib\python3.9\site-packages\setuptools\monkey.py", line 164, in patch_for_msvc_specialized_compiler
          patch_func(*msvc9('find_vcvarsall'))
        File "C:\Users\kcuda\AppData\Local\Temp\pip-build-env-lwb36tz1\overlay\lib\python3.9\site-packages\setuptools\monkey.py", line 151, in patch_params
          mod = import_module(mod_name)
        File "C:\msys64\mingw64\lib\python3.9\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "C:\Users\kcuda\AppData\Local\Temp\pip-build-env-lwb36tz1\overlay\lib\python3.9\site-packages\setuptools\_distutils\msvc9compiler.py", line 295, in <module>
          raise DistutilsPlatformError("VC %0.1f is not supported by this module" % VERSION)
      distutils.errors.DistutilsPlatformError: VC 6.0 is not supported by this module
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


I try to install numpy, opencv or deepface.. the same error comes of vc6.0 is not supported by this module, can you please tell how to fix this

**Comment by bambooozeld** [comment]
@uday18git I fixed it by removing the "normal" setuptools and using the one from the pacman repo.

```
pip uninstall setuptools
pacman -S mingw-w64-x86_64-python-setuptools
```

or if you use python3:

```
pip3 uninstall setuptools
pacman -S mingw-w64-x86_x64-python3-setuptools 
```
