### ISSUE TITLE
configured libdir not correctly passed to Python executable

### ISSUE THREAD

**Issue by 2f9dae4c-238f-42b3-a19c-8ab844056834** [python/cpython#80939]
BPO | [36758](https://bugs.python.org/issue36758)
--- | :---
Nosy | @vstinner, @michael-o, @websurfer5

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-04-30.11:15:47.996>
labels = ['3.8', 'build', 'expert-installation']
title = 'configured libdir not correctly passed to Python executable'
updated_at = <Date 2019-12-10.07:51:18.677>
user = 'https://github.com/michael-o'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-10.07:51:18.677>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build', 'Installation']
creation = <Date 2019-04-30.11:15:47.996>
creator = 'michael-o'
dependencies = []
files = []
hgrepos = []
issue_num = 36758
keywords = []
message_count = 2.0
messages = ['341148', '341354']
nosy_count = 3.0
nosy_names = ['vstinner', 'michael-o', 'Jeffrey.Kintscher']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue36758'
versions = ['Python 3.8']
```

</p></details>

**Comment by michael-o** [comment]
I guess this bug isn't on the radar at the moment...

**Comment by vstinner** [comment]
> I guess this bug isn't on the radar at the moment...

Can you reproduce the issue on Linux? If yes, please give instructions to reproduce the issue.

cc @erlend-aasland

**Comment by michael-o** [comment]
> > I guess this bug isn't on the radar at the moment...
> 
> Can you reproduce the issue on Linux? If yes, please give instructions to reproduce the issue.
> 
> cc @erlend-aasland

Let me try tomorrow,  would FreeBSD also be fine? I have only one spare RHEL 7 machine for this.

**Comment by vstinner** [comment]
An OS more common than HP-UX may motive other people to dig into your issue.

**Comment by michael-o** [comment]
@vstinner, have a look and tell me what you think:

Reproduced on FreeBSD 12-STABLE:
```
export PREFIX=/var/tmp/opt/ports
export LIBDIR=$PREFIX/lib/freebsd64
export SYSCONFDIR=/var/tmp/etc/ports
export CONFIGURE="./configure --prefix=$PREFIX --libdir=$LIBDIR --sysconfdir=$SYSCONFDIR --localstatedir=/var"
export CPPFLAGS="-I$PREFIX/include"
export LDFLAGS="-L$LIBDIR"
```
then used `$CONFIGURE` on all current branches:
3.8:
```
cc -pthread -c -fPIC -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall    -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration  -I./Include/internal  -I. -I./Include -I/var/tmp/opt/ports/include -I/var/tmp/opt/ports/include  -DPy_BUILD_CORE -o Modules/_math.o Modules/_math.c
 CC='cc -pthread' LDSHARED='cc -pthread -shared -L/var/tmp/opt/ports/lib/freebsd64 -L/var/tmp/opt/ports/lib/freebsd64  ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall'    _TCLTK_INCLUDES='' _TCLTK_LIBS=''       ./python -E ./setup.py  build
Traceback (most recent call last):
  File "./setup.py", line 2320, in <module>
    class PyBuildInstallLib(install_lib):
  File "./setup.py", line 2327, in PyBuildInstallLib
    shlib_suffix = sysconfig.get_config_var("SHLIB_SUFFIX")
  File "/net/home/osipovmi/cpython/Lib/sysconfig.py", line 615, in get_config_var
    return get_config_vars().get(name)
  File "/net/home/osipovmi/cpython/Lib/sysconfig.py", line 564, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/net/home/osipovmi/cpython/Lib/sysconfig.py", line 432, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata__freebsd12_x86_64-unknown-freebsd12'
gmake: *** [Makefile:617: sharedmods] Fehler 1
```

3.9:
```
osipovmi@deblndw011x:~/cpython (3.9 %=)
$ python3
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python 3.9.17+ (heads/3.9:38b489bae8, Aug 22 2023, 11:12:25)
[Clang 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

3.10:
```
osipovmi@deblndw011x:~/cpython (3.10 =)
$ python3
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python 3.10.12+ (heads/3.10:56e8c87e84, Aug 22 2023, 11:20:50) [Clang 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a3 on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

3.11:
```
osipovmi@deblndw011x:~/cpython (3.11 =)
$ python3
Could not find platform dependent libraries <exec_prefix>
Python 3.11.4+ (heads/3.11:8e837373ed, Aug 22 2023, 11:25:36) [Clang 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a3 on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
```

3.12:
```
osipovmi@deblndw011x:~/cpython (3.12 =)
$ python3
Could not find platform dependent libraries <exec_prefix>
Python 3.12.0rc1+ (heads/3.12:47f60c3f67, Aug 22 2023, 11:33:35) [Clang 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a3 on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

main:
```
osipovmi@deblndw011x:~/cpython (main =)
$ python3
Could not find platform dependent libraries <exec_prefix>
Python 3.13.0a0 (heads/main:86617518c4, Aug 22 2023, 11:41:03) [Clang 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a3 on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
```

So I consider that this problem still persists and is not a platform issue.

**Comment by erlend-aasland** [comment]
Python 3.8 does not accept bug-fixes anymore, only security fixes. Judging from https://github.com/python/cpython/issues/80939#issuecomment-1687851299, it seems to me this is a problem in 3.8 only. Suggesting to close as wont-fix.

**Comment by michael-o** [comment]
> Python 3.8 does not accept bug-fixes anymore, only security fixes. Judging from [#80939 (comment)](https://github.com/python/cpython/issues/80939#issuecomment-1687851299), it seems to me this is a problem in 3.8 only. Suggesting to close as wont-fix.

What? Regardless of 3.8, it fails on other versions as you can see by the output. How can you consider this as wontfix?

**Comment by erlend-aasland** [comment]
> What? Regardless of 3.8, it fails on other versions as you can see by the output. How can you consider this as wontfix?

Ah, I failed to see the `Could not find platform dependent libraries <exec_prefix>` lines.

Hm, yeah, configure.ac ignores `libdir`. In fact, it ignore pretty much all of the standard GNU Autoconf dir arguments, except `prefix` (AFAICS).

**Comment by erlend-aasland** [comment]
Looking more closely, it looks like some of these are passed straight on to the Makefile, though, including `libdir`.

**Comment by erlend-aasland** [comment]
AFAICS; this has nothing to do with the build/installation; it has to do with lookup (getpath.c).

**Comment by michael-o** [comment]
> AFAICS; this has nothing to do with the build/installation; it has to do with lookup (getpath.{c,py}).

There is yet another bug during installation: I have requested this subdir, but libs still partially don't land there:
```
osipovmi@deblndw011x:/var/tmp/opt/ports
$ ll lib/
total 8
drwxr-xr-x   4 osipovmi  wheel   512 2023-08-22 11:43 freebsd64/
drwxr-xr-x  37 osipovmi  wheel  4096 2023-08-22 11:43 python3.13/
```
I'd expect everything to be in `freebsd64`, no?

**Comment by erlend-aasland** [comment]
`python3.13/` contains Python libraries (site packages). I'd guess that `freebsd64` contains the binary library (`libpython3.13.a`).

**Comment by michael-o** [comment]
> `python3.13/` contains Python libraries (site packages). I'd guess that `freebsd64` contains the binary library (`libpython3.13.a`).
> 
> But this is off-topic; if there's a problem with `--prefix`, report that as a separate issue.

Correct, I think this needs to be addressed before I can go on with the new issue.
