### ISSUE TITLE
Import deadlock detection causes deadlock

### ISSUE THREAD

**Issue by 9a4854ba-a0a7-4291-945b-b0004bf07198** [python/cpython#82272]
BPO | [38091](https://bugs.python.org/issue38091)
--- | :---
Nosy | @brettcannon, @pitrou, @ericsnowcurrently, @rlamy, @phmc, @miss-islington, @vzhestkov
PRs | <li>python/cpython#17518</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-09-10.13:26:40.706>
labels = ['3.7', '3.8', 'type-bug', 'library', '3.9']
title = 'Import deadlock detection causes deadlock'
updated_at = <Date 2021-07-20.16:00:14.797>
user = 'https://github.com/rlamy'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-20.16:00:14.797>
actor = 'vzhestkov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-09-10.13:26:40.706>
creator = 'Ronan.Lamy'
dependencies = []
files = []
hgrepos = []
issue_num = 38091
keywords = ['patch']
message_count = 3.0
messages = ['351647', '363232', '397884']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'pitrou', 'eric.snow', 'Ronan.Lamy', 'pconnell', 'miss-islington', 'vzhestkov']
pr_nums = ['17518']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38091'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by encukou** [comment]
I just saw a [buildbot failure](https://buildbot.python.org/all/#/builders/540/builds/3379) that might be related to the test added in #17518:
```
test_concurrency (test.test_import.ImportTests.test_concurrency) ... Warning -- Uncaught thread exception: RuntimeError
Exception in thread Thread-3 (run):
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-sles-z/build/Lib/threading.py", line 1036, in _bootstrap_inner
    self.run()
  File "/home/dje/cpython-buildarea/3.x.edelsohn-sles-z/build/Lib/threading.py", line 973, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dje/cpython-buildarea/3.x.edelsohn-sles-z/build/Lib/test/test_import/__init__.py", line 471, in run
    sys.settrace(None)
RuntimeError: Cannot install a trace function while another trace function is being installed
ok
```
