### ISSUE TITLE
[Windows] multiprocessing: DupHandle.detach() race condition on DuplicateHandle(DUPLICATE_CLOSE_SOURCE)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#82444]
BPO | [38263](https://bugs.python.org/issue38263)
--- | :---
Nosy | @pitrou, @eryksun, @s0undt3ch, @pablogsal, @Yan Ren

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-09-24.10:36:39.140>
labels = ['build', 'library', '3.9']
title = '[Windows] multiprocessing: DupHandle.detach() race condition on DuplicateHandle(DUPLICATE_CLOSE_SOURCE)'
updated_at = <Date 2021-04-10.01:07:14.748>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-10.01:07:14.748>
actor = 'leonardo2'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-09-24.10:36:39.140>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 38263
keywords = []
message_count = 8.0
messages = ['353064', '362460', '362466', '362471', '377296', '389832', '390229', '390683']
nosy_count = 7.0
nosy_names = ['pitrou', 'eryksun', 's0undt3ch', 'pablogsal', 'pemryan', 'jesvi22j', 'leonardo2']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue38263'
versions = ['Python 3.9']
```

</p></details>

**Comment by 00938091-2a30-4bf6-a34a-2ea2b1402ac8** [comment]
What I'm able to copy from the console(though I doubt I'm getting all of
the traceback):

```pytb
  Traceback (most recent call last):
    File "<string\>", line 1, in <module\>
    File "c:\\hostedtoolcache\\windows\\python\\3.5.4\\x64\\lib\\multiprocessing\\spawn.py", line 106, in spawn_main
      exitcode = _main(fd)
    File "c:\\hostedtoolcache\\windows\\python\\3.5.4\\x64\\lib\\multiprocessing\\spawn.py", line 116, in _main
      self = pickle.load(from_parent)
    File "c:\\hostedtoolcache\\windows\\python\\3.5.4\\x64\\lib\\multiprocessing\\connection.py", line 942, in rebuild_pipe_connection
      handle = dh.detach()
    File "c:\\hostedtoolcache\\windows\\python\\3.5.4\\x64\\lib\\multiprocessing\\reduction.py", line 128, in detach
      self._access, False, _winapi.DUPLICATE_CLOSE_SOURCE)

PermissionError: [WinError 5] Access is denied
```

Pedro Algarvio @ Phone

A sábado, 22/02/2020, 13:44, Eryk Sun \<report@bugs.python.org\> escreveu:

```pytb
>
> Eryk Sun <eryksun@gmail.com> added the comment:
>
> > I seem to be consistingly hitting this issue.
>
> It will help with test development if you can provide a minimal example
> that reliably reproduces the problem.
>
> In msg353064 I see DuplicateHandle calls failing with ERROR_ACCESS_DENIED
> (5). Assuming the process handles have the required PROCESS_DUP_HANDLE
> access, it's most likely the case that the underlying NtDuplicateObject
> system call is failing with STATUS_PROCESS_IS_TERMINATING (0xC000010A). For
> example:
>
>     import ctypes
>     ntdll = ctypes.WinDLL('ntdll')
>     from subprocess import Popen, PIPE
>     from _winapi import GetCurrentProcess, TerminateProcess
>     from _winapi import DuplicateHandle, DUPLICATE_SAME_ACCESS
>
>     p = Popen('cmd.exe', stdin=PIPE, stdout=PIPE, stderr=PIPE)
>     TerminateProcess(p._handle, 0)
>
> Try to duplicate the process handle into the terminated process:
>
>     >>> source = GetCurrentProcess()
>     >>> target = handle = p._handle
>     >>> try:
>     ...     DuplicateHandle(source, handle, target,
>     ...         0, False, DUPLICATE_SAME_ACCESS)
>     ... except:
>     ...     status = ntdll.RtlGetLastNtStatus()
>     ...     print(f'NTSTATUS: {status & (2**32-1):#010x}')
>     ...     raise
>     ...
>     NTSTATUS: 0xc000010a
>     Traceback (most recent call last):
>       File "<stdin>", line 2, in <module>
>     PermissionError: [WinError 5] Access is denied
>
> 
```
----------
> nosy: +eryksun
>
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<https://bugs.python.org/issue38263\>
> _______________________________________
>

**Comment by vstinner** [comment]
While it's a real issue, sadly it seems like nobody is available to propose a real fix (PR). I don't have the bandwidth to work on this issue, so sorry I just close it.
