### ISSUE TITLE
__import__ is not thread-safe on Python 3

### ISSUE THREAD

**Issue by 2ecf16d7-7e1f-4944-819e-c7b964dad848** [python/cpython#83065]
BPO | [38884](https://bugs.python.org/issue38884)
--- | :---
Nosy | @brettcannon, @gpshead, @ncoghlan, @ericsnowcurrently, @mulka
Files | <li>[import_module_not_found.py](https://bugs.python.org/file48734/import_module_not_found.py "Uploaded as text/plain at 2019-11-21.19:11:54 by Valentyn Tymofieiev")</li><li>[import_deadlock.py](https://bugs.python.org/file48735/import_deadlock.py "Uploaded as text/plain at 2019-11-21.19:13:23 by Valentyn Tymofieiev")</li><li>[issue38884.zip](https://bugs.python.org/file48737/issue38884.zip "Uploaded as application/zip at 2019-11-21.22:30:18 by Valentyn Tymofieiev")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-11-21.19:11:54.536>
labels = ['3.7', '3.8', '3.9']
title = '__import__ is not thread-safe on Python 3'
updated_at = <Date 2021-12-08.22:53:27.704>
user = 'https://bugs.python.org/ValentynTymofieiev'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-08.22:53:27.704>
actor = 'Valentyn Tymofieiev'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2019-11-21.19:11:54.536>
creator = 'Valentyn Tymofieiev'
dependencies = []
files = ['48734', '48735', '48737']
hgrepos = []
issue_num = 38884
keywords = []
message_count = 14.0
messages = ['357198', '357199', '357202', '357214', '357227', '357228', '357230', '357234', '357464', '360068', '360069', '362746', '375958', '408052']
nosy_count = 9.0
nosy_names = ['brett.cannon', 'gregory.p.smith', 'gjb1002', 'ncoghlan', 'eric.snow', 'ryan.petrello', 'Valentyn Tymofieiev', 'Martin Laus', 'repalviglator']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue38884'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-137196

**Comment by emmatyping** [comment]
The case as I understand it is that T1 imports `package.subpackage`, which in it's `__init__.py` imports `package.subpackage.module`
Simultaneously, T2 is trying to import `package.subpackage.module`, which should involve importing `package.subpackage`?


Then you end up with a deadlock where T1 needs to resolve `package.subpackage.module` to resolve `package.subpackage`, while T2 needs to resolve `package.subpackage` to resolve `package.subpackage.module`, so we end up with a deadlock where they are holding mutually referential locks.

Here's the traceback on main:
```
Exception in thread Thread-1 (t1):
Traceback (most recent call last):
  File "/home/emma/cpython/Lib/threading.py", line 1074, in _bootstrap_inner
    self._context.run(self.run)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/emma/cpython/Lib/threading.py", line 1016, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emma/test_import_race/import_deadlock.py", line 5, in t1
    return __import__("package.subpackage", level=0)
  File "/home/emma/test_import_race/package/__init__.py", line 1, in <module>
    from package import subpackage
  File "/home/emma/test_import_race/package/subpackage/__init__.py", line 1, in <module>
    from package.subpackage.module import *
  File "<frozen importlib._bootstrap>", line 1368, in _find_and_load
  File "<frozen importlib._bootstrap>", line 421, in __enter__
  File "<frozen importlib._bootstrap>", line 346, in acquire
_frozen_importlib._DeadlockError: deadlock detected by _ModuleLock('package.subpackage.module') at 138200313720016
```

I'm not really sure what can be done to solve this other than some kind of earlier check when resolving `package.subpackage.module` if another thread is resolving a parent (in this case `package.subpackage`) and may need to resolve `package.subpackage.module`? Then block that thread until the other thread is done.

**Comment by gpshead** [comment]
The blunt force workaround for import madness of this form regardless of cause has always been: Do your imports from the main thread.  Not super friendly, and extra annoying when it's something nobody likes to think about such as unplanned indirect imports such as those from `codecs` dynamically loading infrequently used codec implementations, possibly due to untrusted data, in a serving stack.

Out of curiosity, I just had Claude Opus 4 take a stab at this as Emma's analysis sounded right.  Draft PR from that attached.  If that is sensible (I'll give it more of a look later), I think real performance tests are needed.  But hierarchical lock acquisition was also going to be my suggestion w/o having re-read importlib guts as well, so it maybe served as a bit of validation of both the issue & analysis and that thought.

---

Claude code prompts (/model is opus 4):

* load github issue 83065 and analyze the workings of Lib/importlib/ to understand the situation.  focus on emmatyping's issue comment, is that accurate given how the importlib code works?  what could be done to avoid this?
* Plan the import system improvements
* before benchmarking, look over the diff so far with the eye of a code reviewer and simplify it.  also remove the _use_hierarchical_import_locks logic, we'll always want this enabled. -- _(this helped the code quality a lot!)_
* run the reindent tool -- _(it knows how via [my CLAUDE.local.md](https://github.com/gpshead/cpython/blob/claude-code-config/CLAUDE.local.md))_
* commmit your work, credit Emma for the analysis in the commit message.
* be sure to put markdown backticks around `__init__.py`
* push to the gpshead remote and create a Draft PR, prefix the title of the PR with "GH-83065: "

half an hour of API use. this cost $$ money _(stated just to let others know the scale)_.

**Comment by gpshead** [comment]
thanks all for earlier reviews!  i found some remaining nits and fixed them, polished up, documented and merged.  if we uncover problems with this during 3.15 betas - reverting to the prior status quo can happen.  so many things in the world have worked around this long-standing flaw in odd manners.  it'll be nice to stop encountering those.

**Comment by bdraco** [comment]
Thanks for fixing this. I have personally made a donation to PSF in your honor.

**Comment by gpshead** [comment]
thanks! 😁

**Comment by steve-s** [comment]
FTR there seem to be also a rare race in stdlib with `collections`/`collections.abc` fixed by the linked PR, and causing `ModuleNotFoundError: No module named 'collections.abc'`
```
Thread A:
  import collections
    -> _find_and_load("collections")
    -> execute collections/__init__.py
    -> stop between these lines:
        ```
          # collections/__init__.py:29
          import _collections_abc
          import sys
          # INTERRUPTED HERE
          _sys.modules['collections.abc'] = _collections_abc
          abc = _collections_abc
        ```
        -> "collections" is already in sys.modules
        -> although spec._initializing is still True  


Thread B:
  import collections.abc
    -> _find_and_load("collections.abc")
    -> parent "collections" already exists in sys.modules
    -> do not wait for the parent package to finish (no check of _initializing on the spec)     
    -> search collections.__path__ for an abc submodule
    -> no collections/abc.py so no finder result
    -> ModuleNotFoundError at _bootstrap.py:1329 
```
[self-contained reproducer](https://github.com/steve-s/collection-abc-race-reproducer) fails for me locally on 3.13 and passes on 3.15 dev build
