### ISSUE TITLE
Show qualified function name when giving arguments error

### ISSUE THREAD

**Issue by 06547701-06a2-4e4a-b672-16a33475101e** [python/cpython#83393]
BPO | [39212](https://bugs.python.org/issue39212)
--- | :---
Nosy | @stevendaprano, @cool-RR

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-01-04.18:52:25.742>
labels = ['interpreter-core', 'type-feature', '3.9']
title = 'Show qualified function name when giving arguments error'
updated_at = <Date 2020-01-06.14:56:41.405>
user = 'https://github.com/cool-RR'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-06.14:56:41.405>
actor = 'cool-RR'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2020-01-04.18:52:25.742>
creator = 'cool-RR'
dependencies = []
files = []
hgrepos = []
issue_num = 39212
keywords = []
message_count = 5.0
messages = ['359302', '359310', '359385', '359413', '359430']
nosy_count = 2.0
nosy_names = ['steven.daprano', 'cool-RR']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39212'
versions = ['Python 3.9']
```

</p></details>

**Comment by cfbolz** [comment]
CPython is quite inconsistent now in whether the error string shows the module where a function is from. Example:

```python
>>> def f(): pass
... 
>>> f(**1)
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    f(**1)
    ~^^^^^
TypeError: __main__.f() argument after ** must be a mapping, not int
>>> f(1)
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    f(1)
    ~^^^
TypeError: f() takes 0 positional arguments but 1 was given
>>> f(a=1, **{1:2})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: keywords must be strings
```

to fix this, `initialize_locals` in `ceval.c` should use probably use `_PyObject_FunctionStr` too, like the `_PyDict_MergeEx` related functions do.
