### ISSUE TITLE
[doc]  creating large SharedMemory crashes on MacOs

### ISSUE THREAD

**Issue by bf8b85a2-9df0-412b-b6c3-5481df7521c8** [python/cpython#83765]
BPO | [39584](https://bugs.python.org/issue39584)
--- | :---
Nosy | @ronaldoussoren, @pitrou, @tiran, @ned-deily, @applio, @vinay0410
PRs | <li>python/cpython#21877</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-08.14:18:24.896>
labels = ['OS-mac', '3.8', '3.9', 'expert-C-API', 'type-crash', 'docs']
title = 'multiprocessing.shared_memory: MacOS crashes by running attached Python code'
updated_at = <Date 2020-11-17.10:55:29.496>
user = 'https://github.com/vinay0410'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-17.10:55:29.496>
actor = 'ronaldoussoren'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'macOS', 'C API']
creation = <Date 2020-02-08.14:18:24.896>
creator = 'vinay0410'
dependencies = []
files = []
hgrepos = []
issue_num = 39584
keywords = ['patch']
message_count = 9.0
messages = ['361629', '361924', '373806', '375229', '375245', '375249', '381221', '381222', '381223']
nosy_count = 7.0
nosy_names = ['ronaldoussoren', 'pitrou', 'christian.heimes', 'ned.deily', 'docs@python', 'davin', 'vinay0410']
pr_nums = ['21877']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue39584'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-138552

**Comment by dversoza** [comment]
@ronaldoussoren, do we have any updates with Apple on the filled issue **FB8903019**?

@tiran, I agree with you on [not hard-codding any arbitrary memory limit](https://github.com/python/cpython/issues/83765#issuecomment-1093856617), but considering that creating large SharedMemory will continue to crash on MacOS, I'd like to hear from you if documenting about the MacOS multiprocessing limit be enough to handle this issue?

**Comment by ronaldoussoren** [comment]
> @ronaldoussoren, do we have any updates with Apple on the filled issue **FB8903019**?

There are no updates on the issue with Apple.

**Comment by esatormi** [comment]
Couldn't reproduce the crash with Python3.12 and MacOS Sonoma (14.5).

Running the original code:

```py
>>> from multiprocessing.shared_memory import SharedMemory
>>> shm = SharedMemory(name='test-crash', create=True, size=1000000000000000000)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py", line 239, in main
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/shared_memory.py", line 115, in __init__
    self._mmap = mmap.mmap(self._fd, size)
    cache[rtype].remove(name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '/test-crash'
OSError: [Errno 12] Cannot allocate memory
```

Smaller amount works:

```py
shm = SharedMemory(name='test-crash', create=True, size=100000000000000)
```

Given C++ code works too.

@ronaldoussoren is there any updates about the issue?

**Comment by picnixz** [comment]
Friendly ping @ronaldoussoren (you can also close the issue if you think it's not worth the additional doc effort).

**Comment by gpshead** [comment]
I do not think this is worth documenting in any specific platform sense.  All hardware platforms have address space size limits, and the underlying OSes tend to further restrict the amount of that possible to claim as shared memory.  Often configurable to a much smaller limit on a system, process, or container basis.

This is just something people willing to delve into using shared memory need to know.  But the specifics aren't something Python docs are appropriate to contain, at most we could just mention "most platforms have specific sometimes configurable limits in the amount of shared memory address possible to allocate".
