### ISSUE TITLE
Segmentation fault on shutdown with shelve & c pickle

### ISSUE THREAD

**Issue by bfc977b6-9e56-4e34-911a-17627f598976** [python/cpython#83853]
BPO | [39672](https://bugs.python.org/issue39672)
--- | :---
Nosy | @dorosch
PRs | <li>python/cpython#18655</li>
Files | <li>[test_crash_shelve.zip](https://bugs.python.org/file48899/test_crash_shelve.zip "Uploaded as application/x-zip-compressed at 2020-02-18.09:51:02 by zd nex"): files for repro crash</li><li>[crash_pdb.txt](https://bugs.python.org/file48907/crash_pdb.txt "Uploaded as text/plain at 2020-02-24.10:07:42 by zd nex")</li><li>[crash.txt](https://bugs.python.org/file48912/crash.txt "Uploaded as text/plain at 2020-02-25.09:18:25 by zd nex")</li><li>[shelve.py.patch](https://bugs.python.org/file48913/shelve.py.patch "Uploaded as text/plain at 2020-02-25.09:53:48 by @dorosch")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-18.09:51:02.305>
labels = ['interpreter-core', '3.8', '3.9', 'ctypes', '3.7', 'library', 'type-crash']
title = 'Segmentation fault on shutdown with shelve & c pickle'
updated_at = <Date 2020-06-29.13:48:46.728>
user = 'https://bugs.python.org/zdnex'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-29.13:48:46.728>
actor = 'zd nex'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core', 'Library (Lib)', 'ctypes']
creation = <Date 2020-02-18.09:51:02.305>
creator = 'zd nex'
dependencies = []
files = ['48899', '48907', '48912', '48913']
hgrepos = []
issue_num = 39672
keywords = ['patch']
message_count = 15.0
messages = ['362186', '362257', '362573', '362576', '362577', '362580', '362581', '362582', '362628', '362629', '362797', '364649', '364838', '372574', '372575']
nosy_count = 2.0
nosy_names = ['dorosch', 'zd nex']
pr_nums = ['18655']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue39672'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by furkanonder** [comment]
Only version 3.8 has a segmentation fault. @dorosch @zdnex

```bash
$ python3.8 -X faulthandler ce_test_2.py                                                                                                                                                                                                                                  
start
end
Fatal Python error: Segmentation fault

Current thread 0x00007fa195bda740 (most recent call first):
  File "/usr/lib/python3.8/shelve.py", line 124 in __setitem__
  File "/usr/lib/python3.8/shelve.py", line 168 in sync
  File "/usr/lib/python3.8/shelve.py", line 144 in close
  File "/usr/lib/python3.8/shelve.py", line 162 in __del__
[1]    432422 segmentation fault (core dumped)  python3.8 -X faulthandler ce_test_2.py
```

```bash
$ python3.9 -X faulthandler ce_test_2.py                                                                                                                                                                                                                                  
start
end
Exception ignored in: <function Shelf.__del__ at 0x7f729c959790>
Traceback (most recent call last):
  File "/usr/lib/python3.9/shelve.py", line 162, in __del__
  File "/usr/lib/python3.9/shelve.py", line 144, in close
  File "/usr/lib/python3.9/shelve.py", line 168, in sync
  File "/usr/lib/python3.9/shelve.py", line 124, in __setitem__
ImportError: sys.meta_path is None, Python is likely shutting down
```

```bash
$ python3.10 -X faulthandler ce_test_2.py
start
end
Exception ignored in: <function Shelf.__del__ at 0x7f8932b37c70>
Traceback (most recent call last):
  File "/usr/lib/python3.10/shelve.py", line 162, in __del__
  File "/usr/lib/python3.10/shelve.py", line 144, in close
  File "/usr/lib/python3.10/shelve.py", line 168, in sync
  File "/usr/lib/python3.10/shelve.py", line 124, in __setitem__
ImportError: sys.meta_path is None, Python is likely shutting down
```

```bash
$ python3.11 -X faulthandler ce_test_2.py
start
end
Exception ignored in: <function Shelf.__del__ at 0x7fdfb7ed9580>
Traceback (most recent call last):
  File "/usr/lib/python3.11/shelve.py", line 162, in __del__
  File "/usr/lib/python3.11/shelve.py", line 144, in close
  File "/usr/lib/python3.11/shelve.py", line 168, in sync
  File "/usr/lib/python3.11/shelve.py", line 124, in __setitem__
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by serhiy-storchaka** [comment]
So this issue can be closed as outdated. 3.8 only accepts security fixes.
