### ISSUE TITLE
multiprocessing.Queue.put can fail silently due to pickle errors

### ISSUE THREAD

**Issue by a7d0779b-af78-4a87-8240-13d89e25d85c** [python/cpython#84376]
BPO | [40195](https://bugs.python.org/issue40195)
--- | :---
Files | <li>[minimal_repr.py](https://bugs.python.org/file49036/minimal_repr.py "Uploaded as text/plain at 2020-04-05.10:55:01 by Sander Land"): Minimal example for reproducing the behaviour</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-04-05.10:55:01.927>
labels = ['3.7', 'type-bug', 'library']
title = 'multiprocessing.Queue.put can fail silently due to pickle errors'
updated_at = <Date 2020-04-05.10:55:01.927>
user = 'https://bugs.python.org/SanderLand'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-05.10:55:01.927>
actor = 'Sander Land'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-04-05.10:55:01.927>
creator = 'Sander Land'
dependencies = []
files = ['49036']
hgrepos = []
issue_num = 40195
keywords = []
message_count = 1.0
messages = ['365816']
nosy_count = 1.0
nosy_names = ['Sander Land']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40195'
versions = ['Python 3.7']
```

</p></details>

**Comment by iantra** [comment]
Recently ran into this and it was quite annoying to debug, so just putting in my 2 cents and a vote to solve this :+1: 

From looking at the [tests](https://github.com/python/cpython/blob/main/Lib/test/_test_multiprocessing.py#L1265) it seems like not raising anything on failed serialization is the intended behavior, to make sure the queue still works afterwards. All exceptions in the feeder thread are simply printed as you can see [here](https://github.com/python/cpython/blob/main/Lib/multiprocessing/queues.py#L255) and [here](https://github.com/python/cpython/blob/main/Lib/multiprocessing/queues.py#L275)

I think keeping the background thread running makes sense, but an exception should probably be raised in the main thread so that people can actually deal with a pickling error in a nice way (errors should never pass silently and all that.) This is actually how it's done in a [Pipe](https://github.com/python/cpython/blob/main/Lib/multiprocessing/connection.py#L205), so it should be relatively simple to get right, but it would be a breaking change that might actually affect a few workflows. One way to make it backward compatible would be to add a flag (e.g. raise_pickling_errors) that you can turn on/off when making the Queue, although personally I think it should just be the default since people can ignore exceptions on their own, and it would then be more consistent with the behavior of pipes.

Also adding a minimal example here for clarity:

``` python
import multiprocessing
q = multiprocessing.Queue()
try:
    q.put(lambda: None)
    print("Success!")
except Exception:
    print("Failure")
```

And the (very confusing) output if you run this:
```
Success!
>>> Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7fbe76711090>: attribute lookup <lambda> on __main__ failed
```

I'd be happy to open a PR if others consider it a worthwhile change.

**Comment by serhiy-storchaka** [comment]
See also #55095. It was closed as superseded by #61227, but the latter did not change anything with this issue.

**Comment by ekneg54** [comment]
I fall into that and yes it would be nice to raise somehow in the main thread or to add a note in the documentation about this behavior: https://docs.python.org/3.11/library/multiprocessing.html#multiprocessing.Queue.put

**Comment by andrewkho** [comment]
+1 on surfacing to the main thread, we're seeing this issue for multi-process dataloading in pytorch

**Comment by belforte** [comment]
very annoying to debug, yes.  At least one line in the doc. is desperately needed.

**Comment by picnixz** [comment]
There is a note in the docs (emphasis mine)

> When an object is put on a queue, **the object is pickled** and a background thread later flushes the pickled data to an underlying pipe. This has some consequences which are a little surprising, but should not cause any practical difficulties – if they really bother you then you can instead use a queue created with a [manager](https://docs.python.org/3.11/library/multiprocessing.html#multiprocessing-managers).

but this note could be improved as, while it's being pickled, execution somewhat continues if pickling fails:

```py
>>> import multiprocessing
>>> q = multiprocessing.Queue()
>>> try:
...     q.put(lambda: None)
...     print("Success!")
... except Exception:
...     print("Failure")
...
Success!
>>> print(12345)
12345
>>> AttributeError: module '__main__' has no attribute '<lambda>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/$HOME/lib/python/cpython/Lib/multiprocessing/queues.py", line 262, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/$HOME/lib/python/cpython/Lib/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7ff4e04ed010>: it's not found as __main__.<lambda>

>>>

Oh and by the way, with the new REPL I also got some scrambled output:

```py
>>> import multiprocessing
... q = multiprocessing.Queue()
... try:
...     q.put(lambda: None)
...     print("Success!")
... except Exception:
...     print("Failure")
... print(1)
...
Success!
1
>>> AttributeError: module '__main__' has no attribute '<lambda>'

                                                                 During handling of the above exception, another exception occurred:

                                                                                                                                    Traceback (most recent call last):
                   File "/$HOME/lib/python/cpython/Lib/multiprocessing/queues.py", line 262, in _feed
                                                                                                               obj = _ForkingPickler.dumps(obj)
                                                                                                                                                 File "/$HOME/lib/python/cpython/Lib/multiprocessing/reduction.py", line 51, in dumps
                                                                                          cls(buf, protocol).dump(obj)
                                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
 _pickle.PicklingError: Can't pickle <function <lambda> at 0x7f06ae4ae770>: it's not found as __main__.<lambda>
                                                                                                           >>>
```

**Comment by belforte** [comment]
thank you @picnixz . I was looking at 3.12 doc

**Comment by YvesDup** [comment]
This traceback is called from a static method passed when the  `_feed` thread is created.  See:
https://github.com/python/cpython/blob/e642a24b50fa1ac2fa709cda233d1dc5c90333fe/Lib/multiprocessing/queues.py#L292-L299

But you can define your own static `_on_queue_feeder_error` method inheriting your own class from the `multiprocessing.queues.Queue`. See the example below : 
https://github.com/python/cpython/blob/e642a24b50fa1ac2fa709cda233d1dc5c90333fe/Lib/test/_test_multiprocessing.py#L1431-L1437

It might be a good idea to add the `queue` attribute as a new argument to the `_on_queue_feeder_error` method to allow the programmer to implement their own error handling.

**Comment by YvesDup** [comment]
I suggest to close this issue
