### ISSUE TITLE
add support for os.PathLike filename in zipfile.ZipFile.write()

### ISSUE THREAD

**Issue by 2e43ab83-bade-46f4-acc7-c599eba17e11** [python/cpython#84686]
BPO | [40506](https://bugs.python.org/issue40506)
--- | :---
Nosy | @Yhg1s, @ethanfurman, @serhiy-storchaka, @domragusa
Files | <li>[pathlike_writestr.patch](https://bugs.python.org/file49132/pathlike_writestr.patch "Uploaded as text/plain at 2020-05-06.18:31:13 by @domragusa")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-05.02:12:03.387>
labels = ['type-feature', 'library', '3.10']
title = 'add support for os.Pathlike filenames in zipfile.ZipFile.writestr'
updated_at = <Date 2021-09-08.00:49:22.380>
user = 'https://github.com/domragusa'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-08.00:49:22.380>
actor = 'ethan.furman'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-05-05.02:12:03.387>
creator = 'd.ragusa'
dependencies = []
files = ['49132']
hgrepos = []
issue_num = 40506
keywords = ['patch']
message_count = 2.0
messages = ['368098', '368289']
nosy_count = 4.0
nosy_names = ['twouters', 'ethan.furman', 'serhiy.storchaka', 'd.ragusa']
pr_nums = ['20002']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40506'
versions = ['Python 3.10']
```

</p></details>

### Linked PRs
* gh-20002
* gh-113386

**Comment by TBSenseo** [comment]
I have encountered the same issue with a different zipfile function: The zipfile.ZipFile.getinfo function throws a KeyError when using a pathlib.Path object containing the valid path to an existing zip-file member. I am actually using the zipfile.ZipFile.extract function in my case. This function calls the getinfo function, that in turn throws a key error:

```python
traceback.print_exc()
Traceback (most recent call last):
  File "<my script file>", line 501, in extractTestFilesZipFolderItem
    return Path(zf.extract(zipFileItemPath, path = destinationFolderPath))
  File "C:\Progs\Python\Python310\lib\zipfile.py", line 1630, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Progs\Python\Python310\lib\zipfile.py", line 1669, in _extract_member
    member = self.getinfo(member)
  File "C:\Progs\Python\Python310\lib\zipfile.py", line 1443, in getinfo
    raise KeyError(
KeyError: "There is no item named WindowsPath('<Zip file member path>') in the archive"
``` 

The code of the function is:
```python
from typing import Union
import os
from pathlib import Path
import zipfile
import bdb
from breakOnException import setBreakOnException, getBreakOnException

def extractTestFilesZipFolderItem(zipFilePath : Union[str, os.PathLike], zipFileItemPath : Union[str, os.PathLike], destinationFolderPath : Union[None, str, os.PathLike] = None) -> Path:
	# Parameter zipFilePath
	if not (isinstance(zipFilePath, str) or isinstance(zipFilePath, os.PathLike)):
		raise TypeError('Parameter zipFilePath must be a string or another path-like instance')
	# Parameter zipFileItemPath
	if not (isinstance(zipFileItemPath, str) or isinstance(zipFileItemPath, os.PathLike)):
		raise TypeError('Parameter zipFileItemPath must be a string or another path-like instance')
	# Parameter destinationFolderPath
	if not (destinationFolderPath is None or isinstance(destinationFolderPath, str) or isinstance(destinationFolderPath, os.PathLike)):
		raise TypeError('Parameter destinationFolderPath must be None, a string or another path-like instance')
	# Normal code
	try:
		with zipfile.ZipFile(zipFilePath) as zf:
			return Path(zf.extract(zipFileItemPath, path = destinationFolderPath))
	except Exception as ex:
		if type(ex) not in [KeyboardInterrupt, bdb.BdbQuit] and getBreakOnException():
			breakpoint()
		raise
```
The getBreakOnException function is just a function from a self-made library breakOnException that globally tracks whether I want a breakpoint to be triggered when an exception occurs to be able to investigate the values of the variables that may have caused the exception.

When I put 'str(' and ')' around zipFileItemPath like `zf.extract(str(zipFileItemPath), path = destinationFolderPath)`, then it works as intended.

In my opinion, the zipfile functions expecting paths (including file names) should be able to accept any string and path-like object.
I am using:
* Spyder version: 5.4.3  (pip)
* Python version: 3.10.11 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows 10

**Comment by serhiy-storchaka** [comment]
It was discussed previously (maybe several times), and I opposed it. Path objects should only be supported for external paths (see #72418). Internal ZIP file paths do not represent real files, they are simply string keys. Using a Path object to access an entry in the ZIP file is a programming error, and we should not make easier to do such errors.

**Comment by gpshead** [comment]
Thanks, in general I think I agree. Though the `zipfile` module has APIs that conflate the two concepts, `writestr` is not one of those.

`ZipFile.write` and `ZipInfo.from_file` are both APIs that take a local filesystem path in order to read & store it in the zip file.  Those specific two being made to properly handle PathLike for their `filename` parameters make sense.

Otherwise as far as supporting it in all situations, what I'm finding as I explore in my draft PR is that it gets a bit messy  to support them in "lookup/update" scenarios. I had to use more conditional `_sanitize_filename` calls in too many places to be comfortable - and I still have pathname bugs when a `*WindowsPath` is involved (see the CI) - and even then callers need to ensure they're using relative paths for lookups.

The original simple PR (#20002) put up by @domragusa even used `pathlib.PurePosixPath` within its test as a way to avoid the need for that, but exposes a bit of the smell: `zip` files are not posix.  that they happened to settle on forward slashes internally for paths is an implementation detail but asking users to use PurePosixPath if the want pathlib keys for lookups seem awkward.

**Comment by TBSenseo** [comment]
@gpshead, you are essentially saying that the zip file paths follow a different semantic than Windows and POSIX paths. I would say that a perfect solution would be to have a ZipFilePath class based on the standard Python PurePath class or so for handling zip file paths in a convenient way. Probably, it needs to include the ability to convert to and from the other existing paths types including raising exceptions when the conversion cannot be done. Then, this class can be used with the ZipFile and ZipInfo module functions.
