### ISSUE TITLE
zoneinfo: ZoneInfo raises IsADirectoryError instead of ZoneInfoNotFoundError

### ISSUE THREAD

**Issue by fc57fb39-0a7a-4ca9-8996-e973ba0d61a9** [python/cpython#85702]
BPO | [41530](https://bugs.python.org/issue41530)
--- | :---
Nosy | @vstinner, @pganssle, @bijij
PRs | <li>python/cpython#21839</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-08-12.11:42:16.788>
labels = ['type-bug', 'library', '3.9', '3.10']
title = 'zoneinfo: ZoneInfo raises IsADirectoryError instead of ZoneInfoNotFoundError'
updated_at = <Date 2020-08-12.14:46:45.318>
user = 'https://github.com/bijij'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-12.14:46:45.318>
actor = 'josh.ja.butt'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-08-12.11:42:16.788>
creator = 'josh.ja.butt'
dependencies = []
files = []
hgrepos = []
issue_num = 41530
keywords = ['patch']
message_count = 10.0
messages = ['375225', '375226', '375228', '375233', '375234', '375235', '375238', '375239', '375240', '375251']
nosy_count = 4.0
nosy_names = ['vstinner', 'python-dev', 'p-ganssle', 'josh.ja.butt']
pr_nums = ['21839']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41530'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-131333
* gh-136117
* gh-136128
* gh-136130
* gh-136136

**Comment by fabien-michel** [comment]
This is still a issue with python3.13:

```
>>> from zoneinfo._common import load_tzdata
>>> load_tzdata("Europe")
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    load_tzdata("Europe")
    ~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib/python3.13/zoneinfo/_common.py", line 12, in load_tzdata
    return resources.files(package_name).joinpath(resource_name).open("rb")
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/pathlib/_local.py", line 537, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/path/to/python3.13/site-packages/tzdata/zoneinfo/Europe'
```

**Comment by StanFromIreland** [comment]
`IsADirectoryError` has been fixed, now just the windows specific case of `PermissionError` remains. We should not catch it outright, but maybe we could check if the error is for a file in tzdata, and then raise `ZoneInfoNotFoundError`?

**Comment by vstinner** [comment]
> IsADirectoryError has been fixed, now just the windows specific case of PermissionError remains. We should not catch it outright, but maybe we could check if the error is for a file in tzdata, and then raise ZoneInfoNotFoundError?

I created https://github.com/python/cpython/pull/136117 for the PermissionError on Windows.

**Comment by StanFromIreland** [comment]
Windows pr and backports have been merged. I do not know of anything else to do here, if other os-specific cases pop up in the future we can always reopen.
