### ISSUE TITLE
Make threading._register_atexit public?

### ISSUE THREAD

**Issue by 5c0d0cd9-bbdc-4a00-8830-a38a1efc5f8a** [python/cpython#86128]
BPO | [41962](https://bugs.python.org/issue41962)
--- | :---
Nosy | @pitrou, @vstinner, @bdarnell, @ericsnowcurrently, @aeros

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-10-07.01:09:44.475>
labels = ['library', '3.9']
title = 'Make threading._register_atexit public?'
updated_at = <Date 2022-02-04.19:07:30.806>
user = 'https://github.com/bdarnell'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-04.19:07:30.806>
actor = 'Ben.Darnell'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-10-07.01:09:44.475>
creator = 'Ben.Darnell'
dependencies = []
files = []
hgrepos = []
issue_num = 41962
keywords = []
message_count = 10.0
messages = ['378144', '385589', '385598', '385688', '412438', '412470', '412471', '412472', '412475', '412526']
nosy_count = 6.0
nosy_names = ['pitrou', 'vstinner', 'sa', 'Ben.Darnell', 'eric.snow', 'aeros']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue41962'
versions = ['Python 3.9']
```

</p></details>

**Comment by lucaswiman** [comment]
Another issue (also related to long-running threads, though I don't think that's essential) is that there is no way to use an `atexit` function to tell your threads to exit cleanly. I reduced the issue to this:
```python
import atexit
import concurrent.futures
import time


stop_signal = False

def waiter():
    while not stop_signal:
        time.sleep(1)
        print('.', end="")
        import sys; sys.stdout.flush()


def stop_workers():
    global stop_signal
    print("called!")
    stop_signal = True


atexit.register(stop_workers)


if __name__ == "__main__":
    executor = concurrent.futures.ThreadPoolExecutor(max_workers=1)
    executor.submit(waiter)
    assert False
```

When you run this, it will block and continue executing the `waiter` thread. When I hit control+C it generates this error:
```pytb
..^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
called!
```

So there's effectively a deadlock between the `ThreadPoolExecutor`'s atexit handler, which runs _before_ any methods registered by `atexit.register`. This seems very counter intuitive since the documentation in atexit says the atexit handlers are processed in a LIFO fashion. 

I feel like an inability to tell threads to gracefully exit when the main thread ends is a pretty significant limitation of `ThreadPoolExecutor` and should be mentioned in the docs, even if it's not clear what the right fix for it is. Would the maintainers be supportive if I added a documentation PR to that effect?

**Comment by SyntaxColoring** [comment]
We should be careful about describing this with emphasis on `ThreadPoolExecutor`, because it affects *any* non-daemon thread. [Here's a demo.](https://gist.github.com/SyntaxColoring/c4b3059cb44b1f629db311f8b3ff3977)

**Comment by lucaswiman** [comment]
> How much of this is actually specific to ThreadPoolExecutor, as opposed to non-daemon threads in general? 

@SyntaxColoring Prior to 3.9, `ThreadPoolExecutor` did use daemon threads, with unusual behavior for daemon threads. (Updated in [this commit](https://github.com/python/cpython/commit/b61b818d916942aad1f8f3e33181801c4a1ed14b)).

I think your example is expected behavior for non-daemon threads, though the threading/atexit docs could probably be clarified a bit on this point.
