### ISSUE TITLE
Usage of HTTPResponse.url

### ISSUE THREAD

**Issue by 3719dc32-bb91-44fc-84ac-aef837752e97** [python/cpython#86228]
BPO | [42062](https://bugs.python.org/issue42062)
--- | :---
Nosy | @vadmium, @fbidu
PRs | <li>python/cpython#22738</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-10-17.14:13:56.336>
labels = ['library']
title = 'Usage of HTTPResponse.url'
updated_at = <Date 2020-10-18.01:59:43.626>
user = 'https://github.com/fbidu'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-18.01:59:43.626>
actor = 'martin.panter'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-10-17.14:13:56.336>
creator = 'fbidu'
dependencies = []
files = []
hgrepos = []
issue_num = 42062
keywords = ['patch']
message_count = 2.0
messages = ['378814', '378846']
nosy_count = 2.0
nosy_names = ['martin.panter', 'fbidu']
pr_nums = ['22738']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue42062'
versions = []
```

</p></details>

**Comment by dimo414** [comment]
This seems to still be broken in 3.12:

```
$ docker run --rm python:3.12 python -c \
  'import http.client as httplib; conn = httplib.HTTPConnection("google.com"); conn.request("GET", "/"); print(conn.getresponse().geturl())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.12/http/client.py", line 790, in geturl
    return self.url
           ^^^^^^^^
AttributeError: 'HTTPResponse' object has no attribute 'url'
```
[
`HTTPResponse.url`](https://docs.python.org/3.12/library/http.client.html#http.client.HTTPResponse.url) doesn't exist, and [`HTTPResponse.geturl()`](https://docs.python.org/3.12/library/http.client.html#http.client.HTTPResponse.geturl) is broken. I tried 3.12, 3.11, 3.10, 3.9, and 3.8 (prior to #11447), it doesn't look like this has _ever_ worked.

FYI @merwok and @matrixise who approved #11447.

**Comment by merwok** [comment]
Tangent: I now wish the original PR had also updated the docstrings on the deprecated methods (it only added a code comment).

**Comment by vadmium** [comment]
Another problem with this documentation is it suggests _HTTPResponse.headers_ is an EmailMessage instance, while _HTTPResponse.msg_ remains only a (subclassed) instance of _email.message.Message_. And _addinfourl.info_ and _addinfourl.headers_ are now supposed to return an EmailMessage, although _.info_ was previously (indirectly) documented to return an _email.message.Message_.

I tested Python 3.10.2 and it seems _HTTPResponse.headers_ has not changed because the object didn’t have one of the methods unique to EmailMessage:

```pycon
>>> u = urlopen('http://google.com')
>>> u.headers.is_attachment
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'HTTPMessage' object has no attribute 'is_attachment'
```
