### ISSUE TITLE
global declarations affect too much inside exec or compile

### ISSUE THREAD

**Issue by e077a8c4-d531-4757-90e2-f4d365041ba6** [python/cpython#86356]
BPO | [42190](https://bugs.python.org/issue42190)
--- | :---
Nosy | @gvanrossum, @terryjreedy, @lysnikolaou, @pablogsal

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-10-29.05:07:31.334>
labels = ['interpreter-core', 'type-bug', '3.8', '3.9', '3.10']
title = 'global declarations affect too much inside exec or compile'
updated_at = <Date 2020-10-31.01:01:46.824>
user = 'https://bugs.python.org/KevinShweh'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-31.01:01:46.824>
actor = 'pablogsal'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2020-10-29.05:07:31.334>
creator = 'Kevin Shweh'
dependencies = []
files = []
hgrepos = []
issue_num = 42190
keywords = []
message_count = 4.0
messages = ['379855', '380024', '380028', '380029']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'terry.reedy', 'Kevin Shweh', 'lys.nikolaou', 'pablogsal']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42190'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by ncoghlan** [comment]
For the record, I also double-checked that this quirk doesn't happen for nested classes:

```
>>> def f():
...     class C:
...         x = 1
...         def m():
...             global x
...             return x
...     return C
...
>>> C = f()
>>> C.x
1
>>> C.m()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in m
NameError: name 'x' is not defined
>>> x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'x' is not defined
```
