### ISSUE TITLE
Incorrect behavior of inspect.signature(f).bind

### ISSUE THREAD

**Issue by 23923e01-7789-4d6b-ae0a-dfdd85d18a61** [python/cpython#87106]
BPO | [42940](https://bugs.python.org/issue42940)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-01-16.16:30:52.922>
labels = ['type-bug', '3.8', '3.9']
title = 'Incorrect behavior of inspect.signature(f).bind'
updated_at = <Date 2021-01-16.16:30:52.922>
user = 'https://bugs.python.org/slavkostrov'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-16.16:30:52.922>
actor = 'slavkostrov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-01-16.16:30:52.922>
creator = 'slavkostrov'
dependencies = []
files = []
hgrepos = []
issue_num = 42940
keywords = []
message_count = 1.0
messages = ['385143']
nosy_count = 1.0
nosy_names = ['slavkostrov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42940'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-103404
* gh-118984
* gh-118985

**Comment by jacobtylerwalls** [comment]
In another case, inspect.signature(foo).bind gives a TypeError when no TypeError is even raised in the actual call:

```python
>>> def foo(a=0, /, b=1, **kwargs): pass
...
>>> foo(a=1)
>>> inspect.signature(foo).bind(a=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/inspect.py", line 2933, in _bind
    raise TypeError(msg) from None
TypeError: 'a' parameter is positional only, but was passed as a keyword
```
