### ISSUE TITLE
locale.getlocale fails if locale is set

### ISSUE THREAD

**Issue by 4ab1b499-c4d2-4986-b08a-7a379be00275** [python/cpython#87281]
BPO | [43115](https://bugs.python.org/issue43115)
--- | :---
Nosy | @malemburg, @pfmoore, @tjguk, @zware, @eryksun, @zooba, @AndersMunch

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-03.13:42:50.296>
labels = ['3.8', '3.10', 'library', '3.9', 'OS-windows']
title = 'locale.getlocale fails if locale is set'
updated_at = <Date 2021-02-23.17:59:57.570>
user = 'https://github.com/AndersMunch'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-23.17:59:57.570>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2021-02-03.13:42:50.296>
creator = 'AndersMunch'
dependencies = []
files = []
hgrepos = []
issue_num = 43115
keywords = []
message_count = 15.0
messages = ['386203', '387136', '387138', '387147', '387149', '387157', '387164', '387195', '387205', '387208', '387209', '387256', '387273', '387558', '387588']
nosy_count = 8.0
nosy_names = ['lemburg', 'paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'swt2c', 'AndersMunch']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue43115'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-137253
* gh-137313
* gh-137722
* gh-137723

**Comment by vstinner** [comment]
I don't get the purpose of the getlocale() function. For me, it's a can of worms.

If you need to get the locale encoding, there is a function just for that: ``locale.getencoding()``. On Python 3.10 and older, ``locale.getpreferredencoding(False)`` can be used instead.

If you want to save/restore the locale, use:

```
# Replace LC_ALL with another category if you prefer
old_loc = locale.setlocale(locale.LC_ALL, None)
# ... code changing the locale ...
locale.setlocale(locale.LC_ALL, old_loc)
```

These functions work on all platforms with any locale. Python doesn't need to parse the locale name string. Just pass it back to setlocale().

I would prefer to get rid of all code in the locale module which parses the locale name: getdefaultlocale(), getlocale() and normalize(). See https://github.com/python/cpython/issues/87723

**Comment by malemburg** [comment]
On 25.05.2022 02:55, Victor Stinner wrote:
> I would prefer to get rid of all code in the locale module which parses the
> locale name: getdefaultlocale(), getlocale() and normalize(). See #87723
> <https://github.com/python/cpython/issues/87723>

The reason for having the parsing and normalization engine
is that there are too many ways to write locale strings.

At the same time the setlocale() function (at least on Linux)
is very picky about which variant to use. Normalizing makes
this more robust.

-- 
Marc-Andre Lemburg
http://www.malemburg.com/

**Comment by vstinner** [comment]
My main usage of setlocale() is to set a temporary locale and save/restore the locale in between. For this use case, I don't see the purpose of getlocale(), especially if it can fail.

```
import locale

loc = locale.LC_TIME
old = locale.setlocale(loc, None)   # *get* the locale
try:
    locale.setlocale(loc, "C")
    # ... code running with LC_TIME set to "C"
finally:
    locale.setlocale(loc, old)
```

**Comment by serhiy-storchaka** [comment]
Other examples were mentioned in https://github.com/python/cpython/issues/123853#issuecomment-2340425516.

* "sr-Latn-RS" on Windows and "sr_RS@latin" on Linux
* "ca-ES-valencia" on Windows and "ca_ES@valencia" on Linux

You can set "sr-Latn-RS" and "ca-ES-valencia",  but the following `locale.getlocale()` fails. Linux-compatible spelling "sr_RS@latin" and "ca_ES@valencia" is not supported.
```pycon
>>> locale.setlocale(locale.LC_ALL, 'ca-ES-valencia')
'ca-ES-valencia'
>>> locale.getlocale(locale.LC_ALL)
Traceback (most recent call last):
  File "<python-input-45>", line 1, in <module>
    locale.getlocale(locale.LC_ALL)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\py\cpython\Lib\locale.py", line 603, in getlocale
    return _parse_localename(localename)
  File "D:\py\cpython\Lib\locale.py", line 501, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: ca-ES-valencia
>>> locale.setlocale(locale.LC_ALL, 'ca_ES@valencia')
Traceback (most recent call last):
  File "<python-input-46>", line 1, in <module>
    locale.setlocale(locale.LC_ALL, 'ca_ES@valencia')
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\py\cpython\Lib\locale.py", line 620, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

Note also that modifiers are lost in `locale.getlocale()` on Linux:
```pycon
>>> locale.setlocale(locale.LC_ALL, "ca_ES@valencia")
'ca_ES@valencia'
>>> locale.getlocale(locale.LC_ALL)
('ca_ES', 'UTF-8')
>>> locale.setlocale(locale.LC_ALL, "sr_RS@latin")
'sr_RS@latin'
>>> locale.getlocale(locale.LC_ALL)
('sr_RS', 'UTF-8')
```
So the roundtrip does not work.

**Comment by malemburg** [comment]
`_parse_localename()` does not support modifiers in general, so no surprise there. It only has support for the *@euro* modifier, since that was in actual use at the time I wrote this in order to support the Euro symbol (via iso-8859-15).

We'd need to add support if we want to support that use case.

**Comment by malemburg** [comment]
> I don't see the purpose of getlocale(), especially if it can fail.

Your example code was the reason I added the local aliasing engine. I wanted to do the same, but found that `setlocale()` often did not accept the return value of `setlocale(..., None)` or `getdefaultlocale()` at the time (*).  Today's glibc appears to have gotten a lot more friendly in that respect and no longer immediately falls over if you write "de_DE.utf8" instead of "de_DE.UTF-8".

Still, `setlocale(..., None)` doesn't always provide (default) encoding settings, which `getlocale()` attempts to add.

Perhaps we should have `getlocale()` do what it says on the tin and indeed make it return `None` in case it e.g. cannot determine the encoding due to missing information in the `locale_alias` table, instead of simply raising an error.

(*) And to add more history: the main reason for adding `getdefaultlocale()` in Pyhon 2 was to avoid having to run `setlocale(LC_ALL, "")` to first configure the lib C locale system (this can have unwanted side effects when embedding Python in other applications). The call was added in Python 3, which made trying to figure out the default encoding by other means (as is attempted by `getdefaultlocale()`) less of an issue, at the cost of making embedding a bit harder.

**Comment by serhiy-storchaka** [comment]
And the `@euro` support is broken as well. For example, "fr_FR.iso885915@euro" is normalized to "fr_FR.ISO8859-15", because of the X11's `locale.alias` mapping, but only the first one is supported in glibc. Most of `@euro` mappings in `locale.alias` are incorrect.

**Comment by malemburg** [comment]
> And the `@euro` support is broken as well. For example, "fr_FR.iso885915@euro" is normalized to "fr_FR.ISO8859-15", because of the X11's `locale.alias` mapping, but only the first one is supported in glibc. Most of `@euro` mappings in `locale.alias` are incorrect.

The @euro modifier was meant to mean "add support for the Euro sign" to encodings which did not have it, e.g. ISO-8859-1. [ISO-8859-15](https://en.wikipedia.org/wiki/ISO/IEC_8859-15) is ISO-8859-1 plus the Euro sign (and a few other new mappings), so the modified does not have any meaning and can be removed.

**Comment by serhiy-storchaka** [comment]
No, it cannot be removed. On Linux, there is locale fr_FR.iso885915@euro, but no fr_FR.iso885915.

el_GR@euro is mapped to el_GR.ISO8859-15 in locale.alias, but it uses ISO8859-7.

There are no `@euro` locales on FreeBSD, NetBSD, OpenBSD and Openindiana. It seems that Linux is the only common platform with `@euro` locales.

`@euro` specifies not only default encoding. For some locales it affects also collation.

I think that the way aliases mapping is used in the locale module is incorrect. It replaces correct locale names with locale names unsupported on the current platform or names which refer to different locales. If we want to support other locale names across platforms, `setlocale()` should try to set different locales until it success -- first the specified name, then different variants of names created using the aliases mapping as a fallback. `normalize()` then should not add encodings or remove modifiers, but just convert the name to some standardized form. For example, "french" should not be mapped to "fr_FR.ISO8859-1", but to "fr", and `setlocale()` then should try "fr", "fr_FR", "fr_FR.ISO8859-1", "fr_FR.UTF-8", "french", etc. `getlocale()` should just extract the encoding name from the locale name. If there are no encoding name, it can try to get it in other way (for example by using `nl_langinfo_l(CODESET)`), otherwise return None. This is a large change, and I'll try first less invasive methods which can be backported.

**Comment by malemburg** [comment]
> No, it cannot be removed. On Linux, there is locale fr_FR.iso885915@euro, but no fr_FR.iso885915.

Interesting. Glibc appears to have a different understanding of this than X.org, which we use as basis for the aliasing table.
They probably use the modifier for some additional non-codepage related locale settings.
 
> el_GR@euro is mapped to el_GR.ISO8859-15 in locale.alias, but it uses ISO8859-7.

ISO8859-7 is special, since it received the Euro sign in 2003 (according to Wikipedia). I guess the mapping was left around for historical reasons.
 
> There are no `@euro` locales on FreeBSD, NetBSD, OpenBSD and Openindiana. It seems that Linux is the only common platform with `@euro` locales.
> 
> `@euro` specifies not only default encoding. For some locales it affects also collation.

Not really surprising, since those modifiers are not standardized. The can mean many things and are often used to be able to differentiate between slightly different locale settings used in a country.
 
> I think that the way aliases mapping is used in the locale module is incorrect. It replaces correct locale names with locale names unsupported on the current platform or names which refer to different locales. If we want to support other locale names across platforms, `setlocale()` should try to set different locales until it success -- first the specified name, then different variants of names created using the aliases mapping as a fallback. `normalize()` then should not add encodings or remove modifiers, but just convert the name to some standardized form. For example, "french" should not be mapped to "fr_FR.ISO8859-1", but to "fr", and `setlocale()` then should try "fr", "fr_FR", "fr_FR.ISO8859-1", "fr_FR.UTF-8", "french", etc. `getlocale()` should just extract the encoding name from the locale name. If there are no encoding name, it can try to get it in other way (for example by using `nl_langinfo_l(CODESET)`), otherwise return None. This is a large change, and I'll try first less invasive methods which can be backported.

That would mean a larger change and require a PEP, especially for the `setlocale()` part.

I think for this particular ticket we should focus on having getlocale() succeed, even if no locale information for the encoding is available and it currently raises an exception.

Like you say, we could try to get the encoding information from `nl_langinfo_l(CODESET)` if no alias is found.

**Comment by StanFromIreland** [comment]
Triage: Is there anything left to do here? All backports are complete.

**Comment by serhiy-storchaka** [comment]
Yes, this is a large and complex issue. It needs a lot of work.
