### ISSUE TITLE
code.InteractiveConsole can crash if sys.excepthook is broken

### ISSUE THREAD

**Issue by 9719010a-7a6d-45ea-a4c0-9c1ede24d0ea** [python/cpython#87320]
BPO | [43154](https://bugs.python.org/issue43154)
--- | :---
Nosy | @terryjreedy, @vstinner, @cfbolz, @Julian
Files | <li>[crash.log](https://bugs.python.org/file49797/crash.log "Uploaded as text/x-log at 2021-02-07.16:26:30 by @cfbolz")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-07.16:26:30.537>
labels = ['type-bug', '3.10']
title = 'code.InteractiveConsole can crash if sys.excepthook is broken'
updated_at = <Date 2021-04-02.22:33:56.780>
user = 'https://github.com/cfbolz'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-02.22:33:56.780>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-02-07.16:26:30.537>
creator = 'Carl.Friedrich.Bolz'
dependencies = []
files = ['49797']
hgrepos = []
issue_num = 43154
keywords = []
message_count = 3.0
messages = ['386593', '386892', '390108']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'vstinner', 'Carl.Friedrich.Bolz', 'Julian']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43154'
versions = ['Python 3.10']
```

</p></details>

### Linked PRs
* gh-122456
* gh-122514
* gh-122515

**Comment by cfbolz** [comment]
This issue is a little bit more pressing now with pyrepl, because that is based on the `code` module. Here's Python 3.12:

```python
Python 3.12.0 (main, Apr 28 2024, 22:42:26) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.excepthook = object(); asdf
Error in sys.excepthook:
TypeError: 'object' object is not callable

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'asdf' is not defined
```

And Python 3.13 (I tried on current 3.13 branch, 10cf7d6d00ad90867634114a894eb7e9f35df867):

```python
>>> import sys; sys.excepthook = object(); asdf
Error in sys.excepthook:
TypeError: 'object' object is not callable

Original exception was:
Traceback (most recent call last):
  File "/home/cfbolz/projects/cpython/Lib/code.py", line 91, in runcode
    exec(code, self.locals)
    ~~~~^^^^^^^^^^^^^^^^^^^
  File "<python-input-0>", line 1, in <module>
    import sys; sys.excepthook = object(); asdf
                                           ^^^^
NameError: name 'asdf' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/cfbolz/projects/cpython/Lib/_pyrepl/__main__.py", line 6, in <module>
    __pyrepl_interactive_console()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/cfbolz/projects/cpython/Lib/_pyrepl/main.py", line 59, in interactive_console
    run_multiline_interactive_console(console)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/cfbolz/projects/cpython/Lib/_pyrepl/simple_interact.py", line 156, in run_multiline_interactive_console
    more = console.push(_strip_final_indent(statement), filename=input_name, _symbol="single")  # type: ignore[call-arg]
  File "/home/cfbolz/projects/cpython/Lib/code.py", line 303, in push
    more = self.runsource(source, filename, symbol=_symbol)
  File "/home/cfbolz/projects/cpython/Lib/_pyrepl/console.py", line 200, in runsource
    self.runcode(code)
    ~~~~~~~~~~~~^^^^^^
  File "/home/cfbolz/projects/cpython/Lib/code.py", line 95, in runcode
    self.showtraceback()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/cfbolz/projects/cpython/Lib/_pyrepl/console.py", line 168, in showtraceback
    super().showtraceback(colorize=self.can_colorize)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cfbolz/projects/cpython/Lib/code.py", line 153, in showtraceback
    sys.excepthook(ei[0], ei[1], last_tb)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'object' object is not callable

```
