### ISSUE TITLE
contextvars does not work properly in asyncio REPL.

### ISSUE THREAD

**Issue by 0651bd0c-a40e-4f1c-99b0-77359d007ea7** [python/cpython#87585]
BPO | [43419](https://bugs.python.org/issue43419)
--- | :---
Nosy | @asvetlov, @1st1, @lanfon72
PRs | <li>python/cpython#24773</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-06.14:09:53.246>
labels = ['type-bug', '3.8', '3.9', 'expert-asyncio']
title = 'contextvars does not work properly in asyncio REPL.'
updated_at = <Date 2021-03-06.15:06:01.651>
user = 'https://github.com/lanfon72'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-06.15:06:01.651>
actor = 'lanfon72'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-03-06.14:09:53.246>
creator = 'lanfon72'
dependencies = []
files = []
hgrepos = []
issue_num = 43419
keywords = ['patch']
message_count = 1.0
messages = ['388199']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'lanfon72']
pr_nums = ['24773']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43419'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment]
3.9 is no longer maintained and I can't reproduce this on 3.10 and 3.11:

% python3.10 -m asyncio
asyncio REPL 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> from contextvars import ContextVar
>>> ctx = ContextVar('ctx')
>>> ctx.set(1)
<Token var=<ContextVar name='ctx' at 0x10f704fe0> at 0x10f702000>
>>> 

I don't know what "other problems" you were seeing, but if you are still seeing them in 3.10+ please open reopen this or create a new issue with full details.

**Comment by wicol** [comment]
I'm getting the same thing with 3.11:
```
# python
Python 3.11.0 (main, Nov 15 2022, 08:44:11) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
root@17823fe6186d:/app# python -m asyncio
asyncio REPL 3.11.0 (main, Nov 15 2022, 08:44:11) [GCC 10.2.1 20210110] on linux
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> from contextvars import ContextVar
>>> ctx = ContextVar('ctx')
>>> ctx.set(1)
<Token var=<ContextVar name='ctx' at 0xffffa695cc70> at 0xffffa68ed7c0>
>>> ctx.get()
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/asyncio/__main__.py", line 34, in callback
    coro = func()
           ^^^^^^
  File "<console>", line 1, in <module>
LookupError: <ContextVar name='ctx' at 0xffffa695cc70>
>>>
```

**Comment by terryjreedy** [comment]
Irit, you left off `ctc.get()`, which is what fails.  I get same failure on Win10 local main compiled 10 hours ago.

**Comment by ZeroIntensity** [comment]
Fixed by gh-124594
