### ISSUE TITLE
starting a thread in __del__ hangs at interpreter shutdown

### ISSUE THREAD

**Issue by 6be01009-0e09-42e9-a035-403e22a7f3b6** [python/cpython#87950]
BPO | [43784](https://bugs.python.org/issue43784)
--- | :---
Nosy | @rhettinger, @pfmoore, @pitrou, @tjguk, @zware, @eryksun, @zooba, @sylikc
Files | <li>[win_subprocess_hang.py](https://bugs.python.org/file49947/win_subprocess_hang.py "Uploaded as text/plain at 2021-04-09.05:25:49 by @sylikc"): Sample code that hangs</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-09.05:25:49.909>
labels = ['3.8', 'type-bug', 'library', '3.9', '3.10']
title = 'starting a thread in __del__ hangs at interpreter shutdown'
updated_at = <Date 2021-04-10.06:05:35.590>
user = 'https://github.com/sylikc'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-10.06:05:35.590>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-04-09.05:25:49.909>
creator = 'sylikc'
dependencies = []
files = ['49947']
hgrepos = []
issue_num = 43784
keywords = []
message_count = 4.0
messages = ['390587', '390593', '390658', '390695']
nosy_count = 8.0
nosy_names = ['rhettinger', 'paul.moore', 'pitrou', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'sylikc']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43784'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by sylikc** [comment]
Hi, just curious, how far down in the backlog is this issue, and how likely would it to get fixed?  It still exhibits this behavior on the most recent releases

**Comment by arhadthedev** [comment]
> Reader threads for stdout and stderr are only used in Windows, since there's no equivalent to select/poll for synchronous pipes in Windows.

Adding `OS-windows` tag to notify these who can design around the race between a worker thread and interpreter shutdown routine. Probably a critical section or mutex would warrant? Thus, tagging `export-multiprocessing` as well for expertise on possible deadlocks here.

**Comment by zooba** [comment]
It's not Windows-specific, apart from the fact that `subprocess.Popen.communicate` on Windows relies on threads and on Linux it doesn't.

A threading/state expert is needed to figure out the best way to cause thread creation to fail during finalization (either object or interpreter - I'm not sure which). And it's likely that this will still leave the original code broken, just more quickly and with an unhandled exception.

**Comment by sylikc** [comment]
🙄 Looks like this is a truly complex issue.

Anyways, I think an unhandled exception is preferred to hanging the interpreter.  At least that way, control flow can continue... like an external caller to run a python script doesn't wait indefinitely, but can read an error code from the interpreter crash

**Comment by gpshead** [comment]
> A threading/state expert is needed to figure out the best way to cause thread creation to fail during finalization (either object or interpreter - I'm not sure which). And it's likely that this will still leave the original code broken, just more quickly and with an unhandled exception.

https://github.com/python/cpython/pull/104826 from https://github.com/python/cpython/issues/104690 may be of interest...

That was focusing on the `atexit` finalizer case. I'm not sure if it does enough to raise an exception for the case outlined in this issue but it's at least a step in that direction.

**Comment by sylikc** [comment]
Interesting issues referred.  If the PR #104826 goes through I'd be curious if it'd be a partial fix... possibly.

Afterall, it touches `static PyObject * thread_PyThread_start_new_thread(PyObject *self, PyObject *fargs)` and catches interpreter shutdown... I've never looked into Python source code, but it looks close to my issue 😂

**Comment by sylikc** [comment]
So, I tested the code chunk from https://github.com/python/cpython/issues/87950#issuecomment-1093910115 on **CPython 3.12.0 on Windows x64**, and it definitely doesn't hang anymore.

> ```python
>     import threading
> 
>     class C:
>         def __del__(self):
>             t = threading.Thread(target=print, args=('spam',), daemon=True)
>             t.start()
> 
>     c = C()
>     #del c # uncomment to prevent hanging
> ```

It crashes with
```
Exception ignored in: <function C.__del__ at 0x000002953146E3E0>
Traceback (most recent call last):
  File "C:\TEMP\test.py", line 6, in __del__
  File "C:\Python312\Lib\threading.py", line 971, in start
RuntimeError: can't create new thread at interpreter shutdown
```

Which is much more ideal.  I can now trap this error and do additional processing.

Is it possible to backport this to older versions, or is this issue considered resolved but only for v3.12.0+?

**Comment by gpshead** [comment]
The details on this kind of change are often quite a challenge to get right. We're not likely to backport any changes that may have helped fix this to 3.11.x (which is going to move to security fix only status soon anyways).

_(keeping open for now as this being fixed deserves further verification.)_

**Comment by serhiy-storchaka** [comment]
Since 3.12, starting a thread at interpreter shutdown raises RuntimeError instead of hanging (gh-104690), as confirmed above. Closing as fixed.
