### ISSUE TITLE
inspect.signature does not work for datetime classes

### ISSUE THREAD

**Issue by bf047d34-3faa-4900-b5d1-454a18c82fa9** [python/cpython#88784]
BPO | [44618](https://bugs.python.org/issue44618)
--- | :---
Nosy | @gvanrossum, @hongweipeng, @mauvilsa
PRs | <li>python/cpython#27177</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-13.07:41:18.210>
labels = ['type-bug', '3.8', '3.9', '3.10', '3.7', 'library']
title = 'inspect.signature does not work for datetime classes'
updated_at = <Date 2021-07-17.09:51:41.720>
user = 'https://github.com/mauvilsa'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-17.09:51:41.720>
actor = 'mauvilsa'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-07-13.07:41:18.210>
creator = 'mauvilsa'
dependencies = []
files = []
hgrepos = []
issue_num = 44618
keywords = ['patch']
message_count = 6.0
messages = ['397387', '397481', '397484', '397488', '397713', '397715']
nosy_count = 3.0
nosy_names = ['gvanrossum', 'hongweipeng', 'mauvilsa']
pr_nums = ['27177']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44618'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by bf047d34-3faa-4900-b5d1-454a18c82fa9** [comment]
Classes in the datetime module are implemented using \_\_new__ with some named parameters. I want to be able to inspect their signature to know which are the names of the parameters it accepts like it works for most classes. However, this does not work for classes in the datetime module. I already mentioned this in https://bugs.python.org/issue40897 but now I am thinking this should be a separate issue so I am creating this one.

An example is the class timedelta. It has as parameters days, seconds, microseconds, milliseconds, minutes, hours and weeks. If I run the following script trying different python versions

```shell
for py in 36 37 38 39; do
  source py${py}/bin/activate
  echo "=== $(python3 --version) ==="
  python3 -c "
from datetime import timedelta
import inspect
print(inspect.signature(timedelta.__new__))
print(inspect.signature(timedelta.__init__))
inspect.signature(timedelta)
"
  deactivate
done
```

What I get is

```
=== Python 3.6.9 ===
(*args, **kwargs)
(self, /, *args, **kwargs)
Traceback (most recent call last):
...
ValueError: no signature found for builtin type <class 'datetime.timedelta'>
=== Python 3.7.11 ===
(*args, **kwargs)
(self, /, *args, **kwargs)
Traceback (most recent call last):
...
ValueError: no signature found for builtin type <class 'datetime.timedelta'>
=== Python 3.8.11 ===
(*args, **kwargs)
(self, /, *args, **kwargs)
Traceback (most recent call last):
...
ValueError: no signature found for builtin type <class 'datetime.timedelta'>
=== Python 3.9.6 ===
(*args, **kwargs)
(self, /, *args, **kwargs)
Traceback (most recent call last):
...
ValueError: no signature found for builtin type <class 'datetime.timedelta'>
```

**Comment by furkanonder** [comment]
Reproduced in Python 3.12.0a7.

```
Python 3.12.0a7+ (heads/main:8d95012c95, May 13 2023, 14:05:03) [GCC 13.1.1 20230429] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import timedelta
>>> import inspect
>>> print(inspect.signature(timedelta.__new__))
(*args, **kwargs)
>>> print(inspect.signature(timedelta.__init__))
(self, /, *args, **kwargs)
>>> inspect.signature(timedelta)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abc/cpython/Lib/inspect.py", line 3316, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abc/cpython/Lib/inspect.py", line 3060, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abc/cpython/Lib/inspect.py", line 2622, in _signature_from_callable
    raise ValueError(
ValueError: no signature found for builtin type <class 'datetime.timedelta'>
>>> 
```

**Comment by StanFromIreland** [comment]
Since this is a problem with how the C extension is configured, maybe we could make some workaround where it calls the python implementation signature?

```
>>> from _pydatetime import timedelta
... import inspect
... print(inspect.signature(timedelta.__new__))
... print(inspect.signature(timedelta.__init__))
... inspect.signature(timedelta)
... 
(cls, days=0, seconds=0, microseconds=0, milliseconds=0, minutes=0, hours=0, weeks=0)
(self, /, *args, **kwargs)
<Signature (days=0, seconds=0, microseconds=0, milliseconds=0, minutes=0, hours=0, weeks=0)>

```

**Comment by serhiy-storchaka** [comment]
#136573 fixes this issue, most cases. The only cases without signature/with unsupported signature are:

* The `tzinfo` constructor. This is an abstract class, you should not create instances of it. There is a difference between Python and C implementations. Python implementation does not accept any argument, C implementation accepts any arguments.
* The `timezone` constructor. Python implementation takes optional `name` argument with default value None. In C implementation, passing None and not passing anything give different results, so None cannot be used as the default value. `help()` shows it as `timezone(offset, name=<unrepresentable>)`.
* All `replace()` methods. They are the same as `__replace__()` methods, so we can give them the same signature, `__replace__(self, /, **changes)`, but it does not show which keywords are accepted. So, `help()` shows the `datetime.replace()` signature as `replace(self, /, year=unchanged, month=unchanged, day=unchanged, unchanged, minute=unchanged, second=unchanged, microsecond=unchanged, tzinfo=unchanged, *, fold=unchanged)`, which is not supported in `inspect.signature()`.

To support this cases, we need a general solution in `inspect.signature()` (which would fix many other cases) and somehow resolve the differences between Python and C implementations. These are different issues.
