### ISSUE TITLE
importing does not dispatch to __builtins__.__getitem__ to lookup __import__

### ISSUE THREAD

**Issue by 8527e2fb-3575-4b29-bda6-022dc83e1251** [python/cpython#88809]
BPO | [44643](https://bugs.python.org/issue44643)
--- | :---
Nosy | @brettcannon, @stevendaprano, @pxeger
Files | <li>[dict_lookup_demo.py](https://bugs.python.org/file50151/dict_lookup_demo.py "Uploaded as text/plain at 2021-07-15.08:30:04 by @pxeger"): Demonstration of this behaviour</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-15.08:30:05.599>
labels = ['interpreter-core', 'type-feature', '3.9', '3.10', '3.11']
title = 'importing does not dispatch to __builtins__.__getitem__ to lookup __import__'
updated_at = <Date 2021-07-15.10:51:35.067>
user = 'https://github.com/pxeger'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-15.10:51:35.067>
actor = 'pxeger'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2021-07-15.08:30:05.599>
creator = 'pxeger'
dependencies = []
files = ['50151']
hgrepos = []
issue_num = 44643
keywords = []
message_count = 6.0
messages = ['397531', '397532', '397533', '397534', '397535', '397536']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'steven.daprano', 'pxeger']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44643'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by jeff5** [comment]
I stumbled across this too and agree with @pxeger's analysis of the cause. Here's a simple reproducer:
```
>>> prog = """\
... import sys
... """
>>> progc = compile(prog, '*<:)', 'exec')
>>> exec(progc, dict(__builtins__=NotDict('builtins')))
Traceback (most recent call last):
  File "<pyshell#217>", line 1, in <module>
    exec(progc, dict(__builtins__=NotDict('builtins')))
  File "*<:)", line 1, in <module>
SystemError: D:\_w\1\s\Objects\dictobject.c:1756: bad argument to internal function
```
Here, `NotDict` is a mapping class [1] that is not a `dict` that I was using to probe behaviour in `ceval.c`.

I read the argument that `__builtins__` in globals as used by `exec`/`eval` may be CPython specific. I'm trying to reproduce the logic: it it _is_ a little clunky.

However, the `builtins` module, and that fact that its dictionary (or another object) can appear as `function.__builtins__` and `frame.f_builtins`, appear to be expected features of Python. Everywhere else, the interpreter allows for the possibility that `f_builtins` is not a `dict`, conditionally taking a slow path when it isn't, in a way it would be easy to incorporate here.

Is it not a principle that nothing you can type should raise a `SystemError`?

---
[1] For completeness:
```
# Class to use as a namespace in exec (not a dict)
class NotDict():
    def __init__(self, name):
        self.name = name
        self.map = dict()
    def __getitem__(self, key):
        print(f'== {self.name}.__getitem__({key})')
        return self.map.__getitem__(key)
    def __setitem__(self, key, value):
        print(f'== {self.name}.__setitem__({key}, {value})')
        return self.map.__setitem__(key, value)
    def __delitem__(self, key):
        print(f'== {self.name}.__delitem__({key})')
        return self.map.__delitem__(key)
```
