### ISSUE TITLE
Code objects can contain unmarshallable objects

### ISSUE THREAD

**Issue by encukou** [python/cpython#89290]
BPO | [45127](https://bugs.python.org/issue45127)
--- | :---
Nosy | @encukou, @shihai1991, @FFY00, @DiddiLeija
Files | <li>[reproducer_replace.py](https://bugs.python.org/file50268/reproducer_replace.py "Uploaded as text/plain at 2021-09-07.13:57:18 by @encukou")</li><li>[reproducer_compileall.py](https://bugs.python.org/file50269/reproducer_compileall.py "Uploaded as text/plain at 2021-09-07.13:57:30 by @encukou")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-07.13:57:18.092>
labels = []
title = 'Code objects can contain unmarshallable objects'
updated_at = <Date 2021-09-07.17:23:45.434>
user = 'https://github.com/encukou'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-07.17:23:45.434>
actor = 'shihai1991'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-09-07.13:57:18.092>
creator = 'petr.viktorin'
dependencies = []
files = ['50268', '50269']
hgrepos = []
issue_num = 45127
keywords = []
message_count = 3.0
messages = ['401277', '401278', '401281']
nosy_count = 4.0
nosy_names = ['petr.viktorin', 'shihai1991', 'FFY00', 'DiddiLeija']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45127'
versions = []
```

</p></details>

**Comment by vasiliyk** [comment]
I want to propose to keep code objects unrestricted at creation and just improve the error at save time.

Marshal already raises on `dump`, but the message does not say where the problem is. A code object can contain many values, and with nested code objects it is hard to tell what `MyStr` refers to.

```pycon
>>> import marshal
>>> class MyStr(str): pass
... marshal.dumps(compile("", MyStr("foo.py"), "exec"))
...
Traceback (most recent call last):
  File "<python-input-1>", line 2, in <module>
    marshal.dumps(compile("", MyStr("foo.py"), "exec"))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot marshal MyStr objects
```

The error could carry context to make it more helpful:

```pytb
Traceback (most recent call last):
  File "<python-input-1>", line 2, in <module>
    marshal.dumps(compile("", MyStr("foo.py"), "exec"))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot marshal MyStr objects: 'foo.py' (subclasses of str are not supported)
when marshalling code object field co_filename
when marshalling code object '<module>' (foo.py, line 1)
```

This covers every path that creates a code object.

Why not reject such objects at creation?

- Most code objects are never written to a `.pyc` (`exec`, bytecode tools, `replace()` in tests); restricting creation would break code that works today.
- Nothing changes for code that is not saved, so there is no compatibility concern.
- It seems Java/.Net use a similar model (allow runtime-only code to reference arbitrary objects and restrict what can be saved). Not sure how much weight 'others do it too' can carry :]

**Comment by picnixz** [comment]
@serhiy-storchaka

**Comment by picnixz** [comment]
FTR, if someone messes up with code.replace, it is at their own discretion and we do not want to validate their modifications. This is why we closes previous similar issues

**Comment by serhiy-storchaka** [comment]
I agree with @vasiliyk. We should not restrict the use which does not involve marshalling.

Adding notes to locate error like in pickle and json is also a good idea. It was impossibly to implement it before the changes which were made few days ago -- we did not have a raised exception, only an error code.
