### ISSUE TITLE
Cross-module dataclass inheritance breaks get_type_hints

### ISSUE THREAD

**Issue by f1757f88-e777-456d-af43-08b017b56f99** [python/cpython#89687]
BPO | [45524](https://bugs.python.org/issue45524)
--- | :---
Nosy | @gvanrossum, @ericvsmith, @JelleZijlstra, @sobolevn, @Fidget-Spinner, @AlexWaygood
PRs | <li>python/cpython#29158</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericvsmith'
closed_at = None
created_at = <Date 2021-10-19.14:37:47.448>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'Cross-module dataclass inheritance breaks get_type_hints'
updated_at = <Date 2022-01-22.08:37:13.515>
user = 'https://bugs.python.org/aidanbclark'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-22.08:37:13.515>
actor = 'AlexWaygood'
assignee = 'eric.smith'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-10-19.14:37:47.448>
creator = 'aidan.b.clark'
dependencies = []
files = []
hgrepos = []
issue_num = 45524
keywords = ['patch']
message_count = 13.0
messages = ['404307', '404312', '404313', '404314', '404321', '404740', '404752', '404754', '404812', '404822', '404823', '404907', '404918']
nosy_count = 8.0
nosy_names = ['gvanrossum', 'eric.smith', 'JelleZijlstra', 'slebedev', 'sobolevn', 'kj', 'AlexWaygood', 'aidan.b.clark']
pr_nums = ['29158']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45524'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-137168

**Comment by tuukkamustonen** [comment]
Just bumped into this trying to use a DI framework (that analyzes `__init__` type hints).

It makes it impossible to use dataclasses and inheritance (across modules). You have to either:

1. Explicitly re-import the parent's types in the child module (and exclude those from linters/formatters that would nag or drop them)
2. Not use dataclasses

The syntax that dataclasses allow is much nicer, though - you avoid the need to re-write and pass parent's arguments in the child's `__init__`.

So there _are_ workarounds, it's not a blocker, but inconvenient and comes as a surprise...

**Comment by JelleZijlstra** [comment]
The other solution is to not use `typing.get_type_hints`. It makes a number of questionable choices and it's likely more robust to use `inspect.get_annotations` directly.

Also, in 3.14+ this will work seamlessly if you remove the future import.

**Comment by Tishka17** [comment]
`inspect.get_annotations` does not resolve type hints, it gives you strings. Anyway, the bug is not related to `get_type_hints` logic, it is a bug with dataclasses: `make_dataclass` regenerates `__init__` method on a child class and copies all annotations from parent without solving them. So, if the annotations are strings, it uses them as-is and the information about a namespace is lost and cannot be recovered by any means.

**Comment by Tishka17** [comment]
I've tried python3.14rc1 with `annotationlib.get_annotations`. It is still broken in the same way as it is with `get_type_hints`
```
Traceback (most recent call last):
  File "/src/tmp/dtc/child.py", line 21, in <module>
    print(annotationlib.get_annotations(Child.__init__, eval_str=True))
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/annotationlib.py", line 998, in get_annotations
    key: value if not isinstance(value, str) else eval(value, globals, locals)
                                                  ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'LocalDep' is not defined
```

**Comment by JelleZijlstra** [comment]
You are not showing a full code sample so I can't tell, but the problem may be that you're using `from __future__ import annotations`. The behavior under the future import is largely unchanged in Python 3.14. If you want good introspection, don't use `from __future__ import annotations`.

**Comment by Tishka17** [comment]
@JelleZijlstra what I see:
a.py
```
class A: pass
```
b.py:
```
import a
from annotationlib import ForwardRef

x = ForwardRef("Foo", module=a)
print(x.evaluate())
```
result:
```
NameError: name 'Foo' is not defined
```

**Comment by Tishka17** [comment]
The current problem is:
a.py:
```python
class A: pass
```
b.py:
```python
import a
from annotationlib import ForwardRef

class A: pass

x = ForwardRef("A", module='a')
cls = x.evaluate(globals=globals(), locals=locals())
assert cls is a.A
```

This raises an assertion error

**Comment by JelleZijlstra** [comment]
If you pass `globals()`, it uses those globals in preference to the `owner` parameter. This could perhaps be made more explicit in https://docs.python.org/3.14/library/annotationlib.html#annotationlib.ForwardRef.evaluate .

**Comment by Tishka17** [comment]
It should not, I believe, because there is no other way to make forward ref bounded to module

**Comment by JelleZijlstra** [comment]
It works if you just call `x.evaluate()` in your example without passing explicit `globals()`.

I'm not sure why you'd expect passing a different module's globals would help evaluate the ForwardRef.

**Comment by Tishka17** [comment]
Because it's what's happening inside `get_type_hints`

**Comment by JelleZijlstra** [comment]
I don't think so; its `globals` arguments defaults to None, not the calling module's `globals()`. Indeed, `typing.evaluate_forward_ref(x)` succeeds for your example too.

I realize this might cause problems though if you call `get_type_hints()` and need to pass `globals=globals()` for some ForwardRefs in there but not others. Not sure when that would happen though; I'd love self-contained examples where the current behavior doesn't work well.

**Comment by Tishka17** [comment]
a.py:
```python
from dataclasses import dataclass

class A: pass

@dataclass
class D:
    a: A

```

b.py:
```python
import a
from typing import ForwardRef, evaluate_forward_ref, get_type_hints
from annotationlib import get_annotations, Format
from dataclasses import dataclass

class A: pass

@dataclass
class D2(a.D):
    pass

print(get_type_hints(a.D.__init__))
print(a.D.__init__.__annotations__)
print(get_annotations(a.D.__init__, format=Format.VALUE))

print("D2")
print(get_type_hints(D2.__init__))
print(D2.__init__.__annotations__)
print(get_annotations(D2.__init__, format=Format.VALUE))
```


Playing with order of `A` and `D`, if the annotation is string or not, I got different behavior, but it should not be different. 
To fix this we should have a type hint holding module, but there isn't anything exceptForwardRef

**Comment by Tishka17** [comment]
What I see now:
* Attributes of ForwardRef are uncodumented https://docs.python.org/3.14/library/annotationlib.html#annotationlib.ForwardRef
* In cases ForwardRef has `owner` or `module` set ( ForwardRef('A', is_class=True, owner=<class 'a.D'>)) it is resolved by `get_type_hints` ignoring information about it's origin. 
* string annotations in class are not converted to `ForwardRef` and `__annotations__` strores them as is
* `TypeAliasType` doesn't expect module argument and is immutable so cannot be used as a lazy proxy to another module
* dataclasses copy annotations of all fields (including parent ones) to `__init__`

So, the question is:
How can I create an annotation (in runtume) which is lazy and references to the same type even if used or resolved in another place?

**Comment by JelleZijlstra** [comment]
As far as I can tell, things work correctly when creating a `ForwardRef` with an appropriate `owner=` and calling `.evaluate()`. Things also work correctly if you don't use string annotations.

What doesn't work well is `get_type_hints()`, because it's prone to passing in the wrong globals when it evaluates ForwardRefs. Unfortunately, that function has a lot of legacy behavior and is difficult to change. In user code, I'd recommend performing a simplified version of `get_type_hints()` directly, i.e., calling `annotationlib.get_annotations()`, converting any raw strings into ForwardRefs with the appropriate `owner`, and then calling `ForwardRef.evaluate()` as appropriate.

Dataclasses could do better at preserving the owner of field types in the case of inheritance. I think this patch would be an improvement:

```
diff --git a/Lib/dataclasses.py b/Lib/dataclasses.py
index 53b3b54cfb3..e3d25fb0840 100644
--- a/Lib/dataclasses.py
+++ b/Lib/dataclasses.py
@@ -789,7 +789,10 @@ def _get_field(cls, a_name, a_type, default_kw_only):
 
     # Only at this point do we know the name and the type.  Set them.
     f.name = a_name
-    f.type = a_type
+    if isinstance(a_type, str):
+        f.type = annotationlib.ForwardRef(a_type, owner=cls)
+    else:
+        f.type = a_type
 
     # Assume it's a normal field until proven otherwise.  We're next
     # going to decide if it's a ClassVar or InitVar, everything else
```

**Comment by Tishka17** [comment]
Ok, setting a `ForwardRef` with `owner` right on field type sounds better, but anyway it does nothing if `globals`/`locals` are passed. Looks like the encapuslation here is broken.

I still have no idea about the idea behind the module/owner. From my perspecitve any `ForwardRef` should be bounded to a scope, so it can still access the same value in that scope. If `ForwardRef` is created within a specific module, it is expected to be solved using objects in that module. It is not a matter of solver but an origin where it is created. 

Talking about this, I can say that I do not see much difference between `TypeAliasType` and `ForwardRef`, but you cannot create `TypeAliasType` instance providing another module so it cannot be used here. 

If you have any links related the design of `ForwardRef` attributes, please share
