### ISSUE TITLE
exception lost when loop.stop() in finally

### ISSUE THREAD

**Issue by 2d8f2ee3-565a-4169-80d2-2f59c1236ea9** [python/cpython#90052]
BPO | [45894](https://bugs.python.org/issue45894)
--- | :---
Nosy | @asvetlov, @serhiy-storchaka, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-24.20:35:15.395>
labels = ['type-bug', '3.8', '3.10', 'expert-asyncio']
title = 'exception lost when loop.stop() in finally'
updated_at = <Date 2021-11-25.00:34:04.982>
user = 'https://bugs.python.org/AmosAnderson'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-25.00:34:04.982>
actor = 'Amos.Anderson'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-11-24.20:35:15.395>
creator = 'Amos.Anderson'
dependencies = []
files = []
hgrepos = []
issue_num = 45894
keywords = []
message_count = 4.0
messages = ['406957', '406961', '406962', '406970']
nosy_count = 4.0
nosy_names = ['asvetlov', 'Amos.Anderson', 'serhiy.storchaka', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45894'
versions = ['Python 3.8', 'Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
If you change another_level to replace "except Exception as e:" by "except BaseException as e:"  you will get this:

```
% ./python.exe xx.py
INFO:root:start
DEBUG:asyncio:Using selector: KqueueSelector
INFO:root:raising exception
INFO:root:stopped
INFO:root:trapping from another_level
ERROR:root:
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/xx.py", line 14, in method_that_raises
    raise ValueError("my exception1")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: my exception1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/xx.py", line 23, in another_level
    await method_that_raises()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/xx.py", line 18, in method_that_raises
    await asyncio.sleep(0.5)
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/asyncio/tasks.py", line 648, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
ERROR:root:Event loop stopped before Future completed.
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/xx.py", line 32, in <module>
    asyncio.run(another_level())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/asyncio/runners.py", line 181, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/asyncio/runners.py", line 115, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/asyncio/base_events.py", line 648, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Event loop stopped before Future completed.
INFO:root:done
```
