### ISSUE TITLE
Add note that some multiprocessing examples don't work in the repl

### ISSUE THREAD

**Issue by aeb36b5a-92e2-4578-99c8-26ef942ff145** [python/cpython#90072]
BPO | [45914](https://bugs.python.org/issue45914)
--- | :---
Nosy | @rhettinger, @terryjreedy, @pfmoore, @tjguk, @zware, @eryksun, @zooba, @quattrozhou

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-28.04:37:54.305>
labels = ['3.11', 'type-bug', 'OS-windows', 'docs']
title = 'Very first multiprocessing example not working on Windows 11'
updated_at = <Date 2021-12-04.07:37:31.190>
user = 'https://github.com/quattrozhou'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-04.07:37:31.190>
actor = 'eryksun'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Windows']
creation = <Date 2021-11-28.04:37:54.305>
creator = 'quattrozhou'
dependencies = []
files = []
hgrepos = []
issue_num = 45914
keywords = []
message_count = 4.0
messages = ['407186', '407189', '407638', '407646']
nosy_count = 9.0
nosy_names = ['rhettinger', 'terry.reedy', 'paul.moore', 'tim.golden', 'docs@python', 'zach.ware', 'eryksun', 'steve.dower', 'quattrozhou']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45914'
versions = ['Python 3.11']
```

</p></details>

**Comment by StanFromIreland** [comment]
I get the same issue on Linux:

```
>>> from multiprocessing import Pool
... 
... def f(x):
...     return x*x
... 
... if __name__ == '__main__':
...     with Pool(5) as p:
...         print(p.map(f, [1, 2, 3]))
...         
Process ForkServerPoolWorker-1:
Process ForkServerPoolWorker-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/stan/PycharmProjects/cpython/Lib/multiprocessing/process.py", line 320, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/stan/PycharmProjects/cpython/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stan/PycharmProjects/cpython/Lib/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/stan/PycharmProjects/cpython/Lib/multiprocessing/queues.py", line 387, in get
    return _ForkingPickler.loads(res)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: module '__main__' has no attribute 'f'
  File "/home/stan/PycharmProjects/cpython/Lib/multiprocessing/process.py", line 320, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/stan/PycharmProjects/cpython/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stan/PycharmProjects/cpython/Lib/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/stan/PycharmProjects/cpython/Lib/multiprocessing/queues.py", line 387, in get
    return _ForkingPickler.loads(res)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: module '__main__' has no attribute 'f'
Process ForkServerPoolWorker-3:
Traceback (most recent call last):
  File "/home/stan/PycharmProjects/cpython/Lib/multiprocessing/process.py", line 320, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/stan/PycharmProjects/cpython/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stan/PycharmProjects/cpython/Lib/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/stan/PycharmProjects/cpython/Lib/multiprocessing/queues.py", line 387, in get
    return _ForkingPickler.loads(res)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^
AttributeError: module '__main__' has no attribute 'f'
```

So this is an issue for repl on all platforms.
