### ISSUE TITLE
Calling read() on HTTPError may cause KeyError in tempfile

### ISSUE THREAD

**Issue by b4354296-d728-4898-a9b2-6d3e3ff6e4f5** [python/cpython#90113]
BPO | [45955](https://bugs.python.org/issue45955)
--- | :---
Nosy | @corona10, @sivel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-01.19:12:05.368>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'Calling read() on HTTPError may cause KeyError in tempfile'
updated_at = <Date 2022-02-07.03:08:26.172>
user = 'https://github.com/sivel'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-07.03:08:26.172>
actor = 'corona10'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-12-01.19:12:05.368>
creator = 'sivel'
dependencies = []
files = []
hgrepos = []
issue_num = 45955
keywords = []
message_count = 1.0
messages = ['407482']
nosy_count = 2.0
nosy_names = ['corona10', 'sivel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45955'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by icemac** [comment]
Calling `getattr(exc_value, "__notes__", ())` on `HTTPError` causes the same exception.

This happens when `pytest >= 7.2` tries to render an exception using the `exceptiongroup` package.

**Comment by corona10** [comment]
@icemac https://github.com/python/cpython/issues/98778 looks similar.
It's still happening with the latest commit version?

**Comment by corona10** [comment]
````

Python 3.12.0a5+ (heads/main:8de59c1bb9, Mar  5 2023, 00:53:41) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.error import HTTPError
>>> from urllib.request import HTTPDigestAuthHandler, HTTPPasswordMgrWithDefaultRealm, build_opener
>>> passman = HTTPPasswordMgrWithDefaultRealm()
>>> passman.add_password(None, 'httpbin.org', 'user', 'wrong')
>>> opener = build_opener(HTTPDigestAuthHandler(passman))
>>> try:
...     opener.open('https://httpbin.org/digest-auth/auth/user/passwd')
... except HTTPError as e:
...     e.read()
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/user/oss/cpython/Lib/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/oss/cpython/Lib/urllib/request.py", line 537, in _open
    return self._call_chain(self.handle_open, 'unknown',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/oss/cpython/Lib/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Users/user/oss/cpython/Lib/urllib/request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
>>>
````

Looks like be fixed.

**Comment by icemac** [comment]
@corona10 I forgot to mention that I am using Python 3.9.16. Is there a chance to get the fix backported to that version?

**Comment by corona10** [comment]
@icemac 

> @corona10 I forgot to mention that I am using Python 3.9.16. Is there a chance to get the fix backported to that version?

Unfortunately, no

**Comment by corona10** [comment]
This issue was solved by the following issues.
* https://github.com/python/cpython/issues/98778
* https://github.com/python/cpython/issues/101936
