### ISSUE TITLE
fileinput.input(path, inplace=True) crashes for valid filename with 252-255 characters

### ISSUE THREAD

**Issue by 460277e2-0191-4daf-b3d8-9c63bb058b94** [python/cpython#90123]
BPO | [45965](https://bugs.python.org/issue45965)
--- | :---
Nosy | @jamilraichouni
Files | <li>[long_filename_passed_to_fileinput.ipynb](https://bugs.python.org/file50471/long_filename_passed_to_fileinput.ipynb "Uploaded as text/plain at 2021-12-02.15:46:58 by @jamilraichouni"): Example Jupyter notebook showcasing that fileinput cannot handle a valid file</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-02.15:46:58.990>
labels = ['type-feature', 'library', '3.10']
title = 'fileinput.input(path, inplace=True) crashes for valid filename with 252-255 characters'
updated_at = <Date 2021-12-02.15:46:58.990>
user = 'https://github.com/jamilraichouni'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-02.15:46:58.990>
actor = 'jamil.raichouni'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-12-02.15:46:58.990>
creator = 'jamil.raichouni'
dependencies = []
files = ['50471']
hgrepos = []
issue_num = 45965
keywords = []
message_count = 1.0
messages = ['407534']
nosy_count = 1.0
nosy_names = ['jamil.raichouni']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45965'
versions = ['Python 3.10']
```

</p></details>

**Comment by StanFromIreland** [comment]
The error has since changed, on `3.15`:

```py
Python 3.15.0a0 (heads/main:046a4e39b3f, Aug 10 2025, 11:57:03) [GCC 15.1.1 20250521 (Red Hat 15.1.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fileinput
... from pathlib import Path
... path = Path(252 * "x")
... path.write_text("")
... for line in fileinput.input(path, inplace=True):
...     pass
...     
Traceback (most recent call last):
  File "<python-input-0>", line 5, in <module>
    for line in fileinput.input(path, inplace=True):
                ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/stan/PycharmProjects/cpython/Lib/fileinput.py", line 251, in __next__
    line = self._readline()
  File "/home/stan/PycharmProjects/cpython/Lib/fileinput.py", line 337, in _readline
    os.rename(self._filename, self._backupfilename)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' -> 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.bak'
>>> 
```
