### ISSUE TITLE
typing.NamedTuple with default arguments without type annotations is falsy

### ISSUE THREAD

**Issue by 9d440abf-3ac8-4ed7-8860-bff675b85c27** [python/cpython#90130]
BPO | [45972](https://bugs.python.org/issue45972)
--- | :---
Nosy | @gvanrossum, @ericvsmith, @TeamSpen210, @Fidget-Spinner, @AlexWaygood, @emontnemery

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-03.08:45:38.495>
labels = ['3.8', 'type-bug', 'library', '3.9']
title = 'typing.NamedTuple with default arguments without type annotations is falsy'
updated_at = <Date 2021-12-03.11:44:35.319>
user = 'https://github.com/emontnemery'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-03.11:44:35.319>
actor = 'emontnemery'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-12-03.08:45:38.495>
creator = 'emontnemery'
dependencies = []
files = []
hgrepos = []
issue_num = 45972
keywords = []
message_count = 7.0
messages = ['407570', '407571', '407572', '407573', '407575', '407576', '407579']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'eric.smith', 'Spencer Brown', 'kj', 'AlexWaygood', 'emontnemery']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45972'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by JelleZijlstra** [comment]
Agree that it's good to document that typing.NamedTuple only picks up annotated attributes. Would you be willing to submit a PR?

**Comment by gvanrossum** [comment]
> To me, the fact that NamedTuple uses class attributes to provide field defaults feels like an implementation detail that is only relevant to an unusual edge case.

This implementation detail would have to be part of the specification of NamedTuple though, right? It doesn't feel like something that we should left unspecified.
```
>>> class C(NamedTuple):
...   a: int = 0
...   b: int
...   c = 42
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gvanrossum\AppData\Local\Programs\Python\Python310\lib\typing.py", line 2274, in __new__
    raise TypeError(f"Non-default namedtuple field {field_name} "
TypeError: Non-default namedtuple field b cannot follow default field a
>>> class C(NamedTuple):
...   a: int
...   b: int = 0
...   c = 42
...
>>> C(1000)
C(a=1000, b=0)
>>>
```
