### ISSUE TITLE
Strip IsolatedAsyncioTestCase frames from reported stacktraces

### ISSUE THREAD

**Issue by asvetlov** [python/cpython#90286]
BPO | [46128](https://bugs.python.org/issue46128)
--- | :---
Nosy | @asvetlov, @serhiy-storchaka
PRs | <li>python/cpython#30196</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-19.08:45:55.760>
labels = ['library', '3.9', '3.10', '3.11']
title = 'Strip IsolatedAsyncioTestCase frames from reported stacktraces'
updated_at = <Date 2021-12-19.11:43:26.633>
user = 'https://github.com/asvetlov'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-19.11:43:26.633>
actor = 'asvetlov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-12-19.08:45:55.760>
creator = 'asvetlov'
dependencies = []
files = []
hgrepos = []
issue_num = 46128
keywords = ['patch']
message_count = 3.0
messages = ['408887', '408892', '408895']
nosy_count = 2.0
nosy_names = ['asvetlov', 'serhiy.storchaka']
pr_nums = ['30196']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue46128'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by bialix** [comment]
Quite annoying to see internals in traceback. Is it really can't be fixed? Please?

Just simple example:
```
import unittest

class TestAsync(unittest.IsolatedAsyncioTestCase):
    async def test_fail(self):
        self.fail()
```

And got:

```
C:\Temp>python -m unittest
F
======================================================================
FAIL: test_fail (test_async.TestAsync)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python\3.10-64\lib\unittest\async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "C:\Python\3.10-64\lib\unittest\async_case.py", line 87, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "C:\Python\3.10-64\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python\3.10-64\lib\unittest\async_case.py", line 101, in _asyncioLoopRunner
    ret = await awaitable
  File "C:\Temp\test_async.py", line 5, in test_fail
    self.fail()
AssertionError: None

----------------------------------------------------------------------
Ran 1 test in 0.013s

FAILED (failures=1)
```
