### ISSUE TITLE
Multiple test failures on Alpine 3.15 / musl-1.2.2-r7

### ISSUE THREAD

**Issue by tiran** [python/cpython#90548]
BPO | [46390](https://bugs.python.org/issue46390)
--- | :---
Nosy | @brettcannon, @terryjreedy, @tiran, @zware, @ncopa
Files | <li>[alpine315-tests.txt](https://bugs.python.org/file50566/alpine315-tests.txt "Uploaded as text/plain at 2022-01-17.12:12:10 by @tiran")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-15.12:56:24.197>
labels = ['type-bug', 'tests', 'build', '3.11']
title = 'Multiple test failures on Alpine 3.15 / musl-1.2.2-r7'
updated_at = <Date 2022-03-31.17:55:03.007>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-31.17:55:03.007>
actor = 'brett.cannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build', 'Tests']
creation = <Date 2022-01-15.12:56:24.197>
creator = 'christian.heimes'
dependencies = []
files = ['50566']
hgrepos = []
issue_num = 46390
keywords = []
message_count = 7.0
messages = ['410645', '410848', '410849', '411187', '411191', '411193', '411905']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'terry.reedy', 'christian.heimes', 'zach.ware', 'ncopa']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46390'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-131313
* gh-134454
* gh-137864
* gh-138348
* gh-138592
* gh-138593
* gh-138600
* gh-138601
* gh-138602
* gh-138713

**Comment by tiran** [comment]
GH-92826 is a compiler or musl libc issue on Alpine that manifests on PPC64LE platforms.

**Comment by brettcannon** [comment]
FYI neither Alpine nor musl are covered by [PEP 11](https://peps.python.org/pep-0011/) (PPC64LE is tier-2, though).

**Comment by tianon** [comment]
FWIW, I visually spot-checked each instance of `FAIL:` in https://buildbot.python.org/all/api/v2/logs/11438284/raw_inline today (the latest build from https://buildbot.python.org/all/#/workers/19 at the time of my checking), and almost all the current failures are locale-related (which is somewhat expected with musl; see https://wiki.musl-libc.org/open-issues#Locale-limitations).

If we ignore the Locale-related failures, here are the two failures I'm seeing that remain:

```
======================================================================
FAIL: test_fma_zero_result (test.test_math.FMATests.test_fma_zero_result)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/buildbot/buildarea/3.x.ware-alpine/build/Lib/test/test_math.py", line 2760, in test_fma_zero_result
    self.assertIsNegativeZero(math.fma(tiny, -tiny, 0.0))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/buildbot/buildarea/3.x.ware-alpine/build/Lib/test/test_math.py", line 2876, in assertIsNegativeZero
    self.assertTrue(
    ~~~~~~~~~~~~~~~^
        value == 0 and math.copysign(1, value) < 0,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        msg="Expected a negative zero, got {!r}".format(value)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
AssertionError: False is not true : Expected a negative zero, got 0.0

----------------------------------------------------------------------
```

```
======================================================================
FAIL: test_fpathconf (test.test_os.TestInvalidFD.test_fpathconf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/buildbot/buildarea/3.x.ware-alpine/build/Lib/test/test_os.py", line 2452, in test_fpathconf
    self.check(os.pathconf, "PC_NAME_MAX")
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/buildbot/buildarea/3.x.ware-alpine/build/Lib/test/test_os.py", line 2379, in check
    self.fail("%r didn't raise an OSError with a bad file descriptor"
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              % f)
              ^^^^
AssertionError: <built-in function pathconf> didn't raise an OSError with a bad file descriptor

----------------------------------------------------------------------
```

These certainly seem worrying, but not "the build is totally invalid and shouldn't exist" levels of worrying (which is what I was looking at this to evaluate -- namely whether https://github.com/docker-library/python can reasonably continue to provide Alpine-based builds or whether we should deprecate and remove them).

To be very clear, I don't have any good opinions on what CPython maintainers should do here (and in fact would love to follow any recommendations, including deprecating these builds anyhow, if that's the consensus), but I went through some of the data and figured it'd be worth noting the data points I found. :bow: :heart:

**Comment by bitdancer** [comment]
FWIW I'm invested in keeping python working on alpine.  I'll propose it for tier 3 when the tests actually pass ;)  test_fma is dealt with and I've proposed PR gh-131313 that will fix some other test failures by building on the parallel musl "fixes" for emscripten/wasi (including test_fpathconf, which is arguably not a musl *bug*), but there are more to go ;)

**Comment by zware** [comment]
Just to note, I did manage to [fix](https://buildbot.python.org/?#/builders/301/builds/11750) the [`test_cppext` failure](https://buildbot.python.org/?#/builders/301/builds/11749) seen on the Alpine buildbot by installing the `g++` package.  That will be included in any future rebuilds of the image as well.

The full list of (manually) installed packages on that worker are as follows:

```
                ca-certificates \
                bzip2-dev \
                ccache \
                coreutils \
                dpkg-dev dpkg \
                expat-dev \
                gcc \
                g++ \
                gdb \
                gdbm-dev \
                git \
                libc-dev \
                libffi-dev \
                libnsl-dev \
                libtirpc-dev \
                linux-headers \
                make \
                mpdecimal-dev \
                ncurses-dev \
                openssl \
                openssl-dev \
                pax-utils \
                py3-pip \  # Used to install buildbot-worker, later removed
                python3 \
                python3-dev \  # Later removed
                readline-dev \
                sqlite-dev \
                tcl-dev \
                tk \
                tk-dev \
                tzdata \
                xz-dev \
                zlib-dev \
                xvfb-run 
```

**Comment by zware** [comment]
With GH-134454, GH-138592, and GH-138593 merged, https://buildbot.python.org/#/builders/301/builds/12989 is the first green build on Alpine 3.22.1.  python/buildmaster-config#626 will move the Alpine worker from "unstable" to "stable" to prevent regressions.

@hugovk, is it too late to backport these three test-only changes to enable proper support on 3.14(.0)?

**Comment by hugovk** [comment]
It's fine to backport those for the next RC.

**Comment by zware** [comment]
Thanks, Hugo!  With the attached PRs and backports merged, I think we can go ahead and close this issue; new issues can be opened for anything further.

Also with these fixes merged, we have the option to bump `x86_64-linux-musl` up to Tier 3.  I'm not sure if we want to do that for 3.14 so close to release, though.

**Comment by vstinner** [comment]
> Thanks, Hugo! With the attached PRs and backports merged, I think we can go ahead and close this issue

Cool, congratulations to everyone who was involved in fixing this old issue :-)

**Comment by tianon** [comment]
> Also with these fixes merged, we have the option to bump `x86_64-linux-musl` up to Tier 3. I'm not sure if we want to do that for 3.14 so close to release, though.

Not sure if someone wanted to pick this part up now that we're into the 3.15 cycle, but figured it was worth a friendly ping/reminder in case someone did since the issue is closed so it probably won't be on anyone's radar officially. :smile:
