### ISSUE TITLE
Python 3.10 OpenSSL Configuration Issues

### ISSUE THREAD

**Issue by e91f3816-b999-40f5-bc1b-dffbfd2e99d4** [python/cpython#91019]
BPO | [46863](https://bugs.python.org/issue46863)
--- | :---
Nosy | @tiran, @adampinky85
Files | <li>[python_builds.tar.gz](https://bugs.python.org/file50653/python_builds.tar.gz "Uploaded as application/x-gzip at 2022-02-28.23:46:33 by @adampinky85")</li><li>[python_details.tar.gz](https://bugs.python.org/file50654/python_details.tar.gz "Uploaded as application/x-gzip at 2022-03-02.01:51:54 by @adampinky85")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-26.05:12:46.583>
labels = ['expert-SSL', 'type-bug', '3.10']
title = 'Python 3.10 OpenSSL Configuration Issues'
updated_at = <Date 2022-03-03.03:41:15.739>
user = 'https://github.com/adampinky85'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-03.03:41:15.739>
actor = 'adam'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['SSL']
creation = <Date 2022-02-26.05:12:46.583>
creator = 'adam'
dependencies = []
files = ['50653', '50654']
hgrepos = []
issue_num = 46863
keywords = []
message_count = 11.0
messages = ['414072', '414089', '414093', '414098', '414101', '414105', '414226', '414246', '414321', '414340', '414402']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'adam']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46863'
versions = ['Python 3.10']
```

</p></details>

**Comment by Doubletop12** [comment]
I have been going around in circles trying to find a solution to this but there is nothing that seems to work.
Here is the result of help() modules ssl in Python 3.10.7
`
help> modules ssl

Here is a list of modules whose name or summary contains 'ssl'.
If there are any, enter a module name to get more help.

asyncio.sslproto 
ssl - This module provides some more Pythonic support for SSL.
test.make_ssl_certs - Make the custom certificate and private key files used by test_ssl
test.ssl_servers 
test.ssltests 
test.test_asyncio.test_sslproto - Tests for asyncio/sslproto.py.
test.test_ssl 
pip._vendor.urllib3.contrib.pyopenssl - TLS with SNI_-support for Python 2. Follow these instructions if you would
pip._vendor.urllib3.util.ssl_ 
pip._vendor.urllib3.util.ssl_match_hostname - The match_hostname() function from Python 3.3.3, essential when using SSL.
pip._vendor.urllib3.util.ssltransport 

help> ^C
You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.
>>> 
 `
wheras for Python 


`
help> modules ssl

Here is a list of modules whose name or summary contains 'ssl'.
If there are any, enter a module name to get more help.

asyncio.sslproto 
ssl - This module provides some more Pythonic support for SSL.
_ssl 
pip._vendor.urllib3.contrib.pyopenssl - TLS with SNI_-support for Python 2. Follow these instructions if you would
pip._vendor.urllib3.util.ssl_ 
pip._vendor.urllib3.util.ssl_match_hostname - The match_hostname() function from Python 3.3.3, essential when using SSL.
pip._vendor.urllib3.util.ssltransport 
pyopenssl 
pyopenssl.openssl 
OpenGL.GLES2.OES.EGL_image_external_essl3 
Expected Tk Togl installation in /usr/lib/python3/dist-packages/OpenGL/Tk/togl-linux
Failure loading Togl package: can't find package Togl, on debian systems this is provided by `libtogl2`
OpenGL.raw.GLES2.OES.EGL_image_external_essl3 
OpenSSL - pyOpenSSL - A simple wrapper around the OpenSSL library
OpenSSL.SSL 
OpenSSL._util 
OpenSSL.crypto 
OpenSSL.debug 
OpenSSL.rand - PRNG management routines, thin wrappers.
OpenSSL.version - pyOpenSSL - A simple wrapper around the OpenSSL library
cryptography.hazmat.backends.openssl 
cryptography.hazmat.backends.openssl.aead 
cryptography.hazmat.backends.openssl.backend 
cryptography.hazmat.backends.openssl.ciphers 
cryptography.hazmat.backends.openssl.cmac 
cryptography.hazmat.backends.openssl.decode_asn1 
cryptography.hazmat.backends.openssl.dh 
cryptography.hazmat.backends.openssl.dsa 
cryptography.hazmat.backends.openssl.ec 
cryptography.hazmat.backends.openssl.ed25519 
cryptography.hazmat.backends.openssl.ed448 
cryptography.hazmat.backends.openssl.encode_asn1 
cryptography.hazmat.backends.openssl.hashes 
cryptography.hazmat.backends.openssl.hmac 
cryptography.hazmat.backends.openssl.ocsp 
cryptography.hazmat.backends.openssl.poly1305 
cryptography.hazmat.backends.openssl.rsa 
cryptography.hazmat.backends.openssl.utils 
cryptography.hazmat.backends.openssl.x25519 
cryptography.hazmat.backends.openssl.x448 
cryptography.hazmat.backends.openssl.x509 
cryptography.hazmat.bindings._openssl 
cryptography.hazmat.bindings.openssl 
cryptography.hazmat.bindings.openssl._conditional 
cryptography.hazmat.bindings.openssl.binding 

`
Clearly something is missing

Pete

**Comment by 9967819** [comment]
Interesting thread/problem! 

it also seems that the issue propagated itself into python 3.11 as well, affecting programs like certbot:

> smart@open-neurosecurity:~$ sudo certbot renew --dry-run -v
> Traceback (most recent call last):
>  File "/usr/bin/certbot", line 33, in <module>
>    sys.exit(load_entry_point('certbot==2.1.0', 'console_scripts', 'certbot')())
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/bin/certbot", line 25, in importlib_load_entry_point
>    return next(matches).load()
>          ^^^^^^^^^^^^^^^^^^^^
>  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
>    module = import_module(match.group('module'))
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
>    return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
> File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
> File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>  File "/usr/lib/python3/dist-packages/certbot/main.py", line 6, in <module>
>   from certbot._internal import main as internal_main
> File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 19, in <module>
>    import josepy as jose
>  File "/usr/lib/python3/dist-packages/josepy/__init__.py", line 40, in <module>
>    from josepy.json_util import (
>  File "/usr/lib/python3/dist-packages/josepy/json_util.py", line 14, in <module>
>    from OpenSSL import crypto
>  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
>    from OpenSSL import SSL, crypto
>  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 9, in <module>
>    from OpenSSL._util import (
>  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 6, in <module>
>    from cryptography.hazmat.bindings.openssl.binding import Binding
>  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 228, in <module>
>    Binding.init_static_locks()
>  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 188, in init_static_locks
>   cls._ensure_ffi_initialized()
>  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 176, in _ensure_ffi_initialized
>    _openssl_assert(
>  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 90, in _openssl_assert
>   raise InternalError(
> cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is > not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling > it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on > > how to reproduce this. ([_OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO > support routines::could not load the shared library'), _OpenSSLErrorWithText(code=310378599, lib=37, reason=103, > reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=126353445, lib=15, reason=524325, reason_text=b'error:07880025:common libcrypto routines::reason(524325)')])

**Comment by jamiegau** [comment]
Python is a good glue language for talking to legacy devices, however, I assume this issue I will describe is connected to this issue as well.

I have an embedded device running an old https server.

If I do a basic request such as in the following code..
```
import requests

def fetch_and_print_webpage(url):
    response = requests.get(url, verify=False)
    print(response.text)

def main():
    url = 'https://10.30.25.11:43758/?wsdl'
    fetch_and_print_webpage(url)

if __name__ == "__main__":
    main()
```
If running under python 3.9, it runs as expected.
However, If I run it under 3.10 or 3.11. I get the following error.
```
python Test2.py
Traceback (most recent call last):
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/urllib3/connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.30.25.11', port=43758): Max retries exceeded with url: /?wsdl (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamieg/Test2.py", line 12, in <module>
    main()
  File "/Users/jamieg/Test2.py", line 9, in main
    fetch_and_print_webpage(url)
  File "/Users/jamieg/Test2.py", line 4, in fetch_and_print_webpage
    response = requests.get(url, verify=False)
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jamieg/p310env/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.30.25.11', port=43758): Max retries exceeded with url: /?wsdl (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure (_ssl.c:1007)')))
```

From digging up on this, this error is because the later version of Python are compiled against the newer version of OpenSSL. The newer version having cyphers depricated and REMOVED  that the old embedded https server needs.

In effect, if I go over version 3.9  I lock myself out of talking to certain older embedded devices.

I was jumping to 3.11 as I wanted the speed boost.
But this currently holds me back.

This could be a serious issue for those using Python to talk to older embedded devices.

I wanted to point this out and also see if I could get an expert opinion on if it would be possible to get a python 3.11 with older OpenSSL libraries in it?  Or any other input in how to deal with this situation.
