### ISSUE TITLE
test_curses fails if terminal defaults to bright white text (15)

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#91221]
BPO | [47065](https://bugs.python.org/issue47065)
--- | :---
Nosy | @Yhg1s, @gpshead, @ncoghlan, @encukou, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-19.11:10:26.159>
labels = ['type-bug', 'tests']
title = 'test_curses fails if terminal defaults to bright white text (15)'
updated_at = <Date 2022-03-20.21:36:01.610>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-20.21:36:01.610>
actor = 'gregory.p.smith'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2022-03-19.11:10:26.159>
creator = 'ncoghlan'
dependencies = []
files = []
hgrepos = []
issue_num = 47065
keywords = []
message_count = 3.0
messages = ['415539', '415559', '415634']
nosy_count = 5.0
nosy_names = ['twouters', 'gregory.p.smith', 'ncoghlan', 'petr.viktorin', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue47065'
versions = []
```

</p></details>

### Linked PRs
* gh-132986
* gh-132990
* gh-132992

**Comment by Krelyshy** [comment]
Same issue with Konsole on openSUSE 15.3 while compiling Python 3.9.14 and 3.10.7

`TERM=xterm-256color
test_use_default_colors (test.test_curses.TestCurses) ... 
FAIL

======================================================================
FAIL: test_use_default_colors (test.test_curses.TestCurses)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/krel/dev/Python-3.9.14/Lib/test/test_curses.py", line 46, in wrapped
test(self, *args, **kwargs)
File "/home/krel/dev/Python-3.9.14/Lib/test/test_curses.py", line 991, in test_use_default_colors
self.assertIn(old, [(curses.COLOR_WHITE, curses.COLOR_BLACK), (-1, -1), (0, 0)])
AssertionError: (15, 0) not found in [(7, 0), (-1, -1), (0, 0)]

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
test test_curses failed`

**Comment by dandv** [comment]
Same issue with Konsole on Fedora 38:

```
Re-running test_curses in verbose mode (matching: test_use_default_colors)
TERM=xterm-256color
test_use_default_colors (test.test_curses.TestCurses.test_use_default_colors) ... 
======================================================================
FAIL: test_use_default_colors (test.test_curses.TestCurses.test_use_default_colors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dandv/downloads/Python-3.12.3/Lib/test/test_curses.py", line 49, in wrapped
    test(self, *args, **kwargs)
  File "/home/dandv/downloads/Python-3.12.3/Lib/test/test_curses.py", line 999, in test_use_default_colors
    self.assertIn(old, [(curses.COLOR_WHITE, curses.COLOR_BLACK), (-1, -1), (0, 0)])
AssertionError: (15, 0) not found in [(7, 0), (-1, -1), (0, 0)]
```

**Comment by picnixz** [comment]
I created a PR which simply skips this check. But I can also (15, 0) as a valid value. I don't know how easy and how likely there would be users that could have their own custom terminfo possibly with different `initialize_color` values.

**Comment by picnixz** [comment]
I've added the (15,0) pair so I think we can close this one. Let's re-open it other users have different issues and at this time we'll decide whether to skip the check or try to deduce more reliably the supported values.
