### ISSUE TITLE
No protection: `import numpy` in two different threads can lead to race-condition

### ISSUE THREAD

**Issue by cefac2db-eec3-4433-8759-1b576baf8bab** [python/cpython#91238]
BPO | [47082](https://bugs.python.org/issue47082)
--- | :---
Nosy | @tiran, @seberg, @jhgoebbert

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-21.17:03:05.346>
labels = ['interpreter-core', 'type-bug', '3.11']
title = 'No protection: `import numpy` in two different threads can lead to race-condition'
updated_at = <Date 2022-03-21.23:04:38.800>
user = 'https://github.com/jhgoebbert'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-21.23:04:38.800>
actor = 'seberg'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2022-03-21.17:03:05.346>
creator = 'jhgoebbert'
dependencies = []
files = []
hgrepos = []
issue_num = 47082
keywords = []
message_count = 4.0
messages = ['415687', '415690', '415718', '415722']
nosy_count = 3.0
nosy_names = ['christian.heimes', 'seberg', 'jhgoebbert']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue47082'
versions = ['Python 3.11']
```

</p></details>

**Comment by fbrunodr** [comment]
@seberg  can you provide a working example of that bug? I tried to simulate this race condition and could not reproduce the bug.

**Comment by seberg** [comment]
Unfortunately not, it was @jhgoebbert who experienced it, but maybe I can try tomorrow or so.  My hypothesis was cython got involved.  But of course it could be that there is a deeper threading issue elsewhere.  Another thing may be that you need a fairly new NumPy versions to run into the environment variable issue, because older versions probably do not mess with `OPENBLAS_MAIN_FREE`.

**Comment by cg505** [comment]
Hi! We have an extremely fragile reproduction case in the CI for SkyPilot here: https://github.com/skypilot-org/skypilot/actions/runs/14391450370/job/40359190320?pr=5095
Relevant stacktrace:
```
E 04-10 22:26:00 sdk.py:1486] Traceback (most recent call last):
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/work/skypilot/skypilot/sky/server/requests/executor.py", line 361, in _request_execution_wrapper
E 04-10 22:26:00 sdk.py:1486]     return_value = func(**request_body.to_kwargs())
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/work/skypilot/skypilot/sky/clouds/service_catalog/__init__.py", line 103, in list_accelerator_counts
E 04-10 22:26:00 sdk.py:1486]     results = _map_clouds_catalog(clouds,
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/work/skypilot/skypilot/sky/clouds/service_catalog/__init__.py", line 51, in _map_clouds_catalog
E 04-10 22:26:00 sdk.py:1486]     results = subprocess_utils.run_in_parallel(_execute_catalog_method,
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/work/skypilot/skypilot/sky/utils/subprocess_utils.py", line 138, in run_in_parallel
E 04-10 22:26:00 sdk.py:1486]     return list(ordered_iterators)
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/.local/share/uv/python/cpython-3.8.20-linux-x86_64-gnu/lib/python3.8/multiprocessing/pool.py", line 868, in next
E 04-10 22:26:00 sdk.py:1486]     raise value
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/.local/share/uv/python/cpython-3.8.20-linux-x86_64-gnu/lib/python3.8/multiprocessing/pool.py", line 125, in worker
E 04-10 22:26:00 sdk.py:1486]     result = (True, func(*args, **kwds))
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/work/skypilot/skypilot/sky/clouds/service_catalog/__init__.py", line 49, in _execute_catalog_method
E 04-10 22:26:00 sdk.py:1486]     return method(*args, **kwargs)
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/work/skypilot/skypilot/sky/clouds/service_catalog/vast_catalog.py", line 102, in list_accelerators
E 04-10 22:26:00 sdk.py:1486]     return common.list_accelerators_impl('Vast', _df, gpus_only, name_filter,
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/work/skypilot/skypilot/sky/clouds/service_catalog/common.py", line 578, in list_accelerators_impl
E 04-10 22:26:00 sdk.py:1486]     df = df[~df['GpuInfo'].isna()]
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/work/skypilot/skypilot/sky/clouds/service_catalog/common.py", line 153, in __getitem__
E 04-10 22:26:00 sdk.py:1486]     return self._load_df()[key]
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/work/skypilot/skypilot/sky/clouds/service_catalog/common.py", line 145, in _load_df
E 04-10 22:26:00 sdk.py:1486]     raise e
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/work/skypilot/skypilot/sky/clouds/service_catalog/common.py", line 138, in _load_df
E 04-10 22:26:00 sdk.py:1486]     self._update_func()
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/work/skypilot/skypilot/sky/clouds/service_catalog/common.py", line 209, in _update_catalog
E 04-10 22:26:00 sdk.py:1486]     r = requests.get(url=url,
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/test-env/lib/python3.8/site-packages/requests/api.py", line 73, in get
E 04-10 22:26:00 sdk.py:1486]     return request("get", url, params=params, **kwargs)
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/test-env/lib/python3.8/site-packages/requests/api.py", line 59, in request
E 04-10 22:26:00 sdk.py:1486]     return session.request(method=method, url=url, **kwargs)
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/test-env/lib/python3.8/site-packages/requests/sessions.py", line 579, in request
E 04-10 22:26:00 sdk.py:1486]     settings = self.merge_environment_settings(
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/test-env/lib/python3.8/site-packages/requests/sessions.py", line 760, in merge_environment_settings
E 04-10 22:26:00 sdk.py:1486]     env_proxies = get_environ_proxies(url, no_proxy=no_proxy)
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/test-env/lib/python3.8/site-packages/requests/utils.py", line 835, in get_environ_proxies
E 04-10 22:26:00 sdk.py:1486]     return getproxies()
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/.local/share/uv/python/cpython-3.8.20-linux-x86_64-gnu/lib/python3.8/urllib/request.py", line 2516, in getproxies_environment
E 04-10 22:26:00 sdk.py:1486]     for name, value in os.environ.items():
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/.local/share/uv/python/cpython-3.8.20-linux-x86_64-gnu/lib/python3.8/_collections_abc.py", line 744, in __iter__
E 04-10 22:26:00 sdk.py:1486]     yield (key, self._mapping[key])
E 04-10 22:26:00 sdk.py:1486]   File "/home/runner/.local/share/uv/python/cpython-3.8.20-linux-x86_64-gnu/lib/python3.8/os.py", line 675, in __getitem__
E 04-10 22:26:00 sdk.py:1486]     raise KeyError(key) from None
E 04-10 22:26:00 sdk.py:1486] KeyError: 'OPENBLAS_MAIN_FREE'
E 04-10 22:26:00 sdk.py:1486] 
```

We have some custom code to lazily import `numpy` as needed, and I guess it is running in one thread. It causes a crash in another thread - which is not doing an import, but is just trying to read from `os.environ`. In fact, you can see that the bottom three frames of the stacktrace are in CPython, and they all look very innocuous.

It seems that the numpy import is somehow changing os.environ out from under the thread that crashes. That's easy enough to understand, but what I can't understand is **how this is not protected by GIL**, since numpy's `os.environ` modification is happening in Python:
https://github.com/numpy/numpy/blob/v1.24.4/numpy/core/__init__.py#L14-L20
https://github.com/numpy/numpy/blob/v1.24.4/numpy/core/__init__.py#L50-L52

This is python 3.8.20 (I know EOL, but sharing anyway since it might help pin down the actual issue) with numpy 1.24.4. The threads are all part of a `multiprocessing.pool.ThreadPool`, which you can see in the stacktrace. It's here in the SkyPilot source:
https://github.com/skypilot-org/skypilot/blob/d01d496e66615656a2ddf57e4695151392b61c63/sky/utils/subprocess_utils.py#L136-L138
