### ISSUE TITLE
Python 3.10 hang at exit in drop_gil() (due to resource warning at exit?)

### ISSUE THREAD

**Issue by 2941a905-cf6d-4069-8e6f-bdecd9c20475** [python/cpython#91414]
BPO | [47258](https://bugs.python.org/issue47258)
--- | :---
Nosy | @rpurdie

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-04-08.10:02:05.768>
labels = ['interpreter-core', '3.10']
title = 'Python 3.10 hang at exit in drop_gil() (due to resource warning at exit?)'
updated_at = <Date 2022-04-08.10:02:05.768>
user = 'https://github.com/rpurdie'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.10:02:05.768>
actor = 'rpurdie'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2022-04-08.10:02:05.768>
creator = 'rpurdie'
dependencies = []
files = []
hgrepos = []
issue_num = 47258
keywords = []
message_count = 1.0
messages = ['416968']
nosy_count = 1.0
nosy_names = ['rpurdie']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue47258'
versions = ['Python 3.10']
```

</p></details>

**Comment by itachaaa** [comment]
Similar problems are found in Python 3.9.11. The stack is as follows;We have six threads, five of which are daemon threads, two of which periodically wait for the thread lock, and two of which periodically release the lock. When the lock is hanged, both the thread and the main thread that wait for the lock in the two periods are suspended.
`
(gdb) py-bt
Traceback (most recent call first):
  File "/usr1/python/python/target/checkout/package/python/python-22.50.19/lib/python3.9/socket.py", line 243, in __repr__
  Garbage-collecting
(gdb) bt
#0  0x0000ffff87f352a8 in pthread_cond_wait () from /lib64/libpthread.so.0
#1  0x0000aaaab1538184 in drop_gil (ceval=0xaaaab1b79820 <_PyRuntime+344>, ceval@entry=0xaaaab14dce9c <PyObject_Str+44>, ceval2=ceval2@entry=0xaaaab98e79f0,
    tstate=tstate@entry=0xaaaab98ea760) at Python/ceval_gil.h:178
#2  0x0000aaaab149b5c4 in eval_frame_handle_pending (tstate=0xaaaab98ea760) at Python/ceval.c:882
#3  _PyEval_EvalFrameDefault (tstate=<optimized out>,
    f=Frame 0xffff7833e610, for file /usr1/python/python/target/checkout/package/python/python-22.50.19/lib/python3.9/socket.py, line 243, in __repr__ (self=<SSLSoc   ket(_context=<SSLContext at remote 0xffff783d37c0>, _session=None, _sslobj=<_ssl._SSLSocket at remote 0xffff7838ca50>, server_side=False, server_hostname=None, do_h   andshake_on_connect=True, suppress_ragged_eofs=True, _connected=True) at remote 0xffff7838cac0>), throwflag=<optimized out>) at Python/ceval.c:1402
#4  0x0000aaaab1499e1c in _PyEval_EvalFrame (throwflag=0,
    f=Frame 0xffff7833e610, for file /usr1/python/python/target/checkout/package/python/python-22.50.19/lib/python3.9/socket.py, line 243, in __repr__ (self=<SSLSoc   ket(_context=<SSLContext at remote 0xffff783d37c0>, _session=None, _sslobj=<_ssl._SSLSocket at remote 0xffff7838ca50>, server_side=False, server_hostname=None, do_h   andshake_on_connect=True, suppress_ragged_eofs=True, _connected=True) at remote 0xffff7838cac0>), tstate=0xaaaab98ea760) at ./Include/internal/pycore_ceval.h:40
#5  function_code_fastcall (tstate=0xaaaab98ea760, co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Objects/call.c:330
#6  0x0000aaaab14f6360 in _PyObject_VectorcallTstate (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>,
    tstate=<optimized out>) at ./Include/cpython/abstract.h:118
#7  _PyObject_CallNoArg (func=<optimized out>) at ./Include/cpython/abstract.h:172
#8  call_unbound_noarg (self=<optimized out>, func=<function at remote 0xffff7ac07dc0>, unbound=<optimized out>) at Objects/typeobject.c:1515
#9  slot_tp_repr (self=<optimized out>) at Objects/typeobject.c:6630
#10 0x0000aaaab14dcd44 in PyObject_Repr (
    v=<SSLSocket(_context=<SSLContext at remote 0xffff783d37c0>, _session=None, _sslobj=<_ssl._SSLSocket at remote 0xffff7838ca50>, server_side=False, server_hostna   me=None, do_handshake_on_connect=True, suppress_ragged_eofs=True, _connected=True) at remote 0xffff7838cac0>) at Objects/object.c:420
#11 0x0000aaaab152006c in unicode_fromformat_arg (vargs=0xffffd4603ff8, f=<optimized out>, writer=0xffffd4603fb8) at Objects/unicodeobject.c:2989
#12 PyUnicode_FromFormatV (format=<optimized out>, vargs=...) at Objects/unicodeobject.c:3053
#13 0x0000aaaab1536368 in _PyErr_WarnFormatV (
    source=<SSLSocket(_context=<SSLContext at remote 0xffff783d37c0>, _session=None, _sslobj=<_ssl._SSLSocket at remote 0xffff7838ca50>, server_side=False, server_h   ostname=None, do_handshake_on_connect=True, suppress_ragged_eofs=True, _connected=True) at remote 0xffff7838cac0>, category=<type at remote 0xaaaab1b20db0>,
    stack_level=1, format=<optimized out>, vargs=<error reading variable: Cannot access memory at address 0xffffffbb>) at Python/_warnings.c:1124
#14 0x0000aaaab1536998 in PyErr_ResourceWarning (source=<optimized out>, stack_level=<optimized out>, format=<optimized out>) at Python/_warnings.c:1179
#15 0x0000ffff7abb9e54 in ?? ()
   from /opt/cloud/envs/Product-OSSToolService/222.170.102/rtsp/python/lib/python3.9/lib-dynload/_socket.cpython-39-aarch64-linux-gnu.so
#16 0x0000aaaab158a4b8 in finalize_garbage (tstate=0xaaaab98ea760, collectable=0xffffd4604280) at Modules/gcmodule.c:969
#17 collect (tstate=0xaaaab98ea760, generation=generation@entry=2, n_collected=n_collected@entry=0x0, n_uncollectable=n_uncollectable@entry=0x0,
    nofail=nofail@entry=1) at Modules/gcmodule.c:1260
#18 0x0000aaaab158b474 in _PyGC_CollectNoFail () at Modules/gcmodule.c:2097
#19 0x0000aaaab1554840 in _PyImport_Cleanup (tstate=tstate@entry=0xaaaab98ea760) at Python/import.c:572
#20 0x0000aaaab156963c in Py_FinalizeEx () at Python/pylifecycle.c:1426
#21 0x0000aaaab14a4110 in Py_RunMain () at Modules/main.c:679
#22 0x0000aaaab14a49f8 in pymain_main (args=args@entry=0xffffd4604568) at Modules/main.c:707
#23 0x0000aaaab14a4ad4 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:731
#24 0x0000ffff87c9ebec in __libc_start_main () from /lib64/libc.so.6
#25 0x0000aaaab14a37bc in _start ()`

**Comment by kumaraditya303** [comment]
@itachaaa Can you provide a minimal reproducer? Also can you try main branch?

**Comment by kumaraditya303** [comment]
Yes main means master branch.

**Comment by Gigioliva** [comment]
Any news on this? I have the same problem but can't create an MWE. I have a periodic task that runs ~300 containers per day with the same code and randomly ~4 of them hang in this state
