### ISSUE TITLE
async related issues on Windows 11

### ISSUE THREAD

**Issue by jkloth** [python/cpython#91845]
A recent update to Windows 11 is causing abnormalities in the test suite.  Note that the tests are not *failing*, but they are emitting error messages.

I believe the offending Windows update is [KB5012592](https://support.microsoft.com/en-us/help/5012592).

```
python -m test test_contextlib_async test_coroutines test_unittest test_asyncio
```
```
Running Debug|x64 interpreter...
0:00:00 Run tests sequentially
0:00:00 [1/4] test_contextlib_async
Task was destroyed but it is pending!
task: <Task pending name='Task-12' coro=<<async_generator_athrow without __name__>()>>
Task was destroyed but it is pending!
task: <Task pending name='Task-14' coro=<<async_generator_athrow without __name__>()>>
Task was destroyed but it is pending!
task: <Task pending name='Task-23' coro=<<async_generator_athrow without __name__>()>>
0:00:00 [2/4] test_coroutines
C:\Users\Jeremy\Source\cpython\Lib\test\test_coroutines.py:2207: RuntimeWarning: coroutine 'CoroutineTest.test_bpo_45813_2.<locals>.f' was never awaited
  with self.assertWarns(RuntimeWarning):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
0:00:00 [3/4] test_unittest
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\case.py", line 552, in _callTearDown
    self.tearDown()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\test\test_async_case.py", line 26, in tearDown
    support.gc_collect()
  File "C:\Users\Jeremy\Source\cpython\Lib\test\support\__init__.py", line 729, in gc_collect
    gc.collect()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\async_case.py", line 118, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\async_case.py", line 102, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\runners.py", line 71, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] The parameter is incorrect
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\case.py", line 552, in _callTearDown
    self.tearDown()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\test\test_async_case.py", line 26, in tearDown
    support.gc_collect()
  File "C:\Users\Jeremy\Source\cpython\Lib\test\support\__init__.py", line 729, in gc_collect
    gc.collect()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\async_case.py", line 118, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\async_case.py", line 102, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\runners.py", line 71, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] The parameter is incorrect
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\case.py", line 552, in _callTearDown
    self.tearDown()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\test\test_async_case.py", line 26, in tearDown
    support.gc_collect()
  File "C:\Users\Jeremy\Source\cpython\Lib\test\support\__init__.py", line 729, in gc_collect
    gc.collect()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\async_case.py", line 118, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\async_case.py", line 102, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\runners.py", line 71, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] The parameter is incorrect
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\case.py", line 552, in _callTearDown
    self.tearDown()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\test\test_async_case.py", line 26, in tearDown
    support.gc_collect()
  File "C:\Users\Jeremy\Source\cpython\Lib\test\support\__init__.py", line 729, in gc_collect
    gc.collect()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\async_case.py", line 118, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\async_case.py", line 102, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\runners.py", line 71, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] The parameter is incorrect
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\case.py", line 552, in _callTearDown
    self.tearDown()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\test\test_async_case.py", line 26, in tearDown
    support.gc_collect()
  File "C:\Users\Jeremy\Source\cpython\Lib\test\support\__init__.py", line 729, in gc_collect
    gc.collect()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\async_case.py", line 118, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\Jeremy\Source\cpython\Lib\unittest\async_case.py", line 102, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\runners.py", line 71, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] The parameter is incorrect
0:00:06 [4/4] test_asyncio
Exception in callback interrupt_self() at C:\Users\Jeremy\Source\cpython\Lib\test\test_asyncio\test_runners.py:17
handle: <TimerHandle when=2796.928 interrupt_self() at C:\Users\Jeremy\Source\cpython\Lib\test\test_asyncio\test_runners.py:17>
Traceback (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\test\test_asyncio\test_runners.py", line 18, in interrupt_self
    _thread.interrupt_main()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\runners.py", line 140, in _on_sigint
    self._loop.call_soon_threadsafe(lambda: None)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\base_events.py", line 809, in call_soon_threadsafe
    self._write_to_self()
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\base_events.py", line 511, in _write_to_self
    raise NotImplementedError
    ^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError
Task exception was never retrieved
future: <Task finished name='Task-1725' coro=<RunnerTests.test_interrupt_cancelled_task.<locals>.subtask() done, defined at C:\Users\Jeremy\Source\cpython\Lib\test\test_asyncio\test_runners.py:365> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\test\test_asyncio\test_runners.py", line 368, in subtask
    interrupt_self()
    ^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\test\test_asyncio\test_runners.py", line 18, in interrupt_self
    _thread.interrupt_main()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\runners.py", line 140, in _on_sigint
    self._loop.call_soon_threadsafe(lambda: None)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\base_events.py", line 809, in call_soon_threadsafe
    self._write_to_self()
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\base_events.py", line 511, in _write_to_self
    raise NotImplementedError
    ^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError
Exception in callback interrupt_self() at C:\Users\Jeremy\Source\cpython\Lib\test\test_asyncio\test_runners.py:17
handle: <TimerHandle when=2797.0209999999997 interrupt_self() at C:\Users\Jeremy\Source\cpython\Lib\test\test_asyncio\test_runners.py:17>
Traceback (most recent call last):
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\test\test_asyncio\test_runners.py", line 18, in interrupt_self
    _thread.interrupt_main()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\runners.py", line 140, in _on_sigint
    self._loop.call_soon_threadsafe(lambda: None)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\base_events.py", line 809, in call_soon_threadsafe
    self._write_to_self()
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeremy\Source\cpython\Lib\asyncio\base_events.py", line 511, in _write_to_self
    raise NotImplementedError
    ^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError
test_asyncio passed in 1 min 15 sec

== Tests result: SUCCESS ==

All 4 tests OK.

Total duration: 1 min 21 sec
Tests result: SUCCESS
```

**Comment by jkloth** [comment]
Also note that this extraneous output is **NOT** reflected in the buildbot output logs. :(  However, testing locally on my buildbot does produce these messages in the Terminal.

**Comment by kumaraditya303** [comment]
@jkloth Is this still an issue? Can you try the current main branch ?

**Comment by kumaraditya303** [comment]
Closing because of no response.
