### ISSUE TITLE
sre_parse.py

### ISSUE THREAD

**Issue by tfox72** [python/cpython#92057]
After the recent commits to this package when initializing Jupyter Lab I keep getting the following errors?

![image](https://user-images.githubusercontent.com/14864902/166076533-96f5472b-9ee2-4b52-92c5-e4eaf577fd50.png)

**Comment by sweeneyde** [comment]
Please copy-paste the full traceback, instead of posting images.

**Comment by rhettinger** [comment]
An erronenous ``\P`` in regex used to be ignored in Python 3.3, but started being reported as an error by Python 3.6.

The pattern needs to be fixed.  Without the full traceback, we can't tell if the root cause is in the standard library (not likely) or in a third-party module (likely).

**Comment by tfox72** [comment]
(notify) C:\>jupyter lab
[W 2022-04-29 15:14:24.957 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-04-29 15:14:24.972 LabApp] 'browser' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-04-29 15:14:24.972 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-04-29 15:14:24.979 ServerApp] notebook_dir is deprecated, use root_dir
[I 2022-04-29 15:14:24.979 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-04-29 15:14:24.979 ServerApp] nbclassic | extension was successfully linked.
[I 2022-04-29 15:14:25.480 ServerApp] notebook_shim | extension was successfully linked.
Traceback (most recent call last):
  File "C:\Users\tef0\Anaconda3\envs\notify\Scripts\jupyter-lab-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\site-packages\jupyter_server\extension\application.py", line 584, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\site-packages\jupyter_server\extension\application.py", line 554, in initialize_server
    serverapp.initialize(
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\site-packages\traitlets\config\application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\site-packages\jupyter_server\serverapp.py", line 2414, in initialize
    self.init_webapp()
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\site-packages\jupyter_server\serverapp.py", line 1904, in init_webapp
    self.web_app = ServerWebApplication(
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\site-packages\jupyter_server\serverapp.py", line 251, in __init__
    super().__init__(handlers, **settings)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\site-packages\tornado\web.py", line 2078, in __init__
    self.wildcard_router = _ApplicationRouter(self, handlers)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\site-packages\tornado\web.py", line 1926, in __init__
    super().__init__(rules)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\site-packages\tornado\routing.py", line 414, in __init__
    super().__init__(rules)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\site-packages\tornado\routing.py", line 332, in __init__
    self.add_rules(rules)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\site-packages\tornado\routing.py", line 344, in add_rules
    rule = Rule(PathMatches(rule[0]), *rule[1:])
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\site-packages\tornado\routing.py", line 559, in __init__
    self.regex = re.compile(path_pattern)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\re.py", line 252, in compile
    return _compile(pattern, flags)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\sre_parse.py", line 525, in _parse
    code = _escape(source, this, state)
  File "C:\Users\tef0\Anaconda3\envs\notify\lib\sre_parse.py", line 426, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \P at position 3

**Comment by tfox72** [comment]
> An erronenous `\P` in regex used to be ignored in Python 3.3, but started being reported as an error by Python 3.6.
> 
> The pattern needs to be fixed. Without the full traceback, we can't tell if the root cause is in the standard library (not likely) or in a third-party module (likely).

Was away from the computer all weekend, above is the full traceback.

**Comment by rhettinger** [comment]
It looks like this is upstream from the standard library.

**Comment by serhiy-storchaka** [comment]
There may be two cause of such error:
1. You use non-escaped Windows path like `C:\Program Files` in the regular expression.
2. You are trying to use the syntax for negative Unicode property (`\P`) in the regular expression. It is supported by the `regex` package and some other RE engines, but not in the `re` module yet.

The first cause is more likely, and the error is raised to save you from bugs when support of `\P` will be added in `re`. In any case the error is in your code or in the code of Jupiter or one of its extension, but not in the code of Tornado or the stdlib.
