### ISSUE TITLE
`inspect.getfile` doesn't properly handle PEP 420

### ISSUE THREAD

**Issue by TheTechRobo** [python/cpython#92525]
**Bug report**

`inspect.getfile` handles all `__file__ is None` modules as built-in. Cf. https://github.com/python/cpython/blob/f298ba1f2712ad10530a30bb225548a6889820b5/Lib/inspect.py#L898-L901

This leads to PEP 420 packages being treated as built-in, as implicit namespaces have __file__ set to None, but `__path__` set to the actual path.

Creating PEP 420 directory:

```bash
~ ❯❯❯ mkdir python_test
~ ❯❯❯ vim python_test/hello.py
```

Python interpreter

```
Python 3.9.7 (default, Oct 10 2021, 14:08:54)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import python_test
>>> import inspect
>>> inspect.getfile(python_test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python-3.9.7/lib/python3.9/inspect.py", line 660, in getfile
    raise TypeError('{!r} is a built-in module'.format(object))
TypeError: <module 'python_test' (namespace)> is a built-in module
>>> print(python_test.__file__)
None
>>> print(python_test.__path__)
_NamespacePath(['/home/thetechrobo/python_test'])
```

**Your environment**

- CPython versions tested on: 3.9.7
- Operating system and architecture: Elive Linux 3.8.27 64-bit (Debian Bullseye); custom Python installation

Apologies if this is a duplicate. I've searched for any related issues, but I may have missed one.

### Linked PRs
* gh-92635

**Comment by serhiy-storchaka** [comment]
What are you going to do with the result? You cannot open a file, and `inspect.getsource()` will still fail.

**Comment by TheTechRobo** [comment]
@serhiy-storchaka I tried to use it for debugging, trying to figure out where the package was being imported from. The error message is currently wrong so it is a pretty annoying issue.
