### ISSUE TITLE
urllib.request.urlopen(data_uri).file are closed automatically when the response is not hold by a variable

### ISSUE THREAD

**Issue by maple3142** [python/cpython#92713]
**Bug report**

Opening a data uri with `urllib.request.urlopen` and read it directly will result in `I/O operation on closed file.`.

Errored example:

```python
from urllib.request import urlopen

url = 'data:text/plain,hello world'
print(urlopen(url).file.read())

"""
Output:

Traceback (most recent call last):
  File "/home/maple3142/tmp/xa.py", line 4, in <module>
    print(urlopen(url).file.read())
ValueError: I/O operation on closed file.
"""
```

Normal example:

```python
from urllib.request import urlopen

url = 'data:text/plain,hello world'
resp = urlopen(url)
print(resp.file.read())

"""
Output:

b'hello world'
"""
```

**Your environment**

- CPython versions tested on: 3.8.11, 3.10.4
- Operating system and architecture: Arch Linux on WSL2 on Windows 10 x64

**Comment by tgbv** [comment]
On my side, both examples work as expected on Windows 10 x64, Python 3.10.4

**Comment by maple3142** [comment]
```python
from urllib.request import urlopen

url = 'data:text/plain,hello world'
resp = urlopen(url)
# print(resp.file.read())
f = resp.file
print(resp)
print(f.closed)
del resp
print(f.closed)
print(f.read())
```

and output:

```
<addinfourl at 139752443554848 whose fp = <_io.BytesIO object at 0x7f1aa6a756c0>>
False
True
Traceback (most recent call last):
  File "/home/maple3142/tmp/xb.py", line 11, in <module>
    print(f.read())
ValueError: I/O operation on closed file.
```

This probably have something to do with reference counting causing temporary file to be closed, but I am not sure where to look for this. https://github.com/python/cpython/blob/2cd70ffb3fe22d778d0bb6ec220fdf67dccc1be6/Lib/urllib/response.py looks pretty normal

**Comment by maple3142** [comment]
This bug still exist in Python 3.11, 3.12 .

I think it is because when the reference to `addinfourl` (which extends [`_TemporaryFileWrapper`](https://github.com/python/cpython/blob/3.12/Lib/tempfile.py#L459) so it also holds a reference to [`_TemporaryFileCloser`](https://github.com/python/cpython/blob/3.12/Lib/tempfile.py#L416) )  got lost, which triggered `_TemporaryFileCloser.__del__`.

A hacky fix is to prevent `_TemporaryFileCloser` from automatically closing the file by deleting its `__del__`:

```python
from tempfile import _TemporaryFileCloser

del _TemporaryFileCloser.__del__
```

but I am not sure how to fix this properly. Perhaps `_TemporaryFileWrapper.file` and `_TemporaryFileWrapper._closer` should be merged together somehow?

**Comment by maple3142** [comment]
Similar cases that also caused by the same problem:

```python
from tempfile import NamedTemporaryFile

NamedTemporaryFile().file.read()
```

This is a lot more unlikely to happen because such operation make no sense. On the other way, the `urlopen(...).file.read()` does not seem so bad. (but `urlopen(...).read()` should be preferred)

Currently, they are only two users of `_TemporaryFileCloser` in CPython's codebase: `class addinfourl` (return value of `urlopen`) and `NamedTemporaryFile`.
