### ISSUE TITLE
hashlib should probably load "default" OpenSSL provider on OpenSSL 3.x explicitly

### ISSUE THREAD

**Issue by mgorny** [python/cpython#92876]
**Bug report**

FWIU OpenSSL 3.x disables loading the `default` provider automatically if one loads a provider explicitly before calling any MD-related function. Since `hashlib` normally relies on the MDs provided by the `default` OpenSSL provider, perhaps it should load them explicitly to ensure that they are present. This would also ensure that the loaded OpenSSL providers are consistent whether `hashlib` is loaded prior to the script loading other providers or not.

By default:

```python
>>> import hashlib
>>> sorted(hashlib.algorithms_available)
['blake2b', 'blake2s', 'md5', 'md5-sha1', 'sha1', 'sha224', 'sha256', 'sha384', 'sha3_224', 'sha3_256', 'sha3_384', 'sha3_512', 'sha512', 'sha512_224', 'sha512_256', 'shake_128', 'shake_256', 'sm3']
>>> hashlib.new("sha512_256")
<sha512_256 _hashlib.HASH object @ 0x7fcccbff2c50>
```

But if I load the `legacy` provider first:
```python
>>> import ctypes
>>> ctypes.CDLL("libssl.so").OSSL_PROVIDER_load(None, b"legacy")
-1589238480
>>> import hashlib
>>> sorted(hashlib.algorithms_available)
['blake2b', 'blake2s', 'md4', 'md5', 'mdc2', 'ripemd160', 'sha1', 'sha224', 'sha256', 'sha384', 'sha3_224', 'sha3_256', 'sha3_384', 'sha3_512', 'sha512', 'shake_128', 'shake_256', 'whirlpool']
>>> hashlib.new("sha512_256")
Traceback (most recent call last):
  File "/usr/lib/python3.11/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: unsupported hash type sha512_256
>>> import _hashlib
>>> _hashlib.openssl_md_meth_names
frozenset({'whirlpool', 'ripemd160', 'mdc2', 'md4'})
```

but if I load both `default` and `legacy` providers, I get the full set:

```python
>>> import ctypes
>>> ctypes.CDLL("libssl.so").OSSL_PROVIDER_load(None, b"legacy")
-265107616
>>> ctypes.CDLL("libssl.so").OSSL_PROVIDER_load(None, b"default")
-265087936
>>> import hashlib
>>> sorted(hashlib.algorithms_available)
['blake2b', 'blake2s', 'md4', 'md5', 'md5-sha1', 'mdc2', 'ripemd160', 'sha1', 'sha224', 'sha256', 'sha384', 'sha3_224', 'sha3_256', 'sha3_384', 'sha3_512', 'sha512', 'sha512_224', 'sha512_256', 'shake_128', 'shake_256', 'sm3', 'whirlpool']
>>> hashlib.new("sha512_256")
<sha512_256 _hashlib.HASH object @ 0x7ffb1937f6b0>
>>> import _hashlib
>>> _hashlib.openssl_md_meth_names
frozenset({'sha512_256', 'sha3_512', 'sm3', 'sha512_224', 'sha1', 'md5', 'mdc2', 'sha3_256', 'blake2s', 'ripemd160', 'sha3_224', 'sha256', 'whirlpool', 'sha3_384', 'sha384', 'sha224', 'sha512', 'shake_256', 'md5-sha1', 'blake2b', 'md4', 'shake_128'})
```

**Your environment**

- CPython versions tested on: 3.11.0b1
- Operating system and architecture: Gentoo Linux amd64
- OpenSSL version: 3.0.3

**Comment by tomato42** [comment]
On the other hand, if the system in in FIPS mode, lack of default provider may instead be conscious and deliberate action by the system administrator.

Necessity to explicitly load both default and legacy providers if you want to use legacy algorithms is a deliberate choice by openssl.

**Comment by h-vetinari** [comment]
I don't think FIPS mode should be a concern here. I doubt that python itself can run (unmodified) in a FIPS environment, and the vast, vast majority of users are not affected by rules for USG agencies and contractors.

Said otherwise, someone trying to use this in a FIPS environment will have bigger issues than whether the legacy provider is loaded (which wouldn't be present on their system anyway). While it could ostensibly be wrapped with a `try:/except:` or a config knob, the default should surely be to load the legacy provider.

**Comment by tomato42** [comment]
1. FIPS is just an example of a most popular configuration where you are not using the `default` provider, there definitely be others too
2. Even if there are industries which do not have a legal requirement to be running FIPS certified software, they may still choose to do so because of other reasons (e.g. banking)
3. > someone trying to use this in a FIPS environment will have bigger issues
   
   Python already has interfaces for working in FIPS-like environments, that's what [`usedforsecurity`](https://docs.python.org/3/library/hashlib.html#hashlib.new) is for
4. >  legacy provider is loaded (which wouldn't be present on their system anyway)
    
    Not true, what's in scope of FIPS is protection of user data. If a cryptographic implementation isn't used for that, then FIPS doesn't care about it. You totally can use legacy provider when the system is in FIPS mode.

**Comment by thesamesam** [comment]
In any case, an easy way to load it would be nice, even if it's not default in Python.

**Comment by gpshead** [comment]
If algorithms are not provided at all in usedforsecurity=False mode by OpenSSL, hashlib falls back to our built-ins: https://github.com/python/cpython/blob/main/Lib/hashlib.py#L126-L141 per `__get_openssl_constructor()`

**Comment by gpshead** [comment]
If there are openssl providers people configure via whatever means rather than whatever a "default" was for the past 20 years that, for example, do not provide sha1 and md5 at all, hashlib will quite happily do its job and provide those itself. This is working as intended as far as I'm concerned.

**Comment by faelin** [comment]
> I doubt that python itself can run (unmodified) in a FIPS environment, and the vast, vast majority of users are not affected by rules for USG agencies and contractors.

I run Python 2 and Python 3 everyday in a FIPS environment with no problem.

Use of the builtin hashlib currently generates an error for me:
```
'import sitecustomize' failed; use -v for traceback
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/pub/python-2.7.9/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/pub/python-2.7.9/lib/python2.7/hashlib.py", line 109, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/pub/python-2.7.9/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
<module 'hashlib' from '/pub/python-2.7.9/lib/python2.7/hashlib.pyc'>
```

This is particularly annoying, since I do not have permissions to modify the installed module (spssaux) that utilizes the hashlib module, so I provide the `usedforsecurity` constructor argument that would bypass the error.

**Comment by h-vetinari** [comment]
It's pretty ironic to use FIPS-approved cryptography on python 2.7.9 (>10 years old), which has about 20 CVEs compared to 2.7.18, itself already unmaintained for almost 5 years.

**Comment by faelin** [comment]
> It's pretty ironic to use FIPS-approved cryptography on python 2.7.9 (>10 years old), which has about 20 CVEs compared to 2.7.18, itself already unmaintained for almost 5 years.

Oh yeah, definitely! Who's doing that...? That would be super foolish!

The good news is, cryptography has nothing to do with the error I noted above. The hashlib library is actually used for a bunch of non-cryptographic contexts including, of all things, the `random` library that comes bundled with Python. Which is what leads to the error I shared above. Or rather, the IBM `spss` package, which utilizes the `random` library, which in turn uses the `hashlib` library to generate "interesting" random numbers (https://github.com/python/cpython/blob/8d21aa21f2cbc6d50aab3f420bb23be1d081dac4/Lib/random.py#L158)

As for why Python 2.7.9 on a FIPS-compliant machine, well, the org I work for maintains some heinously old scripts that were never updated for Python3, which are run on servers that are required to run in FIPS mode, due to government contracts. Trust me, I am well aware of the irony, but the FIPS mode is enforced at the administrative level, during OS installation, so the age/context of the software we run has no bearing on whether the MD5 hash algo is available or not. And of course we're never allocated adequate time to update our outdated scripts... -_-

**Comment by encukou** [comment]
I agree with Greg that hashlib is working as intended.

IMO, if you configure OpenSSL in a way that breaks Python, I'd consider that an active choice to block some functionality. CPython can't guarantee that such a setting will have an effect, but it also shouldn't go out of its way to override it.

Greg, can we close this?
