### ISSUE TITLE
test_launcher fails on the ARM64 Windows Non-Debug Azure 3.x buildbot

### ISSUE THREAD

**Issue by vstinner** [python/cpython#93005]
test_launcher fails on the ARM64 Windows Non-Debug Azure 3.x buildbot:
https://buildbot.python.org/all/#/builders/897/builds/322

The failure may be caused by https://github.com/python/cpython/commit/73473fdeac3ff9d75ac9d189bb8552b7459812f1

```
0:14:26 Re-running test_launcher in verbose mode (matching: test_virtualenv_with_env)
test_virtualenv_with_env (test.test_launcher.TestLauncher.test_virtualenv_with_env) ... FAIL
Stdout:
++ COMMAND ++
[WindowsPath('C:/Workspace/buildarea/3.x.linaro2-win-arm64.nondebug/build/PCbuild/arm64/py.exe'), '-3']
++ STDOUT ++
++ STDERR ++
argv0: C:\Workspace\buildarea\3.x.linaro2-win-arm64.nondebug\build\PCbuild\arm64\py.exe
version: 3.12.0a0
# Reading from C:\Users\tcwg\AppData\Local\py.ini for defaults/py_python3
# Did not find file C:\Users\tcwg\AppData\Local\py.ini
# Reading from C:\Workspace\buildarea\3.x.linaro2-win-arm64.nondebug\build\PCbuild\arm64\py.ini for defaults/py_python3
# Did not find file C:\Workspace\buildarea\3.x.linaro2-win-arm64.nondebug\build\PCbuild\arm64\py.ini
SearchInfo.originalCmdLine: C:\Workspace\buildarea\3.x.linaro2-win-arm64.nondebug\build\PCbuild\arm64\py.exe -3
SearchInfo.restOfCmdLine: 
SearchInfo.executablePath: (null)
SearchInfo.scriptFile: (null)
SearchInfo.executable: python.exe
SearchInfo.executableArgs: (null)
SearchInfo.company: (null)
SearchInfo.tag: 3
SearchInfo.oldStyleTag: True
SearchInfo.lowPriorityTag: False
SearchInfo.exclude32Bit: False
SearchInfo.only32Bit: False
SearchInfo.allowDefaults: True
SearchInfo.allowExecutableOverride: True
SearchInfo.windowed: False
SearchInfo.list: False
SearchInfo.listPaths: False
SearchInfo.help: False
# PythonTestSuite/ignored has no executable path
 -V:ContinuumAnalytics/Anaconda39-64 C:\wenv\x64_vs2022\conda\python.exe
 -V:PythonTestSuite/3.100 X.Y.exe
 -V:PythonTestSuite/3.100-32 X.Y-32.exe
 -V:PythonTestSuite/3.100-arm64 X.Y-arm64.exe -X fake_arg_for_test
No suitable Python runtime found
Pass --list (-0) to see all detected environments on your machine
or set environment variable PYLAUNCHER_ALLOW_INSTALL to use winget
or open the Microsoft Store to the requested version.
======================================================================
FAIL: test_virtualenv_with_env (test.test_launcher.TestLauncher.test_virtualenv_with_env)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Workspace\buildarea\3.x.linaro2-win-arm64.nondebug\build\Lib\test\test_launcher.py", line 487, in test_virtualenv_with_env
    data2 = self.run_py(["-3"], env={**env, "PY_PYTHON": "-3"})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Workspace\buildarea\3.x.linaro2-win-arm64.nondebug\build\Lib\test\test_launcher.py", line 223, in run_py
    self.assertEqual(expect_returncode, p.returncode)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 0 != 103
Stdout:
++ COMMAND ++
[WindowsPath('C:/Workspace/buildarea/3.x.linaro2-win-arm64.nondebug/build/PCbuild/arm64/py.exe'), '-3']
++ STDOUT ++
++ STDERR ++
argv0: C:\Workspace\buildarea\3.x.linaro2-win-arm64.nondebug\build\PCbuild\arm64\py.exe
version: 3.12.0a0
# Reading from C:\Users\tcwg\AppData\Local\py.ini for defaults/py_python3
# Did not find file C:\Users\tcwg\AppData\Local\py.ini
# Reading from C:\Workspace\buildarea\3.x.linaro2-win-arm64.nondebug\build\PCbuild\arm64\py.ini for defaults/py_python3
# Did not find file C:\Workspace\buildarea\3.x.linaro2-win-arm64.nondebug\build\PCbuild\arm64\py.ini
SearchInfo.originalCmdLine: C:\Workspace\buildarea\3.x.linaro2-win-arm64.nondebug\build\PCbuild\arm64\py.exe -3
SearchInfo.restOfCmdLine: 
SearchInfo.executablePath: (null)
SearchInfo.scriptFile: (null)
SearchInfo.executable: python.exe
SearchInfo.executableArgs: (null)
SearchInfo.company: (null)
SearchInfo.tag: 3
SearchInfo.oldStyleTag: True
SearchInfo.lowPriorityTag: False
SearchInfo.exclude32Bit: False
SearchInfo.only32Bit: False
SearchInfo.allowDefaults: True
SearchInfo.allowExecutableOverride: True
SearchInfo.windowed: False
SearchInfo.list: False
SearchInfo.listPaths: False
SearchInfo.help: False
# PythonTestSuite/ignored has no executable path
 -V:ContinuumAnalytics/Anaconda39-64 C:\wenv\x64_vs2022\conda\python.exe
 -V:PythonTestSuite/3.100 X.Y.exe
 -V:PythonTestSuite/3.100-32 X.Y-32.exe
 -V:PythonTestSuite/3.100-arm64 X.Y-arm64.exe -X fake_arg_for_test
No suitable Python runtime found
Pass --list (-0) to see all detected environments on your machine
or set environment variable PYLAUNCHER_ALLOW_INSTALL to use winget
or open the Microsoft Store to the requested version.
```

**Comment by zooba** [comment]
Ah, the test relies on there being an existing install. I'll fix it

**Comment by zooba** [comment]
PR is good to merge, but I'll be AFK, probably until Monday. Feel free to merge it whenever CI is done

**Comment by neonene** [comment]
The buildbots still have the issue. Passing `"-3"` to py.exe, it exits with `RC_NO_PYTHON` (103) from `launcher2.c/_selectEnvironment()`, after searching an environment variable then `py.ini` for `"py_python3"` at `checkDefaults()`.

**Comment by zooba** [comment]
You're right, I made half the fix but not all of the fix...
