### ISSUE TITLE
asyncio.gather behaves inconsistently when handling KeyboardInterruption/SystemExit

### ISSUE THREAD

**Issue by HFrost0** [python/cpython#93122]
**Bug report**

Here is a minimal example:

```python
import asyncio

e = KeyboardInterrupt  # or SystemExit


async def main_task():
    await asyncio.gather(
        sub_task(),
    )


async def sub_task():
    raise e


if __name__ == '__main__':
    try:
        asyncio.run(main_task())
    except e:
        print(f'Handle {e}')
```

This code handles the Interrupt normally as I expected.

```
Handle <class 'KeyboardInterrupt'>

Process finished with exit code 0
```

But when I add the `asyncio.sleep(0)` (can be replaced by other task, not important) into `main_task`'s `asyncio.gather`

```python
import asyncio

e = KeyboardInterrupt  # or SystemExit


async def main_task():
    await asyncio.gather(
        sub_task(),
        asyncio.sleep(0)
    )


async def sub_task():
    raise e


if __name__ == '__main__':
    try:
        asyncio.run(main_task())
    except e:
        print(f'Handle {e}')
```

There is an unexpected traceback print out which is really confusing 💦, this traceback indicates that there is
**another** KeyboardInterrupt raised.

<details>
<summary>Full traceback</summary>

```
Traceback (most recent call last):
  File "/Users/huanghuiling/PycharmProjects/Lighting-bilibili-download/tests/log_test.py", line 45, in <module>
    asyncio.run(main_task())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test9/lib/python3.9/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test9/lib/python3.9/asyncio/runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/huanghuiling/PycharmProjects/Lighting-bilibili-download/tests/log_test.py", line 7, in main_task
    await asyncio.gather(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/huanghuiling/PycharmProjects/Lighting-bilibili-download/tests/log_test.py", line 14, in sub_task
    raise e
KeyboardInterrupt

Process finished with exit code 0
```

</details>

So I go deeply into the `asyncio.run`, and write code (a simplified `asyncio.run`) below to figure out what happen.

```python
import asyncio

e = KeyboardInterrupt  # or SystemExit


async def main_task():
    await asyncio.gather(
        sub_task(),
        asyncio.sleep(0)
    )


async def sub_task():
    raise e


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(main_task())
    except e:
        print(f'Expected {e}')
    finally:
        try:
            tasks = asyncio.all_tasks(loop)
            for t in tasks:
                t.cancel()
            # ⬇️ this line will raise another KeyboardInterrupt which is unexpected ⬇️ 
            loop.run_until_complete(asyncio.gather(*tasks, return_exceptions=True))
        except e:
            print(f'Unexpected {e} !!!!')
```

This line will raise another KeyboardInterrupt which is unexpected.

```python
loop.run_until_complete(asyncio.gather(*tasks, return_exceptions=True))
```

```
Expected <class 'KeyboardInterrupt'>
Unexpected <class 'KeyboardInterrupt'> !!!!

Process finished with exit code 0
```

Note that this line is used to cancel all tasks during gracefully shutdown (also in `asyncio.run`), and when I change
`e` to other error like `IndexError`(any `BaseException`), this code works fine without unexpected another exception.
I believe this is related to the `asyncio` treats `SystemExit` and `KeyboardInterrupt` in different way. For example
in `events.py`

```python
def _run(self):
    try:
        self._context.run(self._callback, *self._args)
    except (SystemExit, KeyboardInterrupt):
        raise
    except BaseException as exc:
        cb = format_helpers._format_callback_source(
            self._callback, self._args)
        msg = f'Exception in callback {cb}'
        context = {
            'message': msg,
            'exception': exc,
            'handle': self,
        }
        if self._source_traceback:
            context['source_traceback'] = self._source_traceback
        self._loop.call_exception_handler(context)
    self = None  # Needed to break cycles when an exception occurs.
```

My question is:

1. Why `asyncio.gather` behaves inconsistently.
2. Is there any reason to treat `KeyboardInterrupt` differently, since the simplest way
   to solve this bug is to handle it same as `BaseException`.

I think user would like to handle all error consistently during the running of a task whether
it's `KeyboardInterrupt` or `BaseException`.

Even `asyncio` treats them in different way (incase really necessary)

```
asyncio.gather(sub_task())
```

and

```
asyncio.gather(sub_task(), asyncio.sleep(0))
```

should behave consistently, so I think this is a bug in asyncio.

**Your environment**

- CPython versions tested on: 3.8, 3.9, 3.10
- Operating system and architecture: both macOS and windows

**Comment by kumaraditya303** [comment]
Can you test 3.11 and main branch as the signal handling was changed recently ?

**Comment by HFrost0** [comment]
> Can you test 3.11 and main branch as the signal handling was changed recently ?

@kumaraditya303 I have tested on docker [3.11.0b1-bullseye](https://github.com/docker-library/python/blob/25889dfdc59ca946c04af98c6a82e63bd97680d3/3.11-rc/bullseye/Dockerfile), but still got the same problem.

**Comment by YvesDup** [comment]
The traceback message appears at the end of the script after the last line of `__name__ == __main__` block.
This is bout the  `main_task`coroutine: Task exception was never retrieved

So I tried to cancel this current task when exception raises, updating your `main_task` coroutine as below:

```py
async def main_task():
    try:
        r = await asyncio.gather(sub_task(), asyncio.sleep(1))

    except (SystemExit, KeyboardInterrupt): 
        # cancel current task
       asyncio.current_task().cancel()

        # give time to other tasks to run (including me)
        await asyncio.sleep(0)
        raise

    except:
        raise
```
I don't really figure out in detail why but now the traceback message does not appear. 
I suppose that other tasks run updating their internal state. This is including the current task `main_wait`.
And may be some loop flags are updated too.

I wonder whether something is not missing in `except (SystemExit, KeyboardInterrupt):' part of the `def _run(self)`method ?

I'd like to understand too.

**Comment by HFrost0** [comment]
In your case
```python
import asyncio

e = IndexError  # or SystemExit


async def main_task():
    try:
        r = await asyncio.gather(sub_task(), asyncio.sleep(1))

    except (SystemExit, KeyboardInterrupt):
        # cancel current task
        asyncio.current_task().cancel()
        # give time to other tasks to run (including me)
        await asyncio.sleep(0)
        print('never reach here')
        raise
    except:
        print('')
        raise


async def sub_task():
    raise e


if __name__ == '__main__':
    try:
        asyncio.run(main_task())
    except e:
        print(f'Handle {e}')

```
There are two independent `KeyboardInterrupt` raised. One in `sub_task` and one in `await asyncio.sleep(0)`. 
```python
print('never reach here')
raise
```
is nerver reached (test by debug). So two try except catch these two interrupt, no traceback anymore, but still very confusing why `await asyncio.sleep(0)` raised another interrupt🥲, or not in sleep but in event loop somewhere, I dont know.

**Comment by HFrost0** [comment]
> `asyncio.sleep(0)` raised `CancelError`cause by `asyncio.current_task().cancel()` the line above Sorry, bad solution and no more explanation.

I'm pretty sure it's not a `CancelError` but a `KeyboradInterrupt`.

**Comment by YvesDup** [comment]
Hi @HFrost0 
I checked the documentation on [`asyncio.gather`](https://docs.python.org/3/library/asyncio-task.html#asyncio.gather) and there is nothing about the `keyboardError` exception. Before opening a PR, I think it would be a good idea to send a message to [python-dev](https://mail.python.org/archives/list/python-dev@python.org/) asking what the behavior of `asyncio.gather` is when a `KeyboardError` is raised.
 
 IMO there is also another gap in the documentation about what happens when two or more exceptions raise in tasks.

**Comment by HFrost0** [comment]
Hi @YvesDup 
Agree, but I'm a little bit busy right now and not familiar with [python-dev](https://mail.python.org/archives/list/python-dev@python.org/). Could you send this message please?

**Comment by YvesDup** [comment]
```py
async def main_task():
    try:
        await asyncio.gather(
            sub_task(),
            asyncio.sleep(0)
        )
    except BaseException as e:
        print(repr(e))
```
if you catch the exception in the `main_task()` coroutine, there is no more error with one or two tasks.

**Comment by HFrost0** [comment]
Any update for this?

**Comment by tfarago** [comment]
I'd like to chip in, hope it's fine. With `wait` one gets rid of the unexpected exception (run the excerpt below, change `use_gather` to `True` for the old behavior), although to make the code run without the additional "Task exception was never retrieved" it gets a bit messy. One could also change the `ALL_COMPLETED`, which simulates the behavior of `gather` to `FIRST_EXCEPTION` and then the task creations and retrieving their exceptions all goes away, however, one would need to iterate and make sure pending tasks are finished, but that's another topic.

```python
import asyncio

e = KeyboardInterrupt  # or SystemExit


async def main_task(use_gather=True):
    loop = asyncio.get_running_loop()

    tasks = [loop.create_task(sub_task()), loop.create_task(asyncio.sleep(0))]

    try:
        if use_gather:
            await asyncio.gather(*tasks)
        else:
            await asyncio.wait(tasks, return_when=asyncio.ALL_COMPLETED)
    except:
        for t in tasks:
            try:
                # Prevent "Task exception was never retrieved"
                t.exception()
            except:
                pass
        raise


async def sub_task():
    raise e


if __name__ == '__main__':
    try:
        asyncio.run(main_task(use_gather=False))
    except e:
        print(f'Handle {e}')
```

I also bumped into the same problem as the `never reach here` above, an example and the `wait`-based solution can be found in my [gist](https://gist.github.com/tfarago/389d4960cf405cdd0ea166471f760f03).

I think `except` and `finally` blocks not running through is a serious issue which should be addressed and before it's solved the documentation should warn about this.

**Comment by willingc** [comment]
This would be a good issue for triagers to test the current behavior and document here.

**Comment by anton-ryzhov** [comment]
I've also stumbled upon it the same or similar bug. In my case after `SystemExit` the `IOLoop` became broken and didn't allow other tasks to finish their work gracefully.

I was debugging that using [relatively fresh version](https://github.com/python/cpython/tree/5fe139cc39fb8110b3d6cbed6224d7c8f5d91987) and found [this block](https://github.com/python/cpython/blob/5fe139cc39fb8110b3d6cbed6224d7c8f5d91987/Lib/asyncio/tasks.py#L303-L305) that already looks incorrect — the code "saves" the exception to "handle it later" (`set_exception`) and same time re-raises it right now. That exactly doubles the same exception in cases mentioned above.

That causes that issue with [this part of code](https://github.com/python/cpython/blob/5fe139cc39fb8110b3d6cbed6224d7c8f5d91987/Lib/asyncio/events.py#L92-L96) — the `IOLoop` and its `Handle`s don't catch these two errors and just reraise them transparently all the way up to `run_until_complete` or `run_forever` or so.
These exceptions stops the IOLoop abruptly here and now.

Then in case of `asyncio.run` use, it tries to gracefully [cancel](https://github.com/python/cpython/blob/5fe139cc39fb8110b3d6cbed6224d7c8f5d91987/Lib/asyncio/runners.py#L62-L71) [all tasks](https://github.com/python/cpython/blob/5fe139cc39fb8110b3d6cbed6224d7c8f5d91987/Lib/asyncio/runners.py#L212-L215). It cancels all the tasks and reruns the IOLoop to let them handle cancellation and exit. But here the copy of the original exception (the `set_exception()` branch) is re-reraised and immediately breaks the finalization loop as well.

I've tried to remove one `super().set_exception(exc)` or replace it with `self.cancel()` — these changes look logical to me. But it didn't work nicely, the task was stuck in `cancelling` state and the IOLoop was infinitely waiting for it.

That looks like another bug that was masked with `set_exception() + raise` hack.


I didn't use `asyncio.gather` nor `asyncio.wait` anywhere in my tests, these look irrelevant to the problem

**Comment by YvesDup** [comment]
From your example, when you suggest:

> When I've replaced:
> ```diff
> - await do_raise()
> + task = asyncio.create_task(do_raise())
> ```

You might to wait for the task 

```diff
task = asyncio.create_task(do_raise())
+ await task
```

**Comment by YvesDup** [comment]
> But of course this code is incorrect. But all correct cases cause the issue.

Please, would you provide a simple example that causes the issue as I am a bit lost.
