### ISSUE TITLE
wsgiref validator complaining about no content-type when it is not needed

### ISSUE THREAD

**Issue by calimeroteknik** [python/cpython#93416]
**Bug report**

https://github.com/python/cpython/blob/main/Lib/wsgiref/validate.py#L70 says that it wants to check
> * That no Content-Type is given when there is no content

However, the code's behaviour appears not to match that.

The code notes there was uncertainty: https://github.com/python/cpython/blob/main/Lib/wsgiref/validate.py#L417
But more importantly, its behaviour is a contradiction with the stated objective mentioned above, as I interpret this.
I also cannot see where RFC2616 (which has been obsoleted by others, it would seem) mandates that behaviour.

In the following example, there is no content, and the validator complains about no Content-Type:

```python
#!/usr/bin/env python3

from wsgiref.simple_server import make_server
from wsgiref.validate import validator

def wsgi_callable(environ, start_response):
	start_response('302 Found', [('Location', 'https://example.com/')])
	return [] # same result with None

make_server(host='localhost', port=8080, app=validator(wsgi_callable)).serve_forever()
```

When I make a request with `curl localhost:8080`, this error appears:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python3.10/wsgiref/validate.py", line 181, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/home/calimero/test.py", line 7, in wsgi_callable
    start_response('302 Found', [('Location', 'https://example.com/')])
  File "/usr/lib/python3.10/wsgiref/validate.py", line 172, in start_response_wrapper
    check_content_type(status, headers)
  File "/usr/lib/python3.10/wsgiref/validate.py", line 428, in check_content_type
    assert_(0, "No Content-Type header found in headers (%s)" % headers)
  File "/usr/lib/python3.10/wsgiref/validate.py", line 128, in assert_
    raise AssertionError(*args)
AssertionError: No Content-Type header found in headers ([('Location', 'https://example.com/')])
```

**Your environment**

- CPython version tested on: 3.10.4
- Operating system and architecture: Archlinux x86-64

**Comment by akulakov** [comment]
According to RFC 7231 and 9110 for 302 code:

https://httpwg.org/specs/rfc9110.html#status.302
| The server's response payload usually contains a short hypertext note with a hyperlink to the different URI(s).

The logic in validate.py validates based on response codes only, rather than checking actual body. The intent seems to have been roughly "if response type MAY contain body, it should have Content-Type". This is not specific to 302, but to all response codes.

So the logic seems to align with the intent / design of this function.

It's also not an exception: the next response code, 303, also may contain hyperlink to the URI in the payload.

Also from RFC 7231 and 9110:
|A sender that generates a message containing a payload body SHOULD generate a Content-Type header field in that message unless the intended media type of the enclosed representation is unknown to the sender.

So you are right that these RFCs do not mandate this behaviour, but it doesn't seem necessarily wrong to me.

For practical reasons it seems preferable to always generate Content-Type, so that the client that expects this header to be present as usual, won't break (but they you might argue for the body to also be present if that's the usual case).
