### ISSUE TITLE
`SIGBUS` when running built `python` on amd64 after 00f8fe956491816f03f1cc76bc7ed297cd9c0930 on 3.11 branch (3.11b3)

### ISSUE THREAD

**Issue by thesamesam** [python/cpython#93438]
**Bug report**
```
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/python-3.11.0_beta3 --htmldir=/usr/share/doc/python-3.11.0_beta3/html --libdir=/usr/lib64 ac_cv_header_stropts_h=no --enable-shared --without-static-libpython --enable-ipv6 --infodir=${prefix}/share/info --mandir=${prefix}/share/man --with-computed-gotos --with-dbmliborder=gdbm --with-libc= --enable-loadable-sqlite-extensions --without-ensurepip --with-system-expat --with-system-ffi --with-platlibdir=lib --with-pkg-config=yes --without-lto --disable-optimizations --with-readline=readline
[...]
$ make -j$(nproc)
[...]
$ ./python -c 'from sphinx import search'
Bus error (core dumped)
```

Backtrace:
```
(gdb) r
Starting program: /tmp/cpython/python -c from\ sphinx\ import\ search
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".

Program received signal SIGBUS, Bus error.
PyObject_Hash (v=<unknown at remote 0x7ffff7f30800>) at Objects/object.c:775
775         if (tp->tp_hash != NULL)
(gdb) bt
#0  PyObject_Hash (v=<unknown at remote 0x7ffff7f30800>) at Objects/object.c:775
#1  0x00007ffff7b9bb20 in PyDict_GetItemWithError (
    op={'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", '__package__': '', '__loader__': <type at remote 0x5555555795a0>, '__spec__': <ModuleSpec(name='builtins', loader=<type at remote 0x5555555795a0>, origin='built-in', loader_state=None, submodule_search_locations=None, _uninitialized_submodules=[], _set_fileattr=False, _cached=None) at remote 0x7ffff73cf690>, '__build_class__': <built-in method __build_class__ of module object at remote 0x7ffff73c86d0>, '__import__': <built-in method __import__ of module object at remote 0x7ffff73c86d0>, 'abs': <built-in method abs of module object at remote 0x7ffff73c86d0>, 'all': <built-in method all of module object at remote 0x7ffff73c86d0>, 'any': <built-in method any of module object at remote 0x7ffff73c86d0>, 'ascii': <built-in method ascii of module object at remote 0x7ffff73c86d0>, 'bin': <built-in method bin of module object at remote 0x7ffff73c86d0>, ...(truncated), key=key@entry=<unknown at remote 0x7ffff7f30800>) at Objects/dictobject.c:1783
#2  0x00007ffff7c3f02b in _PyEval_GetBuiltin (name=<unknown at remote 0x7ffff7f30800>) at Python/ceval.c:7122
#3  0x00007ffff6f47b0c in _Pickle_InitState (st=0x7ffff7199ae0) at /tmp/cpython/Modules/_pickle.c:238
#4  PyInit__pickle () at /tmp/cpython/Modules/_pickle.c:7984
#5  0x00007ffff7c67e5e in _PyImport_LoadDynamicModuleWithSpec (
    spec=spec@entry=<ModuleSpec(name='_pickle', loader=<ExtensionFileLoader(name='_pickle', path='/tmp/cpython/build/lib.linux-x86_64-3.11/_pickle.cpython-311-x86_64-linux-gnu.so') at remote 0x7ffff6fa9c50>, origin='/tmp/cpython/build/lib.linux-x86_64-3.11/_pickle.cpython-311-x86_64-linux-gnu.so', loader_state=None, submodule_search_locations=None, _uninitialized_submodules=[], _set_fileattr=True, _cached=None) at remote 0x7ffff6fa8fd0>, fp=fp@entry=0x0) at ./Python/importdl.c:169
#6  0x00007ffff7c64ff5 in _imp_create_dynamic_impl (module=<optimized out>, file=<optimized out>,
    spec=<ModuleSpec(name='_pickle', loader=<ExtensionFileLoader(name='_pickle', path='/tmp/cpython/build/lib.linux-x86_64-3.11/_pickle.cpython-311-x86_64-linux-gnu.so') at remote 0x7ffff6fa9c50>, origin='/tmp/cpython/build/lib.linux-x86_64-3.11/_pickle.cpython-311-x86_64-linux-gnu.so', loader_state=None, submodule_search_locations=None, _uninitialized_submodules=[], _set_fileattr=True, _cached=None) at remote 0x7ffff6fa8fd0>) at Python/import.c:2384
#7  _imp_create_dynamic (module=<optimized out>, args=<optimized out>, nargs=<optimized out>) at Python/clinic/import.c.h:446
#8  0x00007ffff7ba80ee in cfunction_vectorcall_FASTCALL (func=<built-in method create_dynamic of module object at remote 0x7ffff73c9fd0>, args=0x7ffff6f86bd8, nargsf=<optimized out>, kwnames=<optimized out>)
    at Objects/methodobject.c:427
#9  0x00007ffff7b0e0e8 in _PyEval_EvalFrameDefault (tstate=0x7ffff7f30800 <_PyRuntime+36160>, frame=0x7ffff72f5b90, throwflag=-134937672) at Python/ceval.c:5378
#10 0x00007ffff7c3e650 in _PyEval_EvalFrame (throwflag=0, frame=0x7ffff72f58a8, tstate=0x7ffff7f503b8 <_PyRuntime+166136>) at ./Include/internal/pycore_ceval.h:72
#11 _PyEval_Vector (tstate=0x7ffff7f503b8 <_PyRuntime+166136>, func=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:6421
#12 0x00007ffff7b64cd5 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=2, args=0x7fffffffbf00, callable=<function at remote 0x7ffff738bce0>, tstate=0x7ffff7f503b8 <_PyRuntime+166136>)
    at ./Include/internal/pycore_call.h:92
#13 object_vacall (tstate=tstate@entry=0x7ffff7f503b8 <_PyRuntime+166136>, base=base@entry=0x0, callable=<function at remote 0x7ffff738bce0>, vargs=vargs@entry=0x7fffffffbf90) at Objects/call.c:819
#14 0x00007ffff7b64ee4 in PyObject_CallMethodObjArgs (obj=0x0, name=<optimized out>) at Objects/call.c:879
#15 0x00007ffff7c66dc9 in import_find_and_load (abs_name='_pickle', tstate=0x7ffff7f503b8 <_PyRuntime+166136>) at Python/import.c:1735
#16 PyImport_ImportModuleLevelObject (name='_pickle', globals=<optimized out>, locals=<optimized out>, fromlist=('PickleBuffer',), level=0) at Python/import.c:1834
#17 0x00007ffff7b11aa4 in import_name (level=<optimized out>, fromlist=<optimized out>, name=<optimized out>, frame=<optimized out>, tstate=<optimized out>) at Python/ceval.c:7390
#18 _PyEval_EvalFrameDefault (tstate=0x7ffff7f30800 <_PyRuntime+36160>, frame=0x7ffff72f5830, throwflag=-134937672) at Python/ceval.c:3951
#19 0x00007ffff7c3e650 in _PyEval_EvalFrame (throwflag=0, frame=0x7ffff72f5830, tstate=0x7ffff7f503b8 <_PyRuntime+166136>) at ./Include/internal/pycore_ceval.h:72
#20 _PyEval_Vector (tstate=tstate@entry=0x7ffff7f503b8 <_PyRuntime+166136>, func=func@entry=0x7ffff6f816c0,
    locals=locals@entry={'__name__': 'pickle', '__doc__': 'Create portable serialized representations of Python objects.\n\nSee module copyreg for a mechanism for registering custom picklers.\nSee module pickletools source for extensive comments.\n\nClasses:\n\n    Pickler\n    Unpickler\n\nFunctions:\n\n    dump(object, file)\n    dumps(object) -> string\n    load(file) -> object\n    loads(bytes) -> object\n\nMisc variables:\n\n    __version__\n    format_version\n    compatible_formats\n\n', '__package__': '', '__loader__': <SourceFileLoader(name='pickle', path='/tmp/cpython/Lib/pickle.py') at remote 0x7ffff6f7fdd0>, '__spec__': <ModuleSpec(name='pickle', loader=<...>, origin='/tmp/cpython/Lib/pickle.py', loader_state=None, submodule_search_locations=None, _uninitialized_submodules=[], _set_fileattr=True, _cached='/tmp/cpython/Lib/__pycache__/pickle.cpython-311.pyc', _initializing=True) at remote 0x7ffff6f7fe10>, '__file__': '/tmp/cpython/Lib/pickle.py', '__cached__': '/tmp/cpython/Lib/__pycache__/pickle.cpython-311.pyc', '__buil...(truncated), args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:6421
#21 0x00007ffff7c3e711 in PyEval_EvalCode (co=co@entry=<code at remote 0x55555569e510>,
    globals=globals@entry={'__name__': 'pickle', '__doc__': 'Create portable serialized representations of Python objects.\n\nSee module copyreg for a mechanism for registering custom picklers.\nSee module pi--Type <RET> for more, q to quit, c to continue without paging--
ckletools source for extensive comments.\n\nClasses:\n\n    Pickler\n    Unpickler\n\nFunctions:\n\n    dump(object, file)\n    dumps(object) -> string\n    load(file) -> object\n    loads(bytes) -> object\n\nMisc variables:\n\n    __version__\n    format_version\n    compatible_formats\n\n', '__package__': '', '__loader__': <SourceFileLoader(name='pickle', path='/tmp/cpython/Lib/pickle.py') at remote 0x7ffff6f7fdd0>, '__spec__': <ModuleSpec(name='pickle', loader=<...>, origin='/tmp/cpython/Lib/pickle.py', loader_state=None, submodule_search_locations=None, _uninitialized_submodules=[], _set_fileattr=True, _cached='/tmp/cpython/Lib/__pycache__/pickle.cpython-311.pyc', _initializing=True) at remote 0x7ffff6f7fe10>, '__file__': '/tmp/cpython/Lib/pickle.py', '__cached__': '/tmp/cpython/Lib/__pycache__/pickle.cpython-311.pyc', '__buil...(truncated),
    locals=locals@entry={'__name__': 'pickle', '__doc__': 'Create portable serialized representations of Python objects.\n\nSee module copyreg for a mechanism for registering custom picklers.\nSee module pickletools source for extensive comments.\n\nClasses:\n\n    Pickler\n    Unpickler\n\nFunctions:\n\n    dump(object, file)\n    dumps(object) -> string\n    load(file) -> object\n    loads(bytes) -> object\n\nMisc variables:\n\n    __version__\n    format_version\n    compatible_formats\n\n', '__package__': '', '__loader__': <SourceFileLoader(name='pickle', path='/tmp/cpython/Lib/pickle.py') at remote 0x7ffff6f7fdd0>, '__spec__': <ModuleSpec(name='pickle', loader=<...>, origin='/tmp/cpython/Lib/pickle.py', loader_state=None, submodule_search_locations=None, _uninitialized_submodules=[], _set_fileattr=True, _cached='/tmp/cpython/Lib/__pycache__/pickle.cpython-311.pyc', _initializing=True) at remote 0x7ffff6f7fe10>, '__file__': '/tmp/cpython/Lib/pickle.py', '__cached__': '/tmp/cpython/Lib/__pycache__/pickle.cpython-311.pyc', '__buil...(truncated)) at Python/ceval.c:1155
#22 0x00007ffff7c368e0 in builtin_exec_impl (module=<optimized out>, closure=<optimized out>,
    locals={'__name__': 'pickle', '__doc__': 'Create portable serialized representations of Python objects.\n\nSee module copyreg for a mechanism for registering custom picklers.\nSee module pickletools source for extensive comments.\n\nClasses:\n\n    Pickler\n    Unpickler\n\nFunctions:\n\n    dump(object, file)\n    dumps(object) -> string\n    load(file) -> object\n    loads(bytes) -> object\n\nMisc variables:\n\n    __version__\n    format_version\n    compatible_formats\n\n', '__package__': '', '__loader__': <SourceFileLoader(name='pickle', path='/tmp/cpython/Lib/pickle.py') at remote 0x7ffff6f7fdd0>, '__spec__': <ModuleSpec(name='pickle', loader=<...>, origin='/tmp/cpython/Lib/pickle.py', loader_state=None, submodule_search_locations=None, _uninitialized_submodules=[], _set_fileattr=True, _cached='/tmp/cpython/Lib/__pycache__/pickle.cpython-311.pyc', _initializing=True) at remote 0x7ffff6f7fe10>, '__file__': '/tmp/cpython/Lib/pickle.py', '__cached__': '/tmp/cpython/Lib/__pycache__/pickle.cpython-311.pyc', '__buil...(truncated),
    globals={'__name__': 'pickle', '__doc__': 'Create portable serialized representations of Python objects.\n\nSee module copyreg for a mechanism for registering custom picklers.\nSee module pickletools source for extensive comments.\n\nClasses:\n\n    Pickler\n    Unpickler\n\nFunctions:\n\n    dump(object, file)\n    dumps(object) -> string\n    load(file) -> object\n    loads(bytes) -> object\n\nMisc variables:\n\n    __version__\n    format_version\n    compatible_formats\n\n', '__package__': '', '__loader__': <SourceFileLoader(name='pickle', path='/tmp/cpython/Lib/pickle.py') at remote 0x7ffff6f7fdd0>, '__spec__': <ModuleSpec(name='pickle', loader=<...>, origin='/tmp/cpython/Lib/pickle.py', loader_state=None, submodule_search_locations=None, _uninitialized_submodules=[], _set_fileattr=True, _cached='/tmp/cpython/Lib/__pycache__/pickle.cpython-311.pyc', _initializing=True) at remote 0x7ffff6f7fe10>, '__file__': '/tmp/cpython/Lib/pickle.py', '__cached__': '/tmp/cpython/Lib/__pycache__/pickle.cpython-311.pyc', '__buil...(truncated), source=<code at remote 0x55555569e510>) at Python/bltinmodule.c:1075
#23 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Python/clinic/bltinmodule.c.h:465
#24 0x00007ffff7ba7a16 in cfunction_vectorcall_FASTCALL_KEYWORDS (func=<built-in method exec of module object at remote 0x7ffff73c86d0>, args=0x7ffff6f99c18, nargsf=<optimized out>, kwnames=<optimized out>)
    at Objects/methodobject.c:443
#25 0x00007ffff7b0e0e8 in _PyEval_EvalFrameDefault (tstate=0x7ffff7f30800 <_PyRuntime+36160>, frame=0x7ffff72f57a8, throwflag=-134937672) at Python/ceval.c:5378
#26 0x00007ffff7c3e650 in _PyEval_EvalFrame (throwflag=0, frame=0x7ffff72f5538, tstate=0x7ffff7f503b8 <_PyRuntime+166136>) at ./Include/internal/pycore_ceval.h:72
#27 _PyEval_Vector (tstate=0x7ffff7f503b8 <_PyRuntime+166136>, func=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:6421
#28 0x00007ffff7b64cd5 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=2, args=0x7fffffffc5a0, callable=<function at remote 0x7ffff738bce0>, tstate=0x7ffff7f503b8 <_PyRuntime+166136>)
    at ./Include/internal/pycore_call.h:92
#29 object_vacall (tstate=tstate@entry=0x7ffff7f503b8 <_PyRuntime+166136>, base=base@entry=0x0, callable=<function at remote 0x7ffff738bce0>, vargs=vargs@entry=0x7fffffffc630) at Objects/call.c:819
#30 0x00007ffff7b64ee4 in PyObject_CallMethodObjArgs (obj=0x0, name=<optimized out>) at Objects/call.c:879
#31 0x00007ffff7c66dc9 in import_find_and_load (abs_name='pickle', tstate=0x7ffff7f503b8 <_PyRuntime+166136>) at Python/import.c:1735
#32 PyImport_ImportModuleLevelObject (name='pickle', globals=<optimized out>, locals=<optimized out>, fromlist=None, level=0) at Python/import.c:1834
#33 0x00007ffff7b11aa4 in import_name (level=<optimized out>, fromlist=<optimized out>, name=<optimized out>, frame=<optimized out>, tstate=<optimized out>) at Python/ceval.c:7390
#34 _PyEval_EvalFrameDefault (tstate=0x7ffff7f30800 <_PyRuntime+36160>, frame=0x7ffff72f54c8, throwflag=-134937672) at Python/ceval.c:3951
#35 0x00007ffff7c3e650 in _PyEval_EvalFrame (throwflag=0, frame=0x7ffff72f54c8, tstate=0x7ffff7f503b8 <_PyRuntime+166136>) at ./Include/internal/pycore_ceval.h:72
#36 _PyEval_Vector (tstate=tstate@entry=0x7ffff7f503b8 <_PyRuntime+166136>, func=func@entry=0x7ffff73884a0,
    locals=locals@entry={'__name__': 'sphinx.search', '__doc__': 'Create a full-text search index for offline search.', '__package__': 'sphinx.search', '__loader__': <SourceFileLoader(name='sphinx.search', path='/usr/lib/python3.11/site-packages/sphinx/search/__init__.py') at remote 0x7ffff7226050>, '__spec__': <ModuleSpec(name='sphinx.search', loader=<...>, origin='/usr/lib/python3.11/site-packages/sphinx/search/__init__.py', loader_state=None, submodule_search_locations=['/usr/lib/python3.11/site-packages/sphinx/search'], _uninitialized_submodules=[], _set_fileattr=True, _cached='/usr/lib/python3.11/site-packages/s--Type <RET> for more, q to quit, c to continue without paging--
phinx/search/__pycache__/__init__.cpython-311.pyc', _initializing=True) at remote 0x7ffff71b8890>, '__path__': [...], '__file__': '/usr/lib/python3.11/site-packages/sphinx/search/__init__.py', '__cached__': '/usr/lib/python3.11/site-packages/sphinx/search/__pycache__/__init__.cpython-311.pyc', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is th...(truncated), args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:6421
#37 0x00007ffff7c3e711 in PyEval_EvalCode (co=co@entry=<code at remote 0x5555555c5c70>,
    globals=globals@entry={'__name__': 'sphinx.search', '__doc__': 'Create a full-text search index for offline search.', '__package__': 'sphinx.search', '__loader__': <SourceFileLoader(name='sphinx.search', path='/usr/lib/python3.11/site-packages/sphinx/search/__init__.py') at remote 0x7ffff7226050>, '__spec__': <ModuleSpec(name='sphinx.search', loader=<...>, origin='/usr/lib/python3.11/site-packages/sphinx/search/__init__.py', loader_state=None, submodule_search_locations=['/usr/lib/python3.11/site-packages/sphinx/search'], _uninitialized_submodules=[], _set_fileattr=True, _cached='/usr/lib/python3.11/site-packages/sphinx/search/__pycache__/__init__.cpython-311.pyc', _initializing=True) at remote 0x7ffff71b8890>, '__path__': [...], '__file__': '/usr/lib/python3.11/site-packages/sphinx/search/__init__.py', '__cached__': '/usr/lib/python3.11/site-packages/sphinx/search/__pycache__/__init__.cpython-311.pyc', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is th...(truncated),
    locals=locals@entry={'__name__': 'sphinx.search', '__doc__': 'Create a full-text search index for offline search.', '__package__': 'sphinx.search', '__loader__': <SourceFileLoader(name='sphinx.search', path='/usr/lib/python3.11/site-packages/sphinx/search/__init__.py') at remote 0x7ffff7226050>, '__spec__': <ModuleSpec(name='sphinx.search', loader=<...>, origin='/usr/lib/python3.11/site-packages/sphinx/search/__init__.py', loader_state=None, submodule_search_locations=['/usr/lib/python3.11/site-packages/sphinx/search'], _uninitialized_submodules=[], _set_fileattr=True, _cached='/usr/lib/python3.11/site-packages/sphinx/search/__pycache__/__init__.cpython-311.pyc', _initializing=True) at remote 0x7ffff71b8890>, '__path__': [...], '__file__': '/usr/lib/python3.11/site-packages/sphinx/search/__init__.py', '__cached__': '/usr/lib/python3.11/site-packages/sphinx/search/__pycache__/__init__.cpython-311.pyc', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is th...(truncated)) at Python/ceval.c:1155
#38 0x00007ffff7c368e0 in builtin_exec_impl (module=<optimized out>, closure=<optimized out>,
    locals={'__name__': 'sphinx.search', '__doc__': 'Create a full-text search index for offline search.', '__package__': 'sphinx.search', '__loader__': <SourceFileLoader(name='sphinx.search', path='/usr/lib/python3.11/site-packages/sphinx/search/__init__.py') at remote 0x7ffff7226050>, '__spec__': <ModuleSpec(name='sphinx.search', loader=<...>, origin='/usr/lib/python3.11/site-packages/sphinx/search/__init__.py', loader_state=None, submodule_search_locations=['/usr/lib/python3.11/site-packages/sphinx/search'], _uninitialized_submodules=[], _set_fileattr=True, _cached='/usr/lib/python3.11/site-packages/sphinx/search/__pycache__/__init__.cpython-311.pyc', _initializing=True) at remote 0x7ffff71b8890>, '__path__': [...], '__file__': '/usr/lib/python3.11/site-packages/sphinx/search/__init__.py', '__cached__': '/usr/lib/python3.11/site-packages/sphinx/search/__pycache__/__init__.cpython-311.pyc', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is th...(truncated),
    globals={'__name__': 'sphinx.search', '__doc__': 'Create a full-text search index for offline search.', '__package__': 'sphinx.search', '__loader__': <SourceFileLoader(name='sphinx.search', path='/usr/lib/python3.11/site-packages/sphinx/search/__init__.py') at remote 0x7ffff7226050>, '__spec__': <ModuleSpec(name='sphinx.search', loader=<...>, origin='/usr/lib/python3.11/site-packages/sphinx/search/__init__.py', loader_state=None, submodule_search_locations=['/usr/lib/python3.11/site-packages/sphinx/search'], _uninitialized_submodules=[], _set_fileattr=True, _cached='/usr/lib/python3.11/site-packages/sphinx/search/__pycache__/__init__.cpython-311.pyc', _initializing=True) at remote 0x7ffff71b8890>, '__path__': [...], '__file__': '/usr/lib/python3.11/site-packages/sphinx/search/__init__.py', '__cached__': '/usr/lib/python3.11/site-packages/sphinx/search/__pycache__/__init__.cpython-311.pyc', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is th...(truncated), source=<code at remote 0x5555555c5c70>) at Python/bltinmodule.c:1075
#39 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Python/clinic/bltinmodule.c.h:465
#40 0x00007ffff7ba7a16 in cfunction_vectorcall_FASTCALL_KEYWORDS (func=<built-in method exec of module object at remote 0x7ffff73c86d0>, args=0x7ffff72263d8, nargsf=<optimized out>, kwnames=<optimized out>)
    at Objects/methodobject.c:443
#41 0x00007ffff7b0e0e8 in _PyEval_EvalFrameDefault (tstate=0x7ffff7f30800 <_PyRuntime+36160>, frame=0x7ffff72f5440, throwflag=-134937672) at Python/ceval.c:5378
#42 0x00007ffff7c3e650 in _PyEval_EvalFrame (throwflag=0, frame=0x7ffff72f51d0, tstate=0x7ffff7f503b8 <_PyRuntime+166136>) at ./Include/internal/pycore_ceval.h:72
#43 _PyEval_Vector (tstate=0x7ffff7f503b8 <_PyRuntime+166136>, func=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:6421
#44 0x00007ffff7b64cd5 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=2, args=0x7fffffffcc40, callable=<function at remote 0x7ffff738bce0>, tstate=0x7ffff7f503b8 <_PyRuntime+166136>)
    at ./Include/internal/pycore_call.h:92
#45 object_vacall (tstate=tstate@entry=0x7ffff7f503b8 <_PyRuntime+166136>, base=base@entry=0x0, callable=<function at remote 0x7ffff738bce0>, vargs=vargs@entry=0x7fffffffccd0) at Objects/call.c:819
#46 0x00007ffff7b64ee4 in PyObject_CallMethodObjArgs (obj=0x0, name=<optimized out>) at Objects/call.c:879
#47 0x00007ffff7c66dc9 in import_find_and_load (abs_name='sphinx.search', tstate=0x7ffff7f503b8 <_PyRuntime+166136>) at Python/import.c:1735
#48 PyImport_ImportModuleLevelObject (name=name@entry='sphinx.search', globals=globals@entry=0x0, locals=locals@entry=0x0, fromlist=fromlist@entry=0x0, level=0) at Python/import.c:1834
#49 0x00007ffff7c35259 in builtin___import___impl (level=<optimized out>, fromlist=0x0, locals=0x0, globals=0x0, name='sphinx.search', module=<optimized out>) at Python/bltinmodule.c:277
#50 builtin___import__ (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Python/clinic/bltinmodule.c.h:78
--Type <RET> for more, q to quit, c to continue without paging--
#51 0x00007ffff7ba7a16 in cfunction_vectorcall_FASTCALL_KEYWORDS (func=<built-in method __import__ of module object at remote 0x7ffff73c86d0>, args=0x7ffff7405f18, nargsf=<optimized out>,
    kwnames=<optimized out>) at Objects/methodobject.c:443
#52 0x00007ffff7b0e0e8 in _PyEval_EvalFrameDefault (tstate=0x7ffff7f30800 <_PyRuntime+36160>, frame=0x7ffff72f5148, throwflag=-134937672) at Python/ceval.c:5378
#53 0x00007ffff7c3e650 in _PyEval_EvalFrame (throwflag=0, frame=0x7ffff72f5078, tstate=0x7ffff7f503b8 <_PyRuntime+166136>) at ./Include/internal/pycore_ceval.h:72
#54 _PyEval_Vector (tstate=0x7ffff7f503b8 <_PyRuntime+166136>, func=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:6421
#55 0x00007ffff7b64cd5 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=3, args=0x7fffffffd0c0, callable=<function at remote 0x7ffff738be20>, tstate=0x7ffff7f503b8 <_PyRuntime+166136>)
    at ./Include/internal/pycore_call.h:92
#56 object_vacall (tstate=tstate@entry=0x7ffff7f503b8 <_PyRuntime+166136>, base=base@entry=0x0, callable=<function at remote 0x7ffff738be20>, vargs=vargs@entry=0x7fffffffd150) at Objects/call.c:819
#57 0x00007ffff7b64ee4 in PyObject_CallMethodObjArgs (obj=0x0, name=<optimized out>) at Objects/call.c:879
#58 0x00007ffff7c66940 in PyImport_ImportModuleLevelObject (name='sphinx', globals=<optimized out>, locals=<optimized out>, fromlist=('search',), level=0) at Python/import.c:1905
#59 0x00007ffff7b11aa4 in import_name (level=<optimized out>, fromlist=<optimized out>, name=<optimized out>, frame=<optimized out>, tstate=<optimized out>) at Python/ceval.c:7390
#60 _PyEval_EvalFrameDefault (tstate=0x7ffff7f30800 <_PyRuntime+36160>, frame=0x7ffff72f5020, throwflag=-134937672) at Python/ceval.c:3951
#61 0x00007ffff7c3e650 in _PyEval_EvalFrame (throwflag=0, frame=0x7ffff72f5020, tstate=0x7ffff7f503b8 <_PyRuntime+166136>) at ./Include/internal/pycore_ceval.h:72
#62 _PyEval_Vector (tstate=tstate@entry=0x7ffff7f503b8 <_PyRuntime+166136>, func=func@entry=0x7ffff73d44a0,
    locals=locals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <type at remote 0x5555555795a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff73c86d0>}, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:6421
#63 0x00007ffff7c3e711 in PyEval_EvalCode (co=co@entry=<code at remote 0x7ffff7370ab0>,
    globals=globals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <type at remote 0x5555555795a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff73c86d0>},
    locals=locals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <type at remote 0x5555555795a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff73c86d0>}) at Python/ceval.c:1155
#64 0x00007ffff7c80ed3 in run_eval_code_obj (tstate=tstate@entry=0x7ffff7f503b8 <_PyRuntime+166136>, co=co@entry=0x7ffff7370ab0,
    globals=globals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <type at remote 0x5555555795a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff73c86d0>},
    locals=locals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <type at remote 0x5555555795a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff73c86d0>}) at Python/pythonrun.c:1714
#65 0x00007ffff7c810f6 in run_mod (mod=mod@entry=0x5555555c7198, filename=filename@entry='<string>',
    globals=globals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <type at remote 0x5555555795a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff73c86d0>},
    locals=locals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <type at remote 0x5555555795a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff73c86d0>}, flags=flags@entry=0x7fffffffd5e8, arena=arena@entry=0x7ffff7357770) at Python/pythonrun.c:1735
#66 0x00007ffff7c843df in PyRun_StringFlags (str=str@entry=0x7ffff7432c90 "from sphinx import search\n", start=start@entry=257,
    globals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <type at remote 0x5555555795a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff73c86d0>},
    locals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <type at remote 0x5555555795a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff73c86d0>}, flags=flags@entry=0x7fffffffd5e8) at Python/pythonrun.c:1605
#67 0x00007ffff7c8444f in PyRun_SimpleStringFlags (command=0x7ffff7432c90 "from sphinx import search\n", flags=flags@entry=0x7fffffffd5e8) at Python/pythonrun.c:487
#68 0x00007ffff7ca14be in pymain_run_command (command=<optimized out>) at Modules/main.c:255
#69 pymain_run_python (exitcode=0x7fffffffd5e0) at Modules/main.c:592
#70 Py_RunMain () at Modules/main.c:680
#71 0x00007ffff7ca215e in pymain_main (args=0x7fffffffd700) at Modules/main.c:710
#72 Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:734
#73 0x00007ffff77512d0 in ?? () from /usr/lib64/libc.so.6
--Type <RET> for more, q to quit, c to continue without paging--
#74 0x00007ffff7751389 in __libc_start_main () from /usr/lib64/libc.so.6
#75 0x0000555555555095 in _start ()
(gdb)
```

**Your environment**

- CPython versions tested on: Python 3.11.0b3 (b1, b2 are fine)
- Operating system and architecture: Linux (5.15.44), Gentoo, amd64
- Originally reported downstream in [Gentoo](https://bugs.gentoo.org/849311) (noticed when building Python itself)

**Comment by thesamesam** [comment]
Bisected to 00f8fe956491816f03f1cc76bc7ed297cd9c0930:
```
commit 00f8fe956491816f03f1cc76bc7ed297cd9c0930
Author: Miss Islington (bot) <31488909+miss-islington@users.noreply.github.com>
Date:   Tue May 31 19:13:27 2022 -0700

    [3.11] gh-91162: Fix substitution of unpacked tuples in generic aliases (GH-92335) (#92484)

    * gh-91162: Fix substitution of unpacked tuples in generic aliases (GH-92335)
    (cherry picked from commit 9d25db9db1617f012d7dba118b5b8f2b9e25e116)

    Co-authored-by: Serhiy Storchaka <storchaka@gmail.com>

    * Regenerate ABI file

    Co-authored-by: Serhiy Storchaka <storchaka@gmail.com>
    Co-authored-by: Pablo Galindo <pablogsal@gmail.com>
```

cc @pablogsal @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
Where did you get sphinx? It looks to me that some extensions were built incompatible with Python 3.11b3 ABI.

**Comment by thesamesam** [comment]
It's built using the packaging for Sphinx in Gentoo (works fine normally) (cc @mgorny).

**Comment by thesamesam** [comment]
I'm sorry, this ended up being our fault -- we were setting LD_LIBRARY_PATH and the system Python 3.11 was being mixed with the just-built libpython. Apologies!
