### ISSUE TITLE
[tests][multiprocessing] multiprocessing test_shared_memory_recreate() failed on aarch64 Fedora Stable LTO 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#93531]
aarch64 Fedora Stable LTO 3.x:
https://buildbot.python.org/all/#/builders/336/builds/1911

```
======================================================================
FAIL: test_shared_memory_recreate (test.test_multiprocessing_fork.WithProcessesTestSharedMemory.test_shared_memory_recreate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-stable-aarch64.lto/build/Lib/test/_test_multiprocessing.py", line 3976, in test_shared_memory_recreate
    self.assertEqual(shm1._name, names[0])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: '/psm_test02_fn' != '/psm_test01_fn'
- /psm_test02_fn
?           ^
+ /psm_test01_fn
?           ^


----------------------------------------------------------------------
Ran 1 test in 0.279s

FAILED (failures=1)
test test_multiprocessing_fork failed
0:03:01 load avg: 3.26 Re-running test_multiprocessing_forkserver in verbose mode (matching: test_shared_memory_recreate)
test_shared_memory_recreate (test.test_multiprocessing_forkserver.WithProcessesTestSharedMemory.test_shared_memory_recreate) ... FAIL

======================================================================
FAIL: test_shared_memory_recreate (test.test_multiprocessing_forkserver.WithProcessesTestSharedMemory.test_shared_memory_recreate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-stable-aarch64.lto/build/Lib/test/_test_multiprocessing.py", line 3976, in test_shared_memory_recreate
    self.assertEqual(shm1._name, names[0])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: '/psm_test02_fn' != '/psm_test01_fn'
- /psm_test02_fn
?           ^
+ /psm_test01_fn
?           ^


----------------------------------------------------------------------
Ran 1 test in 0.263s

FAILED (failures=1)
test test_multiprocessing_forkserver failed
0:03:02 load avg: 3.26 Re-running test_multiprocessing_spawn in verbose mode (matching: test_shared_memory_recreate)
test_shared_memory_recreate (test.test_multiprocessing_spawn.WithProcessesTestSharedMemory.test_shared_memory_recreate) ... FAIL

======================================================================
FAIL: test_shared_memory_recreate (test.test_multiprocessing_spawn.WithProcessesTestSharedMemory.test_shared_memory_recreate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-stable-aarch64.lto/build/Lib/test/_test_multiprocessing.py", line 3976, in test_shared_memory_recreate
    self.assertEqual(shm1._name, names[0])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: '/psm_test02_fn' != '/psm_test01_fn'
- /psm_test02_fn
?           ^
+ /psm_test01_fn
?           ^
```

**Comment by vstinner** [comment]
I don't know why, but an old was kept by a previous test run and was not removed:

```
$ ls /dev/shm/psm*test*
/dev/shm/psm_test01_fn
```
