### ISSUE TITLE
mock.patch applied at class level behaves incorrectly 

### ISSUE THREAD

**Issue by r3m0t** [python/cpython#93582]
**Bug report**

When applying `@mock.patch` to classes where the `test_` method is inherited, this applies the patch to the base class,, instead of to the specific class. In this case, the patch to the `g` method applies in `MockedFTests` and `MockedFStraightGTests`.

```
# a.py
import unittest
from unittest import mock

def f():
    return 41

def g():
    return 43

class BaseFTests(unittest.TestCase):
    def test_a(self):
        self._asserts(f())

    def _asserts(self, val):
        print(self, val)

@mock.patch('a.f', new=lambda: 2)
class MockedFTests(BaseFTests):
    def _asserts(self, val):
        print(self, val)
        self.assertEqual(val, 2)
        self.assertEqual(g(), 43)

@mock.patch('a.g', new=lambda: 3)
class MockedFMockedGTests(MockedFTests):
    def _asserts(self, val):
        print(self, val)
        self.assertEqual(val, g()-1)

class MockedFStraightGTests(MockedFTests):
    def _asserts(self, val):
        print(self, val)
        self.assertEqual(val, 2)
        self.assertEqual(g(), 43)
```

Expect all tests to pass.
Actual output: 2 tests fail with error `AssertionError: 3 != 43`

**Your environment**

- CPython versions tested on: Python 3.10.4 on Windows

**Comment by tirkarthi** [comment]
Calling `mock.patch` at class level iterates through all methods and applies the patch. You might probably want to move patching to `setUp` that might help your use case. 

Also see : https://stackoverflow.com/questions/32981141/inheriting-a-patched-class

https://github.com/python/cpython/blob/c735d545343c3ab002c62596b2fb2cfa4488b0af/Lib/unittest/mock.py#L1319-L1330

```python
# bpo93582.py

import unittest
from unittest import mock


def f():
    return 41


def g():
    return 43


class BaseFTests(unittest.TestCase):
    def test_a(self):
        self._asserts(f())

    def _asserts(self, val):
        pass


class MockedA(BaseFTests):
    def setUp(self):
        super().setUp()
        patch_f = mock.patch(f"{__name__}.f", lambda: 2)
        patch_f.start()
        self.addCleanup(patch_f.stop)

    def _asserts(self, val):
        self.assertEqual(val, 2)
        self.assertEqual(g(), 43)


class MockedB(MockedA):
    def setUp(self):
        super().setUp()
        patch_g = mock.patch(f"{__name__}.g", lambda: 3)
        patch_g.start()
        self.addCleanup(patch_g.stop)

    def _asserts(self, val):
        self.assertEqual(val, g() - 1)


if __name__ == "__main__":
    unittest.main()

```

**Comment by r3m0t** [comment]
@tirkarthi do you want to treat it as a docs issue? It's surprising that a class decorator will affect the base class as well as the class it was applied to.

> Patch can be used as a TestCase class decorator. It works by decorating each test method in the class. This reduces the boilerplate code when your test methods share a common patchings set. [patch()](https://docs.python.org/3.12/library/unittest.mock.html?highlight=unittest%20mock#unittest.mock.patch) finds tests by looking for method names that start with patch.TEST_PREFIX. By default this is 'test', which matches the way [unittest](https://docs.python.org/3.12/library/unittest.html#module-unittest) finds tests. You can specify an alternative prefix by setting patch.TEST_PREFIX.

**Comment by tirkarthi** [comment]
I guess it's tricky to explain this without getting into too much detail or an example since in this case `BaseFTests.test_a` which is the base class method holds references to patches of both `f` and `g` during execution as class level patching is executed during startup itself.

@cjw296 @mariocj89 Thoughts on any suggested explanation?

```python
import unittest
from unittest import mock


def f():
    return 41


def g():
    return 43


class BaseFTests(unittest.TestCase):
    def test_a(self):
        self._asserts(f())

    def _asserts(self, val):
        pass


@mock.patch(f"{__name__}.f", lambda: 2)
class MockedA(BaseFTests):

    def _asserts(self, val):
        print("MockedA test_a patchings : ", self.test_a.patchings)
        self.assertEqual(val, 2)
        self.assertEqual(g(), 43)


@mock.patch(f"{__name__}.g", lambda: 3)
class MockedB(MockedA):

    def _asserts(self, val):
        print("MockedB test_a patchings : ", self.test_a.patchings)
        self.assertEqual(val, g() - 1)


if __name__ == "__main__":
    unittest.main(exit=False)
```

`patchings` should be 1 for each test but it's 2 since `f` and `g` are patched as class decorator

```
./python ../bpo93582_decorator.py -vvv
test_a (__main__.BaseFTests.test_a) ... ok
test_a (__main__.MockedA.test_a) ... MockedA test_a patchings :  [<unittest.mock._patch object at 0x7f56e07fb0d0>, <unittest.mock._patch object at 0x7f56dfe4fdd0>]
FAIL
test_a (__main__.MockedB.test_a) ... MockedB test_a patchings :  [<unittest.mock._patch object at 0x7f56e07fb0d0>, <unittest.mock._patch object at 0x7f56dfe4fdd0>]
ok

======================================================================
FAIL: test_a (__main__.MockedA.test_a)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthikeyan/stuff/python/cpython/Lib/unittest/mock.py", line 1359, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthikeyan/stuff/python/cpython/../bpo93582_decorator.py", line 15, in test_a
    self._asserts(f())
    ^^^^^^^^^^^^^^^^^^
  File "/home/karthikeyan/stuff/python/cpython/../bpo93582_decorator.py", line 27, in _asserts
    self.assertEqual(g(), 43)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 3 != 43

----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (failures=1)

```

**Comment by mariocj89** [comment]
That's indeed tricky to explain as I can see how this might be unexpected for the user, at the same time, the opposite (not patching base methods) will also be a surprise for users in other situations.

An potential fix here might be to move "class level" patches to the class itself, and have the patchings be a property that also looks at the class patchings together with a  private list of the method level patchings.

**Comment by cjw296** [comment]
I don't have any sensible suggestions, other than noting that I've hit issues with stacked patching decorators in testfixtures too...
