### ISSUE TITLE
Randomly Socket Shutdowns/Issues (FastAPI/Uvicorn), OSError: [WinError 64]

### ISSUE THREAD

**Issue by Cacsjep** [python/cpython#93758]
**Hey Guys,**

We have running an fastapi asgi app running on uvicorn and sometimes web server is not working because of the following error.
It looks like that socket is closed, this issue happens randomly once a month or so, updating to latest 3.9.13 version did not resolve this issue.

I just want to ask if there someting that we can do or is this an open issue, I cant found one on bug tracker.
Event Viewer on windows does not showing any event when this happpen.
Disabling Windows Defender does not affect or resovle this issue.

I was not able todo a reproducible example.

```
ERROR  Task exception was never retrieved
future: <Task finished name='Task-15680987' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at C:\Program Files\Python39\lib\asyncio\windows_events.py:568> exception=OSError(22, 'The specified network name is no longer available', None, 64, None)>
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 571, in accept_coro
    await future
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 560, in finish_accept
    ov.getresult()
OSError: [WinError 64] The specified network name is no longer available

ERROR  Accept failed on a socket
socket: <asyncio.TransportSocket fd=1192, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8088)>
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 819, in loop
    conn, addr = f.result()
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 571, in accept_coro
    await future
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 560, in finish_accept
    ov.getresult()
OSError: [WinError 64] The specified network name is no longer available
```

OS:  Windows 10 Pro
Python: 3.9.13

**Comment by kumaraditya303** [comment]
This is likely a bug in uvicorn and without a reproducer there isn't much we can do about it. Also 3.9 is now security fix only so you should try  newer version to see if this is resolved there or report this to uvicorn bug tracker.

**Comment by Cacsjep** [comment]
ok thank u for your answer
