### ISSUE TITLE
Enum does not work if member is an instance of types.GenericAlias

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#93847]
Enums does not work with generic alias of builtin types, like `list[int]`.
```
>>> class E(enum.Enum):
...     L = list[int]
... 
>>> E.L
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/py/cpython/Lib/enum.py", line 1241, in __repr__
    return "<%s.%s: %s>" % (self.__class__.__name__, self._name_, v_repr(self._value_))
                                                                  ^^^^^^^^^^^^^^^^^^^^
TypeError: descriptor '__repr__' requires a 'type' object but received a 'types.GenericAlias'
```
All works with `typing.List[int]`.
```
>>> class E(enum.Enum):
...     L = List[int]
... 
>>> E.L
<E.L: typing.List[int]>
```
This is a manifestation of the  #89828 bug.

**Comment by serhiy-storchaka** [comment]
It is not directly caused by the #89828 bug, but both bugs have the same cause (fixed in #93754).
