### ISSUE TITLE
Address Sanitizer: some test function of test.test_concurrent_futures  fail

### ISSUE THREAD

**Issue by alittlesir** [python/cpython#93981]
when i run `python -m test.regrtest test_concurrent_futures -v`,  

test_crash_at_task_unpickle
test_crash_during_func_exec_on_worker

was failed

```
== CPython 3.9.9 (main, Jun 15 2022, 09:11:01) [GCC 10.3.1]
== Linux-5.10.0
== cwd: /root/rpmbuild/BUILD/Python-3.9.9/build/test_python_2838568æ
== CPU count: 4
== encodings: locale=UTF-8, FS=utf-8
0:00:00 load avg: 0.95 Run tests sequentially
0:00:00 load avg: 0.95 [1/1] test_concurrent_futures
test_cancel (test.test_concurrent_futures.FutureTests) ... ok
test_cancelled (test.test_concurrent_futures.FutureTests) ... ok
test_done (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_already_cancelled (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_already_failed (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_already_successful (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_raises (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_raises_already_succeeded (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_with_cancel (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_with_exception (test.test_concurrent_futures.FutureTests) ... ok
test_done_callback_with_result (test.test_concurrent_futures.FutureTests) ... ok
test_exception_with_success (test.test_concurrent_futures.FutureTests) ... ok
test_exception_with_timeout (test.test_concurrent_futures.FutureTests) ... ok
test_multiple_set_exception (test.test_concurrent_futures.FutureTests) ... ok
test_multiple_set_result (test.test_concurrent_futures.FutureTests) ... ok
test_repr (test.test_concurrent_futures.FutureTests) ... ok
test_result_with_cancel (test.test_concurrent_futures.FutureTests) ... ok
test_result_with_success (test.test_concurrent_futures.FutureTests) ... ok
test_result_with_timeout (test.test_concurrent_futures.FutureTests) ... ok
test_running (test.test_concurrent_futures.FutureTests) ... ok
test_correct_timeout_exception_msg (test.test_concurrent_futures.ProcessPoolForkAsCompletedTest) ... 0.15s ok
test_duplicate_futures (test.test_concurrent_futures.ProcessPoolForkAsCompletedTest) ... 2.15s ok
test_free_reference_yielded_future (test.test_concurrent_futures.ProcessPoolForkAsCompletedTest) ... 0.32s ok
test_no_timeout (test.test_concurrent_futures.ProcessPoolForkAsCompletedTest) ... 0.15s ok
test_zero_timeout (test.test_concurrent_futures.ProcessPoolForkAsCompletedTest) ... 2.15s ok
test_crash_at_task_unpickle (test.test_concurrent_futures.ProcessPoolForkExecutorDeadlockTest) ... AddressSanitizer:DEADLYSIGNAL
=================================================================
==2838713==ERROR: AddressSanitizer: SEGV on unknown address 0x0000002b50b9 (pc 0x7f128387710f bp 0x00000000000b sp 0x7ffdfc6d1c20 T0)
==2838713==The signal is caused by a READ memory access.
    #0 0x7f128387710f  (/usr/lib64/libc.so.6+0x8d10f)
    #1 0x7f128382b025 in raise (/usr/lib64/libc.so.6+0x41025)
    #2 0x7f693e in faulthandler_raise_sigsegv Modules/faulthandler.c:1045
    #3 0x7f693e in faulthandler_sigsegv Modules/faulthandler.c:1061
    #4 0x87d862 in cfunction_call Objects/methodobject.c:552
    #5 0x45eedc in _PyObject_MakeTpCall Objects/call.c:191
    #6 0x43e3e0 in _PyObject_VectorcallTstate Include/cpython/abstract.h:116
    #7 0x43e3e0 in _PyObject_VectorcallTstate Include/cpython/abstract.h:103
    #8 0x43e3e0 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #9 0x43e3e0 in call_function Python/ceval.c:5075
    #10 0x43e3e0 in _PyEval_EvalFrameDefault Python/ceval.c:3487
    #11 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #12 0x42265c in function_code_fastcall Objects/call.c:330
    #13 0x7f12721f1675 in load_reduce /root/rpmbuild/BUILD/Python-3.9.9/Modules/_pickle.c:6833
    #14 0x7f12721f1675 in load /root/rpmbuild/BUILD/Python-3.9.9/Modules/_pickle.c:6981
    #15 0x7f12721f5236 in _pickle_loads_impl /root/rpmbuild/BUILD/Python-3.9.9/Modules/_pickle.c:7935
    #16 0x7f12721f5236 in _pickle_loads /root/rpmbuild/BUILD/Python-3.9.9/Modules/clinic/_pickle.c.h:834
    #17 0x87ea08 in cfunction_vectorcall_FASTCALL_KEYWORDS Objects/methodobject.c:446
    #18 0x437c94 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #19 0x437c94 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #20 0x437c94 in call_function Python/ceval.c:5075
    #21 0x437c94 in _PyEval_EvalFrameDefault Python/ceval.c:3487
    #22 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #23 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #24 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #25 0x846289 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #26 0x846289 in method_vectorcall Objects/classobject.c:53
    #27 0x4359d4 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #28 0x4359d4 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #29 0x4359d4 in call_function Python/ceval.c:5075
    #30 0x4359d4 in _PyEval_EvalFrameDefault Python/ceval.c:3535
    #31 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #32 0x42265c in function_code_fastcall Objects/call.c:330
    #33 0x4610ac in PyVectorcall_Call Objects/call.c:231
    #34 0x42c932 in do_call_core Python/ceval.c:5123
    #35 0x42c932 in _PyEval_EvalFrameDefault Python/ceval.c:3580
    #36 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #37 0x42265c in function_code_fastcall Objects/call.c:330
    #38 0x438eaf in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #39 0x438eaf in PyObject_Vectorcall Include/cpython/abstract.h:127
    #40 0x438eaf in call_function Python/ceval.c:5075
    #41 0x438eaf in _PyEval_EvalFrameDefault Python/ceval.c:3504
    #42 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #43 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #44 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #45 0x846289 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #46 0x846289 in method_vectorcall Objects/classobject.c:53
    #47 0x4359d4 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #48 0x4359d4 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #49 0x4359d4 in call_function Python/ceval.c:5075
    #50 0x4359d4 in _PyEval_EvalFrameDefault Python/ceval.c:3535
    #51 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #52 0x42265c in function_code_fastcall Objects/call.c:330
    #53 0x438eaf in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #54 0x438eaf in PyObject_Vectorcall Include/cpython/abstract.h:127
    #55 0x438eaf in call_function Python/ceval.c:5075
    #56 0x438eaf in _PyEval_EvalFrameDefault Python/ceval.c:3504
    #57 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #58 0x42265c in function_code_fastcall Objects/call.c:330
    #59 0x463884 in _PyObject_FastCallDictTstate Objects/call.c:118
    #60 0x463884 in _PyObject_Call_Prepend Objects/call.c:489
    #61 0x540d5d in slot_tp_init Objects/typeobject.c:6964
    #62 0x51e8d7 in type_call Objects/typeobject.c:1026
    #63 0x45eedc in _PyObject_MakeTpCall Objects/call.c:191
    #64 0x437946 in _PyObject_VectorcallTstate Include/cpython/abstract.h:116
    #65 0x437946 in _PyObject_VectorcallTstate Include/cpython/abstract.h:103
    #66 0x437946 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #67 0x437946 in call_function Python/ceval.c:5075
    #68 0x437946 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #69 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #70 0x42265c in function_code_fastcall Objects/call.c:330
    #71 0x437c94 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #72 0x437c94 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #73 0x437c94 in call_function Python/ceval.c:5075
    #74 0x437c94 in _PyEval_EvalFrameDefault Python/ceval.c:3487
    #75 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #76 0x42265c in function_code_fastcall Objects/call.c:330
    #77 0x438eaf in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #78 0x438eaf in PyObject_Vectorcall Include/cpython/abstract.h:127
    #79 0x438eaf in call_function Python/ceval.c:5075
    #80 0x438eaf in _PyEval_EvalFrameDefault Python/ceval.c:3504
    #81 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #82 0x42265c in function_code_fastcall Objects/call.c:330
    #83 0x438eaf in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #84 0x438eaf in PyObject_Vectorcall Include/cpython/abstract.h:127
    #85 0x438eaf in call_function Python/ceval.c:5075
    #86 0x438eaf in _PyEval_EvalFrameDefault Python/ceval.c:3504
    #87 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #88 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #89 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #90 0x846111 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #91 0x846111 in method_vectorcall Objects/classobject.c:83
    #92 0x4610ac in PyVectorcall_Call Objects/call.c:231
    #93 0x42c932 in do_call_core Python/ceval.c:5123
    #94 0x42c932 in _PyEval_EvalFrameDefault Python/ceval.c:3580
    #95 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #96 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #97 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #98 0x438eaf in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #99 0x438eaf in PyObject_Vectorcall Include/cpython/abstract.h:127
    #100 0x438eaf in call_function Python/ceval.c:5075
    #101 0x438eaf in _PyEval_EvalFrameDefault Python/ceval.c:3504
    #102 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #103 0x42265c in function_code_fastcall Objects/call.c:330
    #104 0x846289 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #105 0x846289 in method_vectorcall Objects/classobject.c:53
    #106 0x436237 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #107 0x436237 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #108 0x436237 in call_function Python/ceval.c:5075
    #109 0x436237 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #110 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #111 0x42265c in function_code_fastcall Objects/call.c:330
    #112 0x438eaf in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #113 0x438eaf in PyObject_Vectorcall Include/cpython/abstract.h:127
    #114 0x438eaf in call_function Python/ceval.c:5075
    #115 0x438eaf in _PyEval_EvalFrameDefault Python/ceval.c:3504
    #116 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #117 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #118 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #119 0x846111 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #120 0x846111 in method_vectorcall Objects/classobject.c:83
    #121 0x4610ac in PyVectorcall_Call Objects/call.c:231
    #122 0x42c932 in do_call_core Python/ceval.c:5123
    #123 0x42c932 in _PyEval_EvalFrameDefault Python/ceval.c:3580
    #124 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #125 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #126 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #127 0x463884 in _PyObject_FastCallDictTstate Objects/call.c:118
    #128 0x463884 in _PyObject_Call_Prepend Objects/call.c:489
    #129 0x5317dc in slot_tp_call Objects/typeobject.c:6724
    #130 0x45eedc in _PyObject_MakeTpCall Objects/call.c:191
    #131 0x437946 in _PyObject_VectorcallTstate Include/cpython/abstract.h:116
    #132 0x437946 in _PyObject_VectorcallTstate Include/cpython/abstract.h:103
    #133 0x437946 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #134 0x437946 in call_function Python/ceval.c:5075
    #135 0x437946 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #136 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #137 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #138 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #139 0x846111 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #140 0x846111 in method_vectorcall Objects/classobject.c:83
    #141 0x4610ac in PyVectorcall_Call Objects/call.c:231
    #142 0x42c932 in do_call_core Python/ceval.c:5123
    #143 0x42c932 in _PyEval_EvalFrameDefault Python/ceval.c:3580
    #144 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #145 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #146 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #147 0x463884 in _PyObject_FastCallDictTstate Objects/call.c:118
    #148 0x463884 in _PyObject_Call_Prepend Objects/call.c:489
    #149 0x5317dc in slot_tp_call Objects/typeobject.c:6724
    #150 0x45eedc in _PyObject_MakeTpCall Objects/call.c:191
    #151 0x437946 in _PyObject_VectorcallTstate Include/cpython/abstract.h:116
    #152 0x437946 in _PyObject_VectorcallTstate Include/cpython/abstract.h:103
    #153 0x437946 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #154 0x437946 in call_function Python/ceval.c:5075
    #155 0x437946 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #156 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #157 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #158 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #159 0x846111 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #160 0x846111 in method_vectorcall Objects/classobject.c:83
    #161 0x4610ac in PyVectorcall_Call Objects/call.c:231
    #162 0x42c932 in do_call_core Python/ceval.c:5123
    #163 0x42c932 in _PyEval_EvalFrameDefault Python/ceval.c:3580
    #164 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #165 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #166 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #167 0x463884 in _PyObject_FastCallDictTstate Objects/call.c:118
    #168 0x463884 in _PyObject_Call_Prepend Objects/call.c:489
    #169 0x5317dc in slot_tp_call Objects/typeobject.c:6724
    #170 0x45eedc in _PyObject_MakeTpCall Objects/call.c:191
    #171 0x437946 in _PyObject_VectorcallTstate Include/cpython/abstract.h:116
    #172 0x437946 in _PyObject_VectorcallTstate Include/cpython/abstract.h:103
    #173 0x437946 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #174 0x437946 in call_function Python/ceval.c:5075
    #175 0x437946 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #176 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #177 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #178 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #179 0x846111 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #180 0x846111 in method_vectorcall Objects/classobject.c:83
    #181 0x4610ac in PyVectorcall_Call Objects/call.c:231
    #182 0x42c932 in do_call_core Python/ceval.c:5123
    #183 0x42c932 in _PyEval_EvalFrameDefault Python/ceval.c:3580
    #184 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #185 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #186 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #187 0x463884 in _PyObject_FastCallDictTstate Objects/call.c:118
    #188 0x463884 in _PyObject_Call_Prepend Objects/call.c:489
    #189 0x5317dc in slot_tp_call Objects/typeobject.c:6724
    #190 0x45eedc in _PyObject_MakeTpCall Objects/call.c:191
    #191 0x437946 in _PyObject_VectorcallTstate Include/cpython/abstract.h:116
    #192 0x437946 in _PyObject_VectorcallTstate Include/cpython/abstract.h:103
    #193 0x437946 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #194 0x437946 in call_function Python/ceval.c:5075
    #195 0x437946 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #196 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #197 0x42265c in function_code_fastcall Objects/call.c:330
    #198 0x438eaf in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #199 0x438eaf in PyObject_Vectorcall Include/cpython/abstract.h:127
    #200 0x438eaf in call_function Python/ceval.c:5075
    #201 0x438eaf in _PyEval_EvalFrameDefault Python/ceval.c:3504
    #202 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #203 0x42265c in function_code_fastcall Objects/call.c:330
    #204 0x436237 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #205 0x436237 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #206 0x436237 in call_function Python/ceval.c:5075
    #207 0x436237 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #208 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #209 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #210 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #211 0x437c94 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #212 0x437c94 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #213 0x437c94 in call_function Python/ceval.c:5075
    #214 0x437c94 in _PyEval_EvalFrameDefault Python/ceval.c:3487
    #215 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #216 0x42265c in function_code_fastcall Objects/call.c:330
    #217 0x77f9c5 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #218 0x77f9c5 in partial_vectorcall Modules/_functoolsmodule.c:167
    #219 0x436237 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #220 0x436237 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #221 0x436237 in call_function Python/ceval.c:5075
    #222 0x436237 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #223 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #224 0x42265c in function_code_fastcall Objects/call.c:330
    #225 0x436237 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #226 0x436237 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #227 0x436237 in call_function Python/ceval.c:5075
    #228 0x436237 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #229 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #230 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #231 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #232 0x4359d4 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #233 0x4359d4 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #234 0x4359d4 in call_function Python/ceval.c:5075
    #235 0x4359d4 in _PyEval_EvalFrameDefault Python/ceval.c:3535
    #236 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #237 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #238 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #239 0x436237 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #240 0x436237 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #241 0x436237 in call_function Python/ceval.c:5075
    #242 0x436237 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #243 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #244 0x42265c in function_code_fastcall Objects/call.c:330
    #245 0x436237 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #246 0x436237 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #247 0x436237 in call_function Python/ceval.c:5075
    #248 0x436237 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #249 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #250 0x42265c in function_code_fastcall Objects/call.c:330
    #251 0x438eaf in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #252 0x438eaf in PyObject_Vectorcall Include/cpython/abstract.h:127
    #253 0x438eaf in call_function Python/ceval.c:5075
    #254 0x438eaf in _PyEval_EvalFrameDefault Python/ceval.c:3504
    #255 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #256 0x42265c in function_code_fastcall Objects/call.c:330
    #257 0x438eaf in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #258 0x438eaf in PyObject_Vectorcall Include/cpython/abstract.h:127
    #259 0x438eaf in call_function Python/ceval.c:5075
    #260 0x438eaf in _PyEval_EvalFrameDefault Python/ceval.c:3504
    #261 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #262 0x42265c in function_code_fastcall Objects/call.c:330
    #263 0x438eaf in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #264 0x438eaf in PyObject_Vectorcall Include/cpython/abstract.h:127
    #265 0x438eaf in call_function Python/ceval.c:5075
    #266 0x438eaf in _PyEval_EvalFrameDefault Python/ceval.c:3504
    #267 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #268 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #269 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #270 0x846289 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #271 0x846289 in method_vectorcall Objects/classobject.c:53
    #272 0x46115a in PyVectorcall_Call Objects/call.c:243
    #273 0x42c932 in do_call_core Python/ceval.c:5123
    #274 0x42c932 in _PyEval_EvalFrameDefault Python/ceval.c:3580
    #275 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #276 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #277 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #278 0x436237 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #279 0x436237 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #280 0x436237 in call_function Python/ceval.c:5075
    #281 0x436237 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #282 0x42265c in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #283 0x42265c in function_code_fastcall Objects/call.c:330
    #284 0x436237 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #285 0x436237 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #286 0x436237 in call_function Python/ceval.c:5075
    #287 0x436237 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #288 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #289 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #290 0x5f74e6 in _PyEval_EvalCodeWithName Python/ceval.c:4359
    #291 0x5f74e6 in PyEval_EvalCodeEx Python/ceval.c:4375
    #292 0x5f74e6 in PyEval_EvalCode Python/ceval.c:826
    #293 0x8f9e00 in builtin_exec_impl Python/bltinmodule.c:1026
    #294 0x8f9e00 in builtin_exec Python/clinic/bltinmodule.c.h:396
    #295 0x87f087 in cfunction_vectorcall_FASTCALL Objects/methodobject.c:430
    #296 0x436237 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #297 0x436237 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #298 0x436237 in call_function Python/ceval.c:5075
    #299 0x436237 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #300 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #301 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #302 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #303 0x436237 in _PyObject_VectorcallTstate Include/cpython/abstract.h:118
    #304 0x436237 in PyObject_Vectorcall Include/cpython/abstract.h:127
    #305 0x436237 in call_function Python/ceval.c:5075
    #306 0x436237 in _PyEval_EvalFrameDefault Python/ceval.c:3518
    #307 0x5f6ce7 in _PyEval_EvalFrame Include/internal/pycore_ceval.h:40
    #308 0x5f6ce7 in _PyEval_EvalCode Python/ceval.c:4327
    #309 0x4621e8 in _PyFunction_Vectorcall Objects/call.c:396
    #310 0x4610ac in PyVectorcall_Call Objects/call.c:231
    #311 0x43fffa in pymain_run_module Modules/main.c:291
    #312 0x441063 in pymain_run_python Modules/main.c:592
    #313 0x442e59 in Py_RunMain Modules/main.c:677
    #314 0x442e59 in pymain_main Modules/main.c:707
    #315 0x442e59 in Py_BytesMain Modules/main.c:731
    #316 0x7f128381726f  (/usr/lib64/libc.so.6+0x2d26f)
    #317 0x7f128381731b in __libc_start_main (/usr/lib64/libc.so.6+0x2d31b)
    #318 0x43f774 in _start (/root/rpmbuild/BUILD/Python-3.9.9/python+0x43f774)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib64/libc.so.6+0x8d10f) 
==2838713==ABORTING
0.21s ok
test_crash_during_func_exec_on_worker (test.test_concurrent_futures.ProcessPoolForkExecutorDeadlockTest) ... AddressSanitizer:DEADLYSIGNAL
```

**Comment by kumaraditya303** [comment]
Closing as 3.9.9  is not supported (security fixes only). Create a new issue if this exists on main or supported Python version.
