### ISSUE TITLE
Subclassing threading Lock/RLock: better Exception messages

### ISSUE THREAD

**Issue by jamesbraza** [python/cpython#94077]
**Bug report**

Please see the below minimal repro:

```python
from threading import Lock, RLock

class SubclassLock(Lock):
    pass

class SubclassRLock(RLock):
    pass
```

The subclass of `Lock` emits:

```none
Traceback (most recent call last):
  File "/path/to/file.py", line 3, in <module>
    class SubclassLock(Lock):
TypeError: cannot create 'builtin_function_or_method' instances
```

The subclass of `RLock` emits:

```none
Traceback (most recent call last):
  File "/path/to/file.py", line 6, in <module>
    class SubclassRLock(RLock):
TypeError: function() argument 'code' must be code, not str
```

Both of these messages are relatively cryptic.  I think if Python doesn't support subclassing `Lock`/`RLock`, it should be documented in [threading](https://docs.python.org/3/library/threading.html), and this error message should be more friendly/clear.

**Your environment**

- CPython versions tested on: 3.10.3
- Operating system and architecture: macOS Big Sur 11.5.1

**Comment by sobolevn** [comment]
Right now it is documented that:

> Note that RLock is actually a factory function which returns an instance of the most efficient version of the concrete RLock class that is supported by the platform.

https://docs.python.org/3/library/threading.html#threading.RLock

> Note that Lock is actually a factory function which returns an instance of the most efficient version of the concrete Lock class that is supported by the platform.

https://docs.python.org/3/library/threading.html#threading.Lock

Proper way to do that is:

```python
_LockType = type(threading.Lock())

class MyLock(_LockType): ...
```

But, we can also add this to `Lock` and `RLock` functions:

```python
def Lock():
    """Factory function that returns a new lock."""
    return _allocate_lock()

Lock.__mro_entries__ = lambda bases: (_thread.lock,)

# ...

RLock.__mro_entries__ = lambda bases: (
    _PyRLock if _CRLock is None else _CRLock,
)
```

This way we can actually use it as a base type:

```python
>>> from threading import RLock
>>> class My(RLock): ...
... 
>>> My.__mro__
(<class '__main__.My'>, <class '_thread.RLock'>, <class 'object'>)
>>> 
```

In my opinion, it looks way better than my first example with `_LockType = type(threading.Lock())`

I won't make a PR for this, because I am still not sure if this is worth it.
I didn't ever had subclasses of `Lock` and `RLock` in my code.

I want to hear other opinions first, if others agree - then I will send a PR :)

**Comment by sobolevn** [comment]
I've posted https://discuss.python.org/t/make-threading-lock-rlock-factory-functions-subclassable/24008
