### ISSUE TITLE
`test -R` breaks `test_unittest`: `_overlapped.CreateIoCompletionPort` raises `OSError: [WinError 87] The parameter is incorrect`

### ISSUE THREAD

**Issue by arhadthedev** [python/cpython#94337]
**Bug report**

1. Build CPython with `pcbuild\build -d`
2. Run `python -m test -R 1:1:reflog.txt`
3. `test_unittest` prints many `Error on reading from the event loop self pipe` failures. Stack traces have various intermediate functions but the leaf function is always `CreateIoCompletionPort`.

<details><summary>First lines of the test stdout report</summary>

```text
== CPython 3.12.0a0 (main, Jun 27 2022, 14:00:00) [MSC v.1932 64 bit (AMD64)]
== Windows-10-10.0.19044-SP0 little-endian
== cwd: C:\Users\oleg\Documents\dev\notmine\cpython\build\test_python_8628æ
== CPU count: 4
== encodings: locale=cp1251, FS=utf-8
WARNING: Running tests with --huntrleaks/-R and less than 3 warmup repetitions can give false positives!
0:00:00 Run tests sequentially
0:00:00 [  1/436] test_grammar
beginning 2 repetitions
12
..
test_grammar leaked [6] references, sum=6
0:00:00 [  2/436/1] test_opcodes -- test_grammar failed (reference leak)
beginning 2 repetitions
12
..
test_opcodes leaked [6] references, sum=6
0:00:00 [  3/436/2] test_dict -- test_opcodes failed (reference leak)
beginning 2 repetitions
12
..
test_dict leaked [6] references, sum=6
0:00:03 [  4/436/3] test_builtin -- test_dict failed (reference leak)
beginning 2 repetitions
12
..
test_builtin leaked [6] references, sum=6
0:00:04 [  5/436/4] test_exceptions -- test_builtin failed (reference leak)
beginning 2 repetitions
12
..
test_exceptions leaked [5] references, sum=5
0:00:25 [  6/436/5] test_types -- test_exceptions failed (reference leak)
beginning 2 repetitions
12
..
test_types leaked [6] references, sum=6
0:00:25 [  7/436/6] test_unittest -- test_types failed (reference leak)
beginning 2 repetitions
12
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\case.py", line 584, in _callTearDown
    self.tearDown()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\test_unittest\test_async_case.py", line 49, in tearDown
    support.gc_collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\support\__init__.py", line 737, in gc_collect
    gc.collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 138, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 122, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\runners.py", line 70, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] Параметр задан неверно
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\case.py", line 584, in _callTearDown
    self.tearDown()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\test_unittest\test_async_case.py", line 49, in tearDown
    support.gc_collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\support\__init__.py", line 737, in gc_collect
    gc.collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 138, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 122, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\runners.py", line 70, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] Параметр задан неверно
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\case.py", line 584, in _callTearDown
    self.tearDown()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\test_unittest\test_async_case.py", line 49, in tearDown
    support.gc_collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\support\__init__.py", line 737, in gc_collect
    gc.collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 138, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 122, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\runners.py", line 70, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] Параметр задан неверно
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\case.py", line 584, in _callTearDown
    self.tearDown()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\test_unittest\test_async_case.py", line 49, in tearDown
    support.gc_collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\support\__init__.py", line 737, in gc_collect
    gc.collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 138, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 122, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\runners.py", line 70, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] Параметр задан неверно
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\case.py", line 584, in _callTearDown
    self.tearDown()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\test_unittest\test_async_case.py", line 49, in tearDown
    support.gc_collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\support\__init__.py", line 737, in gc_collect
    gc.collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 138, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 122, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\runners.py", line 70, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] Параметр задан неверно
.Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\case.py", line 584, in _callTearDown
    self.tearDown()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\test_unittest\test_async_case.py", line 49, in tearDown
    support.gc_collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\support\__init__.py", line 737, in gc_collect
    gc.collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 138, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 122, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\runners.py", line 70, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] Параметр задан неверно
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\case.py", line 584, in _callTearDown
    self.tearDown()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\test_unittest\test_async_case.py", line 49, in tearDown
    support.gc_collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\support\__init__.py", line 737, in gc_collect
    gc.collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 138, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 122, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\runners.py", line 70, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] Параметр задан неверно
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\case.py", line 584, in _callTearDown
    self.tearDown()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\test_unittest\test_async_case.py", line 49, in tearDown
    support.gc_collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\support\__init__.py", line 737, in gc_collect
    gc.collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 138, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 122, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\runners.py", line 70, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] Параметр задан неверно
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\case.py", line 584, in _callTearDown
    self.tearDown()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\test_unittest\test_async_case.py", line 49, in tearDown
    support.gc_collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\support\__init__.py", line 737, in gc_collect
    gc.collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 138, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 122, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\runners.py", line 70, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] Параметр задан неверно
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\case.py", line 584, in _callTearDown
    self.tearDown()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\test_unittest\test_async_case.py", line 49, in tearDown
    support.gc_collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\test\support\__init__.py", line 737, in gc_collect
    gc.collect()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 138, in __del__
    self._tearDownAsyncioRunner()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\unittest\async_case.py", line 122, in _tearDownAsyncioRunner
    runner.close()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\runners.py", line 70, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 320, in run_forever
    self.call_soon(self._loop_self_reading)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\proactor_events.py", line 797, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 450, in recv
    self._register_with_iocp(conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Lib\asyncio\windows_events.py", line 743, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] Параметр задан неверно
```

</details>

**Your environment**

- CPython versions tested on: Python 3.12.0a0 bb8b931385ba9df4e01f7dd3ce4575d49f60efdf
- Operating system and architecture: Windows 10 21H2.

**Comment by arhadthedev** [comment]
With this patch:

```diff
diff --git a/Modules/overlapped.c b/Modules/overlapped.c
index e40a52476b..55e13e4d78 100644
--- a/Modules/overlapped.c
+++ b/Modules/overlapped.c
@@ -207,6 +207,8 @@ initialize_function_pointers(void)
  * Completion port stuff
  */

+#include <stdio.h>
+
 /*[clinic input]
 _overlapped.CreateIoCompletionPort

@@ -231,6 +233,7 @@ _overlapped_CreateIoCompletionPort_impl(PyObject *module, HANDLE FileHandle,
     Py_BEGIN_ALLOW_THREADS
     ret = CreateIoCompletionPort(FileHandle, ExistingCompletionPort,
                                  CompletionKey, NumberOfConcurrentThreads);
+    printf("\nCreateIoCompletionPort(%p, %p, %p, %p) == %p; GetLastError() == %d", FileHandle, ExistingCompletionPort, CompletionKey, NumberOfConcurrentThreads, ret, (unsigned)GetLastError());
     Py_END_ALLOW_THREADS

     if (ret == NULL)
```

I got the following result:

```plain
[...]
0:00:23 [  7/436/6] test_unittest -- test_types failed (reference leak)
beginning 2 repetitions
12

CreateIoCompletionPort(FFFFFFFFFFFFFFFF, 0000000000000000, 0000000000000000, 00000000FFFFFFFF) == 0000000000000218; GetLastError() == 0
CreateIoCompletionPort(00000000000002E4, 0000000000000218, 0000000000000000, 0000000000000000) == 0000000000000218; GetLastError() == 0
CreateIoCompletionPort(FFFFFFFFFFFFFFFF, 0000000000000000, 0000000000000000, 00000000FFFFFFFF) == 0000000000000218; GetLastError() == 258
CreateIoCompletionPort(0000000000000344, 0000000000000218, 0000000000000000, 0000000000000000) == 0000000000000218; GetLastError() == 0
CreateIoCompletionPort(FFFFFFFFFFFFFFFF, 0000000000000000, 0000000000000000, 00000000FFFFFFFF) == 0000000000000218; GetLastError() == 258
CreateIoCompletionPort(0000000000000344, 0000000000000218, 0000000000000000, 0000000000000000) == 0000000000000218; GetLastError() == 0
CreateIoCompletionPort(FFFFFFFFFFFFFFFF, 0000000000000000, 0000000000000000, 00000000FFFFFFFF) == 0000000000000330; GetLastError() == 258
CreateIoCompletionPort(0000000000000344, 0000000000000330, 0000000000000000, 0000000000000000) == 0000000000000330; GetLastError() == 0
CreateIoCompletionPort(FFFFFFFFFFFFFFFF, 0000000000000000, 0000000000000000, 00000000FFFFFFFF) == 0000000000000330; GetLastError() == 258
CreateIoCompletionPort(0000000000000218, 0000000000000330, 0000000000000000, 0000000000000000) == 0000000000000330; GetLastError() == 0
CreateIoCompletionPort(FFFFFFFFFFFFFFFF, 0000000000000000, 0000000000000000, 00000000FFFFFFFF) == 0000000000000340; GetLastError() == 258
CreateIoCompletionPort(000000000000032C, 0000000000000340, 0000000000000000, 0000000000000000) == 0000000000000340; GetLastError() == 0
CreateIoCompletionPort(FFFFFFFFFFFFFFFF, 0000000000000000, 0000000000000000, 00000000FFFFFFFF) == 0000000000000340; GetLastError() == 258
CreateIoCompletionPort(000000000000033C, 0000000000000340, 0000000000000000, 0000000000000000) == 0000000000000340; GetLastError() == 0
CreateIoCompletionPort(000000000000033C, 0000000000000340, 0000000000000000, 0000000000000000) == 0000000000000000; GetLastError() == 87Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
[...]
```

The last two lines suggest that we cannot bind the same port to the same file handle twice.

**Comment by kumaraditya303** [comment]
@arhadthedev Can you try again with the latest main?

**Comment by arhadthedev** [comment]
I've performed the same reproduction steps on bcc4cb0c7d5e0590928e74cae86b0a7938c0f74b and now it successes both passes just complaining about already known memory leaks.

<details><summary>First lines of the test stdout report</summary>

```plain
C:\Users\oleg\Documents\dev\notmine\cpython>python -m test -R 1:1:reflog.txt
Running Debug|x64 interpreter...
== CPython 3.12.0a0 (main, Aug 21 2022, 15:00:11) [MSC v.1932 64 bit (AMD64)]
== Windows-10-10.0.19044-SP0 little-endian
== cwd: C:\Users\oleg\Documents\dev\notmine\cpython\build\test_python_1500æ
== CPU count: 4
== encodings: locale=cp1251, FS=utf-8
WARNING: Running tests with --huntrleaks/-R and less than 3 warmup repetitions can give false positives!
0:00:01 Run tests sequentially
0:00:01 [  1/435] test_grammar
beginning 2 repetitions
12
..
test_grammar leaked [2] references, sum=2
0:00:03 [  2/435/1] test_opcodes -- test_grammar failed (reference leak)
beginning 2 repetitions
12
..
test_opcodes leaked [6] references, sum=6
0:00:03 [  3/435/2] test_dict -- test_opcodes failed (reference leak)
beginning 2 repetitions
12
..
test_dict leaked [6] references, sum=6
0:00:07 [  4/435/3] test_builtin -- test_dict failed (reference leak)
beginning 2 repetitions
12
..
test_builtin leaked [6] references, sum=6
0:00:18 [  5/435/4] test_exceptions -- test_builtin failed (reference leak)
beginning 2 repetitions
12
..
test_exceptions leaked [6] references, sum=6
0:00:45 [  6/435/5] test_types -- test_exceptions failed (reference leak)
beginning 2 repetitions
12
..
test_types leaked [6] references, sum=6
0:00:46 [  7/435/6] test_unittest -- test_types failed (reference leak)
beginning 2 repetitions
12
```

</details>

So closing the issue as fixed.
