### ISSUE TITLE
timeit module is too hard to use, and it is not documented well

### ISSUE THREAD

**Issue by 108806** [python/cpython#94335]
```
def benchmark(func):
    def inner(args):
        print(timeit.timeit('func(args)')) # I dont even know what stmt means
    return inner

@benchmark
def quicksort(array):
    """Sort the array by using quicksort."""

    less = []
    equal = []
    greater = []

    if len(array) > 1:
        pivot = array[0]
        for x in array:
            if x < pivot:
                less.append(x)
            elif x == pivot:
                equal.append(x)
            elif x > pivot:
                greater.append(x)

        return sorted(less) + equal + sorted(greater)
    # Note that you want equal ^^^^^ not pivot
    else:
        return array
```

```Traceback (most recent call last):
  File "C:\Users\ansga\PycharmProjects\Benchmark\main.py", line 75, in <module>
    quicksort(test)
  File "C:\Users\ansga\PycharmProjects\Benchmark\main.py", line 19, in inner
    print(timeit.timeit(stmt='func(args)'))
  File "C:\Program Files\Python310\lib\timeit.py", line 234, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "C:\Program Files\Python310\lib\timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
NameError: name 'func' is not defined

Process finished with exit code 1
```

I don't know how to use it with my code, docs are full of garbage unpractical and ugly and unclear examples like this one:
`timeit.timeit('"-".join(map(str, range(100)))', number=10000)
0.23702679807320237`
And i dont fkn know what is going on there and what it has to do with benchmarking the actual function in some idiomatic way.

When I try to do it like: `timeit.timeit('func(args)')` it will say that func is not declared. 
Absolute mess and unintiutive hell.

**Comment by hugovk** [comment]
https://docs.python.org/3/library/timeit.html are the docs in question.

```pycon
>>> timeit.timeit('"-".join(map(str, range(100)))', number=10000)
0.23702679807320237
```

This example shows how long it takes to run the code in that string:
```python
'"-".join(map(str, range(100)))'
```

---

This example relevant for you:


> A callable can also be passed from the [Python Interface](https://docs.python.org/3/library/timeit.html#python-interface):
```pycon
>>> timeit.timeit(lambda: "-".join(map(str, range(100))), number=10000)
0.19665591977536678
```

A "callable" is something that can be called, like your `quicksort` function. In this example, the callable is:

```python
"-".join(map(str, range(100))
```

So you could do something like:

```python
import timeit


def quicksort(array):
    """Sort the array by using quicksort."""

    less = []
    equal = []
    greater = []

    if len(array) > 1:
        pivot = array[0]
        for x in array:
            if x < pivot:
                less.append(x)
            elif x == pivot:
                equal.append(x)
            elif x > pivot:
                greater.append(x)

        return sorted(less) + equal + sorted(greater)
    # Note that you want equal ^^^^^ not pivot
    else:
        return array


print(timeit.timeit(lambda: quicksort([1, 2, 3, 4, 5]), number=10000))
print(timeit.timeit(lambda: quicksort(range(1000)), number=10000))
```

Outputs:
```
0.006743457997799851
5.859863124991534
```

**Comment by iritkatriel** [comment]
This "bug report" has too little useful feedback for us and too much swearing and insults. 

This bug tracker is for reporting things we can improve. If you are struggling to understand something, try asking on user help forums like python-list.  Once you understand it well enough to suggest concrete ways in which the documentation can be improved, it becomes appropriate to create an issue here to let us know.
