### ISSUE TITLE
SystemError invoking copy.deepcopy

### ISSUE THREAD

**Issue by clo-vis** [python/cpython#94390]
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32

```python
import datetime, copy, numpy
copy.deepcopy(numpy.empty_like([datetime.datetime.now()]))
```

```
TypeError: deepcopy() missing 1 required positional argument: 'x'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
...
  File "C:\Program Files\Python310\lib\copy.py", line 153, in deepcopy
    y = copier(memo)
SystemError: <built-in method __deepcopy__ of numpy.ndarray object at 0x000001C918C49EF0> returned a result with an exception set
```

(just reporting because the documentation says "You should report this to the author or maintainer of your Python interpreter.")

**Comment by JelleZijlstra** [comment]
Could you report the full stack race? I suspect it's a bug in numpy instead.

**Comment by clo-vis** [comment]
```
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime, copy, numpy
>>> copy.deepcopy(numpy.empty_like([datetime.datetime.now()]))
TypeError: deepcopy() missing 1 required positional argument: 'x'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python310\lib\copy.py", line 153, in deepcopy
    y = copier(memo)
SystemError: <built-in method __deepcopy__ of numpy.ndarray object at 0x0000021CAD246010> returned a result with an exception set
```

**Comment by mdickinson** [comment]
https://github.com/numpy/numpy/issues/8706 may be related

**Comment by mdickinson** [comment]
At a guess, `itemp` is `NULL` in [this](https://github.com/numpy/numpy/blob/4d057e633408c04c15292ccc9cd11d96e33a90f5/numpy/core/src/multiarray/methods.c#L1636) call:

```
        res = PyObject_CallFunctionObjArgs(deepcopy, itemp, visit, NULL);
```

So yes, almost certainly a NumPy bug.

**Comment by mdickinson** [comment]
Reported downstream at https://github.com/numpy/numpy/issues/21883. I think we can close here.
