### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2070' in position 32: character maps to <undefined>

### ISSUE THREAD

**Issue by RichardErkhov** [python/cpython#94422]
Python 1.10.4, windows 10 64bit
```
>python -m trace --trace moviepymerger.py > test.txt
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\lib\trace.py", line 740, in <module>
    main()
  File "C:\Python310\lib\trace.py", line 728, in main
    t.runctx(code, globs, globs)
  File "C:\Python310\lib\trace.py", line 450, in runctx
    exec(cmd, globals, locals)
  File "moviepymerger.py", line 3, in <module>
    from moviepy.editor import *
  File "C:\Python310\lib\site-packages\moviepy\editor.py", line 24, in <module>
    import imageio
  File "C:\Python310\lib\site-packages\imageio\__init__.py", line 24, in <module>
    from .core import FormatManager, RETURN_BYTES
  File "C:\Python310\lib\site-packages\imageio\core\__init__.py", line 10, in <module>
    from .util import Image, Array, Dict, asarray, image_as_uint, urlopen
  File "C:\Python310\lib\site-packages\imageio\core\util.py", line 10, in <module>
    import numpy as np
  File "C:\Python310\lib\site-packages\numpy\__init__.py", line 154, in <module>
    from . import polynomial
  File "C:\Python310\lib\site-packages\numpy\polynomial\__init__.py", line 116, in <module>
    from .polynomial import Polynomial
  File "C:\Python310\lib\site-packages\numpy\polynomial\polynomial.py", line 87, in <module>
    from ._polybase import ABCPolyBase
  File "C:\Python310\lib\site-packages\numpy\polynomial\_polybase.py", line 18, in <module>
    class ABCPolyBase(abc.ABC):
  File "C:\Python310\lib\site-packages\numpy\polynomial\_polybase.py", line 73, in ABCPolyBase
    "0": "⁰",
  File "C:\Python310\lib\site-packages\numpy\polynomial\_polybase.py", line 73, in ABCPolyBase
    "0": "⁰",
  File "C:\Python310\lib\trace.py", line 575, in localtrace_trace
    print("%s(%d): %s" % (bname, lineno,
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2070' in position 32: character maps to <undefined>
```

**Comment by eryksun** [comment]
You redirected stdout to the file "test.txt". In Windows, the default file encoding is the system code-page encoding, which in your case is code page 1252 (i.e. "cp1252").  You can override standard I/O to use UTF-8 by setting the environment variable `PYTHONIOENCODING=utf-8`. You can override the default for all I/O to use UTF-8 by enabling UTF-8 mode, either via the environment variable `PYTHONUTF8=1` or via the command-line option `-X utf8`.
