### ISSUE TITLE
`Tools/c-analyzer` raises trying to import `pwd`

### ISSUE THREAD

**Issue by arhadthedev** [python/cpython#94723]
The c-analyzer script used to regenerate `Tools/c-analyzer/TODO` tries to import `pwd` module removed by PEP-594:

```
C:\Users\oleg\Documents\dev\notmine\cpython>python Tools/c-analyzer/c-analyzer.py check --format summary
Running Release|x64 interpreter...
Traceback (most recent call last):
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Tools\c-analyzer\c-analyzer.py", line 4, in <module>
    cmd, cmd_kwargs, verbosity, traceback_cm = parse_args()
                                               ^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Tools\c-analyzer\cpython\__main__.py", line 366, in parse_args
    prog=prog or get_prog(),
                 ^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Tools\c-analyzer\c_common\scriptutil.py", line 26, in get_prog
    if _is_standalone(filename):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Tools\c-analyzer\c_common\scriptutil.py", line 81, in _is_standalone
    return fsutil.is_executable(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Tools\c-analyzer\c_common\fsutil.py", line 346, in is_executable
    return _check_mode(st, mode, S_IXANY, user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Tools\c-analyzer\c_common\fsutil.py", line 416, in _check_mode
    _, uid, gid, groups = _get_user_info(user)
                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oleg\Documents\dev\notmine\cpython\Tools\c-analyzer\c_common\fsutil.py", line 390, in _get_user_info
    import pwd
    ^^^^^^^^^^
ModuleNotFoundError: No module named 'pwd'
```

**Comment by eryksun** [comment]
The `spwd` module is deprecated. `pwd` is not deprecated, but it's not available in Windows. The `_get_user_info()` and `_check_mode()` functions are incompatible with Windows.
