### ISSUE TITLE
Python 3.11 -P option changes one aspect of nspkg.pth namespace packages

### ISSUE THREAD

**Issue by hroncok** [python/cpython#94741]
**Bug report**

When trying to add the `-P` flag to Python shebangs in Fedora package, @befeleme discovered that our sphinxcontrib-programoutput fails to build documentation when `/usr/bin/sphinx-build` has `-P` in the shebang. After a lot of debugging, I've discovered that `-P` somewhat breaks the behavior wrt old-school namespace packages with `nspkg.pth` files.

To reproduce, I needed to install a `sphinxcontrib`-namespaced package globally to site-packages. Then, importing another `sphinxcontrib`-namespaced package without `nspkg.pth` from a manually specified `$PYTHONPATH` location fails with `-P`.

```
$ podman run --rm -ti python:3.11.0b3 /bin/bash
...
root@b881d08fc5f2:/# pip install 'sphinxcontrib-htmlhelp==2.0.0'
...
root@b881d08fc5f2:/# ls -1 /usr/local/lib/python3.11/site-packages
...
sphinxcontrib_htmlhelp-2.0.0-py3.9-nspkg.pth
sphinxcontrib_htmlhelp-2.0.0.dist-info
...
root@b881d08fc5f2:/# cd /tmp

root@b881d08fc5f2:/tmp# mkdir -p build/lib/sphinxcontrib/programoutput/
root@b881d08fc5f2:/tmp# touch build/lib/sphinxcontrib/programoutput/__init__.py

root@b881d08fc5f2:/tmp# PYTHONPATH=build/lib python3.11 -c 'import sphinxcontrib.programoutput'
(success)

root@b881d08fc5f2:/tmp# PYTHONPATH=build/lib python3.11 -P -c 'import sphinxcontrib.programoutput'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sphinxcontrib.programoutput'
```

When the import is in a script, it behaves the same:

```
root@b881d08fc5f2:/tmp# cat > script.py
import sphinxcontrib.programoutput

root@b881d08fc5f2:/tmp# PYTHONPATH=build/lib python3.11 script.py
(success)

root@b881d08fc5f2:/tmp# PYTHONPATH=build/lib python3.11 -P script.py 
Traceback (most recent call last):
  File "/tmp/script.py", line 1, in <module>
    import sphinxcontrib.programoutput
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'sphinxcontrib.programoutput'
```

**Your environment**

I wasn't able to reproduce this in venv, only when installing the namespace packages globally to system-wide site-packages. I've reproduced on Fedora as well as in the official python:3.11.0b3 Docker image.

- CPython versions tested on: 3.11.0b3
- Operating system and architecture: Fedora Linux, Debian, x86_64

**Comment by hroncok** [comment]
Interestingly, this makes it import:

```python
import importlib
importlib.invalidate_caches()
import sphinxcontrib.programoutput
```

(I've tried that because I recall some namespace-related cache issues from https://github.com/python/cpython/issues/89866)

**Comment by hroncok** [comment]
I believe this is related to https://github.com/python/cpython/blob/eb0004c27163ec089201c81eb9ece470700be6c7/Lib/importlib/_bootstrap_external.py#L1296-L1299

Without `-P` I seem to recall it works like this:

 1. upon interpreter startup, the `nspkg.pth` file is executed, adding a `_NamespacePath` that only includes `sphinxcontrib` in the global `site-packages`
 2. empty path or the path of the script's directory is added to `sys.path`, invalidating the `_NamespacePath`'s `_last_parent_path`, so importing from other directories works

With, `-P`, (2) does not happen, hence the loaded `_NamespacePath`s are all cached as they were.

**Comment by hroncok** [comment]
The more I think about this problem the more I believe this isn't a regression per se, but rather a limitation of `nspkg.pth`-based namespace packages. Relying on the fact that implicit addition to `sys.path` invalidates the case is probably too fragile and we should figure out a way to invalidate the cache in Fedora, when we need to do it.

**Comment by hroncok** [comment]
Drop the support from Python? I think we could made setuptools to stop producing the nspkg pth files.

**Comment by ericvsmith** [comment]
If you install a PEP-420 namespace package you don't need any .pth files. Certainly PEP-420 doesn't require it (I wrote the PEP), but I'm not sure what setuptools requires. Maybe it always creates them.

**Comment by michel-slm** [comment]
This affects the Fedora build of lazr.config too - tests are run using zope-testrunner, and since lazr.delegates is installed in the system path, but lazr.config is installed to a separate buildroot during packaging, if zope-testrunner is invoked with python -sP it fails to find lazr.config

Failed build: https://koji.fedoraproject.org/koji/buildinfo?buildID=2289006
Fixed build (invoking zope-testrunner using python -m zope.testrunner to avoid the shebang): https://koji.fedoraproject.org/koji/buildinfo?buildID=2289085
