### ISSUE TITLE
error in datetime.timestamp on windows

### ISSUE THREAD

**Issue by kecmen** [python/cpython#94757]
Hi,

i found few similar bugs but all of them seems to be closed in older versions of python.
On windows (10, 64b) I get an `OSError` if I try to get timestamp from `datetime.datetime `object for some dates:

```
>>> datetime.datetime(year=2021, month=11, day=13).timestamp()

1636758000.0

>>> datetime.datetime(year=3021, month=11, day=13).timestamp()

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

OSError: [Errno 22] Invalid argument

>>> datetime.datetime(year=1021, month=11, day=13).timestamp()

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

OSError: [Errno 22] Invalid argument

>>> sys.version

'3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]'

>>> 
```

**Comment by kecmen** [comment]
Hi,

For the 1021 the negative value would make sense I guess.
This is the result on my Ubuntu (64b) machine:

```
>>> import datetime
>>> datetime.datetime(year=2021, month=11, day=13).timestamp()
1636758000.0

>>> datetime.datetime(year=1021, month=11, day=13).timestamp()
-29920237064.0

>>> datetime.datetime(year=3021, month=11, day=13).timestamp()
33193666800.0

>>> import sys
>>> sys.version
'3.8.10 (default, Mar 15 2022, 12:22:08) \n[GCC 9.4.0]'
```
However this is older version (default for the Ubuntu 20.04 LTS) that I must use on the windows machine.

**Comment by pochmann** [comment]
From the [`datetime.timestamp()` documentation](https://docs.python.org/3.9/library/datetime.html#datetime.datetime.timestamp):

> Naive datetime instances are assumed to represent local time and this method relies on the platform C mktime() function to perform the conversion. Since datetime supports wider range of values than mktime() on many platforms, this method **may raise OverflowError for times far in the past or far in the future.**

(Doesn't say OSError, though...)

**Comment by StanFromIreland** [comment]
Duplicates: https://github.com/python/cpython/issues/81708, https://github.com/python/cpython/issues/94414

**Comment by picnixz** [comment]
> thanks, for me it solved the issue. Question is, whether this shouldn't behave the same way like or linux by default.

I think it's platform-specific so I don't think this should be done (unless we do have a bug in the Windows implementation). I'm closing this as a duplicate of https://github.com/python/cpython/issues/81708, but we have a [workaround](https://github.com/python/cpython/issues/94757#issuecomment-1183633735). For the root issue, it appears that it has been located: https://github.com/python/cpython/issues/81708#issuecomment-1284582287.
