### ISSUE TITLE
deepcopy memoryview raises TypeError

### ISSUE THREAD

**Issue by stuaxo** [python/cpython#95081]
**Bug report**

Calling deepcopy on a memoryview raises a TypeError, this looks similar to bug 82474 https://github.com/python/cpython/issues/82474

This also breaks BinaryField when using Django Polymorphic

https://github.com/django-polymorphic/django-polymorphic/issues/524
**Your environment**

- CPython versions tested on:  3.8, 3.10
- Operating system and architecture:  Ubuntu 21.10

```python
>>> a = memoryview(b'123')
>>> from copy import deepcopy
>>> deepcopy(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'memoryview' object
```

**Comment by corona10** [comment]
This issue looks like related to https://bugs.python.org/issue22995

**Comment by corona10** [comment]
@serhiy-storchaka  Is there any reason to prohibit `copy.deepcopy/copy` operations for `memoryview` object while allowing `property` object?

**Comment by serhiy-storchaka** [comment]
There are no reasons to prohibit shallow and deep copying of `memoryview` objects (or I do not know them). And I have not found any mention of `memoryview` objects in https://bugs.python.org/issue22995. Could you explain what did you mean? Did you mean some other issue?

By default, shallow and deep copying use the same mechanism as pickling. If pickling works, copying works automatically, if pickling is impossible, copying does not work by default. But if it is possible to make a copy, it can be implemented explicitly using other mechanisms.

**Comment by corona10** [comment]
> There are no reasons to prohibit shallow and deep copying of memoryview objects (or I do not know them). And I have not found any mention of memoryview objects in https://bugs.python.org/issue22995. Could you explain what did you mean? Did you mean some other issue?

I found the related patch from that issue, Can you please take a look at this comment? 
https://github.com/python/cpython/pull/95082#discussion_r926287551

**Comment by corona10** [comment]
> By default, shallow and deep copying use the same mechanism as pickling. If pickling works, copying works automatically, if pickling is impossible, copying does not work by default. But if it is possible to make a copy, it can be implemented explicitly using other mechanisms.

Okay Thank you for explain :)

**Comment by seperman** [comment]
Hi, any updates on this ticket? Thanks @corona10 and @serhiy-storchaka !
