### ISSUE TITLE
Code objects with non-equal `co_linetable`s compare equal

### ISSUE THREAD

**Issue by 15r10nk** [python/cpython#95150]
# Bug report

``` python
def f(a, b):
    return dict((k.lower(), v) for k, v in a.items()) == dict(
        (k.lower(), v) for k, v in b.items()
    )

f({"a": 5}, {1: 1})
```
output:
``` python
Traceback (most recent call last):
  File "/home/frank/projects/executing/test8.py", line 8, in <module>
    f({"a": 5}, {1: 1})
  File "/home/frank/projects/executing/test8.py", line 2, in f
    return dict((k.lower(), v) for k, v in a.items()) == dict(
                                                         ^^^^^
  File "/home/frank/projects/executing/test8.py", line 2, in <genexpr>
    return dict((k.lower(), v) for k, v in a.items()) == dict(
                 ^^^^^^^
AttributeError: 'int' object has no attribute 'lower'
```
The error should be reported at line 3 and not at line 2, because the integer is passed to `b`

# Your environment

* current cpython 3.11 branch (3a33e9b7a0)
* and the Python 3.11.0b4

**Comment by alexmojaki** [comment]
Simpler reproduction:

```python
[k.lower() for k in "a"], [k.lower() for k in [1]]
```

```python
Traceback (most recent call last):
  File "...", line 1, in <module>
    [k.lower() for k in "a"], [k.lower() for k in [1]]
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "...", line 1, in <listcomp>
    [k.lower() for k in "a"], [k.lower() for k in [1]]
     ^^^^^^^^^
AttributeError: 'int' object has no attribute 'lower'
```

**Comment by brandtbucher** [comment]
Ooh, nice find! The code objects are being "deduplicated" in the compiler, even though they have different column positions.

We need to consider the entire positions table when comparing code objects for equality.
