### ISSUE TITLE
`pip install pip --upgrade` breaks pip

### ISSUE THREAD

**Issue by andry81** [python/cpython#95244]
# Bug report

* `Windows 8.1 x64`
* `python-3.10.5-amd64.exe`

```cmd
C:\Python\x64\310\Scripts>..\python --version
Python 3.10.5

C:\Python\x64\310\Scripts>pip install pip --upgrade
Requirement already satisfied: pip in c:\python\x64\310\lib\site-packages (22.0.4)
Collecting pip
  Downloading pip-22.2-py3-none-any.whl (2.0 MB)
     ---------------------------------------- 2.0/2.0 MB 1.4 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
ERROR: Could not install packages due to an OSError: [WinError 5] Отказано в доступе: 'c:\\python\\x64\\310\\scripts\\pip.exe'
Consider using the `--user` option or check the permissions.


C:\Python\x64\310\Scripts>pip install pip --upgrade
Traceback (most recent call last):
  File "C:\Python\x64\310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\x64\310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\x64\310\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'
```

The issue first issued here: https://github.com/NulAsh/cpython/issues/30

**Comment by eryksun** [comment]
Problems with pip should be reported on the [pip issue tracker](https://github.com/pypa/pip/issues). However, this is a well-known problem with a simple workaround. First restore pip via `python -m ensurepip --upgrade --default-pip`. Then upgrade it via `python -m pip install --upgrade pip`. Do not run this command from the "Scripts" directory. Running it there [may fail](https://github.com/pypa/pip/issues/11278).
