### ISSUE TITLE
unusual behaviour in asyncio.TaskGroup in the presence of GeneratorExit, StopIteration, KeyboardInterrupt and SystemExit

### ISSUE THREAD

**Issue by graingert** [python/cpython#95571]
```python
import gc
import asyncio
import logging

logger = logging.getLogger(__name__)


async def keyboard_interrupt():
    raise KeyboardInterrupt

async def system_exit():
    raise SystemExit

async def task_groups():
    async with asyncio.TaskGroup() as tg:
        tg.create_task(system_exit())
        tg.create_task(keyboard_interrupt())




loop = asyncio.SelectorEventLoop()
task = loop.create_task(task_groups())

while not task.done():
    try:
        loop.run_until_complete(asyncio.sleep(0))
    except (SystemExit, KeyboardInterrupt) as e:
        print(f"{e=}")

print(f"{task=} {task.exception()=}")
loop.close()

print("#######################################################")

async def gen_exit():
    async with asyncio.TaskGroup() as tg:
        await asyncio.get_running_loop().create_future()


loop = asyncio.SelectorEventLoop()
task = loop.create_task(gen_exit())
loop.run_until_complete(asyncio.sleep(0))
del task
gc.collect()

print("#######################################################")
```

gives the following output on 3.12:

```
e=SystemExit()
e=KeyboardInterrupt()
e=SystemExit()
task=<Task finished name='Task-1' coro=<task_groups() done, defined at /home/graingert/projects/cpython/demo.py:14> exception=SystemExit()> task.exception()=SystemExit()
#######################################################
Exception ignored in: <coroutine object gen_exit at 0x7fd62350cd60>
Traceback (most recent call last):
  File "/home/graingert/projects/cpython/demo.py", line 37, in gen_exit
    async with asyncio.TaskGroup() as tg:
  File "/home/graingert/projects/cpython/Lib/asyncio/taskgroups.py", line 134, in __aexit__
    raise me from None
BaseExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<gen_exit() done, defined at /home/graingert/projects/cpython/demo.py:36> wait_for=<Future pending cb=[Task.task_wakeup()]>>
#######################################################
```

**Comment by graingert** [comment]
I think there should be special handling for SystemExit, StopIteration, GeneratorExit and KeyboardInterrupt in that priority order. If you see an exception of higher priority you swap the self._base_error

eg if you get a SystemExit and then a KeyboardInterrupt you should prioritize the KeyboardInterrupt
also if you get a SystemExit(0) then a SystemExit(1) you should prioritize the SystemExit(1)

**Comment by gvanrossum** [comment]
Sure send a PR.

**Comment by vxgmichel** [comment]
I ran into a similar issue with a much simpler example:
```python
import asyncio

async def system_exit():
    raise SystemExit

async def main():
    async with asyncio.TaskGroup() as tg:
        tg.create_task(system_exit())

if __name__ == "__main__":
    asyncio.run(main())
```
This program works as expected (i.e it returns with code `0`) except that it prints the following message in the console:
```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at /home/vinmic/repos/cpython/debug2.py:6> exception=SystemExit()>
Traceback (most recent call last):
  File "/home/vinmic/repos/cpython/Lib/asyncio/runners.py", line 193, in run
    with Runner(debug=debug, loop_factory=loop_factory) as runner:
  File "/home/vinmic/repos/cpython/Lib/asyncio/runners.py", line 62, in __exit__
    self.close()
  File "/home/vinmic/repos/cpython/Lib/asyncio/runners.py", line 70, in close
    _cancel_all_tasks(loop)
  File "/home/vinmic/repos/cpython/Lib/asyncio/runners.py", line 205, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "/home/vinmic/repos/cpython/Lib/asyncio/base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "/home/vinmic/repos/cpython/Lib/asyncio/base_events.py", line 618, in run_forever
    self._run_once()
  File "/home/vinmic/repos/cpython/Lib/asyncio/base_events.py", line 1951, in _run_once
    handle._run()
  File "/home/vinmic/repos/cpython/Lib/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/home/vinmic/repos/cpython/debug2.py", line 7, in main
    async with asyncio.TaskGroup() as tg:
  File "/home/vinmic/repos/cpython/Lib/asyncio/taskgroups.py", line 117, in __aexit__
    raise self._base_error
  File "/home/vinmic/repos/cpython/Lib/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/vinmic/repos/cpython/Lib/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinmic/repos/cpython/Lib/asyncio/base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "/home/vinmic/repos/cpython/Lib/asyncio/base_events.py", line 618, in run_forever
    self._run_once()
  File "/home/vinmic/repos/cpython/Lib/asyncio/base_events.py", line 1951, in _run_once
    handle._run()
  File "/home/vinmic/repos/cpython/Lib/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/home/vinmic/repos/cpython/debug2.py", line 4, in system_exit
    raise SystemExit
SystemExit
```
Note that other similar examples **do not** produce this trace:
- When the exception is raised in the `TaskGroup` body:
  ```python
  async def system_exit():
      raise SystemExit
  
  async def main():
      async with asyncio.TaskGroup() as tg:
          tg.create_task(asyncio.sleep(1))
          await system_exit()
  ```
- When the exception is raised in a `done_callback`:
```python
  def system_exit(_):
      raise SystemExit

  async def main():
      async with asyncio.TaskGroup() as tg:
          tg.create_task(asyncio.sleep(0)).add_done_callback(system_exit)
  ```
Also, note that the error also happens when the exception is caught and another one is re-raised later:
```python
async def system_exit():
    raise SystemExit

async def main():
    try:
        async with asyncio.TaskGroup() as tg:
            tg.create_task(system_exit())
    except SystemExit:
        pass
    await asyncio.sleep(1)
    await system_exit()
```

**Comment by gvanrossum** [comment]
Could *you* send a PR to fix this? (Unfortunately it looks like @graingert is still not available.)

**Comment by vxgmichel** [comment]
> Could you send a PR to fix this?

It's most likely out of my reach. I can provide a patch that *appears* to solve the issue though:

```diff
diff --git a/Lib/asyncio/runners.py b/Lib/asyncio/runners.py
index 1b89236599..1cd0214730 100644
--- a/Lib/asyncio/runners.py
+++ b/Lib/asyncio/runners.py
@@ -115,7 +115,14 @@ def run(self, coro, *, context=None):
 
         self._interrupt_count = 0
         try:
-            return self._loop.run_until_complete(task)
+            while True:
+                try:
+                    return self._loop.run_until_complete(task)
+                except BaseException:
+                    if not task.done():
+                        task.cancel()
+                        continue
+                    raise
         except exceptions.CancelledError:
             if self._interrupt_count > 0:
                 uncancel = getattr(task, "uncancel", None)
```
It's probably a bit naive, but it kind of makes sense: when the run of the main task finishes without the main task being actually done (because a base exception such as `KeyboardError` or `SystemExit` bubbled up from **another** task), we cancel it and run it again. The while-loop is needed because it might take as many tries as the depth of the nested task groups, e.g:
```python
import asyncio

async def level3():
    raise SystemExit

async def level2():
    async with asyncio.TaskGroup() as tg:
        tg.create_task(level3())

async def level1():
    async with asyncio.TaskGroup() as tg:
        tg.create_task(level2())

async def main():
    async with asyncio.TaskGroup() as tg:
        tg.create_task(level1())

if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by gvanrossum** [comment]
Thanks, but since that modifies `runners.Runner.run()` it won't fix the original issue, since that doesn't even use `run()`.

I wonder if these are even the same issue? The OP suggested in a follow-up comment that the problem is due to `_base_error` sticking to the first `BaseException` encountered.

Also, I don't see any similarity between the tracebacks and error messages from your example and the original.

**Comment by vxgmichel** [comment]
> I wonder if these are even the same issue?

I agree, those are most likely two different issues. I just created a follow-up here: #101515

**Comment by YvesDup** [comment]
Occasionaly I am working on this issue https://github.com/python/cpython/issues/93122 and I get the same traceback messages with `Task exception was never retrieved` in `asyncio.run` when `SystemExit` or `KeybordInterrupt` are raised (This is not my initial main problem).

@vxgmichel  It's look like your [first case](https://github.com/python/cpython/issues/95571#issuecomment-1412088211) described above.

To eliminate these warning messages, I wrote a fix in the `_cancel_all_tasks` function of file `runnners.py`. For reminder, this function is called on the `close` method from the `__exit__` method of `Runner` class. The fix adds a try bloc around the call of `asyncio.run_until_complete(gather(*....)`, and in the  dedicated `except` bloc on `SystemExit` or `KeybordInterrupt`, there are:
+ a check of cancelled tasks, 
+ a comsuption of complete task with an exception (no more message 'Task exception ...'), 
+ a new call to the `_cancel_all_tasks` function, if tasks are still pending.

```py
    to_cancel = tasks.all_tasks(loop)
    if not to_cancel:
        return

    for task in to_cancel:
        task.cancel()

    try:
        loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
    except (SystemExit, KeyboardInterrupt):
        # Checks if all pending tasks are cancelled, done or
        # still pending.
        _pending_tasks = False
        for task in to_cancel:
            if task.cancelled():
                continue
            elif task.done():
                # task raises this exception, consumes it
                # now elimintate a warning message 'Task exception ...'
                task.exception()
            else:
                _pending_tasks = True
        # cancels last pending tasks.
        if _pending_tasks:
            _cancel_all_tasks(loop)
        raise

    for task in to_cancel:
        if task.cancelled():
            continue
        if task.exception() is not None:
            loop.call_exception_handler({
                'message': 'unhandled exception during asyncio.run() shutdown',
                'exception': task.exception(),
                'task': task,
            })
```
@vxgmichel I hope this fix will be useful for your case.
Thank you for your feedback.

**Comment by YvesDup** [comment]
> I think there should be special handling for SystemExit, StopIteration, GeneratorExit and KeyboardInterrupt in that priority order. If you see an exception of higher priority you swap the self._base_error
> 
> eg if you get a SystemExit and then a KeyboardInterrupt you should prioritize the KeyboardInterrupt also if you get a SystemExit(0) then a SystemExit(1) you should prioritize the SystemExit(1)

I wonder if `StopIteration` should be replaced by `StopAsyncIteration`. I can send a PR about this feature if the fix is planned for the 3.13 version.
