### ISSUE TITLE
re-entrant call in asyncio.Runner

### ISSUE THREAD

**Issue by graingert** [python/cpython#95592]
asyncio.Runner calls `main_task.cancel()` from a re-entrant context. This task is likely to be at the top of a chain of tasks and futures any of which could be custom.

demo:
```python
import asyncio
import _thread
import threading

class Future(asyncio.Future):
    def add_done_callback(self, *args, **kwargs):
        print("a task is waiting on me")
        super().add_done_callback(*args, **kwargs)

    def cancel(self, *args, **kwargs):
        print("I'm cancelling!")
        super().cancel(*args, **kwargs)


async def print_stuff_soon():
    await asyncio.sleep(0)
    await asyncio.sleep(0)
    await asyncio.sleep(0)
    await asyncio.sleep(0)
    while True:
        print(f"I'm printing!")


async def main():
    asyncio.create_task(print_stuff_soon())
    t = threading.Timer(1, _thread.interrupt_main)
    t.start()
    await Future()

asyncio.run(main())
```

output:

```
a task is waiting on me
I'm printing!
I'm printing!
I'm printing!
I'm printing!
I'm printing!
I'm printing!
I'm printing!
I'm printing!
..... lots of these .....
I'm printing!
I'm printing!
I'm printing!
I'm printing!
I'm printing!
I'm printing!
I'm printing!
I'm printing!
I'm printing!
I'm printing!
I'm printing!
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<print_stuff_soon() done, defined at /home/graingert/projects/custom_cancel.py:15> exception=RuntimeError("reentrant call inside <_io.BufferedWriter name='<stdout>'>")>
Traceback (most recent call last):
  File "/home/graingert/projects/custom_cancel.py", line 21, in print_stuff_soon
    print(f"I'm printing!")
  File "/usr/lib/python3.11/asyncio/runners.py", line 150, in _on_sigint
    main_task.cancel()
  File "/home/graingert/projects/custom_cancel.py", line 11, in cancel
    print("I'm cancelling!")
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>
```

**Comment by graingert** [comment]
Even the default built in asyncio.Future calls `call_soon` which happens to be re-entrant safe in asyncio but isn't required to be in other implementations

**Comment by kumaraditya303** [comment]
This doesn't seem like a issue. Can you provide a case where this breaks without print?
