### ISSUE TITLE
Tarfile extraction does not work on Windows

### ISSUE THREAD

**Issue by ioah86** [python/cpython#95763]
Using Python 3.10.5, there is a scenario where the `extractall` function of `tarfile` is causing an infinite loop for Python on Windows, but not in Linux.

The tar-file where the issue occurred was the one produced by `docker export`, where a file-system is saved as a tar file. Unfortunately, it is too big to upload here, so I will give some commands to get this file.

```
> docker create --name "testcontainer" tomcat
> docker export --output="testtomcat.tar" testcontainer
```
That should produce a file of about 457MB.

Now, using Python 3.10.5 under Windows, the following code-snippet will crash:

```
import tarfile
with tarfile.open("testtomcat.tar") as tarf:
     members_to_extract = [tar_info for tar_info in tarf.getmembers()
                                           if not tar_info.isdev()]
     tarf.extractall(path="/tmp/foo/", members=members_to_extract)
```
The error says: `maximum recursion depth exceeded while calling a Python object`

# Your environment

- CPython versions tested on: Python 3.10.5
- Operating system and architecture: Windows 11 is where it failed, and it works fine with the same python version in Arch Linux with kernel  `Linux 5.15.58-2-lts x86_64`

**Comment by eryksun** [comment]
If the current user isn't allowed to create symlinks, `TarFile.makelink()` instead tries to extract the target of the symlink. It looks for the target in the archive via `TarFile._find_link_target()`. This method contains the following snippet:

```python
        if tarinfo.issym():
            # Always search the entire archive.
            linkname = "/".join(filter(None, (os.path.dirname(tarinfo.name), tarinfo.linkname)))
            limit = None
```

This assumes that the link target is relative to the symlink. For example:

```python
>>> tf = tarfile.open("testtomcat.tar")
>>> ti = tf.getmember('var/run')
>>> ti.name, ti.linkname
('var/run', '/run')
>>> tf._find_link_target(ti).name
'var/run'
```

In the above example, the target is the POSIX absolute path "/run". This gets joined to the directory of the symlink to form "var//run", which is normalized as "var/run". This is the same path that it initially tried to extract. It's thus a recursive loop that eventually raises `RecursionError`.

Extracting "testtomcat.tar" will 'work' (albeit with many broken symlinks) if the current user is allowed to create symbolic links.

**Comment by eryksun** [comment]
In Windows, creating symlinks requires either the current user to have the symlink privilege or the system to be in developer mode. By default, SeCreateSymbolicLinkPrivilege is granted only to the "Administrators" group (S-1-5-32-544). In this case, if User Account Control (UAC) is enabled, getting the privilege requires an elevated logon (i.e. "run as administrator"), except not if the user is an administrator that's excluded from UAC (e.g. the machine's "Administrator" account, S-1-5-21-\<machine ID\>-500). 

That said, SeCreateSymbolicLinkPrivilege can be granted directly to a user, or to a standard group such as "Authenticated Users" (S-1-5-11). In this case, there's no need for either administrator access or developer mode. Privileges can be assigned using "secpol.msc", under "Local Policies" -\> "User Rights Assignment".

**Comment by eryksun** [comment]
Note that POSIX absolute symlink targets such as "/run" are broken in Windows. So is any relative symlink target that uses forward slash as the path separator. Also, a symlink to a directory that doesn't exist at the time the symlink is created will be created incorrectly as a file symlink instead of as a directory symlink, unless `os.symlink()` is passed `target_is_directory=True`. 

A rooted target that uses forward slashes, such as "/run", is broken for the following reasons:

* A rooted path such as "/run" is a relative path in Windows (see the next point). A relative target path in a symlink must only use backslash as the path separator. WinAPI `CreateSymbolicLinkW()` doesn't replace forward slashes with backslashes in a relative target path. The resulting symlink is broken because symlink resolution in the kernel supports only backslash as the path separator. This bug has existed since symlink support was added in Windows Vista 16 years ago. 
* A rooted target such as "\\run" is resolved relative to the volume of the opened path. For example, "E:\\Mount\\SpamVolume\\tomcat\\var\\run" resolves to "E:\\run". On the other hand, if "SpamVolume" is also drive "S:", then "S:\\tomcat\\var\\run" resolves to "S:\\run".  A rooted path without a drive is thus an unreliable target for a symlink.
* An archive doesn't indicate whether a symlink such as "var/run" targets a file or directory, but Windows needs to know this. `os.symlink()` tries to check whether the target is an existing directory. However, in "Modules/posixmodule.c", `_is_absW()` incorrectly returns true for a rooted path such as "/run" (it's not Unix, folks). Thus `_check_dirW()` ends up resolving "/run" against the drive of the *current working directory* instead of against the drive of the symlink.

**Comment by ioah86** [comment]
I just checked... I can confirm that if I am in "developer mode", the error does not occur.

However, it would have been great if there was some form of error instead of the console just dying. Maybe, on Windows, error out with "symlinks not allowed for current user" or so. But that is a design decision the Python team needs to make.

Thank you very much for the quick help.

**Comment by eryksun** [comment]
> However, it would have been great if there was some form of error instead of the console just dying. Maybe, on Windows, error out with "symlinks not allowed for current user" or so. But that is a design decision the Python team needs to make.

`TarFile.makelink()` only does that if the target of the symlink can't be found in the archive. Otherwise it uses copies of archive files/directories instead of creating a symlink: 

```python
            try:
                self._extract_member(self._find_link_target(tarinfo),
                                     targetpath)
            except KeyError:
                raise ExtractError("unable to resolve link inside archive") from None
```
Refer to my first response for the explanation of why `_find_link_target(tarinfo)` is failing with `RecursionError`. It's definitely a bug.

**Comment by wiomoc** [comment]
> This assumes that the link target is relative to the symlink. For example:
> 
> tf = tarfile.open("testtomcat.tar")
> ti = tf.getmember('var/run')
> ti.name, ti.linkname
> ('var/run', '/run')
>  tf._find_link_target(ti).name
> 'var/run'
> 
> In the above example, the target is the POSIX absolute path "/run". This gets joined to the directory of the symlink to form "var//run", which is normalized as "var/run". This is the same path that it initially tried to extract. It's thus a recursive loop that eventually raises `RecursionError`.

This looks like the same Error as described in gh-67417

I also wonder if `TarFile._find_link_target()` should be adjusted to raise a `KeyError` if `tarinfo.linkname` is an absolute path.
Alternatively, an absolute `tarinfo.linkname` could be resolved with the `extraction_root` as hint. e.g.

```python
>>> from pathlib import Path
>>> extraction_root = Path("/tmp").absolute()
>>> linkname = Path("/tmp/log")
>>> linkname.relative_to(extraction_root)
PosixPath('log')
>>> linkname_outside = Path("/etc/log")
>>> linkname_outside.relative_to(extraction_root)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/pathlib.py", line 818, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/etc/log' is not in the subpath of '/tmp' OR one path is relative and the other is absolute.
```
