### ISSUE TITLE
Trackstack includes __aexit__ in contextlib which is not in previous versions

### ISSUE THREAD

**Issue by graingert** [python/cpython#95882]
```python
import contextlib


@contextlib.asynccontextmanager
async def f():
    try:
        yield
    finally:
        pass

async def amain():
    async with f(): 1/0


with contextlib.closing(amain().__await__()) as gen:
    next(gen, None)
```

```
Traceback (most recent call last):
  File "/home/graingert/projects/cpython/demo.py", line 16, in <module>
    next(gen, None)
  File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/graingert/projects/cpython/demo.py", line 7, in f
    yield
  File "/home/graingert/projects/cpython/demo.py", line 12, in amain
    async with f(): 1/0
                    ~^~
ZeroDivisionError: division by zero
```

_Originally posted by @graingert in https://github.com/python/cpython/issues/92118#issuecomment-1209663766_

### Linked PRs
* gh-95883
* gh-100715
* gh-100718

**Comment by graingert** [comment]
see also https://github.com/python/cpython/pull/27024

**Comment by graingert** [comment]
I think the test cases and code for contextlib.contextmanager and contextlib.ExitStack should be automatically generated from the test cases and code for contextlib.asynccontextmanager and contextlib.AsyncExitStack

**Comment by iritkatriel** [comment]
Unassigned myself since you are working on it.
