### ISSUE TITLE
test_multiprocessing_forkserver.py, test_multiprocessing_fork.py and test_multiprocessing_spawn.py gives tracebacks

### ISSUE THREAD

**Issue by sharewax** [python/cpython#96026]
# Bug report
During build RPM for python3.11rc1 I've found tracebacks for tests from test suite `test_multiprocessing_forkserver.py`, `test_multiprocessing_fork.py`, and `test_multiprocessing_spawn.py` :
```
[root@xxx test]# python3.11 test_multiprocessing_forkserver.py
............s..................................................s...............................s.s.s.....s...s...........ss.....s......................................................................................................................................Traceback (most recent call last):
  File "/opt/rh/rh-python311/root/usr/lib64/python3.11/multiprocessing/resource_tracker.py", line 209, in main
.    cache[rtype].remove(name)
KeyError: '/psm_8714e59f'
..............................ssss...............................s.........ss.ss..sss.sss.s.ssss......ss....s.
----------------------------------------------------------------------
Ran 374 tests in 75.001s

OK (skipped=33)
[root@xxx test]# python3.11 test_multiprocessing_spawn.py
............s..............s...................................s...............................s.s.s.....s...s...........ss.....s...............................................................................................ss.....................................Traceback (most recent call last):
  File "/opt/rh/rh-python311/root/usr/lib64/python3.11/multiprocessing/resource_tracker.py", line 209, in main
.    cache[rtype].remove(name)
KeyError: '/psm_e93c9b17'
..............................ssss...............................s.........ss.ss..sss.sss.s.ssss......ss....s.
----------------------------------------------------------------------
Ran 374 tests in 118.379s

OK (skipped=36)

[root@xxx test]# python3.11 test_multiprocessing_fork.py
............s..............s...................................s...............................s.s.s.....s...s...........ss.....s........................................................................................s......ss.....................................Traceback (most recent call last):
  File "/opt/rh/rh-python311/root/usr/lib64/python3.11/multiprocessing/resource_tracker.py", line 209, in main
.    cache[rtype].remove(name)
KeyError: '/psm_1324c68a'
..............................ssss...............................s.........ss.ss..sss.sss.s.ssss......ss....s.
----------------------------------------------------------------------
Ran 374 tests in 67.935s

OK (skipped=37)
```
I suppose, that tracebacks are not ok during test. Or close the bug, if it normal.
Some `KeyError` are present in https://github.com/python/cpython/pull/95396.

# Your environment
Python 3.11.0rc1 (main, Aug 13 2022, 18:23:13) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Centos7 x86_64, python 3.11rc1

**Comment by serhiy-storchaka** [comment]
I seen this output many times, but cannot reproduce locally (on Ubuntu).

It is bad because it looks like an error even if test reports OK. It is mixed with real errors report and make it more difficult to analyze. It can also be a symptom of a problem with resource management.

**Comment by sharewax** [comment]
As for KeyError psm it looks like issues with shared memory. Some things was discussed in https://github.com/python/cpython/issues/91577.
I see that in commit https://github.com/python/cpython/commit/9a458befdd68625d088f4fea7df135a57d147deb was added `resource_tracker`, maybe it's connected somehow.

**Comment by sharewax** [comment]
After some debug print and etc I've found that something wrong in this place
`test/_test_multiprocessing.py`
```
        # Attaching Shared Memory Segment without a name
        with self.assertRaises(ValueError):
            shared_memory.SharedMemory(create=False)
```

```
ERROR: test_shared_memory_cleaned_after_process_termination (__main__.WithProcessesTestSharedMemory.test_shared_memory_cleaned_after_process_termination)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/rh/rh-python311/root/usr/lib64/python3.11/test/_test_multiprocessing.py", line 4327, in test_shared_memory_cleaned_after_process_termination
    smm = shared_memory.SharedMemory(name, create=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/rh/rh-python311/root/usr/lib64/python3.11/multiprocessing/shared_memory.py", line 104, in __init__
    self._fd = _posixshmem.shm_open(
               ^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '/'
```

So we are tried to define shared_memory.SharedMemory without name and not creating it. BUT
and we are going by this thread in file `multiprocessing/shared_memory.py`:
```
        if _USE_POSIX:
            if name is None:
...
            else:
                name = "/" + name if self._prepend_leading_slash else name
                self._fd = _posixshmem.shm_open(
                    name,
                    self._flags,
                    mode=self._mode
                )
                self._name = name
```
so we are trying to open shm on the '/' without any try/except block. 

Or, something another, but issue definitely in 
```
        # Attaching Shared Memory Segment without a name
        with self.assertRaises(ValueError):
            shared_memory.SharedMemory(create=False)
```

**Comment by sergeykolosov** [comment]
I'm not entirely confident yet, but it appears that after 9a458be got merged, the workaround from f604cf1 is no longer needed.

**Comment by sharewax** [comment]
@tiran  is it possible to fix it by reverting workaround as mentioned in comment by @sergeykolosov ?

**Comment by tiran** [comment]
@sharewax Please refrain from pinging core developers on issues to draw their attention. It's distracting. Triagers may ping core devs or assign tickets that are listed as experts in https://devguide.python.org/core-developers/experts/index.html.

**Comment by sharewax** [comment]
sorry for that :(
