### ISSUE TITLE
Shutdown issue on Windows OS

### ISSUE THREAD

**Issue by ttodua** [python/cpython#96067]
# Bug report

On Windows 10/11, if you run this code:

```
import asyncio
import sys
import aiohttp

URLS = [
	# Insert several URLs here, e.g.:
	"https://www.python.org/ftp/python/",
	"https://github.com/python/",
	"https://www.cpan.org/src/5.0/",
	"https://aiohttp.readthedocs.io/",
	"https://example.com/",
]

async def main():
	async with aiohttp.ClientSession() as session:
		await asyncio.wait([fetch(session, url) for url in URLS])
	print("Done.")

async def fetch(session: aiohttp.ClientSession, url: str):
	async with session.get(url):
		print(f"Requested: {url}")

if __name__ == '__main__':
    asyncio.run(main())
```

ends up with: 
```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C9ACE4D240>
Traceback (most recent call last):
  File ".\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__  
    self.close()
  File ".\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close    
    self._loop.call_soon(self._call_connection_lost, None)
  File ".\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon    
    self._check_closed()
  File ".\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

However, if you add the below workaround (before `asyncio.run(main())`): 
 
```
originalShutdownFunc = asyncio.BaseEventLoop.shutdown_default_executor
async def shutdown_default_executor(arg):
    result = await originalMet(arg)
    await asyncio.sleep(0.25)
    return result

asyncio.BaseEventLoop.originalShutdownFunc = shutdown_default_executor
```
then exception is avoided. Another fix could be to add `sleep(0.25)` before [`loop.close` ](https://github.com/python/cpython/blob/main/Lib/asyncio/runners.py#L76)  (_I have also met related misbehaviors [mentioned by others](https://github.com/wbenny/python-graceful-shutdown#beware-of-windows-buggy-proactoreventloop) out there, idk if it's related_)

Do you see any possible fix in asyncio for that, as one of our programs users are experiencing similar issues and we think it might be better to be fixed in core instead of workarounds. tnx

**Comment by ttodua** [comment]
My bad, seems in latest python release (i was on 3.10.4) the issue seems no longer happening.
