### ISSUE TITLE
test_socket:  "RuntimeWarning: received malformed or improperly-truncated ancillary data"

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#96283]
```
% ./python.exe -We -m test -v test_socket

======================================================================
ERROR: testSecondCmsgTruncInData (test.test_socket.RecvmsgIntoRFC3542AncillaryUDP6Test.testSecondCmsgTruncInData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 4266, in testSecondCmsgTruncInData
    msg, ancdata, flags, addr = self.doRecvmsg(
                                ^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 2882, in doRecvmsg
    result = sock.recvmsg_into([buf], *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: received malformed or improperly-truncated ancillary data

======================================================================
ERROR: testSingleCmsgTruncInData (test.test_socket.RecvmsgIntoRFC3542AncillaryUDP6Test.testSingleCmsgTruncInData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 4162, in testSingleCmsgTruncInData
    msg, ancdata, flags, addr = self.doRecvmsg(
                                ^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 2882, in doRecvmsg
    result = sock.recvmsg_into([buf], *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: received malformed or improperly-truncated ancillary data

======================================================================
ERROR: testCmsgTruncLen0 (test.test_socket.RecvmsgIntoSCMRightsStreamTest.testCmsgTruncLen0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3839, in testCmsgTruncLen0
    self.checkTruncatedArray(ancbuf=socket.CMSG_LEN(0), maxdata=0)
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3819, in checkTruncatedArray
    msg, ancdata, flags, addr = self.doRecvmsg(self.serv_sock,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 2882, in doRecvmsg
    result = sock.recvmsg_into([buf], *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: received malformed or improperly-truncated ancillary data

======================================================================
ERROR: testCmsgTruncLen0Plus1 (test.test_socket.RecvmsgIntoSCMRightsStreamTest.testCmsgTruncLen0Plus1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3845, in testCmsgTruncLen0Plus1
    self.checkTruncatedArray(ancbuf=socket.CMSG_LEN(0) + 1, maxdata=1)
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3819, in checkTruncatedArray
    msg, ancdata, flags, addr = self.doRecvmsg(self.serv_sock,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 2882, in doRecvmsg
    result = sock.recvmsg_into([buf], *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: received malformed or improperly-truncated ancillary data

======================================================================
ERROR: testCmsgTruncLen1 (test.test_socket.RecvmsgIntoSCMRightsStreamTest.testCmsgTruncLen1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3851, in testCmsgTruncLen1
    self.checkTruncatedArray(ancbuf=socket.CMSG_LEN(SIZEOF_INT),
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3819, in checkTruncatedArray
    msg, ancdata, flags, addr = self.doRecvmsg(self.serv_sock,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 2882, in doRecvmsg
    result = sock.recvmsg_into([buf], *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: received malformed or improperly-truncated ancillary data

======================================================================
ERROR: testCmsgTruncLen2Minus1 (test.test_socket.RecvmsgIntoSCMRightsStreamTest.testCmsgTruncLen2Minus1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3858, in testCmsgTruncLen2Minus1
    self.checkTruncatedArray(ancbuf=socket.CMSG_LEN(2 * SIZEOF_INT) - 1,
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3819, in checkTruncatedArray
    msg, ancdata, flags, addr = self.doRecvmsg(self.serv_sock,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 2882, in doRecvmsg
    result = sock.recvmsg_into([buf], *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: received malformed or improperly-truncated ancillary data

======================================================================
ERROR: testSecondCmsgTruncInData (test.test_socket.RecvmsgRFC3542AncillaryUDP6Test.testSecondCmsgTruncInData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 4266, in testSecondCmsgTruncInData
    msg, ancdata, flags, addr = self.doRecvmsg(
                                ^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 2791, in doRecvmsg
    result = sock.recvmsg(bufsize, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: received malformed or improperly-truncated ancillary data

======================================================================
ERROR: testSingleCmsgTruncInData (test.test_socket.RecvmsgRFC3542AncillaryUDP6Test.testSingleCmsgTruncInData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 4162, in testSingleCmsgTruncInData
    msg, ancdata, flags, addr = self.doRecvmsg(
                                ^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 2791, in doRecvmsg
    result = sock.recvmsg(bufsize, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: received malformed or improperly-truncated ancillary data

======================================================================
ERROR: testCmsgTruncLen0 (test.test_socket.RecvmsgSCMRightsStreamTest.testCmsgTruncLen0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3839, in testCmsgTruncLen0
    self.checkTruncatedArray(ancbuf=socket.CMSG_LEN(0), maxdata=0)
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3819, in checkTruncatedArray
    msg, ancdata, flags, addr = self.doRecvmsg(self.serv_sock,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 2791, in doRecvmsg
    result = sock.recvmsg(bufsize, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: received malformed or improperly-truncated ancillary data

======================================================================
ERROR: testCmsgTruncLen0Plus1 (test.test_socket.RecvmsgSCMRightsStreamTest.testCmsgTruncLen0Plus1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3845, in testCmsgTruncLen0Plus1
    self.checkTruncatedArray(ancbuf=socket.CMSG_LEN(0) + 1, maxdata=1)
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3819, in checkTruncatedArray
    msg, ancdata, flags, addr = self.doRecvmsg(self.serv_sock,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 2791, in doRecvmsg
    result = sock.recvmsg(bufsize, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: received malformed or improperly-truncated ancillary data

======================================================================
ERROR: testCmsgTruncLen1 (test.test_socket.RecvmsgSCMRightsStreamTest.testCmsgTruncLen1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3851, in testCmsgTruncLen1
    self.checkTruncatedArray(ancbuf=socket.CMSG_LEN(SIZEOF_INT),
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3819, in checkTruncatedArray
    msg, ancdata, flags, addr = self.doRecvmsg(self.serv_sock,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 2791, in doRecvmsg
    result = sock.recvmsg(bufsize, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: received malformed or improperly-truncated ancillary data

======================================================================
ERROR: testCmsgTruncLen2Minus1 (test.test_socket.RecvmsgSCMRightsStreamTest.testCmsgTruncLen2Minus1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3858, in testCmsgTruncLen2Minus1
    self.checkTruncatedArray(ancbuf=socket.CMSG_LEN(2 * SIZEOF_INT) - 1,
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 3819, in checkTruncatedArray
    msg, ancdata, flags, addr = self.doRecvmsg(self.serv_sock,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_socket.py", line 2791, in doRecvmsg
    result = sock.recvmsg(bufsize, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: received malformed or improperly-truncated ancillary data

----------------------------------------------------------------------
```

**Comment by iritkatriel** [comment]
Neither the test nor the code are new. I don't know what brought this about.

**Comment by tiran** [comment]
Ancillary data is a feature of Unix Domain Sockets (AF_UNIX) to send and receive additional information across a Unix socket connection. This includes passing of file descriptors and user credentials. The OS kernel is involved, too. Did you update your OS or libc?

**Comment by iritkatriel** [comment]
I recently updated the os version (Mac). But I don’t know if the issue started only then. I may not have noticed it before.

**Comment by tirkarthi** [comment]
This seems to be a known issue as per @ned-deily's comment https://github.com/python/cpython/issues/68016#issuecomment-1093679390

**Comment by iritkatriel** [comment]
Duplicate of #68016.
