### ISSUE TITLE
pathlib.Path.touch incorrectly raises FileNotFoundError

### ISSUE THREAD

**Issue by automorphis** [python/cpython#96366]
# Bug report

In ipython, the first two calls to `pathlib.Path.touch` succeed but the third fails. I see no reason that it should fail, and if it should, the error raised is incorrect.

```
from pathlib import Path
log_filename = Path('/mnt/c/Users/Michael/OneDrive/PycharmProjects/beta_numbers/logs/perron_numbers_log0.txt')
log_filename.touch() # success
log_filename = Path('/mnt/c/Users/Michael/OneDrive/PycharmProjects/beta_numbers/logs/perron_numbers_log_.txt')
log_filename.touch() # success
log_filename = Path('/mnt/c/Users/Michael/OneDrive/PycharmProjects/beta_numbers/logs/perron_numbers_log_0.txt')
log_filename.touch()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/pathlib.py", line 1166, in touch
    self._accessor.touch(self, mode, exist_ok)
  File "/usr/lib/python3.10/pathlib.py", line 331, in touch
    fd = os.open(path, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/Michael/OneDrive/PycharmProjects/beta_numbers/logs/perron_numbers_log_0.txt'
```

Contents of `/mnt/c/Users/Michael/OneDrive/PycharmProjects/beta_numbers/logs` prior to the first touch:

 - -3_-1_-7.log
 - -7_-29_-43.log
 - -8_-3_-17.log
 - -9_-35_-51.log
 - analyze.log
 - find_close_orbit.log
 - test_log.txt
 - testy.log
 - update_legacy_data.log

# Your environment

- CPython versions tested on: 3.10.4
- Operating system and architecture: Ubuntu 22.04 run on a Windows 10 x64 device through WSL2

**Comment by sobolevn** [comment]
I cannot reproduce it with just regular files on my machine.
Can you please find an example that can be reproduced?
Maybe with docker? 

Right now it is not clear what is going on within your file system.

**Comment by mdboom** [comment]
Does it only happen on the Windows (`/mnt/c/`) filesystem?
