### ISSUE TITLE
ZoneInfo object raises OSError instead of ZoneInfoNotFoundError for timezone input larger than 255 characters

### ISSUE THREAD

**Issue by lleontop** [python/cpython#96463]
# Bug report

According to documentation all calls to ZoneInfo should raise `ValueError` or `ZoneInfoNotFoundError`. 
Creating a ZoneInfo object with an invalid very long timezone (length > 255) an OSError is raised instead (`OSError: [Errno 36] File name too long`). 

I believe that https://github.com/python/cpython/blob/29f1b0bb1ff73dcc28f0ca7e11794141b6de58c9/Lib/zoneinfo/_common.py#L11-L24 should also handle the `OSError` exception raised by open and reraise it to `ZoneInfoNotFoundError`.

Sample code for reproduction:
```
from zoneinfo import ZoneInfo
ZoneInfo("a"*256)
```

# Your environment

- CPython versions tested on: Python 3.10.4
- Operating system and architecture: Debian GNU/Linux 11 (bullseye)

### Linked PRs
* gh-99602

**Comment by sobolevn** [comment]
I cannot reproduce it on macos. I've tried `3.10`, `3.11`, and `3.12`. The result it:

```python
>>> from zoneinfo import ZoneInfo
>>> ZoneInfo("a"*256)
Traceback (most recent call last):
  File "/Users/sobolev/.pyenv/versions/3.10.0/lib/python3.10/zoneinfo/_common.py", line 12, in load_tzdata
    return importlib.resources.open_binary(package_name, resource_name)
  File "/Users/sobolev/.pyenv/versions/3.10.0/lib/python3.10/importlib/resources.py", line 43, in open_binary
    package = _common.get_package(package)
  File "/Users/sobolev/.pyenv/versions/3.10.0/lib/python3.10/importlib/_common.py", line 66, in get_package
    resolved = resolve(package)
  File "/Users/sobolev/.pyenv/versions/3.10.0/lib/python3.10/importlib/_common.py", line 57, in resolve
    return cand if isinstance(cand, types.ModuleType) else importlib.import_module(cand)
  File "/Users/sobolev/.pyenv/versions/3.10.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sobolev/.pyenv/versions/3.10.0/lib/python3.10/zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
```

Trying `docker run --rm -it python:3.10.4-bullseye`. And result is the same. 
Can you please provide more information? Maybe you have some extra settings for the filesystem?

**Comment by lleontop** [comment]
Hi, 

I think the absence of `tzdata` package somehow hides the problem I'm describing originally probably due to exiting sooner. When also installing `tzdata` the error appears. Apologies I missed this info on the original report. 

I tried `docker run --rm -it python:3.10.4-bullseye /bin/sh -c "python -m pip install tzdata && python"` with the reproduction code and the error appears also in docker.

**Comment by sobolevn** [comment]
Thanks, now I can see this error.
I am trying to reproduce it in our CI to learn about `tzdata` package in our buildbots. No luck for now.

But, in the mean time: can you please explain how practical is it to catch this exception?
Are there any timezones that are longer than 255 chars? Maybe this exception should be propagated: it might indicate issues with file system or permissions.

There are too many use-cases for `OSError` to catch it blindly.

**Comment by sobolevn** [comment]
Related https://github.com/python/cpython/issues/85702

**Comment by lleontop** [comment]
You are correct blindly catching `OSError` is not really good and I am not sure what should be the best course of action here. In practice so long timezones shouldn't exist, but if some input reaches this function and __is__ that long somebody implementing only what the documentation mentions might end up with unhandled exceptions (this is how I found this actually from stress testing my application). Maybe a change in the documentation might suffice here, mentioning `OSError` as a possible exception and propagating this as you described also sounds good.

**Comment by FFY00** [comment]
Technically, since this data comes from the `Traversable` abstraction (see [importlib.resources](https://docs.python.org/3/library/importlib.resources.html)), which may be user defined and makes no guarantees about which exceptions can be raise. IMO we should probably blindly catch all (normal -- `Exception`) exceptions and stack them with `ZoneInfoNotFoundError`.

@pganssle do you have any thoughts regarding this?

**Comment by StanFromIreland** [comment]
255 bytes is the max filename length on certain OSs.

https://stackoverflow.com/questions/6571435/limit-on-file-name-length-in-bash

**Comment by ariebovenberg** [comment]
Another related (but a tad pedantic 🙂 ) case that is different depending on whether `tzdata` is installed:

```python
ZoneInfo("__init__.py")
```

with `tzdata` you get `ValueError: Invalid TZif file: magic not found`, because the package data includes python package markers and pycache files. Without `tzdata` installed, you simply get `ZoneInfoNotFoundError`.

The second follows the documented behavior:

> key must be in the form of a relative, normalized POSIX path, with no up-level references. The constructor will raise [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) if a non-conforming key is passed.

`__init__.py` satisfies is a "relative, normalized POSIX path, with no up-level references", so the exception should be `ZoneInfoNotFoundError`.

Note that `ZoneInfo("leapseconds")` also gives a `ValueError` that should be `ZoneInfoNotFoundError`, but this is regardless of whether tzdata is installed.

(tested under python 3.13.2)
