### ISSUE TITLE
Union and isdisjoint operations between self-defined set classes cause segfault on CPython 3.12.0a0

### ISSUE THREAD

**Issue by xiaxinmeng** [python/cpython#96676]
# Crash report

The following code defines a class Myset, then we instance the class and make union and isdisjoint operation. It causes segfault on CPython  3.12.0a0 (Master branch), while it triggers RecursionError on previous versions as expected.

```
from collections.abc import Set
class MySet(Set):
    def __init__(a, itr):
        a.contents = a
    def __contains__(a, x):
        return a in a.contents
    def __iter__(a):
        return iter(a.contents)
    def __len__(a):
        return len([a for a in a.contents])

s1 = MySet((1, 2, 3))
s2 = MySet((3, 4, 5))
s1 = s2 & s2       #crash, segmentation fault
s1.isdisjoint(s2)    # also crash, segmentation fault
```

# Error messages

Error message for CPython Python 3.12.0a0:
```
Segmentation fault (core dumped)
```

Error message for other versions of CPython: Python 3.7.12,Python 3.8.12,Python 3.9.0,Python 3.10.1,Python 3.11.0a7+ 
```
Traceback (most recent call last):
  File "/error/test_arithmetic_Set.py", line 20, in <module>
    s1.isdisjoint(s2)
    ^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 594, in isdisjoint
  File "/error/test_arithmetic_Set.py", line 12, in __iter__
    return iter(a.contents)
           ^^^^^^^^^^^^^^^^
  File "/error/test_arithmetic_Set.py", line 12, in __iter__
    return iter(a.contents)
           ^^^^^^^^^^^^^^^^
  File "/error/test_arithmetic_Set.py", line 12, in __iter__
    return iter(a.contents)
           ^^^^^^^^^^^^^^^^
  [Previous line repeated 988 more times]
RecursionError: maximum recursion depth exceeded
```

# Your environment

Python 3.12.0a0 (main, Sep  6 2022, 20:37:56) [GCC 7.5.0] on linux

**Comment by kumaraditya303** [comment]
I am unable to reproduce on main 2fd7246e97c. How did you compile CPython? What command did you use?

**Comment by xiaxinmeng** [comment]
> I am unable to reproduce on main [2fd7246](https://github.com/python/cpython/commit/2fd7246e97c8cc09b4e3f22933693f9d68f08163). How did you compile CPython? What compiler options did you use?

Thanks, I re-check this crash, this bug seem to  already be fixed on main https://github.com/python/cpython/commit/2fd7246e97c8cc09b4e3f22933693f9d68f08163 and the latest main branch. I downloaded the main branch three days ago (2022.09.06), and installed it with./configure, make, sudo make install.  I am not sure which the compiler it is.

**Comment by sweeneyde** [comment]
I replicated the failure on the main branch on windows, and then bisected back to

> commit cd05d0a423d97be69f9de4650f68f89e99ad68d1
> Author: neonene <53406459+neonene@users.noreply.github.com>
> Date:   Wed Mar 23 09:35:25 2022 +0900
> 
>     bpo-43166: Disable ceval.c optimizations for Windows debug builds (GH-32023)
> 
>     Also increases the stack allocation when run with `python_d.exe` to account for the extra stack checks that are added.

**Comment by MojoVampire** [comment]
I assume you realize your class is *very* weird. You're using `a` to mean `self`, and ignoring any other arguments. So `a.contents` is `a` itself. All of your methods are, by definition, infinitely recursive, invoking themselves forever (well, okay, `__len__` hits `__iter__` to infinitely recurse there instead). Granted, Python shouldn't segfault when you do this, but why include all the irrelevant stuff (e.g. unused `itr` in `__init__`, passing stuff that won't ever be touched) when it's irrelevant to the problem?

**Comment by xiaxinmeng** [comment]
Thanks. Yes it is, the class is weird here. This test is obtained by fuzzing. This may be a corner case, but I sincerely hope it could be helpful to the development of CPython.

**Comment by serhiy-storchaka** [comment]
The crash can no longer be reproduced in 3.13+ (and not even in 3.3+). RecursionError is expected here.
