### ISSUE TITLE
Discrepancy between inplace add and add for list and iterables

### ISSUE THREAD

**Issue by davidlhw** [python/cpython#96770]
# Documentation

Noticed this discrepancy between inplace add and add for list and iterables, not sure if this behavior is purposefully intended or a bug:

The Addition Assignment `+=` operator will concatenate `str` to `list`, treating the `str` as an iterable and behaving like `list.extend(...)` instead of throwing `TypeError`, as one might expect, since the Addition operator `+` throws a `TypeError` when attempting to concatenate `str` to `list`.

<img src="https://user-images.githubusercontent.com/13061926/189630784-33cb4889-2ab6-475f-8d1f-705c8c28a10d.png" alt="code snippet" width="512">

**Comment by DavidLHW** [comment]
@Fidget-Spinner

**Comment by rhettinger** [comment]
It's not bug; it was just a design mistake that we have to live with.

**Comment by ezio-melotti** [comment]
`l + 's'` calls `list_concat`, that only works with other lists and raises an error otherwise:
https://github.com/python/cpython/blob/1756ffd66a38755cd45de51316d66266ae30e132/Objects/listobject.c#L510-L521
`l += 's'` calls `list_inplace_concat` which calls `list_extend`:
https://github.com/python/cpython/blob/1756ffd66a38755cd45de51316d66266ae30e132/Objects/listobject.c#L991-L997
and `list_extend` expects an iterable:
https://github.com/python/cpython/blob/1756ffd66a38755cd45de51316d66266ae30e132/Objects/listobject.c#L917-L920

This is already documented in https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types.
"`s.extend(t)` and `s += t`" are documented together, and `.extend` is documented as taking an iterable.

After more testing however I noticed an inconsistency with another mutable sequence -- `bytearray`s:
```py
>>> b = bytearray()
>>> b + [1, 2, 3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't concat list to bytearray
>>> b += [1, 2, 3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't concat list to bytearray
>>> b.extend([1, 2, 3])
>>> b[0:3] = [3, 2, 1]
>>> b
bytearray(b'\x03\x02\x01')
```

Perhaps we could add a note to the linked table to describe this.

**Comment by gvanrossum** [comment]
I think it will be difficult to change the behavior of list here, since it's been like that for three decades. For bytearray I could see allowing `b += [1,2,3]`.

**Comment by serhiy-storchaka** [comment]
I agree, that it is accidentally behavior which is hard to change now, but extending `+=` for `bytearray` would make `b += array('I', [1, 2, 3])` ambiguous. `+=` for `bytearray` is already generic -- it accepts any object supporting the buffer protocol. `+=` for `list` accepts any object supporting the iterable protocol, and `+=` for `tuple` only accepts a tuple.

It is old known. I am sure that there was one or more closed issues for this.

**Comment by gvanrossum** [comment]
Why would `b += array('I', [1, 2, 3])` become ambiguous? `b.extend(array('I', [1, 2, 3]))` already means something different from `b.extend([1, 2, 3])` (since when `b +=` and `b.extend` are both defined, they do the same thing).
