### ISSUE TITLE
Inconsistant behavior of .readable() and .writable() on io.IOBase

### ISSUE THREAD

**Issue by mcleantom** [python/cpython#96780]
# Bug report

The methods `.readble()` and `.writable()` on `io.IOBase` should return a boolean representing if the file can be read from/written to. However, calling `.readable()` on a closed IO file object causes a `ValueError`, whereas calling `.writable()` on a closed file returns `False` if the file was opened with just read permissions, but raises `ValueError` if it was opened with read and write permissions.

Make a folder with a text file in, then run:
```
f = open("hello.txt")
print(f.writable())
print(f.readable())
f.close()
print(f.writable())
print(f.readable())
```
This will output:
```
False
True
False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: I/O operation on closed file
```
Then doing a similar thing, but with `w+` permissions

```
f = open("hello.txt", "w+")
print(f.writable())
print(f.readable())
f.close()
print(f.writable())
print(f.readable())
```
Will output
```
True
True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: I/O operation on closed file
```

# Your environment
- CPython versions tested on: 3.10.4
- Operating system and architecture: Windows 64bit

**Comment by eryksun** [comment]
The `readable()` and `writable()` methods of `io.IOBase` are mixins. The base implementations return `False`. It's up to a subclass to override this as appropriate. `io.BufferedReader` overrides `readable()`, and `io.BufferedWriter` overrides `writable()`, while `io.BufferedRandom` overrides them both. The `readable()` and `writable()` methods could be consistently implemented for all three types on `io.BufferedIOBase`. Then only `io.BufferedRWPair` would need to override them specially, to forward the call either to the raw reader or the raw writer.

**Comment by sobolevn** [comment]
Documentation does not mention any exceptions.

```
readable()

    Return True if the stream can be read from. If False, read() will raise [OSError](https://docs.python.org/3/library/exceptions.html#OSError).

writable()

    Return True if the stream supports writing. If False, write() and [truncate()](https://docs.python.org/3/library/io.html#io.IOBase.truncate) will raise [OSError](https://docs.python.org/3/library/exceptions.html#OSError).
```

Originally added in https://bugs.python.org/issue15841 or https://github.com/python/cpython/issues/60045

It is not clear to me: why this just does not return `False`. But, it is unlikely that we can change this: too many releases count on this behaviour.
