### ISSUE TITLE
unittest.mock does not work on WebAssembly build of CPython

### ISSUE THREAD

**Issue by treyhunner** [python/cpython#96883]
# Bug report

Use CPython compiled for WebAssembly and then import `unittest.mock`

Or visit [this page](https://pym.dev/p/2qh9v/) and click the "Run in Browser" button to see the error.

The error shown is:

```
Traceback (most recent call last):
  File "//__main__.py", line 2, in <module>
    import unittest.mock
  File "/home/runner/work/cpython-wasm-test/cpython-wasm-test/cpython/Lib/unittest/mock.py", line 26, in <module>
  File "/home/runner/work/cpython-wasm-test/cpython-wasm-test/cpython/Lib/asyncio/__init__.py", line 8, in <module>
  File "/home/runner/work/cpython-wasm-test/cpython-wasm-test/cpython/Lib/asyncio/base_events.py", line 18, in <module>
ModuleNotFoundError: No module named 'concurrent'
```

This error seems to only occur on the WebAssembly build for the browser (the Node build allows `unittest.mock` to be imported as expected).

# Your environment

- CPython versions tested on: 3.11.0rc2
- Operating system and architecture: WebAssembly

**Comment by brettcannon** [comment]
@tiran can this issue be closed?

**Comment by treyhunner** [comment]
Closing, as `unittest.mock` works for me now
