### ISSUE TITLE
`len` built-in overwritten in `ssl.py` leading to "'int' object is not callable" error

### ISSUE THREAD

**Issue by pn** [python/cpython#97558]
# Bug report

I experienced a crash:
```
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1235, in sendall
    amount = len(byte_view)
TypeError: 'int' object is not callable
```

Looks like `len` built-in function is overwritten by an int in one of `read` methods in the same file:
> def read(self, **len**=1024, buffer=None):

Following patch fixes the issue for me:
```diff
908c908
<     def read(self, len=1024, buffer=None):
---
>     def read(self, _len=1024, buffer=None):
915c915
<             v = self._sslobj.read(len, buffer)
---
>             v = self._sslobj.read(_len, buffer)
917c917
<             v = self._sslobj.read(len)
---
>             v = self._sslobj.read(_len)
1121c1121
<     def read(self, len=1024, buffer=None):
---
>     def read(self, _len=1024, buffer=None):
1130c1130
<                 return self._sslobj.read(len, buffer)
---
>                 return self._sslobj.read(_len, buffer)
1132c1132
<                 return self._sslobj.read(len)
---
>                 return self._sslobj.read(_len)
```

# Your environment

- CPython versions tested on: 3.10.7
- Operating system and architecture: MacOS 12.5 (21G72) M1

I searched opened issues and PRs, but did not find this issue reported yet.

**Comment by vstinner** [comment]
> I experienced a crash:

Can you please provide the whole traceback? I don't see the relationship between the ssl read() method overridding len() built-in function and the ssl sendall() method.

**Comment by pn** [comment]
@vstinner, here is more complete stack trace I can share (deleted part related to private project).
```
    async for doc in cursor:
  File "/Users/pawel/Library/Caches/pypoetry/virtualenvs/project-V3vI678V-py3.10/lib/python3.10/site-packages/motor/core.py", line 1249, in next
    if self.alive and (self._buffer_size() or await self._get_more()):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/pawel/Library/Caches/pypoetry/virtualenvs/project-V3vI678V-py3.10/lib/python3.10/site-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__send_message(q)
  File "/Users/pawel/Library/Caches/pypoetry/virtualenvs/project-V3vI678V-py3.10/lib/python3.10/site-packages/pymongo/cursor.py", line 1052, in __send_message
    response = client._run_operation(
  File "/Users/pawel/Library/Caches/pypoetry/virtualenvs/project-V3vI678V-py3.10/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1267, in _run_operation
    return self._retryable_read(
  File "/Users/pawel/Library/Caches/pypoetry/virtualenvs/project-V3vI678V-py3.10/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1371, in _retryable_read
    return func(session, server, sock_info, read_pref)
  File "/Users/pawel/Library/Caches/pypoetry/virtualenvs/project-V3vI678V-py3.10/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1263, in _cmd
    return server.run_operation(
  File "/Users/pawel/Library/Caches/pypoetry/virtualenvs/project-V3vI678V-py3.10/lib/python3.10/site-packages/pymongo/server.py", line 114, in run_operation
    sock_info.send_message(data, max_doc_size)
  File "/Users/pawel/Library/Caches/pypoetry/virtualenvs/project-V3vI678V-py3.10/lib/python3.10/site-packages/pymongo/pool.py", line 786, in send_message
    self._raise_connection_failure(error)
  File "/Users/pawel/Library/Caches/pypoetry/virtualenvs/project-V3vI678V-py3.10/lib/python3.10/site-packages/pymongo/pool.py", line 784, in send_message
    self.sock.sendall(message)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1235, in sendall
    amount = len(byte_view)
TypeError: 'int' object is not callable
```

The version of pymongo is 4.1.1

Also I should have mentioned that the crash is happening **only** during debugging of the project.

**Comment by chinmaygupta28** [comment]
Experiencing a similar issue -

```
error An HTTP Client raised an unhandled exception: 'int' object is not callable for cr_312781580, Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/site-packages/botocore/httpsession.py\", line 448, in send
    urllib_response = conn.urlopen(
  File \"/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 703, in urlopen
    httplib_response = self._make_request(
  File \"/usr/local/lib/python3.10/site-packages/newrelic/hooks/external_urllib3.py\", line 32, in _nr_wrapper_make_request_
    return wrapped(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 386, in _make_request
    self._validate_conn(conn)
  File \"/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 1040, in _validate_conn
    conn.connect()
  File \"/usr/local/lib/python3.10/site-packages/urllib3/connection.py\", line 416, in connect
    self.sock = ssl_wrap_socket(
  File \"/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 424, in ssl_wrap_socket
    context.set_alpn_protocols(ALPN_PROTOCOLS)
  File \"/usr/local/lib/python3.10/ssl.py\", line 566, in set_alpn_protocols
    if len(b) == 0 or len(b) > 255:
TypeError: 'int' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/code/app/aws_utils/dynamo_db.py\", line 188, in update_multi_attributes
    response = table.update_item(
  File \"/usr/local/lib/python3.10/site-packages/boto3/resources/factory.py\", line 580, in do_action
    response = action(self, *args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/boto3/resources/action.py\", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File \"/usr/local/lib/python3.10/site-packages/botocore/client.py\
```

**Comment by iritkatriel** [comment]
@pn We need a complete repro for this issue (and a unit test) if we are going to make the change you suggest.  Will close this issue if you are not able to provide that.

**Comment by vstinner** [comment]
For me, ssl.py is fine. It's ok to have a function with a parameter called len, it only overrides the "len" variable name in this function, not in the whole module. The patch is for the read() method, whereas it's the send() method which has a "len" parameter. So the bug is not in ssl but somewhere else. Moreover, the bug was only seen when a debugger is used, which is suspicious. Maybe the debugger changes the behavior of the code.
