### ISSUE TITLE
`test_asyncio` failures in the "Ubuntu with SSL" tests

### ISSUE THREAD

**Issue by ezio-melotti** [python/cpython#97894]
```pytb
1 test failed:
    test_asyncio
0:01:38 load avg: 0.80
0:01:38 load avg: 0.80 Re-running failed tests in verbose mode
0:01:38 load avg: 0.80 Re-running test_asyncio in verbose mode (matching: test_eof_feed_when_closing_writer, test_wait_closed_on_close)
Warning -- Unraisable exception
Exception ignored in: <coroutine object StreamTests2.test_eof_feed_when_closing_writer at 0x7fcf806a1cd0>
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/warnings.py", line 537, in _warn_unawaited_coroutine
    warn(msg, category=RuntimeWarning, stacklevel=2, source=coro)
RuntimeWarning: coroutine 'StreamTests2.test_eof_feed_when_closing_writer' was never awaited
test_eof_feed_when_closing_writer (test.test_asyncio.test_streams.StreamTests2.test_eof_feed_when_closing_writer) ... ERROR
Warning -- Unraisable exception
Exception ignored in: <coroutine object StreamTests2.test_wait_closed_on_close at 0x7fcf806ced50>
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/warnings.py", line 537, in _warn_unawaited_coroutine
    warn(msg, category=RuntimeWarning, stacklevel=2, source=coro)
RuntimeWarning: coroutine 'StreamTests2.test_wait_closed_on_close' was never awaited
test_wait_closed_on_close (test.test_asyncio.test_streams.StreamTests2.test_wait_closed_on_close) ... ERROR

======================================================================
ERROR: test_eof_feed_when_closing_writer (test.test_asyncio.test_streams.StreamTests2.test_eof_feed_when_closing_writer)
----------------------------------------------------------------------
DeprecationWarning: It is deprecated to return a value!=None from a test case (<bound method StreamTests2.test_eof_feed_when_closing_writer of <test.test_asyncio.test_streams.StreamTests2 testMethod=test_eof_feed_when_closing_writer>>)

======================================================================
ERROR: test_wait_closed_on_close (test.test_asyncio.test_streams.StreamTests2.test_wait_closed_on_close)
----------------------------------------------------------------------
DeprecationWarning: It is deprecated to return a value!=None from a test case (<bound method StreamTests2.test_wait_closed_on_close of <test.test_asyncio.test_streams.StreamTests2 testMethod=test_wait_closed_on_close>>)

----------------------------------------------------------------------
Ran 2 tests in 0.031s

FAILED (errors=2)
```

This broke after this PR was merged:
* https://github.com/python/cpython/pull/93369#issuecomment-1267363937

(It was reported in the comments, but I'm creating this issue for visibility, since after noticing the failure in an unrelated PR I looked at the open issues and couldn't find anything.)

(cc @kumaraditya303 @gvanrossum @arhadthedev)

**Comment by gvanrossum** [comment]
I was going to wait until tomorrow morning to revert this, to give the author some more time to fix it. But if it’s problem go Shetland revert it.
