### ISSUE TITLE
Occasional incorrect chaining of CancelledError when calling 'cancel' on result of 'asyncio.gather'

### ISSUE THREAD

**Issue by vladima** [python/cpython#97907]
```python
import asyncio

async def f1():
    await asyncio.sleep(1)

async def f2():
    return 42

async def main():
    # case 1
    gfut = asyncio.gather(f1(), f2(), return_exceptions=True)
    # case 2
    #gfut = asyncio.gather(f2(), f1(), return_exceptions=True)
    await asyncio.sleep(0.1)
    gfut.cancel("my message")
    await gfut

asyncio.run(main())

# case 1

#Traceback (most recent call last):
#  File "/Users/vladima/Sources/gather.py", line 14, in main
#    print(await gfut)
#asyncio.exceptions.CancelledError
#
#During handling of the above exception, another exception occurred:
#
#Traceback (most recent call last):
#  File "/Users/vladima/Sources/gather.py", line 16, in <module>
#    asyncio.run(main())
#  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
#    return loop.run_until_complete(main)
#  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
#    return future.result()
#asyncio.exceptions.CancelledError

# case 2
#Traceback (most recent call last):
#  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 605, in sleep
#    return await future
#asyncio.exceptions.CancelledError: my message

#During handling of the above exception, another exception occurred:

#Traceback (most recent call last):
#  File "/Users/vladima/Sources/gather.py", line 14, in main
#    print(await gfut)
#asyncio.exceptions.CancelledError
#
#During handling of the above exception, another exception occurred:
#
#Traceback (most recent call last):
#  File "/Users/vladima/Sources/gather.py", line 16, in <module>
#    asyncio.run(main())
#  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
#    return loop.run_until_complete(main)
#  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
#    return future.result()
#asyncio.exceptions.CancelledError
```

Currently traceback and description parts of `CancelledError` depend upon the order of arguments that were passed into `asyncio.gather`. The reason I believe is [this](https://github.com/python/cpython/blob/main/Lib/asyncio/tasks.py#L812): here `fut` would be bound to the last item in `children` which might or might not correspond to the cancelled task and instead it should probably be one of tasks that were actually cancelled  (which is still not ideal since there might be many of them but I guess with `gather` it is as good as it can be).

### Linked PRs
* gh-133243

**Comment by akulakov** [comment]
Note that `msg` argument to cancel() is deprecated in 3.11 and will be removed in the future, so once that happens it will be just that traceback is different - not sure if that's an issue that needs a fix.

**Comment by gvanrossum** [comment]
Actually on the final 3.11 release cancel(msg) will be undeprecated — we had a last minute change of heart. So if there’s an issue it may have to be addressed — in 3.12, probably.

**Comment by akulakov** [comment]
@gvanrossum in that case should I remove the deprecation warning from latest dev branch, or that's already planned to be done by someone?

**Comment by gvanrossum** [comment]
We already removed it. 
https://github.com/python/cpython/pull/98006

**Comment by gvanrossum** [comment]
On the original issue, I suppose we could do better -- a PR would be appreciated.
