### ISSUE TITLE
dataclass with slots=True, init=False raises AttributeError

### ISSUE THREAD

**Issue by noskill** [python/cpython#98247]
**Python 3.10.4**
dataclass with slots=True, init=False raises AttributeError on attribute access
```
from dataclasses import dataclass

@dataclass(slots=True, init=False)
class WorldState:
    is_mission_running: bool = False

w = WorldState()
w.is_mission_running
```
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   AttributeError: 'WorldState' object has no attribute 'is_mission_running'

**Comment by OOFLORDISME** [comment]
A tip is to declare your variables at the beginning of your code that way someone else knows where they are and how to debug the code.

**Comment by ericvsmith** [comment]
Interesting. By specifiying `init=False`, you're taking on responsibility for what dataclass's supplied `__init__` does. One of the things it does is assign to all of the instance variables when `slots=True`. I think it's on you to do that in this case. I don't see how dataclasses can help here, but I'm open to discussion about it.

**Comment by noskill** [comment]
yeah, it makes sense, but now i am confused why the same code works with slots=False, init=False 

```
>>> @dataclass(slots=False, init=False)
... class WorldState:
...     is_mission_running: bool = True
... 
>>> w = WorldState()
>>> w.is_mission_running
True
```

**Comment by ericvsmith** [comment]
> yeah, it makes sense, but now i am confused why the same code works with slots=False, init=False

In case it's not clear: it's because with `slots=False`, `x.is_mission_running` refers to `WorldState.is_mission_running`. This attribute exists and is `False`. But with `slots=True`,  the newly created `WorldState` class doesn't have this attribute. The more I think about it, the more I think the right thing to do is to copy any field's default value from the old class to the new class, and stop doing the instance assignment of default values in the generated `__init__`. But this change is probably user visible, so maybe I shouldn't backport it to 3.10 and 3.11. I'm still mulling it over.

**Comment by noskill** [comment]
Thank you. I am closing the issue since the behaviour is consistent with what you get with defining \_\_slots\_\_ manually and not defining \_\_init\_\_

```
>>> class WorldState:
...     __slots__ = ['is_mission_running']
... 
>>> w = WorldState()
>>> w.is_mission_running
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'WorldState' object has no attribute 'is_mission_running'
```

**Comment by ericvsmith** [comment]
I'm going to leave it open, if that's okay. I'm leaning towards changing dataclass's behavior here to match the experience if you don't use slots.

**Comment by nstarman** [comment]
We've run into this issue at Astropy, where we're trying to make some objects lighter-weight using `slots`, but can't because they are dataclasses.
