### ISSUE TITLE
Intermittent semaphore cleanup issues when using multiprocessing forkserver option

### ISSUE THREAD

**Issue by aggieNick02** [python/cpython#98268]
# Bug report

I recently changed a program that makes use of multiprocessing and semaphores to use the forkserver start option.

I've noticed that on program exit, I will intermittently get a long list of ignored exceptions and complaints from the multiprocessing resource_tracker that semaphores appear to be leaked. I'll see many of these:

```Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
```
and then
```
/usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 109 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/usr/lib/python3.8/multiprocessing/resource_tracker.py:229: UserWarning: resource_tracker: '/mp-li69sgfk': [Errno 2] No such file or directory
  warnings.warn('resource_tracker: %r: %s' % (name, e))
```
Unfortunately at this point I can't reproduce reliably with my large program, much less a toy reproduction. But I've spent a few hours examining the code and wanted to see if others had ideas.

The fact that `sem_unlink` is failing means that the semaphores have already been unlinked somehow. The only code I see that calls `sem_unlink` is the `SemLock._cleanup` method in `multiprocessing/synchronize.py`. Any ideas what else could cause the unlinking to have already happened?

The complaint from the `resource_tracker` is just because the semaphores are not unregistered in the last line of `_cleanup` because the `sem_unlink(name)` line throws.

The program and its processes are exiting cleanly when this happens. My processes derive from multiprocessing.Process and use a number of multiprocessing constructs, including `RLock`.

# Your environment
Ubuntu 20.04.4 LTS
Python 3.8.10

**Comment by aggieNick02** [comment]
I stumbled onto the answer with some incredible google-luck a few hours after posting here. My program was being run as a standard user (myself) via supervisord. It turns out that, by default, systemd will remove IPC resources when a user logs out. So the named semaphores disappear while the program is running if I log out of my last interactive shell. A somewhat noisy shutdown log doesn't seem all that bad considering what we now know has happened.

systemd does not consider this a bug. A lot of people disagree. Oracle has changed the default in their Linux to avoid the issue.

Closing since this has nothing to do with Python. Hopefully the stack trace and terms here will help others that may hit this.

The blog I stumbled on that explained the core issue is: https://webuild.envato.com/blog/the-tale-of-the-missing-semaphore/

It has links to others affected by the issue. One of those links to the systemd response: https://github.com/systemd/systemd/issues/2039
