### ISSUE TITLE
Test failure: __stdout__.encoding != __stderr__.encoding

### ISSUE THREAD

**Issue by WickWeiWkSpace** [python/cpython#98474]
Hi All,

Python3 failed to run test_sys on release and debug configuration with MSVC on windows. it can be reproduced on 9331087 on master branch. Could you please help look at this issue?

Environment:
VS 2019 + Windows Server 2019

Repro steps:
1. git clone https://github.com/python/cpython F:\gitP\python\cpython
2. cd F:\gitP\python\cpython\PCBuild
3. get_externals.bat --clean-only 2>&1
4. echo f | xcopy F:\Agent\_work\5\s\src\tools\nuget\nuget.exe F:\gitP\python\cpython\externals\nuget.exe /k/r/e/i/s/c/h/f/y
5. build -d -e -r --no-tkinter -v "/p:PlatformToolset=v142" "/p:WindowsTargetPlatformVersion=10.0.18362.0" 2>&1
6. rt -d -q -x test_asyncio test_distutils test_importlib test_peg_generator test_tools test_socket test_compileall 2>&1

Error info:
[debug_test.log](https://github.com/python/cpython/files/9828065/debug_test.log)

== Tests result: FAILURE ==

384 tests OK.

1 test failed:
    test_sys

44 tests skipped:
    test_curses test_dbm_gnu test_dbm_ndbm test_devpoll test_epoll
    test_fcntl test_fork1 test_gdb test_grp test_idle test_ioctl
    test_kqueue test_multiprocessing_fork
    test_multiprocessing_forkserver test_nis test_openpty
    test_ossaudiodev test_pipes test_poll test_posix test_pty test_pwd
    test_readline test_resource test_smtpnet test_socketserver
    test_spwd test_syslog test_tcl test_threadsignals test_tix test_tk
    test_ttk_guionly test_ttk_textonly test_turtle test_urllib2net
    test_urllibnet test_wait3 test_wait4 test_winsound test_xmlrpc_net
    test_xxlimited test_xxtestfuzz test_zipfile64

Total duration: 33 min 10 sec
Tests result: FAILURE

**Comment by sweeneyde** [comment]
Can you run with the verbose flag (`rt test_sys -v`) so we can see the particular assertion that is failing?

**Comment by WickWeiWkSpace** [comment]
> Can you run with the verbose flag (`rt test_sys -v`) so we can see the particular assertion that is failing?

Ok, I did it. Look at the log.
[test.log](https://github.com/python/cpython/files/9849743/test.log)

**Comment by sweeneyde** [comment]
Copy-pasting the failure here for convenience:
```
======================================================================
FAIL: test_43581 (test.test_sys.SysModuleTest.test_43581)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\gitP\python\cpython\Lib\test\test_sys.py", line 643, in test_43581
    self.assertEqual(sys.__stdout__.encoding, sys.__stderr__.encoding)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'cp1252' != 'utf-8'
- cp1252
+ utf-8


----------------------------------------------------------------------
```
Potentially similar to https://github.com/python/cpython/issues/69889.

**Comment by sweeneyde** [comment]
I can reliably reproduce in powershell:


```
PS C:\Users\sween\Source\Repos\cpython2\cpython> .\PCbuild\rt.bat -d -q test_sys 2>&1
```
```
C:\Users\sween\Source\Repos\cpython2\cpython>"C:\Users\sween\Source\Repos\cpython2\cpython\PCbuild\amd64\python_d.exe"  -u -Wd -E -bb -m test  test_sys
0:00:00 Run tests sequentially
0:00:00 [1/1] test_sys
test_sys failed (1 failure)

== Tests result: FAILURE ==

1 test failed:
    test_sys

Total duration: 2.6 sec
Tests result: FAILURE
.\PCbuild\rt.bat : test test_sys failed -- Traceback (most recent call last):
At line:1 char:1
+ .\PCbuild\rt.bat -d -q test_sys 2>&1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (test test_sys f...ent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

  File "C:\Users\sween\Source\Repos\cpython2\cpython\Lib\test\test_sys.py", line 657, in test_43581
    self.assertEqual(sys.__stdout__.encoding, sys.__stderr__.encoding)
AssertionError: 'utf-8' != 'cp1252'
- utf-8
+ cp1252
```

But the test passes when I run from cmd.exe:

```
C:\Users\sween\Source\Repos\cpython2\cpython>.\PCbuild\rt.bat -d -q test_sys 2>&1
```
```
C:\Users\sween\Source\Repos\cpython2\cpython>"C:\Users\sween\Source\Repos\cpython2\cpython\PCbuild\amd64\python_d.exe"  -u -Wd -E -bb -m test  test_sys
0:00:00 Run tests sequentially
0:00:00 [1/1] test_sys

== Tests result: SUCCESS ==

1 test OK.

Total duration: 2.6 sec
Tests result: SUCCESS
```

**Comment by sweeneyde** [comment]
The fix from https://github.com/python/cpython/issues/69889 was applied to Python 2.7, but Python 3. Maybe a similar fix would work now.

**Comment by WickWeiWkSpace** [comment]
> The fix from #69889 was applied to Python 2.7, but Python 3. Maybe a similar fix would work now.

Ok, we'll try this solution and will inform you of the result as soon as possible. But we've been using the VS command line, not PowerShell or cmd.

**Comment by WickWeiWkSpace** [comment]
Hi all，
We have tried the fix you provided and found that test_sys can pass successfully. Thank you very much！

**Comment by iritkatriel** [comment]
> The fix from #69889 was applied to Python 2.7, but not Python 3. Maybe a similar fix would work now.

Do we need to apply it on main branch?
CC  @serhiy-storchaka .

**Comment by serhiy-storchaka** [comment]
It is Windows-only issue. No need to apply it on other platforms.

As for Windows, what is the type of `sys.__stdout__.buffer` and `sys.__stderr__.buffer`? Also, what is returned by `sys.__stdout__.isatty()` and `sys.__stderr__.isatty()`?

Try to run the test with redirecting only stdout or only stderr like in #69889. On windows it should be something like:
```
python.bat -m test.regrtest -v test_sys -m test_43581 | type
python.bat -m test.regrtest -v test_sys -m test_43581 2>&1
```

**Comment by StanFromIreland** [comment]
Seeing as Serhiy's questions haven't been answered for 3 years, I'm closing as stale.
