### ISSUE TITLE
`test_handling_bad_descriptor` fails on macos 10.14

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#98829]
I am trying to run `test_pathlib` locally on my machine. One test fails:

```
» ./python.exe -m test -v test_pathlib -m test_handling_bad_descriptor
== CPython 3.12.0a1+ (heads/main:b27b57c6e4, Oct 28 2022, 20:34:51) [Clang 11.0.0 (clang-1100.0.33.16)]
== macOS-10.14.6-x86_64-i386-64bit little-endian
== cwd: /Users/sobolev/Desktop/cpython/build/test_python_5120æ
== CPU count: 4
== encodings: locale=UTF-8, FS=utf-8
0:00:00 load avg: 1.86 Run tests sequentially
0:00:00 load avg: 1.86 [1/1] test_pathlib
test_handling_bad_descriptor (test.test_pathlib.PosixPathTest.test_handling_bad_descriptor) ... ERROR

======================================================================
ERROR: test_handling_bad_descriptor (test.test_pathlib.PosixPathTest.test_handling_bad_descriptor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_pathlib.py", line 2869, in test_handling_bad_descriptor
    file_descriptors = list(pathlib.Path('/dev/fd').rglob("*"))[3:]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython/Lib/pathlib.py", line 894, in rglob
    for p in selector.select_from(self):
  File "/Users/sobolev/Desktop/cpython/Lib/pathlib.py", line 334, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "/Users/sobolev/Desktop/cpython/Lib/pathlib.py", line 279, in _select_from
    with scandir(parent_path) as scandir_it:
         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython/Lib/pathlib.py", line 864, in _scandir
    return os.scandir(self)
           ^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/dev/fd/36'

----------------------------------------------------------------------
Ran 1 test in 0.015s
```

Here's how it is defined:

https://github.com/python/cpython/blob/7ee3aca00a0dffc9cb5906a24005a8c61d5bce14/Lib/test/test_pathlib.py#L2865-L2886

My macos version: 10.14.x
Python is built with: `./configure --with-pydebug && make`

Looks like something is off, I will try to investigate and send a PR.

**Comment by sobolevn** [comment]
This is not just about tests:

```
» ./python.exe                                                        
Python 3.12.0a1+ (heads/main:7ea10567af, Oct 29 2022, 13:15:59) [Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib
>>> list(pathlib.Path('/dev/fd').rglob("*"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sobolev/Desktop/cpython/Lib/pathlib.py", line 912, in rglob
    for p in selector.select_from(self):
  File "/Users/sobolev/Desktop/cpython/Lib/pathlib.py", line 334, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "/Users/sobolev/Desktop/cpython/Lib/pathlib.py", line 279, in _select_from
    with scandir(parent_path) as scandir_it:
         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython/Lib/pathlib.py", line 882, in _scandir
    return os.scandir(self)
           ^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/dev/fd/36'
```

It fails in runtime too.

**Comment by sobolevn** [comment]
Original PR: https://github.com/python/cpython/pull/8542

**Comment by sobolevn** [comment]
My tree results:

```
» tree /dev/fd
/dev/fd
├── 0
├── 1
├── 2
├── 25
├── 27
├── 28
├── 29
├── 3
├── 30
├── 31
├── 32
├── 33
├── 34
├── 36 [error opening dir]
├── 37 [error opening dir]
├── 38
├── 39
├── 4
├── 40
├── 41
├── 42
├── 44
├── 45
├── 46
├── 47
├── 48
├── 49
├── 5 [error opening dir]
├── 50
├── 51
├── 52
├── 53
├── 54
├── 55
├── 62
├── 63
├── 64
├── 65
├── 66
└── 73
```

**Comment by sobolevn** [comment]
Looks like this is specific to my machine. I cannot reproduce it on my other mac.
