### ISSUE TITLE
`traceback.walk_stack(None)` yields frames from higher in the stack on 3.11

### ISSUE THREAD

**Issue by graingert** [python/cpython#99013]
eg:

```
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import traceback
>>> list(traceback.walk_stack(None))
[]
>>> 
```

```
Python 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:18:27) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> list(traceback.walk_stack(None))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/graingert/anaconda3/envs/dask-distributed-311/lib/python3.11/traceback.py", line 332, in walk_stack
    f = sys._getframe().f_back.f_back.f_back.f_back
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'f_back'
>>> 
```

_Originally posted by @graingert in https://github.com/python/cpython/pull/26958#discussion_r1012036670_

**Comment by ammaraskar** [comment]
I believe this is the same as https://github.com/python/cpython/issues/96092, I don't currently have time to triage this but this should be a relatively simple fix + test for regression

**Comment by graingert** [comment]
duplicate of https://github.com/python/cpython/issues/96092
