### ISSUE TITLE
`inspect.getmembers_static` triggers `__getattribute__`

### ISSUE THREAD

**Issue by gschaffner** [python/cpython#99673]
# Bug report

`inspect.getmembers_static` is documented as not triggering `__getattribute__`, but it can trigger it via `dir`. For example the following hits the recursion limit:

```python
class A:
    def __getattribute__(self, name: str) -> Any:
        getmembers_static(self)
        return "all attrs exist!"

A().anything
```

(A workaround for examples like this one is to add the base cases required by `dir` to `__getattribute__`:

```python
if name in ("__dict__", "__class__"):
    return object.__getattribute__(self, name)
```

(The `__dict__` case is not always needed depending on the `__dir__` implementation.))

Switching `getmembers_static` to use `dir_static` (gh-55979) would fix this problem, I believe. `getmembers_static` already documents that it can't find the dynamically created attributes, etc. that `getattr_static` can't find, so I don't think such a change would be breaking.

# Your environment

- CPython versions tested on: 3.11.0
- Operating system and architecture: Linux-based, x86_64

**Comment by sobolevn** [comment]
I would simplify your example a bit:

```python
>>> from inspect import getmembers_static
>>> class A:
...    def __getattribute__(self, attr):
...        raise RuntimeError('Nope', attr)
... 
>>> getmembers_static(A())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sobolev/Desktop/cpython/Lib/inspect.py", line 594, in getmembers_static
    return _getmembers(object, predicate, getattr_static)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython/Lib/inspect.py", line 538, in _getmembers
    names = dir(object)
            ^^^^^^^^^^^
  File "<stdin>", line 3, in __getattribute__
RuntimeError: ('Nope', '__dict__')
```

It indeed contradicts its docs:

> Return all members of an object as (name, value) pairs sorted by name
>    without triggering dynamic lookup via the descriptor protocol,
>    `__getattr__` or `__getattribute__`
