### ISSUE TITLE
repl buffering conflicts with sys.stdin

### ISSUE THREAD

**Issue by allisonkarlitskaya** [python/cpython#99751]
# Bug report

When running the interpreter (`python -i`) the REPL appears to implement its own buffering, independent of `sys.stdin` and its internal buffer.

Consider the following (working) example, manually entered into the REPL via the keyboard:

```
$ python3 -i
Python 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print('hello', sys.stdin.readline())
world
hello world

>>>
```

This appears to work only because at the time I hit `<enter>` after the `print()` line, the `world` isn't available to read yet, and therefore the repl can't possibly consume it.  If I put the whole thing into a file, and `cat` it in one go, however:

```
$ cat example.py 
import sys
print('hello', sys.stdin.readline())
world

$ cat example.py | python3 -i                                          ST 12   peer 
Python 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> hello 
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'world' is not defined
>>> >>> 
```

We can see that `readline()` returns nothing at all, because `world` has already been consumed by the repl, which attempts (and fails) to interpret it as the next command to be executed.

You can work around this issue by inserting even the tiniest of pauses.  Consider:

```
$ cat example.py
import sys
print('hello', sys.stdin.readline())
```

```
$ (cat example.py; echo world) | python3 -i
Python 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> hello 
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'world' is not defined
>>> 
```
(ie: broken)

but:
```
$ (cat example.py; sleep 0.1; echo world) | python3 -i
Python 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> hello world
```

(ie: working).

# Your environment

Stock `python3-3.11.0-1.fc37.x86_64` package installed on Fedora 37.

**Comment by rruuaanng** [comment]
> # Bug report
> 
> When running the interpreter (`python -i`) the REPL appears to implement its own buffering, independent of `sys.stdin` and its internal buffer.
> 
> Consider the following (working) example, manually entered into the REPL via the keyboard:
> 
> ```
> $ python3 -i
> Python 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import sys
> >>> print('hello', sys.stdin.readline())
> world
> hello world
> 
> >>>
> ```
> 
> This appears to work only because at the time I hit `<enter>` after the `print()` line, the `world` isn't available to read yet, and therefore the repl can't possibly consume it. If I put the whole thing into a file, and `cat` it in one go, however:
> 
> ```
> $ cat example.py 
> import sys
> print('hello', sys.stdin.readline())
> world
> 
> $ cat example.py | python3 -i                                          ST 12   peer 
> Python 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> >>> hello 
> >>> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'world' is not defined
> >>> >>> 
> ```
> 
> We can see that `readline()` returns nothing at all, because `world` has already been consumed by the repl, which attempts (and fails) to interpret it as the next command to be executed.
> 
> You can work around this issue by inserting even the tiniest of pauses. Consider:
> 
> ```
> $ cat example.py
> import sys
> print('hello', sys.stdin.readline())
> ```
> 
> ```
> $ (cat example.py; echo world) | python3 -i
> Python 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> >>> hello 
> >>> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'world' is not defined
> >>> 
> ```
> 
> (ie: broken)
> 
> but:
> 
> ```
> $ (cat example.py; sleep 0.1; echo world) | python3 -i
> Python 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> >>> hello world
> ```
> 
> (ie: working).
> # Your environment
> 
> Stock `python3-3.11.0-1.fc37.x86_64` package installed on Fedora 37.

This behavior seems correct because repl reads files by parsing and executing them line by line, rather than treating unknown symbols as standard input.

**Comment by ayjayt** [comment]
@rruuaanng but why would the pause then change how its interpreted? is that appropriate? Or should an EOF character or some other character or maybe a function or keyword tell the interpreter that further standard input should be interpreted as stdin for the program.

I generally agree one file or one string or one-file-like-thing should be interpreted as program, not as stdin, but then it would be nice to have a way to also pipe in stdin next to it, maybe on a different file descriptor.
