### ISSUE TITLE
Crypt errors with valid hashing algorithms

### ISSUE THREAD

**Issue by Shane-Braswell** [python/cpython#99854]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/crypt.py", line 117, in <module>
    _add_method('MD5', '1', 8, 34)
  File "/usr/local/lib/python3.10/crypt.py", line 94, in _add_method
    result = crypt('', salt)
  File "/usr/local/lib/python3.10/crypt.py", line 82, in crypt
    return _crypt.crypt(word, salt)
PermissionError: [Errno 1] Operation not permitted
```
Allow usage of crypt when at least one hashing algorithm is supported. E.g. when FIPS is enabled then MD5 isn't supported but other algorithms are.

### Linked PRs
* gh-99855

**Comment by Shane-Braswell** [comment]
Closing - crypt is deprecated
